### ISSUE TITLE
Histogram/bar charts aren't being correctly sized on the x-axis

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10054]
This is on our stats instance. It seems like Bar charts that are grouped by a binned numeric dimension (aka histograms) are doing something funny where the last bar is narrower than the others and is hanging off the right-side margin:

![image](https://user-images.githubusercontent.com/2223916/58499656-79e7e080-8135-11e9-9400-a439193d905f.png)

![image](https://user-images.githubusercontent.com/2223916/58499723-9552eb80-8135-11e9-9f9d-8970207a2764.png)

**Comment by paulrosenzweig** [comment]
It seems like this is because we're using an ordinal x-axis and then manipulating the bars directly.

We start with a chart that looks like this and then apply some transformations:
![image](https://user-images.githubusercontent.com/691495/58571196-45445980-8207-11e9-9da3-8af618ba274f.png)

We then:
* Stretch the bars to have a 1px gap
* Translate the chart 0.5 bar widths to the right
* Remove padding outside the bars

I'm likely missing some of the history, but it seems like we could use a quantitative x-axis instead? Have we run into issues going down that path?

**Comment by paulrosenzweig** [comment]
cc @tlrobinson for input on that ☝️
