### ISSUE TITLE
Restart SSH Tunnel if connection goes away

### ISSUE THREAD

**Issue by pulponair** [metabase/metabase#10081]
**Problem:** 
If you connect to a database using a SSH Tunnel aka SSH "Bastion Host"  Metabase ends up in "Broken Pipe" and/or "Connections could not be acquired from the underlying database!" when the remote host ends the SSH connections (usually caused by the lack of keep alive packages)

**Solution:**
1. Check the connection tunnel state before firering a query or a db connection and reestablish it if it is gone.

2. Add the possibility to specify ServerAliveInterval and ServerAliveCountMax and/or set at least some  stable defaults e.g. 120/15

3. Until this has been implemented one can add openssh to the container and open tunnels withing the dockerfile which gives one full controll over ssh settings:
`apk add openssh`
`echo "ServerAliveInterval 120" >> ~/.ssh/config`
`echo "ServerAliveCountMax 15" >> ~/.ssh/config`
`ssh -f -N remoteuser@remoteserver -L 12345:mysqlserver.foo:3306`

To make supersure one also might want to install autossh and let it take care of the ssh tunnels.

**Comment by pulponair** [comment]
Another hint:
com.jcraft.jsch.JSch is able to parse ~/.ssh/config style format see:
http://www.jcraft.com/jsch/examples/OpenSSHConfig.java.html

So a pretty flexible implementation would be to just add a text field to the ssh configuration and let people define what ever they want in there or even better use keys and config of the metabase user.

**Comment by dpsutton** [comment]
Updates about this:
- Have added a heartbeat to the ssh tunnel so it will hopefully not close due to idleness going forward. https://github.com/metabase/metabase/blob/master/src/metabase/util/ssh.clj#L57-L59
- Associated issue to make this configurable per ssh tunnel https://github.com/metabase/metabase/issues/13399
- the ssh tunnel needs some work to handle disconnections. Need to think about the best way to handle this but hopefully these improvements can help out in the meantime.
