### ISSUE TITLE
Sand box not working on custom question

### ISSUE THREAD

**Issue by nooberfsh** [metabase/metabase#10152]
## Env:
- Browser version: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- OS: macOS Mojave version 10.14
- DB: H2
- Metabase version: v1.1.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

## Description
- create group `customer`
- create user `tom` with attribute `user_id=10` and put this user into the `customer` group
- create a `custom question` 
```sql
select id, address, email, name 
from PEOPLE
where id = {{cid}}
```
- grant sandbox access to table `people` for group `customer` and select the `question` I create and choose variable to `cid` and user attribute to `user_id`
- Log in as a test user and open the `question`:
 > Unable to substitute 'cid': param not specified. Found: ("cid")

**Comment by mazameli** [comment]
To do what I believe you're trying to do, you need to do two things:

1. In the sandbox settings for your `people` table, use the second radio option, `use a saved question to create a custom view for this table`, and select your `question`. Map the user attribute to your `cid` variable as before.

2. Then, instead of opening your `question`, your `tom` user should instead try browsing to and viewing the `people` table. What will happen is that when they go to view that table, they will instead be shown your `question` with their user attribute correctly substituted.

**Comment by flamber** [comment]
A lot has changed since and there's now better documentation:
https://www.metabase.com/learn/permissions/data-sandboxing-row-permissions.html
https://www.metabase.com/learn/permissions/data-sandboxing-column-permissions.html
