### ISSUE TITLE
downloads for Mac 404

### ISSUE THREAD

**Issue by jagg19** [metabase/metabase#10241]
**Describe the bug**
Can't download metabase for Mac, 404 errors occur. I tried to download directly from the website with this link https://metabase.com/start/mac.html and also using homebrew. All versions for Mac.

**To Reproduce**
1. Go to 'https://metabase.com/start/mac.html'
2. Click on 'Download metabase for mac'
3. See 404 error

**Expected behavior**
It downloads.

**Screenshots**

![Screen Shot 2019-06-21 at 4 18 37 PM](https://user-images.githubusercontent.com/43685717/59949141-3fc1e400-9440-11e9-841e-b89699e26a60.png)

![Screen Shot 2019-06-21 at 4 19 22 PM](https://user-images.githubusercontent.com/43685717/59949179-5a945880-9440-11e9-81c0-e73298d86845.png)

**Information about your Metabase Installation:**
- Safari Version 12.1

- Mac OS Mojave

- All versions

- Mac App

**Severity**
Blocking usage of metabase for Mac entirely.

**Comment by flamber** [comment]
Hi @jagg19 
While it looks like there was a glitch in all downloads.metabase.com (it also failed for me), but while I was investigating it started to work again, so I'm not sure if it was a problem with the S3 storage.
Is it working for you again?
It looks like you're trying to download 0.32.2 instead of the latest 0.32.9 - is that on purpose?

**Comment by ogeagla** [comment]
I pushed a configuration issue which caused downloads to fail during that window.  Sorry about that, all should be well again, but lmk if issues persist.

**Comment by jagg19** [comment]
@ogeagla Yes all works fine!!! @flamber I was trying to download multiple versions to see if it was across the board. But all is well now, thanks!
