### ISSUE TITLE
"?" char in literals inside parameterized SQL queries can breaks for PrestoDB/BigQuery

### ISSUE THREAD

**Issue by thomasLeclaire** [metabase/metabase#10257]
**Describe the bug**
I create a custom query with one metabase filter variable.
I define this request :
```
SELECT 
CASE
when ({{metabase_filter}} like 'a') THEN '?blabla'
when ({{metabase_filter}} like 'b') THEN true
end
```

but presto receives this one : 
```
SELECT
CASE
when ('metabase_filter_value' like 'a') THEN ''metabase_filter_value'blabla'
when (? like 'b') THEN true
end

```
which is invalid due to the multiple quotes and second variable item not replaced as expected.
**Expected behavior**
the asking point "?" should not be replaced by the filter but directly provided to presto.

**Information about your Metabase Installation:**
metabase

**Severity**
prevent to use regexp features of prestoDB

**Comment by camsaul** [comment]
So this is a bug with our code that converts the parameterized SQL statements we generate back to unparameterized ones for databases like Presto whose JDBC drivers don't support them 

Specifically [this code here](https://github.com/metabase/metabase/blob/master/src/metabase/driver/sql/util/unprepare.clj#L76) just looks for and `?`s in the SQL and assumes they're placeholders and replaces them with parameters. According to the SQL standard, `?`s inside literals (such as the string literal in your example), should not be interpreted as parameter placeholders.

I think we should probably just avoid generating parameterized SQL in the first place so we don't have to worry about splicing parameters back into the SQL

**Comment by lukeman** [comment]
As @camsaul noted was likely above, this does affect BigQuery (as of the v0.34.2 release). Any native SQL that uses variables throws positional param errors if you use something like `REGEXP_EXTRACT` with a pattern that includes `?`.

Contrived example (fails if you specify a value for the variable):
```
SELECT
  REGEXP_EXTRACT('Foo Storage Bar (Baz)', r" Storage (\w+(?:\s{1}[\w]+)*)"),
  {{ any_var }}
```
<img width="921" alt="Screen Shot 2020-02-24 at 3 55 48 PM" src="https://user-images.githubusercontent.com/13008/75190479-68f8e980-571e-11ea-8c35-3dd4c7574e6b.png">

**Comment by rashad** [comment]
Did anyone find a (even dirty) solution to this issue?

**Comment by lukeman** [comment]
@rashad Since Metabase doesn't always play well with complex BigQuery types I usually work with a view that already does a number of convenience things to extract particular nested values into discrete fields. For this case I was able to leverage that and just added the regex fields that I needed onto the view. Basically anything you can do to get the `?` out of your query text is enough, so another option might be a custom UDF that you can call from your parameterized queries.

Of course the issue goes away if you don't use params, so I usually just hard-code those things when I need to write some regex in a pinch.

**Comment by rashad** [comment]
Dope Thanks a lot @lukeman for your advice 🙏 

For those looking into a solution, I've found a very nice BigQuery feature in the documentation where one can **declare a variable and even set a default value**. Those variables can then be used in the query with no risk of messing up. All you need is to define those variables at the beginning of your query.

Here's [the doc](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting#declare) about scripting (declare, set variables and much more...)

Combining this approach with Metabase's query parameter you get something like
```
DECLARE search STRING;
DECLARE author STRING;
SET search = {{ search }};
[[ SET author = {{ author }}; ]]

SELECT ARRAY_LENGTH(REGEXP_EXTRACT_ALL(docs, r'(?im)\W' || search)) AS search_match,
where REGEXP_CONTAINS(name, r'(?i)^'|| author || '$')
```

Hope that helps and don't hesitate if I can help!
Cheers from France 👋 🇫🇷

**Comment by lukeman** [comment]
@rashad Wow, I'd never considered that using `DECLARE` would work around this issue. Thanks so much for sharing.

**Comment by camsaul** [comment]
Not sure if this still affects BigQuery or not since we switched to the newly-supported parameterized SQL fairly recently.

To fix this the right way we need to avoid generating parameterized SQL in the first place for Presto and other databases that don't support parameterized SQL. Then we can remove the parameter splicing logic that is causing the problems we're seeing.

I think we could possibly accomplish this by overriding `->honeysql` for the drivers in question for various types of literals (e.g. strings and temporal values) to generate non-parameterized SQL

**Comment by camsaul** [comment]
For example right now an MBQL query like 

```clojure
{:filter [:= [:field-id 1] "Cam"]}
```

compiles to HoneySQL like

```clojure
{:where [:= :first_name "Cam"]}
```

which in turn compiles to SQL like

```sql
WHERE first_name = ?
```

(`Cam` passed in separately as a parameter).

Since Presto doesn't support parameterized SQL we then splice the parameter back in to get

```sql
WHERE first_name = 'Cam'
```

(there is some escaping done as well during splicing to prevent SQL injection).

So the fix is to override `->honeysql` and do the splicing directly so we can skip the intermediate step. A series of method impls like this

```clojure
(defmethod sql.qp/->honeysql [:presto String]
  [_ s]
  (hx/literal (escape-string s)))
```

and removing the calls to `unpreprare/unprepare` in the drivers in the `execute-query` methods should do the trick.

**Comment by jeff303** [comment]
I wonder if the changes in #14883 (coming in 0.39) would fix this?

**Comment by lukeman** [comment]
I noticed that today on v0.39.1 (likely due to #14883 as Jeff mentioned above) I am able to use non-capturing groups in a BigQuery regex now, which was the original case that bit me with queries containing question marks.

So at least using the case I provided earlier in the thread, BigQuery does seem to be fixed as of v0.39.

**Comment by camsaul** [comment]
#14883 might fix this for native queries... for JDBC-based drivers. However, Presto and BigQuery don't use JDBC (at least not yet for Presto). This is likely related to our "unprepare" parameter-splicing behavior we use for these queries... basically we generate parameterized SQL like `["SELECT * FROM table WHERE field = ?" "some'value'"]` and then since Presto and BigQuery aren't JDBC-based we splice the parameter values back in after escaping them e.g. `SELECT * FROM table WHERE field = 'some''value'`. 

The right fix would be to toss out the "unprepare" stuff entirely and just hack HoneySQL to output `WHERE field = 'some''value'` directly. We can also maybe use that for the "convert to SQL" stuff we support.

Rating this as hard because the proper fix would require some refactoring and knowledge of HoneySQL internals

**Comment by jeff303** [comment]
I believe that new drivers for Presto (#16194) and BigQuery (#16746) should take care of this, once they are available.

**Comment by flamber** [comment]
I cannot reproduce with the new drivers of Presto nor BigQuery on 0.41.2

**Comment by thomasLeclaire** [comment]
Sounds still not working for my use case : using the last 0.41.2 version : 

`SELECT 
CASE
when ({{metabase_filter}} like 'a') THEN '?blabla'
when ({{metabase_filter}} like 'b') THEN true
end`

with metabase_filter to "aa"

result on presto side in : 

`SELECT
CASE
when (from_utf8(from_hex('6161')) like 'a') THEN 'from_utf8(from_hex('6161'))blabla'
when (? like 'b') THEN true
end`

**Comment by flamber** [comment]
@thomasLeclaire Post "Diagnostic Info" from Admin > Troubleshooting. Sounds like you are not using the new driver, which you can change in Admin > Databases > (your-db).

**Comment by thomasLeclaire** [comment]
ahhh I thought it was a direct update! didn't checked the db config but ok, using the new driver it's perfectly working ! 🥳  thx!!

**Comment by mayanala-coxauto** [comment]
Hi, is this issue resolved in latest version ? We still see the issue ? Here is the our environment details. 

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.273-207.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.12"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-05",
      "tag": "v0.47.11",
      "branch": "?",
      "hash": "51935b1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
