### ISSUE TITLE
Cannot see remove and edit icons in the table options visible columns section if name is too long

### ISSUE THREAD

**Issue by kieranklaassen** [metabase/metabase#10286]
**Describe the bug**
Cannot see remove and edit icons in the table options visible columns section if name is too long

**To Reproduce**
1. Go to 'Change visualization'
2. Click on 'Table'
3. Scroll down to 'Visible columns'
4. When the name is too long it is not clickable

**Expected behavior**

**Screenshots**

<img width="377" alt="Question_·_Metabase" src="https://user-images.githubusercontent.com/209089/60531233-1fa3e780-9cc0-11e9-9af5-a4303a2900e8.png">

**Comment by flamber** [comment]
Hi @kieranklaassen 
Which version of Metabase?
There's several places, where long names causes some issues. There's a proposed fix for some of those - PR #9711
As a work-around, you can rename the field to something shorter:
Admin > Data Model > (database) > (table) > (column) :gear:

**Comment by kieranklaassen** [comment]
I'm on `version v0.33.0-preview`

**Comment by mazameli** [comment]
Just a note: @flamber attempted to solve this in #9711, but ultimately reverted [this commit](https://github.com/metabase/metabase/commit/224ce016817679ef31bde2a2f5c46902cfedefb1) before merging because something about it was causing a [test failure](https://circleci.com/gh/metabase/metabase/77954) that he didn't understand. 

If someone from our @metabase/core-developers wants to take a look at why that test was failing, then we could just open a quick PR that basically does what @flamber already did in that commit.

**Comment by flamber** [comment]
I don't remember when it was fixed, but it's a few versions ago. This is 0.35.4:
![image](https://user-images.githubusercontent.com/1447303/83420911-9513bd00-a427-11ea-80a3-a364edef9599.png)
