### ISSUE TITLE
sum-where syntax

### ISSUE THREAD

**Issue by kurumpa** [metabase/metabase#10290]
Hello,
Can you please give me a hint, is there any thoughts about `sum-where` and `count-where` syntax when used in custom expressions? Will `filter-clause` look like a second argument for `Sum()` or maybe SQL-like syntax `Sum(CASE a>100 THEN a ELSE 0 END)`? Just wondering in case i'll have time to extend/upgrade Chevrotain rules for that. Thanks.

**Comment by salsakran** [comment]
paging @sbelak

**Comment by sbelak** [comment]
These new MBQL ops are not supported in custom expressions yet.

**Comment by mazameli** [comment]
@metabase/core-developers What do we think the syntax should be for `sum-where` or `count-if` expressions? (And another other conditional aggregation functions we might add, like `averageif` etc.)

To tip my hand, my bias is to have the syntax be more similar to Excel, Numbers, Google Sheets, etc., as I view the Custom/notebook editor to be a bridge for folks who are familiar with tools like those, but who aren't really comfortable with SQL (otherwise they'd just be using the SQL editor).

It seems there are a few sensible directions to go in:

## Direction A: make it [like spreadsheet programs](https://support.google.com/docs/answer/3093583?hl=en)

Spreadsheet programs treat `sumif` and `countif` as separate functions from `sum` and `count`. For `sumif`, you specify the column to sum and the condition that rows in that column must meet in order to be included in the aggregation. A third parameter can be used to specify a different column for the condition to be applied to instead of the column to be summed.

For `countif`, you'd specify the column to compare to the conditional, then the conditional.

**Pattern:**
`sumif(column_to_sum, condition, optional_column_for_the_condition_to_apply_to)`
`countif(column_to_check, condition)`

**Examples:**
`sumif(subtotal, >= 100)`
`sumif(sessions, "Twitter", source)`
`countif(state, "CA")`

### Direction B: allow additional arguments in existing functions
This seems like a slight distinction from direction A to me, which would just let you write e.g. `sum(subtotal, >=100)` or `count(state, "CA")` instead of there being distinct `sumif()` and `countif()` functions. 

I'm guessing there are implementation trade-offs between direction A vs. B, but again I'm biased towards direction A because that's what every spreadsheet app does.

## Direction C: make it like SQL syntax
I'm not knowledgeable about this kind of syntax, but I'd assume it would be basically like @kurumpa wrote:
`Sum(CASE a>100 THEN a ELSE 0 END)`
`Count(CASE Position WHEN 'Manager' THEN 1 ELSE null END)`

**Comment by flamber** [comment]
:+1: on Direction A, but it would probably be more difficult to build, but would give greater control.
As for Direction C, that sounds a lot like #6331.

**Comment by mazameli** [comment]
Something else I'm realizing that `sumif` and `countif` would let you do is period-over-period comparisons. E.g., you could have a notebook query like so (pseudocode)…

`sumif(subtotal, created_at:year = 2019)`, `sumif(subtotal, created_at:year = 2018)`
`Group by Created At: Month of Year`

…and you'd then have 2019 vs. 2018 revenue per month.

**Comment by sbelak** [comment]
True, but you could also do the same by grouping by month of year, and year separately (which you can't currently do in QB as you can't group multiple times on the same col ... which is something we should look into).

**Comment by lindsay-stevens** [comment]
For Postgres and SQLite there's also `count(*) filter (where <cond>)` which could be a way to re-use existing MBQL stuff from `where`. Ref: https://modern-sql.com/feature/filter

**Comment by sbelak** [comment]
We've now exposed `sumif`, `countif` and a slew of other functions via #11868
