### ISSUE TITLE
Tables are slow to render in Firefox when scrolling

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10339]
This is present in both master as well as in the new notebook-mode branch.

![firefox-table-scrolling](https://user-images.githubusercontent.com/2223916/61163184-7b8d1e00-a4c1-11e9-9ae0-5e42cae62ead.gif)

**Comment by ariya** [comment]
Steps:
1. Ask a question, Simple question
2. Sample Dataset, _Reviews_ table
3. Scroll vertically

With Firefox's profiler (Developer Tools' Performance tab), I can spot a few cases where the handler for the scroll event takes too long. Here's one > 100 ms. Notionly, this contributes to the poor scrolling experience. The profiler shows an average framerate of 22.10 fps, with the minimum as low as 2.76 fps.

![image](https://user-images.githubusercontent.com/7288/106800601-849a8e80-6615-11eb-992f-00b305d866db.png)


Meanwhile, running the same query with Chrome doesn't exhibit the same situation, scroll event's handler is consistently below 30 ms.

Tested with Metabase v0.38.0-rc4 (commit 6312927a) on Debian 10 in a VM (2 CPUs, execution capped at 50%).

**Comment by uladzimirdev** [comment]
The problem appeared across different browsers, @ranquild already merged several fixes and moved cell actions calculations to event handlers instead of rendering

check https://github.com/metabase/metabase/pull/35148, https://github.com/metabase/metabase/pull/33831 and https://github.com/metabase/metabase/pull/33908, https://github.com/metabase/metabase/pull/34037
