### ISSUE TITLE
Collections archive incorrectly listing tables

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10439]
As [mentioned](https://github.com/metabase/metabase/pull/10429#issuecomment-516657176) by @flamber, https://github.com/metabase/metabase/pull/10429 seems to have introduced a bug where tables are appearing in the collections archive page, `/archive`:

![image](https://user-images.githubusercontent.com/2223916/62244319-06ac5600-b394-11e9-8f88-838f08fb8637.png)

To quote Flamber:
`Clicking [the trash icon] just results in following log: DELETE /api/table/1 404 1 ms (0 DB calls) "API endpoint does not exist."`

**Comment by walterl** [comment]
The same error occurs for each selected table, when selecting one or more tables and clicking _Delete_ in the toolbar at the bottom of the page.

I guess the biggest question is: should archived tables be deletable? If so, this seems like a simple case of adding the `DELETE /api/table/:id` API endpoint.

**Comment by flamber** [comment]
@walterl I'm fairly sure tables shouldn't be displayed at all, since tables can't be archived - and I don't think delete is supported at all, since if you remove a table from the physical database, then it's just hidden in Metabase (something to do with how sync works, if I'm understanding the logic correctly)

**Comment by walterl** [comment]
@flamber That makes sense, thanks :+1:
