### ISSUE TITLE
Trying to add columns from an already-joined, FK-linked table results in error

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10444]
If I join e.g. Products to Orders, if I open up the table visualization settings, I still see all the columns in Products listed as columns that I could add. If I try to add one, I get:

```
value does not match schema: {:query {:fields (named (not ("distinct" a-clojure.lang.PersistentVector)) "Distinct, non-empty sequence of Field clauses")}}
```

![image](https://user-images.githubusercontent.com/2223916/62248921-1d57aa80-b39e-11e9-98bc-00d21e062ad9.png)

It seems like I should not see any of the FK-linked columns listed in the chart settings pane, except for columns that I excluded in the join step in the notebook.

**Comment by camsaul** [comment]
This only happens if you add a a Field that is already part of the results. In the example above, if you join `Orders + Products`, then all of the columns for both `Orders` and `Columns` are already in the results; however, all the columns in `Products` appear in the "more columns" list in the visualization settings. Adding a column from a third table, such as `People`, works as expected. When adding a column already in the results, i.e. a `Products` column, the QP code returns an invalid query error because you've included the same Field more than once in `:fields`, which is expected behavior.

The root cause of the problem here IMO is that we should not be listing columns that are already present in the results in "more columns".

**Comment by mazameli** [comment]
> It makes no sense to for columns already in the results to be in the list of columns you can add to the results.

Yep, agreed. That's what I meant here:

`It seems like I should not see any of the FK-linked columns listed in the chart settings pane, except for columns that I excluded in the join step in the notebook.`

…but to be more correct, I should have said that fk-linked columns that have already been included via an explicit join should be listed in the "visible columns" section, but not in the "more columns" section.

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/10592
