### ISSUE TITLE
Improve UX when attempting to join data from a different DB

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10440]
Currently in the notebook you can select a saved question based on data from a database different from the currently selected one, but it results in an error if you attempt to preview the results:

![image](https://user-images.githubusercontent.com/2223916/62245930-7a039700-b397-11e9-8900-239026b7f523.png)

Ideally we should filter out the selectable saved questions to only include ones that are based on the same database.

Falling short of that, we should provide a nicer-looking warning message.

**Comment by mazameli** [comment]
@tlrobinson Will it be feasible to solve this by filtering out saved questions that are from a database different from the current working data? We really shouldn't let users make selections that we know won't work.

**Comment by tlrobinson** [comment]
This is essentially the same problem as not being able to nest/join/etc when starting a question based on the "Saved Question" fake database: the frontend doesn't know which underlying database each saved question belongs to.

We may be able to fix this by having `/api/database?include_tables=true&include_cards=true` return the actual database ID instead of `db_id: -1337`:

![Screenshot 2019-08-05 17 16 53](https://user-images.githubusercontent.com/18193/62502545-dd7d3280-b7a4-11e9-8342-5e52cdc95b0b.png)

@camsaul how hard would it be to switch `db_id` to the actual DB?

**Comment by tlrobinson** [comment]
@camsaul I think I've found where in the code this needs to change (`card->virtual-table`), I'll give it a try. I'm not sure if there will be an side effects of changing it though.

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/10506
