### ISSUE TITLE
standardize z-index usage with z-index lib

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1047]
this is a reminder for me to take a look at where we're using z-index and standardize it based on https://github.com/kdoh/z-index

**Comment by tlrobinson** [comment]
I think the `z#` classes are nice if you're using them within a single component (e.x. if we were able to apply them all in `App.jsx`, or within something like NavDropdown), but when they're spread across multiple components I feel like it doesn't help much with ensuring they're used correctly. I think it would most useful to enumerate the "top level" z-indexes in one place.

Here are all the components in the "root" stacking context that use z-indexes:

* `Nav`: `z-index: 4`
  * (note NavDropdown is currently not a popover so z-index of Nav affects it)
* Modals:
  * `HeaderModal` `z-index: 4` (needs to appear on top of `Nav`)
  * `WindowModal` (our "traditional" modal in a window, with the rest of the app blurred)  `z-index: 4`
  * `FullPageModal` (fills content, doesn't overlap Nav)  `z-index: 3` so the nav dropdowns appear on top
* `UndoListing`: `z-index: 99` because why not?
* `OnClickOutsideWrapper`: sets parent element z-index to auto-incrementing z-index starting at 3, because I'm not sure why

Also, some of these are likely only being z-indexed correctly because of their relative order in the DOM, e.x. everything with `z-index: 4` (but maybe that's ok?)
