### ISSUE TITLE
Add ability to use joins when starting data is a saved question

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10491]
0.33 will add the ability to join _to_ a saved question, but currently there's a limitation where you can't use joins if your _starting data_ is a saved question. 

This won't be a 0.33 feature, but maybe 0.34 or 0.35?

**Comment by RMMSecurity** [comment]
I agree, it makes sense to add this in not only for consistently, but also usability. As much as I'd like to make my own views everywhere sometimes it's just far easier to let people create their own saved questions and go from there. 

That's how they were naturally using it. Based on all the work that's been done it doesn't seem terribly hard to add.

**Comment by salsakran** [comment]
It's a bit more complicated than it looks because
1. Our current organization of all saved questions being in a fake database breaks a couple things, namely that we don't do cross-db joins. 
2. Having every question ever be a starting point is a pain organizationally and we're going to be changing how we expose them 
3. We don't have a clear design for 2, and don't want to hold up an already huge release with additional scope.

**Comment by RMMSecurity** [comment]
Makes sense, thanks for taking the time to explain it @salsakran 

I like the solution @tlrobinson came up with in #10506 . You might be able to add in serialization for alerts based on saved questions if that was the blocker.

**Comment by mazameli** [comment]
This was fixed by #10506. It also addressed item 1 that @salsakran listed.

The second item @salsakran listed I think is pretty well covered by https://github.com/metabase/metabase/issues/10163.

Closing this issue.
