### ISSUE TITLE
No feedback when clicking "Bring the sample dataset back" in /admin/databases

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10514]
If you delete the sample dataset DB, then click the button to add it back, it SEEMS like nothing is happening. But if you look in the logs it is actually hitting the API endpoint. We should add some sort of confirmation dialog that lets you user know it's being re-enabled

**Comment by daltojohnso** [comment]
@kdoh & @mazameli -- I'm planning to work on this shortly. Any preferences for how this should look? A loading indicator somewhere? A dialog box with text? If you'd prefer the latter, what text do you want in the dialog box?

**Comment by mazameli** [comment]
@daltojohnso, I think we can go fairly simple with this since it seems to only take a few seconds for the sample dataset to be restored. I'd just swap out the text button/link with our `Text` component, and have it read, "Restoring the sample dataset…", like so:

![image](https://user-images.githubusercontent.com/2223916/106535970-49308080-64ac-11eb-9123-c96be9cac15a.png)
