### ISSUE TITLE
Show download progress/indicator while exporting to avoid multiple clicks

### ISSUE THREAD

**Issue by bjtthao** [metabase/metabase#10566]
Is your feature request related to a problem? Please describe.

When clicking the download file button, there is no prompt for the user, so the user does not know the download situation. When the downloaded file takes a long time, the user may click the download file button multiple times, which will generate many queries and affect the system performance.

Describe the solution you'd like

You should prompt for the file download status and prohibit the click of the download button again when the download is not complete.

Describe alternatives you've considered

Download file prompts download status and restricts downloading button when download is not completed

How important is this feature to you?
Downloading files is the most basic requirement, and multiple-click downloads will generate multiple queries, seriously affecting system performance.

**Additional context**

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
Recategorizing as a new feature request -- this is not a bug given that the download link is working as spec'd.

**Comment by anubhavsahoo** [comment]
I would rate this as a blocker. Most of our users download large datasets via metabase. So it takes a while for the file to download after they click a download option.
Because of this bug, people keep clicking the download option repeatedly because they assume that the download has not been initiated.

This has led to a very small set of users to overload our entire metabase setup. We are left with 2 options either to significantly increase the size/# of metabase instances or move this functionality out of metabase.
(#10968)

**Comment by nitzien** [comment]
Has anybody identified a workaround for this?

**Comment by paoliniluis** [comment]
> Has anybody identified a workaround for this?

a workaround for this would be to deploy a reverse-proxy in front of Metabase and rate limit the endpoint to your needs, but ensure you understand the consequences of this choice

**Comment by sugengsuprayogi** [comment]
when the embedded dashboard is filtered and then downloaded the download results are not filtered

**Comment by flamber** [comment]
@sugengsuprayogi Completely unrelated to this issue.
Create a new issue with all details filled out or use the forum for questions and troubleshooting: https://discourse.metabase.com/
