### ISSUE TITLE
Fields with "only detailed view visibility" should not be accessible in tabs

### ISSUE THREAD

**Issue by alexisdeudon** [metabase/metabase#10577]
**Describe the bug**
When looking at raw data for a given table it appears those fields do not show up by default but we can still add them in tabs settings section.

**To Reproduce**
1. Set a field as "only in detailed views"
2. Open table in Metabase
3. Go to the settings of the tab that has appeared
4. You will be able to add the given column

**Expected behavior**
I would expect not to see these fields in tab config

**Screenshots**

**Information about your Metabase Installation:**
- Chrome
- Ubuntu
- Postgres
- Metabase version: 0.32.10

**Comment by salsakran** [comment]
This is by design.

Our intention is that the `only in detail views setting` is meant to be used to make sure the listing table visualization renders reasonably. If someone wants to add one of those fields back in, they should be able to do so. 

It is _not_ intended to be a way to enforce column level permissions (which is a separate feature)
