### ISSUE TITLE
Upgrading to v0.33.0 - BigQuery throws errors

### ISSUE THREAD

**Issue by jlindenbaum** [metabase/metabase#10723]
**Describe the bug**

Upgrading from v0.31 to v0.33 we are now unable to perform any kind of queries against our BigQuery data sets.

These can be native queries that work in BigQuery console and are pasted into metabase, that throw errors, or they can be more complex reports that rely on BigQuery, built with the custom query builder.

This can be a simple query 
**To Reproduce**

* Upgraded from v0.31 to v0.32
  * BigQuery, custom or native queries, would throw "NullPointerException" errors
* Upgraded to v0.33
  * BigQuery error now reads `Attempting to call unbound fn: #'metabase.driver.bigquery/dataset-name-for-current-query` message

Error 1 (Native Query)
* Ask a question --> native query
* Choose BigQuery database
* Simple SELECT, for example `SELECT * FROM `project.data_set.table` LIMIT 1000`
* Error: `No method in multimethod 'execute-query' for dispatch value: :bigquery`

Error 2 (Query Builder)
* Ask a question --> Custom question
* Choose BigQuery database
* Choose BigQuery table
* No filters, all columns
* Click Visualize (which, I assume is the same as `SELECT * FROM table`
* Error: `Attempting to call unbound fn: #'metabase.driver.bigquery/dataset-name-for-current-query`

**Expected behavior**
Raw data in table format is returned (in both scenarios)

**Screenshots**
![Screen Shot 2019-08-26 at 5 13 02 PM](https://user-images.githubusercontent.com/197034/63729532-cf12bb80-c824-11e9-9ac2-3b57a490d213.png)

**Information about your Metabase Installation:**
- Updated Chrome / macOS
- Metabase running on Ubuntu 16.04 on OpenJDK 12 (gcp vm)
- BigQuery (2 data sets), MySQL unaffected (2 different databases)
- Metabase 0.33 (internal DB pgsql 9.6)
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

**Severity**
We are unable to load, query, or do anything with reports reliant on bigquery data sets.

**Comment by attsn** [comment]
Hi @camsaul,

We are also getting error while loading BigQuery related dashboard with metabase 0.33.0.
Same dashboards works fine with 0.31.2. 

**Deployment environment** - 
"Ubuntu 18.04.2 LTS" with "openjdk version 11.0.4"

Error message is same as mentioned in https://github.com/metabase/metabase/issues/9915 and https://github.com/metabase/metabase/issues/9980.

Please include a fix for this in upcoming metabase release.

**Comment by jlindenbaum** [comment]
Things appear to be working as expected again in 0.33.2

**Comment by camsaul** [comment]
Thanks for letting us know you're no longer running into this @jlindenbaum. Closing as fixed in 0.33.2

**Comment by attsn** [comment]
@camsaul/Metabase team,

BQ integration is working for us with 0.33.2 jar file. 
But we have observed that the files in plugin folder needs to be cleaned up for BQ integration to work. 
As per metabase upgrade documentation - https://metabase.com/docs/v0.33.2/operations-guide/upgrading-metabase.html only the jar file need to replaced. But during our deployment we have found that all the files in plugin folder needs to be replaced. And once we start metabase application with latest 0.33.2 jar file then it regenerated the plugin files and BQ integration started working.

Metabase upgrade documentation needs to be updated, so that other also don't face the issue with BQ integration.

Our upgrade was from 0.31.2 to 0.33.2

NOTE – Our initial metabase application was 0.28.x and when we upgraded to 0.31.2 , we only replaced the jar file and BQ integration was working fine. So looks like the cleanup of plugin files is only needed for upgrade to 0.33.x version.
