### ISSUE TITLE
Do not translate error log messages, or add unique error codes for each error

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10764]
Currently error logs are also translated, but it makes it really difficult to understand for anyone trying to help (if you don't speak that language) and also makes it really difficult for the one with the problem to search for similar problems or solutions.

Proposal: Either don't translate the error logs or add error codes (like Windows :fearful:).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

__________________________________________

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/33340
- [ ] Consider error codes and their hierarchy
```

**Comment by camsaul** [comment]
I like the error codes idea, it's really the best of both worlds.

If we came up with a convention for returning the error codes we could easily have Kondo enforce this rule, e.g. every `ex-info` has to include the `:error-code` key or something like that.

For QP stuff we're currently using a `:type` key with an error type hierarchy in https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/error_type.clj, but those aren't unique. It could be a good starting point tho for unique error code stuff.

I don't know how feasible it would be to have Kondo enforce error code uniqueness across the entire application. We wouldn't want to use something like `gensym` because we wouldn't want the error message to change between versions. I think the main problem is that because Kondo lints stuff atomically there's not really a way to ensure uniqueness between error codes in unrelated namespaces. Some ideas:

1. We could require that the `:error-code` be a namespaced keyword for the current namespace. Then we should be able to track the keywords we saw in that namespace in a Kondo linter and error if we see a duplicate in the same namespace. Downside: error codes are longer/harder to search. Benefit: instant feedback
2. Swap out `ex-info` in `:test` mode and have it record error codes it sees and error if it sees a duplicate. Since this is `:test` only we wouldn't have to worry about problems with reloading code. Downside: no feedback until you run tests from the CLI or in CI. 
3. Write a test that walks the codebase and looks for `:error-code`s inside `ex-info` and errors on duplicates. Downside: no feedback until you run that specific test
4. Write some sort of `(ensure-unique-error-code :my-error-code)` macro that tracks all the error codes it's called with and errors at macroexpansion time if you use the error code more than once. Enforce usage of this with Kondo. To make reloading work it should only error in `:test` mode. Same downsides as (2)

I think maybe some sort of hybrid approach like this would work:

1. Write a Kondo linter to require all `ex-info`s have an `:error-code` with `ensure-unique-error-code`, and ensure those error codes are unique in a given namespace
2. `ensure-unique-error-code` should track all of the error codes it sees, and what namespace it sees them in. It should disallow using an existing error code in a different namespace than the one it first saw it in. This is more or less what we're doing to ensure `defsetting`s are unique. 

This approach would give you instant feedback and let us use short error codes as well

**Comment by camsaul** [comment]
I think the other piece of this puzzle is we need to figure out how to make Log4j print our error codes in a nice way when it prints ExceptionInfos. I think we'd want to walk the `.getCause` chain and get the root error code? And have that be the very first thing in the log message. E.g.

```
ERROR some.namespace: [error code :qp.invalid-filter-clause] This is an invalid filter clause, try again later.
<gigantic mega stacktrace>
```

**Comment by camsaul** [comment]
Having some sort of error type hierarchy like we do for https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/error_type.clj would still be nice tho, that way we would know if certain errors mean things can be automatically retried or not. For example we can retry a query if there is a network error, but shouldn't retry it if there is a syntax error. Maybe that should be part of defining the error code with `ensure-unique-error-code`, or we would want to have a separate `:error/category` or `:error-category` key as well?
