### ISSUE TITLE
New SQL variable type to swap out columns

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#10768]
It would be powerful to add a SQL variable type called `Column` maybe, which would let users use a filter widget to dynamically swap out the column used in an aggregation function, grouping, or filter.

E.g., `SELECT SUM({{my_col_var}}) FROM orders`

A use case would be for example to let me easily see different metrics about the same entity, like revenue or costs from a SQL query that defines a segment of specific orders.

**Comment by flamber** [comment]
Hi @mazameli I can definitely see the use-case.
It looks like PR #5247 does this (and more).
Would there be some security implications for people not having write-access to the SQL, since the column filter would be editable in the URL? Like changing the column to one that is hidden.
Versions before 0.23 could do something like that, but was changed to prevent SQL injections #4639

**Comment by walterl** [comment]
@flamber's right: this is a duplicate of #4639.
