### ISSUE TITLE
Metric with unnamed Custom Expression breaks Data Model for table

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#10844]
**Describe the bug**
Create a Metric with a Custom Expression without giving it an optional name, and then save the metric and visit Data Model. Now it doesn't load the data on the table for the metric.

**Logs**
I'm not seeing any backend errors.
But there's browser errors. While saving the Metric it gave `TypeError: prevComponentInstance is null`.
And when visiting the Data Model, then it shows ```Error: `query` is a required parameter to format expressions```.

**To Reproduce**
1. Go to Admin > Data Model > Sample Dataset > Orders > Add a Metric
2. Click View > Custom Expression and set expression `Sum(Subtotal) + Sum(Tax)` without setting Name, click Done.
3. Save expression (it might be "stuck" and need a second click on Save). Browser console should show `TypeError: prevComponentInstance is null`.
4. If it returns to the Data Model (Sample:Orders), then there's no data/metrics/column and browser console shows ```Error: `query` is a required parameter to format expressions```

**Work-around**
Manually go and edit the Metric and give the Custom Expression a name.
Visit the URL `/admin/datamodel/metric/X`, where `X` is the ID of the failing metric.
If you don't know the ID of the metric, then you can find it by clicking "Browse Data" in top-menu, "Learn about our data" top-right > "Metrics" left-side > click the metric and check the URL, which will look like `/reference/metrics/X`.

**Information about your Metabase Installation:**
Metabase 0.33.2 (and 0.33.0 and current `master`) on H2 with various browsers.

**Additional context**
Was reported in the forum:
https://discourse.metabase.com/t/custom-expression-in-metric-crashing-the-model/7285

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Fixed by #11065, included in 0.33.4

**Comment by flamber** [comment]
Partially fixed by #11065, included in 0.33.4, since you cannot create Custom Expression without a name now, but for any existing metrics with Custom Expressions containing math, it will still fail showing Data Model.

**Comment by Sire** [comment]
Suggested fix: Metrics without "display-name" still show up on the table view. 
Even better: Copy the name to the display name, so the error is fixed in next database update.

Right now we get errors and no metrics show up so it's tricky to delete them. Workaround was to modify an existing PUT command with curl.

**Comment by mallchin** [comment]
Thanks @flamber, works a treat!

**Comment by flamber** [comment]
Changing priority, since 0.36.0 now has all metrics in one page, which will make it a lot harder to figure out which metric is causing the problem

**Comment by trov-madisonhope** [comment]
Any update on this issue?  We're still seeing this in production.

**Comment by nemanjaglumac** [comment]
### Note
Cannot test directly in Cypress because it is not possible/allowed to save custom expression without name in newer versions.

I can try to wrap an API call to [`/api/metric/`](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apimetric) with `withSampleDataset()` to programatically save a metric with unnamed custom expression. 

### Question
Does this even make sense to cover with test, since we don't allow this behaviour to occur in the first place in the newer versions?

**Comment by paulrosenzweig** [comment]
Mostly fixed a while ago with a small fix in #13579
