### ISSUE TITLE
Visualization type set by user is not saved with question when using editor

### ISSUE THREAD

**Issue by crunchtoinfo** [metabase/metabase#10957]
**Describe the bug**
Let's say I have saved a question to show sales as a pivot table by month and by year. If I click show editor and filter on account manager name to show only their sales, the visualization is changed automatically to Bar. I have explicitly specified and  saved as table before and this is unexpected behavior that forces me to change the visualization every time I use the editor.
This behavior is a but, in my view.

If I don't use the Show editor button, but Filter or Summarize buttons the visualization type is preserved - which is correct.

I don't see a need to add info to the other sections of the bug report. If asked, I will do it.

**Comment by mazameli** [comment]
Yeah, it looks like our auto-viz-selection logic needs some tweaking. Here's a GIF that shows what you're describing:

![auto-viz-bug](https://user-images.githubusercontent.com/2223916/65636066-668b3b80-df96-11e9-8489-89ed4052a97b.gif)

I think this logic would make more sense:

**For Custom/notebook:**
- If this is a new question that hasn't been visualized yet, autoselect a viz when the user clicks Visualize.
- For saved questions, or for unsaved ones where a visualization has been explicitly set, if the query changes and the user clicks Visualize, first check if the current visualization still makes sense (`is-sensible`) for the new results (e.g. if it's changed from a time series to a scalar, and line chart doesn't make sense). If the existing viz makes sense, leave it alone; otherwise, autoselect a viz.

**For Simple mode:**
- For unsaved questions, autoselect the viz for me whenever I change the query _until_ I click on a specific visualization from the viz sidebar menu. Then, when I change the query, see if the results are still sensible for my selected viz type. If so, don't change my viz. If not, autoselect my viz, and keep doing so until I again manually select a viz type.
- For saved questions, if I change the query, see if the results are still sensible for the currently selected viz type. If so, don't change my viz. If not, autoselect my viz, and keep doing so until I manually select a viz type.

**Comment by crunchtoinfo** [comment]
Hi, Maz. 
1. The problem described above happens only when the "Show editor" button is used. The viz is not auto-changed when Filter or Summarize (next to "Show editor") are used. Just pointing this out if it has implications for the story.
2. "is-sensible" has to be a common sense, human test that only removes absolutely incompatible visualizations. So, according to this test, if I have manually chosen Table as a visualization, it should always pass this test because table is sensible for any type of data (that I can think of). Maybe it's not the best but it is sensible and I have chosen it for some reason.
3. Maybe you could add "Auto" as the first visualization type in the list and it is the default. Then if the use click choose another - this becomes the choice for the given question. The user can always choose back to the Auto type. This approach has the fewest surprises and highlights the intelligence of the software. You can track how often users adopt / change the Auto choice and train the algorithm. Maybe I am going into fiction area here...

**Comment by sitepodmatt** [comment]
>Yeah, it looks like our auto-viz-selection logic needs some tweaking

Did anyone ever request auto-viz-selection? I think you could satisfy a lot of people just by having it off by default or providing an option to disable.

**Comment by Tbodewes** [comment]
Could it be that this fix led to a new problem described in this thread https://discourse.metabase.com/t/question-visualization-config-is-lost-when-navigate-from-dashboard/8690. 

We are currently facing this problem on V0.34.3.
