### ISSUE TITLE
When grouped by week, time series tooltips aren't correctly displaying the week when there are many x-axis points

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11059]
Seeing this on our stats instance. It stops happening if the number of x-axis points is small enough such that the x-axis labels show the starting day of the week. To reproduce:

- Start a new simple GUI question on orders
- Summarize by count of rows and created at: week
- Hover over a data point and see that it only shows the month instead of indicating which week of the month it is:

![image](https://user-images.githubusercontent.com/2223916/66226141-f57f0e80-e68e-11e9-9311-0e773680ce48.png)

I'd expect the tooltip  to look like this:

![image](https://user-images.githubusercontent.com/2223916/66225348-121a4700-e68d-11e9-90f2-9e2381e24e08.png)

**Comment by flamber** [comment]
@mazameli 
Almost looks like a return of #10841, which was fixed by #10864 on 0.33.3
Out of interest, which version is the stats instance running?
On my `master` (commit 8597f7cb3f0b68158a6697984e8b8fc859a03f11) it looks okay.
![Screenshot_00001](https://user-images.githubusercontent.com/1447303/66227430-67a92080-e69a-11e9-97a4-58012991a59e.png)

**Comment by paulrosenzweig** [comment]
I'm guessing it _was_ #10841 and that stats was running a pre-0.33.3 version. We haven't been keeping it up to date. It works on stats now 🤷‍♂
