### ISSUE TITLE
metabase-deploy (heroku) is out of date

### ISSUE THREAD

**Issue by yaviner** [metabase/metabase#11088]
Hi,
I'd like to update our Heroku instance of metabase, which uses metabase-deploy. The latest version of metabase is currently 0.33.3, though metabase-deploy doesn't look like it's been updated since 0.32.8. I'm posting here because issues aren't enabled for metabase-deploy.

Is metabase-deploy actively maintained, and/or does anyone have a workaround for updating an instance on Heroku to the latest version of metabase?

**Comment by salsakran** [comment]
`metabase/metabase-deploy` uses `metabase/metabase-buildpack` (https://github.com/metabase/metabase-deploy/blob/master/app.json)

`metabase-buildpack` has been updated to the latest version.

Are you having issues upgrading or is this just a question?

Closing since things look like they're working. If you're unable to upgrade, please describe symptoms and I'll reopen the issue.
