### ISSUE TITLE
Error saving questions in 0.33.4

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11108]
We received a single [report](https://discourse.metabase.com/t/new-card-saving-issue-v0-33-4/7616/2) of a user having trouble saving new questions in 0.33.4 after upgrading. They're able to edit and save _existing_ questions just fine. I attempted upgrading a 0.32.10 instance to 0.33.4 but could not reproduce this myself yet.

They're querying a Postgres DB, and didn't see seem to see any migration errors.

When attempting to save a new question, they're seeing the following:

```
[4df59e9a-c035-4191-8bb9-c252a483c5bd] 2019-10-09T18:17:19+01:00 INFO metabase.api.card Card results metadata passed in to API is VALID. Thanks!
[4df59e9a-c035-4191-8bb9-c252a483c5bd] 2019-10-09T18:17:19+01:00 DEBUG metabase.async.util Running metabase.api.card$save_new_card_async_BANG_$fn__60472@40f6b8c4 on separate thread...
[4df59e9a-c035-4191-8bb9-c252a483c5bd] 2019-10-09T18:17:19+01:00 DEBUG metabase.middleware.log POST /api/card 200 [ASYNC: completed] 108.8 ms (36 DB calls) Jetty threads: 2/50 (5 idle, 0 queued) (161 total active threads) Queries in flight: 0
[4df59e9a-c035-4191-8bb9-c252a483c5bd] 2019-10-09T18:17:19+01:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@40f6b8c4
```

And here's what the save modal display:

![image](https://user-images.githubusercontent.com/2223916/66508891-d5808e00-ea86-11e9-99df-6c2b4f3c9fe4.png)

I'm calling this a P1 for now, but if it turns out this is widespread, it could escalate to a P0 IMO.

**Comment by mazameli** [comment]
The user who reported left [an update on discourse](https://discourse.metabase.com/t/new-card-saving-issue-v0-33-4/7616/6?u=maz):

> We found that this error was being driven by the Postgres sequence not recognising the existing values in a table and therefore conflicting with unique constraints.

> I used the following combinations to replace the sequences:

> `SELECT MAX(id) + 1 FROM report_card;`
> `CREATE SEQUENCE card_id_seq START WITH 946;`
> `ALTER TABLE report_card ALTER COLUMN id SET DEFAULT nextval('card_id_seq');`

> This fix would likely have worked for the two other tables we truncated.

Not sure if that means we can/should close this bug. Ideally we'd at least provide a more helpful error message than just "Saving failed".

**Comment by ReneSoul** [comment]
@mazameli using the latest version basically every new question fails saving, without doing anyting but selecting the table....

`[4922d16a-76ed-49a5-ae8c-e81b49bcb739] 2019-10-15T09:43:35+02:00 ERROR metabase.async.util Caught error running metabase.api.card$save_new_card_async_BANG_$fn__60472@1e94b6c3`

**Comment by ReneSoul** [comment]
Hi @flamber not at all, metabase sits directly on the database of a Jira instance and this error occurs if I open a new question, select a table get the results and trying to save it...this of course worked fine in the previous version, so this feels like a bug to me, but I am rather new in using metabase

**Comment by flamber** [comment]
@ReneSoul 

It is not between Metabase and the database, but between you and Metabase. There has been some really strange issues, which are caused by various reverse-proxy services.

Which version did you use before? Have you tried to downgrade to that version? Remember to always backup before upgrading/downgrading.

I'm fairly sure you're experiencing a different issue than this, so I would recommend that you create a new issue and fill in all the requested details.

**Comment by ReneSoul** [comment]
@flamber 

Thanks a lot for your rapid answers. I cant recall the previous version, but as I dont want to relinquish the new editor I will workaround this issue for now (switching to SQL view and save there)

**Comment by flamber** [comment]
@ReneSoul As I was investigating other things, I stumbled upon your problem again. By any chance, are you using MySQL for metadata (Metabase's application database)? If yes, then the problem is that your MySQL is not using `utf8mb4` for it's tables/columns - how to check and convert, see #10691
Otherwise, please head over to the forum - https://discourse.metabase.com/ - if you want help to troubleshooting this problem.

**Comment by flyingmachine** [comment]
@flamber I've posted [a response to the thread maz posted](https://discourse.metabase.com/t/new-card-saving-issue-v0-33-4/7616/7?u=nonrecursive)

**Comment by flyingmachine** [comment]
@mazameli could you give me feedback on what to do next, here? I think a couple next steps could be:

* report the error in the UI as you suggested
* If we provide tools to move metabase data to a new database, make sure they preserve postgres sequence info

After looking into the issue I think it's the result of a less common use case (moving data to a new DB instance, not just updating metabase itself) so I think this probably isn't a P1 but I'd like your guidance :)

**Comment by mazameli** [comment]
Yeah, if there's an easy enough way to add a clear, human-readable error message in this situation, that would be great. @tlrobinson and @kdoh recently did some work to update our <Form> component to have a consistent place to display error messages, so if we can use that here, that would be grand.

As for the moving data to a new DB scenario, it seems to me it's super common to go from the default H2 to e.g. Postgres, but because we haven't heard more reports of this specific problem, maybe it's less common to go from one Postgres instance to a new one. [Serialization](https://www.metabase.com/docs/latest/enterprise-guide/serialization) is a tool that allows you to move some of the contents of one MB app DB instance to another — could you foresee this bug resurfacing more commonly in that use case?

There is still just the single report of this issue to my knowledge, and that user was able to remediate it, so if we don't think many folks are likely to hit this I'm okay if we want to call it a P2.

**Comment by flyingmachine** [comment]
@camsaul it looks like there's a wrinkle in displaying an error message in that [the card creation API endpoint](https://github.com/metabase/metabase/blob/master/src/metabase/api/card.clj#L218) returns a go channel, and the resulting response status is always 200, even if there's an exception. The response does at least return an error message.

Is there already a way for the frontend to recognize this scenario, and if so, how do we need to structure the response so that the FE will render the error message that gets returned?

**Comment by flyingmachine** [comment]
I've gone through the serialization and it does in fact update the db sequences correctly. The user in the discourse thread must have used some other tool to move his data to a new database, and that seems to me like something we don't need to support within the metabase app

**Comment by flyingmachine** [comment]
with #11726 we now report these errors in the UI
