### ISSUE TITLE
[QUESTION] add sqlite db in read-only mode 

### ISSUE THREAD

**Issue by nskalis** [metabase/metabase#11123]
Hi,

Is it possible when importing a SQLite database
to configure Metabase to open a connection to it as `read-only`
?

For example,

```file:sqlite.db?mode=ro```

**Comment by flamber** [comment]
Hi @nskalis 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Metabase is by definition read-only already, since it only does analytics. You cannot send `INSERT`/`UPDATE`/`DELETE` queries to any of the databases.
Metabase doesn't import databases, it connects to them (and caches some content, but that's a different topic).
Some databases needs write-mode, since that's the only way to set certain database settings (like timezones, etc). I'm not sure if that applies to SQLite.
As a work-around, since SQLite is file-based, then you could just set the file to be read-only by whatever file-system user that Metabase is trying to access the file with.

**Comment by mazameli** [comment]
Looks like this is being discussed on discourse.
