### ISSUE TITLE
iFrameResizer resizer already defined.

### ISSUE THREAD

**Issue by judell** [metabase/metabase#11144]
**Describe the bug**

Same intermittent failure as https://github.com/metabase/metabase/issues/5964 but I think circumstances differ. It doesn't happen in the metabase dashboard, but rather when using the embed mechanism described here: https://www.metabase.com/docs/v0.23.0/administration-guide/13-embedding.html

**Logs**

![image](https://user-images.githubusercontent.com/46509/66861715-5c7cad00-ef44-11e9-9a26-fccf3441b4f4.png)

**To Reproduce**

Unclear how to repro, it happens intermittently.

**Expected behavior**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Current Chrome and Firefox
- Your operating system: WIndows 10
- Your databases: Postgres
- Metabase version: v0.31.2
- Metabase hosting environment: AWS
- Metabase internal database:  Postgres

**Severity**

Will block an intended use for sharing metrics with customers and partners. We are using metabase _very_ successfully for internal metrics (thank you!), hope to use the embed mechanism to share some of them. The workaround will be to go direct to postgres for that purpose.

**Comment by flamber** [comment]
Hi @judell 

You're referencing a very old version of the documentation (`v0.23.0`), the latest is [v0.33.4](https://www.metabase.com/docs/v0.33.4/administration-guide/13-embedding.html) - not that a lot has changed with that specific docs, just note that you should follow the documentation for the version you're using.

There has been many changes since version 0.31.2 - is there a specific reason why you haven't upgraded to a newer version?

Are you referencing the iFrame Resizer script included in Metabase, or which version are you using? The script included in Metabase is version [3.5.11](https://github.com/metabase/metabase/blob/master/resources/frontend_client/app/iframeResizer.js), while the latest is [4.2.2](https://github.com/davidjbradshaw/iframe-resizer).
And are you only loading the script once - or are you trying to load it for every iFrame embed?

**Comment by judell** [comment]
>  is there a specific reason why you haven't upgraded to a newer version?

I don't control the installation, happy to ask for an upgrade, if there's a reason to think it'll solve the problem that will help.

> And are you only loading the script once - or are you trying to load it for every iFrame embed?

I'm not loading the script directly, I'm loading multiple iframes into a single page, each iframe with a src tag like https://metabase.hypothes.is/embed/question/...

**Comment by flamber** [comment]
@judell 
So you're not loading the iframeResizer.js script at all?
It might be a race-condition, but it's difficult to tell without seeing all source.

**Comment by judell** [comment]
Correct. It's app-embed.bundle.js that throws the error.

![image](https://user-images.githubusercontent.com/46509/66866475-38be6480-ef4e-11e9-9ed1-b94e06d91ee4.png)

**Comment by judell** [comment]
This appears to be a downstream effect. I checked a failing query interactively and found this happening (again intermittently, for the same query): https://stackoverflow.com/questions/49668404/metabase-clojure-error-unfreezable-type-class-org-postgresql-jdbc-pgarray. Then I realized I'd inadvertently dropped an index. Upon restoring that, the embeds are working fine.

I thought I'd done the interactive check before but evidently not. Should this happen again I'll be sure to do so.

Thanks for metabase, it is a wonderful tool!

**Comment by flamber** [comment]
@judell 
Are you referring to the `400` error? If you had access to the server log, then you should be able to see more information (or top-right :gear: > Metabase Log on 0.31.2, or :gear: > Admin > Troubleshooting > Logs on 0.32+)

Does that mean that you're only seeing the resizer error, when the question is failing? That might help narrow down the problem.

**Comment by judell** [comment]
> Does that mean that you're only seeing the resizer error, when the question is failing? 

I _think_ so, time will tell.

As per https://stackoverflow.com/questions/49668404/metabase-clojure-error-unfreezable-type-class-org-postgresql-jdbc-pgarray, I'm seeing relatively many serialization complaints even after restoring that index:

`Oct 15 21:28:18 WARN metabase.driver :: Don't know how to map class 'class org.postgresql.jdbc.PgArray' to a Field base_type, falling back to :type/*.`

But so far none of these that were recorded before:

`{:status :failed,
:class clojure.lang.ExceptionInfo,
:error "Unfreezable type: class org.postgresql.jdbc.PgArray",
:stacktrace
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
"clojure.core$ex_info.invoke(core.clj:4739)"
"taoensso.nippy$throw_unfreezable.invokeStatic(nippy.clj:720)"
"taoensso.nippy$throw_unfreezable.invoke(nippy.clj:718)"
"taoensso.nippy$fn__22755.invokeStatic(nippy.clj:924)"`

**Comment by flamber** [comment]
@judell Okay, that's a different problem than this issue, so it should be split, but I would recommend that you upgrade to the latest release, since there has been many changes and fixes since 0.31.2
I have no idea if the `PgArray` issue would be fixed in latest release, but it's difficult to support an almost one year old version.

**Comment by judell** [comment]
> I would recommend that you upgrade to the latest release,

Would like to. This will help us prioritize doing so, thanks again.
