### ISSUE TITLE
Tooltip on hover does not correctly reflect filter with multiple selections

### ISSUE THREAD

**Issue by niparis** [metabase/metabase#11180]
**Describe the bug**
When a filter is used with multiple selection, the hover on a chart will display only a single value for that variable.

**To Reproduce**
Create a chart (ex: stacked bar chart, X axis is time, Y some metric, select a few other variables for filtering)
Implement a filter (field filter, for example on a country)
Use the filter to select 2 or more countries

In the tooltip, *only one of the selected countries will be shown*. The country displayed *will be different* depending on which bar is highlighted. I wasnt able to find a reliable pattern (though sorting makes it less predictable)

**Expected behavior**
In the tooltip, ALL OF of the selected countries should be shown
Example: if US, GB, and DE are selected in the filter, the tooltip should show: "country: US, GB, DE"

**Screenshots**
Filter selection
![image](https://user-images.githubusercontent.com/3415960/67193834-8fcda900-f428-11e9-9985-a18d4761232d.png)
Tooltip
![image](https://user-images.githubusercontent.com/3415960/67193879-a7a52d00-f428-11e9-93be-603f38eb5769.png)

**Information about your Metabase Installation:**

Metabase 0.33.4

**Severity**
Quite serious. Anyone checking the tooltip is left wondering if the filter works properly.

**Comment by flamber** [comment]
Hi @niparis 
I'm having difficulties trying to reproduce your issue.
Can you provide better steps-to-reproduce? And screenshots of what is hovered (mouse pointer)?
Perhaps use the Sample Dataset in case you don't want to share data.

**Comment by mazameli** [comment]
I'm also not able to repro this. We might've made some fixes to tooltips since 0.33.4. As @flamber already mentioned, any additional, more specific repro steps and screenshots you can provide would be peachy.

Here's an example of what I'm seeing: my metric and breakout columns are in the tooltip, but not the filter column(s), which seems expected to me.

![image](https://user-images.githubusercontent.com/2223916/72564858-8c9a5b80-3865-11ea-9e45-9361db495c40.png)
