### ISSUE TITLE
Cannot connect to Aliyun/Alibaba RDS MySQL 5.6.16-log

### ISSUE THREAD

**Issue by jinlan0639** [metabase/metabase#11266]
![image](https://user-images.githubusercontent.com/44486674/68208554-5aba7c80-000c-11ea-8b3e-f3e293e0cb52.png)
cant connect to database , dont know reason

**Comment by mazameli** [comment]
This error occurs when you're using a version of SQL that Metabase does not support. What type of database (including version) are you attempting to connect to?

**Comment by jinlan0639** [comment]
our database and version ： MySQL 5.6

**Comment by jinlan0639** [comment]
> This error occurs when you're using a version of SQL that Metabase does not support. What type of database (including version) are you attempting to connect to?

our database and version ： MySQL 5.6

**Comment by flamber** [comment]
Metabase does not support Alibaba RDS MySQL 5.6.16-log, since changing to MariaDB Connector/J in version 0.32.0, because `session_track_schema` is not supported in the old MySQL.
It has been discussed several times before #9483 and #9954 and in the forums too [6791](https://discourse.metabase.com/t/i-get-an-error-when-i-create-a-mysql-5-6-database-connection/6791) and [7261](https://discourse.metabase.com/t/metabase-always-show-this-report-have-a-problem/7261).
Seems like the only solution would be to submit a PR to the MariaDB repo with [these changes](https://github.com/metabase/metabase/issues/9954#issuecomment-492023843).

**Comment by flamber** [comment]
@camsaul It seems like MariaDB Connector/J 2.5.4 just got an option to not set session_track_schema with `trackSchema=false`, which should mean that it should work with Alibaba RDS MySQL 5.6.16-log.
I don't know if you have an Alibaba account available to test with - and I guess you have to use `MB_DB_CONNECTION_URI` for metadata, since that would be the only way to add the option?
https://github.com/mariadb-corporation/mariadb-connector-j/releases/tag/2.5.4
https://jira.mariadb.org/projects/CONJ/issues/CONJ-755?filter=allissues

**Comment by flamber** [comment]
Closing, since Metabase doesn't officially support versions earlier than MySQL 5.7 and MariaDB 10.2. If you're still experiencing problems with newer versions of the latest version of Metabase, then please comment.
