### ISSUE TITLE
Wrong display on chart floating description

### ISSUE THREAD

**Issue by Olaktal** [metabase/metabase#11284]
**Describe the bug**

Hello,
I reproduced the bug i'm facing with the sample dataset.
Here is my SQL query:

`SELECT product_id, CASE WHEN quantity <3 THEN '<3' ELSE '>=3' END as quantity_range,  CASE WHEN discount <2 THEN '<2' ELSE '>=2' END as discount_range, sum(total)
FROM ORDERS 
GROUP BY product_id, quantity_range, discount_range
ORDER BY 2,3`

I created a surface chart as following --> 

![image](https://user-images.githubusercontent.com/5711131/68474703-6aada880-0226-11ea-8246-54365efb0f70.png)

And this is the result --> 

![image](https://user-images.githubusercontent.com/5711131/68474528-e8bd7f80-0225-11ea-9fb1-4f33f40fcd05.png)

What I was expecting is to display the total in the floating description but it seems to display one of the many result.
Is it possible to display the real total or nothing ? this information is very misleading in our dashboards.

**Information about your Metabase Installation:**

Metabase version: 0.33.4

**Comment by mazameli** [comment]
Yeah, it appears that the y-axis is showing what you'd expect, but the tooltip isn't:

![image](https://user-images.githubusercontent.com/2223916/72574469-076f7080-387e-11ea-8630-6fc1439cc31c.png)

I'm marking this as a P2 for now because I'm not sure how common it is to run into this exact scenario, though it does deal with correctness.

**Comment by flamber** [comment]
Closing in favor of #11907
