### ISSUE TITLE
Cumulative Count can't be to join data or in custom expression

### ISSUE THREAD

**Issue by shafy** [metabase/metabase#11303]
**Describe the bug**
A Saved Question which uses the Cumulative Count metric doesn't appear when trying to join to other data. I can join it if I do it without saving it as a seperate question, but then I can't use the Cumulative Count column in a Custom Expression.

The error I get is
```
No method in multimethod '->honeysql' for dispatch value: [:bigquery :cum-count]
```

I think it might be related to #3110

I'm on v0.33.5 with BigQuery as the database running on Heroku.

**Comment by flamber** [comment]
Hi @shafy 
That's a known limitation, as listed in the documentation:
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#picking-your-starting-data
Cumulative Count (and Cumulative Sum) are special aggregations, where Metabase does some magic behind the scene, so that's the reason why it doesn't work like other aggregations.
I'm not sure I understand what you mean with this?
> I can join it if I do it without saving it as a seperate question, but then I can't use the Cumulative Count column in a Custom Expression.

**Comment by shafy** [comment]
Hey thanks for pointing that out, I didn't find this when searching. Haha, what I meant is if I don't save it as a question but directly join it. But definitely related to the same limitation.

Any ideas for workarounds?

**Comment by flamber** [comment]
@shafy No, only by doing the entire query in SQL.
But since this is a known limitation listed in the documentation, then you can close this issue.

**Comment by shafy** [comment]
Ok, thanks a lot for your help!
