### ISSUE TITLE
Timeseries tick labels are always in English even when interface is another langage

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11319]
**Describe the bug**
The tick labels of a line/bar/area timeseries are always showing English instead of browser language. It shows localized version in 0.33.4
Workaround is to change visualization Settings > Axes > X-axis scale = Ordinal.

**To Reproduce**
1. Simple question - Sample Dataset - Orders
2. Summarize count-of-rows grouped by CreatedAt:Month
3. Ticks are showing English month names.

**Screenshots**
0.33.5.1+ always shows English ticks
![image](https://user-images.githubusercontent.com/1447303/68877850-59541880-06cc-11ea-85b9-4f253a4b098a.png)

0.33.4 works
![image](https://user-images.githubusercontent.com/1447303/68877882-67a23480-06cc-11ea-8a0d-92c55a3ecd1c.png)

**Information about your Metabase Installation:**
Metabase 0.33.5.1 on Firefox 70 (different browser languages).

**Additional context**
https://discourse.metabase.com/t/notebook-editor-unable-to-change-displayed-language/7977

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by SwiftTT18** [comment]
Hi, does this bug fixed?
The tick label still showing english instead of browser language (japanese) . version: 0.35.4

Some of our clients and manager level staff don't understand english. It is annoying and even a little bit rude (due to the Japanese business culture) when we show our clients the chart in english.

would you mind telling me the latest news about this bug?

**Comment by flamber** [comment]
@SwiftTT18 Yes, but there's 1700 other open issues too. We use upvotes to help us prioritize issues, so remember to upvote the issues you're encountering by clicking :+1: on the first post of each issue.
