### ISSUE TITLE
Upgrade check should only tell "... latest and greatest!" if it really is

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11336]
I'm unsure if I should classify this as a bug or feature.

There has been many times in the forum (and [9819](https://discourse.metabase.com/t/why-does-metabase-want-my-smtp-password-in-plain-text/9819) and [9511](https://discourse.metabase.com/t/admin-password-reset/9511)), where people show a screenshot of Admin > Settings > Updates, where it says "You're running Metabase X.YY.Z which is the latest and greatest!", but they're not running the latest.

Errors:
1. Sometimes it's because connection to `static` is blocked.
2. Sometimes they're using their own compiled version.
3. Sometimes they have just upgraded, but the notice doesn't go away until `metabase.task.upgrade-checks.job` runs again (every 12 hours).
4. Sometimes something else is going on, which I'm not sure why.
5. Sometimes the check fails with `Sorry, we were unable to check for updates at this time.` - [not sure why](https://discourse.metabase.com/t/unable-to-check-for-updates/9893).
6. Enterprise Editions will also show `Sorry...` message

Possible changes:
1. If checks are disabled, then it should not show that message.
2. If last check was more than 1 day ago, then it should not show that message
3. If running version/hash and version-info->latest does not match, then it should recommend upgrade.
4. Have a manual button "Check for updates" together with `Last check` timestamp.
5. Host version-info over https://
6. Possibly show information from Github release notes instead of showing the short-list from version-info. Or at least link to them.
7. Link to [upgrade docs](https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html) instead of `/start/`, when there's a newer version available. Or have an upgrade link under each type in `/start/`.
8. Enterprise Edition should either have a dedicated version-info or completely hidden
(not sure what should be done/shown, when Whitelabel is enabled - should probably not have links to metabase`.`com)
9. Hosted Cloud should show a custom message or completely hidden

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by urkle** [comment]
I just got hit by this. I've been running 0.33.6 for a while now and it continued to state it was the "latest and greatest".

**Comment by jeff303** [comment]
As of 0.39 (via #15517), the following improvements are in place:

- There is a separate version check URL for enterprise edition, named `:mb-version-info-ee-url`, and settable via env var just like `:mb-version-info-url`
- The Enterprise Edition of Metabase will query the aforementioned URL instead of the OSS one
- Previously, there were issues where the version check code thought it was already on the latest, because `1.36` (for example) is always greater than any `0.x` release.  This is fixed now because the new EE verison info file that we publish will only include `1.x` version tags
- The version check backend job still runs on the same schedule as before.  However, it will also track a timestamp when the last check was successfully made, and if a check fails, it will set the current `version-info` value to `nil` instead of leaving it to some potentially super outdated value (i.e. not thinking that `0.38` is still the latest in six months' time, just because the update checks start failing tomorrow)
- If the update check fails, then the "Sorry, we were unable to check..." language on the frontend will also show the timestamp of the last successful check
- Upon successfully finding a newer version available, the frontend link will go to its specific upgrade docs instead of the `/start` catch-all page

All other improvements/tweaks mentioned in the original description (ex: different behavior on hosted, manual "check now" feature) will need to go into a follow-up issue to be addressed separately.
