### ISSUE TITLE
Slack Pulses aren't rendering Lato font correctly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#11401]
This is not the typeface we've all come to know and love. This pulse was generated from our Stats instance.

![image](https://user-images.githubusercontent.com/2223916/69764229-781eca00-1124-11ea-9a56-93fde3e00400.png)

**Comment by flyingmachine** [comment]
Here's what I've found so far:

* I don't run into this issue when I run the app from the REPL locally
* I *do* run into this issue when I create a docker container from my local repo and run that. I confirmed this by doing the following:
    * Creating a pulse with no code changes - this did not use Lato.
    * Creating a pulse changing the `font-family` to just `sans serif`. The rendered pulse looked identical to the one created in the step above.
    * Creating a pulse with a `font-family` of `serif` to make sure that my changes were getting picked up. The pulse looked different and serif-y compared to the previous two pulses.

The next step I'm going to take is to run try this with a docker image that does not include the changes from the Bundle Fonts PR, #10963 . Final step will be to figure out why docker isn't picking up the bundled fonts.

My guess - and this just occurred to me - is that the HTML produced for rendering pngs doesn't actually include whatever tags or styles are necessary to actually include the fonts.

**Comment by flamber** [comment]
@flyingmachine 
I was playing around with the pulse code last weekend, because I was trying to see if I could fix 2342 (avoiding link), and was completely blank on how it actually included the font.
I was updating [CSSBox to 4.14](https://github.com/radkovo/CSSBox/blob/master/CHANGELOG), since that version has basic font-face support, but still couldn't understand the Clojure code well enough to get anywhere :crying_cat_face:

**Comment by flyingmachine** [comment]
I tried rendering a pulse image in docker using commit `767760df13d72e72b0a599b129858c71903bed1a`, which is the parent commit of the first commit in #10963. The result is more visually pleasing but it's still not using the correct font:

![pulse-pre-bundle](https://user-images.githubusercontent.com/1421/71211343-ed417300-227c-11ea-8d0b-c27742e1596c.png)

**Comment by flyingmachine** [comment]
@flamber yeah, I'm not sure it even includes the font? I think [this is where we generate some html that gets passed to CSSBox](https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render/png.clj#L72) and I'm not seeing where the fonts would get loaded. I'm also not sure if there's additional configuration you need to on the CSSBox end to make fonts available.

**Comment by flamber** [comment]
@flyingmachine 
I'm guessing that CSSBox will the automagically read the fonts (TTF only?), from looking at this commit: https://github.com/radkovo/CSSBox/commit/295ca523c8774c6f992518c174f7a09868326096

From what I can understand on 4.14, you would add a `<style>@font-face{...}</style>` to the `render-html-to-png`'s `:head` (before `:body`) with a style like [base.css](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/css/core/base.css) on the frontend (of course with different paths, since it's not webpack).

But I still don't understand how it's even picking up Lato currently, which is where I got lost and thought I should ask people smarter than me :wink: 
From my very little Java, it looks like it's done via `java.awt.Font`, but that's not included in `png.clj`

**Comment by flyingmachine** [comment]
I tried adding the contents of base.css in a `<style>` tag in `<head>`, but that didn't work, which I think makes sense because those styles direct the browser to load the fonts from a given path, but I don't think CSSBox would have access to the server to load the fonts from.

I've also tried base64-encoding the fonts using [these instructions](http://stephenscaff.com/articles/2013/09/font-face-and-base64-data-uri/), which I would expect to work, but didn't. I'm now at a loss for what to do next :/
