### ISSUE TITLE
Clicking on a multi-series chart to view question data applies incorrect filters

### ISSUE THREAD

**Issue by landreville** [metabase/metabase#11442]
**Describe the bug**

I've added a multi-series bar chart to the dashboard group by monthly data. Clicking on one of the series' bars in one of the months (x-axis) and choosing "View these ..." should show the data for that bar. Hovering over the bar also shows the filters that should be applied.

However, clicking on "View these..." goes to a question that contains all of the filters for every series on the multi-series chart. In my test I used two series that are constrained by different years. There are two year filters after clicking on the "View these..." link.

**To Reproduce**
1. Create two questions for time series data grouped by month. Include different year filters on both to ensure they don't contain the same data (eg 2018 and 2019)
2. Create a new dashboard
3. Add the first question to the dashboard as a vertical bar chart
3. Add a a second series to that dashboard widget and choose the second question
4. Save the dashboard
5. Hover over the bar data and notice that it includes a filter (eg "Year: 2019")
6. Click on the bar data and click "View these ... "

Expected results: the original question is displayed with a filter for the month that was clicked on. For example year: 2019 and month: June

Actual results: the original question is displayed with a filter for the month that was clicked on and the filters from the other non-clicked series. For example year: 2019 and year: 2018 and month: June

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.4.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

- Your browser and the version: Firefox 70.0.1
- Your operating system: Kubuntu 19.04
- Your databases: Postgres 9.6
- Metabase version: 0.33.4
- Metabase hosting environment: Red Hat Linux
- Metabase internal database: Postgres 9.6

**Severity**
Annoying, unexpected behaviour. 

Workaround is to click on the question name on the dashboard, which takes the user to the question itself. Then click on the bar that is displayed on the question graph.

**Comment by flamber** [comment]
Hi @landreville 
Let me see if I understand you correctly. You are combining two questions on one chart on the dashboard. But when clicking the "View these ..." on any of bars, it always takes you to the first question with correct filters applied? Since it's taking you to the first question, the result is wrong.
Seems like it's the same problem for all the drill-through actions (Zoom in, View these, ...)

I can reproduce that on `master` with Simple question > Sample Dataset > Orders:
1. Q1: Filter: CreatedAt=2018, Summarize: Count by CreatedAt:Month and Product.Category
2. Q2: Filter: CreatedAt=2019, Summarize: Count by CreatedAt:Month and Product.Category
3. Add Q1 to dashboard, hover and click Add (combine), and select Q2, and save dashboard.
4. Hover dashboard card in the 2019-end (Q2), click to drill-through, all actions will lead to Q1, but Q2 filters are applied, which could mean that you're seeing different results.

If you're not using the same structure for both questions, then it will result in error. Sample Dataset:
1. Q3: Products > Summarize: Count by CreatedAt:MonthOfYear and Category
2. Q4: People > Summarize: Count by CreatedAt:MonthOfYear and Source
3. Add Q3 to dashboard, hover and click Add (combine), and add Q4, and save dashboard.
4. Hover dashboard card, click any of the series from Q4 to drill-through, all actions will lead to Q3, which returns an error, since the filters are applied to Q4.
