### ISSUE TITLE
metabase geojson error

### ISSUE THREAD

**Issue by mohanrajanonymousallegator** [metabase/metabase#11449]
i am trying to add custom map to the metabase and i have my geojson file here https://github.com/mohanrajanonymousallegator/anonymous/blob/master/india_states.json
when i try to load the data i am getting an error like this
Unable to parse resource at URL `https://github.com/mohanrajanonymousallegator/anonymous/blob/master/india_states.json` as JSON
can anyone help with this issue 
thanks in advance

**Comment by flamber** [comment]
Hi @mohanrajanonymousallegator 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You are linking to a website. You need to link to the actual file, click the Download-button.
It's going to be very slow, since it's 13MB, so you should simplify it with https://mapshaper.com/
And please close this issue :+1:

**Comment by mohanrajanonymousallegator** [comment]
Thank you very much @flamber
