### ISSUE TITLE
"Try it" button broken for native query parameters

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#11481]
On `master`, on stats.

1. Create any sort of native query.
2.  Click the variables button -> Help -> one of the `Try It` buttons.
3.  Run query. Works as expected
4.  Click a different `Try It` button.
5.  Cannot run the query

![MetabaseParams2](https://user-images.githubusercontent.com/1455846/70484433-aa271900-1aa0-11ea-80e7-785e260236f3.gif)

**Comment by camsaul** [comment]
it seems like it has something to do with the second example being a Field Filter, it's not setting it correctly.

**Comment by flamber** [comment]
It's only changing from the Help-tab to Settings-tab on the first click, so manually changing to the Settings-tab after the first click exposes the required options (in case of clicking Field Filter "Try it" as the second click).
I enabled the Field Filter "Try it" a long time ago, since it was commented out (and I didn't understand why), but this might have been the reason. Dang it :man_facepalming: 
The Field Filter "Try it" should probably select the field, since it's a try-it-button...
