### ISSUE TITLE
Metabasev0.34.0：Android WeChat Browser Stuck on Pie Chart

### ISSUE THREAD

**Issue by iiAt-ch** [metabase/metabase#11591]
Metabasev0.34.0：**Android WeChat Browser** Stuck on **Pie Chart**。Other charts open without problems。

**Comment by iiAt-ch** [comment]
Tested v0.31.2 version without this problems

**Comment by iiAt-ch** [comment]
![Record the screen](https://user-images.githubusercontent.com/28256364/71456482-84a24b00-27d4-11ea-8cf2-9e9e186cbd2f.gif)

**Comment by flamber** [comment]
Hi @iiAt-ch 
Does it work with mobile versions of Chrome or Firefox (or other browsers)?
Does WeChat provide a way to see the browser console for errors, could you provide those?

**Comment by flamber** [comment]
Closing, since I cannot reproduce, but Pie chart has been updated several times in the past couple of years.
If anyone is still experiencing this issue, please include a screenshot, and "Diagnostic Info" from Admin > Troubleshooting, and any other information that can be helpful in reproducing the problem.
