### ISSUE TITLE
Pulse attachments not included when reports contain few columns

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#11640]
**Describe the bug**
If there are more columns than can be displayed in the body of a pulse, Metabase will provide an attachment. But, if there are just more rows than can be displayed, Metabase does not provide an attachment. This means that if I want to send a pulse with just one or two columns and I expect greater than 20 rows, the only way to allow an external user to see all the rows is to add enough extraneous columns to trigger the creation of the attachment.

**To Reproduce**
1. Make a report that has just two columns on it but several hundred rows (too many to fit in the body of the pulse email)
2. Attach that report to a pulse and send the test email. No attachment will be included, and thus users can't get access to all the rows without clicking through to the original question (which is impossible if the pulse is sent to an external user).
3. Modify the original report to include more columns than will fit in the body of the email.
4. Send the pulse again to see how the attachment now appears

**Expected behavior**
I'd expect that pulses should include an attachment containing all the rows regardless of the number of columns in the report.

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.9.41-moby",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "7d81ff4"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Severity**
Adding extra columns is a functional workaround, but it creates needlessly complicated reports both for report creators and, more importantly, for the external customers who are relying on them.

**Comment by flyingmachine** [comment]
Hi @nickhamlin!

I've looked into this and here's what I've found:

1. If metabase determines that your pulse is showing a table (as opposed to, say, a bar chart), then it will automatically include a CSV attachment if the table has more than 10 columns or 20 rows. Since your data is returning hundreds of rows, MB should be adding a CSV attachment. Could you confirm that the pulse you're sending is a table and not a chart? (I'm assuming that it is indeed a table since data gets attached when you add columns, but I just want to be sure. I'm going to continue trying to reproduce the behavior you're describing.)

2. You can configure the pulse to _always_ include a CSV attachment by clicking the paperclip icon for the Question you want to include in the post. I've attached a screen shot which shows the paperclip highlighted, meaning the question's data will be included as a CSV. Could you try this and confirm whether it works for you?

<img width="641" alt="Screen Shot 2020-01-07 at 3 06 03 PM" src="https://user-images.githubusercontent.com/1421/71925883-16f50800-3160-11ea-9671-5c1e26313803.png">


Thanks!

**Comment by flyingmachine** [comment]
OK, after looking into this a little more I can see that MetaBase guesses that your Question should be rendered as a bar chart if a) there are only 2 columns and b) the second column is numerical. In this case probably your best bet is to turn on attachments manually - hope this helps :)

**Comment by nickhamlin** [comment]
@flyingmachine Thanks for taking at look at this! I didn't realize there was a way to specifically force the CSV attachment, and I've confirmed that that solves our problem. Much appreciated!
