### ISSUE TITLE
Handle large Slack channel lists

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#11735]
#11509 noted read_timeout errors that could occur when trying to list Slack channels in pulses if there are a lot of channels. We should make sure that large numbers of Slack channels don't cause issues for folks.

Per @salsakran's [comment there](https://github.com/metabase/metabase/pull/11509#pullrequestreview-340854104).

>This will require
> - modifying the UI widget to scroll/paginate
> - updating the frontend fetching to be page aware
> - extending the api to return a specific page.

**Comment by rohilsurana** [comment]
@kdoh @salsakran can you guys help understand how the UI widget would function with pagination. Since Slack API doesn't seems to have a query or search parameter I am unable to understand how search would work in UI widget with pagination. In case you guys have some example that would be great.
We have been facing the read timed out issue, and the only way for us was to increase the slack timeouts to 2000ms [1].

[1] https://github.com/metabase/metabase/blob/master/src/metabase/integrations/slack.clj#L43

**Comment by camsaul** [comment]
Fixed by #13105
