### ISSUE TITLE
joins across multiple tables

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1173]
one of the biggest feature requests here is the ability to join more than one hop from the starting table. usually in filters, but sometimes in group-bys too. i know this is a nontrivial feature, but i can imagine it would be at least somewhat doable, UI wise, by just including connections in the filter column list, and collapsing when necessary if you keep following foreign keys. (and when rendering the filter "chip.")

background: i've been doing "metabase office hours" here for the last couple days, and i've collected a handful of bug reports/feature requests. i'll try to search first to make sure i don't dupe existing issues, but apologies in advance if i do.

people are loving metabase here, btw! here are a few messages i've gotten on slack, verbatim:

> hey! everyone is raving about metabase, but my invite is not working. i want in on the new hotness! any chance i can get another invite?
> oh wow nice! this thing is impressive. i _love_ that you can do raw sql!
> holy crap metabase is amazing :rainbow: :sparkles:

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by GuillermoBlasco** [comment]
Well, actually #1177 is going to solve it whilst you start the answer with the middle table. Ieus est B in the diagram:

    A => B => C

I think it would be nice to be able to reach C from A. In the case of my company from Product to BroadCategory:

    Product => VeryFineCategory => SomewhatFineCategory => GeneralCategory => BroadCategory

Because of our normalised schema we are not able to answer product questions about broad categories.

By the way, here we are engaging with metabase too :smile_cat:

**Comment by pygeek** [comment]
+1

**Comment by iwaffles** [comment]
+1

**Comment by tbeseda** [comment]
I think this proposal is relevant to a feature we'd like.
I'll give an example:
We have `User`s that have one `Subscription` that has many `Delivery`s. We'd like to find out how many of last week's deliveries were to "VIP" users (tracked in the users table).
```
deliveries => subscriptions => users
```
Currently (v0.13.2), we can't get a count on deliveries based on user attributes.  
(Of course, we could if deliveries had a foreign key for `users`, but I think this is a good example regardless.)

Hope the example helps.

**Comment by anaptfox** [comment]
+1

**Comment by adamthehutt** [comment]
+1

For Metabase to be useful for us we need to be able to query across arbitrary depth. An example:

donation => monthly pledge => donor => address

If I want to know the total sum of donations received via monthly pledges from donors who live in zip code 10001, this is the referential chain I need to follow.

**Comment by mdwongca** [comment]
+1

**Comment by gauravarora** [comment]
+1

**Comment by shrav** [comment]
+1

**Comment by stephenjwinn** [comment]
+1

**Comment by MrMauricioLeite** [comment]
Guys, I think 1 extra level of connection is ok, but more then that can slow thing down a lot.

The way it's designed today is perfect if you have an actual datawarehouse in relational database for rOLAP querys. Where one fact table always connect to a dimenson.  If we add another level of FKs, it can help with outriger dimensions and some extractions of the OLTP database but it can potentially slow your queries a lot, depending on how big is your database and how bad your users filter.

The best sollution for me is to create a View on your OLTP database that can connect with other FKs in 1 join, in the most with 2 if aded to the source.

(remembering, that's just my opinion. Feel free to ignore me) =)

**Comment by salsakran** [comment]
Hey gents, check out the design in https://github.com/metabase/metabase/issues/2214

It's an admin function but should cover some of the functionality that N-way joins provide

**Comment by MrMauricioLeite** [comment]
Man, that sure solves the problem. It's almost like a fancy view creator and it looks awesome.

**Comment by marcoruggine** [comment]
Hey guys, we've just implemented Metabase as our BI platform and we are simply blown away by it's semplicity... big up for your work!

This said, I'd like to join this discussion by adding my two cents: 

Right now we have users, searches and purchases on 3 different tables, it would be great to be able to combine all these data so that we're able to understand who is searching what/where and whether they'll end up buying or not.

**Comment by jakudlaty** [comment]
+1000 :)

**Comment by julien-gm** [comment]
+1

**Comment by mamaya881** [comment]
+1

**Comment by DiegoZurita** [comment]
+1

**Comment by bardusco** [comment]
+1

**Comment by MathiasDL** [comment]
+1

**Comment by DiegoZurita** [comment]
+1

**Comment by bertrandjamin** [comment]
+1 plz to avoid switching to quickly on SQL query 🙏

**Comment by AWMooreCO** [comment]
+1

**Comment by shwhl** [comment]
+1

**Comment by pierrerigal** [comment]
+1

**Comment by felarof99** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by kjohannessen** [comment]
Linking through Foreign keys should be a major priority! For non technical users ID's don't mean anything. The GUI for Filters already provides this feature .. just add the same feature to "Customise this table" +1

**Comment by aswinkp** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by larsboehnke** [comment]
+1

**Comment by Pedroglp** [comment]
At least, It would be good to some basic calculations with question numbers at the dashboard, I think this could be easier and solve most of the questions.

**Comment by mordillo123** [comment]
+1

**Comment by dawoodjee** [comment]
+

**Comment by steverowland** [comment]
This is really a must! Way more important than collections etc. We've been using trevor.io -> the way these guys did it is really awesome - hope to see something similar in metabase one day.

**Comment by lwqcz** [comment]
Hi there, please can you tell us how this feature stands on priority list of new features or at least any kind of roadmap for this one? Please. Thnx.

**Comment by jornh** [comment]
Hey everyone posting `+1` etc. comments. See this https://github.com/metabase/metabase/issues/1173#issuecomment-290491594 and https://github.com/metabase/metabase/issues/1173#issuecomment-298380086 - similar posts (which are all buried in `+1` and `when can I have this? pleeease` comments). 

Each time someone posts to this issue you are essentially sending spam to (currently) 33+ subscribers to this issue. (Also, a kitten 🐱 might die ...)

If you want to know priorities - you can:

- sort issues by 👍 votes - like this search: https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc - also easy to do yourself, after clicking `Issues` above (still note 👍's is *one* factor in prioritizing)
- look at the GitHub Roadmap - on the `Projects` button above: https://github.com/metabase/metabase/projects  (which currently is - short term - overruled I think by the team putting together a good v0.30.1 fixing as much high priority small stuff after a **big** v0.30.0 as possible)
- find posts on Discourse about how the Metabase team operate (I'll try to dig some of those up later and update here, unless someone beats me to posting that on Discourse)


**Note:** This is *not* to pick on anyone in particular. Just to post this info in a highly visible place. I'm *not* in a bad mood today 😄 - since you cant see my face it's actually got a slightly smirky, but contempt smile on right now. Trust me on that! Also note: I'm not a team member. Just a - currently, but it can change - pretty engaged Metabase user as you.

**Comment by captainbob** [comment]
now, i only  have one step when make a new dataset . it is simple but nested dataset can't be joined. 
so i think we need more steps to get a dataset. like we can have a join step, then choose the joind dataset, it is really flexible!

**Comment by tlrobinson** [comment]
Hey everyone, we're excited to share a preview of next version of Metabase which has a more powerful graphical query builder that allows you to create joins, do post-aggregation filtering, or multiple stages of aggregating, and more. We'd love to get your feedback. More details on the here: https://metabase.com/blog/a-query-for-your-thoughts/index.html

**Comment by salsakran** [comment]
closing this since it's been merged into master.
