### ISSUE TITLE
Add Native SQL Editor template tags to reuse previous questions as CTEs/subselects

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#11804]
There have been many requests for a better way to organize subqueries and SQL snippets. 

We should add a native template tag that allows the reuse of a previous question as either a subselect or CTE.

Proposed syntax
```
With {{#55}} AS DailyActiveUser
SELECT count distinct(id), day) from DailyActiveUSer
```

Here `#55` would have the generated SQL for a question inserted at that point.

**Comment by tlrobinson** [comment]
Would this include a way to add native "steps" to the notebook? Something like (not sure about the syntax)

```
WITH {{#previous}} AS previous
SELECT ... FROM previous
```

**Comment by sbelak** [comment]
I think CTEs are just boilerplate here.

**Comment by walterl** [comment]
Here's what I think needs to happen:

1. Add MBQL support for the `WITH ... AS ...` syntax
2. Generate native queries for that MBQL, where CTE is "populated" with referenced question's query.
3. Test the crap of it, on all databases.

Does that look correct?

Is there any UI work required?

**Comment by salsakran** [comment]
For frontend work- 
For other template variables, we include them in the sidebar.

@mazameli @kdoh how do you think this new template tag should be treated? 
Another option would be to just have the variable name in the tag, and select the question in the sidebar. I can't tell if the simplicity of just saying `{{#55}}` overrides the cryptic nature of a raw number?

**Comment by mazameli** [comment]
I'm biased towards the improved inspectability that would be provided by selecting the question in the sidebar. I have no idea what `{{#55}}` references unless I punch `/question/55` into the browser and open the question up. 

And when you're writing a new query where you want to include a template tag like this, unless you already have the question you intend to reference open up in another tab or have its ID number memorized, I _think_ it would be preferable to navigate to that question and select it via a popover in the variables sidebar rather than opening up another tab and using search/collections to navigate to it in order to look up its ID.

**Comment by sbelak** [comment]
Ideally it would be the question name, not it's ID in the tag, but renaming complicates things.

@walterl: MBQL doesn't need to be updated for this (it already supports nested questions), just the query processor.

**Comment by salsakran** [comment]
Names are a non-starter -- Question names are neither currently guaranteed to be unique, nor could we possible expect them to be unique across collections run by different teams.

**Comment by tlrobinson** [comment]
> Another option would be to just have the variable name in the tag, and select the question in the sidebar. I can't tell if the simplicity of just saying {{#55}} overrides the cryptic nature of a raw number?

One possible way to get the best of both worlds:

1. You start typing `{{#` and we pop open the sidebar with a question picker
2. You can either:
    a. Continue typing a question ID, or
    b. Use the question picker in the sidebar to select a question. Once you select a question we replace the `{{#}}` with `{{#55}}` in the query text
3. You can later decide to change the question by using the sidebar, and we update the query text again.

**Comment by walterl** [comment]
As a start I got it working with a sub-query like syntax: `SELECT x.* FROM {{#123}} AS x`.

@salsakran How set are you on the CTE-like (`WITH {{#123}} AS x...`) syntax?

**Comment by salsakran** [comment]
uhm ... I'm somewhat set on not having to write `SELECT x.* FROM blah AS X` -- that's some J2EE level of boilerplate. =)

**Comment by walterl** [comment]
@salsakran I'm not quite following. `WITH {{#123}} AS x SELECT x.*` and `SELECT x.* FROM {{#123}} AS x` would be equivalent - no real difference in the amount of boilerplate. What is it in the `WITH...` syntax that you want to keep?

Although I'm not sure if sub-queries are executed the same as CTEs by the database. @sbelak @camsaul Are you aware of any DBMS-level reason to prefer one over the other?

**Comment by salsakran** [comment]
The purpose of template tags is to use these as building blocks in constructing complicated queries. My expectation is that you'd be able to do things like

```
WITH {{#123}} as DAU
WITH {{#124}} as DailyRevenue

SELECT d.day, d.value/dr.
FROM DAU d join DailyRevenue dr ON d.day=dr.day
GROUP BY d.day
ORDER by d.day
```

The `WITH` statement lets you have a fairly self-contained set of "imports" statements that can be easily scanned and worked with vs a big mess of a SQL template. My conviction on this is ~90%

**Comment by sbelak** [comment]
Performance wise they should be the same for any sane DB. CTEs give you the option of recursive queries, but this is not particularly relevant here. 

I’d compile to a CTE for debug readability, but just behind the scenes, the user would write a plain select.

**Comment by tlrobinson** [comment]
@walterl @salsakran Any reason `SELECT * FROM {{#123}}` shouldn't just work as well? (in addition to the CTE syntax)?

**Comment by sbelak** [comment]
@tlrobinson it should work in both cases. What you put after `AS` is just a select.

**Comment by walterl** [comment]
@tlrobinson No, you're 100% correct. It does work both ways. :slightly_smiling_face:

**Comment by walterl** [comment]
Template tags from referenced queries should be automatically inherited, right?

**Comment by walterl** [comment]
How should we handle template tags from referenced queries? My gut feel is that the current query should inherit them (dynamically), but that will have consequences:

* Whenever a question is referenced, we'll need to fetch the relevant card instance via the API, parse the result for template tags, and display the relevant UI for them.
* Values for inherited tags would need to be determined, and we'll need to decide how to transmit that back to the API, together with the current query and its tag data.
* We'll probably need to visually differentiate inherited template tags, so that they're not confused with the current query's tags.
* Circular references will have to be avoided.

This represents quite the mushrooming of functionality and code, but if we don't inherit template tags, we effectively limit the set of referencable questions to those without template tags. That seems like an odd and artificial limitation from a user's point of view.

**Comment by salsakran** [comment]
I think this might be better done in stages, and skip inheriting template tags for this stage. 

The assumption here isn't that people will use any arbitrary saved question in another one, but rather that a common set of useful saved questions will get built up to simplify writing nested queries.

**Comment by tlrobinson** [comment]
Good question.

First of all, to clarify our nomenclature:

1. **Questions**  can expose filterable **Dimensions** (i.e. an underlying field that can be filtered) and **Variables** (a simple value that can be filled in) via their query
    * **Structured Query** has implicit **Dimensions** based on the query's table, joins, etc. It doesn't currently support **Variables**.
   * **Native Query** exposes **Dimensions** and **Variables** via **Template Tags** (`tag.type` of `dimension` for the former, `text`/`number`/`date` for the latter)
2. **Dashboards** and **Questions** can have **Parameters** which can be mapped to a **Dimension** or **Variable**
     * Dashboards have explicitly added **Parameters**, which are mapped to each Question's **Dimensions** or **Variables**
     * Questions based on **Native Query** have their **Parameters** implicitly created based on **Template Tags** (**Dimensions** and **Variables**) 
     * Questions based on **Structured Query** don't currently have **Parameters**

3. **Native Queries** can have  **Template Tags** with different types that do different things:
    * `text`, `number`, `date` expose "variables" on the question, which can be mapped to dashboard parameters, and create an implicit question parameter
    * `dimension` exposes a filterable "dimension", which can also be mapped to dashboard parameters, and create an implicit question parameter
    * this new type of subquery tag which isn't related to **Dimension** or **Variable** (i.e. can't map a **Parameter** to)

We don't currently inherit any of these things when doing nested queries via saved question.

If we did want to do some type of inheritance, I *think* we'd want to inherit **Dimensions** and **Variables** or **Parameters** rather than **Template Tags**, since they are agnostic to whether the source question is **Native** or **Structured**.

Alternatively, it might be neat if when you use a subselect you could hardcode a value, basically like calling a function. One possible syntax:

```
SELECT * FROM {{#1:user_type="admin"}}
```

 (`user_type` would be either a **Parameter** or **Variable** on question 1)

Maybe you explicitly could "proxy" them too via nested tags?

```
SELECT * FROM {{#1:user_type={{user_type}}
```

Or maybe shorthand to proxy them:

```
SELECT * FROM {{#1:user_type}}
```

We should probably move this to another issue.

**Comment by walterl** [comment]
@tlrobinson Thanks for that great description on the nomenclature. I'm going to have to re-read it a few times.

Your proposed syntax looks really cool. I agree that we should move that to another issue, though.
