### ISSUE TITLE
Configure output destination for query results

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [metabase/metabase#11881]
Can Metabase be configured to output data to S3 or some path? I want to enable the customer to run queries, but save their results to an S3 path of their choosing.

**Comment by flamber** [comment]
Hi @aidan-plenert-macdonald 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
I'm not quite sure what you mean by saving the results - do you mean instead of downloading a CSV via the browser, then the file is saved to S3 instead - if yes, then you might be able to do something with reverse-proxy by modifying the request.
