### ISSUE TITLE
Metadata query_execution.dashboard_id is not being filled

### ISSUE THREAD

**Issue by vitorhirota** [metabase/metabase#11909]
If a question is executed as part of a dashboard, the `query_execution.dashboard_id` field is not being filled.

This is somewhat related to #5570.

**To Reproduce**
1. Open any dashboard
2. Check `query_execution.dashboard_id` for the latest  records, verify there are n records of questions executed, no dashboard_id information

**Expected behavior**
Have the dashboard_id info filled. A specific context value ("dashboard"?) might also be interesting.

**Screenshots**

![image](https://user-images.githubusercontent.com/1316133/74477438-126fed80-4e8a-11ea-932e-9f07dcdd9c32.png)

**Information about your Metabase Installation:**
Metabase version v0.34.0

**Comment by camsaul** [comment]
Not sure this is really a bug because this table is used internally and not user-facing. We intended to populate that column when we first added the Table but to do so we need some way to know what dashboard a Card was executed from, either by adding a new endpoint specifically for executing cards inside a dashboard or by having the FE client pass the dashboard ID along when executing a query.

**Comment by lukeman** [comment]
I noticed while poking around the internal DB on v0.39.4 that @flamber's observation about public dashboards populating the `dashboard_id` field in `query_execution` still holds true: https://github.com/metabase/metabase/issues/5570#issuecomment-583403356

I see proper `dashboard_id`s for both public and embedded dashboard contexts, so it seems that the null dashboard id case is limited to executions from standard authed dashboard views.

**Comment by flamber** [comment]
This was added in 0.41
