### ISSUE TITLE
Drill-through without data permission - should that be possible?

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#11914]
**Describe the bug**
Users without data permission and trying to drill-through a dashboard question, just sees a spinner and there's an error in the log.

**To Reproduce 1**
1. Create user with no-data permission, view-only collection.
2. Create a Simple question of Sample Dataset > Orders, and save to dashboard
3. Login with no-data user, access dashboard, try to drill-through the question (i.e. Quantity = 2)
4. Shows `Sorry, you don’t have permission to see that.` (frontend) / `You don't have permissions to do that.` (backend)
![image](https://user-images.githubusercontent.com/1447303/84762198-cd400180-afca-11ea-973e-46d1604b334d.png)

**To Reproduce 2**
1. Login as no-data user and go to the question created previously in Repro1.Step2
2. Try reordering the columns, or sorting one of the columns
3. Similar error as Repro1.Step4

**Information about your Metabase Installation:**
Tested 0.34.2 thru 0.41.2

**Additional context**
https://discourse.metabase.com/t/drilldown-option-without-data-permission/8708

I'm not sure if drill-through should even be possible, when user doesn't have data permission.
Tested 0.32.10 and in that version the drill-through are disabled, so something changed in 0.33+

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by antoineverger1** [comment]
It's a pretty serious issue for us. We were allowing users with no data permission but a view-only collection to drill through from a dashboard or even directly accessing the questions and now they can not do that anymore. 

To make it work, we are forced to give data permission which we obviously don't want to do since it means allowing them to access data that we might not want them to use.

**Comment by antoineverger1** [comment]
If it's a way to enforce the Enterprise product, it's pretty smart and evil at the same time !

**Comment by flamber** [comment]
@antoineverger1 
Which version did drill-through work with no-data, view-collection permissions?
If it is a regression, then I'll look into that. Please provide as much information, so I can reproduce.
Existing functionality will not suddenly break in a plot to force you to buy the Enterprise Edition.

**Comment by antoineverger1** [comment]
Hey @flamber, we love the product and we are evaluating the enterprise. My bad for the bad joke.

Anyways, I am trying to narrow down the issue on my local system using a different version.

On our side, the case might be slightly different. We have a user belonging to a group that has a "view collection" permission on a subcollection. At the same time, the group has no data permission.  This collection has one question. Til 0.34.1, the user could access the question but since 0.34.2, the spinner keeps spinning and I see a "You don't have permissions to do that" in the network logs for the query_metadata.

Should I create another issue?
Is that enough info?

**Comment by flamber** [comment]
@antoineverger1 Well, it would be Dr. Evil level of cruelty - not really what we're trying to do :-)
It sounds a bit like #11028, but not quite.
Steps to reproduce and errors are extremely helpful. But yes, you should create a new issue, since it sounds like a more general permission problem than only drill-through.

**Comment by antoineverger1** [comment]
@flamber I know. I love the project, even makes me evaluate doing some Clojure :D

Here is the freshly created issue : https://github.com/metabase/metabase/issues/11932

I am gonna downgrade my prod to 0.34.1 to work around the issue and since I don't see any DB migration in the milestone, I guess it's fine. Would you mind confirming me that it's fine?

**Comment by flamber** [comment]
@antoineverger1 I'll have a look at the other issue.
Downgrade should be fine to 0.34.1, but always make a backup before upgrade/downgrade.

**Comment by flamber** [comment]
Since 0.35.0 it now displays a permission error page `You don't have permissions to do that.`  instead of loading spinner.
![image](https://user-images.githubusercontent.com/1447303/84762198-cd400180-afca-11ea-973e-46d1604b334d.png)
