### ISSUE TITLE
Join UI picks the first schema even if a different one is selected

### ISSUE THREAD

**Issue by CaliLuke** [metabase/metabase#11958]
I'm running into a problem where I'm trying to build a query with multiple joins.

I have a database with three schemas and the same table names:

DB
 - schema 1
 - schema 2
 - schema 3

When I pull down the selector and pick "schema 3" the selector ignores it and shows me a list of tables in "schema 1".

This happens after the second join, the first two work fine.

![2020-02-22_15-18-55](https://user-images.githubusercontent.com/73209/75100736-b6425300-5586-11ea-876e-2f405e1664f2.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @CaliLuke 
Please post "Diagnostic Info" from Admin > Troubleshooting.
Do you see any errors in the browser console, when it starts showing tables from a different schema?

**Comment by emilythacher** [comment]
Just jumping in to say I've also experienced this. I'll pull the logs if it happens again. I did not receive any error messages. When in the same window without refreshing, I experienced the same problem about 4 times in a row (took me a few tries to be sure it wasn't that I was clicking the wrong thing...). For me, it only happened when I searched the schema name I wanted, then clicked it in the reduced list. That meant it was showing me results for a schema that had actually not been available to click at the time I clicked. However, I observed no issue when I scrolled down the list and clicked the schema I wanted rather than searching then clicking. The problem was also resolved on refresh.

**Comment by flamber** [comment]
@emilythacher If you can do a screen recording, then it might help to understand what's going on, since you say it's not generating any warnings/errors in the browser console.
I'm wondering if you are seeing something like this issue #11571 ?

**Comment by emilythacher** [comment]
@flamber yeah I'll try to record it if it happens again, but I'm not sure how to intentionally reproduce. 

It does actually look similar to #11571. I can't tell for sure what's happening in that recording, but it looks like it might be the same behavior of showing the tables in the first item in the list, regardless of which is clicked.

**Comment by emilythacher** [comment]
@flamber I actually was able to reproduce, but I don't think I can share the screen recording since it would show private information on our company's data. I'm happy to clarify anything if needed though.

**Comment by flamber** [comment]
@emilythacher Does it look like #11571, where clicking around in the Data Selector suddenly shows you a different schema/collection than you clicked on - and going back, clicking again might show the correct one second time?
Since you cannot show it, then you would have to explain it in a lot of details. Unless we get information that we somehow can reproduce, then it's very difficult to fix issues.

**Comment by emilythacher** [comment]
@flamber Same as what @CaliLuke was saying. In order to join a dataset in the query builder, steps are typically: 

1. Click the join data icon, causing new row for the join to pop out with illustration of previous dataset, join type, and selector for choosing what data you want to join. The selector has a search ("Find...") at the top, followed by list of schemas below. 
2. EITHER:
a) Type into search bar, causing list of schemas to dynamically narrow, OR
b) Scroll down to find the schema you want
3. Click schema you want
4. List of tables within clicked schema appears
5. Click table you want, and progress to indicating what fields to join them by

This process would be the same for the 1st, 2nd, 3rd, etc. join you add to the builder. 

I've seen that if I'm on the 3rd or 4th join (meaning the original data, plus three or four additional joins), I get the error. The error is that _if_ I choose 2a (search) rather than 2b (scroll), the list of tables that pops up in 4 is _not_ the list of tables in the schema I clicked on, but rather the first option in the list that shows based on step 1. For example, if schemas were Analytics, Inventory, and Sales, and I typed "Sal" in the search bar to narrow the list to just the Sales schema, then clicked Sales schema, it would then show me the list of tables in the Analytics schema. I would not observe this error if I did 2b (scroll) rather than 2a (search). 

I tested this with the Metabase database and observed no issue up to 6 joins. I observed the error for queries from both a Redshift and PostgreSQL databases.

**Comment by stephaneDelos** [comment]
Same Error for me

**Comment by flamber** [comment]
@stephaneDelos 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And can you provide a video of how it looks?

**Comment by landreville** [comment]
Here's the diagnostic info from when this happened to me
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "3.10.0-1062.4.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.34.1",
      "date": "2020-01-13",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}

```

And a screen grab of it happening:

![ScreenGrab](https://user-images.githubusercontent.com/24076/83283179-c763b700-a1a8-11ea-8252-f76bbb9127c0.gif)

**Comment by flamber** [comment]
Thank you @landreville :heart:
I can definitely see the problem, but I cannot reproduce on `master`, which is the upcoming 0.36.0
I haven't tested on 0.35.3/0.35.4 yet.
Do you see anything in the browser developer console?

**Comment by landreville** [comment]
Nothing in the console and nothing in the Metabase log output.
