### ISSUE TITLE
We don't properly communicate that you can't get more than 2,000 rows in the UI via the limit widget

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12188]
**Describe the bug**
Setting the row limit doesn't seem to have an effect when querying for a data table. Note that this is expected behavior (from a backend perspective) because there's a different "max rows constraint" that takes precedence over `:limit`. 

**Logs**
No relevant console or server logs. This is the XHR request that gets sent to `/api/dataset`
```json
{"type":"query","query":{"source-table":2,"limit":3000},"database":1,"parameters":[]}
```

The response I get back only includes 2,000 rows even though the table has 18,000 rows. This is the JSON response without the `data` block.

```json
database_id: 1
started_at: "2020-03-24T16:23:55.815216-07:00"
json_query: {type: "query", query: {source-table: 2, limit: 3000}, database: 1,…}
average_execution_time: null
status: "completed"
context: "ad-hoc"
row_count: 2000
running_time: 658
```

**To Reproduce**
1. Go to Sample Dataset --> Orders
2. Change the limit of rows either by clicking the "Showing first 2,000 rows text" or by changing the row limit in the notebook editor
3. Run the query
4. Observe that the query still says "Showing 2,000 rows"

**Expected behavior**
Except that the desired number of rows is returned.

**Screenshots**
This is a screenshot of the result table after the query has run. You can see I requested 20,000 rows, but only 2,000 get returned.
![image](https://user-images.githubusercontent.com/1512/77486409-efbbe780-6dec-11ea-805f-b841d9b71a3a.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "10.15.3",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "redshift",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-03-18",
      "tag": "v0.35.0-rc1",
      "branch": "master",
      "hash": "943e667"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Critical

**Additional context**
Related #1546

**Comment by camsaul** [comment]
context from slack convo:

here's how it works:
1.  queries have a "max rows constraint" of 2k for viewing in the GUI
2.  queries have a "max rows constraint" of ~1 million for downloads
3.  if you specify `:limit`, we pick the lower of limit/max rows constraint and use that as the LIMIT in the complied SQL query

Sort of a wacky way of doing things IMO but this is the way it's worked since basically forever. 

You can override the default constraints if you want > 2000 rows by adding 

```clj
{:constraints {:max-results-bare-rows 3000}}
```

to your query.

So that's one option for addressing this issue. 

Another option is having the UI clarify that the limit is still subject to the 2k/1m constraints.

A third option is taking out the `:constraints` stuff entirely and using `:limit` for everything which I am happy with too, I personally never liked having the `:constraints` key in the first place

**Comment by camsaul** [comment]
Personally I think we do need some sort of maximum value for the limit (e.g. under no circumstances should we be letting people fetch a billion rows for display in the GUI, because while it wouldn't affect the backend now that the responses are streaming, you would make your browser explode for sure). And I think the maximum value for limit is something that we should be communicating in the UI.

So whether or not we apply a maximum value to `:limit`, or keep the `:constraints` key, we still need to advertise this in the UI

**Comment by kdoh** [comment]
Sounds like this is more of a UX issue rather than a bug then unless I'm reading things wrong?

**Comment by dacort** [comment]
@kdoh Yea, you're correct. When I first filed this I thought it was an actual bug, but turns out just UX. It's confusing for me to be able to set a limit, but then only get back a partial result.

**Comment by kdoh** [comment]
I might rename this then so it's easier to get that from the title without having to have the conversation context.
