### ISSUE TITLE
data loss on docker restart 

### ISSUE THREAD

**Issue by ranjanmishra07** [metabase/metabase#12201]
`version: "3"

# All available services
services:

  # Misc Storage
  postgres:
    container_name: "data-engine_postgres"
    restart: "unless-stopped"
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB:<db>

  metabase:
    container_name: "data-engine_metabase"
    restart: "unless-stopped"
    image: metabase/metabase
    volumes: 
      - metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME:name<>
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS:<pass>
      MB_DB_HOST: postgres   
    ports:
      - 80:3000

# Volumes to persist data
volumes:
  postgres-data:
  metabase-data:`

Hi, this is my docker-compose file 
Whenever i stop metabase container and rerun (do docker-compose up again) then all my reports and settings and data in metabase gets lost and i am sent back to metabase setup screen again . It happened with me on production .
even i am doing the volume mapping correctly , because postgres data didn't got lost when i restarted postgres container .
Is there a bug with metabase docker or do i need to do some changes in here .
Thanks

**Comment by flamber** [comment]
Hi @ranjanmishra07 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It sounds like Metabase is not getting the `MB_DB_***` environment variables, so it's started using H2 instead of Postgres. Check the log during startup for more details.
And you don't need any volumes if the variables are read correctly.
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#using-postgres-as-the-metabase-application-database

**Comment by AshutoshAM2002** [comment]
Got the same issue, my production data was also lost. Not getting where is the data stored in docker volumes.
