### ISSUE TITLE
Pulses are sent with non-updated data

### ISSUE THREAD

**Issue by LeviPorto** [metabase/metabase#12392]
# Describe the bug
Our customer have about 3000 pulses configured to be triggered per day (different hours, but, the most are configured to be triggered 10 UTC). Every day, some pulses are sent to emails with non-updated data (data with values that appeared time before). I checked 10 min before and at the same time on pulse screen and shows correct data, but is sent to email with past data (see attached images, to a better visualization)

# Logs
[pulse_log.txt](https://github.com/metabase/metabase/files/4530817/pulse_log.txt)

# To Reproduce
1. Create many questions
2. Configure pulses to be triggered on specific time, putting questions inside it (for example, count of one register, using group by)
3. Record on pulse screen at 10 min and on exactly moment that will be sent
4. See on email that was sent non-updated data

# Expected behavior
Data that appears on pulse screen must be exactly data that appears on email

# Screenshots
![pulse_image](https://user-images.githubusercontent.com/13751358/80244280-0b5e1c00-863f-11ea-9cb5-cdf068e73f95.jpg)

On the left is pulse that was sent to email and on the right, pulse viewed at the same time that trigger was sent

# Information about your Metabase Installation

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "4.14.171-105.231.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v1.34.1",
      "date": "2020-01-16",
      "branch": "enterprise-release-1.34.x",
      "hash": "a6df4f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

- Your databases: Postgres
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

# Severity
We are with this problem about three months, with hardly investigation. We already talked to Metabase support, but without any solution for resolve this. Please, consider it with big priority.

# Additional Information
We are with suspicious about data caching. Every time, Metabase sent SQL on the time that pulse are sent? Or there is some data caching involved on this process (with don´t have cached data, we will sent normal question queries, anything about this)?

**Comment by flamber** [comment]
Hi @LeviPorto 

If you prefer to do support here, then we can do that, but otherwise I would recommend the support email.

It seems like it's a different issue than the one that was reported, where pulses were returning `0`.
I didn't get any replies with debug logging a month ago, but I should probably have followed up, so sorry about that.

I think we need to create a debug build, so we can figure out what's going on.

**Comment by LeviPorto** [comment]
Hi! You are right about pulses returning 0, but i think this is the same problem (past data).

The real reason for the problem is because Metabase is showing data that was true some time ago, but at the time of sending the pulse, it is no longer because new data has arrived (it is returning 0 because in the past it was 0, the same placed figures, in the past was the email data)

I will answer you on email, my objective of this issue is make easy to find if anyone on Metabase´s Community has passed to this same problem

Thank you!

**Comment by flamber** [comment]
Hi @LeviPorto 

I totally understand that you want the problem solved and tried to see if the community could help.

I've read 99% of all issues/topic and remember most of them, and I've never seen anything that comes close to what you've been experiencing. And no other customers either, where several of them are sending a lot more Pulses per day.

We can keep this issue open in case someone has comments - otherwise I'll comment, when we've figured out what is going on.

Send a new mail to support and we can continue there, since I'm going to need details about your setup that you probably won't like public.
