### ISSUE TITLE
API `/api/database/:id/fields` returns table display name instead of (real) table name as `table_name`

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#12419]
In the endpoint `/api/database/1/fields` the table names are 'Orders', 'People', 'Products', 'Reviews' (which is expected), but in the endpoint `/api/table` the names are 'ORDERS', 'PEOPLE', 'PRODUCTS', 'REVIEWS' (i.e. they are all in uppercase letters).

This caused issues when I was building tests for my Python wrapper for MB API.

Metabase version: 0.35.3

**Comment by flamber** [comment]
Hi @vvaezian 
It's not related to Sample Dataset, but in general.
`/api/database/:id/fields` returns table display name instead of (real) table name, as `table_name`.
While `/api/table` returns all table information, which includes both (real table) name and (table) display name.
I can see that will likely cause some confusion. Took the liberty to change the title too.

**Comment by vvaezian** [comment]
The same issue applied to the column name. In other words the value of the keys `name` and `table_name` in the output of `/api/database/:id/fields` changes based on the value chosen for `Friendly Table and Field Names` in Admin > Settings > General.
