### ISSUE TITLE
Update Java requirements

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12433]
The documentation of Java could need a revisit.

Proposal:
1. Recommended version is latest LTS, which is currently version 11, but any [supported version](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) should work.
2. Recommended type is AdoptOpenJDK, while Oracle and OpenJDK are supported. (Corretto might not work #9869)
3. Recommended JVM is HotSpot. (OpenJ9 might work, but [might require version 13](https://discourse.metabase.com/search?q=openj9))
4. Only JRE is needed to run Metabase, but JDK is needed for development.
5. "headless JVM" or JVM missing AWT classes, means Pulses does not work #7986

Update references (I don't think there's more locations):
- [/start/jar.html](https://metabase.com/start/jar.html)
- [/start/other.html](https://metabase.com/start/other.html)
- [readme.md](https://github.com/metabase/metabase#jvm-jar)
- [/docs/latest/operations-guide/java-versions.html](https://www.metabase.com/docs/latest/operations-guide/java-versions.html)
- [/docs/latest/operations-guide/running-the-metabase-jar-file.html](https://www.metabase.com/docs/latest/operations-guide/running-the-metabase-jar-file.html)
- [/docs/latest/developers-guide.html#install-prerequisites](https://www.metabase.com/docs/latest/developers-guide.html#install-prerequisites)

Related #12223 #12543

**Comment by camsaul** [comment]
To clarify, we support any currently-supported version of Java 8 or higher. Right now, that means Java 8, 11, and 14. Java 13 is already EOL -- see
https://www.oracle.com/java/technologies/java-se-support-roadmap.html and https://adoptopenjdk.net/support.html. The new Java release strategy is to have a LTS release every 3 years with cutting-edge releases every 6 months that are EOL'ed once the next one comes out.

It's safest to use the most recent LTS release (11), and that's what we're planning on using for our Docker images in the future -- when Java 17 comes out in September 2021 we'll switch to that.

We should recommend people use AdoptOpenJDK+HotSpot, because that's what we use for our Docker image, and what we test with. I've tried OpenJ9 in the past and it worked but I didn't see any performance benefits. Theoretically any JVM should work, but I'm not sure why Corretto doesn't -- we still need to investigate this.

Another thing to clarify: running Metabase with `java.awt.headless` should be fine. Running Metabase on a "headless JVM" *image* that ships without JWT classes will run into problems when you try to send a Pulse. See my comments in #12223
