### ISSUE TITLE
Changing sub-collection permission causes change of permission for all sub-collections and root collection itself

### ISSUE THREAD

**Issue by RomantsovArtur** [metabase/metabase#12489]
**Describe the bug**
If user change archived sub-collection permission it will cause change permission to all other root sub-collections and root collection itself

**Logs**
[log.txt](https://github.com/metabase/metabase/files/4604198/log.txt)

**To Reproduce**
1. Go to /collection/root
2. Click on 'New collection'
3. Create three new collection with 'Collection it's saved in' point to root collection
4. Go to any of created sub-collection
5. Press 'Archive this collection'
6. Without closing the window after step 5 -> Press 'Edit the permission of this collection' and press 'Revoke all user access' on pop-up window
7. See that access was revoked for all root sub-collections and root collection itself

**Expected behavior**
If access was revoked for root sub-collection it wouldn't affect other root sub-collection or root-collection itslef

**Screenshots**
select * from collection_revision;
![image](https://user-images.githubusercontent.com/40241717/81480660-fb3f6280-9222-11ea-8a43-21c96aebed0c.png)
![image](https://user-images.githubusercontent.com/40241717/81480679-15794080-9223-11ea-996f-4bb33e3bf82d.png)
![image](https://user-images.githubusercontent.com/40241717/81480702-2de95b00-9223-11ea-94b9-70fa4e2d2cf5.png)

**Information about your Metabase Installation:**
You're on version v0.35.3
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~deb9u1-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.9.0-9-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.3",
      "date": "2020-04-24",
      "branch": "metabase-revolut",
      "hash": "01ca8d1"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
In case of this situation - all sub-collections lose their permission as well as root collection. That cause incident about accessibility of metabase

**Additional context**
No additional context

**Comment by flamber** [comment]
Hi @RomantsovArtur 
Reproduced on 0.35.3, and like you say, it's important not to do anything like refreshing in step 6.
But I actually think that the real bug is that you're not returned to parent collection (this case root) after you've archived the collection in step 5.
On a side-note, it would be nice if it told you the collection name instead of just "this" #2061

**Comment by nemanjaglumac** [comment]
I can't reproduce this anymore since archiving a nested collection correctly takes me to its parent.

**Comment by flamber** [comment]
It has changed a bit since 0.38.0, but it can still be reproduced.

**Reproduce in 0.38**
1. Admin > People > create user "U1"
2. Admin > Permissions > Collections > set Curate for "All users"
![image](https://user-images.githubusercontent.com/1447303/112055626-6225eb80-8b57-11eb-8456-9ac1582ec416.png)
3. Create a collection "Test" in root collection
4. Go to the collection, click the pencil in upper-right corner > "Archive this collection" (URL is `/collection/:id/archive`) > Archive
![image](https://user-images.githubusercontent.com/1447303/112053877-31dd4d80-8b55-11eb-9ca0-1e2ab9454809.png)
5. The collection is now archived and URL changes to `/collection/root`
6. Click the browser back-button, which takes you back to the collection (`/collection/:id`), which now looks empty, but there is still edit options in upper-right corner
![image](https://user-images.githubusercontent.com/1447303/112054055-62bd8280-8b55-11eb-8f14-c8174766beed.png)
7. Click the lock-icon in upper right corner, click Revoke (including sub-collection toggle) for "All users" > Save
![image](https://user-images.githubusercontent.com/1447303/112054207-94cee480-8b55-11eb-9452-78ac5032836d.png)
8. Nothing seems to have happened, but it has revoked collection permissions for everything except the "Test" collection (and other archived collections).
9. Going into Admin > Permissions > Collections will now show all (non-archived) collections are revoked.
![image](https://user-images.githubusercontent.com/1447303/112055576-50444880-8b57-11eb-97a7-c966dce4096c.png)
10. Login as "U1" and go to `/collection/:id` and it is possible to view that archived "Test" collection - without any content - and it's not possible to view any other collections.
![image](https://user-images.githubusercontent.com/1447303/112054816-5c7bd600-8b56-11eb-9b74-d046d700ad0d.png)

While it seems like a lot of steps to go through now, I'm leaving the P2, since it's still a rather problematic behavior.
