### ISSUE TITLE
Display error with custom expression filter containing dates

### ISSUE THREAD

**Issue by m-vdb** [metabase/metabase#12492]
**Describe the bug**
When using custom expressions in filters with dates, especially when comparing date columns with each other, the display of the filter is broken:

<img width="766" alt="Screenshot 2020-05-11 at 17 44 18" src="https://user-images.githubusercontent.com/1931615/81581507-1d65eb80-93af-11ea-81c2-f9f4880df043.png">

Whereas the underlying SQL seems correct:

<img width="633" alt="Screenshot 2020-05-11 at 17 44 40" src="https://user-images.githubusercontent.com/1931615/81581524-23f46300-93af-11ea-8c66-53d43b3e68fc.png">

**Logs**
<img width="557" alt="Screenshot 2020-05-11 at 17 48 13" src="https://user-images.githubusercontent.com/1931615/81581880-a11fd800-93af-11ea-9c66-b2793a0b9969.png">

**To Reproduce**
1. Create a custom question and JOIN two table, each with a date column
2. Click on the filter section and "Custom expression"
3. Type the first date column, then ">", then the second date column
4. Validate, and see error

**Expected behavior**
I would expect to see a description of the filter, e.g. "Column 1 > Column 2"

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Your operating system: OS X 10.15.4
- Your databases: Postgres
- Metabase version: 0.35.3
- Metabase hosting environment: GCP, K8s
- Metabase internal database: Postgres

**Severity**
It's problematic for non-technical users that won't have the reflex to view the SQL to see if the question is setup properly (and they wouldn't even be capable to read it). For technical users, it's less serious.

Given that we're trying to drive adoption of Metabase, especially for non-technical users, this hinders our efforts.

**Comment by flamber** [comment]
Hi @m-vdb 

I've reproduced the problem - if it was only an issue of it just displaying `[Unknown]`, the easy workaround would be to click the filter to display, but doing that will actually show a calendar widget, because the second date column is converted to a static date string (in the filter widget selector).

Reproduce with Sample Dataset:
1. Simple question (no need to join, the problem is the same for linked tables) > Orders
2. Filter > Custom Expression > `[Created At] > [Product -> Created At]`
3. The SQL is correct (seems to return the correct results), but clicking the filter widget will display the calendar, and going back to Custom Expression the formula is: `[Created At] > "2020-05-11"`
![image](https://user-images.githubusercontent.com/1447303/81584529-23f66200-93b3-11ea-8203-e79deef09a54.png)

**Comment by m-vdb** [comment]
ah yeah exactly, I forgot the second part, you're right. (updated the version number, I filled it off the top of my head 😄 )
