### ISSUE TITLE
Fix UX for the new HTTPS redirect setting

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#12540]
Already discussed this with @robdaemon, but opening this issue for posterity and tracking. This is a 0.36 blocker.

**With the newly merged HTTPS redirect setting, there are two problems:**
1. I can lock myself out of my instance if I set my site URL to start with `HTTPS:` and turn the redirect toggle on if I don't actually have HTTPS enabled where my instance is running.
2. I can turn the redirect toggle on even if my site URL doesn't start with HTTPS, which then doesn't do anything.

~~**What we'd like the behavior to be:**~~
- ~~When I enter my site URL, if I change it to start with HTTPS, we should validate that I do in fact have HTTPS set up by trying to access an image resource or something over HTTPS. If it doesn't work, we should display a friendly error message to the effect of `It looks like HTTPS isn't actually set up for this domain.`~~
- The redirect toggle should be off and un-clickable if the site URL setting is not set to HTTPS, or ~~if the HTTPS validation fails.~~

[New instructions below](https://github.com/metabase/metabase/issues/12540#issuecomment-634140544)

**When should we trigger the HTTPS validation check?**
- Not exactly sure, but maybe: check for `HTTPS` in the site URL string `on-key-up`, and if we find it, do the validation like 500ms after key-up? The idea is that we shouldn't be doing the check at all unless the string starts with https (right?), but even after they do, we don't want an error to immediately show up if they're still typing out the rest of the URL.

**Comment by kdoh** [comment]
After poking at this a bit the real UX issue here is how these two interconnected settings are separated when they should be more tightly coupled since one really does depend on the other.

## This supersedes the instructions above.

1. The site URL setting should have a new display - an input with a select prefix. This option will show either http:// (the default) or https:// and the input will have the site url as its value just like it does now.

<img width="397" alt="Screen Shot 2020-05-26 at 12 39 34 PM" src="https://user-images.githubusercontent.com/5248953/82927011-0944f100-9f4e-11ea-8e9f-d60fec72eac6.png">

<img width="437" alt="Screen Shot 2020-05-26 at 12 39 41 PM" src="https://user-images.githubusercontent.com/5248953/82927046-13ff8600-9f4e-11ea-8365-ea015c8b2ee8.png">


2. If the user switches the prefix to https we should do a quick check, similar to the one mentioned up above (trying to fetch a https resource) to try and verify that https is properly configured.

<img width="422" alt="Screen Shot 2020-05-26 at 12 39 45 PM" src="https://user-images.githubusercontent.com/5248953/82927035-106bff00-9f4e-11ea-8072-728041f04faa.png">

3. If it is, we can then show the force https option, which the user can toggle on. We don’t need to be so verbose here either, a simple toggle and label should be fine.

<img width="431" alt="Screen Shot 2020-05-26 at 12 39 50 PM" src="https://user-images.githubusercontent.com/5248953/82927057-19f56700-9f4e-11ea-8569-3154f605d43d.png">

4. If it isn’t, we should show a little message that https appears to not be configured properly and set the value back to http. 

<img width="424" alt="Screen Shot 2020-05-26 at 12 39 57 PM" src="https://user-images.githubusercontent.com/5248953/82927086-2974b000-9f4e-11ea-99a5-caae9ab3fcae.png">
