### ISSUE TITLE
We should show + New Collection in empty collections

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#12824]
It's hard to create a new Collection inside an empty Collection.

When a Collection is empty

![image](https://user-images.githubusercontent.com/1455846/86285698-f1d6d480-bb99-11ea-8010-559b2dab78c6.png)

the only way to add a child Collection is to navigate away to the top-level "Our Analytics" Collection and click "Add Collection" and then change the "Where's it's saved in" to the desired location:

![image](https://user-images.githubusercontent.com/1455846/86285779-13d05700-bb9a-11ea-9e1c-7e7f21d5d13b.png)

But if it already contains another Collection I can click `+ New Collection` to add another one in the Collection detail view:

![image](https://user-images.githubusercontent.com/1455846/86285835-32cee900-bb9a-11ea-85d3-38950c92f6b2.png)

We should show the `+ New Collection` button in empty Collections as well.

**Comment by mazameli** [comment]
Huh, interesting. I don't know if I've ever run into this problem in my own use, but it's a valid point. I could see cases where you're trying to create a folder structure and assign permissions for a new instance before creating all your charts and dashboards. But I would guess that in practice, most folks end up creating subfolders only as they need to in order to organize all the stuff that's built up in the parent collection(s).

**Comment by flamber** [comment]
This has been fixed as part of the 0.38 collection reorganization
![image](https://user-images.githubusercontent.com/1447303/103920581-c537e280-5111-11eb-85c0-5ab4431f7312.png)
