### ISSUE TITLE
Delete database popup don't have the database name

### ISSUE THREAD

**Issue by iurisilvio** [metabase/metabase#12883]
**Describe the bug**
The "Delete database" popup have no clue about which database the action will be executed.

**To Reproduce**
1. Go to admin Databases
2. Click on Delete

![image](https://user-images.githubusercontent.com/105852/87086122-73b4a680-c207-11ea-972d-c82840cc2d19.png)

3. Close the popup and repeat the process to be sure you selected the correct database and click delete again...

**Expected behavior**
I want to know which database I selected. "Delete database **MY_AMAZING_DB**?"

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: 0.35.4

**Severity**
It is annoying and easy to fix. Just a small text change would be amazing to user experience here.

**Comment by flamber** [comment]
Normally I wouldn't call this a bug, but since it's a pretty permanent thing, then I'll call it a P2 bug. Related to #2061

**Comment by nemanjaglumac** [comment]
@flamber I can fix this quickly. The following question probably deserves a discussion beforehand. 

#### What would be the preferred way of dealing with translation string "Delete this database"?

1. I can put the database name before the string in order to preserve translation (like this):
![image](https://user-images.githubusercontent.com/31325167/87677371-f8f50980-c779-11ea-9dcf-68002155c9c0.png)
_(other possible variations can include: putting database name in quotes, using hypen instead of colon, reversing the order of the string and database name etc.)_

2. I can use the database name as a placeholder in the middle of the string, but that would require translation files to be updated:
![image](https://user-images.githubusercontent.com/31325167/87678446-3d34d980-c77b-11ea-92d2-68dcef735735.png)

3. open for suggestions

**Comment by flamber** [comment]
@nemanjaglumac I think @mazameli would be better at answering that.

**Comment by nemanjaglumac** [comment]
In general, what is the practice for already established and confirmed translations? Do you guys tend not to break them and how often are new translations added/updated?

I am asking because the language needs 100% coverage to be included, if I understood correctly.

**Comment by flamber** [comment]
@nemanjaglumac Yes, strings can be changed - meaning new translations - when needed, but generally should be avoided. And will probably not be shipped with 0.36.0, since it's too close to release.

**Comment by xPaw** [comment]
I would suggest changing "DELETE" to type the actual database name.

Similar to deleting github repos:
![image](https://user-images.githubusercontent.com/613331/96021081-a0580a00-0e57-11eb-9088-8b4b4b73af1f.png)
