### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by CZvacko** [metabase/metabase#13002]
Some translations in the Czech/Slovak language are missing (probably also in other languages).

**Missing in POEditor:**
- The default language for all users across the Metabase UI, system emails, pulses, and alerts. Users can individually override this default language from their own account settings.
- Retire segment

**Translated in POEditor, but not present in v 0.36 release**
- Metabase can attempt to transform your table and field names into more sensible, human-readable versions, e.g. "somehorriblename" becomes "Some Horrible Name". This doesn’t work all that well if the names are in a language other than English, however. Do you want us to take a guess?
- To determine how long each saved question's cached result should stick around, we take the query's average execution time and multiply that by whatever you input here. So if a query takes on average 2 minutes to run, and you input 10 for your multiplier, its cache entry will persist for 20 minutes.
- Database instance name
- Additive sum of all the values of a column.\\ne.x. total revenue over time
- Additive count of the number of rows.\\ne.x. total number of sales over time.
- {0} rows [in segment setting]

**Comment by flamber** [comment]
Several of these are caused by #10770 - all the really long lines.

`Retire Segment`
https://github.com/metabase/metabase/blob/5e8ff50d5ed3f0d569ce4e196fcd272d594eabb7/frontend/src/metabase/admin/datamodel/components/ObjectActionSelect.jsx#L65

`Database instance name` - I guess you mean the SQL Server driver? - `display-name` property is not getting translated:
https://github.com/metabase/metabase/blob/a84d1ac0e10797e135386cde78ea4331d8d2ba99/modules/drivers/sqlserver/resources/metabase-plugin.yaml#L20

`Additive sum of all the values of a column.\ne.x. total revenue over time` and `Additive count of the number of rows.\ne.x. total number of sales over time.`
We shouldn't have newlines, since those are removed from translations and it's not even supported for tooltips either.
![image](https://user-images.githubusercontent.com/1447303/88525452-e4770380-cffa-11ea-8931-f809a405ebf3.png)

`{0} rows`
https://github.com/metabase/metabase/blob/66631d845fa7a41ab2946f4d4d749b315a10bca0/frontend/src/metabase/query_builder/components/view/QuestionRowCount.jsx#L21

**Comment by CZvacko** [comment]
SQL Server driver? - **YES**
Concerning newlines, you will generate new strings for POEditor, then all translators will make new translations? Or I should adjust existing and remove _\\ne.x._ ?

**Comment by flamber** [comment]
@CZvacko When the strings change (even a space or a newline), it's seen as a new string and needs to be translated.

**Comment by CZvacko** [comment]
One more issue: when define "Sumarize" by _datetime_ column, editor shows translated period (day/month/etc..) as translated, but displayed table show untranslated string in header. Is this the right behavior?
![Day-define](https://user-images.githubusercontent.com/66993187/88531943-fe691400-d003-11ea-9783-0b4b9fdfb458.jpg)
![Day-display](https://user-images.githubusercontent.com/66993187/88531948-ff01aa80-d003-11ea-9ee7-5700a4ea64e0.jpg)

**Comment by flamber** [comment]
@CZvacko That's your table name. You can change that in Admin > Data Model.

**Comment by CZvacko** [comment]
@flamber 
No I mean **Den** <> **Day** 
or **Rok** <> **Year**

**Comment by flamber** [comment]
@CZvacko Instead of turning this into a back-and-forth, then there's several other places that is not translated and several issues open about it, so have a look in those too: https://github.com/metabase/metabase/labels/Customization%2Fi18n
The granularity not getting translated is probably caused by the function that gets the column name, but not sure about that:
https://github.com/metabase/metabase/blob/510b979e84c47464edc4043f0838e331d1370300/frontend/src/metabase/visualizations/visualizations/Table.jsx#L368

**Comment by npfitz** [comment]
Retire Segment is still not translated, as well as the default name for a column header
