### ISSUE TITLE
Issue updating from 0.35.4 to 0.36.1

### ISSUE THREAD

**Issue by skaboy007** [metabase/metabase#13052]
unfortunately when I try to update this is what I get 

`  Reason: liquibase.exception.DatabaseException: (conn=24739) Cannot add or update a child row: a foreign key constraint fails (`metabase_test`.`#sql-60e_60a3`, CONSTRAINT `fk_table_ref_database_id` FOREIGN KEY (`db_id`) REFERENCES `metabase_database` (`id`) ON DELETE CASCADE) [Failed SQL: ALTER TABLE metabase_test.metabase_table ADD CONSTRAINT fk_table_ref_database_id FOREIGN KEY (db_id) REFERENCES metabase_test.metabase_database (id) ON DELETE CASCADE]`

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your operating system:  Ubuntu 18.04
- Your databases: MySQL and ClickHous
- Metabase version: 0.35.4 
- Metabase hosting environment: Jar
- Metabase internal database:  MySQL

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7-Ubuntu-1ubuntu218.04.1",
    "os.name": "Linux",
    "os.version": "4.15.0-34-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "sqlserver",
      "h2",
      "clickhouse"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-0ubuntu0.18.04.1-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Comment by flamber** [comment]
Hi @skaboy007 
Can you please post the full stacktrace. Is this a regular MySQL or some other variant like Galera or something?
Related to #13043

**Comment by wlp7s0** [comment]
[metabase.log](https://github.com/metabase/metabase/files/5020385/metabase.log)
Hello @flamber,
As @skaboy007 mentioned in the init topic - we are using MySQL database
full startup log attached.

**Comment by flamber** [comment]
@wlp7s0 
Is the MySQL configuration almost the default or have you made a lot of changes? I cannot reproduce on two instances of regular MySQL 5.7 with almost no configuration changes.

Do you see more information in the MySQL log that could help pointing in the right direction?
Do you have rows in `metabase_test.metabase_table.db_id` that references `metabase_test.metabase_database.id`, but doesn't actually exists?

Otherwise try setting [MB_DB_AUTOMIGRATE](https://github.com/metabase/metabase/blob/master/docs/operations-guide/environment-variables.md#mb_db_automigrate) to false, and manually run the queries on MySQL to see if it gives more helpful errors on why it's failing.

**Comment by wlp7s0** [comment]
@flamber thank you for your answer. 
[mysql_vars.txt](https://github.com/metabase/metabase/files/5022142/mysql_vars.txt)
this is almost default configuration of the mysql.
But I did some investigation. Thank you for pointing out where to search for the issue.

`mysql> SELECT DISTINCT db_id FROM metabase_table;
+-------+
| db_id |
+-------+
|     1 |
|     3 |
|     4 |
|     5 |
|     6 |
+-------+
5 rows in set (0.00 sec)
`

`mysql> select distinct id from metabase_database;
+----+
| id |
+----+
|  3 |
|  4 |
|  5 |
|  6 |
+----+
4 rows in set (0.00 sec)
`

it indeed has a reference to the table that does not exist.

**Comment by flamber** [comment]
@wlp7s0 Okay, then you need to remove `db_id=1` from `metabase_table` (and there's probably references from `metabase_field` to that table too), which I'm fairly sure was the Sample Dataset at some point, but I have no idea how you ended up in this state. It shouldn't be possible, since there has always been constraints on the column I think, so it must have been done manually at some point.
Related to #11813

**Comment by sbelak** [comment]
It might be handy to have some self-diagnose and self-fix tool for cases like this.

**Comment by wlp7s0** [comment]
Yeah, thank a lot. Issue fixed by deleting this data from the database and running migrations again. 
Will ask @skaboy007 to mark as solved.
Thanks again!

**Comment by skaboy007** [comment]
hi Thank you For the prompt Replay, We appreciate your work, 

the solution was to do this 

```
mysql> DELETE from metabase_table where db_id=1;
Query OK, 4 rows affected (0.01 sec)
```
