### ISSUE TITLE
Environment variable MB_ENABLE_EMBEDDING=true makes Admin > Embedding subpage not function

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13166]
**Describe the bug**
When setting environment variable [MB_ENABLE_EMBEDDING](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_enable_embedding)=`true`, then it looks Embedding isn't enabled.

Workaround is to not use environment variable, but enable embedding through the API with the key `enable-embedding`:
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**To Reproduce**
1. Start Metabase with `MB_ENABLE_EMBEDDING=true`
2. Go to Admin > Settings > Embedding in other Applications
![image](https://user-images.githubusercontent.com/1447303/91218818-e9be8f80-e719-11ea-914a-bc289dbabf06.png)
3. Shows as if Embedding is not enabled, but it is - and clicking "Enable" button does not change anything.

**Expected behavior**
To show the Embedding page as if it was enabled, so it's possible to view/edit secret, and see which dashboard and questions are currently available through embedding.
![image](https://user-images.githubusercontent.com/1447303/91219223-91d45880-e71a-11ea-803c-7d690e911078.png)

**Information about your Metabase Installation:**
Metabase 1.36.4 and 0.36.4

**Additional context**
Related to #13160 and #12272

**Comment by jensgustafsson** [comment]
I can confirm that this bug is apparent in my environment as well. Are there any kind of work around available that can set this at startup or do I have to make an API request after the service has booted?

**Comment by jensgustafsson** [comment]
Update:

I'm having the same problem with other environment variables. Some variables works as expected but not all of them.

Here's a list of other features I've tried to enable via environment variables but seems to be not working:

* `MB_CHECK_FOR_UPDATES`
* `MB_ENABLE_PUBLIC_SHARING`
* `MB_JWT_ENABLED`


The the `api/setting` endpoint in the API returns 

```
{
    "value": null,
    "is_env_setting": true
}
```

for all variables that I've set via env variables. At first I thought this meant that no values were set since the value is set to null but I've for instance been able to set the `MB_PREMIUM_EMBEDDING_TOKEN` and `MB_APPLICATION_COLORS` and confirmed that they're applied.

**Comment by robert-mccarter** [comment]
Yes, Metabase has MANY bugs around configuration. 
- Sometimes env vars work,
- Sometimes they work but don't show up in the UI,  and
- Sometimes they simply don't work and we need to configure them through the REST API

**Comment by jensgustafsson** [comment]
> Update:
> 
> I'm having the same problem with other environment variables. Some variables works as expected but not all of them.
> 
> Here's a list of other features I've tried to enable via environment variables but seems to be not working:
> 
> * `MB_CHECK_FOR_UPDATES`
> * `MB_ENABLE_PUBLIC_SHARING`
> * `MB_JWT_ENABLED`
> 
> The the `api/setting` endpoint in the API returns
> 
> ```
> {
>     "value": null,
>     "is_env_setting": true
> }
> ```
> 
> for all variables that I've set via env variables. At first I thought this meant that no values were set since the value is set to null but I've for instance been able to set the `MB_PREMIUM_EMBEDDING_TOKEN` and `MB_APPLICATION_COLORS` and confirmed that they're applied.

**Ignore my previous post**

After some trial and error I've realized that everything seems to work as expected. The admin page doesn't show what you've actually configured in a good way but the config provided via ENVS are the config that's actually being used.

**Comment by camsaul** [comment]
We can definitely test this -- just need to mock the API response to include `is_env_setting: true` and make sure the page still works correctly

**Comment by ranquild** [comment]
@flamber this is a definitely a BE bug as `api/setting` endpoint does not return values for env settings and the FE has no other way to get them. What surprises me more, is that it's even documented in code:

```
(defn all
  "Return a sequence of Settings maps in a format suitable for consumption by the frontend.
   (For security purposes, this doesn't return the value of a Setting if it was set via env var).
```

**Comment by camsaul** [comment]
Not returning values for Settings that are set by environment variable is by design -- that's why we return the `is_env_setting: true` key in the API response. The FE is supposed to gray out these Settings in this case and maybe show a tooltip or something that says "this Setting is set via environment variable"
