### ISSUE TITLE
Oracle driver is not appeared in databases

### ISSUE THREAD

**Issue by yanghuancheng** [metabase/metabase#13168]
When I want to add a database, there is no oracle in the drop-down menu.  
 It doesn't seem to work when I put the “ojdbc8.jar” in the “/plugins” while it run in docker.
 
Could you add ojdbc8 or other available driver in this jar?

**Comment by flamber** [comment]
Hi @yanghuancheng 
We are not permitted to distribute ojdbc8.jar, so that won't be possible.
You could use a volume, so the plugins directory refers to somewhere outside of the container, if that makes it easier to maintain.
Remember to restart the container after adding the ojdbc8.jar - and remember to set the correct file permissions.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
