### ISSUE TITLE
Add support for "yyyymmddhhmmss" formatted datetime strings

### ISSUE THREAD

**Issue by fbstj** [metabase/metabase#1324]
This is a really great program/project and I've really hoped to be able to use it for querying my wiki instances, but for some arcane reason mediawiki stores timestams as yyyymmddhhmmss in binary/varbinary columns. How would I go about interpreting these into something metabase understands?

I also don't understand how to request a column from a joined table (aka selecting username in a query grouping a table by the user ID seems to confuse it)

**Comment by agilliland** [comment]
Wow, that's indeed a very customized way of dealing with timestamps.  Metabase actually supports the notion that a timestamp column is a long integer of ms since the epoch and under the hood we can do all the transformations to make that work like any normal date/time column.  We'll have to look into this and see if we can do something similar for this scenario.

**Comment by fbstj** [comment]
I was more asking if there's any explanation of how to add custom parsing (preferably without resorting to setting up a full javac and recompile and all that junk) 

From my quick playing around (until I figured out why the dates were breaking) I really liked the thing and was looking forward to doing more complex graphs and queries and things.

Is there any way of exporting the metadata to be imported on other copies, or as a 'template' (since having to fill in the data manually for something like mediawiki where it's very similar over every install is a bit of a faff).

**Comment by camsaul** [comment]
Related: #1576

**Comment by dpsutton** [comment]
Merged into master, slated for 40 release
