### ISSUE TITLE
Ability to set different color for negative values in Bar charts

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13253]
If we can set a different color for negative values (or for a defined threshold) that would be great. Something like the following image:

![Screenshot_2020-09-15 Question · Metabase](https://user-images.githubusercontent.com/15974735/93298440-165d4880-f7a8-11ea-944a-27c1316d61f9.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #5763

**Comment by flamber** [comment]
This is actually possible since 0.38 with Waterfall chart:
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#waterfall-charts
![image](https://user-images.githubusercontent.com/1447303/119890450-254fe980-bf38-11eb-8c64-837137c52720.png)

@vvaezian Going to close this, but let me know if you're asking for something different, then we might create a new issue.
