### ISSUE TITLE
Unable to add Application Database using Elastic Beanstalk 

### ISSUE THREAD

**Issue by timabe** [metabase/metabase#13251]
**Describe the bug**
From the Elastic Beanstalk documentation, when you click [Launch on EBS](https://downloads.metabase.com/v0.36.5.1/launch-aws-eb.html), the configuration for the **Modify database** card is broken. I'm unable to access any of the dropdown and there are no default options filled in as before.
 
**Logs**

**To Reproduce**
1. Go to https://downloads.metabase.com/v0.36.5.1/launch-aws-eb.html
2. Click on **Upload your code** > **Review and Launch**
3. Click **Edit** on the **Database** card.
4. Notice it's not possible to fill in.

**Expected behavior**
In the past, I've been able to add a PostgreSQL or MySQL database here.

**Screenshots**
![ebs_mb](https://user-images.githubusercontent.com/1427277/93237762-69e27e80-f735-11ea-91e2-cfa6af07512d.gif)

**Information about your Metabase Installation:**

**Severity**

Blocking the paved path EBS deployment.

**Comment by timabe** [comment]
This appears to be a bug with Elastic Beanstalk, not Metabase. I've filed it with AWS and am triaging it. I'll close it out when they've solved it, but for now it might be helpful to leave this issue open for discoverability.

**Comment by dacort** [comment]
Oddly enough, `postgres` is no longer mentioned as an option for `rdsDBEngine` in the [Launch URL](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/launch-now-url.html) docs, even though it's shown as an example and still supported when configuring a Beanstalk app from scratch... 🤔

**Comment by slickrock22** [comment]
@paoliniluis I am still having this issue and would love to seperate my ELB front-end from my backend.  Thanks!

**Comment by paoliniluis** [comment]
Hi @slickrock22, can you please describe the issue you are having? the separation between the Elastic Load Balancer and the backend seems that is another issue and not this one that seems like a UI error on the ElasticBeanstalk webpage

**Comment by slickrock22** [comment]
@paoliniluis Sorry I may be getting some wires crossed.   I believe I stumbled across and followed this post because when I followed the instructions that Metabase provided for detaching the Postgres database that gets created in RDS automatically using the ELB process, you have to select the database using the same drop-down that is now missing from the revised ELB UI.   I was waiting for Metabase to revive the documentation on the Detachment process due to the revision by AWS. I hope that makes sense.

**Comment by paoliniluis** [comment]
Hi, this is a UI error from Elastic Beanstalk that I faced several times when trying to add a Database before adding a network to the stack. It seems an AWS error rather than a Metabase one. We've updated the documentation and if steps are followed accordingly this issue shouldn't appear. I'll close it for now as this is something that AWS has to fix rather than us. 
If it happens again or any user faces this, go back and try to add a network (VPC) to the Elastic Beanstalk stack, then go back to the database selection and try clicking on the engine first. It should work
