### ISSUE TITLE
Presto not respecting SSL and always uses http instead of https

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13295]
**Describe the bug**
Presto not respecting SSL setting and always uses `http` instead of `https`, which means it cannot connect to databases that only allows https.

**To Reproduce**
1. Admin > Databases > Add database > Presto and fill out information including SSL activated:
![image](https://user-images.githubusercontent.com/1447303/93924857-99851e00-fd15-11ea-856d-996f1a993d7f.png)
2. When saving, Metabase will try to connect to `http://presto.example.test:443` instead of over `https` - the log would output something like this:
`Caused by: clojure.lang.ExceptionInfo: clj-http: status 404 {:object {:request-time 5, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :reason-phrase "Not Found", :headers {"Content-Type" "text/plain; charset=utf-8", "X-Content-Type-Options" "nosniff", "Date" "Tue, 22 Sep 2020 20:21:25 GMT", "Content-Length" "19", "Connection" "close"}, :orig-content-encoding nil, :status 404, :length 19, :body "404 page not found\n", :trace-redirects ["http://presto.example.test:443/v1/statement"]}, :environment {req {:headers {"X-Presto-Source" "test", :as :json, :redirect-strategy :lax, :url "http://presto.example.test:443/v1/statement", :request-method :post}, p__23212 {:request-time 5, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :reason-phrase "Not Found", :headers {"Content-Type" "text/plain; charset=utf-8", "X-Content-Type-Options" "nosniff", "Date" "Tue, 22 Sep 2020 20:21:25 GMT", "Content-Length" "19", "Connection" "close"}, :orig-content-encoding nil, :status 404, :length 19, :body "404 page not found\n", :trace-redirects ["http://presto.example.test:443/v1/statement"]}, map__23213 {:request-time 5, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :reason-phrase "Not Found", :headers {"Content-Type" "text/plain; charset=utf-8", "X-Content-Type-Options" "nosniff", "Date" "Tue, 22 Sep 2020 20:21:25 GMT", "Content-Length" "19", "Connection" "close"}, :orig-content-encoding nil, :status 404, :length 19, :body "404 page not found\n", :trace-redirects ["http://presto.example.test:443/v1/statement"]}, resp {:request-time 5, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :reason-phrase "Not Found", :headers {"Content-Type" "text/plain; charset=utf-8", "X-Content-Type-Options" "nosniff", "Date" "Tue, 22 Sep 2020 20:21:25 GMT", "Content-Length" "19", "Connection" "close"}, :orig-content-encoding nil, :status 404, :length 19, :body "404 page not found\n", :trace-redirects ["http://presto.example.test:443/v1/statement"]}, status 404}}
`

**Information about your Metabase Installation:**
Metabase 1.36.6.1 and 0.36.6

**Additional context**
From the code, it should automatically select `https`, when SSL is activated:
https://github.com/metabase/metabase/blob/d48accbeadfebd3ef4bb0a128408a98cd0fdf94e/modules/drivers/presto/src/metabase/driver/presto.clj#L70-L73

**Comment by mazameli** [comment]
We had some discussion about UX implications around this. Here's where I think we ended up.

1. Keep this behavior: SSL toggle is off by default, but we give SSL a try even if it's off, and "upgrade" the connection silently to SSL if we can.
2. Keep this behavior: if the SSL toggle is off, and we try SSL but it doesn't work, we should just save as normal. (**I don't think there's any need here to add additional messages or confirmations** — SSL was off, so there's no expectation it should be on.)
3. If the SSL toggle is _on_ and the user hits Save, if we try to connect but it doesn't work, we should then try to connect _without_ SSL. If that works, we should display a dialog to tell the user that we were able to connect without SSL, and ask them what they want to do. If they choose "No, don't connect" we should not save details, and just leave them on the form page.

Here's an illustration for scenario 3:

![image](https://user-images.githubusercontent.com/2223916/93948017-24ecb800-fcf2-11ea-9ada-e8b8bdc751c0.png)

(I mentally went down the road of proposing that we default SSL to on, but I don't think we need to do that since we're already automatically trying to connect via SSL regardless of the state of that toggle. Defaulting to On would just mean more folks running into that "do you want to proceed" dialog than need to. So for all intents and purposes, that SSL toggle is more like a "force SSL, and tell me if it doesn't work" toggle.)

**Comment by flamber** [comment]
@mazameli Perhaps it could be added along with #11671?

**Comment by camsaul** [comment]
Fixed by #13304
