### ISSUE TITLE
Provide a "verify settings" feature to email settings

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1330]
It's hard to tell if you made a mistake in entering email creds and it would be useful to provide a way to verify your settings similar to the DB credentials verification.

This is especially problematic due to the lack of user facing display of email errors

**Comment by mazameli** [comment]
Here's the current WIP design prototype:
https://invis.io/RV4R7QNFN

**Comment by mazameli** [comment]
We're currently trying to figure out:
* what makes sense for the default From Address setting (or should there be a default?)
* final error states and copy
* final positioning and styling of error messages

Future enhancement ideas:
* could we have a dropdown for users to select their SMTP service so that we could auto-populate some or the fields?

**Comment by mazameli** [comment]
@kdoh and @tlrobinson: I made some updates to the prototype (link above), if you wouldn't mind taking a look.

**Comment by mazameli** [comment]
Incidentally, #1229 would be fixed by this issue.
