### ISSUE TITLE
0.37-rc1: When mapping dashboard filters to columns, SQL questions should display the name of the column mapped to the field filter

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#13376]
Right now, we display the name of the field filter variable, which doesn't seem as helpful as displaying the mapped table and column name.

**Comment by paulrosenzweig** [comment]
@mazameli you're talking about mapping a dashboard filter when connecting it to a card, right? (rather than the new sidebar click mapping UI)

If so, it looks like we already display the name of the column mapped to the field filter.

I have this native question on a dashboard:
![image](https://user-images.githubusercontent.com/691495/95625834-2b479780-0a47-11eb-99ce-d4ac8cae418b.png)

This is what I see when mapping an ID filter to it:
![image](https://user-images.githubusercontent.com/691495/95625757-07845180-0a47-11eb-8c3a-8c95ee9ea71e.png)

Maybe I'm reversing this issue's meaning. IMO the current behavior is wrong, and we _should_ display the name of the field filter variable. You could have multiple field filters pointing to the same field, but they will have different variable names.

**Comment by flamber** [comment]
@paulrosenzweig We definitely want to show the variable name, but I think it was one of the things that confused me (together with #13406), when you select the filter, then it shows as `Order.product_id` (normalized, shouldn't it be Order**s**?), which is a mix between the table display name and the variable name.
I think I expected it to either show the variable name - or the table.column reference. Maybe it's just me?
This is essentially trying to solve #12792/#4787
