### ISSUE TITLE
When entering a question from a dashboard, the saved visualization type is ignored

### ISSUE THREAD

**Issue by pattonjh** [metabase/metabase#13415]
**Describe the bug**
When clicking on a question shown in a dashboard, Metabase seems to fall back to autopicking vis type - ignoring that a different visualization type was saved with the question. It correctly shows the saved visualization type in the dashboard card.

**Logs**
I do not think the logs are relevant but if you disagree please let me know and I will update with them. I have reproduced this issue through multiple dashboards and questions - it seems to be very reproduceable.

**To Reproduce**
1. Go to a dashboard with a saved question, wherein the question has a visualization type saved other than the auto picked one.
2. Click on the question title in the dashboard card to view the question
3. See error: visualization type is different than what was previously saved

**Expected behavior**
When entering a question from the dashboard, I expect to view the question in the same visualization type as it appeared in the dashboard card.

**Screenshots**
Screenshot of the data as seen in the dashboard card where it's a table:
![image](https://user-images.githubusercontent.com/5550872/95510760-09cda980-097c-11eb-80b8-f15302e73bfa.png)

Screenshot of the data after clicking on the title of the question where it's a line chart:
![image](https://user-images.githubusercontent.com/5550872/95510954-5e712480-097c-11eb-91c7-3def1ec6be9f.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.193-113.317.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v0.36.6",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
This is pretty severe for us, but perhaps not for everyone. Some of our datasets do not perform well at all in the auto selected visualization, resulting in browser crashes or timeouts.

**Comment by flamber** [comment]
Hi @pattonjh 
It seems like it only happens, when there's a dashboard filter connected and with defined value. Then somehow the "auto-viz" functionality is used instead of the selected visualization type.

**Steps to reproduce:**
1. Simple question > Sample Dataset > Orders
2. Summarize Count grouped by Category and CreatedAt:Year
3. Visualization as Table (Pivot) and save question as "Q1"
![image](https://user-images.githubusercontent.com/1447303/95760054-d906b080-0caa-11eb-8113-9a5c54d28544.png)
4. Add to dashboard, create a filter ("Other categories") connected to Q1.Category
5. Set the dashboard filter value:
![image](https://user-images.githubusercontent.com/1447303/95760902-e07a8980-0cab-11eb-8c6d-8740dc4b0f73.png)
6. Click the card title:
![image](https://user-images.githubusercontent.com/1447303/95760966-f38d5980-0cab-11eb-9934-9b3ffda0a279.png)

Related to some closed issues #12361 and #11218

**Comment by flamber** [comment]
Fixed by #14640
