### ISSUE TITLE
Oracle Database Driver

### ISSUE THREAD

**Issue by Clemzd** [metabase/metabase#1344]
I was installing your software when I realized it doesn't support Oracle database.

Do you plan to add support for Oracle?

**Comment by hdao324** [comment]
+1 for this request

**Comment by agilliland** [comment]
@Clemzd we plan to add support for any databases the community feels are important, so we are asking people to indicate their preferences here and then we'll let that steer the development efforts.

**Comment by tapester** [comment]
+1
Would it be possible to provide a generic JDBC interface just supplying the connection string?

**Comment by jrbing** [comment]
+1

**Comment by jonasdiel** [comment]
+1

Em seg, 26 de out de 2015 às 12:14, JR Bing <notifications@github.com>
escreveu:

**Comment by jonasdiel** [comment]
+1

**Comment by ismaild** [comment]
+1

**Comment by theonewolf** [comment]
:+1:

**Comment by jamhall** [comment]
:+1:

**Comment by camsaul** [comment]
:+1:

**Comment by ctaloi** [comment]
This would be helpful - have an Oracle DB and would benefit from this integration.

**Comment by accopeland** [comment]
+1 for Oracle support.

**Comment by kurtadamsen** [comment]
+1

**Comment by fabfurnari** [comment]
+1

**Comment by dreamerworks** [comment]
+1

**Comment by camsaul** [comment]
+1

**Comment by typerlc** [comment]
+1

**Comment by jmuders** [comment]
+1

**Comment by dersteppenwolf** [comment]
+1

**Comment by dinesh-ms** [comment]
+1

**Comment by XRyu** [comment]
+1

**Comment by camsaul** [comment]
@tapester @XRyu it isn't as simple as just accepting a generic JDBC string. You still need to have the appropriate JDBC driver bundled to handle connections of a given DB type. On top of that, Metabase does things that aren't offered by JDBC, and needs additional Metabase-specific code for each new database to support these features.

**Comment by computersarehard** [comment]
I spent some time getting something minimal working for Oracle. There are still a lot of details (conversions, vendor syntax, etc.) but for the most part things work. There are some big picture issues that could use input from the core team:

1. Current driver jars are not available in a _public_ maven repository. Oracle has its own, authenticated, repository that may have these jars. Thus, including them in the uberjar has some hurdles.
2. I'm not a lawyer, but I doubt the driver jars can be distributed with Metabase due to licensing issues.
3. Given 1 above and the proprietary nature of Oracle, it makes it hard to run tests. Express Edition could probably be used for this (currently only an 11g version is available) and it does look like  there are some Oracle XE Vagrant VMs out there.

Oracle support can just be optional (i.e. works if the driver jar is on the user's classpath). I'm mainly unsure about the testing and packaging requirements.

Any thoughts?

P.S. Thank you so much for Metabase. It's great!

**Comment by tapester** [comment]
@computersarehard 
Do you have a working fork for Oracle? I'd like to pitch here.

**Comment by computersarehard** [comment]
@tapester I haven't yet made a fork as the implementation is pretty rough&mdash;not something I'm comfortable making public yet. I'm planning to spend some more time on it this week so I'll give an update once something is pushed.

**Comment by salsakran** [comment]
Hey everyone- 

As an update. We do have an oracle driver built, tested, etc. However we're not able to distribute it + oracles jdbc driver together with the main open source project. We're also debating internally whether the cost of maintaining it over time makes sense, given that none of installations we're running touch Oracle. We're not talking so much about getting the initial cut right, but rather dealing with lots of operational idiosyncrasies and driver quirks as they pop up over time. 

If you're willing to work with us on a private build and help us debug/test, etc, reach out to me directly!

**Comment by ismaild** [comment]
@salsakran you have mail. Willing to pitch in.

**Comment by ismaild** [comment]
@computersarehard shout out if you need assistance. Email is in my profile

**Comment by stvsmth** [comment]
+1

**Comment by darinbaumgartel** [comment]
+1

**Comment by oleg-starcoders** [comment]
+1

**Comment by mariosergioti** [comment]
+1

**Comment by HebertSantana** [comment]
+1

**Comment by h4ck4life** [comment]
+1

**Comment by camsaul** [comment]
Implemented by #3258.
