### ISSUE TITLE
Error "e is null" when adding lines

### ISSUE THREAD

**Issue by olivier-magloire** [metabase/metabase#13465]
**Describe the bug**
When trying to add an additional line to any question on any dashboard I get the error "e is null" (Firefox) or "Cannot read property 'type' of null" (Chromium).
There are no apparent errors in the server log, can't tell what the js error means.
Adding lines is therefore not possible because the search doesnt work.

**Logs**
Server logs: [metabase.log.tar.gz](https://github.com/metabase/metabase/files/5377153/metabase.log.tar.gz)
JS logs (Firefox): [js.log](https://github.com/metabase/metabase/files/5377226/js.log)

**To Reproduce**
Based on https://www.metabase.com/docs/latest/users-guide/09-multi-series-charting.html#combining-two-saved-questions
1. Go on dashboard
2. Add any question
3. Add a line to that question
4. Error shows up on the right

**Expected behavior**
Being able to add lines to existing questions on the dashboard

**Screenshots**
Chromium:
![Chromium](https://user-images.githubusercontent.com/36983007/95971237-3a489400-0e11-11eb-9d9b-ce403fec4b50.png)
Firefox:
![Firefox](https://user-images.githubusercontent.com/36983007/95971243-3b79c100-0e11-11eb-83f3-b3994fd3bbf8.png)

**Information about your Metabase Installation:**
- Your browser and the version: Firefox 81.0.1, Chromium 83.0.4103.116
- Your operating system: Debian 10.6
- Your databases: Any
- Metabase version: v0.36.3
- Metabase hosting environment: Self-hosted on Debian 9.11
- Metabase internal database: MySQL

**Severity**
Multi series charting is a major feature of metabase, comparing data is very inconvenient like this.

**Additional context**
None

**Comment by flamber** [comment]
Hi @olivier-magloire 
I cannot reproduce on latest release, 0.36.7. Are you using a reverse-proxy of any kind?
Since you say this happens with any question/database, can you provide steps-to-reproduce with Sample Dataset?

**Comment by olivier-magloire** [comment]
Hi @flamber 
Thanks for the quick reply!
We are using nginx as reverse proxy but I just tried to access the application directly per IP and Port 3000, same effect.
I upgraded to 0.36.7, same effect.

Reproduce (IP is fictional):
1. Reenabled the Sample Dataset on http://10.10.10.10:3000/admin/databases
2. Browse Data, Select Sample Dataset and open Orders on http://10.10.10.10:3000/browse/78
3. Summarize by count and group by created at. (Default graph is line, thats ok)
4. Save in personal collection
5. Create test dashboard
6. Add question to test dashboard on http://10.10.10.10:3000/dashboard/155
7. Add line to question
8. Screenshot
![screenshot_2020-10-14_153626](https://user-images.githubusercontent.com/36983007/95996557-18600900-0e33-11eb-83f6-d034c68f2aff.png)

**Comment by flamber** [comment]
@olivier-magloire Okay, the problem is somewhere else. I cannot reproduce. It's probably choking on one of the questions somewhere in your setup.
If you check the browser developer Network-console, when trying to combine another question to the card ("Add line to question", as you call it), then you should see a bunch of requests. Are some of them hanging or non-200?
I have a feeling it's related to #13100, and that you have a lot of databases and questions.

**Comment by flamber** [comment]
@olivier-magloire Hmmm... looking through the 187,000 lines of server log, and I'm stumbling over the lines `Oct 14 11:28:19`
Can you figure out which question that is? I have no idea what's causing the error `Unable to normalize` `clojure.lang.ExceptionInfo: Input to normalize-token does not match schema`, but since it seems to come up in relation to loading the `query_metadata`, then I guess it's very related somehow.

**Comment by olivier-magloire** [comment]
@flamber oh i found one question in this database 7 that failed with unknown error. after archiving its again possible to combine questions. thank you very much!
can i provide more information for a fix or to improve error handling?

**Comment by flamber** [comment]
@olivier-magloire Excellent that it fixed your problem.
I would love to figure out how I can reproduce a similar broken question, because then it's a lot easier for the developers to have something to work with.
That problematic question, when you visited it, which errors were you seeing the the UI and log? You can unarchive it by going to `/archive` in the Metabase URL.
Can you provide more information about the question - is it SQL or GUI question, which database type, does it contain variables or filters? And could you provide the query?

**Comment by olivier-magloire** [comment]
I could access the question without unarchiving it, I still had the id. Does that make a difference? You'll find the requested info below. 
Is there another way to access the question than by UI? I can currently not select edit (see screenshot).
The query seems to be visible within the logfile.
Logfile: [metabase.log](https://github.com/metabase/metabase/files/5384560/metabase.log)
Screenshot: ![screenshot_2020-10-15_134744](https://user-images.githubusercontent.com/36983007/96119401-39853000-0eed-11eb-8ec6-a5b497bac6ce.png)

**Comment by flamber** [comment]
@olivier-magloire Yes, you have to unarchive it. Otherwise it will never be loaded.

**Comment by olivier-magloire** [comment]
I am unable to unarchive the question, I get following error in the server log. Unarchiving other questions work.

[metabase.log](https://github.com/metabase/metabase/files/5389407/metabase.log)

**Comment by flamber** [comment]
@olivier-magloire I've been trying several things, but I cannot reproduce this in any way. I have tried to mess up a question really good, and drop columns from the database, which was connected via Field Filters, but I'm not getting to this broken state.
It would require a lot more investigation to figure out all the metadata of this question, but some of that information might already have been lost, when it was archived, so let's leave this - and if someone else is experiencing something similar, then I'll start debugging on that.

**Comment by olivier-magloire** [comment]
@flamber ok, sorry if i accidentally destroyed evidence. anyway thanks a bunch, excellent support!
