### ISSUE TITLE
Support PEM file to connect to MySQL DB with SSL certificate

### ISSUE THREAD

**Issue by mickey** [metabase/metabase#1350]
With `MySQL`: https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-ca

This would allow us to connect directly to our RDS instance.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nambrot** [comment]
+1

**Comment by KevinMartin** [comment]
+1

**Comment by jefffriesen** [comment]
Has anyone else been able to get Metabase to connect to an RDS MySQL instance?

> java.sql.SQLException: Access denied for user 'snugg'@'63-253-110-78.ip.mcleodusa.net' (using password: YES)

**Comment by jefffriesen** [comment]
@mickey @nambrot @KevinMartin Have any of you been able to connect to your RDS instance from Metabase?

**Comment by holtkamp** [comment]
The Metabase [documentation suggests](http://www.metabase.com/docs/v0.12.0/administration-guide/01-managing-databases#secure-socket-layer-ssl) that it will try to use SSL. However, connections to the database seem to fail for [users that have been configured to require SSL](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport). Apparently Metabase does not use/consider [the public key as issued by Amazon](https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem)... So +1 on this!

**Comment by nambrot** [comment]
@jefffriesen unfortunately no

**Comment by jefffriesen** [comment]
@holtkamp @nambrot Thank you for responding and the tip. I asked people who know AWS better than I looking at it and they are investigating using a VPC. But I'll pass this on. 
Thanks again

**Comment by franceindia** [comment]
@holtkamp, your solution works and you're spot on about the issues you describe with requiring SSL vs. not requiring it.  
That said, isn't it a slipery slope to not require SSL for a user? Especially since you can't force SSL from within Metabase.  We have to trust that somehow behind the scenes, Metabase is using SSL to transfer data.  While I know how to list all connections on the serve with `SHOW FULL PROCESSLIST`, it' doesn't show whether a connection is SSL or not. This means I can't verify whether that things are happening over SSL.

The documentation says you can change the SSL setting in Metabase but I couldn't figure out where to do that (I may be missing something though): 

>  You can always change this setting later if you prefer to connect without this layer of security, but we highly recommend keeping SSL turned on to keep your data secure.

Of lesser danger if properly managed, but still not ideal, allowing even one user to connect without SSL opens up the possibility of someone indavertently setting up an unencrypted connection down the line.  

I'd love to hear people's thoughts on my above concerns.  Thus far, I have had no success setting up Metabase and an SSL RDS connection. I tried both Heroku and Elastic Beanstalk but unless I blindly trust Metabase to use SSL, I can't enforce it. Am I overthinking this?  
I'll be sure to update this thread if I have a breakthrough.

**Comment by aardvark82** [comment]
+1 I have a Google Cloud instance (managed MySql 5.7.14) I wish to connect to. It is setup to only allow SSL connections. 

- I don't want to setup SSH tunneling. There is no tunnel to connect on the managed instance to and I don't have a server available on the subnet.
- I don't want to setup a read-only, non SSL user. Db IP is exposed and I need security.

**Comment by robokaso** [comment]
I successfully connected to MariaDB 10.3 server that requires ssl by setting the "Additional JDBC connection string options" to `useSSL=true&verifyServerCertificate=false`

**Comment by holtkamp** [comment]
Hi @camsaul any news on this? AWS RDS is rotating their certificates. Maybe a nice time to support this?

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by slickrock22** [comment]
@holtkamp do you know if updating the cert on RDS will require a config change on beanstalk?  I posted in the discussion forum as well https://discourse.metabase.com/t/update-your-amazon-rds-ssl-tls-certificates-before-march-5-2020/8250

**Comment by holtkamp** [comment]
@slickrock22 no, sorry, no experience with beanstalk...

**Comment by jamesaq12wsx** [comment]
unsubscribe
-----Original message-----

**Comment by saywebsolutions** [comment]
> I successfully connected to MariaDB 10.3 server that requires ssl by setting the "Additional JDBC connection string options" to `useSSL=true&verifyServerCertificate=false`

@robokaso where do you place the key file and where/how do you specify the path to the key?

**Comment by tiago-as** [comment]
> > I successfully connected to MariaDB 10.3 server that requires ssl by setting the "Additional JDBC connection string options" to `useSSL=true&verifyServerCertificate=false`
> 
> @robokaso where do you place the key file and where/how do you specify the path to the key?

I also need to connect to to Mariadb and to specify the ca.pem... I haven't found anywhere some explanation of what parameters to give to "Additional JDBC connection string options" so Metabase knows where the pem file is.
If there is a way of doing this, could someone please paste an url for documentation or give a brief "How to"?

Thanks in advance

+1 on this ticket.

**Comment by flamber** [comment]
@tiago-as From https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/#provide-certificate-directly
Add this to connection string: `serverSslCert=/path/to/cert.pem`
Where the certificate you need locally is what the server references in it's `ssl_cert` configuration (think the default location is `/var/lib/mysql/server-cert.pem`)

**Comment by tiago-as** [comment]
@flamber Thanks for the explanation. I'll try it out and see if it works as expected.

**Comment by fagai** [comment]
Hello.
Based on the above information, I was able to make an SSL connection to RDS.

get root certificate of aws. Leave it in a suitable place.
https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem

Set JDBC options.
`useSSL=true&verifyServerCertificate=false&serverSslCert=/{path}/rds-combined-ca-bundle.pem`

Connect!

**Comment by stadeli** [comment]
This is still a problem in 2022 with metabase. It's more than obvious that metabase does not want to make it easy for self hosting clients. So that's the price we pay, spending HOURS researching dozens of blogs to try to find a solution that works. 
Ubuntu 20.4 / virtualmin / metabase installation with .jar file
on the metabase setup form in the browser, when you get a connection error, simply change the database name to the following (append ?xxx)

databasename?allowPublicKeyRetrieval=True&useSSL=false

it will work like a charm!

**Comment by andryan** [comment]
I also encountered this issue and managed to solve this by placing and mounting the MySQL's public_key.pem file into the docker instance of metabase, in my case /metabase-certs, and use the following "Additional JDBC connection string options": 
sslMode=VERIFY&serverRsaPublicKeyFile=/metabase-certs/public_key.pem
