### ISSUE TITLE
Trend visualization requires time column to be the first otherwise it shows blank visualization

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13710]
**Describe the bug**
Trend visualization requires time column to be the first otherwise it shows blank visualization.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize - do not select metric - group by Quantity:unbinned and CreatedAt:Month
![image](https://user-images.githubusercontent.com/1447303/98380771-478c2380-2049-11eb-96ca-6c1594c3417b.png)
3. Set visualization to Trend - just shows blank visualization
![image](https://user-images.githubusercontent.com/1447303/98380872-72767780-2049-11eb-9ac3-ee8927f90f21.png)
4. Change the summarize grouping, so CreatedAt:Month is the first with Quantity:unbinned as second, then it works:
![image](https://user-images.githubusercontent.com/1447303/98381039-9f2a8f00-2049-11eb-97b0-4c5127d58ed1.png)

**Information about your Metabase Installation:**
Tested 0.35 thru 0.37.0.2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by alxnddr** [comment]
@metabase/backend-developers it looks like a back end fix is requires for this bug because the `insights` prop does not have correct data:
<img width="871" alt="Screen Shot 2021-06-16 at 22 27 52" src="https://user-images.githubusercontent.com/14301985/122280657-1a162b00-cef2-11eb-870f-6ef47fb6fa21.png">
`last-change` and `previous-value` are missing

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/16638

Created a separate issue for missing BE data: https://github.com/metabase/metabase/issues/16683
