### ISSUE TITLE
Docker storage

### ISSUE THREAD

**Issue by danieljacobarcher** [metabase/metabase#1378]
Where are the basic configuration/user data stored when Metabase is deployed via Docker? Asking because in production, the Docker image is replaced with each deploy, so the storage needs to be persisted to the more secure parts of the server. For example: http://help.cloud66.com/managing-your-stack/service-storage

**Comment by agilliland** [comment]
In our documentation about running Metabase via Docker we provide some options for how to control where the application data is stored in order to ensure long term persistence ...

http://www.metabase.com/docs/v0.12.1/operations-guide/running-metabase-on-docker.html

quick answer is that by default the app will use a local H2 database file inside the container, so if your container is replaced then you'll lose your data.  to address that you can either 1) mount a persistent volume into your container and store the H2 database there, or 2) use a separate database like postgres which is what we recommend.

the H2 database option is really just meant to be easy for people who want to run the app locally on a laptop or for people who are just doing a quick trial.

**Comment by danieljacobarcher** [comment]
Awesome, thanks @agilliland. I don't know that it was clear enough from the documentation. Maybe your answer here will help others just getting started like me too.
