### ISSUE TITLE
database password is sent everytime you login as admin

### ISSUE THREAD

**Issue by slangwald** [metabase/metabase#1389]
Hi,

on each full load of the page all database passwords are exposed and sent via JSON to the client, if you are an admin user. ( http://localhost:3000/api/database/2 ). From a security perspective it would be good to make the passwords for the databases write-only (UI-server communication) and at best encrypted in the datastore backend. 

Or is there any reason to send it each time? 

Cheers, and thank you for the great work so far guys!

**Comment by tlrobinson** [comment]
FYI we've got an issue open for encrypting database details: #865

**Comment by camsaul** [comment]
I was thinking the same thing the other day. We don't expose the passwords in the UI so the endpoint should definitely be stripping this info

**Comment by salsakran** [comment]
+1

**Comment by agilliland** [comment]
@camsaul are you actively working on this?  i can take a shot at it if you're not.

either way, after taking a quick look at this one the main issue here is that we are currently using a separate api call to validate the connection details before saving.  for that api call to pass without an error it needs the password, which is why we had left the password to be returning in the `:details`.  

probably the better approach is to just remove the /api/database/validate endpoint and just run that check as part of the POST/PUT endpoints when creating and updating databases.  that way we remove an extra round trip to the server and we make it possible to solve this issue.

**Comment by camsaul** [comment]
Then you wouldn't be able to update the DB details without reentering the password. I think instead we should work on having some way for validate or PUT to use the existing password if a new one isn't specified. Just need to think of a way to do that but also let users unset passwords

**Comment by agilliland** [comment]
yeah, i'm fussing with a solution to that.  i think the simplest thing is actually to replace the real password with a known value when it's returned from the API (e.g. `**ProtectedPassword**`).  then when the call is made to update the database if we see that value we replace it with the existing real password, otherwise we assume the user changed the password and use the value they submitted.

**Comment by slangwald** [comment]
An additional thought: maybe move the passwords to a separate table, that way you can't return it by 'accident' in the future and wrap it in a specific api call.

**Comment by agilliland** [comment]
@slangwald , yeah that would definitely make sense.  I think we'll probably hold off on doing that until we tackle #865 and allow for encryption of the password, but I like the idea of separating out the credentials into their own table.
