### ISSUE TITLE
Clearing dashboard filter with default value is not preserved on refresh or direct link

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13960]
**Describe the bug**
When a dashboard has filter with default value, then it's not possible to clear that filter and do any type of page refresh without the default filters getting applied again.
This means it's not possible to clear a filter and send that dashboard URL to someone, or returning to dashboard after a drill-through will re-apply the default value.

**To Reproduce**
1. Simple question > Sample Dataset > Products - summarize Count by Category - viz as Pie - save as "Q1" to dashboard
2. Add two filters and connect to "Q1" - Categories and ID - set Default Value for Category to "Doohickey"
3. Going to the dashboard will automatically apply filter for Category, as expected
![image](https://user-images.githubusercontent.com/1447303/101174893-bd81ab80-3644-11eb-8080-958aea237139.png)
4. Clearing Category filter (and applying the other filter) removes it from the URL
![image](https://user-images.githubusercontent.com/1447303/101175038-f588ee80-3644-11eb-91c2-9e234ccab6bb.png)
5. Going into fullscreen, doing a browser refresh, or sending the current URL to a coworker will result in the default value getting reset and gives a different result than what I am currently seeing.
![image](https://user-images.githubusercontent.com/1447303/101175295-47317900-3645-11eb-96fd-d6415cfa1a92.png)

**Expected behavior**
This might be difficult to make backward compatible, and would probably require a bigger change to how the URL parameters are handled, but the expected behavior is that everyone should be able to see the same results that I am.

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.3 - has probably been the behavior for several years

**Severity**
Only giving P3, since it's not returning incorrect results, but adding Correctness, since it is wrong.

**Additional context**
Very related to #6070, and a bit to #5332 and #13708

**Comment by daltojohnso** [comment]
This bug definitely needs some product input as this is simply a consequence of how dashboard parameters work. We rely on it in-app, even -- any links to dashboards will go to a url like `/dashboard/:dashboardId` without added param values because the params code fills that in for us.

We could do something a bit hacky like preserve a keyword  to represent "don't use this parameter, even if it has a default value," but IDK what that keyword should be, nor do I know what that UI should look like 🙂

**Comment by daltojohnso** [comment]
@brunobergher had a good alternative to my above comment, to add additional logic to the URL beyond what dashboard parameters currently rely on. A good approach to avoid clobbering potential parameter IDs or values would be to append a hash to the URL and then add additional instructions there, similar to what we do when adding a card to a dashboard from the query builder view (we navigate to a url like `/dashboard/1#add=123` and the dashboard code knows to add the card with id `123` to the dashboard).

We can do something like... `/dashboard/1?state=foo#unset=customer_id,something_else` where `unset` is interpreted by the default parameter-setting code as a list of parameter ids to skip when adding default.

A few edge cases:
1. `/dashboard/1?state=foo#unset=state` -- I think the set value of `"foo"` should take priority over the presence of `state` in the `unset` list. We should also probably remove `state` from `unset` to make it clear we are using the `"foo"` value.
2. `/dashboard/1#unset=does_not_exist` -- if the parameter id doesn't match a parameter that exists the obvious thing to do is just to clean up the url.
3. I'm thinking that we only add an id to `unset` when a parameter has a default value since the presence of an undefaulted parameter in the list is a no-op.

**Comment by brunobergher** [comment]
Thanks for documenting these. Your take on these edge cases seem spot on for me.

**Comment by flamber** [comment]
My take would be to include the parameter without a value, which then overrules the Default Value, since the parameter exists in the URL. But I don't know the code logic behind the filters everywhere, so I don't know what's easiest.

So if you have a dashboard with two filters - State and City - and State has a default to "CA", then when visiting the dashboard directly `/dashboard/:id`, then it would automatic apply default `/dashboard/:id?state=CA` before querying cards.
Then if I remove the State value, it would change to `/dashboard/:id?state` instead of removing the parameter it completely, since it knows that State has a default value.

This has to work similarly for Public and Embedding.

**Comment by brunobergher** [comment]
I think that would indeed be the ideal way of doing things, but my understanding is that browser implementation of returning empty GET parameters is very unreliable. I'd defer to Dalton on what works best, though.

**Comment by daltojohnso** [comment]
I was able to handle this relatively easily the way @flamber prefers it, though I don't want to go too much further with this without some usability testing since this code is a little infuriating to deal with, so if you can, please test out the code on #17299.

I've made it so that clearing a defaulted parameter keeps the slug in the query param. In order to return to the defaulted value the user will have to explicitly remove the slug from the URL, so I wonder if we ought to add an additional button to the widget to return to the defaulted value.

A query param like `foo=` means `foo` is set to an empty string `""` so `""` becomes an unusable parameters value. It doesn't really work already, so that doesn't seem like a huge deal. We could add an "is empty string" parameter filter to remedy this if desired.
