### ISSUE TITLE
Split `report-timezone` Setting into three new Settings 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14056]
Here's a few ideas for improving our handling of timezones:

## `report-timezone` is overloaded

Right now we only have one global Time zone setting, `report timezone`, which is used to determine ~three~ four separate things:
1.  which timezone to show results in
2.  which timezone to interpret local temporal values (i.e., without zone/offset information) as being in
3.  which timezone to use to determine absolute moments in time corresponding to date filters e.g. the exact meaning of `month = 12-2020`
4. which time zone to use when doing aggregations like group by month. 

These are really separate concepts -- maybe I have a `TIMESTAMP WITHOUT TIME ZONE` column that I'd like to interpret as being in UTC, find values during December 2020 in Eastern time, and then display as `US/Pacific`. This is totally impossible to do in Metabase right now, and things are busted if you want to use anything but one time zone for all three things `report-timezone` does.

I think we should split `report-timezone` into `display-time-zone`, ~`local-time-zone`~ `implicit-time-zone`, and ~`filter-time-zone`~ `reporting-time-zone` .

*  ~`local-time-zone`~ `implicit-time-zone` would be what time zone to treat local temporal values as being in. 
*  ~`display-time-zone` is the zone to display results in~ [See here](https://github.com/metabase/metabase/issues/14056#issuecomment-1387557246) for why `display-timezone` may be a bad idea.
*  ~`filter-time-zone`~ `reporting-time-zone` (?) `query-timezone` (?) is the zone to use for filter widgets as described above, **and** for aggregating e.g. group by month. I originally thought we should call this `filter-time-zone` when it was just for filter widgets but Sameer pointed out that we also need something for aggregations. So this Setting is for both points now. I'm not convinced `reporting-time-zone` is the perfect name since it sounds too much like the old name and suggests to me that it affects query result formatting, so we can noodle on this name a bit. Maybe `query-time-zone` or something would work.

#### NOTE: While there are a lot of open questions in comments below relating to whether these should be User-local or Database-local or what, we can implement this now and worry about that later, since this has to be done regardless.
 
# Related issues

These are now being tracked in different issues so you can ignore them for purposes of tackling this issue, but I'll leave them here because there is some discussion around them below

## Give timezone settings Database-level and/or Field-level overrides

Ideally I think we'd want to make the columns above global like `report_timezone`, but also have Database/Table/Field overrides. I think it's totally possible that you have one database in UTC and another in US/Eastern. Right now Metabase cannot handle such a situation.

~We should consider implementing Database-local Settings -- this is a separate rabbit hole, so I've opened #14055 for this.~ Done

## Stop using session/connection/query timezones entirely

Just generate SQL that uses the appropriate TZ offset functions. Only a fraction of our DBs support "session timezones" which means timezone support is somewhat broken on DBs like BigQuery. Other DBs cannot set session timezone on read-only connections, so this would give us the extra benefit of being able to make more things read-only.

## Other things to consider

*  Just having timezone isn't enough for a `LocalTime` -- should we treat `13:35` `US/Pacific` as `13:35-07:00` or `13:35-08:00`? We might need a `local_offset` column as well

**Comment by paulrosenzweig** [comment]
Good point that `display_timezone` and `filter_timezone` are logically separate! Though, I can't really imagine a situation where you'd want to set them differently.

It makes sense to split out `local_timezone` and allow field-level overrides. For this situation though, I think the "right" solution is to fix/disambiguate the data in the db using dbt or another tool. Metabase currently does a lot of data cleaning tasks (e.g. field remapping), but I think we should move away from that or at least consolidate it away from our core BI functionality. Adding timezone data to ambiguous fields feels like it falls into that bucket.

Switching from session timezones to SQL TZ offset functions is the biggest win IMO. If you're using BigQuery, there's no way to group in a non-UTC timezone. Since that needs to work at query-time, it seems to be more clearly a BI responsibility.

**Comment by salsakran** [comment]
One V.Next things it would be cool to be able to express -- 
Given a table of restaurant reservations with a `time_reserved` as a `timestamp with timezone` with reservations across a large spread of timezones (eg, nationwide)
"what are reservations made for lunch time (11a-2p in that timezone)?"

**Comment by flamber** [comment]
Related to #4284 and #6439

**Comment by paoliniluis** [comment]
Adding this one to this list https://github.com/metabase/metabase/issues/5927 (which IDK if it's too old and even solved but never closed), but just FYI

**Comment by salsakran** [comment]
Some quick thoughts -- 

`local_timezone` should probably be `implicit_timezone` 
I think `local` can be overloaded and confused me on first read. 

`filter_timezone` should stay `reporting_timezone` 
i.e. the timezone to use when filtering dates, aggregating by day, etc.

`display_timezone` should just be a display change of anything coming back from the DB, and maybe even strictly client-side?

**Comment by salsakran** [comment]
we've seen a couple cases of things like ` I think it's totally possible that you have one database in UTC and another in US/Eastern.` so that's no longer theoretical

**Comment by camsaul** [comment]
One question I think we forgot to ask is whether we can or should support just leaving local datetimes e.g. `timestamp without time zone` local without affixing one offset or another to them, and just return them as-is in the results. In other words, should we support having no `display_timezone` at all for local datetimes?

**Comment by camsaul** [comment]
Posting [@salsakran's comment in Slack here for history purposes/context](https://metaboat.slack.com/archives/C04DN5VRQM6/p1670979040706609?thread_ts=1670872832.221129&cid=C04DN5VRQM6)

> Implicit timezone and query timezone have nothing to do with each other and can be getting set by different people in different parts of the organization.
>
> Implicit timezone is decided by whoever set up a the table (perhaps years in the past). Often once it has been set it is too much hassle to change, and if there are companies with legacy databases, it's very very likely that someone did something stupid here. The ability to clean that up via an implicit DB-wide timezone really smooths out that world
>
> Query timezone is the timezone for a _specific_ query. For anyone with a dataset that has rows that span a variety of timezones, it's not uncommon to specify a timezone for a specific query. For companies with operations that are geographically distributed things like "set these reports to run under this store's timezone" are not uncommon.
>
> Splitting all these different concepts up at the QP level _help_ us unravel the weirdness that is timezones because different DBs and even different JDBC drivers have subtly different timezone behaviour, and the ability to explicitly correct one of these lays helps a lot. Exposing them to the user isn't even strictly necessary to get value from them. The list in #14056 came from a pretty deep audit of all the places where there are fundamentally different timezones at play in the various layers from the browser all the way back to the DB table, and allowing us to both reason about them, as well as patch things at the source of a DBs weirdness.

I like the idea of having a per-query override for the query timezone -- that makes sense. I think we'll probably want to have a global default Setting and support per-query overrides as an option in the query itself or something. Open question: should we support Database-specific overrides for `query-timezone`? I'm not sure about this. Do we reasonably expect people to want to do aggregate in one timezone for one database, but not for another? For example maybe I have a Europe Database and when I do "count of new users grouped by month" that should be grouping by UTC by default, and I have a separate North America Database and when I do "count of new users grouped by month" it should be grouped by US/Eastern by default. Or would the per-query override be enough for these situations? Why stop at Database? We originally discussed per-Field overrides in #6439 but decided it wasn't needed because Models exist now

**Comment by camsaul** [comment]
I think `implicit-timezone` should be a global Setting with per-Database overrides. Continuing the example above, maybe I have a Europe Database and when I do `SELECT *` the `datetime` columns should get interpreted as being in UTC; when I do `SELECT *` in the North America Database I want the `datetime` columns to get interpreted as being in `US/Pacific`. #e originally planned to make this overridable in per-Field in #6439, but you can now use models to accomplish this.

**Comment by camsaul** [comment]
RE `results-timezone` -- I think this should probably be a global Setting that can be User-local (i.e., a User can have their own value), but my conviction on this point is week... should there be a per-query override for this as well?

**Comment by camsaul** [comment]
Mega thread in https://metaboat.slack.com/archives/C04DN5VRQM6/p1670872832221129. Once a consensus has been reached there I will update this

**Comment by snoe** [comment]
Working through splitting `display-timezone` revealed a core problem with interactions if `display-timezone` and `query-timezone` differ.

In a linear workflow, the separation of query and display timezones make sense. query is the "input" and display is the "output":
<img width="500" alt="image" src="https://user-images.githubusercontent.com/105012/213264616-9b4d906a-7c48-4dd7-8b04-92119b9dc2cc.png">

However, with user interaction in play, it's clear that such a split puts a ton of onus on the user to interpret the displayed times back into filter times. 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/105012/213265211-b91280e5-b044-4d88-a8db-59c754e3535b.png">

In fact, with this circular interaction in mind, I'll argue that such a split only adds a new confusion to the problem and doesn't actually address any of the issues we found in the wild. It is important to keep filtering, grouping, expressions AND results in the same timezone since those are the points of interaction with the user.

The problems of display timezone, are (as far as I can see), issues of overriding the report timezone at the user or query level. We can look at logging systems like CloudWatch or logtail for ux examples. Logs are filtered, queried and displayed in a consistent timezone, usually defaulting to the browser's timezone and can be overridden during the browser session or specified in a filter as a fully qualified instant (if you need to paste in a given timestamp in a different tz). The UI makes the timezone that things are operating in visible.
