### ISSUE TITLE
Document pivot tables

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14090]
- [Product doc](https://docs.google.com/document/d/1ScNpNjjYlsi6syyHFKctTlZ149g5ulTIHFnAmmq6h58/edit)
- [Implementation issue](https://github.com/metabase/metabase/issues/13662)

This is a new tabular visualization type, and is a classic Excel/Sheets pivot table, in essence. There are three main sub-features for this feature.

## Grouping and pivoting

For a given query result, it allows you to assign fields in the result into one of three "buckets." You can click and drag the fields from one bucket to another in the settings. These are the buckets:
- fields that generate the table's _rows_
- fields that generate the table's _columns_
- and fields that generate the table's _values_

Assigning a field to the "columns" bucket then pivots that field, rendering each unique value of that field horizontally as a column heading.

You can put multiple fields in each of these buckets. Doing so for columns or rows causes each additional field after the first to be nested within the field before it; so the order matters. You should also be able to change the sort order for each grouping row or column, so you could e.g. sort descending by Created At, then Ascending by Product Category.

## Subtotals

Each grouping row displays a subtotal if the group has subtotals within it. E.g. if my rows are grouped first by Product Category, then by State, the States are a subgroup for each product category, and I'll see subtotals for each one, like Gizmo. If I have any pivoted fields, then I'll also see a subtotal for each row. I should be able to toggle subtotals on or off for each grouping field. Also, when subtotals are on, I should see one for _each metric_ in my "values" bucket, and the subtotal should reflect the type of aggregation the metric is — e.g., if my metric is `Average Age` the subtotals for that metric will be _averages_, not sums.

## Collapsable/expandable rows

This hasn't been implemented yet, but what it should do is allow you to collapse any row grouping that has at least one child grouping within it. So if I'm grouping by Created At, then Category, then Source, I could collapse a category, like Widget, down to just its subtotal row, hiding all the Sources.

**Comment by serhiiivan** [comment]
Hi @maliayas @jeff-bruemmer @jeff-bruemmer @wilson @tpope @michaelklishin 

My name is Serhii from Ukraine and I am a Software Engineer. Do you know "Eric Dominic" by any chance? https://www.linkedin.com/in/eric-di-domenico/

Eric (@qwertme) hired me on Upwork and I worked on "RV Care" and "Virtual Briefing Center" project with Ruby on Rails. Recently, I was not able to dedicate much time to these projects because of personal problems. Due to this simple reason, he pressed to refund $2350 on Upwork. How he is a thief! I cannot tolerate him.

I am an old person and have families so I am working hard. If possible, I would like you to judge this problem.

Thank you,
Serhii
