### ISSUE TITLE
App becomes nearly unusable after trying to visualize a pivot table with 3+ metrics and 3+ breakouts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14336]
Here's an [example query](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MiwiYWdncmVnYXRpb24iOltbImNvdW50Il0sWyJzdW0iLFsiZmllbGQtaWQiLDE0XV0sWyJhdmciLFsiZmllbGQtaWQiLDEwXV1dLCJicmVha291dCI6W1siZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDEyXSwicXVhcnRlciJdLFsiZmstPiIsWyJmaWVsZC1pZCIsMTFdLFsiZmllbGQtaWQiLDI1XV0sWyJmay0-IixbImZpZWxkLWlkIiwxMV0sWyJmaWVsZC1pZCIsMjZdXSxbImZrLT4iLFsiZmllbGQtaWQiLDEzXSxbImZpZWxkLWlkIiw0XV0sWyJiaW5uaW5nLXN0cmF0ZWd5IixbImZrLT4iLFsiZmllbGQtaWQiLDEzXSxbImZpZWxkLWlkIiw2XV0sImRlZmF1bHQiXV19LCJkYXRhYmFzZSI6MX0sImRpc3BsYXkiOiJwaXZvdCIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDEyXSwicXVhcnRlciJdLFsiZmstPiIsWyJmaWVsZC1pZCIsMTFdLFsiZmllbGQtaWQiLDI1XV0sWyJmay0-IixbImZpZWxkLWlkIiwxMV0sWyJmaWVsZC1pZCIsMjZdXSxbImZrLT4iLFsiZmllbGQtaWQiLDEzXSxbImZpZWxkLWlkIiw0XV0sWyJiaW5uaW5nLXN0cmF0ZWd5IixbImZrLT4iLFsiZmllbGQtaWQiLDEzXSxbImZpZWxkLWlkIiw2XV0sIm51bS1iaW5zIixudWxsLHsibWluLXZhbHVlIjowLCJtYXgtdmFsdWUiOjUuMjUsIm51bS1iaW5zIjo4LCJiaW4td2lkdGgiOjAuNzV9XV0sImNvbHVtbnMiOltdLCJ2YWx1ZXMiOltbImFnZ3JlZ2F0aW9uIiwwXSxbImFnZ3JlZ2F0aW9uIiwxXSxbImFnZ3JlZ2F0aW9uIiwyXV19LCJwaXZvdF90YWJsZS5jb2xsYXBzZWRfcm93cyI6WyJbXCIyMDE2LTA0LTAxVDAwOjAwOjAwLTA3OjAwXCJdIl19fQ==). I'm running off of the `pivot-tables-collapse-expand-rows` branch on Chrome 87 with macOS Big Sur on a late 2015 Macbook pro. 

Trying to open up the filter/summarize or settings sidebars becomes unusably slow when you have a query of this size, as you can see in this video: https://share.getcloudapp.com/p9ury7yZ

**Comment by ariya** [comment]
Just to confirm @paulrosenzweig, I believe that `pivot-tables-collapse-expand-rows` branch was already merged to master (as of commit ed089df3).

**Comment by paulrosenzweig** [comment]
@ariya what do you mean? I think this issue was filed on a version without that code. Though, I don't expect `pivot-tables-collapse-expand-rows` helped or hurt this performance issue.

**Comment by ariya** [comment]
For a start, the query results in a large amount of data being transferred from the back-end, 5.6 MB total payload (although it's only 1.9 MB transferred thank to g-zip). For completeness, the query is:
```
{
  "type":"query",
  "query": {
    "source-table":2
    "aggregation":[
      ["count"],
      ["sum",["field-id",14]],
      ["avg",["field-id",10]]
    ],
    "breakout":[
      ["datetime-field",["field-id",12],"quarter"],
      ["fk->",["field-id",11],["field-id",25]],
      ["fk->",["field-id",11],["field-id",26]],
      ["fk->",["field-id",13],["field-id",4]],
      ["binning-strategy",["fk->",["field-id",13],["field-id",6]],"default"]
    ]
  },
  "database":1,
  "parameters":[],
  "pivot_rows":[0,1,2,3,4],
  "pivot_cols":[]
}
```

There are > 69,000 rows sent by the back-end. The first few rows look like:
```
["2016-04-01T00:00:00-07:00","AK","Google","Gadget",3.75,0,2,79.63475256480312,27],
["2016-04-01T00:00:00-07:00","AK","Google","Gizmo",3.0,0,2,149.21192315709592,3],
["2016-04-01T00:00:00-07:00","AL","Google","Doohickey",4.5,0,1,44.4315141414441,6],
["2016-04-01T00:00:00-07:00","AL","Organic","Widget",3.0,0,1,36.60883787357609,3],
["2016-04-01T00:00:00-07:00","AR","Google","Gizmo",3.0,0,1,36.683234169385244,3],
["2016-04-01T00:00:00-07:00","AR","Google","Widget",3.75,0,1,50.90170136783837,3],
["2016-04-01T00:00:00-07:00","CA","Twitter","Gadget",3.75,0,1,33.39659192329691,7],
["2016-04-01T00:00:00-07:00","CA","Twitter","Widget",3.75,0,1,75.41148135558485,5],
["2016-04-01T00:00:00-07:00","CO","Affiliate","Widget",3.75,0,1,89.0134841727878,7],
```

First, I wonder if this is also related to too-many-rows problem outlined in #14329, but it doesn't look like it since there are rarely duplicated rows (thus, not showing the same symptoms).

When I captured the calls using the Performance tab in Chrome Dev Tools, looks like some event handler (in this for `Event:focus`) is **terribly slow**. It's taking 316 ms, or roughly equivalent to 3 fps. And this is on a beefy desktop machine (likely a few times more powerful than a Macbook Pro 2015). No wonder the sluggishness is so noticeable.

![image](https://user-images.githubusercontent.com/7288/104250410-6d0b2400-5422-11eb-81fd-cb40c2831d80.png)

**Next step**: Narrow down the above slow execution.

**Comment by paulrosenzweig** [comment]
@ariya sorry I didn’t set more context around this issue yesterday before you jumped into it. Here are some potential leads:
- The initial structuring is done during `render`.
To render the pivot table we split apart the unified result set into the various breakout sets, build an index to look up values by the pivoted columns, and create the full data structures used to populate the top and left headers. The body cells are formatted as requested by the virtual grid, but the values in the top and left headers are formatted in one go. A quick win is do only do this when the data changes.
- We force the grid to recompute sizes every render.
I ran into issues where the grids weren't updating correctly so I moved the calls for grids to resize directly into render. This is wrong but seemed to get past the issues. It's easy to check if this is the culprit by commenting the `recomputeGridSize` lines.
- The virtual table “cells” are big. 
The virtual table cells don't map directly to visual cells. There's only one virtual grid cell per "top level" value in the headers. Each outlined area is rendered together:
<img width="1314" src="https://user-images.githubusercontent.com/691495/104345871-cdef3680-54cc-11eb-9ed5-d0a7a1c78c04.png">
This structure made it easier to layout the grids initially. I assumed each virtual grid cell would be small enough to avoid perf issues, but I was very likely wrong. With high cardinality dimensions stacked on top of each other, the cells can be pretty big. Though, with large cells we should only ever render one or two at a time if we configure the virtual grid correctly.
Unwinding this is a pretty involved refactor, but it's doable if that's the core issue.

**Comment by ariya** [comment]
I did check `recomputeGridSize` and I was sure it wasn't the problem. I do it again, adding the time measurement:

```diff
--- a/frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
+++ b/frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
@@ -131,9 +131,11 @@ export default class PivotTable extends Component {
     // Putting this in componentDidUpdate led the dimensions to be recomputed _after_ re-rendering the cells.
     // According to the docs, recomputing dimensions should force a render but this didn't occur correctly.
     // The downside of keeping it here is that the dimensions are computed twice per render.
+    console.time('recomputeGridSize');
     this.bodyGrid && this.bodyGrid.recomputeGridSize();
     this.topGrid && this.topGrid.recomputeGridSize();
     this.leftList && this.leftList.recomputeRowHeights();
+    console.timeEnd('recomputeGridSize');
 
     const { settings, data, width, height } = this.props;
     if (data == null || !data.cols.some(isPivotGroupColumn)) {
```

and all I see from a few logging, they are < 2 ms.

I tried to follow some other leads, but they were all red herrings.

My current guess so far is that this is React trying to handle a large number of components. If we take a look at another recording snapshot below, the function call that (in total) takes > 120m can be traced to all the internal functions within React (and likely React DOM). The first half seems to relate to nested component handling (maybe diffing or reconcialition?) and the second half triggers the browser's CSS recalc (see the dark block "Recalculate Style").

![image](https://user-images.githubusercontent.com/7288/104389066-7b734180-54ef-11eb-867b-12b530fd6254.png)


When I tracked down the number of DOM nodes being handled, for this case, it amounts to approximately **220,000**. That's a lot of DOM nodes! No wonder the total heap taken by JavaScript skyrockets to ~300 MB.

Unfortunately, I could not use React DevTools Profile to get some additional deeper insight since we are not using React 16 yet.

Another experiment I did: reduce the breakouts by removing _Created At_. The dataset sent by the back-end was only at about 598 KB (with g-zip, compressed down to 316 KB). This however still didn't affect the sluggishness, I still saw _"Event:scroll"_ taking as long as 300 ms.

**Next step**: attempt to accurately measure the dimension of the virtual grid (cells).

**Comment by paulrosenzweig** [comment]
> When I tracked down the number of DOM nodes being handled, for this case, it amounts to approximately 220,000.

😳 oof yeah that sounds like the third lead I mentioned in my previous comment. The virtual grid cells can grow with stacked breakouts. I guess that makes sense:
50 states x ~20 quarters x ~5 sources x ~5 categories x ~10 bins of whatever = 250,000

That's way too big, so I'll need to update how that's structured. The body cells will be straightforward to decompose, but the headers will be trickier.

Separate from this specific performance issue, we should add some reasonable limits to these endpoints. With #14329 fixed, this query will still run multiple slow queries. I wouldn't want to run pivot tables with more than ~5 breakouts. On the frontend, even with this issue fixed, we'll eventually hit problems structuring so many rows into the lookups for pivot tables.
