### ISSUE TITLE
Custom expression errors are too verbose now

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14345]
I believe I saw @ariya made some recent changes to custom expression error messaging, and while I was playing around with them on master, I found a few cases where I was getting way too much error noise.

In this gif, for example, I don't think I'd expect to see any of these error messages, unless I tabbed out of the expression input field. The "unknown field" error isn't helpful here, as I'm often typing a function name. And the error I'm getting after typing a function name but before I've typed an opening paren isn't helpful as it's way too verbose.

![expression-errors](https://user-images.githubusercontent.com/2223916/104218409-86e04300-53f1-11eb-944c-47273dd297ac.gif)

There are similarly odd errors when writing aggregation or filter expressions, too. E.g. in this case, I'm writing a filter expression and have selected a valid field, but I'm being told I've selected an invalid segment, which is unhelpful:

![image](https://user-images.githubusercontent.com/2223916/104219125-8e541c00-53f2-11eb-8722-3a374a6c614e.png)

Here's that same aggro parentheses error when doing an aggregation expression:

![Screen Shot 2021-01-11 at 9 41 22 AM](https://user-images.githubusercontent.com/2223916/104219196-ac218100-53f2-11eb-92a3-8f6fd316111f.png)

**Comment by rlotun** [comment]
this is also related to one I just opened last night: https://github.com/metabase/metabase/issues/14341

**Comment by nemanjaglumac** [comment]
^ #14341 is now reproduced. It feels like an overkill to reproduce this issue as well because the fix for one will most likely fix both. However, just LMK if you think it's worth reproing this issue separately and I'll do it in a second.

**Comment by ariya** [comment]
BTW custom expression enhancement I'm doing right now (see #14214) is still in the feature branch (it's not part of master yet, at least I don't plan to merge it while 0.38 is still in flight).

I'm happy to include this problem as part of the same investigation thought my gut feeling says that this is potentially just a regression.

**Comment by ariya** [comment]
The second issue ("Unknown Segment...") is a duplicate of what @flamber already filed in #12268. I suggest tracking it there instead, as it also contains other useful bits. Note that this is not a recent problem, it has been like that since 0.35.

The first issue (too verbose error message) is definitely a regression in 0.37 due to PR #13724. This becomes a problem in master as well since that branch is merged to master.

To demonstrate this, first checkout commit c235432b (this is in `release-x.37.x` branch, **before** PR 13724 is merged):

![image](https://user-images.githubusercontent.com/7288/104265217-f5e58800-5441-11eb-924e-0e6126f7f3be.png)

then do the same for commit b9cebc18 (this is in `release-x.37.x` branch, **after** PR 13724 is merged):

![image](https://user-images.githubusercontent.com/7288/104265051-9be4c280-5441-11eb-9952-438fd1783d84.png)

**Next step**: figure out why the regression happened.

**Comment by nemanjaglumac** [comment]
@ariya if it helps, "too verbose" part has Cypress coverage (see: https://github.com/metabase/metabase/pull/14344)

**Comment by flamber** [comment]
I think we can close this in favor of #14341, which covers both the error message and missing initial popup selector.

**Comment by mazameli** [comment]
Closing in favor of #14341.
