### ISSUE TITLE
Allow more columns to be grouped by default

### ISSUE THREAD

**Issue by podviaznikov** [metabase/metabase#1437]
I just started using Metabase.

I connected my PostreSQL database and was able to created dashboard with few questions.
However I noticed that I can't group my rows using all table columns. Most of the columns are date columns and the rest is missing. Can you give my some hints why that might happen?

**Comment by podviaznikov** [comment]
Ok, I got it. I need to mark columns as dimensions manually.

**Comment by tlrobinson** [comment]
I'm going to reopen and rename this issue since we should be doing a better job of detecting which columns are dimensions automatically, or possibly loosen the requirements for a field to be grouped.
Can you provide some details about those columns, in particular their schema types and cardinality?

**Comment by podviaznikov** [comment]
So column type is varchar. But it has index. So maybe if column has index you should be able to group by it?

Also small win would be to add instruction into the grouping dialog to go and change metadata if your grouping field is missing from the list.

**Comment by podviaznikov** [comment]
Cardinality was probably low. I think it was several hundreds unique values for the 5 million rows.

**Comment by iwaffles** [comment]
Ran into the same problem myself, @podviaznikov. Was trying to group together first/last name and email (I believe they are all the same type). Little confused about this. Looks like everything is set to Information by default. 

It also seems that I cannot group by more than 2 columns: 

![pasted_image_11_4_15__10_34_am](https://cloud.githubusercontent.com/assets/7333/10947893/9b65a7e0-82df-11e5-85b6-0b4052ff973c.png)

It'd be nice to be able to add multiple so that I could generate a report of all sales including email address, total, name, and possibly other data (in a table only, I can understand why you can't do more then 2 dimensions on a graph).

For the time being I've written sql queries to handle this – an excellent feature.

**Comment by tlrobinson** [comment]
@iwaffles I think #1445 is actually what you want in order to "generate a report of all sales including email address, total, name, and possibly other data"

**Comment by pavei** [comment]
+1

**Comment by tlrobinson** [comment]
For reference, the current criteria for automatically marking columns as `:special_type` of `:category` is <= 40 distinct values: https://github.com/metabase/metabase/blob/master/src/metabase/driver/sync.clj#L409-L411 In the frontend we allow you to group by columns that have `:field_type` of `:dimension` or columns that are considered date/times, categories, or entities: https://github.com/metabase/metabase/blob/master/frontend/src/lib/schema_metadata.js#L57-L60

**Comment by salsakran** [comment]
This is no longer relevant since PR #2192
