### ISSUE TITLE
Dashboard subscriptions: broken dropdown when trying to set Slack subscription/pulse to Hourly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#14399]
I'm working from memory here, but I believe that in version 0.37 and before, this second dropdown would let you choose if an hourly Pulse would get sent at the top of the hour, or at the :15, :30, or :45 of the hour. Something got changed in master in this component, though, and now it's displaying a dropdown with a bunch of integers, and clicking on an option doesn't do anything. No JavaScript console errors.

This is on our Stats instance:

![Screen Shot 2021-01-14 at 10 27 29 AM](https://user-images.githubusercontent.com/2223916/104633797-8abfcf80-5654-11eb-8780-8d486404c777.png)

**Comment by dpsutton** [comment]
The previous UI had no extra information for hourly:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/6377293/104650665-27e22e80-567c-11eb-939d-ecc58b7fdb5a.png">

Hourly always meant at 0 minutes. This was recently changed in https://github.com/metabase/metabase/pull/14343. We need the minute resolution for scheduling syncing so that the hourly syncs of dbs can be spread out in time instead of all running at 0 minutes past the hour. The schedule widget was expanded to handle this and correctly works on the sync schedule widget of the db settings. I'm surprised it doesn't work in other contexts.
