### ISSUE TITLE
Login redirects to root, if already logged in and visiting URL like `/auth/login?redirect=..`

### ISSUE THREAD

**Issue by megapies** [metabase/metabase#14436]
Hi there,
I encounter abnormal happen about authentication.

**Description**
when someone opens metabase link without authentication, it will transform URL from `https://metabase.example.com/dashboard/47?date=2020-01-16` to `https://metabase.example.com/auth/login?redirect=%2Fdashboard%2F47%3Fdate%3D2021-01-16`.

It works well when there are not already authenticate in browser, but in authenticated browser it does not redirect to specific path.

**To Reproduce**
open URL like `https://metabase.example.com/auth/login?redirect=...` in already authenticated (log in) browser. It will not redirect.

**For more information**
I encounter this situation when using in-app browser (like Line, Facebook). metabase cannot detect authentication when open in in-app browser although you already login in Chrome. It will transform URL to /auth/login?redirect=

---
Thank you in advance,

**Comment by flamber** [comment]
Reproduce:
1. Tab1: Login to Metabase. Tab2: Go to `/collection/root`
2. Tab1: Logout of Metabase. Tab2: browser refresh, so it changes URL to `/auth/login?redirect=%2Fcollection%2Froot`
3. Tab1: Login to Metabase. Tab2: browser refresh, which then goes to `/` instead of `/collection/root`

Have a feeling it's related to #13666

**Comment by qnkhuat** [comment]
This seems to be a FE bug and I'm not familiar with the FE code base enough to debug this 🥲
