### ISSUE TITLE
CSV exports of timestamps at midnight (00:00:00) is truncated to date

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14504]
**Describe the bug**
CSV (and JSON) downloads of timestamp columns at midnight (00:00:00) is truncated to date. XLSX are correct (since 0.36.8).

**To Reproduce**
1. Native question > Sample Dataset:
```sql
SELECT CAST(TIMESTAMP '2020-01-01 00:00:00' AS TIMESTAMP(0)) AS "DATETIME", CAST(TIMESTAMP '2020-01-01 00:00:00' AS DATE) AS "DATE"
UNION ALL 
SELECT CAST(TIMESTAMP '2020-01-02 00:00:22' AS TIMESTAMP(0)), CAST(TIMESTAMP '2020-01-02 00:00:22' AS DATE)
UNION ALL 
SELECT CAST(TIMESTAMP '2020-01-03 03:03:03.333' AS TIMESTAMP(0)), CAST(TIMESTAMP '2020-01-03 03:03:03.333' AS DATE)
```
2. Export as CSV returns the following:
```
DATETIME,DATE
2020-01-01,2020-01-01
2020-01-02T00:00:22,2020-01-02
2020-01-03T03:03:03,2020-01-03
```

**Expected behavior**
```
DATETIME,DATE
2020-01-01T00:00:00,2020-01-01
2020-01-02T00:00:22,2020-01-02
2020-01-03T03:03:03,2020-01-03
```

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.7 - regression since 0.36.8, which fixed a lot of export issues in PR #13447

**Comment by dpsutton** [comment]
I'm gonna disagree with the `Difficulty:Easy` label here. This behavior is intentional. The code in `metabase.query-processor.streaming.common/format-value` explicitly does this for `LocalDateTime`:

```clojure
(extend-protocol FormatValue
  ...
  LocalDateTime
  (format-value [t]
    (if (= (t/local-time t) (t/local-time 0))
      (format-value (t/local-date t))
      (u.date/format t)))
   ...
)
```

We've been using the presence of time at midnight to indicate the time is irrelevant and an artifact of using the wrong type (LocalDateTime) when we are dealing with only Date information. Blindly removing this check will just reintroduce the bug that this is fixing.

We do have the cols metadata at one stage of writing results. We could get the index of any `type/Date` columns and add some wrapper or type coercion to ensure that they get formatted correctly.

```clojure
(defmethod i/streaming-results-writer :csv
  [_ ^OutputStream os]
  (let [writer (BufferedWriter. (OutputStreamWriter. os StandardCharsets/UTF_8))]
    (reify i/StreamingResultsWriter
      (begin! [_ {{:keys [cols]} :data}]
;; use cols to figure out date vs datetime types
        (csv/write-csv writer [(map (some-fn :display_name :name) cols)])
        (.flush writer))

      (write-row! [_ row row-num]
;; use date information
        (csv/write-csv writer [(map common/format-value row)])
        (.flush writer))

      (finish! [_ _]
         ;; TODO -- not sure we need to flush both
        (.flush writer)
        (.flush os)
        (.close writer)))))
```

@camsaul I suspect you have the best 30,000 foot overview. Do you think it might be feasible for `:type/Date` columns to end up as a `LocalDate` rather than a `LocalDateTime` throughout metabase and solve this "at the source" rather than piecemeal at particular points like csv writers?
