### ISSUE TITLE
Regex escape characters being removed after saving of a regexextract expression

### ISSUE THREAD

**Issue by paulvolk** [metabase/metabase#14517]
**Describe the bug**
Regex escape characters being removed after saving of a regexextract expression

**Logs**
`:json_query
{:database 5,
:query {:source-table 423916, :expressions {:Hostname ["regex-match-first" ["field-id" 3690821] "(?<=//)[^/]*"]}},
:type "query",
:parameters [],
:middleware {:add-default-userland-constraints? true}},
:native
{:query
"SELECT \"source\".\"page\" AS \"page\", \"source\".\"day\" AS \"day\", \"source\".\"score\" AS \"score\", \"source\".\"hits\" AS \"hits\", \"source\".\"errorcount\" AS \"errorcount\", \"source\".\"Hostname\" AS \"Hostname\" FROM (SELECT regexp_substr(\"ng_report\".\"report_aggregate_page_day_prod\".\"page\", '(?<=//)[^/]*') AS \"Hostname\", \"ng_report\".\"report_aggregate_page_day_prod\".\"page\" AS \"page\", \"ng_report\".\"report_aggregate_page_day_prod\".\"day\" AS \"day\", \"ng_report\".\"report_aggregate_page_day_prod\".\"score\" AS \"score\", \"ng_report\".\"report_aggregate_page_day_prod\".\"hits\" AS \"hits\", \"ng_report\".\"report_aggregate_page_day_prod\".\"errorcount\" AS \"errorcount\" FROM \"ng_report\".\"report_aggregate_page_day_prod\") \"source\" LIMIT 2000",
:params nil},
:status :failed,
:class com.amazon.support.exceptions.ErrorException,
:stacktrace
["com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)"
"com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)"
"com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)"
"com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)"
"com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)"
"com.amazon.redshift.client.PGMessagingContext.getErrorResponse(Unknown Source)"
"com.amazon.redshift.client.PGClient.handleErrorsScenario2ForPrepareExecution(Unknown Source)"
"com.amazon.redshift.client.PGClient.handleErrorsPrepareExecute(Unknown Source)"
"com.amazon.redshift.dataengine.CallablePreparedOrAtomicExecuteTask.call(Unknown Source)"
"com.amazon.redshift.dataengine.CallablePreparedOrAtomicExecuteTask.call(Unknown Source)"
"java.base/java.util.concurrent.FutureTask.run(Unknown Source)"
"java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
"java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
nil],
:context :ad-hoc,
:error
"[Amazon](500310) Invalid operation: Invalid preceding regular expression prior to repetition operator. The error occurred while parsing the regular expression: '(?>>>HERE>>><=//)[^/]*'.\nDetails: \n -----------------------------------------------\n error: Invalid preceding regular expression prior to repetition operator. The error occurred while parsing the regular expression: '(?>>>HERE>>><=//)[^/]*'.\n code: 8002\n context: T_regexp_init\n query: 20516080\n location: funcs_expr.cpp:185\n process: query0_249_20516080 [pid=8592]\n -----------------------------------------------;",
:row_count 0,
:running_time 0,
:preprocessed`

**To Reproduce**
1. Go to question builder and select a table
2. Open metabase editor on table
3. create custom column with `regexextract([Page], "(?<=\/\/)[^\/]*")`
4. Save column
5. reopen column and observe `regexextract([Page], "(?<=//)[^/]*")`

**Expected behavior**
Column retains saved regex rule with escape characters: `regexextract([Page], "(?<=\/\/)[^\/]*")`

**Screenshots**
- Before Saving Column Screenshot: ![before](https://user-images.githubusercontent.com/22222426/105778036-5daad100-5f20-11eb-80f7-afc9a9bb1dee.png)
- After Saving Column and re-opening screenshot:  ![after](https://user-images.githubusercontent.com/22222426/105778082-74e9be80-5f20-11eb-8405-ee9663156bb2.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your operating system:OSx
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Database: Redshift
- Metabase Version: 0.36.4
- Browser: Chrome latest
- Metabase internal database: H2

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.
- This is blocking our ability to successfully use regexextract to extract a value from a column (in this case hostname) which is impeding our ability to aggregate on hostname. A solution would be to solve this in ETL but this could be more easily done here in metabase.
- This is resulting in query failure in redshift as you can see with the attached logs.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #13306

**Comment by jeff303** [comment]
To provide some background here, the issue is that the parser we use (Babel) is parsing that as a string literal.  In general (not just for Babel but in most programming languages), a single backslash isn't a valid character on its own.  It's an escape character for something else.  So a literal backslash would need to be written as `\\` (i.e. an escaped backslash).

Now, the difficulty is we have two layers here:

1. The frontend expression string parsing (i.e. Babel)
2. The regular expression itself

For layer 2, regular expressions _themselves_ need an escape character in certain circumstances (such as the one from the original comment).  So we need to express a literal backslash to the regex, but in order to express _that_ via the frotnend, it actually needs to be written as `\\`.

1. Input has `\\/`
2. JS parser interprets `\\` as `\/` (i.e. a backslash, followed by a forward slash)
3. Regex (later, on the server or DB itself) interprets `\/` as `/` (forward slash)

So the temporary workaround here is to always use `\\` in the input (try it now; it should be persisted correctly).  If we want to do something clever by automatically escaping backslashes, we will need to be extremely careful since it's easy to break the semantics of the expression unintentionally.  But in the immediate term, that is the correct way to do this.

@ariya , is it feasible to extend the approach you used for #15775 to detect this situation?

**Comment by ubunatic** [comment]
Hey, nice that you are working on a fix! With merged code, can I now write things such as the following:
```
regexextract([Prop], "\"key\":\\s*\"([^\"]*)\"")
```
Without getting my expressions escaped again everytime I focus and defocus?

**Comment by flamber** [comment]
Yes, from 0.43.0
![image](https://user-images.githubusercontent.com/1447303/160112869-f5c92e18-b101-4c40-a5d1-49c4d6390cab.png)
