### ISSUE TITLE
Use CMD instead of ENTRYPOINT to start metabase via docker

### ISSUE THREAD

**Issue by chrispruitt** [metabase/metabase#14528]
**Is your feature request related to a problem? Please describe.**
I would like to pull ENV variables each time Metabase starts. I would like to do this by calling a script via the ENTRYPOINT command in a Dockerfile that uses Metabase as the base image. 

**Describe the solution you'd like**
Currently, Metabase uses the ENTRYPOINT command to call `run_metabase.sh`. If the Metabase Dockerfile called `run_metabase.sh` with the CMD command, then it would be more convenient to add a custom ENTRYPOINT script to a custom Dockerfile without having to worry about what startup command to call.

**Describe alternatives you've considered**
Currently, I am overriding the base image ENTRYPOINT and then calling the `run_metabase.sh` script using the CMD command. This works, but if the startup flow of Metabase ever changes then it would be slightly more involved to update the Metabase base image since you would then have to update the startup command as well.

This works currently.
```docker
FROM metabase/metabase:v0.37.7

COPY docker-entrypoint.sh .

# Override metabase base image entrypoint with custom script
ENTRYPOINT [ "./docker-entrypoint.sh" ]

# Start metabase
CMD ["/app/run_metabase.sh"]
```

If this gets implemented then the custom Dockerfile could look like this and you wouldn't have to worry about breaking changes on the start-up command if you needed to update the Metabase base image.
```docker
FROM metabase/metabase:v0.37.7

COPY docker-entrypoint.sh .

# Override metabase base image entrypoint with custom script
ENTRYPOINT [ "./docker-entrypoint.sh" ]

# given the docker-entrypoint.sh script calls `exec "$@"`
```

**How important is this feature to you?**
It's a nice-to-have and I assume others would benefit as well. Basically, you would not have to worry about managing the startup command.

**Comment by Onlinehead** [comment]
As for me, the proposed solution makes things more complex and unobvious then they are now.
We have a working assumption that we have an entrypoint which run a `run_metabase.sh` script which launch Metabase. That is simple, clean and difficult to break, because it is very easy to pass an incorrect CMD to the container, but to break an entrypoint user should at least know how to define it.
If we will move it to the CMD and add kind a "universal runner of CMD" as an `ENTRYPOINT` - that will mean we assume that the universal runner will actually run everything you will push as a `CMD` and `CMD` will contains a `run_metabase.sh` in the end.
It doesn't solve the potential issue "if the startup flow of Metabase ever changes", because in that case both `ENTRYPOINT` and `CMD` can be changed, same as the name and path of the `run_metabase.sh` script, so to build a custom image over it user should know what to run to actually launch a Metabase and user should worry about it anyway, so no simplification here. Also, we can expect that if user want to modify a startup flow of the container he also have enough knowledge to check and care about an original startup flow to make sure the new, changed one, will not break anything.

P.S. 
In general - it is not mandatory build a custom image to change the `ENTRYPOINT` or `CMD`. It can be done by passing additional flags to a containers engine. 
Moreover, most of the modern orchestration platforms (like Kubernetes) which are widely used by many users allow to on-flight add custom files to the docker image before start together with `ENTRYPOINT` or `CMD` overriding .
