### ISSUE TITLE
Seriously we need to stop creating & destroying temporary databases for every single QP test

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1458]
The original reason for doing this is so we wouldn't get a ton of random DBs/Tables coming back from our API endpoints. which would have made those tests harder to write. This wasn't an issue when all DBs were local and creating/destroying/syncing them took 100ms each. But now that we're testing against remote DBs like SQL Server (which takes 1 - 10 seconds to do the same process) we need to stop wasting time or our tests will take an unacceptably long time.

Fix: Create the DBs on test launch with a function marked as `{:expectations-run :before}` and destroy them when the tests finish with a function marked as `{:expectations-run :after}`. Rework the API tests in question. Save dozens of seconds. :yum:

**Comment by snarfed** [comment]
oh man i feel your pain!

**Comment by agilliland** [comment]
+1

One qualification though, which is that I think this makes a ton of sense for static test data that is read-only and is just being loaded on 3rd party dbs we are testing against, but for our local MB application database I'd actually like to implement something like we have for these test datasets and purge/reset the MB database for each unit test so that no unit test can affect the data in a way that messes with any other unit test.  We don't do that right now and it actually drives me crazy when trying to create unit tests.
