### ISSUE TITLE
Long Running Pulses will block other pulses from running

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#14613]
**Describe the bug**
There seems to be a blocking problem when a long running pulse on an issue prevents subsequent pulses from running and being sent. 

**Related Symptom Issues**
This is believed to be the root cause for [TBF]

**Comment by paoliniluis** [comment]
Could be related to:
https://github.com/metabase/metabase/issues/4398
https://github.com/metabase/metabase/issues/10088

**Comment by brunobergher** [comment]
Reducing this to P2 since it doesn't seem it's happened again.

**Comment by flamber** [comment]
Because pulses are being executed one after another, because only a single thread is available, then a single pulse in the beginning can block other all other pulses for a long time. This can be caused by a slow query or full pool.
Adding another thread could be a solution, but it would also cause more queries being executed at the same time.
![image](https://user-images.githubusercontent.com/1447303/139701898-cba9bdb6-5bdc-44cd-9cde-cf5048c2121b.png)

**Comment by qnkhuat** [comment]
Pulses are now being sent in parallel as of https://github.com/metabase/metabase/pull/41772, this problem should now be mitigated.
