### ISSUE TITLE
Shrunken bubbles shown in question for null values

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#14662]
**Describe the bug**

Visual bubbles are shown around null values in question table visualization.

**Logs**
N/A

**To Reproduce**
1. Create a Redshift table and populate it as outlined [here](https://github.com/metabase/metabase/issues/8510#issuecomment-773499858)
2. Sync the database, then update the data model as outlined in that same comment
3. Create a new question, and select this table
4. Table view should be the default, and we can see the "empty" shrunken bubbles for the first two rows

<img width="198" alt="Screen Shot 2021-02-04 at 12 00 16 PM" src="https://user-images.githubusercontent.com/3521562/106935733-5c786180-66e1-11eb-8c1b-bc05f61888aa.png">

**Expected behavior**
These bubbles probably shouldn't be rendered (entirely blank cell shown for null value)?

**Screenshots**
Linked above

**Information about your Metabase Installation:**

0.38 (self hosted, local dev build from `master`)

**Severity**
Minor

**Additional context**
N/A

**Comment by flamber** [comment]
It's somewhat similar behavior, when you use remapped FK "Display Values" and there's no reference, but then instead of showing the ID it also just shows an empty bubble.
But there are some drill-through actions which probably should be available even when it's an empty bubble.

Without FK remapping, where the FK table doesn't have a row with ID=4:
![image](https://user-images.githubusercontent.com/1447303/106940387-c6b0f680-6721-11eb-8acd-558ad2dfc24e.png)
With FK remapping:
![image](https://user-images.githubusercontent.com/1447303/106940314-b1d46300-6721-11eb-9cf6-0e9f06b197e6.png)

**Comment by paulrosenzweig** [comment]
Closed by #14687
