### ISSUE TITLE
Escape/unicode bug when filtering by a joined table's string column

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#1473]
Steps to reproduce:

1. Select the base table under "DATA" header
2. Add a filter under "FILTEREDE BY" header which uses a string column from a connected table
3. If that string column has only several different values, Metabase will offer them as checkboxes
4. If you check a checkbox that includes a space or a unicode character in its body and click "Add filter", a JS error occurs and nothing happens. The following log appears in the browser console:

> InvalidCharacterError: String contains an invalid character (app.bundle.js:54:0)

PS: That line:col corresponds to the Modernizr library.

**Comment by maliayas** [comment]
Edit: I've installed Metabase as a Docker container.

**Comment by tlrobinson** [comment]
@maliayas What browser are you using? I'm not able to reproduce this in Chrome.

**Comment by maliayas** [comment]
Thanks for testing. I'm using recent versions of Chrome and Firefox as well. I notice another issue which I think may be related to this. When I save a question with a unicode name (e.g. "Müşteri sayısı"), then I can't reach it later from the "Saved questions" menu. It gives an empty body:

![ekran goruntusu 2015 11 21 13_41_36](https://cloud.githubusercontent.com/assets/844008/11318321/f24177dc-9055-11e5-8460-b0695c5f05b3.png)

As I check from the network tab of devtools, data recevies at the browser. But then the error you see above in the console occurs.

Probably both issues are caused by the same reason.

**Comment by tlrobinson** [comment]
That's odd, I'm also unable to reproduce that issue:
<img width="844" alt="screenshot 2015-11-21 11 49 38" src="https://cloud.githubusercontent.com/assets/18193/11320216/04d17484-9046-11e5-9888-5f4d8e56d739.png">

Perhaps it's due to a different operating system or locale setting? What OS are you on?

**Comment by maliayas** [comment]
On host: Windows 8, Firefox 42. My locale is Turkish. Maybe it is a Docker related issue. Looking at the console error, it's like originated from Modernizr library.

If you can't reproduce it, thanks anyway for helping.

**Comment by agilliland** [comment]
I tried to reproduce this one as well and was unable to get the failure stated above.

**Comment by tlrobinson** [comment]
I'm unable to reproduce this on Firefox 42 in Windows 10 with the language set to Turkish and using Docker to deploy. I don't have access to a machine with Windows 8.

@maliayas Do you mind trying to reproduce with your language set to English?

Also what database are you using for Metabase's database (H2 by default unless you configured the MB_DB_* environment variables)

It's also possible it's been fixed since the last release but I can't think of anything that changed that would have fixed it.

**Comment by maliayas** [comment]
It's H2, the default. I'll investigate it further. Thanks very much for putting time on the issue.

**Comment by maliayas** [comment]
With the release of 0.13.0, I've created a new container to try it and the bug doesn't occur there. Looks like there was something wrong with my previous installation. So, we can close the bug.

Thanks!
