### ISSUE TITLE
Changing UI language doesn't change personal collection name

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14756]
I set up a new Metabase in Spanish, then changed my language to English. My personal collection is still called "Colección Personal" despite the rest of the UI being in English

**Comment by flamber** [comment]
This happens because the collection is actually created in the table `collection` of the application database with a name based on the language of the instance at creation.
One solution could be to loop through all users, when language is changed - similar to what #11379 did.

If the personal collection was created while the instance was in language1, and the instance is changed to language2, then some parts of Metabase will still show language1-collection-name in some places for that collection.
![image](https://user-images.githubusercontent.com/1447303/108508205-bec58a80-72bb-11eb-9472-349721b2f6c5.png)

**Comment by qnkhuat** [comment]
> One solution could be to loop through all users, when language is changed - similar to what https://github.com/metabase/metabase/pull/11379 did.

This makes sense to me, to be more concrete I think it should happen in 2 scenarios:
1. admin changes instance's language: in this case, we should loop through all users and translate to a preferred language ( account's language if exists, otherwise instance's language)
2. user changes account's language: in this case, we will translate it to the account's language

I also observed that when an account is created: the text `Personal Collection` is translated using admin's language, **not** instance's language. 

That means if the instance's language is English, but the admin's language is French, the created account will have `Personal Collection` translated to French.
I think the correct behavior should be translating it to instance's language (which is English in the above case)
