### ISSUE TITLE
Set more descriptive document titles to make history more useful

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1484]
Currently we never change the document title from "Metabase", resulting in pretty useless history listings like this:

![screenshot 2015-11-16 11 03 25](https://cloud.githubusercontent.com/assets/18193/11191741/c3008cd6-8c51-11e5-82a3-a8b8b7caa6b2.png)

It might be nice to change the title to reflect the state of the application with titles such as:
- Metabase - Home
- Metabase - New Question
- Metabase - New Question (Orders raw data)
- Metabase - New Question (Orders count, grouped by Product Id Rating)
- Metabase - Question - Order count by rating
- Metabase - Dashboard - My Key Metrics
- Metabase - Admin - Settings
- Metabase - Pulses
- Metabase - Pulse - Weekly Key Metrics

etc.

We may or may not want detailed automatically generated descriptions of the query builder state, I'm not sure.

**Comment by tlrobinson** [comment]
Adding keywords for when I inevitably try to search for this in a year: page title, document.title, react-document-title, page name

**Comment by anki-code** [comment]
@tlrobinson @kdoh 

1. I think the format `Metabase - Something` is not so good as `Something - Metabase` because it's not resolve this case:

![image](https://cloud.githubusercontent.com/assets/1708680/22541792/a78a9b5e-e939-11e6-80e9-cac9017b1953.png)

What will I see in this case in the format `Metabase - Something` ? Nothing. I'll get "Metabase Metabase Metabase".

2. Also I have a suggestion: show `MyCompany - Metabase` title on the main page of Metabase:
![image](https://cloud.githubusercontent.com/assets/1708680/22541873/137d3470-e93a-11e6-97f0-ad21a9e4c1e6.png)

**I think the best result is:** 🏆 
![image](https://cloud.githubusercontent.com/assets/1708680/22541935/78bef148-e93a-11e6-8401-06293d6141a2.png)

**Comment by tlrobinson** [comment]
@anki-code Yeah, you're right, it looks like it's pretty standard to have the site name at the end (Google, Twitter, etc).

**Comment by anki-code** [comment]
@salsakran I'm reviewing RC and have a question: will this issue be in 0.23?

**Comment by frankhokevinho** [comment]
Just go into the file **routes.jsx** into to the frontend folder, find title (**Crtl + F**), and you will be able to customize.
