### ISSUE TITLE
Dashboard filters unlinked when upgrading to v0.38

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#14953]
**Describe the bug**
When upgrading Metabase from v0.33.6 to v0.38.0, many dashboard filters got unlinked from their card parameters.
From what I can see, this seems to be all filters linked to a column from a joined table.

**To Reproduce**
1. Spin up a instance of Metabase v0.33.6 (a more recent version might work, I didn't check, see below)
2. Create a question with a joined table, e.g. count of rows from Orders Join People on UserId = Id
3. Add the question to a dashboard
4. Add a ID dashboard filter linked to People.id (must be a column of joined table, not the first one)
5. Add a Category dashboard filter linked to People.state
6. Upgrade to v0.38.0
7. Open the dashboard and use the filter: they still work
8. Click on edit dashboard, and click on each filter: they appear as unlinked to the question!
9. Click on save or cancel, with or without editing the dashboard: the filters still work

In other words, it seems to be only a display issue, the filters show as unlinked even though they are linked and work as expected. It's still scary and makes me dubious about upgrading our production instance to v0.38.0

**Logs**
This is the JS log when displaying the dashboard: [metabase-display.log](https://github.com/metabase/metabase/files/6037386/metabase-display.log)
Nothing is added to the console when I click the edit button and the settings button of a dashboard filter

**Expected behavior**
The filters should show as linked to the columns / parameters they were originally linked to

**Information about your Metabase Installation:**

I am describing this problem as migrating from 33.6 to 38 because that's my current use case (we couldn't upgrade earlier because of a bug that was a blocker for us and got fixed in v0.38), but I imagine it's linked to a specific version in between that I didn't try to identify.

**Severity**
It *seems* to be merely annoying, but I would appreciate an investigation and understanding of the problem to confirm I can ignore it.

**Comment by flamber** [comment]
Hi @rthouvenin 

This was part of a larger nested queries rewrite in 0.38.0, which fixed a lot of problem with queries, but we didn't handle converting the old field-literal format on dashboard filters to the new field reference, which is why it shows as not selected, but if you look at the metadata, you'll see the filter is there. You can manually set the correct column again, when editing the dashboard and then it will be updated to the new non-literal style.
For reference #14810

Giving P2, since depending on how many cards are with the old reference, then this can become a very big task and confusing.

**Comment by rthouvenin** [comment]
Thanks! Personally we don't feel the urge of "fixing" them all, knowing that they continue to work, we'll just fix them as we see them when updating dashboard (I can easily inform the few people that update dashboards about the possible confusion)
