### ISSUE TITLE
Clicking column title in rows visualization runs query with incomplete clauses

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1503]
##### Run a bare rows query:

![screen shot 2015-11-18 at 1 47 39 pm](https://cloud.githubusercontent.com/assets/1455846/11255434/10027ba2-8dfb-11e5-87d3-af3f64e516d3.png)

##### Now select a different aggregation, but don't specify the Field:

![screen shot 2015-11-18 at 1 47 48 pm](https://cloud.githubusercontent.com/assets/1455846/11255449/2162f41c-8dfb-11e5-9bff-413577504d54.png)

The run button doesn't show up! Nice. 

##### But if I click a column title:

![screen shot 2015-11-18 at 1 47 54 pm](https://cloud.githubusercontent.com/assets/1455846/11255461/351fab30-8dfb-11e5-80bc-927134d04ffc.png)
The query runs and includes the incomplete aggregation.

Perhaps instead we could remove the incomplete aggregation when someone clicks a column title.

**Comment by tlrobinson** [comment]
What is the desired behavior here? We have a 'cleanQuery' function that's supposed to remove partially completed pieces of the query, however it's not aware of the previous query (if there was one), so the only sensible thing it can do to the aggregation is set to to `["rows"]`. Are we ok with that?

**Comment by camsaul** [comment]
Why can't it keep a copy of the last valid query? I think it makes sense when you click a column header to use the query that produced it as a starting off point

**Comment by agilliland** [comment]
What about doing it like we do with the filter widget where the clause isn't actually added/set on the query until you've made all the choices?  Part of the underlying issue here is that we are allowing for a state where the query is effectively broken because there is a partially filled out clause.

**Comment by camsaul** [comment]
Another option would be to just pop up an alert saying "please select a field to sum" or something like that.

**Comment by agilliland** [comment]
@kdoh @mazameli , can one of you guys take a look at this one in the next few days?  We are effectively blocked on this one due to a UX issue.

For me the primary issue is that when a clause in a query requires multiple selections we really need to make that happen atomically, otherwise we create a situation where the query can be broken because the user made a half-choice.

**Comment by kdoh** [comment]
@mazameli Since you're in the query builder headspace right now do you want to tackle this?
