### ISSUE TITLE
Error saving metric in data reference

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15127]
![image](https://user-images.githubusercontent.com/691495/110715295-f21c7a80-81d2-11eb-83a1-4a7bdbded0e9.png)

Repro steps:
1. Create a metric in the admin panel.
2. Visit that metric in the data reference and click "Edit".
3. Change some text and save the metric.
4. See error message:
> Cannot read property 'metric_important_fields' of undefined

**Comment by kulyk** [comment]
Hi @paulrosenzweig,

After some research, it seems the frontend tries to interact with a functionality removed from the backend

This issue and #15130 are related to Metric's `important_fields` property. Metric's `api/metrics/:id/important_fields` clearly says it's used for the Getting Started Guide feature (see the [route's comment](https://github.com/metabase/metabase/blob/c2d532575cab803f2583e906faac8eca46d91eb8/src/metabase/api/metric.clj#L115)). But it looks like the Getting Started Guide feature has been removed in Metabase 0.30 (see the [doc](https://github.com/metabase/metabase/blob/2a0683bc3dcf1b3e11e41d073c84bac71b3ddce5/docs/administration-guide/11-getting-started-guide.md)) in favor of dashoards & questions pinning.

Also, the direct reason of the problem is the `guide` object, which has to contain the `metric_important_fields` property, but the `guide` is undefined. The `guide` is retrieved with the `GET /api/getting_started` request, but this route has been removed on the backend almost 3 years ago (see the [PR](https://github.com/metabase/metabase/pull/8162)). This is probably related to the Getting Started Guide feature removal.

Please let me know whether my assumptions here are correct. If so, it looks like the page or just a part of it should probably be revisited

**Comment by paulrosenzweig** [comment]
Fixed by @kulyk in #15209.
