### ISSUE TITLE
fingerprint-fields fails due to non-existing field

### ISSUE THREAD

**Issue by etoulas** [metabase/metabase#15144]
**Describe the bug**

The Metabase logs show below error for two of our tables. Both don't have the `product_id` field and those tables weren't touched for a long time (likely years).

The tables in question look like this:

```
=> \d product_group
                                      Table "public.product_group"
   Column    |          Type          | Collation | Nullable |                  Default
-------------+------------------------+-----------+----------+-------------------------------------------
 id          | integer                |           | not null | nextval('product_group_id_seq'::regclass)
 name        | character varying(255) |           |          |
 supplier_id | integer                |           | not null |
Indexes:
    "product_group_pk" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "product_group_supplier_id_fk" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE
Referenced by:
    TABLE "product2group" CONSTRAINT "product2group_product_group_id_fk" FOREIGN KEY (group_id) REFERENCES product_group(id) ON DELETE CASCADE
```

The other table is similarly unsuspicious regarding the `product_id` field. I can provide the definition on request if it helps.

**Logs**
```
INFO metabase.sync.analyze fingerprint-fields Analyzed [***************···································]    30% table 226 'public.closed_inventory_list_items'
ERROR metabase.sync.util Error fingerprinting table 335 'public.product_group'
org.postgresql.util.PSQLException: ERROR: column product_group.product_id does not exist
```
(I removed the timestamps at the beginning of the line for brevity.)

**Expected behavior**
Fingerprinting doesn't happen on columns that don't exist.

**Information about your Metabase Installation:**

- Your operating system: Debian
- Your databases: PostgreSQL 11.10
- Metabase version: 0.38.0.1
- Metabase hosting environment: Jar-file
- Metabase internal database: PostgreSQL 11.7

**Severity**
Queries seem to work on those tables. But errors in a log file indicate a problem.

**Additional context**
I field another bug report that might be related, or not #15143

**Comment by flamber** [comment]
Hi @etoulas 
Did `product_id` exist on the table `product_group` at one point? I have a feeling you're seeing this issue: #14817
I have outlined possible workaround in https://github.com/metabase/metabase/issues/15143#issuecomment-797381489

**Comment by etoulas** [comment]
Hi @flamber , as mentioned in the issue description "those tables weren't touched for a long time (likely years)". That was way before we even introduced Metabase.

**Comment by flamber** [comment]
@etoulas Okay, time to dig around in the Metabase application database table - try this, which should return all columns, with that name - there you can see the created timestamp, so when Metabase got the information during a sync:
```
select * from "metabase_field" where "name"='product_id'
```
If you get multiple records - then change if the "active" column is `true` and check if rows might be belonging to different tables.

**Comment by etoulas** [comment]
```
```

**Comment by etoulas** [comment]
Looking at the table in the Data Reference, I realised that there are 2 fields that should be there:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/4390468/110965784-d345f180-8354-11eb-9dd7-ded9de7dc954.png">

**Comment by etoulas** [comment]
Same is true for the other table `product_service`, which contains 2 fields that should be there:

It seems they were added to the sync metadata a long time ago...

```
 id  |         created_at         |          updated_at           |        name        |  base_type   | special_type | active | description | preview_display | position | table_id | parent_id |    display_name    | visibility_type | fk_target_field_id | last_analyzed | points_of_interest | caveats | fingerprint | fingerprint_version | database_type | has_field_values | settings | database_position | custom_position
-----+----------------------------+-------------------------------+--------------------+--------------+--------------+--------+-------------+-----------------+----------+----------+-----------+--------------------+-----------------+--------------------+---------------+--------------------+---------+-------------+---------------------+---------------+------------------+----------+-------------------+-----------------
 625 | 2019-08-27 19:34:43.538+00 | 2021-03-12 16:05:27.483681+00 | product_id         | type/Integer |              | t      |             | t               |        0 |       85 |           | Product ID         | normal          |                    |               |                    |         |             |                   0 | int4          |                  |          |                 0 |               0
 624 | 2019-08-27 19:34:43.538+00 | 2021-03-12 16:05:27.484847+00 | product_service_id | type/Integer |              | t      |             | t               |        1 |       85 |           | Product Service ID | normal          |                    |               |                    |         |             |                   0 | int4          |                  |          |                 1 |               0
```

<img width="900" alt="image" src="https://user-images.githubusercontent.com/4390468/110966513-9e866a00-8355-11eb-95dc-3df7a5c83ecb.png">

**Comment by flamber** [comment]
This is very related to #15143 - most likely a duplicate.

**Comment by dpsutton** [comment]
I've been investigating and I cannot understand how it got into this state and why it isn't getting out of the state.

I added an extra field onto a table

```clojure
(db/insert! Field {:name "should not exist" :table_id 10743
                   :base_type :type/Integer
                   :effective_type :type/Integer
                   :database_type "int4"})
```

And then sync the database:

```clojure
table=> (pprint (sync/sync-database! pg))
...
;; one of the steps
   ["sync-fields"
    {:total-fields 9,
     :updated-fields 1,
     :start-time #t "2021-06-17T18:45:28.336062Z[UTC]",
     :end-time #t "2021-06-17T18:45:28.375650Z[UTC]",
     :log-summary-fn #object[clojure.core$comp$fn__5807 0x63d4661 "clojure.core$comp$fn__5807@63d4661"]}]
```
and see there's an updated field, and in the logs:

> 2021-06-17 18:45:28,336 INFO sync.util :: STARTING: step 'sync-fields' for postgres Database 6 'pg '
2021-06-17 18:45:28,348 INFO fields.sync-instances :: Marking Field 'Table 10,743 'public.product_group' Field 'should not exist'' as inactive.

All of this works correctly because the `fetch-metadata` namespace does its job correctly:

```clojure
(pprint (table-metadata (metabase.models/Database 6) (metabase.models/Table 10743)))
{:name "product_group",
 :schema "public",
 :fields
 #{{:name "id", :database-type "serial", :base-type :type/Integer, :database-position 0, :pk? true}
   {:name "foo", :database-type "text", :base-type :type/Text, :database-position 1}}}
```

The fact that these fields are fingerprinted isn't the real bug here. It's the fact that the fields exist at all. If the application thinks these fields should exist, it will try to fingerprint them, catch the error and move on no biggie.

Can you ensure that the database has been synced?
### Sync in Admin > Databases
![image](https://user-images.githubusercontent.com/6377293/122463114-d3b8de80-cf7a-11eb-926e-8f63af09d318.png)
### Find `step 'sync-fields'` in the logs
![image](https://user-images.githubusercontent.com/6377293/122463139-da475600-cf7a-11eb-84d1-a0ea701c2b1e.png)
### Find the task activity in Admin > Troubleshooting > Tasks
![image](https://user-images.githubusercontent.com/6377293/122463178-e501eb00-cf7a-11eb-90c6-f7cf2114198c.png)
### Get task details for the sync-fields task by clicking view on that row
![image](https://user-images.githubusercontent.com/6377293/122463196-eb906280-cf7a-11eb-99d1-20124c9b4da8.png)

If you can verify that it is running and syncing, then there are two places we could investigate:
1. the code that enumerates the fields in a table is wrong or
2. the code that retires fields because they are no longer in the table is wrong

Getting more information in those two spots could prove a bit more tricky but we can cross that bridge when we get there.

Some potentially puzzling information in the meantime, the two fields on the `product_service` table had updated-at timestamps from the day you filed this issue: `2021-03-12 16:05:27.483681+00`. I'm wondering what got updated and from where. I'm gonna see if i can pull at that thread if you can verify all of the above steps for me, @etoulas

**Comment by camsaul** [comment]
Those columns had to have come from somewhere... there's no way Metabase could have just invented an `int4 product_id` column on its own. @dpsutton I'd lean towards "1. the code that enumerates the fields in a table is wrong". Maybe these Fields are in some other table or view in the database and the sync code is incorrectly reporting them as being in this particular table when they in fact are not

**Comment by dpsutton** [comment]
Totally agree. I was just tackling the problem of why aren't they retired. If we get insight into that perhaps we can figure out why they showed up in the first place. Or it is possible that whatever bug allowed them to be created is no longer present in later versions. But this latter half of the problem seems to currently exist and we can hopefully diagnose it.

**Comment by dpsutton** [comment]
@etoulas are you still having this issue? I'm looking through this code and cannot really identify why this would be happening to you. If you are still having this problem, if you're an admin, if you can create another connection to this database, do you still see these extra fields on these tables?

**Comment by etoulas** [comment]
@dpsutton sorry for the late reply. I don't have access to this Metabase installation anymore, so I cannot support with the troubleshooting. I assume that the issue still exists, I will check if you can get the support needed.

**Comment by etoulas** [comment]
@dpsutton Quick update. I haven't managed to get you the support. As mentioned, I have no access to this Metabase instance anymore. I suggest to close it.
