### ISSUE TITLE
Clicking logout adds ?redirect=%2F to the URL

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15224]
Steps to repro:

1. Log in
2. Upper-right menu > Click logout
3. You are taken to http://localhost:3000/auth/login?redirect=%2F

Log out should not add a `redirect` parameter.  `?redirect=%2F` is a little redundant since that's the default anyway

**Comment by flamber** [comment]
In Firefox on 0.38.2 and `master` - a logout by clicking :gear: > "Sign out" does the following:
1. Changes URL to `/` (via pushState)
2. Sends `DELETE /api/session` (to clear cookie/session)
3. Then goes to `GET /`
4. Then because it's unauthenticated, a redirect to the login page (`/auth/login`) including the page it was redirected from, which was just `/`.

In short; I cannot reproduce. Related to #14436
