### ISSUE TITLE
The order of join-type causes query fail because of incorrect SQL - `inner join` is always placed before other joins

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#15342]
**Describe the bug**
In the query builder, when 3 tables are joined, and the first join is left outer and the second one is inner, the inner join in the resulting query is placed first, which leads to an "unknown column" error on MySQL 5.7.

**To Reproduce**
On sample dataset:
1. Create a new custom question.
2. Select from People, join Orders, join Products:

![image](https://user-images.githubusercontent.com/30152071/112534977-06a06b80-8dac-11eb-907c-a46a4a605c7e.png)

3. View the generated SQL and notice the:

`FROM "PUBLIC"."PEOPLE"
LEFT JOIN "PUBLIC"."ORDERS" "Orders" ON "PUBLIC"."PEOPLE"."ID" = "Orders"."USER_ID" LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "Orders"."PRODUCT_ID" = "Products"."ID"`

4. Change the third table's join to inner:

![image](https://user-images.githubusercontent.com/30152071/112535133-351e4680-8dac-11eb-9f43-6ef397d81902.png)

5. View the generated SQL and notice the:

`FROM "PUBLIC"."PEOPLE" INNER JOIN "PUBLIC"."PRODUCTS" "Products" ON "Orders"."PRODUCT_ID" = "Products"."ID"
LEFT JOIN "PUBLIC"."ORDERS" "Orders" ON "PUBLIC"."PEOPLE"."ID" = "Orders"."USER_ID"`

which is `select from people inner join products left join orders`. As `products` are joined before `orders`, MySQL rejects this with the error `Unknown column '"Orders"."PRODUCT_ID"' in 'on clause'`. This may work on the internal database, and I only see this error on my production instance. But a quick MySQL test indicates this shall be the cause:

`mysql> select * from t t1 join t t2 on t2.id = t_t.t2_id join t_t on t1.id = t1_id;`
`ERROR 1054 (42S22): Unknown column 't_t.t2_id' in 'on clause'`
`mysql> select * from t t1 join t_t on t1.id = t1_id join t t2 on t2.id = t_t.t2_id;`
`(a lot of rows)`

**Expected behavior**
I expect the joins to be made in the order they are added in the query builder.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.19.121-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-17",
      "tag": "v0.38.2",
      "branch": "release-x.38.x",
      "hash": "91f0ed6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
I can work this around with SQL, but seems like an bug to me.

**Additional context**
My production instance where I actually get the error message is 0.37.6.

**Comment by flamber** [comment]
Interesting. This is also a problem on Postgres, and possibly other databases (Redshift, I would guess at least).

It seems like the join-types are ordered alphabetically. If you do a right-join and then left-join, then the SQL will be left-join first.
Similar with full-join, which perhaps internally is called outer-join, since it's always placed at the end.
But from what I can tell, this doesn't change the results and the query doesn't fail either.

**Comment by codingjoe** [comment]
@flamber should we bump this to P1? This seems rather severe considering this breaks a core feature on numerous database backends.

**Comment by pawit-metabase** [comment]
HoneySQL is changing the order of our JOIN clauses as it assumes that the input to `hsql/format` is an unordered map and generates one type of join at a type in the order specified [here](https://github.com/seancorfield/honeysql/blob/9f2fe5e9d46d8bd2a7a5875235e1f7d36e8e18a5/src/honeysql/format.cljc#L240-L244).

(Since we're passing in an ordered map, within each type of join, the ordering is still preserved so this issue only occurs when mixing types of join.)

HoneySQL v2 provides a way around this with the [join-by](https://github.com/seancorfield/honeysql/blob/develop/doc/clause-reference.md#join-by) clause.

@camsaul Any plans/concerns/known-issues for upgrading?

**Comment by camsaul** [comment]
I think we'll want to upgrade to HoneySQL 2 to fix this

**Comment by camsaul** [comment]
This actually works on H2 for some crazy reason, I guess H2 doesn't care about what order the joins are in.

**Comment by camsaul** [comment]
When #28008 is in, I will fix this
