### ISSUE TITLE
Dashboard filters show confusing target columns

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#15438]
## Bug

The target fields for a string contains filter does not show fields in my resultset but actually shows fields on another table. The filters seem to work (it's apparently joining even though this is a simple question on sample dataset's reviews table without any apparent joins).

Steps to reproduce:
1. Ask Simple question, targeting sample dataset and reviews
2. Save question, save to dashboard
3. Note columns in result set: (id, productid, reviewer, rating, body, created at)
4. Intend to create a dashboard filter on review containing some text
5. Edit dashboard, add filter, choose Other Categories, Contains (so we can filter to where review contains "good")
6. UI offers column to filter on, but only lists "Product" Title, Category, and Vendor, none of which are apparently in this dataset.
7. If you do choose Category, and search for where contains "Gi" (prefix of Gizmo) it does filter 1112 results down to 320

### Other Categories
<img width="512" alt="image" src="https://user-images.githubusercontent.com/6377293/113336714-6aff8580-92ec-11eb-80dd-7d2efaab1421.png">

### Contains
<img width="543" alt="image" src="https://user-images.githubusercontent.com/6377293/113336748-76eb4780-92ec-11eb-9f5f-825d357ea18c.png">

### Available columns for filter:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/6377293/113336659-59b67900-92ec-11eb-9309-44c28ced4c53.png">

### Columns available in the result dataset:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/6377293/113337011-cdf11c80-92ec-11eb-941d-ab0db2d8d7b5.png">

**Comment by flamber** [comment]
This also happens on 0.38 (and previous releases), so it's not specific "Contains".

It is correctly showing fields available via the foreign key reference, so that's why you are seeing fields from Products.

And I don't know what your Field Type is for Reviewer and Body, but if it is the default, then it's "No special type" and "Description", and those types are not shown in the filter connector (nor available as [Field Filter](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables)).

Generally this UX could be better - and also in cases where it just says "No valid fields", very little help is provided in-app.

Related to #5781 and #13926 (and a bit to #13186)
