### ISSUE TITLE
BigQuery native query parameters are not bound correctly

### ISSUE THREAD

**Issue by medvedev1088** [metabase/metabase#15487]
**Describe the bug**
When using BigQuery database and a Native Query question with 2 parameters, the value of the 1st parameter is used for the 2nd parameter

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Go to Admin and create a BigQuery database
2. Create a Native query question with the following content:
```
DECLARE param1 STRING DEFAULT {{p1}};
DECLARE param2 STRING DEFAULT {{p2}};


select param1, param2
```

3. Set `a` for the p1 param, `b` for p2 param.
4. Run the query, the result will be a row with `a` and `a`.

**Expected behavior**
The result should contain a row with 2 columns with values: `a` and `b`

**Screenshots**
<img width="1099" alt="Screen Shot 2021-04-06 at 01 36 11" src="https://user-images.githubusercontent.com/930603/113611586-ee1c3500-9678-11eb-8e5e-407ce40d43c4.png">

**Information about your Metabase Installation:**

Metabase for Mac, version 0.38.3.

**Comment by flamber** [comment]
Hi @medvedev1088 
Multi-statement queries are currently not supported in Metabase - #4050

**Comment by medvedev1088** [comment]
@flamber thank you! 

Is there any workaround? All I know is it worked in Metabase 0.34

**Comment by flamber** [comment]
@medvedev1088 That's a very long time ago. It would be very helpful if you could test the latest version in each series to narrow down, when this stopped working.

**Comment by medvedev1088** [comment]
@flamber will try doing it. Another question: are single-statements supposed to work, e.g.:

```
CALL `d5-nansen-prod.dbt_metabase.mb_wpp_all_txs__proc`({{ address_A }}, {{ address_B }});
```

uses address_A for both params.

**Comment by flamber** [comment]
Hmmm.... there seems to be a bug in BigQuery with parameters - and it was a regression sometime between 0.34 and 0.36

**Comment by WadeTsai** [comment]
> @flamber will try doing it. Another question: are single-line statements supposed to work, e.g.:
> 
> ```
> CALL `dataset.my_procedure`({{ address_A }}, {{ address_B }});
> ```
> 
> uses address_A for both params.
in Metabase:
CALL `dataset.my_procedure`({{ A }}, {{ B }});

But BQ actually got:
CALL `dataset.my_procedure`({{ A }}, {{ A }});

Please fix it, thanks a lot.

**Comment by WadeTsai** [comment]
> Hmmm.... there seems to be a bug with BigQuery and parameters - and it was a regression sometime between 0.34 and 0.36
> I can reproduce on 0.39.0-rc1

Could you please let us know in which version the bug might be fixed?

**Comment by flamber** [comment]
@WadeTsai There's 2000+ other issues. There's no timeline for a fix. When the issue is closed, then it will have a milestone.

**Comment by jeff303** [comment]
Trying to reproduce in 40 (nightly version) and unable to.  I can bind multiple parameters for a native query and they evaluate successfully.

<img width="1148" alt="Screen Shot 2021-06-15 at 3 10 40 PM" src="https://user-images.githubusercontent.com/3521562/122116984-e5b84700-cdeb-11eb-9be3-5db4f33bf16c.png">

@flamber , are you able to reproduce this on test or sample data?

**Comment by jeff303** [comment]
I ran out of time to spend on this for today, but I suspect it's a bug in the Google BigQuery API client we're using.  A few observations:

- Only happens with `STRING` params, and not `INT64` (for instance), since the latter is spliced directly into the query by us
- Only happens in multi-statement executions (i.e. contains semicolons).  For instance: `SELECT {{p1}} AS p1, {{p2}} AS p2` works fine (even with `STRING` values), and so does a single `SELECT` statement using multiple params to filter the results (for example).
- I have debugged and confirmed we are setting the parameter values correctly in the Google API layer.

Someone could try updating our dependencies (which requires updating `project.clj` in `bigquery`, and `google`, and likely `googleanalytics`, since the Google dependencies are all interrelated), to see if that solves the issue.  Or, more directly, creating a simple standalone Java application that tries to do this and see what the behavior is.

**Comment by flamber** [comment]
@jeff303 This is seems to be specific to procedures.
I have created a simple procedure on our sample - I also included a function, since that does not cause this problem:
```
CREATE OR REPLACE PROCEDURE v6_sample_dataset.issue_15487_procedure(parm1 STRING, parm2 STRING)
BEGIN
  SELECT concat('PROCEDURE:: ', 'parm1:', parm1, ' - ', 'parm2:', parm2);
END;

CREATE OR REPLACE FUNCTION v6_sample_dataset.issue_15487_function(parm1 STRING, parm2 STRING) as ((
  SELECT concat('FUNCTION:: ', 'parm1:', parm1, ' - ', 'parm2:', parm2)
));
```
Then I just did a query like this:
```
 call `v6_sample_dataset.issue_15487_procedure`({{parm1}}, {{parm2}})

-- select `v6_sample_dataset.issue_15487_function`({{parm1}}, {{parm2}})
```
Which seems to only give the first variable as both parameters to the procedure:
![image](https://user-images.githubusercontent.com/1447303/122682503-11776a80-d1fa-11eb-81a7-6652bdf7b316.png)

----

**Workaround?**
I have found a possible workaround - wrap each variable in sub-select:
```
 call `v6_sample_dataset.issue_15487_procedure`((SELECT {{parm1}}), (SELECT {{parm2}}))
```
![image](https://user-images.githubusercontent.com/1447303/122682576-9febec00-d1fa-11eb-9295-47bb35a8c526.png)

**Comment by jeff303** [comment]
This will be supported in the new BigQuery driver coming in release 41.
