### ISSUE TITLE
Unable to Add MongoDB Database -- java.lang.IllegalArgumentException: No method in multimethod 'can-connect?' for dispatch value: :mongo

### ISSUE THREAD

**Issue by quinn-p-mchugh** [metabase/metabase#15543]
**Describe the bug**
When attempting to connect to a MongoDB database (via connection string or manually specifying fields), the following error is displayed on-screen: "No method in multimethod 'can-connect' for dispatch value: :mongo"
<img width="326" alt="Capture" src="https://user-images.githubusercontent.com/40648753/114205608-796f2200-9928-11eb-994c-d96a08a82130.PNG">

**Logs**
https://pastebin.com/TH9yE97R

**To Reproduce**
1. Go to Metabase main dashboard
2. Click gear ("Settings") --> "Admin"
3. In the setup tab, click "Add a database"
4. Database type: MongoDB
5. Enter connection string or manually specify fields
6. Click the "Save" button

**Expected behavior**
Metabase to successfully connect with my MongoDB database.

**Information about your Metabase Installation:**
https://pastebin.com/ReikrgyE

**Severity**
All the data I'm looking to visualize is stored in MongoDB, so the error is blocking my use of Metabase entirely.

**Comment by flamber** [comment]
Hi @quinn-p-mchugh 

Make sure that you don't have some antivirus that blocking or corrupting the files. Otherwise try the Docker container instead.
Please check the sha256 checksum of `metabase.jar` and `plugins\mongo.metabase-driver.jar`
The checksums should be the following:
`266bc2cf4f209b501d460335bfd71004e83880e85d90121756544cdf30be5c8e metabase.jar`
`9066fe8e8ae2d91ad78ae67204c5c42590ef0b659de8cab5aa9629ba6416f83e mongo.metabase-driver.jar`

I cannot reproduce. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by quinn-p-mchugh** [comment]
Thank you! Will try on my end.
