### ISSUE TITLE
When fullscreen layers are shown (eg Embedding or Alerts), then it's not possible vertical scroll anymore

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#15596]
**Describe the bug**
When fullscreen layers are shown (eg Embedding or Alerts), then it's not possible vertical scroll anymore. Works in 0.38.4

**To Reproduce**
1. Go to a dashboard > click the sharing :arrow_upper_right: arrow > Sharing and embedding - just close the fullscreen
2. Go to any page that normally has vertical scroll - Home or troubleshooting Logs - no scrollbars, and cannot use scroll wheel.
3. Refresh the page, then scroll comes back.

**Information about your Metabase Installation:**
Tested 0.39.0-rc2 and 1, and 0.38.4

**Comment by nemanjaglumac** [comment]
I lost at least 1h trying to find a way to reproduce this in Cypress, but it seems impossible since `cy.window.scrollTo()` forces the scroll. In other words, I can reproduce this locally when I personally use the app, but it seems it is not possible to replicate real user behavior in Cypress.

I'll try some more but if anyone else has an idea, I'm all ears.
