### ISSUE TITLE
Show right versions on enterprise custom builds

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#15677]
**Is your feature request related to a problem? Please describe.**
Currently, whenever someone builds an Enterprise custom version, we show that the version is a 0.X version with Enterprise extensions enabled, where Enterprise should be 1.X version. This is confusing for our customers that build their own uberjar and will also be confusing for the support team.

**Describe the solution you'd like**
Whenever there's an Enterprise build, it should be version 1.X, as we do with releases.

**Describe alternatives you've considered**
None, we currently have to figure out if it's Enterprise or not based on the enterprise extensions being present

**How important is this feature to you?**
Future support people will appreciate this :)

**Additional context**
Didn't want to change it myself, as this has a profound impact in the release process, so the person that does releases should be aware of this change

**Comment by flamber** [comment]
This happens when all tags are fetched (eg `git fetch upstream --tags`), since the official repo might mess with which tag was created last during the official release build process.
Example with "1.38.4" as the release you want:
Workaround is to only get the tag you want in your fork: `git fetch upstream tag v1.38.4 --no-tags`
Or alternatively update the tag before building: `git tag --force --annotate --message='v1.38.4' v1.38.4`

**Comment by camsaul** [comment]
Fixed by #16050
