### ISSUE TITLE
Pivot Table with Conditional Formatting

### ISSUE THREAD

**Issue by gustavotrott** [metabase/metabase#15693]
In table visualization we have **Conditional Formatting** option:

![image](https://user-images.githubusercontent.com/5660191/115390362-886d9400-a1b4-11eb-91e3-de9d8edb60dc.png)

But if if I choose **Pivot table** this options is not available:

![image](https://user-images.githubusercontent.com/5660191/115391079-6f191780-a1b5-11eb-9e9b-c823a546eb27.png)

![image](https://user-images.githubusercontent.com/5660191/115390690-e8fcd100-a1b4-11eb-9265-b50afb821ac5.png)

It would be great to have **Conditional Formatting** in **Pivot Table** because normal tables don't show the **Total** in footer. And I need Total and Formatting at the same time!

Thank you!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nskalis** [comment]
update?

**Comment by exetico** [comment]
Great suggestion!

While doing so kindly secure conditional formatting for all pivoted columns (all at once), so it's possible to give style column 1-3 in a table like this:

| Name | Age | PivotCol1 | PivotCol2 | PivotCol3 |
|------|-----|-----------|-----------|-----------|
| Bob  | 32  | 200       | 300       | 250       |
| Mark | 12  | 100       | 250       | 300       |
| Hans | 32  | 100       | 150       | 100       |

I guess that's what you're asking for, but the example only hold a single pivoted column.

Another thing which I really miss, is a way to add a Conditional formatting for all columns - except "Name" and "Age", instead of selecting all columns (I have a dataset where 10 columns needs to be selected, but only **two** columns where the formatting arn't required).

**Comment by nimuriel** [comment]
Hello,

Is there any advance / update with this feature? It is increadibly usefull when you want to sum up KPIs in one single table and not to depend of extra viz tools.

**Comment by exetico** [comment]
Thank you alxnddr! Great work.
