### ISSUE TITLE
Some places shows `{0}` placeholder instead of expected value

### ISSUE THREAD

**Issue by slaycio** [metabase/metabase#15694]
After upgrade from 0.38.x to 0.39.0 I've noticed problems with filters on dashboards that are stored as a multiple choice.
Instead of number of choosen values system displays placeholder like {0}.

**To Reproduce**
You need to have saved dashboard with multiple default values. (you cannot create new because of bug #15689)
If you have one, than you need to display it... and that's it. 

**Expected behavior**
I'm expecting to see number of choosen default values.
{0} wybranych -> 2 wybranych
bad                 -> expected

**Screenshots**
![bug](https://user-images.githubusercontent.com/2892251/115394729-5de6ff80-a1e3-11eb-96ac-3564cb14b639.jpg)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Edge 88.0.705.50 
- Your operating system: Windows 10 20H2
- Your databases: Oracle 19c
- Metabase version: 0.39.0
- Metabase hosting environment: Redhat Linux. straight from the .jar
- Metabase internal database: Postgres

**Severity**
Looks bad... but i can live with it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Reproduce:
1. Simple question > Sample Dataset > Products - save as "Q1" and add to dashboard
2. On dashboard, add a "Other categories" filter and connect "Q1" and save dashboard
3. (because of #15689) Go to URL `/dashboard/:id?category=Gizmo&category=Widget
![image](https://user-images.githubusercontent.com/1447303/115402314-9b4f8b00-a1eb-11eb-83b7-ce0f75fac5b1.png)
4. Account settings > change language to non-English (or via Admin > Settings > Localization)
5. Go back to the dashboard with the URL as in step 3
![image](https://user-images.githubusercontent.com/1447303/115402542-c89c3900-a1eb-11eb-8bf7-499c98ab1cc4.png)

**Comment by mazameli** [comment]
@camsaul, do you think this is related to that other translation placeholder text bug you fixed last week?

**Comment by alpertungir** [comment]
I translated hundreds of words but we can't use it because of this issue, please help. 

Not only displaying problem. 

![Screenshot_2021-05-03-04-12-05-044_com android chrome](https://user-images.githubusercontent.com/4275327/116834313-25252e00-abc6-11eb-958e-0da353efcef6.jpg)

**Comment by flamber** [comment]
@alpertungir You are not providing enough context. Sounds like a different issue. Please open a new issue with steps-to-reproduce

**Comment by yo-iida** [comment]
@flamber @mazameli 
I have tried to solve this problem, could you please check if it is reasonable?(There are still some problems of CI.)
https://github.com/metabase/metabase/pull/15988
