### ISSUE TITLE
Docs/behavior mismatch for embedding postMessage

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#15732]
When Metabase is embedded, we postMessage to the parent page indicating whether the content needs to have a fixed aspect ratio or stretches to fit its container. Those messages are [documented here](https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html#supported-postmessage-messages-from-embedded-metabase).

[Our code](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/embed.js#L56-L62) currently specifies the opposite behavior described in the docs. "fit" doesn't include a height but "normal" does. I think the code is correct, but before changing either the docs or code someone should verify with an embedded app and check both kinds of pages.

**Comment by tg-incyan** [comment]
Original raiser of the support ticket here,

I disagree that this is only a documentation problem, the point of the message is to describe "height" when it is fixed by Metabase and not the containing frame, i.e. in a Dashboard. The bug here is that the height of dashboard is not being provided by any message. 

Currently Dashboards send a fit message which does not provide a height, providing height in the normal message is useless in this context.

In a "normal" scenario i.e. view question or normal navigation, Metabase can scale to the IFrame height and therefore the height returned by Metabase is always the height of the frame so providing the height in this context is not useful, its already the height of the frame.

In a "fit" scenario i.e. viewing a dashboard, Metabase has a fixed aspect and the containing frame needs to scale to fit and therefore needs the height. However it isn't provided and this is the bug.

I can agree that the concepts could be switched, with a "normal" message and height still being sent but it needs to be sent when viewing a Dashboard. "Fit" can be sent during viewing a question or normal navigation as Metabase is scaling to fit the frame.

**Comment by paulrosenzweig** [comment]
@tg-incyan thank you for chiming in!

The examples are helpful. We trigger fit mode when the root DOM node has our `spread` css class. I guess that means we're taking the aspect ratio of the containing element?

A quick fix would be to pass the height in both cases [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/embed.js#L56-L62). That would prevent any issues if someone is relying on how it's currently passed.
