### ISSUE TITLE
Question is set with Do Nothing click behavior, but it still redirects on click

### ISSUE THREAD

**Issue by morl-la** [metabase/metabase#15898]
**Describe the bug**
I have a dashboard with a few questions. Some questions had on-click behavior.
When I decided to make this dashboard embedded and remove the on-click behavior, I set all click behavior on all questions on the dashboard to "Do Nothing" (by the way - the `Done` button should be enabled when changing to "Do Nothing" as it requires no other params).
Still, when I click on the questions I get redirected, as if the Do Nothing is not saved (or I don't understand how it works)

I even tried attaching the same problematic question to a brand new dashboard, verified the click behavior is Do Nothing, yet it still redirects :|  

**Logs**

**To Reproduce**

**Expected behavior**
When Do Nothing click behavior is chosen, it should ... do nothing on click.

**Screenshots**
![image](https://user-images.githubusercontent.com/44611568/116817128-9b497680-ab6d-11eb-9d0d-e9ad4451ed46.png)

**Information about your Metabase Installation:**
Originally running v0.37.8, I upgraded to v0.39.1 to no avail.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-27",
      "tag": "v0.39.1",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
I changed the on click behavior to a broken URL such that it doesn't redirect to where it shouldn't (i.e a dashboard with editable filters).
To an extend - this is a deal breaker. We should be able to resolve this, maybe not tomorrow, but hopefully soon enough.
Thanks.

**Additional context**

**Comment by flamber** [comment]
Hi @morl-la 
Go to the application database of Metabase, look in the table `report_dashboardcard` and post the column `visualization_settings` for that specific dashboard card, but make a note of the `card_id` column, since I would also need `report_card.visualization_settings` for that specific question.
I have a feeling that you have Click Behavior settings stored in report_card, which shouldn't not happen, but those are causing the strange behavior you're seeing.

**Comment by morl-la** [comment]
@flamber thanks for the quick response. Indeed the `report_card.visualization_settings` contains click behavior.
Is/was there a known bug that can cause this  - as you say - unexpected setup?
I assume I should be removing the click behavior from all records in `report_card`, not just the ones related to my problematic dashboard, right? Any other misplaced config I should be aware of?
Thanks again.

**Comment by flamber** [comment]
@morl-la Wow I'm good - just read the first couple of lines and instantly thought of #13595 - see it for more details.

Basically anything that can be set on the dashboard, can be parsed down to the question under specific conditions, which then can be saved together with the questions visualization_settings even though you cannot change those values on the question - or reset them via the UI, so you're kinda stuck with hardcoded values until you cleanup `report_card.visualization_settings` manually.

But yes, you'll have to manually cleanup `report_card.visualization_settings`, so it doesn't contain stuff that should only exist on dashboards (like question title, click behavior etc), but please make sure that you have a backup of your application database before going down this route, since awful easy to really mess things up. The column has to be valid JSON.
If you have a lot of questions with residue settings, then let me know and I'll try to see if I can come up with a SQL you can run.

So one thing is that we need to fix causing problem, but we also need to cleanup existing "corrupt" data - basically not easy.
Closing in favor of #13595

**Comment by morl-la** [comment]
@flamber doing the data fixing on a postgres DB is rather easy - see https://www.postgresql.org/docs/12/functions-json.html
Here's something to start with
```
--verify the corrected data
WITH keys_you_want_to_remove AS (
    SELECT '{click_behavior}'::text[] keys_to_remove -- you can add more keys to remove here
)
SELECT id, visualization_settings original, (visualization_settings::jsonb -keys_to_remove)::TEXT fixed
FROM report_card, keys_you_want_to_remove
where visualization_settings::jsonb ?|  keys_to_remove

--backup the table
CREATE TABLE report_card_bck AS SELECT * FROM report_card;

--do the actual cleanup
UPDATE report_card 
SET visualization_settings= (visualization_settings::jsonb -keys_to_remove)::TEXT
FROM (
    SELECT '{click_behavior}'::text[] keys_to_remove -- you can add more keys to remove here
) keys_you_want_to_remove
WHERE visualization_settings::jsonb ?|  keys_to_remove;```

**Comment by flamber** [comment]
@morl-la Exactly. I did [something similar](https://gist.github.com/flamber/3212a49ca60cad28ba53272a444d6054) for migration of old Custom Drill-through. It still requires a lot of testing to make sure that we're not deleting keys that are valid.
There's two places in the `visualization_settings` hierarchy that `click_behavior` keys can exists (this depends on the visualization being a table or anything else).
We're using text instead of jsonb, because of lack of support currently (issue 708) and the support of multiple different versions and database types for the application database. But we might be getting to a point, where we can effectively do this.
