### ISSUE TITLE
Clicking the column formatting button when the sidebar is already open should correctly open that column's formatting sidebar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#16043]
Right now if you're already looking at one column's formatting settings, or if you have the visualization settings sidebar open at all, clicking the gear in the popover from a table columns heading doesn't correctly switch to that column's settings: 

https://share.getcloudapp.com/5zuB6Ar6

**Comment by flamber** [comment]
#16368 only fixes, when the Settings sidebar is open (not on a specific column).

----

Scenario 1 (fixed by #16368):
1. Simple question > Sample Dataset > Products
2. Click the Settings in lower-right, then click one of the table column headers (not the sidebar) and :gear: in the popover
![image](https://user-images.githubusercontent.com/1447303/120890477-30271000-c603-11eb-9f5f-8c66ed9d88b1.png)
3. Before #16368, nothing would happen.

----

Scenario 2:
1. Simple question > Sample Dataset > Products
2. Click Category column header > :gear: - it will now show the settings sidebar for Category
3. While leaving sidebar as-is, click Price column header > :gear:
![image](https://user-images.githubusercontent.com/1447303/120890579-015d6980-c604-11eb-8140-99f0f0b68e70.png)
4. Nothing will happen, it will still show Category in sidebar

----

Scenario 3 - perhaps it needs it's own issue P3 UX
1. Simple question > Sample Dataset > Products
2. Click Visualization in lower-right, then click one of the table column headers (not the sidebar) and :gear: in the popover
![image](https://user-images.githubusercontent.com/1447303/120890682-ad06b980-c604-11eb-9e90-735f99593c50.png)
3. Now both Visualization and Settings are selected and clicking any of them will close the sidebar
![image](https://user-images.githubusercontent.com/1447303/120890740-fc4cea00-c604-11eb-981e-021394f6435d.png)
