### ISSUE TITLE
Native question's numeric field filter doesn't have any widget options

### ISSUE THREAD

**Issue by gvwilson** [metabase/metabase#16151]
Using the sample data, construct a SQL query that parameterizes the review rating
![Screen Shot 2021-05-19 at 12 40 57 PM (2)](https://user-images.githubusercontent.com/911566/118851494-d18e3200-b89f-11eb-9a1a-99b88a1a7365.png)

Try to construct a field filter for this - Metabase says "no filter widget type".
![Screen Shot 2021-05-19 at 12 41 32 PM](https://user-images.githubusercontent.com/911566/118851560-e5399880-b89f-11eb-8376-15edc0a5dfa5.png)

But Metabase allows the user to save the question anyway
![Screen Shot 2021-05-19 at 12 41 59 PM](https://user-images.githubusercontent.com/911566/118851607-f2568780-b89f-11eb-99eb-e3af7aca7ed6.png)

And in the dashboard, when adding a filter control, it explicitly mentions `Rating` under "Other Categories"
![Screen Shot 2021-05-19 at 12 42 21 PM](https://user-images.githubusercontent.com/911566/118851666-039f9400-b8a0-11eb-8281-338a0c36fc25.png)

1. Users shouldn't be able to save questions with broken field filters.
2. We shouldn't suggest to users that we can filter by Rating when we can't.

Note: @paoliniluis showed me that we can "fix" this by editing the metadata and chating the `Rating` field's semantic type to `Category`. Metabase can handle that, but the comment in the "What do you want to filter?" pop-up puts "Rating" on the same level as "Category", which is misleading.

Metabase info:

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Toronto"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "vUNKNOWN",
      "date": "2021-05-17",
      "branch": "master",
      "hash": "9700fe5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Think it's time to completely revisit Field Type, since it's confusing how it works. I tend to completely ignore the different options available and set it to Category if I need a dropdown.
And setting a string-based field to Number will not format it as numbers (or cast it as such), but it will then show up in Summarize as metric options, which doesn't work (expect for MySQL, which doesn't care about types for some reason).
Related to #15963 #13926 #11721.

**Comment by ranquild** [comment]
I believe this was already fixed because we don't have this section in the dropdown anymore

**Comment by WiNloSt** [comment]
There were 2 problems with this issue.
1. Metabase shows **There aren't any filter widgets for this type of field yet.** when a field filter is mapped to product -> rating.
2. Metabase shouldn't suggest that some filters are available e.g. Rating in this case

For 1) I am not able to reproduce this on 0.44.0. Following the steps literally, the *Field widget type* will always default to *Equal to* widget.
![image](https://github.com/metabase/metabase/assets/1937582/32993f54-e2ff-404f-8463-530b0f4e1c5e)

For 2) it sounds more like a feature request, but the way dashboard filters work is that we can add as many filters as we want to a dashboard even without having any card yet. I could imagine it'd be limiting to only show applicable filters for added cards because that means we're forcing users to always add cards before adding dashboard filters. I don't think we need to make any change about that.

**Comment by WiNloSt** [comment]
I set the milestone to 0.44 since I couldn't reproduce on that version. The issue was likely fix before that version though.
