### ISSUE TITLE
Field Filter's Default Value Not Working on Dashboard with UNIX timestamp

### ISSUE THREAD

**Issue by LFED-FP** [metabase/metabase#16177]
**Describe the bug**
I have set a Dashboard level Relative Date filter wired to my tiles Timestamp data. A week or so ago, when I would land on my dashboard page my default Relative Date would append itself to my url. 

For example, if I type into my browser https://example.net/dashboard/30
The landing page would result in https://example.net/dashboard/30?day=yesterday

My default value would populate into all my tiles and I would see data just from yesterday. Now what happens is that I am getting a NaN on my Relative Date filter when I land on my dashboard page https://example.net/dashboard/30. 

Even when I specifically go to page https://example.net/dashboard/30?day=yesterday, the query string falls off and my Relative Date value automatically sets itself to NaN

Browser: Chrome 89
Operating system: macOS Catalina v10.15
Database: Mysql
Metabase version: v0.39.1
Metabase hosting environment: Docker

**Logs**
I do not have admin privileges

**Expected behavior**
When I land on my landing page; https://example.net/dashboard/30, default values on the dashboard should append themselves to the url and my tiles should filter based upon them

**Screenshots**
Showing that Relative Time default is set and wired to my tiles
![Screen Shot 2021-05-20 at 4 53 41 PM](https://user-images.githubusercontent.com/71031214/119062772-666e5980-b98c-11eb-8dc7-79fcbcb36691.png)

When I land on my landing page my Relative Time defaults to NaN???
![Screen Shot 2021-05-20 at 4 57 27 PM](https://user-images.githubusercontent.com/71031214/119062841-8e5dbd00-b98c-11eb-9aeb-31bb96d5ac01.png)

**Information about your Metabase Installation:**
I do not have admin privileges 

**Severity**
Very annoying

**Comment by flamber** [comment]
Regression since 0.39.0, where `special_type="type/UNIXTimestampSeconds"` was changed to `semantic_type=null, coercion_strategy="Coercion/UNIXSeconds->DateTime"`

Workaround is to define Field Type in Admin > Data Model for fields that are Unix Timestamps. The Field Type can be any of the timestamps, like "Creation timestamp".

After upgrade to 0.39.0 with Field Type changed to "No semantic type":
![image](https://user-images.githubusercontent.com/1447303/120099441-c22ea480-c13b-11eb-9da0-8f0f453d0a39.png)

Manually setting Field Type to "Creation timestamp", while still leaving the casting to "UNIXSeconds->DateTime" fixes it:
![image](https://user-images.githubusercontent.com/1447303/120099521-29e4ef80-c13c-11eb-9d32-271548bf18cc.png)

**Comment by LFED-FP** [comment]
That did it @flamber, thanks for the info! Cheers
