### ISSUE TITLE
Schemas with all tables hidden shows in Browse Data

### ISSUE THREAD

**Issue by Caroline-Jeangeorges** [metabase/metabase#16282]
**Describe the bug**
When exploring available data in the browse data section, schemas configured as hidden appear in the list. When we click on one of those schemas we get a not found error.

**To Reproduce**
1. Click on browse data, on the top right corner of the landing page. 
2. Click on a database.
3. Click on a schema that is configured as hidden.
4. A not found message appear.

**Expected behavior**
Not having the hidden schemas in the list displayed in the browse data. 

**Screenshots**
The not found message that appears when clicking on a hidden schema:
![image](https://user-images.githubusercontent.com/35225250/120005403-1587e200-bfd8-11eb-87db-086d3978ac95.png)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.14.231-173.360.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Because of how Metabase has stored information about schema, and how it currently read information via requests on the Browse Data, it's not possible to hide the schema in the Browse Data.

It will be hidden in data selector, when creating new questions, since tables (returns none) are known there.
If you revoke privileges to the schema, then Metabase will not see it and hide it complete on next sync.

Not sure if this should could be handled with a slightly modified request or if it needs a structural change on `metabase_table`.

Related to #6286 (historic #2086)

**Comment by antoine-lizee** [comment]
I think this is a key aspect of the discoverability for us:
 - We heavily use schema-level visibility to nudge people towards the right data in our warehouse
 - It works well in the query builder (only the whitelisted schemas & table will show)
 - The "browse data" experience is really poor: all the schemas show (which is not good for discoverability of this page), but all the blacklisted schemas show an error page (and it's the majority of our schemas!)

I wished that:
 - Either the "browse data" page had the same whitelisting and didn't show broken / empty schemas (we have ~3 bug report per week because of it)
 - Either we make it possible that "browse data" shows **all the tables all the time**. That way we have a way to nudge to the good data while still allowing people to browse everything that is available, using 2 different experience
