### ISSUE TITLE
Google docs like collaboration feature to list users currently viewing the Dashboard and trail history

### ISSUE THREAD

**Issue by ranandlp** [metabase/metabase#16309]
**Is your feature request related to a problem? Please describe.**
Enabling collaboration within Metabase - Dashboards, will be a game changer and it will enable users to see the trail of users who have accessed dashboards and encourage questions / answers to clarify on the Dashboards itself.

A trail history of views / edits will be really helpful in understanding dashboard changes and its impact. 

**Describe the solution you'd like**
Google docs and many other solution provides similar feature to collaborate on documents.

**Describe alternatives you've considered**
As an alternative we have to be on a call or external chat to discuss dashboards outside of Metabase

**How important is this feature to you?**
This is helpful and will increase user adoption of dashboards

**Additional context**
None

**Comment by flamber** [comment]
Hi @ranandlp 

There's currently work being done to add collaboration #16141 - some will be available in OSS, other only in Enterprise Edition.

The Enterprise Edition has Audit: https://www.metabase.com/docs/latest/enterprise-guide/audit.html

All editions has "Revision history" of dashboards (and questions) by clicking the three-dots in top-right of the dashboard.

This is a little broad request, so going to close it. Please open single topic issues, since it's very difficult to address multi-topic issues. Make sure to search for existing issues first.
