### ISSUE TITLE
Field picker widget with only a couple tables/columns is visually confusing

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#1653]
The borders and icons in the field picker help when there are a lot of tables/fields, but when there are only, say, two tables with one column each it's still hard to distinguish the table "sections" from actual fields:

![screenshot 2015-12-08 10 47 35](https://cloud.githubusercontent.com/assets/18193/11664908/33ae35ca-9d99-11e5-92aa-3d3cbdb8e9b5.png)
![screenshot 2015-12-08 10 47 38](https://cloud.githubusercontent.com/assets/18193/11664909/33b1f5fc-9d99-11e5-99f3-ff0baf6e3889.png)

**Comment by mazameli** [comment]
Yeah, I think we might need bolding for tables, and perhaps indentation for fields. Maybe the link icon for linked tables should go on the right of the label, too, so that all tables are flush-left w/ each other. Also, the primary table name should be further left; it looks oddly indented currently.

**Comment by mbvictoria** [comment]
Closing - issue related to an old design.
