### ISSUE TITLE
Add additional statistical functions like median

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1660]
`median` would be extremely useful for financial calculations and the like. We have other fancy aggregations like Stanard Deviation already... This would be fairly easy to implement, at least for Oracle. We can just make it a `feature` so we don't offer it for DBs that don't support it

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
could also add min + max

**Comment by phalgun** [comment]
:+1:

**Comment by MartinArens** [comment]
+1

**Comment by adamthehutt** [comment]
+1

**Comment by agilliland** [comment]
+1  .. just came across a couple scenarios where max() would be really useful

**Comment by camsaul** [comment]
@agilliland Can't you just order by that field and limit it to 1

**Comment by camsaul** [comment]
But anyways as @salsakran would say, `+1000`

**Comment by agilliland** [comment]
@camsaul yeah, if you are just trying to find a single value that definitely works.  if you apply a grouping then you need the aggregation function though.  e.g. if i want the most expensive order fulfilled each day

**Comment by tlrobinson** [comment]
In particular with the new multiseries stuff you could overlay min/max/avg (though it would be nice to be able to pick your own colors)

**Comment by salsakran** [comment]
@agilliland  + @tlrobinson  will this need any front end design?

**Comment by camsaul** [comment]
It's just an aggregation type so I was thinking just stick them in the advanced options with cumulative sum

**Comment by tlrobinson** [comment]
@salsakran Not if we just want them to show up just like the existing aggregations.

Here:

https://github.com/metabase/metabase/blob/a3de9899c81aeb73ac35f490e4c1d72ad08eaad3/frontend/src/lib/schema_metadata.js#L339
https://github.com/metabase/metabase/blob/a3de9899c81aeb73ac35f490e4c1d72ad08eaad3/frontend/src/lib/query.js#L511

(We should actually consolidate those so there's just one place we need to change)

Also at some point when we switched the aggregation widget we lost the "advanced" distinction. We might want to add that back in if we add a lot more options.

**Comment by camsaul** [comment]
So unfortunately it looks like Oracle is the only DB that we [potentially will] support that ships median aggregations out of the box. We can revisit exposing that if/when we ship our Oracle driver. 

Luckily however `min` and `max` are supported by everybody and are enabled in PR #2171

**Comment by grzaks** [comment]
@camsaul it's possible to calculate median in PostgreSQL like this:
`select percentile_cont(.50) within group (order by value) as value_median from table`

Would you consider adding median, and percentile to aggregation types?

**Comment by doodlebro** [comment]
How about support for median in redshift? Has been around awhile.

**Comment by camsaul** [comment]
Hi @grzaks/@doodlebro, if you have a sense of what needs to be done to support this and some basic familiarity with Clojure, we'd love to have you as a contributor and would welcome a PR to support this 👍

**Comment by camsaul** [comment]
Reöpening this since there's a few databases that support things like `median` so we can consider enabling it for those databases at some point in the future

**Comment by yejianye** [comment]
I implemented median for Postgres, Redshift and SQL Server. Here is the PR
https://github.com/metabase/metabase/pull/7234

**Comment by philip-n** [comment]
+1

I like to use min/max/median/avg to get an initial "feel" for data distribution, allowing to write more specific queries later on. Thanks to @yejianye for providing a pull request, I'd be happy if this functionality could be integrated!

**Comment by eladeyal-intel** [comment]
median is super useful

**Comment by mazameli** [comment]
These would make a ton of sense to add to our custom aggregation expression editor, e.g. let me type `Median(Cost)`.

**Comment by soltanianalytics** [comment]
I'd like to point out that this is still a super relevant issue... Median ist a basic function that is very much lacking in Metabase. It's a bit shocking to find out that its lacking, in fact. Otherwise, Metabase has pretty much all that's required.

**Comment by camsaul** [comment]
PR #7234 implemented `median` for a few databases using our old driver architecture, and would be good to use as a reference for anyone who wants to try to implement it in the future

**Comment by develar** [comment]
Metabase is awesome. I use it to analyze performance metrics that stored in ClickHouse. But if you want to use any advanced of [aggregated function](https://clickhouse.yandex/docs/en/query_language/agg_functions/reference/) , you are forced to use native SQL queries. But the whole things in Metabase are so polished and integrated...

I managed to add median function and build my own docker image. Works very well and I very impressed by Metabase. So, I want to contribute back.


Main problem is that Metabase implemented in an esoteric language, so, not possible to understand code and implement desired functionality in a reasonable time.


Problems:

1. My fork based on 0.33.5.1 — latest timezone refactoring master breaks clickhouse driver (cannot group by datetime field because LocalDateTime is not supported by clickhouse jdbc ("not implemented error")). To fix it, I have to spend 1 full week to be able to read Clojure code. I am not going to fix it, I will wait when @enqueue will fix it :)

2. It is possible to hide unsupported aggregation function using driver feature. I added a new `quantile-aggregations`.

    But code `(defmethod driver/supports? [:clickhouse :quantile-aggregations] [_ _] true)` doesn't work as expected, and because of Clojure, not easy to understand why. As workadound, in `schema_metadata.js` I set `requiredDriverFeature` to `basic-aggregations`. So, `median` will be available not only for clickhouse database. I will sort out when I will prepare PR. 

4. You cannot add a new aggregated functions without changing mbql schema :( See https://github.com/metabase/mbql/blob/a04ced9e4a77a910de2713d32f9e1e8729be3df7/src/metabase/mbql/schema.clj#L523 Otherwise you will get `"[(named (not (some-matching-condition? a-clojure.lang.PersistentVector)) "Must be a valid instance of one of these clauses: :count, :avg, :cum-count, :cum-sum, :distinct, :stddev, :sum, :min, :max, :+, :-, :*, :/, :metric, :share, :count-where, :sum-where")]}}}}"` error. So... I just copied this dependency and fix in-place. MBQL PR: https://github.com/metabase/mbql/pull/24


If anyone want to try, published as docker image `develar/metabase-with-clickhouse`.

Before I will create PR, I want to know — @camsaul  Will you accept PR if it will be implemented in a such way — https://github.com/develar/metabase/commit/bb1031800d2439fbf2bef512a886e009735d750c ?

**Comment by sbelak** [comment]
It seems that median can reasonably -- but messy to varying degree -- be implemented in all the DBs we support.

**Comment by maxmalysh** [comment]
For those looking for a temporary workaround. Here's what we use for median in Postgres:

https://wiki.postgresql.org/wiki/Aggregate_Median 

It will be available only in SQL queries.

**Comment by sbelak** [comment]
We'll also have #12096 merged soon

**Comment by sbelak** [comment]
Implemented in #12096
