### ISSUE TITLE
Confusing UI when adding GeoJSON with no identifiers

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16613]
**Describe the bug**
If you try to add a GeoJSON custom map that doesn't have any identifiers defined, the dropdowns are just empty, but the form doesn't allow you to add the map.

**To Reproduce**
1. Go to Admin -> Settings -> Maps
2. Click on 'Add a map'
3. Add an arbitrary map name
4. Add a URL that points to valid GeoJSON that doesn't contain any identifiers. For example: https://gist.githubusercontent.com/noahmoss/d70c0ba2febad88d39a1ce553084f861/raw/61d1c6fbc00d129dd9a6fdb46c82c9e7659e81d3/gistfile1.txt

**Expected behavior**
Either:
1. We shouldn't allow maps without identifiers, and we should show an informative error when trying to add them
2. We should allow maps without identifiers (not sure what the implication would be for visualization code), and we should improve the UI here -- maybe we only show the dropdowns after you've added a map that has >0 identifiers.

**Information about your Metabase Installation:**

Current master on Firefox 89.0 and macOS Big Sur

**Comment by flamber** [comment]
Since we require the identifier for use on Region maps, then option 1).

But there might be a use-case for option 2) (#12798), where someone could upload a custom map of example indoors area and could populate it with Pin maps, but that would require a larger change of how Pin maps work, which would be a project by itself.
