### ISSUE TITLE
Rework unit tests so we can update expectations (remove uses of expect-let)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1664]
Using `expect-let` is dangerous and was remove from the new version of `expectations`, so rework our half-dozen or so tests that use it.

**Comment by agilliland** [comment]
My IDE counts 49 uses :unamused: 

This feels like it should be done in the context of #1460 where the underlying goal is to have a more robust way to create unit test fixtures which load up a set of data needed for the test which gets blown away at the end of the test itself.  I think that's why we were using `expect-let` in the first place.

If possible I think it would be nice if we were able to use fixtures that involve multiple tests within a single block of test data so that we don't have to recreate data over and over again when realistically the tests are meant to run as a block.

**Comment by camsaul** [comment]
`expect` is just a macro that generates a function with a name bashed on the hash of it's `body`, and with `{:expectation true}` in its metadata. 

So it's easy for us to write macros that load a fixutre:

```clojure
(expect-with-fixture my-fixture
   [5.0]
   (vector-with-avg-rating-on-app-store))
```

or even ones that load a fixture once for several tests:

```clojure
(expect-with-fixture my-fixture
   [5.0]
   (vector-with-avg-rating-on-app-store)

   [100]
   (number-of-upvotes-for-foxpro-98-driver))
```

**Comment by camsaul** [comment]
We're down to 37 uses. These can probably all be refactored out pretty easily if we replace them with `with-temp*` instead.

**Comment by camsaul** [comment]
* I added a new `expect-with-temp` macro a while back which has all the benefits of `with-temp` (tests clean up after themselves) with all of the advantages of `expect-let` (both expected and actual can grab data from the objects that were created)

**Comment by camsaul** [comment]
Down to 20 uses

**Comment by camsaul** [comment]
down to 12 remaining uses after #2891 is merged

**Comment by camsaul** [comment]
down to 10 after #2909 is merged
