### ISSUE TITLE
Cached questions

### ISSUE THREAD

**Issue by caske33** [metabase/metabase#1666]
Is it possible to have "Cached questions" with either the option to run them hourly/daily/weekly like with a pulse or just have a button to rerun them manually. Because we have some heavy queries and we don't want to run them every time somebody looks at our dashboard.

**Comment by agilliland** [comment]
@caske33 I'm curious what you consider a "heavy query"?  how long are those queries taking on average?  and what database are we talking about?

**Comment by caske33** [comment]
For example, we have a query to aggregate some data on our users. This query runs for > 20 seconds. It's ok if this query only runs once every 2 weeks or so.

I guess we could have a cron job that would run this query every two weeks and saves it in the database, but it would be nice if metabase would be able to do this.

**Comment by kotso** [comment]
I have queries running more then 20-30 mins each (doing complex analyzes of transactions for last X days in table with 100M+ records)

**Comment by rafaelveloso** [comment]
Depending on which database system you're using, you can deal with that on the background by using an ETL to recurrently recalculate that query and materialize it. (If you're using Postgres, it allows you to define `materialized views` and refresh them as needed).

**Comment by salsakran** [comment]
Recapping on a slack conversation:
There are two main approaches we're thinking of:
1. using Clojure memoization
2. BringYourOwnBackend where you bring a memcached connection string with you

A rough recap of things to consider 

1. what happens in low memory situations
2. how do we let users know how stale a result is
3. do we let users request a more recent result if the TTL is set silly high
4. eviction policies 
5. are there potential race conditions
6. what happens if memcache* goes down if that’s what we use

As a rough sketch, the functional requirements for this would be:

1. Caching should be opt-in. An admin should explicitly turn it on, and get a warning that this might impact stability
2. It should be straightforward to turn caching on/off
3. There should be a configurable max item size. If someone generates a huge report they download as a CSV, we probably shouldn't cache that
4. There should be a configurable TTL

Open Questions:

* Should caches only be used for dashboards or should running individual questions use them as well?
* Should caches ever be used for pulses?
* What should happen if there is a cached version available but the data warehouse is down?

**Comment by camsaul** [comment]
Redis would be easier to support than memcached I think. It comes shipped with CircleCI so it would be easier to test. Also I've deployed it in prod so I have experience with it, not so much memcached.

**Comment by salsakran** [comment]
@camsaul we could do a prototype branch using memoization and see how it behaves re: the issues raised above.

**Comment by salsakran** [comment]
However, I think it's important to note that for very long queries, this isn't going to be a panacea. If something takes 30 minutes to run, but it's only run once a month, caching doesn't do a whole lot.

In general, pre-computation should probably be handled via ETL jobs, materialized views or something similar. 

This is primarily spec'd to help with the case of dashboards with cards against a slow data warehouse.

**Comment by marwann** [comment]
Hello, any update on this?

**Comment by camsaul** [comment]
@marwann, we're planning on adding this feature at some point in the future, but I don't think we have a concrete date at this point. If this is something you need right away and you have Clojure experience and are feeling adventurous, PRs are welcome!

**Comment by felipegasparini** [comment]
Hey guys!
I'm really interested in this feature and I'm willing to help develop it.

IMO a simple cache using the Metabase's database would work well. The best part of this approach it that it doesn't need any external dependency and configuration.

The way that Redash (check their demo at: https://demo.redash.io/queries/) implemented this feature is a good benchmark, my idea is to develop something similar as a POC and submit a PR in a few weeks to gather some feedback from you.

**Comment by felipegasparini** [comment]
This is a initial version of my : https://github.com/metabase/metabase/pull/3631

In the current state, any new created card will be marked to cache its results for 2 minutes (hard coded value). Whenever you hit refresh in the card or in a dashboard, it will use a cached version if possible. 

I'm using the card-id and the query hash as the "cache key", this is good because there is no need to manually evict old versions of the query and it also caches correctly queries with custom variables. 

Please, let me know if I should keep developing this feature with this approach (i.e. store the cache values in Metabase's db).

**Comment by anki-code** [comment]
+1

I have 10 dashboards with 5-10 cards which show metrics from yesterday and earlier. Why most of charts should be reloaded every visit if we need the data for yesterday and earlier? I have only 2-5 charts with realtime metrics now. For other charts I want to use cache and don't see 10 throbbers every visit.

Also I have a complex sql queries. Theirs execution time is 5-10 seconds but I'm not want to make the load for the database on every dashboard visit from teammate.

**Comment by coderfamily** [comment]
if you add cache, will you give a api to clean cache ?

**Comment by camsaul** [comment]
@coderfamily probably not initially, we're planning on making it configurable within Metabase, and Metabase will handle the rest.

**Comment by derekstavis** [comment]
This is much needed. I have some MongoDB aggregations that take a long time to execute, and when using public dashboards I got a self DoS in database because of multiple people accessing the page at the same time. Caching is much needed and the only core part missing in Metabase for me. Thanks for such a great product!

**Comment by salsakran** [comment]
based on a conversation with @tlrobinson and @camsaul -

We're looking to do the following for 0.24:
- Provide a means of caching queries within Metabase itself
- Provide a way to specify caching backends (in-db, memcache, in-memory, redis, etc)
- Ship one or more backends (probably just in-db)
- Support "automagic" TTL where we'll guess appropriate TTL as per my comments in the above PR
- Allow per-card specification of TTL ?

We'll use this issue to discuss and sort out our approach

**Comment by salsakran** [comment]
closed via #4490

**Comment by sabino** [comment]
@salsakran will you guys add memcache or redis support? any ways to set a custom cache time per question or dashboard?

**Comment by camsaul** [comment]
Hi @sabino, we wrote the caching layer to easily support different backends so that the community could contribute alternatives like Redis or Memcached if they wanted to use it. Instructions for writing a new backend are in the code [here](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middle.ware/cache_backend/interface.clj). If you have some basic familiarity with Clojure (or would like to give it a shot anyway), we'd love to have you as a contributor and would welcome a PR to support additional caching backends 👍

**Comment by sabino** [comment]
Thank you @camsaul 
Will take a look!

btw, the correct url is
https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/cache_backend/interface.clj
