### ISSUE TITLE
Impossible to see the longitude filter (based on binning drill-through) that needs updating 

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16679]
**Describe the bug**
The filter popover for longitude is collapsed and it is impossible to see its contents after a longitude binning drill through.

**Logs**
N/A

**To Reproduce**
1. Open "People" table
2. Click "Summarize" (will open a right sidebar)
3. Open popover with binning options for "Longitude"
4. Choose "Bin every 10 degrees" (or any other specific value)
5. Visualization should render _bars_
6. Click on any of the bars, choose "Zoom in" (to drill through)

![image](https://user-images.githubusercontent.com/31325167/122602467-2a094880-d073-11eb-8357-84e9f098834c.png)

7. The granularity of the longitude will change to 1 degree, filter will show `Longitude -xxx -yyy`
8. Click on that filter
9. Popover appears but only "Update filter" button is visible. The popover itself is collapsed

![image](https://user-images.githubusercontent.com/31325167/122602627-748ac500-d073-11eb-8c78-e6bced5b5e7d.png)

**Expected behavior**
Popover shouldn't be collapsed and it should be easy to see the filter you're trying to update.

**Information about your Metabase Installation:**
local dev, master afae40b63377a361ae20f3d92b7049b9dcf63aec, H2, sample dataset

**Severity**
P3, I guess.

**Comment by flamber** [comment]
It's a P2.5 and a regression since 39, which didn't handle inferred values correctly either, but at least it was easier to change to Custom Expression.
![image](https://user-images.githubusercontent.com/1447303/122671738-65695b80-d1c8-11eb-9092-6eb4a896938a.png)

Likely related to #16658.

We should probably add Between just like what was done in PR 15982. Alternative would be to fall-back to Custom Expression if there isn't a specific option available (though, not all databases supports CE - like Mongo).
