### ISSUE TITLE
Popover footer is displaced when using filter with a search input

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16830]
**Describe the bug**
When using SQL field filter > string the popover footer is displaced. Please see the screenshot.
The same thing happens for dashboards because they use the same component. What's important is that the filter popover has some kind of search input field.

**Logs**
N/A

**To Reproduce**
1. Ask question > Native
2. Enter `SELECT * FROM products where {{ filter }}`
3. In the right sidebar choose Field Filter type and map it to Products.Category
![image](https://user-images.githubusercontent.com/31325167/123962798-200c1180-d9b2-11eb-9f57-7b2f0668b27e.png)
4. For the filter widget type choose anything except `None` or simple `String`. For example, `String contains` will do.
5. Save question
6. Click on the filter widget (left, near the top, by "Sample Dataset" text, and notice the footer is displaced and is flowing outside of the boundaries of the popover.

**Expected behavior**
Popover footer should look like the integral part of the popover.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/123961575-c9ea9e80-d9b0-11eb-8904-6adc578519b7.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
local dev, x.40.0-snapshot, aa78e38494811da129b2c2af5ddc9d3df3d8fe30

**Severity**
UX/UI, but it is a regression.

**Additional context**
This happens for:
- String
    - is not
    - contains
    - does not contain
    -  starts with
    - ends with

- Number*
    - not equal to
    - between
    - greater than or equal to
    - less than or equal to

*Why it doesn't happen for "equal to", although it also uses search?

**Comment by gusaiani** [comment]
> *Why it doesn't happen for "equal to", although it also uses search?

Narrowest "root cause", class `p2` is added to a container only when not isEqualOps, wreaking havoc with the differences of styles of all elements inside (most of which adapt and still look ok).

https://github.com/metabase/metabase/blob/198f5efd6236b6eef03057e99b8e797a5ad07234/frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget.jsx#L157

Systemic root cause, as I see it, is a phenomenal mix of components, styles, conditionals, and drilled props for many things including styles. Trying to serve all possibilities in one go.

To solve this, the path I see is gradually chipping away at the confusion, modularizing and testing things until the really untreatable issues are on the surface like some dinosaur bone. And then we probably rewrite those parts in a focused effort.

**Comment by nemanjaglumac** [comment]
Thank you for the explanation, Gus.
