### ISSUE TITLE
Table header can only show 2 lines

### ISSUE THREAD

**Issue by kurtosis** [metabase/metabase#1685]
I have some long column names and Metabase only shows up to two lines of text in the header cells so I can't read them. Doesn't seem possible to scroll down.

![image](https://cloud.githubusercontent.com/assets/13108483/11824062/649a4f32-a32c-11e5-99f9-29c1f6b7d237.png)

**Comment by agilliland** [comment]
You can actually resize the columns of a table by placing your mouse over the line between columns and clicking/dragging.  So that can hopefully alleviate a little bit of the issue.  Obviously it's a pain to constantly be doing that though.

I can't tell from your screenshot, but is this a table with quite a few columns which is spanning the width of the screen?

**Comment by kurtosis-color** [comment]
Thanks, that helps. Being able to resize row height as well as column width would make it only require one adjustment.

I checked that the issue occurs even for a table that doesn't span the entire window.

**Comment by salsakran** [comment]
this was fixed in our recent port to react-virtualized for tables #3752
