### ISSUE TITLE
After hiding the column and then setting a required default value for SQL field filter (connected to that column) shows all fields as hidden and breaks SQL filters completely

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16914]
**Describe the bug**
It is not possible to set the required + default value for the SQL field filter on the column that was previously marked as hidden. Doing so shows **all** columns as hidden and completely breaks SQL filters functionality because it's not possible to set the filter through the widget or to even change the field that filter is connected to.

**Logs**
N/A

**To Reproduce**
1. Ask new question > Native
2. In the native editor enter `SELECT * FROM products where {{filter}}`
3. In the right sidebar, choose "Field Filter" as a type and connect it to the Products Category
4. Click play icon to run the query - it runs normally and doesn't apply the filter
5. Below the visualization results, choose "Settings"
6. Left sidebar will open, hide `CATEGORY` column, click "Done"
7. Rerun the query - everything still works now (setting the field value through the widget works at this point)
8. Set the filter as required
9. Set the default value to "Gizmo"
10. Rerun the query
11. Results will render "Every field is hidden right now" (but notice it says showing "Showing 51 rows")

After this point, no matter what you do it is not possible to get any results. The only option is to start the new query again.

**Expected behavior**
It should be possible to set the default field filter value even if the connected field is hidden. All other results should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/31325167/124732022-15ea9580-df13-11eb-98a5-fc7ff07bfbc5.png)

**Information about your Metabase Installation:**
local dev, x.40.1-SNAPSHOT, `master`, 8e684e3

**Severity**
Seems pretty severe if you rely on this functionality, but it also seems like a FE issue which makes it a bit less daunting.

**Additional context**
Additional issue: String "Every field is hidden right now" is not translated.

The related code lives in `frontend/src/metabase/visualizations/visualizations/Table.jsx`

**Comment by nemanjaglumac** [comment]
The simple act of hiding one column fires 150 console errors. I had to clear dozens of other errors and warnings before that just to make it more obvious.

https://share.getcloudapp.com/5zuYvgrY

<details>
  <summary> Click to expand and see the full error</summary>

```
react_devtools_backend.js:2560 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
    in TableInteractive (created by TableInteractive)
    in TableInteractive (created by Table)
    in Table (created by Visualization)
    in div (created by Visualization)
    in Visualization (created by Visualization)
    in Visualization (created by VisualizationResult)
    in VisualizationResult (created by QueryVisualization)
    in div (created by QueryVisualization)
    in div (created by QueryVisualization)
    in QueryVisualization (created by View)
    in div (created by DebouncedFrame)
    in div (created by DebouncedFrame)
    in DebouncedFrame (created by DebouncedFrame)
    in DebouncedFrame (created by View)
    in div (created by View)
    in div (created by View)
    in div (created by View)
    in div (created by View)
    in View (created by View)
    in View (created by QueryBuilder)
    in QueryBuilder (created by FitViewport)
    in FitViewport
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by QueryBuilder)
    in QueryBuilder (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
```

</details>

**Comment by flamber** [comment]
Regression since 0.40.0.
I can only trigger this problem if I run the query between step 8 and 9, which shows the error.

**Comment by lukeman** [comment]
Just a heads up that this may not be limited to required fields. I'm not exactly sure what the precise steps have been, but I've gotten into this state on questions where field filters are present but not required. Just now after editing some unrelated SQL in a subquery (the field filter is used there, but was not part of the logic that I changed), I unknowingly triggered it and saved the question, which seems to have gotten it stuck in this error state.

I haven't been able to "undo" this issue and reverting the question isn't available due to schema changes, so if anyone has figured out how to get things working again I'm all ears.

**Comment by lukeman** [comment]
I managed to reproduce this (with a BigQuery connection, Safari, v0.40.0) in a few steps and it seems like a broader issue that isn't just related to field filters. The path to trigger it is a bit different, but it feels like they would share a common cause.

This issue seems to show up any time you've hidden any column (doesn't matter which) with the table settings and a query execution returns an error. When I re-submitted the original query without the errant text, the table.columns attribute of the card's `visualization_settings` in the app state were set to an empty array.

Steps to reproduce:

1. New question > Native
2. In the native editor enter `SELECT 'a' as a, 'b' as b`
3. Click play icon to run the query
4. Below the visualization results, choose "Settings"
5. In the left sidebar hide `a` column and click "Done"
6. Add `foo` to the end of the query and run the query to trigger a SQL error response
7. Remove the errant text from the last step and re-run the original query
8. Results will return but the table renders as "Every field is hidden right now"

**Comment by flamber** [comment]
Changing to P1, since impossible for most users to modify the request to reset viz settings - most would have to recreate the question.

**Comment by nemanjaglumac** [comment]
> I can only trigger this problem if I run the query between step 8 and 9, which shows the error.

Thank you @flamber. And much thanks to @lukeman who reproduced this with even simpler steps and pointed to the root cause of this issue.

It has nothing to do with field filters. Basically, after hiding a column from native results and then triggering ANY kind of error, it is not possible to then recover from that error.
