### ISSUE TITLE
Error when adding a graph question to a pulse

### ISSUE THREAD

**Issue by dudleycarr** [metabase/metabase#1696]
<img width="448" alt="screenshot 2015-12-21 21 54 27" src="https://cloud.githubusercontent.com/assets/218825/11948849/86218912-a82d-11e5-8821-64e4dc3c6e5e.png">

Metabase: v0.13.2
The graph renders just fine on the dashboard. Adding data types that are single values work fine for the provided data set. Adding graphs from the default Orders data set also works. Happy to debug if there are instructions available.

**Comment by tlrobinson** [comment]
Sorry about that. The Pulse rendering code is separate from the dashboard rendering code (since it runs on the server), and it's much newer so we haven't caught all the edge cases yet.

There should be a line in your server logs beginning with `Pulse card render error` that would be a good place to start.

Also a sample of response to the `/api/dataset` HTTP request when viewing the card in the frontend would be helpful (available in the Network section of your browser's Developer Tools/Web Inspector/etc), if you're comfortable sharing that (feel free to email me privately at tom@metabase.com), otherwise any details you can provide about the query and schema.

**Comment by dudleycarr** [comment]
@tlrobinson Thanks for the quick response. Here's the line from the logs:
2015-12-22 06:24:51,483 [WARN ] metabase.pulse :: Pulse card render error:java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number

Will send the `/api/dataset` response via email.

**Comment by tlrobinson** [comment]
@dudleycarr I'm having trouble reproducing this. Is it still occurring for you, and if so which version are you on? What database are you using? Thanks.

**Comment by dudleycarr** [comment]
Upgraded to 0.14.1 and no longer have this problem! Thanks.
