### ISSUE TITLE
Pulse not listing the answers, only the questions.

### ISSUE THREAD

**Issue by caske33** [metabase/metabase#1719]
Sometimes, the pulses don't work. They just report the questions but not the answers. (See image)

![image](https://cloud.githubusercontent.com/assets/896093/12232428/c0f1b38c-b85e-11e5-8ea9-4fa153fa64c1.png)

**Comment by kdoh** [comment]
@caske33 Yeah, unfortunately recent changes to how Slack permissions files means the screenshots of the data aren't able to be displayed in Slack channels currently. We're looking at a fix and we'll update you here when we have a solution. Apologies for the downtime!

In the meantime, if you need regular updates on your data in Metabase email based pulses are unaffected so that could be an interim solution depending on how critical those are for you.

**Comment by caske33** [comment]
Ok!

**Comment by caske33** [comment]
Do you have an estimate of when this will be fixed?

**Comment by agilliland** [comment]
We are working on a fix and plan to have something released shortly.  Unfortunately the Slack team didn't give us any great options for continuing to attach our images to slack posts, so we are considering which work arounds we think are most tolerable.  Thanks for being patient, we know it's frustrating to see empty pulses being posted.

**Comment by agilliland** [comment]
This is done and was released as Metabase 0.13.3 today.  Feel free to grab it @ www.metabase.com/start and everything should be g2g again.

**Comment by caske33** [comment]
I've already deployed the new docker image. Thank you for the fix!
