### ISSUE TITLE
Dashboard causes scrollbars to constantly go on/off depending on viewport size 

### ISSUE THREAD

**Issue by deejayluk** [metabase/metabase#17229]
**Describe the bug**
When I go to settings about subscription, dashoard have problem with size of panels.

**To Reproduce**
1. Go to Dashboards
2. Open dashboard
3. Click on Share -> Subscription

**Expected behavior**
To fix :)

**Screenshots**
![Animation3](https://user-images.githubusercontent.com/73607094/127295322-3f307628-5aaf-4169-b0b4-f5224f7ffa52.gif)

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 92.0.4515.107 
- Your operating system: Windows 10 64bit
- Your databases: MS SQL
- Metabase version: 0.40.1
- Metabase hosting environment: Ubuntu
- Metabase internal database: PostgreSQL

**Comment by flamber** [comment]
Hi @deejayluk 
It's difficult to tell from the description and the looping gif what the problem is, but it looks like that it just readjust the card layout after the sidebar is being opened.

**Comment by deejayluk** [comment]
Look, same thing when the dashboard is bigger than the screen

![Animation4](https://user-images.githubusercontent.com/73607094/127300438-9ac625ee-f18c-451e-8d12-e82b9c9fa6c8.gif)

**Comment by deejayluk** [comment]
but when you create pbulic link and open dashboard from public link everything is okay
I tested on Edge, Chrome and other PC

**Comment by flamber** [comment]
Okay, so this is caused by your browser viewport (window size) is exactly in-between a specific size, where the cards are then switching the scrollbars on/off.

Reproduce:
1. Dashboard with a Textbox, which is 10 cells high and set the browser viewport to 1450x790 (I can only trigger the problem by resizing the window, not by using the responsive devtools, so this might require some slight tweaking to trigger it)
2. It then constantly switches the scroll on/off
![image](https://user-images.githubusercontent.com/1447303/127303633-0ac5e887-29e0-48a2-bdaf-f9597c9077fc.png)

**Comment by deejayluk** [comment]
switching on/off is only when I have 12 grid height (resolution 1920x1080)

![Animation5](https://user-images.githubusercontent.com/73607094/127431998-4a438cdb-72a1-42d2-afb9-06f0c6f30ddc.gif)

**Comment by deejayluk** [comment]
12 grid will be always when we add 4 panels size 3x3 grid :(

**Comment by nemanjaglumac** [comment]
I am able to reproduce this locally but cannot trigger it using Cypress no matter what I do :/

**Comment by ranquild** [comment]
I reproduced the issue and I'm working on a fix.
