### ISSUE TITLE
Frontend shouldn't open new tab for Pulse configure links if client is Mac App

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1728]
When trying to create a pulse before configuring slack or email settings, clicking on the buttons causes a browser window to open instead of going to the page in the mac app.

**Comment by camsaul** [comment]
It opens a new tab in the browser when you're accessing the web app. I think the logic behind that is so you don't lose your place on the create pulse screen?

Since the Mac App doesn't support tabs, we need to change the frontend JS code to *not* open a new tab iff the client is OS X. We don't need to make any changes to the Mac App codebase itself.

**Comment by agilliland** [comment]
I can tackle that real quick.

**Comment by agilliland** [comment]
@camsaul what's the best way to trigger an opening of the users actual browser if that is needed in the mac app?  i'm looking at all cases where we target `_blank` for our links and in a couple cases we are linking out to 3rd party sites, so we'd still want to have those open in a separate browser when the user is on the mac app.

**Comment by camsaul** [comment]
That's exactly what we're doing. You can choose how links with target `_blank` are opened and I coded it a long time ago to just pop open a new browser window. So if we want that behavior we can leave those cases as-is

**Comment by agilliland** [comment]
cool.  then we should be g2g :+1:
