### ISSUE TITLE
Convert custom cursors from SVG to PNG so they work with Mac App

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1729]
The cursor doesn't change to a resize icon when placed on the sides or corners of the card in a dashboard.

Resizing/dragging still works.

**Comment by camsaul** [comment]
After a lot of investigation it looks like the issue here is that SVG cursors aren't supported by Cocoa WebViews for whatever reason. It looks like PNG images work fine however.

![image](https://cloud.githubusercontent.com/assets/1455846/13165013/3648a1e0-d66e-11e5-87ee-90a8c8d7a84a.png)

So I think in this case we should just convert the assets to PNGs instead or just use the built-in cursors like `cursor: move`

**Comment by salsakran** [comment]
@kdoh + @tlrobinson thoughts on this?

**Comment by kdoh** [comment]
Our current custom hovers are a bit oddly sized and obnoxious so I'm down to move to less custom solution like ```cursor:move``` or ```cursor: n-resize``` and not have to have custom resources for that. I will say I'm a bit worried about the Mac App Cocoa Webviews not supporting something like that though. It'd be nice to expect that the rendering of the web views in the mac app maps 1:1 to our other browsers.
