### ISSUE TITLE
CSV/JSON export formatting

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#17422]
Number, currency and datetime format settings should be respected in CSV and JSON exports.

An open question is what subset of format settings would be expected to be applied. Datetime format settings should probably always be applied. Number/currency formatting is a bit more ambiguous, and may depend on the use case.

For example: Metabase always displays thousands separators for numbers on the frontend. JSON doesn't support this without changing the data type from a number to a string. CSV also doesn't support this unless the values are quoted.

This issue replaces #10879 since XLSX formatting will be supported in v41 of Metabase.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by WhyNotHugo** [comment]
While date format seems relevant for CSVs, I think including thing like currency formatting or thousand separators can be problematic. CSV is often processed by automation or different kind of tools that would choke on something like "$1.000"  instead of "1000".

I think it's smart to have started with XSLX, which is what humans would usually work on.

**Comment by gang-qiu-social-chorus** [comment]
i'm experiencing the issue of the exported CSV headers having the database column names, when we want to have the customized formatted name. Is there a hacky way to implement this for our personal use while the issue is in review for the core product?

**Comment by flamber** [comment]
@gang-qiu-social-chorus You would have to use Custom Columns in GUI question or SQL with aliasing.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by colombian-cannonball** [comment]
Hello, is this issue still being worked on? Not having the same column names that appear in a question or dashboard in the downloaded CSV renders reports useless when stakeholders want to export them.

**Comment by devoto13** [comment]
This feature will also be helpful to ensure consistent number formatting in the exported file. Today I have faced an interesting behaviour where in CSV export most of the numbers were in the normal style, but a couple used scientific notation (e.g. `1.584235248E7`) which was not expected by the file consumer.

**Comment by amureki** [comment]
Greetings!

It appears that v49 update has introduced a change that has impacted our user experience somewhat negatively.

Here is an example:
We have an org default in Metabase:
- separator style set to "100 000,00"
- dates style is "31 Jan, 2018"

This is the preferred way for us in all the reports we have in Metabase.
However, we rely heavily on automations that utilize JSON or CSV exports from these reports.
And now, since recent version, the JSON do contain the following:

```
[
  {
    "Created Date": "13 Mar, 2024",
    "Count": "188 857"
  },
...
]
```

I believe, it was different previously.
My suggestion would be to consider adopting a default JSON format that prioritizes raw data. For instance:

```
[
  {
    "Created Date": "13.03.2024",
    "Count": 188857
  },
...
]
```

Alternatively, providing the option to configure JSON export formatting independently of the report formatting could be beneficial, especially since these files are often used in technical implementations where human readability is less of a concern.

**Comment by paoliniluis** [comment]
This issue should be closed, as we shipped this in v49 and now it's impacting everyone who relied on the lack of formatting on their integrations. We're about to build a new endpoint that will export raw data without formatting

**Comment by dmeremyanin** [comment]
Hey @paoliniluis, boolean values are being converted to strings now - for instance, `true` is being converted to `"true"`. This doesn't look like an intentional decision.

It would be super helpful if JSON export formatting can be turned on/off in the settings.
