### ISSUE TITLE
Pin any dashboard to the front page

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#17458]
**Is your feature request related to a problem? Please describe.**
Right now, the Homepage lists the "Pick up where you left off". But some users would like to pin any dashboard, so it is easier for people to find directly after login.

**Describe the solution you'd like**
Allow users to pin any dashboard in the home page, no matter in which collection they are. 

**Describe alternatives you've considered**
Telling each user to go to the dashboards and click the Bookmark, or telling users to ignore the homepage and go to "Our analytics" collection, where the dashboards can be pinned.

**How important is this feature to you?**
Requested by a customer

**Additional context**
We need to check how this entangles with the security structure of Metabase

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jhernandez-stratio** [comment]
This has been requested by multiple customers at our company, since it used to be available. They do not seem to understand what the "pick where you left of" feature is, and they get lost easily. We used to have 5-6 dashboards pinned for them and they have been using that for a couple years. We upgraded to 0.43 and lost that functionality. Is there any workaround to this?

**Comment by paoliniluis** [comment]
@jhernandez-stratio you should upgrade to v45.2.1 which is the most recent version, not old versions which might have security issues. We're planning to move forward with this feature at any point in the near future

**Comment by ignacio-mb** [comment]
Should this issue be closed as completed in 47?
