### ISSUE TITLE
Set # pulses limit to something more generous

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1750]
As per our convo's, let's set this to a more reasonable limit.

Limit should be there to keep people from nuking their instance, not dictating the correct # of cards in a nightly pulse.

**Comment by tlrobinson** [comment]
Need:

1. The new hard limit, if any.
2. Replacement copy for "Pick up to five questions you'd like to send in this pulse"
3. Possibly UI for a warning if you exceed a recommended soft limit?

**Comment by salsakran** [comment]
@kdoh mind chiming in on what you think we should do on those questions?

**Comment by kdoh** [comment]
Yup yup.

1. Any kind of hard limit would be based on needing to do a little research on how long pulses take to send with > N cards and that kind of thing, the main idea being we'd want to make sure that if a pulse was scheduled to show up at noon it doesn't show up at 12:15 because its overloaded. IMO that scenario doesn't seem all that likely right now but its something we want to be cognizant of.

2. "Pick data you'd like to receive on a regular basis." or something similar seems like it'd be the right tone for this. I'm open to improvements and I'll try out some additional copy.

3. I think we'll definitely want to add some sort of message if you overload a pulse with data but I'll need to do a bit of noodling on exactly what triggers it and how best to display it. We should also be aware of how this will affect the pulse list page as well, since we currently list the title of all questions a pulse contains.

**Comment by salsakran** [comment]
It's worth noting that signeasy's raised this limit to 10 in their fork.

**Comment by agilliland** [comment]
My feeling is that somewhere around 25 it gets silly enough that we could clamp down safely.  The UI will be awkward, sending them will be bulky and slowish, and reading them will get pretty lengthy and unfocused.

Putting a warning line at 11 items would be sensible.  Something gentle like "hmmm, this Pulse is getting pretty big.  We recommend having 10 or fewer items in a Pulse if possible."
