### ISSUE TITLE
Too much space between inputs in the Between filter popover

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#17564]
You can see this by filtering on a numeric column via the column heading filter action in Simple mode, or the regular filter popover in Custom/notebook mode. The correct or desired vertical spacing can be seen in the sidebar in Simple mode.

![image](https://user-images.githubusercontent.com/2223916/130522713-b378c255-74cc-4bc5-9587-ee3c40fa8ab7.png)

![image](https://user-images.githubusercontent.com/2223916/130522513-010286bf-628d-47dd-9457-abd7ad20a1f8.png)

**Comment by losrebellos** [comment]
@flamber @mazameli 

Not sure this issue still applies as it seems that since it was created, the UI has changed a fair bit:

- simple mode

![image](https://user-images.githubusercontent.com/348552/164719560-31a40d1f-9581-4be3-a8d5-ce5865a1fdf2.png)

- notebook mode

![image](https://user-images.githubusercontent.com/348552/164719689-b1e69073-d2cc-4ac4-9bac-f39e97cdbd26.png)

**Comment by flamber** [comment]
It was fixed a long time ago - #19365 - in 0.42.0
