### ISSUE TITLE
AWS Elast Beanstalk > Environment property > Reset App Configs

### ISSUE THREAD

**Issue by ruben-veertly** [metabase/metabase#17577]
**Describe the bug**
When adding an Environment property (NGINX_FORCE_SSL) all configurations were lost and the app asked to do the setup again.

**To Reproduce**
1. Go to Configurations in AWS > 'Modify software' 
2. Add a property (NGINX_FORCE_SSL)
3. Save (environment restarts)
4. User is redirected to https://metabase.veertly.com/setup

**Expected behavior**
The current set-up should be kept.

**Information about your Metabase Installation:**
You can get this information by going to Admin -> Troubleshooting.

- Your databases: BigQuery
- Metabase version: 0.40
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
It completely blocks our usage since we're concerned that any change on configuration will result in the same effect.

**Comment by flamber** [comment]
Hi @ruben-veertly 
I have no idea why your configuration was different after adding `NGINX_FORCE_SSL`=`1`
The logs should indicate what might have gone wrong.
I would think that it's because you are not running with a decoupled RDS and have not define the MB_DB_* environment variables.
It is unlikely that we will make any more changes to the Elastic Beanstalk configuration for some time, but we definitely need to document exactly how you should setup the configuration.

**Comment by paoliniluis** [comment]
BTW: Nginx will be removed from future Elastic Beanstalk releases, don't do SSL termination at the server level, use an ALB to do that.

**Comment by ruben-veertly** [comment]
@flamber you were completely right, we were missing the environment variables. It's not clear in the [documentation](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#set-or-change-environment-variables) whether this needs to be done for a coupled RDS. Thanks a lot for unblocking us though!

@paoliniluis, we're keeping that in mind and will make the appropriate changes, appreciate it!
