### ISSUE TITLE
Can't switch back to Query Builder once I'm in SQL mode if I change DBs

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1757]
No way to get back unless I go to "New Question" which means I have to reselect my DB, etc.

**Comment by camsaul** [comment]
Related: #607

**Comment by mazameli** [comment]
One way to do this would be to keep the toggle present after you've started typing in the SQL editor, and just putting the SAVE button to the left of the toggle. If the user toggles back to GUI mode, the SQL that's been written shouldn't have an effect on the query builder. But it would be nice of us to keep the SQL stored in the front end, so that if they toggle out of SQL mode and then toggle back, what they've written is still there. I think we could discard the SQL if they navigate away from the page, though.

**Comment by camsaul** [comment]
This has been implemented by (I think) #2612

**Comment by camsaul** [comment]
Actually I guess there are still some weird things about this. I can't switch back to QB mode if I switch the database at all (even if the SQL box is still empty) 😢

**Comment by salsakran** [comment]
this is fixed as of 0.19.
