### ISSUE TITLE
Base-64 encoded URLs can become multiple kB in raw SQL queries; exceeds size limit when passed as Referer header

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1758]
`2016-01-20 22:11:10,575 [WARN ] org.eclipse.jetty.http.HttpParser :: Header is too large >8192`

**Comment by MartinArens** [comment]
+1

**Comment by camsaul** [comment]
If I understand this correctly when you're talking about "really big" you mean the size of the query text itself, not the results, right? Is this logging just the warning or are there and other issues?

That warning suggests that it's one of the HTTP headers that's too large; queries are passed as part of the request body it seems like something else weird might be going on here. Maybe open the Web Inspector and see if the frontend is making any API calls with really big headers?

FWIW Firefox has a 10KB limit on headers which is in line with the warning you saw.

**Comment by camsaul** [comment]
I did some investigation into this. SQL queries get base-64 encoded into the URL, which gets passed to the backed as the `Referer` header:

![screen shot 2016-01-21 at 12 43 15 pm](https://cloud.githubusercontent.com/assets/1455846/12493959/9776efd2-c03c-11e5-8ae2-7fa283c62ac5.png)

At some point ngnix will even step in and return a 400. Since we don't currently don't use the `Referer` header for anything (and probably never will for API calls) I think the quickest & simplest fix would be just to have to the front-end stop passing it. That would also give us a nice across-the-board API request performance bump, albeit a minor one.

The fact that these base-64 URLs have no size limit is a larger issue. [It looks like most browsers these days are limited to 4-16kB URLs](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) and you can even crash IE 8 by attempting to open a URL over that limit. So it probably makes sense to limit these URLs in some fashion at some point.

**Comment by julianriedelsheimer** [comment]
+1

**Comment by tlrobinson** [comment]
Yup, originally when we designed this feature we were going to auto-shorten the URLs if they got too long but decided to leave out that complexity until we ran into issues. Looks like it's time to revisit this.

**Comment by camsaul** [comment]
I looked into the quick & dirty fix for this and tried to strip out the `Refer` header:
```js
$httpProvider.defaults.transformRequest.push(function(data, headersGetter) {
    delete headersGetter().Referer;
    return data;
});
```

But apparently you're not allowed to modify/unset `Refer` these days ([`XMLHTTPRequest.setRequestHeader()` forbids it](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest?redirectlocale=en-US&redirectslug=DOM%2FXMLHttpRequest)).

So it looks like we will have to actually use shorter URLs :sob: :persevere: :package:

**Comment by agilliland** [comment]
We can address this on the server by bumping the request buffer size on jetty via `:request-header-size 32768`.

When I tested this, with our current setting of 8k, you run into this issue with a SQL query of around 5800 characters.  When I bump this up to 32k I'm able to get in 4x as many characters, which means you could write a query with 23k characters in it.

That seems like plenty to me.  @MartinArens @julianriedelsheimer , you guys voted for this issue so I'm assuming you ran into it at some point?  mind sharing the size of the query you had written when this issue came up?

**Comment by camsaul** [comment]
nginx is throwing the exception in some cases. try it on a AWS instance.

**Comment by julianriedelsheimer** [comment]
right I had the same issue. my query had 7500 characters. 32k should be plenty I guess to start with.
