### ISSUE TITLE
Exports should include formatting everywhere

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17753]
**Is your feature request related to a problem? Please describe.**
I really don't understand how our code functions, but I am wasting so much time on having to validate every single way we can export, which clearly seems like it should be unified to avoid regressions (we have had many of those).

Currently exports can have very different formatting in these cases:
- In-app, unsaved question
- In-app, saved question
- Public Sharing
- Signed Embedding
- Pulse/Dashboard Subscription
- *...other?*

**Describe the solution you'd like**
Create one function that actually generates the export with correct formatting, which is then used by all the different endpoints.

**How important is this feature to you?**
Critical. I have wasted too much time testing exports, and we have had too many regressions (example #17752).

Related #16234

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by noahmoss** [comment]
The user-facing part of this (lack of formatting for XLSX pulse attachments) should be fixed by  #17755.

The more general problem, as you described, is that the code for generating attachments is a bit roundabout: each query in the pulse/subscription is executed normally, and then for queries that need to be converted to attachments, the in-memory results are streamed to the appropriate export format. In contrast, normal exports are streamed directly to the export format as part of the main query execution. Here's a comment with more context: https://github.com/metabase/metabase/blob/cb97c835453780034067589a5631bbf47df72218/src/metabase/email/messages.clj#L353-L355

Standardizing these code paths would definitely be worthwhile, but would also require a major refactor of the pulse generation code. Maybe we can keep this open as a tech debt issue once #17755 is merged?

**Comment by flamber** [comment]
The problem is not specific to XLSX. CSVs suffers from the same as 13677/12964/10803.
I would love to not have to test every single way we can export and then create separate issues for each way.

Currently there's these formatting levels, but if we want to support user-specific defaults (requested by international customers), then it just gets even more complex and likely cause more regressions:
1. System/code defaults (this should almost never be used, since it's mostly US-centric defaults, it should generally use Global)
2. Global (Admin > Settings > Localization)
3. Field (Admin > Data Model > db > table > field :gear: > Formatting, but the semantic type also comes into play)
4. Question (visualization > Settings - either saved or unsaved)
5. Dashboard card (card > Visualization Options)

This is not a TechDebt issue - I gave it Completeness instead of Bug+Correctness, but it's actually closer to that.

**Comment by camsaul** [comment]
> the code for generating attachments is a bit roundabout: each query in the pulse/subscription is executed normally, and then for queries that need to be converted to attachments, the in-memory results are streamed to the appropriate export format. In contrast, normal exports are streamed directly to the export format as part of the main query execution.

I think we should prioritize addressing this and then see where we are... that would divide the number of code paths in half

**Comment by jrca025** [comment]
@flamber is there any workaround for this?
