### ISSUE TITLE
Hiding all tables in data model removes them from the permissions page

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17777]
**Describe the bug**
When all tables in a database are hidden in the data model, they are not visible in the permissions page.

**To Reproduce**
1. Go to Admin > Data model > Sample Dataset
2. Click on the "crossed eye" icon to hide all tables
3. Now go to Permissions tab (it should open to `/admin/permissions/data/group` page by default)
4. Choose any of the user groups from the sidebar and click on it
5. In the page that opens, there should be a "Sample Dataset" link under "Database name" column - click on it
6. URL should change to `/admin/permissions/data/group/:group_id/database/:database_id`
7. Notice there are no tables to choose from. Only a message "Nothing here"
![image](https://user-images.githubusercontent.com/31325167/132259142-da6cd3b7-0d0e-4f53-85c3-8f2ecd4df6a1.png)

**Expected behavior**
One should be able to set data permissions regardless of the tables' visibility setting.

**Information about your Metabase Installation:**
local dev, `master`, 52c9a610add28d86b3449321b0012ed492bd65f3, sample dataset, H2

**Severity**
Seems quite severe that there is no option to set a granular permissions to individual tables.

**Comment by camsaul** [comment]
So it looks like the root cause of this is that the perms graph page is calling `GET /api/database?include=tables` which returns all the Tables for all DBs, but only if they're visible. I'll add an `include_hidden` parameter to the endpoint to return hidden ones as well. Then we can update the FE to use it.

Side note: the graph page calls both `GET /api/database` **and** `GET /api/database?include=tables`... the latter is a superset of the former. We don't need both API calls.

Side note #2: Fetching all tables for all databases seems really inefficient. It would make a lot more sense to just combine a call to `GET /api/database` (fetch list of Databases) with calls to `GET /api/database/:id?include=tables` as you drill down for each DB. Suppose we have 100 databases with 100 tables each... we're fetching 10000 Tables from the DB just to load the list of databases

**Comment by camsaul** [comment]
Not sure if it would make more sense to add `include_hidden` to `GET /api/database/:id?include=tables` instead so we can address the performance issue at the same time... I'll ask around and see what people think makes sense
