### ISSUE TITLE
Remove the name of the question in the url

### ISSUE THREAD

**Issue by MaximeRobion** [metabase/metabase#17822]
**Is your feature request related to a problem? Please describe.**
When I share a question, I send its url. Though, I might come back to this question and change its name. At that moment, the url I sent will not be the right one anymore, and the people I sent it to won't have access to the question.

**Describe the solution you'd like**
Do it as before, the url of the question is just a number. That was perfect!
eg. https://metabase.urbancampus.com/question/160 instead of https://metabase.urbancampus.com/question/160-07-deposit-refunds

**Describe alternatives you've considered**
The alternative I used is to share the collection link and never change the collection name.

**How important is this feature to you?**
To be fair, I send a lot of queries through their link. This could be for reviews, or just to share my work. I would say that half of the time, people in my team don't bother going through the UI of metabase but just have the link somewhere and refer to it when they need.

**Additional context**
None

**Comment by flamber** [comment]
Hi @MaximeRobion 
You can just send `https://metabase.example.com/question/160` to people if you want.

1. If you have a question called "Old Name", then the URL is `https://metabase.example.com/question/160-old-name`
2. You send this URL to people
3. And then you change the question to "New Name", so the URL is `https://metabase.example.com/question/160-new-name`
4. Then when someone clicks the old link, it will automatically update the address to the new name, since Metabase only looks at the ID to find the underlying question. Otherwise this would a high priority bug.

The point of including the name in the URL was to make it easier to understand which question/dashboard/collection the link referred to, since an ID doesn't tell a lot.

Want to close this? I doubt that we will revert back to how it used to be with ID-only URLs.
