### ISSUE TITLE
When joining in a way that returns columns with same name, columns are suffixed and missing metadata

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1786]
e.g. `name` and `name_2`. I believe this is done automatically by Clojure JDBC.
-  Since we don't know the source of `name_2` the correct Metadata doesn't get returned along with it. 
-  It would be better to give it a name like `<table_name>.name`.

See also #1447.

**Comment by agilliland** [comment]
I checked this out a little bit and this is specific to the clojure.jdbc wrapper, which is sadly not well setup to handle the situation where multiple columns have the same name.

Here's some quick example code:

```
;; clojure JDBC
(jdbc/with-db-transaction [conn (jdbc-details mysql-details)]
  (jdbc/query conn "select f.name, t.name from metabase_field f join metabase_table t on f.table_id = t.id"))

Output:
({:name "Metric", :name_2 "rh_reservenightlyemail"} {:name "Yesterday", :name_2 "rh_reservenightlyemail"} {:name "Last Week", :name_2 "rh_reservenightlyemail"} {:name "WoW", :name_2 "rh_reservenightlyemail"})
```

```
;; raw Java JDBC
(jdbc/with-db-transaction [conn (jdbc-details mysql-details)]
  (let [stmt (.createStatement (:connection conn))
        rs   (.executeQuery stmt "select f.name, t.name from metabase_field f join metabase_table t on f.table_id = t.id")
        rsmd (.getMetaData rs)]
    (doseq [idx (range (.getColumnCount rsmd))]
      (println idx "=" (.getTableName rsmd (+ 1 idx)) (.getColumnName rsmd (+ 1 idx))))))

Output:
0 = metabase_field name
1 = metabase_table name
```

So the actual Java JDBC driver is not doing this, it's the fact that the clojure jdbc code wants to convert the ResultSet into a Map and it's trying to key the map using just the column name, so collisions are possible.

Here's the offending code ... https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L295-L312

Since we probably don't want to rewrite the clojure.jdbc code I think the best/most sensible way to address this problem is to construct our SQL with explicit names for every expected column.  If we specify the name of every column when we generate the SQL then we can ensure there are no collisions and we can fully control the mapping of the results back to the Metabase metadata.

**Comment by camsaul** [comment]
They're actually no longer missing Metadata as of #4003 so going to go ahead and close my issue for this
