### ISSUE TITLE
Schemas with only hidden tables are shown in the data selector

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#17989]
**Describe the bug**
Schemas with only hidden tables are shown in the data selector
Regression in master compared to 0.40.4

**To Reproduce**
This requires a database with multiple schemas.
1. Admin > Data Model > (db) > select a schema > hide all tables in the schema - example
![image](https://user-images.githubusercontent.com/1447303/134188974-224e3027-e1b0-4411-a219-cf99b887d672.png)
2. (do a browser refresh or open new tab, just to make sure there isn't any cache)
3. Ask question > Simple question > (db) - it shows the schema, and it's possible to click the schema
![image](https://user-images.githubusercontent.com/1447303/134189520-bae96a3b-6c5b-4507-bc10-5aa6302f2afb.png)
![image](https://user-images.githubusercontent.com/1447303/134189586-e2162cf2-a73b-44c7-8419-06a227239e31.png)

**Expected behavior**
Similar to previous versions, when hiding all tables in a schema, then it should not be shown.

**Information about your Metabase Installation:**
Tested `3c417b0`

**Additional context**
Very related to #16282

**Comment by kulyk** [comment]
A regression since #17455 (don't prefetch data for the data selector). Earlier, Data Picker used to fetch lists of databases, schemas, and tables and filter out hidden records. After #17455 tables are no longer prefetched to improve performance on large instances, so the FE can't filter out schemas with all tables hidden as it has no tables data.

A potential fix can be an optional query parameter for `GET /api/database/:id/schemas` asking the BE to return only schemas with at least one visible table
