### ISSUE TITLE
Dragging dashboards filters makes them hidden while dragging

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18047]
**Describe the bug**
Dragging dashboards filters makes them hidden while dragging

**To Reproduce**
1. Go to dashboard - add a filter - try moving the filter, it becomes hidden while dragging and is then shown again on release

The filter gets `opacity:0; visibility:hidden;` while DND.

Similar happens in Native editor, but that also happens on 0.40.5

**Expected behavior**
Don't hide the filter while dragging. And plus points if z-index could be applied while dragging, so the widget being dragged is top.

**Information about your Metabase Installation:**
master `b557b69` - regression since 0.40.5, where it widget is shown while DND on dashboard

**Comment by kulyk** [comment]
It's expected for a filter to receive `opacity: 0; visibility: hidden;` style while dragging. We use [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc), and it hides the dragged item and creates its absolutely positioned copy that's actually being dragged. The problem here is that the dragged item doesn't have `z-index` set, so it's overlapped by other UI elements
