### ISSUE TITLE
support "does-not-contain" filter option for strings

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#1829]
It should be possible to exclude strings from a query via the query builder beyond exact matches.

**Comment by camsaul** [comment]
An alternative to consider is just adding a general `not` filter operator to MBQL. This would let us do things like `[:not [:contains ...]]` or even `[:not [:starts-with] ...]` and `[:not [:ends-with ...]]`. So it's more flexible in the long run and ultimately would make MBQL more expressive and more powerful.

I've looked into this in the past; it's easy to implement on the backend, but I'm not sure how much effort it would be to do on the frontend. We'd probably still want to expose `[:not [:contains ...]]` as "does not contain" in the UI, so that would require some extra work. @tlrobinson off the top of your head do you know how difficult would it be for the frontend to support something like that?
