### ISSUE TITLE
Clicking in a question in the audit log tracks a view

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#18439]
**Describe the bug**
When going to any question in the Audit->Team Members->Audit log, and seeing just the activity or revision history, Metabase will track that as a "View" on the question, although the actual question wasn't seen at all

**Logs**
N/A

**To Reproduce**
1) Go to our internal instance, Settings->admin->audit->Team members->Audit log and click on any question
2) Now go to the audit log of that specific question, you'll see your name on the top, although you haven't actually viewed it

**Expected behavior**
Don't track views if we see the audit log of the question, track the view when the user actually sees it

**Screenshots**
None

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
Our internal instance

**Severity**
High

**Additional context**
NA

**Comment by calherries** [comment]
The issue is caused by an instance of `Question.Loader` [here](https://github.com/metabase/metabase/blob/master/enterprise/frontend/src/metabase-enterprise/audit_app/pages/AuditQuestionDetail.jsx#L25) on the audit question page, which registers a view event on the BE [here](https://github.com/metabase/metabase/blob/master/src/metabase/api/card.clj#L168). Any solution to this should follow the solution for tables https://github.com/metabase/metabase/pull/23780.
