### ISSUE TITLE
Support SAML and JWT logins at the same time

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18554]
**Is your feature request related to a problem? Please describe.**
Currently when both SAML and JWT logins are enabled, then only a single "Sign in" button is shown on the login page, which is for the SAML IdP.
Even when sending a JWT payload directly to `/auth/sso`, then still redirects to SAML IdP.
![image](https://user-images.githubusercontent.com/1447303/137902778-24257bdb-5ce5-4de2-9d61-94903008b39b.png)

**Describe the solution you'd like**
Allow separate buttons. Or at least allow JWT payload to not redirect to SAML.
Example, "Google Sign-In" is shown as a separate button:
![image](https://user-images.githubusercontent.com/1447303/137902866-4c87c076-7385-4790-a7b7-02397c59c7df.png)

**Describe alternatives you've considered**
Depending on SAML IdP, integrating JWT into that, so everyone sign in via SAML.
This might not be an option for all, and might require a lot of work depending on the IdP.

**Comment by camsaul** [comment]
Mentioned this in Slack but I'll copy it here as well so it doesn't get lost.

I'm not 100% sure this is going to work without making a few tweaks to the User model on the backend... right now there is an assumption that a User is tied to either 0 or 1 SSO methods -- there's an `sso_source` column set to their auth type (see https://github.com/metabase/metabase/pull/20577 for related recent work). So before supporting multiple SSO methods at the same time we need to decide whether we want to support Users logging in with multiple SSO methods or not -- if I originally logged in via JWT and my `sso_source` is `jwt`, what happens if I try to log in via SAML? Do we:

1. Disallow login with SAML with an error like `Hey Cam, you can't log in with SAML, you are a JWT user`?
2. Allow login with SAML? If we do that, do we update `sso_source` to `saml`? Does this make `sso_source` basically meaningless?
3. Migrate `sso_source` to an array of allowed login methods e.g. `#{:jwt :saml}`? That would probably mean we need to add UI so admins can configure which SSO methods each user is allowed to use

Should these behaviors be tweakable with Admin Settings? I can see a case for saying I don't want LDAP users crafting JWTs and logging themselves in that way with a different set of user attributes

**Comment by paoliniluis** [comment]
Just to add to this, the specific use case that a customer requested was to have SAML for Internal users while using JWT for external users (full app embedding), so for this specific case these 2 groups are exclusive.
