### ISSUE TITLE
Email rendering on mobile phone since version 0.41

### ISSUE THREAD

**Issue by nicocashie** [metabase/metabase#18755]
**Describe the bug**
Since Metabase version 0.41, email rendering on mobile phone : not possible to have the big picture and zoom in / out.

**Logs**
N/A

**To Reproduce**
1. Create a new Question
2. Using the table ORDERS of the Sample Dataset, display the orders
3. Add a filter April 19, 2020
4. Save the question
5. Create a pulse and select the question created and test with Send email now

Tested under version 0.40.3.1 and version 0.41.1

**Expected behavior**
On mobile phone, be able to see the big picture of the question, and be able to zoom in / out

**Screenshots**
iPhone 7 Plus - iOS 15.0.1
Email rendering on version 0.41.1
![image](https://user-images.githubusercontent.com/61732374/139440568-ed767ca9-885f-46d6-8898-c6c95ca4827f.png)

Email rendering on version 0.40.3.1
![image](https://user-images.githubusercontent.com/61732374/139440732-633e870c-dea1-480d-ba71-03501e9f3428.png)

**Information about your Metabase Installation:**
version 0.41.1 :
- Your browser and the version: Chrome/95.0.4638.54
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.41.1
- Metabase hosting environment: on premise on Windows Server
- Metabase internal database: Postgres
version 0.40.3.1 :
- Your browser and the version: Chrome/95.0.4638.54
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.40.3.1
- Metabase hosting environment: on premise on Linux server
- Metabase internal database: H2

**Severity**
Pulse / Dashboard subscription sent to executive board, difficult to analyse the results.

**Additional context**
N/A

**Comment by noahmoss** [comment]
Some context on this issue:

Prior to 41, tables rendered in pulse/dashboard subscription emails would be truncated at 10 columns. If a table had more than 10 columns, you would have to download the attachment to see the rest.

In 41, with the email redesign, we removed the column limit but made it so that the table is horizontally scrollable. This should work on both mobile and desktop but it's a bit hard to discover. It also means that you can't zoom out to show more data in the table at once. Not sure if there's any CSS magic that can give us the best of both worlds here.

**Comment by rlotun** [comment]
fixed by https://github.com/metabase/metabase/pull/19654
