### ISSUE TITLE
Feature: Drill-down reporting

### ISSUE THREAD

**Issue by coussej** [metabase/metabase#1884]
An interesting feature would be to have multiple groupings for a dataset, and being able to create drilldown charts for them (something like [this](http://www.highcharts.com/demo/column-drilldown))

For example: I have orders linked to a region and linked to a salesperson.

It would be awesome if you could group by region, then by person in order to create a graph of orders per region, and when you click on a region, if filters on that group and shows the data per salesperson.

**Comment by agilliland** [comment]
Cool.  I've seen drill downs used in a variety of contexts, but this is a very focused and practical application which is a nice alternative to stacked bar charts.  Seems like a fairly solid way to visualize a 2 dimensional breakout.

**Comment by LukeAbell** [comment]
+1

**Comment by tmyoon** [comment]
+1

**Comment by rafaelveloso** [comment]
+1

**Comment by that0n3guy** [comment]
+1

A more simple example is a chart that shows count of rows grouped by category.   If a bar graph is clicked, it shows the data in that bar in table form (non-aggregated, just displayed).

**Comment by daniloaburto** [comment]
+1

**Comment by markrey** [comment]
+1

**Comment by mariosergioti** [comment]
+1

**Comment by salsakran** [comment]
punting this out of 0.20 until we get #3079 dialed in.

**Comment by moumny** [comment]
FYI, the number 1 feedback we get from our users is "is it possible to drill down?"
This can be implemented in several ways

- You click on bar or a pie chart and this redirects you to another dashboards with the relevant filters selected.
- Same as above but each card is linked to another "drilled down card"
- The graph expands into a larger modal/card where you can get asked on which dimension to  breakout next. (or get raw data). 
- You get redirected to the query builder with the relevant filters/fields already set which allows you easily add more group bys for example

Last option is too complicated for users that do not want to use the query builder.
Ideally the dashboard creator should define what is the workflow (by linking to other dashboards or selecting which are the next logical questions/cards you should look at)

At the moment we create several dashboards and add several(most of the time unnecessary) cards to them in order to deal with the problem.

**Comment by salsakran** [comment]
+1

For what it's worth, me punting it out of 0.20 is less downplaying it and more the fact that it's a marquee feature.

We've played around with 3 or 4 approaches, and there are two linked problems:
1. It's very hard to create clear, predictable unambiguous rules as to what a click or tap should do in general (vs with a specific card). There are often more than one sensible things you can do. 
2. It's a royal pain in the ass to manually set up drill through paths in other products and turns every dashboard card into a mini-app.

Where we've ended up is the following rough framework, which you can see in #3079 
* Every cell, row or full table in a result offers up a set of possible next views
* Those will be displayed in an overlaying pane in the right of the screen
* We'll be using a mix of ML and AI techniques to fine tune this set of suggestions over time (the goal is to effectively learn the desired drill through patterns)
* We'll also (eventually) offer the ability to edit these recommendations on a per-card level if we just can't seem to get it right.

**Comment by tomsej** [comment]
+1

**Comment by diegonetto** [comment]
+1

**Comment by vkarpov15** [comment]
+1

**Comment by joermungandr** [comment]
+1

**Comment by Slayr** [comment]
+1

**Comment by 100n0m3** [comment]
+1

**Comment by lanner22** [comment]
+1

**Comment by 100n0m3** [comment]
+1

**Comment by tlrobinson** [comment]
@100n0m3 Please use the 👍  reaction instead of "+1" comments. Thanks.

**Comment by mohanm76** [comment]
+ 1 
I should have ability to just review or open a card in a new tab.

**Comment by mryanb** [comment]
+1 Drill down for tables would be great! Example: Clicking on one of the following invoice counts would show you another table of invoices.
![image](https://cloud.githubusercontent.com/assets/3656391/22560700/ccb36a7a-e932-11e6-99b7-824d4eb1a4c6.png)

**Comment by szkrawcz** [comment]
+1 Drill down feature will make metabase project  in top of all dashboards projects.

**Comment by macfly1202** [comment]
+1 Drill down, Ad Hoc mod will be great, similar to Pivot.

**Comment by ecommandeur** [comment]
@szkrawcz @macfly1202 did you also use the thumbs up reaction? See comment by @tlrobinson above

![image](https://cloud.githubusercontent.com/assets/2678528/23116995/cadad7be-f74d-11e6-919e-ff377fcb6407.png)

**Comment by macfly1202** [comment]
@ecommandeur : understood for next time - sorry !

**Comment by szkrawcz** [comment]
@ecommandeur yep, already done ;)

**Comment by dtheodor** [comment]
In order to enable drill-down, you need to introduce the concept of dimension hierarchies, which is what defines the drill-down action: you drill-down from a less-detailed dimension to a more detailed one, for example, drill-down from country to city

I think you can solve this by following the same approach you use for dashboard filters.

How are filters configured now? There are 2 components
1. at the data model, foreign keys are specified
2. in the dashboard, a filter is allowed to select any field in a question as long as there is a possible JOIN from the question's table to the table containing the field, determined by the foreign key configuration at the data model

Dimension hierarchies can use the same approach
1. At the data model, specify hierarchies by selecting existing table fields and putting them in an ordered list. For example I would create a Location hierarchy of 3 fields: continent, country, city
2. In the dashboard, create a special "drill-down filter". This filter is associated with a specific dimension hierarchy, and can be wired up to questions, but only to a field that is a member of the selected dimension hierarchy. For example, I'm creating a 'country' drill-down filter, choosing my 3-field hierarchy for it, and wire it up to the 'country' field of the questions. The filter is populated by all the country values of my dataset, like a regular filter. When I select a value, it will not only filter the data in all wired-up questions, but those questions that use this field in their group-bys will change the groupby from 'country' to 'city', effectively doing a drilldown

There can be variations on this idea, like omitting the filtering and only change the group-by level. This http://www.cubesviewer.com/studio.html is a project that does this

**Comment by hasder01** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by salsakran** [comment]
implemented in #4496
