### ISSUE TITLE
Admin Settings > Maps breaks when `custom-geojson` is set via env var `MB_CUSTOM_GEOJSON`

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#18862]
**Describe the bug**
When setting `MB_CUSTOM_GEOJSON`, then the frontend returns blank screen.

Workaround: Set it directly in the application database table `setting` or set it via the API with key `custom-geojson`, with value, eg. `{}`
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**To Reproduce**
1. Start Metabase:
`java -DMB_CUSTOM_GEOJSON='{"864d0660-2e03-ba4e-f23c-7d31eb6ac7b8":{"name":"Custom States","url":"https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/us-states.json","region_key":"STATE","region_name":"NAME"}}' -jar metabase.jar`
2. Go to Admin > Settings > Maps - blank screen
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at i.value (app-main.bundle.js:2)
    at Wa (vendor.bundle.js:2)
    at Ba (vendor.bundle.js:2)
    at xs (vendor.bundle.js:2)
    at vu (vendor.bundle.js:2)
    at gu (vendor.bundle.js:2)
    at uu (vendor.bundle.js:2)
    at vendor.bundle.js:2
    at t.unstable_runWithPriority (vendor.bundle.js:2)
```

**Information about your Metabase Installation:**
Tested 0.41.1 (versions pre-0.40.0 would not error, but would not apply the envvar, when there was keys in `setting` table)

**Additional context**
Related to #13166 and #14790

**Comment by camsaul** [comment]
Ok, so looking into this a bit more...

You absolutely CAN use an env var with `MB_CUSTOM_GEOJSON`, and it actually works just fine except for that Admin Settings page in question.

The `GET /api/setting` endpoint powering the Admin Settings page returns the Setting as

```clj
{:key            :custom-geojson
 :value          nil
 :is_env_setting true
 :env_name       "MB_CUSTOM_GEOJSON"
 :description    "JSON containing information about custom GeoJSON files for use in map visualizations instead of the default US State or World GeoJSON."
 :default        "Using value of env var $MB_CUSTOM_GEOJSON"}
```

This is 100% intentional. The endpoint is supposed to return `nil` as the value of Settings set via env var because Admins **are not** allowed to override them -- this is how it's worked since day one. That's also why `is_env_setting` is there (and it correctly returns `true`), and why `:default` is a message to this effect. So the admin panel not working is a FE client bug -- it needs to check `is_env_setting` and disable this page or show something to that effect if this is the case.
