### ISSUE TITLE
Unexpected attachment behavior when attaching CSV results to emailed Dashboard Subscription

### ISSUE THREAD

**Issue by andrewler** [metabase/metabase#18981]
**Describe the bug**
There are a total of two possible files to attach in the dashboard subscription email attachments list.
I select (checkbox) one file to attach in the Dashboard Subscription configuration panel.
When the email is sent out daily, I receive both CSV as attachments instead of the one I specifically selected

**To Reproduce**
1. Dashboard Subscriptions
2. Email it daily
3. Scroll down to 'attachments'
4. place a check mark in only the first attachement checkbox
5. Wait for the daily email to be automatically sent out

**Expected behavior**
I should receive the dashboard subscription email with the CSV attachment I specified.  No more, no less.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-210-generic",
    "user.language": "ko",
    "user.timezone": "Asia/Seoul"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.41.1",
      "date": "2021-10-21",
      "branch": "release-x.41.x",
      "hash": "76aa4a5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Very low severity.  Just a small annoyance.

**Additional context**
The problem seems to be isolated to csv attachments.  The problem goes away when selecting xlsx attachments.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @andrewler 
This is because attachments are manually created for tables with more than 10 rows, since that was the default for older Pulses, but given that there's an explicit selection now, then it feels wrong to send the "automatic" attachments.

**Comment by DiegoDantas001** [comment]
Hi, there! I've been using Metabase for quite a while and I enjoyed the subscription feature a lot. However the problem does not seem to be isolated with .xslx and .csv attachments so it's creating some annoyance with the business teams when they receive an email with .csv attachments even when the 'Attach results' option is toggled off. __Metabase version__=  0.41.1. 
Thanks!

**Comment by johnswanson** [comment]
This is intentional but confusing behavior: as @flamber mentioned, we send attachments for any tables with >10 rows.

Changing this now would presumably break existing workflows, if people now expect attachments for these tables in their existing subscriptions. If they've received emails with a given CSV attachment for years, it might be frustrating to suddenly stop receiving those CSVs.

One option might be to create a migration to automatically add `include_csv` to any table-displayed pulse card, while removing the automatic attachment. This way, existing email notifications would continue to go out as before, with attachments, while newly created subscriptions wouldn't get attachments unless people specifically requested them.

Possibly at some point we could default `include_csv` to `true` for new table-displayed pulse cards as well.

**Comment by adam-james-v** [comment]
https://github.com/metabase/metabase/pull/36383 closes this issue
