### ISSUE TITLE
Fix the GitHub "new" label bot

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#1906]
@agilliland this...
![screen shot 2016-02-08 at 7 13 55 pm](https://cloud.githubusercontent.com/assets/1455846/12906779/742d1550-ce98-11e5-9cce-9fcc94368d90.png)

 is getting...
![screen shot 2016-02-08 at 7 11 18 pm](https://cloud.githubusercontent.com/assets/1455846/12906747/30001044-ce98-11e5-9b97-2000467325e0.png)

pretty frustrating...
![screen shot 2016-02-08 at 7 08 33 pm](https://cloud.githubusercontent.com/assets/1455846/12906748/30008326-ce98-11e5-8c44-9ef84019a015.png)

**Comment by camsaul** [comment]
![screen shot 2016-02-08 at 7 22 01 pm](https://cloud.githubusercontent.com/assets/1455846/12906860/3e0271f4-ce99-11e5-8065-85056a1ab5ab.png)


^ **THIS**

**Comment by camsaul** [comment]
@agilliland why would you just close this?

**Comment by camsaul** [comment]
@agilliland Why do you keep closing this issue without giving any reason?

**Comment by agilliland** [comment]
This isn't even filed in the right place.  it's not related to this project.

**Comment by camsaul** [comment]
Why couldn't you have said that the first two times you closed it? As it affects this project specifically I'm not aware of a better place to file an issue

**Comment by agilliland** [comment]
The code in the current repository is for the Metabase application.  We have other repositories for supporting services where you can file this if you want.  

Issues in this repository should be constrained to things that actually affect the shipped Metabase application only.

**Comment by camsaul** [comment]
It's a best practice, I think, to tell people why we're closing their issue. Can we please remember to do that in the future?

**Comment by agilliland** [comment]
Sure, I'm happy to do that and in exchange I'll ask that you refrain from trolling GH issues with unnecessary issues and screenshots.

**Comment by camsaul** [comment]
It's frustrating when I try to categorize new issues and your bot removes the tags 2 or 3 times a day. I'm not sure how asking to have that be fixed is considered "trolling"

**Comment by agilliland** [comment]
I can understand that could be frustrating and that's why I would be happy to help you out if you come to me and talk about it.  

I am equally frustrated when I have more work to do each day than I can expect to complete and I have to spend the precious attention I have available dealing with silly comments about how I don't delete my branches within 5 seconds of closing a PR.

So again, this issue should have been filed in another repository where the appropriate code resides.  I'm happy to take this conversation offline if you would like to discuss it further.
