### ISSUE TITLE
Metabase Cloud Enterprise Does Not Support Custom SMTP 

### ISSUE THREAD

**Issue by Will-Angel** [metabase/metabase#19120]
**Describe the bug**
Metabase Cloud Enterprise does not support custom SMTP setups

**To Reproduce**
1. Create a Metabase Cloud Account
2. Upgrade to Metabase Enterprise
3 Navigate to Settings in Admin  view

**Expected behavior**
The Email SMTP configuration option visible in regular Metabase cloud should still be available after the upgrade. None of the enterprise documentation on the Metabase website indicates that this feature regression exists.

**Observed behavior**
The option to configure an SMTP server is no longer visible.

**Severity**
Relying on the Metabase Cloud email address means that subscriptions and alerts can only be sent from 'noreply@metabaseapp.com' which makes it difficult to use dashboard subscriptions as automated reports for external partners because the email will not come from a company domain and conflicts with brand guidelines.

**Comment by flamber** [comment]
Hi @Will-Angel 

Metabase Cloud has pre-defined settings for emails, which are made because it's a service, so people didn't need to configure that.
It is not possible to change that currently, but we are working on allowing you to bring-your-own-domain (including SMTP).

I would recommend that you contact customer support.
