### ISSUE TITLE
Combine Clj-Kondo configs

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19257]
When we first started using Kondo we put the config in [`lint-config.edn`](https://github.com/metabase/metabase/blob/master/lint-config.edn) for whatever reason... I think most people would expect it to have a name specific to Kondo. We actually merged in a 3rd-party PR to tweak our Kondo config (#17964) but they didn't realize we already had one (and I didn't notice this when I reviewed the PR) so it actually created a new config in `.clj-kondo/config.edn`.

I think the latter name is more obvious, so we should combine `lint-config.edn` into it and then update the GitHub actions config and the cheatsheet in https://github.com/metabase/metabase/wiki/Migrating-from-Leiningen-to-tools.deps#running-commands

**Comment by dpsutton** [comment]
I initially wrote the config into `lint-config.edn` because we generated an enormous amount of warnings due to extensive use of macros in our codebase. I figured it would allow us to gradually improve a "working" clj-kondo config where we were ok with more errant warnings while working, and then a more strict config for actual linting where it could fail a build.

If we merge these, it would combine the one that powers lsp/clj-kondo linting in your editor with what fails a build in CI. I'm not sure that it is the best idea to unify these yet.

**Comment by camsaul** [comment]
I was working on fixing all those warnings here https://github.com/metabase/metabase/pull/16726/files#diff-56d37d7527d525988517205427f304cc7280ae2f5f499d9869fbc92c5d0e7e52R92-R111 (PR #16726) but I eventually closed that PR out without merging because it got a little too big due to lint error fixes. But I think that fixed most of the warnings.

I think with a little bit of work we could fix all the other warnings

**Comment by camsaul** [comment]
Implemented by #22213
