### ISSUE TITLE
distinguish between DateField, DateTimeField, and TimeField

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#1929]
Currently many parts of the application are treating these cases as synonymous, but they are not and in reality they each represent a different set of temporal data.  It's becoming fairly rare to see DateField and TimeField existing on their own, but it is something that happens.

This is a fairly broad issue, but a specific example to reign it in is that the frontend Date filtering and Date breakout widgets should limit choices appropriately.  For example, it should not be possible to group by "Hour" on a DateField because that field does not have data at that level of granularity.

**Comment by camsaul** [comment]
I think this is really part of a larger issue. We need to rethink our Field types in general. Our `special_types` are a relic of the old Django days ([that's why they have names like `BigIntegerField` and `CharField`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#field-types)) and have been something I've wanted to revisit for a long time. One of the last bits of cruft, one of the last traces of the Dark Ages :scream: 

I want to move to a hierarchical type system like the one I drew up a few months back. This would let us support advanced things like "currency" or "Instagram Photo ID" easily and even do other wacky stuff like Postgres enums.
![image](https://cloud.githubusercontent.com/assets/1455846/13022630/9e41df40-d197-11e5-869e-9db08a90abc8.png).

**Comment by agilliland** [comment]
For sure.  The set of options for marking up the data model needs an upgrade and we have a lot of good thoughts captured about how to do that.  It needs a little more input before it's fully ready, but once that's g2g this would be a good project for us to work on.

**Comment by camsaul** [comment]
This is basically asking for the same thing as #2069 (filter by time in addition to date), but since that issue has a real-world use case in the description I'm going to close this as a duplicate in favor of that one.
