### ISSUE TITLE
Migrating H2db to Postgres

### ISSUE THREAD

**Issue by tmr12** [metabase/metabase#1938]
I am able to generate a sql dump file from h2 using `org.h2.tools.Script.process(Connection con,SQLfile_name,"","").`
how the generated dump file (from h2)can be uploaded into postgres?
Could you please help on this if you already done the migration from h2db to postegres

**Comment by agilliland** [comment]
Hi @tmr12 , we provide a build-in migration command specifically so that we can avoid the problem you are describing.  Not all databases use the same syntax and so it's not as simple as one would hope to take a dump from an H2 database and load it into postgres/mysql/etc.

Here's the docs on how to use the Metabase migration command ... http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres
