### ISSUE TITLE
Nested query is displaying column results with metadata from another column

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#19403]
**Describe the bug**
When using nested query, then it's somehow including the wrong column's metadata, while the result data is correct.

Regression on master.

**To Reproduce**
1. Custom question > Sample Dataset > Products - summarize Sum of Price and Max of Rating, grouped by Category. Save as "Q1".
![image](https://user-images.githubusercontent.com/1447303/146544128-ac53954a-a1af-4321-9ce2-054e5d91eb82.png)
2. Custom question > Saved Questions > "Q1" - summarize Count and Average of "Sum of Price"
![image](https://user-images.githubusercontent.com/1447303/146544029-51d98907-5b3b-4d1d-a78b-4c8963296d09.png)

**Information about your Metabase Installation:**
Tested 0.41.5 and master - regression on master

**Severity**
If the metadata is very different, like a date, then it displays that format, since it's using the semantic type from that field, while including results from the correct field.
![image](https://user-images.githubusercontent.com/1447303/146544501-7a8b64d9-09bc-422d-b156-dba07b9d0022.png)

**Additional context**
Originally found by @ukritw

**Comment by dpsutton** [comment]
So the issue is that we have non-unique names for aggregations:

```clojure
(s/defn ^:private cols-for-ags-and-breakouts
  [{aggregations :aggregation, breakouts :breakout, :as inner-query} :- su/Map]
  (concat
   (for [breakout breakouts]
     (assoc (col-info-for-field-clause inner-query breakout)
            :source :breakout))
   (for [[i aggregation] (m/indexed aggregations)]
     (assoc (col-info-for-aggregation-clause inner-query aggregation)
            :source    :aggregation
            :field_ref [:aggregation i])))) ;; aggregations are labeled by index i
```

When you have these at multiple levels, we end up with two distinct aggregations with the same name and then merge their metadata.

Roughly, `select aggregation 0, aggregation 1 from (select aggregation 0, aggregation 1) ...` but these aggregations are not related. 

We used to merge things by `:id` which is just a no-go since many fields do not have ids (all native fields in a query, any aggregations, or breakouts, etc). But I think this points out a new strategy is needed depending on the circumstances.

- merging at the same level: we compute metadata and also grab it from the driver, and sometimes other information. When at the same level, we should use the field_ref
- merging things "up". When selecting 

For instance, when selecting `(select * from (select sum of price, max of rating ))` the outer field metadata is
```clojure
{:field_ref [:field "sum" {:base-type :type/Float}]
 :base_type :type/Float
 :name "sum"
 :display_name "Sum of Price"
 :effective_type :type/Float
 :semantic_type nil
 :source :fields}
{:field_ref [:field "max" {:base-type :type/Float}]
 :base_type :type/Float
 :name "max"
 :display_name "Max of Rating"
 :effective_type :type/Float
 :semantic_type :type/Score
 :source :fields}
```
And the inner `select` metadata is 
```clojure
{:base_type :type/Float
 :semantic_type nil
 :settings nil
 :name "sum"
 :display_name "Sum of Price"
 :source :aggregation
 :field_ref [:aggregation 0]}
{:base_type :type/Float
 :semantic_type :type/Score
 :settings nil
 :name "max"
 :display_name "Max of Rating"
 :source :aggregation
 :field_ref [:aggregation 1]}
```

Note that the names agree (eg, "sum") but the field_refs disagree: in the outer select we are dealing with `[:field "max" {:base-type :type/Float}]` and the inner select is `[:aggregation 1]`.

We can rely on name being unique, because if it is not, the query will fail anyways (`select name from (select 'bob' as name, 'steve' as name`). IE, the assumption might not be valid 100% of the time, but in the cases where it is invalid, the query will fail anyways.
