### ISSUE TITLE
Previous X hours date filter works unexpectedly on `DATE` column

### ISSUE THREAD

**Issue by kon901** [metabase/metabase#19554]
**Describe the bug**
Tested on Postgres data source.
Previous X hours date filter creates wrong date range.

**To Reproduce**
1. Today we have 2022-01-05T15:00:00
2. Pick Previous 30 Hours in Date FIlter on Native query question
3. Metabase will send date condition as: `where CAST("public"."test_table"."timestamp_column" AS date) BETWEEN '2022-01-04 09:00:00' AND '2022-01-05 15:00:00' `
4. Records with `timestamp_column` between `2022-01-04 09:00:00` and `2022-01-04 23:59:59` will not be returned (because of casting to `date` type)

**Expected behavior**
Records with `timestamp_column` between `2022-01-04 09:00:00` and `2022-01-04 23:59:59` should be returned

**Information about Metabase Installation:**

- Database: Postgres
- Metabase version: 0.41.5

**Comment by flamber** [comment]
Hi @kon901 
So if your column is actually a `DATE` type, then set the filter to Days, since the column doesn't have any information about lower granularity.
It would not be possible to return any records between `09:00:00` and `23:59:59`, since the database doesn't know. The only "time" it knows is `00:00:00`, so by requesting the last 30 hours at 15:00 will only return today's records.

**Comment by kon901** [comment]
Hi @flamber 
Thank you for quick response.
My column is `TIMESTAMP` type, so it contains time information.

**Comment by flamber** [comment]
@kon901 Okay, different problem then. Closing in favor of #17711
