### ISSUE TITLE
Asking questions with schemas generates "ERROR: permission denied for schema [...]"

### ISSUE THREAD

**Issue by aliekens** [metabase/metabase#1963]
When asking questions and working with schemas, questions constructed with the form seem to "forget" or "switch" schemas, resulting in an "ERROR: permission denied for schema [some other random schema in the DB] Position: 120" upon running the query.

**Comment by agilliland** [comment]
Can you provide an example of the question you are trying to execute?  What does your database schema look like?  and what database are you using?

The only reason you should be seeing that error is that you've attempted to access a resource that your database user doesn't have permissions to access.

**Comment by camsaul** [comment]
@aliekens To clarify, you're choosing one schema when you construct your query but it's referencing a different [random] one when the query is ran? Does this happen every time, right away, or after changing something else? Can you add a screenshot of your screen and possibly the output logs that show the SQL that gets generated?

**Comment by aliekens** [comment]
Here's a screenshot of a sample question that generates the error: 

<img width="1164" alt="screen shot 2016-02-24 at 14 03 45" src="https://cloud.githubusercontent.com/assets/973813/13286143/7e0c0d38-daff-11e5-9b55-7d61688a7b7f.png">

A bit of clarification: Each of our clients has its data in their own schema. In this question, I want to compute a total of all cashless transactions from a schema (here, from schema `tgs`). That runs fine, but when I want to define a filter from a join table (here, I only want transactions in a specific currency, with currencies in their own table in the same schema), metabase switches to a different schema to find the join table (here the (existing) schema `pbel` as in the error, but we've seen different schemas being selected with other questions, seemingly random).

**Comment by aliekens** [comment]
Note: We have this problem with every question that involves join tables.

**Comment by aliekens** [comment]
It appears Metabase is looking for the join table in all schemas, and selects the table from the first schema it encounters that has the table by this name. If the search for the table in schemas would prioritize the current schema of the question being asked, this bug would likely be gone.

**Comment by agilliland** [comment]
Hi @aliekens , just to confirm, so you have a database which has multiple schemas each with the exact same set of tables in them?  for example your database might have `schema1.table1`, `schema2.table1`, `schema3.table1`, etc?

Assuming that is the case, would you mind going to the `Data Model` page of the Admin Panel and looking at a few of your tables for me?  In specific, what I'm curious about is on the tables where you are experiencing this problem if you scan the table and find the columns which are marked as `Foreign Key` and just below them there is a dropdown which lets you pick the target column that is followed.  If you expand that dropdown do you see the same column names repeated many times (once for each schema you have?)

I believe that one possible explanation for your issue is that the definitions of your Foreign Keys are pointing to the columns in the wrong schema.

**Comment by zzip** [comment]
Hi @agilliland yes the schemas all have the same tables and structure. 
Basically we use the multiple schemas to accommodate multiple tenants.

Right now if we go to the Data Model page in the Admin Panel, i don't get any data.
When i check the JS console, i see an error, `error loading tables` right after page load and after 1 min i see another error with our nginx complaning the request timed out.

<img width="694" alt="screen shot 2016-02-24 at 22 32 41" src="https://cloud.githubusercontent.com/assets/23869/13303178/02f63e76-db4e-11e5-9465-e01a44500bc2.png">

We have been using Metabase, from before there was explicit support for schemas, maybe we need to clear some stale data in Metabase's own database?

**Comment by zzip** [comment]
After some more fiddling i changed the default nginx timeout to 180 seconds instead of 60 secs. 
The page now get's populated with results, although i still see a js error

<img width="1044" alt="screen shot 2016-02-24 at 23 27 42" src="https://cloud.githubusercontent.com/assets/23869/13303293/bae77e14-db4e-11e5-91f5-377a47a8a905.png">

the `/metadata` call took 100 seconds, and then +/- 1000 `query_metadata` requests are fired.

I managed to expand the dropdown you mentioned and can see the same Table -> Column repeated 50+ times, and the last one is selected. Which schema the referenced table was used is not shown. 
Another thing worth mentioning is that we currently have more schemas then we gave the Metabase postgres user access to.

<img width="966" alt="screen shot 2016-02-24 at 23 33 54" src="https://cloud.githubusercontent.com/assets/23869/13303430/ac4e46a2-db4f-11e5-8e8c-58436e053b82.png">

**Comment by aliekens** [comment]
With respect to the offered solution, if priority could be given to joining with the table in the current schema as the default, that would be very helpful.

**Comment by camsaul** [comment]
@agilliland did #2019 resolve this?

**Comment by agilliland** [comment]
not specifically.  it's likely that this issue is specific to aliekens and the fact that they started their Metabase instance before schemas were properly supported, so I am putting together a couple things to help them through cleaning that up and then I think this issue will be resolved.

**Comment by camsaul** [comment]
@aliekens are you still seeing this issue?

**Comment by camsaul** [comment]
@aliekens ?

**Comment by camsaul** [comment]
@aliekens ?

**Comment by camsaul** [comment]
@aliekens ?

**Comment by camsaul** [comment]
This was a legacy issue from before Metabase supported schemas; it was fixed going forward 7 or 8 months ago. I've reached out to @aliekens several times over the last few months to see if they could confirm that they're no longer seeing this problem, but haven't heard anything back, so I'm going to go ahead and close this out.

**Comment by espinosa** [comment]
Hi @camsaul, @agilliland, same problem here. I'm using 0.28.1 with 2 schemas containing same tables. The foreign key is pointing to the right schema.
Thanks for your help.
