### ISSUE TITLE
New BigQuery Driver clears out Dataset ID when visiting the admin page for existing databases

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19708]
1. Add a new database with the BigQuery Cloud SDK driver
2. Save database
3. Go back to that database details in the admin panel
4. The Dataset ID you entered previously is missing, and you have to re-enter it to be able to save.

I was trying to rename the database to make it easier to distinguish from another DB with the same name, and I had to figure out what the actual dataset name was in and enter it again in order to save it.

**Comment by flamber** [comment]
Looks like this is fixed with the new dataset selector. It's preserving the dataset I defined on master from yesterday.
Created the database, waited until it had done the sync in the database overview, then clicked back and it shows the dataset I entered
![image](https://user-images.githubusercontent.com/1447303/151163690-bf848053-0e9e-47fc-9b81-581331906e6a.png)
