### ISSUE TITLE
Cards / queries break and can't be modified if underlying column is removed

### ISSUE THREAD

**Issue by gincor** [metabase/metabase#1986]
Hi,

we modified some of our tables, moved around some columns etc. in our postgre db. We discovered that existing cards (correctly) now give us the error "ERROR: column abc.xyz does not exist Position: 123" - but we can't modify the query anymore, so we have to rebuild all the affected cards. Would be great if you could just modify queries that run into errors.

**Comment by agilliland** [comment]
I'll test this out, but I believe the underlying issue is that when loading up the card to modify it we are expecting information about the column to exist and it won't be there when the column (or table) has been removed from the database.

We can certainly find a way to deal with this better.

**Comment by tlrobinson** [comment]
@gerbus Are you still running into this on recent versions of Metabase? I tried reproducing it, and while it doesn't show the removed field names I'm still able to edit the query to remove them.

We should at least show something indicating the field is missing instead of a blank space, e.x. 
![screen shot 2016-11-14 at 11 43 18 am](https://cloud.githubusercontent.com/assets/18193/20280930/54b4beec-aa63-11e6-8ced-f4ceb34385c2.png)

**Comment by mazameli** [comment]
We don't have any record of what the field _was_ called, right? I think what you have in the comment is pretty good, Tom; it would just be preferable if we were able to give some additional context for the person trying to fix the card, e.g. `Missing field (User ID)`.

**Comment by tlrobinson** [comment]
@mazameli I think we keep track of removed columns, but currently the metadata endpoints don't return them, so this wouldn't be possible without backend changes. I'm inclined to go with the simple fix for now since it's easy.
