### ISSUE TITLE
Stacked area charts with series containing negative values look broken

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#19968]
**Describe the bug**
When a series of a stacked area chart contains a mix of positive and negative values it renders incorrect data: 

<img width="1541" alt="Screenshot 2022-01-27 at 00 13 04" src="https://user-images.githubusercontent.com/14301985/151268088-61f4a4a9-8eb3-4d20-b225-9456010b58f6.png">

**To Reproduce**
Query
```
select 1 as x, 100 as y1, 50 as y2
union all select 2, -100, 55
union all select 3, -1, 60
```

- Create a question with the query above
- Select Y2 as the first y-axis and Y1 as the second y-axis
- First Y1 series value should be 100, but it renders 150

**Comment by flamber** [comment]
I've change to this, so it's easier to reference:
```
select 'A' as x, 100 as y1, 50 as y2
union all select 'B', -100, 55
union all select 'C', -1, 60
```
The A is correct at 150, since it's stacked, so that would be 50+100 (y2+y1).
B and C are debatable, but we made a change to how negative values are shown, since it was wildly incorrect before #5763.

Am I misunderstanding something? How would you expect it to be shown?

**Comment by alxnddr** [comment]
@flamber, I thought we should either stack all series values or do not stack them at all, but it seems like we are stacking positive and negative values separately. Now I think that makes sense
<img width="1018" alt="Screenshot 2022-01-27 at 12 53 41" src="https://user-images.githubusercontent.com/14301985/151362738-b373c1bf-f0e8-4e92-9359-081f4e5a585c.png">
