### ISSUE TITLE
Connecting dashboard filters to cards can be difficult

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20048]
**Describe the bug**
The new filter options in 0.42 makes it more difficult to connect filters, since there's no indicators or help to understand what the underlying question filter type actually is and unless the correct dashboard filter type is chosen, then it will say "No valid fields".

**Example 1: Text variable**
1. Native query > Sample Dataset > `select {{text_variable}}` - **Text** variable type, save as Q1 and add to a dashboard
2. Only the "Dropdown" selection will allow connecting the filter to the card, but that's not obvious or logical, since no dropdown or search will be shown.
![image](https://user-images.githubusercontent.com/1447303/151694523-59641210-adc7-4e53-baec-50423ae46438.png)

**Example 2: Number**
1. Native query > Sample Dataset > `select {{number_variable}}` - **Number** variable type, save as Q1 and add to a dashboard
2. Only the "Equal to" selection will allow connecting the filter to the card, but that's not obvious.
![image](https://user-images.githubusercontent.com/1447303/159540781-7b79bf5b-fad5-442b-89f4-4196df850481.png)

**Example 3: Field Filter**
1. Native query > Sample Dataset > `select * from PRODUCTS where {{search}}` - Field Filter for Products.Category with **String contains** (imagine that someone else had created this question)
![image](https://user-images.githubusercontent.com/1447303/151694779-e05cb839-ce35-4664-9e52-f485c840e230.png)
3. Now try to add that question to a dashboard and create a filter for it - unless you select the correct type, the it will just be "No valid fields".
![image](https://user-images.githubusercontent.com/1447303/151694903-db8f89f4-34c8-4e86-b0ca-1cc3b9a17391.png)

**Information about your Metabase Installation:**
Tested "rc2" commit `a29860c`

**Additional context**
Field Filters are already complicated enough pre-42, where people didn't understand how to correctly get it to show a dropdown, so this will just make it even more complex.

Would likely be very helpful if it was possible to change the type #14296, but it should come with some constraints, since it's should not be possible to change to conflicting types for already connected cards, which was prevented to avoid correctness issues #16181.

There's a handful of related issues #11274 and https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+%22no+valid+fields%22

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by daltojohnso** [comment]
From both a code and UX sense the way we select dashboard filters just feels really awkward. Everywhere else in the app we start by selecting the field we want to filter on and then select the way in which we filter on said field (eg exact match, contains, etc.) and in a sense the "type" of filter that is selected is implicit: users don't really need to know that the `Product.Category` is semantically a `type/Category` type. No so in dashboardland; you need to pick `string/=` or `string/contains` first and then pick the fields that match that parameter type. I'm wondering if we can revisit parameter filters and make the parameter type more implicit from the perspective of the user, mainly by making the flow be field-first--you (the user) build a parameter widget by selecting a field in a question you want to filter on and then you pick the way in which you filter (=, contains, starts-with, etc.) in the sidebar.

I'm sure there are plenty of complications around this, especially from our letting the user create parameter widgets out of sets of different fields. But it is worth thinking about because we continue to encounter frustrating bits of complexity in dashboard parameters.

**Comment by adjenks** [comment]
To create a dropdown I had to change the field settings. After finally creating a dropdown for the question, I can't seem to also create it for the dashboard. There are no options that allow me to select the filter field that has a dropdown.

I set the field type to "Category".

Oddly, I was able to create the dropdown because I set the "Filter widget type" to nothing at all. I didn't set it and it worked. But if you set it, you cannot unset it, and it then stops giving me a list of options and instead just asks for text since it's set to "contains" or whatever.

**Comment by uladzimirdev** [comment]
implemented https://github.com/metabase/metabase/issues/41037

**Comment by ignacio-mb** [comment]
@uladzimirdev was this merged in 50?

**Comment by uladzimirdev** [comment]
> @uladzimirdev was this merged in 50?

Yes @ignacio-mb
