### ISSUE TITLE
Clean up existing schema for Favorites

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20525]
Rename them to be

`card_bookmark`
`dashboard_bookmark`

Unify columns:

Add `created_at` to `dashboard_bookmark`.
Remove `updated_at` from `card_bookmark`.

Update models to use new schema.

⚠️ Immediately backport changes to prevent pain when people switch branches.

**Comment by adam-james-v** [comment]
This is handled in #20790 as follows:

- app db tables for favorites are left alone. They still exist, but should be removed in a future release. This is done to keep backwards compatibility simple. so that switching between different release versions doesn't require strange migrations.
- 3 tables are added for bookmarks:
  - card_bookmark
  - collection_bookmark
  - dashboard_bookmark
- each of the 3 bookmark tables have the following columns:
  - id (unique within the table, but effectively unused)
  - user_id
  - item_id (where item is card, collection, or dashboard)
  - created_at

The 3 bookmark tables are done this way to enforce uniqueness constraints at the db level. We can union the tables with a query, and the relevant lookup effectively becomes a tuple of [:item :item_id] per user.
