### ISSUE TITLE
Static viz multi-series shows two Y-axis

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20559]
**Describe the bug**
Static viz multi-series shows two Y-axis.
Kinda a regression in 0.42.0, since 0.41.6 would just show a table, but at least there wasn't a correctness issue with that.

**To Reproduce**
1. Question > Sample > Products
2. Summarize Sum of Price, grouped by CreatedAt:Year and Category
![image](https://user-images.githubusercontent.com/1447303/154313283-0d318b23-1077-4c49-ade0-42f5f7812235.png)
3. Visualize and save question
![image](https://user-images.githubusercontent.com/1447303/154313352-8dc77c74-2046-4366-a840-3dc064ef82a8.png)
4. Not going to spend time on subscription, go to `/api/pulse/preview_card_png/:question_id`
![image](https://user-images.githubusercontent.com/1447303/154313185-c075aab9-9fb4-44e9-b4d5-e4c39e493c71.png)

**Expected behavior**
Follow Y-axis choices from normal visualization settings.

**Information about your Metabase Installation:**
Tested 0.41.6 and 0.42.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by losrebellos** [comment]
@flamber @howonlee 

- After checking the `png` render it seems that the `Doohickey` category is using the `left` side axis and all the other categories are using the `right` side axis.
- Based on the original `viz`, the correct axis should be the right side one

**Comment by losrebellos** [comment]
@howonlee

After some more debugging, the example is using a `combo-chart`/`LineAreaBarChart`.
The `options.series` needs to specify which axis the data belong to using `yAxisPosition` with `left` or `right`:
```json
"series": [
  {
    "name": "bar series 1",
    "color": "#88bf4d",
    "yAxisPosition": "left",
    "type": "bar",
    "data": [
      ...
    ],
  },
  ...
}
```

In the GH issue example, it seems that the series all have `"yAxisPosition": "right"` except for the first one. In that case, they should all have `"yAxisPosition": "left"`.

**Comment by Tony-metabase** [comment]
I just tested this on stats and still doesn't work. Reopening since the same replication steps apply

<img width="595" alt="image" src="https://user-images.githubusercontent.com/110378427/232499964-84e67078-a470-46b4-8435-1aa37718410f.png">

**Comment by Tony-metabase** [comment]
Any specific step you are getting stuck? Since same replication steps apply as the one flamber created ... 

So Step 1 ,create the following question:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/110378427/234026126-d6bb57c2-0079-40e9-abe4-8039407da056.png">

Step 2, set visualization as a Line and make sure the split is disabled

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/110378427/234026744-1873ee73-4d8f-4e2b-9009-030e2ad9e5e5.png">


Step 3, Add it to dashboard and send it to an email

<img width="701" alt="image" src="https://user-images.githubusercontent.com/110378427/234026423-b00b6679-f2a1-43b7-8217-cd6c2d94ce01.png">


You get split Y-axis which are not there in the question and are also disabled form the settings ... Anything not clear let me know

Happens both on 1.46.1 and `master`

**Comment by ylq5126** [comment]
@Tony-metabase Can Chromium or  Firefox be used to replace the existing solution?
