### ISSUE TITLE
Questions with Field Filter with widget type "None" will not show results

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#20643]
I had a field filter which was defined on a column that is all null (I had kept the column to populate it later).
This causes the following behavior on v42.1 (not sure about v42.0):

![mb issue](https://user-images.githubusercontent.com/15974735/154780570-6b64fdba-58aa-456a-b23f-8d5a0bbbf4c9.png)

This is also hard to notice, as the variables column is not open when you go to the card. So you see a card where it is not showing any result and the "play" but doesn't work.

Selecting one of the values from the 4 given options solved the issue.

v42.1

**Comment by flamber** [comment]
This is really not about null columns, but old dreaded "Filter widget type"=`None`, which happens when you have the Field Type set is "No semantic type" in Admin > Data Model, when creating the variable.

The strangeness goes back to the illogical functionality of "None" - historically #13825, but also related #11274 and #15963.

Even though it might be unlikely that many are using "None" on purpose, it's still breaking in an unhelpful way.

**Expected behavior**
1. Show results, just like we do in 0.41.6
2. It would be lovely if we completely ignore the "Category" type and always show all possible options (would close #11274).

**Reproduce:**
1. On 0.41.6: Admin > Data Model > Sample > Products > Category set Field Type to "No semantic type"
2. Native > Sample > `select count(*) from products where {{cat}}` - set as Field Filter of Products.Category, notice "Filter widget type" only has "None" option and no filter widget is displayed. Save the question and do a browser refresh to validate that it shows results.
![image](https://user-images.githubusercontent.com/1447303/154797320-93b030f0-0cd6-406e-af12-ed06631907d2.png)
3. Upgrade to 0.42: Go to the question - that's painfully unhelpful, specially if the user doesn't have SQL execute powers.
![image](https://user-images.githubusercontent.com/1447303/154797597-d8835efd-5d96-4ff4-9f03-c82bdce81f5e.png)
4. Opening the variable sidebar shows 4 options, not 6:
![image](https://user-images.githubusercontent.com/1447303/154798285-af8b7295-b79f-4aad-bae2-533a7cd1d39e.png)
5. Admin > Data Model > Sample > Products > Category set Field Type to "Category"
Refresh the question - it will still not show results, but it will now have 6 options in the sidebar:
![image](https://user-images.githubusercontent.com/1447303/154798325-73964866-3a7e-47bd-9b0e-c720e1ceaf03.png)
