### ISSUE TITLE
saving site url as an environment variable, it is not updated in the UI accordingly

### ISSUE THREAD

**Issue by AgentBlond** [metabase/metabase#20773]
**Describe the bug**
Site url is saved as environmental variable but is not saved in the UI. We need this for our documentation tool secoda.

We updated it.
<img width="1325" alt="Screenshot 2022-02-28 at 13 57 42" src="https://user-images.githubusercontent.com/22956171/156135951-9f966ef9-c143-4774-a0de-cbd1ba9b87e8.png">

Metabase gave us the right response:
<img width="440" alt="Screenshot 2022-02-28 at 14 19 05" src="https://user-images.githubusercontent.com/22956171/156136345-1cfe8839-488b-4f41-8bce-2e1d064aa338.png">

But in the ui it hasn't been updated.
![image (6)](https://user-images.githubusercontent.com/22956171/156137744-fba17aa6-9f28-4e16-bd75-382e0e5d0118.png)

**Expected behavior**
Site url should be populated with the right url.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: Mac OS Big Sur
- Metabase version: 1.42.1
- Metabase hosting environment: [docker.io/metabase/metabase-enterprise@sha256:9d3f4f62233a923db7e8c6f1801d6a34e352b3216ff45a6bda6a53550170651b](http://docker.io/metabase/metabase-enterprise@sha256:9d3f4f62233a923db7e8c6f1801d6a34e352b3216ff45a6bda6a53550170651b)
- Metabase internal database: mysql 8.0

**Severity**
We implemented a temporary fix but would be nice, if this issue gets resolved.

**Comment by flamber** [comment]
Hi @AgentBlond 
Ignore the UI. It is using the correct Site URL from the environment variable.

**Comment by camsaul** [comment]
It's by design that we don't show the actual value in the UI for Settings configured by env vars -- this way if they're potentially sensitive things like SMTP passwords they aren't accidentally leaked. 

For whoever ends up fixing this: we return an `is_env_value` key or something like that in the endpoint that returns Setting values, so all we should need to do here is check that key and adjust the UI accordingly if it's truthy. I think elsewhere we're graying the box out and hovering over it shows a popover that says "this value is set by environment variable" or something like that
