### ISSUE TITLE
Check for Card database_id / table_id before calling related endpoints

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2087]
These properties are both nullable.

I have a Card on my machine with a `NULL` `database_id` (not sure why) and [this code](https://github.com/metabase/metabase/blob/master/frontend/src/card/card.controllers.js#L557-L566) attempts to fetch the tables for the DB which ends up being a call to a non-existent endpoint:

![screen shot 2016-03-04 at 12 10 20 pm](https://cloud.githubusercontent.com/assets/1455846/13538942/1a024988-e202-11e5-8b50-415686715f1c.png)

Ideally we should check that these properties are non-nil before making the call at all. Some other questions this brings up:
-  _Should_ `database_id` and `table_id` be nullable?
-  Does a card need `database_id` _and_ `table_id`? Couldn't it just have `table_id` since tables belong to databases?
-  Do we _need_ to fetch the full list of Tables for the Database in question when rendering a Card? It seems like we'd only need that if someone was going to edit the card and change the table (basically, reset the card). Otherwise seems a bit superfluous

**Comment by agilliland** [comment]
I can fill in a few blanks.

* these properties didn't used to exist previously and were added in so that we could do relational queries to find out things like what cards come from table XYZ.  previously this data was purely stored in the JSON dataset_query.
* they are nullable due to database upgrade trickiness where adding a non-null column to an existing table doesn't work.
* i can't think of a reason why database_id would be null, that could be a bug of some sort if you are seeing it.
* table_id can definitely be null, mainly for SQL cards.  hence, why there are 2 separate fields.
* we use the list of tables in a database quite a lot in the QB because pretty much every widget requires some knowledge of what tables/fields are available for use.  it's possible we could reposition that code, but in general it makes sense that when the database changes we load up the set of tables.

**Comment by camsaul** [comment]
Ok. I guess the reasoning behind the columns makes sense.

It would still have been nice to have added a non-null constraint for `database_id`. We could have just created a temp DB object and set its ID as the `database_id` for every Card, added the constraint, then set the correct ID in a data migration. All the cards that still had the temp DB's ID we know would be broken (probably orphaned when their DB was deleted) and we could either cascade delete them or try to magically un-break them somehow. 

If every widget requires knowledge of which *Fields* are available, why do we need to fetch all the other *Tables*? Seems to me like a Card just needs its own Table and not every Table in the DB unless someone tries to change the Table. Keep in mind this call could be pretty expensive for someone with a DB with lots of schemas and tables. It's an easy performance win to cut out unnecessary expensive API calls and I would think most of the time when someone looks at a card they aren't planning on switching the Table it belongs to, if they edit it at all.

**Comment by agilliland** [comment]
The reason is because the tables are relational for most of the dbs we support.  So just because a card starts from Table A doesn't mean it only needs Table A when being used in the QB, it often needs various other tables which it can be joined to.  Currently that information is compiled and reconciled on the frontend, so the app pulls all tables in the db and then builds a complete model of how they relate to each other.

Regardless, there is always room for some improvement and we've been more focused on just making things work in the early stages of the product development.  As the product matures and the capabilities of the application stabilize it's natural to start tuning for performance more and more.

**Comment by flamber** [comment]
Closing, since a lot has changed, but report_card.database_id cannot be null anymore - #5999
