### ISSUE TITLE
The scalar visualization-type should scale the font-size properly

### ISSUE THREAD

**Issue by MrMauricioLeite** [metabase/metabase#2125]
Whe using the number card-type and resizing the card on a Dashboard the inner value should fill the container. I attached ugly examples, but useful (dummy data).

today we have:
![bugreport](https://cloud.githubusercontent.com/assets/1953457/13656501/4991ba56-e646-11e5-942b-268c34eadaeb.PNG)

I think the better idea is:
![bugreport - copia](https://cloud.githubusercontent.com/assets/1953457/13656504/52d27a1a-e646-11e5-9d8a-3f07bcb8cdb7.PNG)

**Comment by kdoh** [comment]
Hey @MrMauricioLeite. Thanks for the feedback. We agree! We're actually working on a version of this as part of our 0.16 release right now.

**Comment by MrMauricioLeite** [comment]
Awesome guys. 

Keep up with the great work. I look forward to use metabase on production. =)

**Comment by tlrobinson** [comment]
This will be resolved by #2103.

However, we don't have it scale quite as large as what you proposed. I'm wondering if the card fills the entire width of a dashboard we should have the text scale to fill the entire card (minus some padding), since in that case it would be pretty clear the user wants it as big as possible. @kdoh?

**Comment by MrMauricioLeite** [comment]
If it fills the entire width like my example it would be awesome to use this dashboard on a talevision somewhere in the office. A huge number to be seen from far.

**Comment by cagiraudo** [comment]
Hi,

I still don't see this bug resolved. I am using the v0.17
