### ISSUE TITLE
Cannot paste multiple values into filters

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#21385]
**Describe the bug**
After update to v.42, copy and paste multiple values on filter are not allowed and comeback to select column

**To Reproduce**
1. Select a filter column
2. paste a multiple value text

**Expected behavior**

**Screenshots**
![Screenshot from 2022-03-31 11-58-27](https://user-images.githubusercontent.com/6808348/161086253-36b6a4e5-c9bb-4fd6-8a46-23942185b2a8.png)

![Screenshot from 2022-03-31 11-58-34](https://user-images.githubusercontent.com/6808348/161086266-51e03f36-29a4-4205-9e82-70bf2f841b7d.png)

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_321-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_321",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.321-b07",
    "os.name": "Linux",
    "os.version": "5.10.0-9-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "cubejs",
      "mysql",
      "postgres",
      "sqlserver",
      "googleanalytics",
      "athena",
      "bigquery",
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.42.1",
      "date": "2022-02-17",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by losrebellos** [comment]
@flamber @mazameli 
Not sure if this is something we want to "fix" as it seems there is some functionalities changes since the previous version.

__Before__

The input was used as a search field __and__ to list the selected categories, hence the ability to copy/paste multiple items in it.
Note that it would also add categories from the pasted text if not present in the list.

https://user-images.githubusercontent.com/348552/163571463-3a95dfed-3cb3-4510-a610-f0bf2c08bee2.mp4

__Current__

In the new version:
- the input is working only as a proper `search field`, used to filter items from the list below
- and the selected tags/categories won't appear anymore in the input once selected
- as the tags/categories list has checkboxes left-side of each items to actually select them

![image](https://user-images.githubusercontent.com/348552/163571670-6c90b213-f0f9-4dab-82e3-9ab78448f5cb.png)

![image](https://user-images.githubusercontent.com/348552/163571773-593f19d7-4727-4784-b80f-f969494c8154.png)

![image](https://user-images.githubusercontent.com/348552/163571699-84d472c4-4106-4764-a313-7cba77b44ef0.png)

**Comment by dannyeuu** [comment]
I saw that you can choose this behavior on Data Model Setting on field setting:
![Screenshot from 2022-12-12 13-17-12](https://user-images.githubusercontent.com/6808348/207097122-8c597f85-72d1-4ed4-a6c7-bea7b7f55328.png)

PS: sorry for the print in pt_BR.

**Comment by flamber** [comment]
@dannyeuu That's great if that's a workaround for you, but it might not be for others. Re-opening.
You are showing a screenshot of this https://www.metabase.com/docs/latest/data-modeling/metadata-editing#picking-the-filter-user-interface-for-a-column

**Comment by jonayreyes** [comment]
Completely broke a whole department's workflow in v0.49.0 ![image](https://github.com/metabase/metabase/assets/2834790/08fe9b23-8582-4c00-b761-86a4db9e7e99)

**Comment by sutyy** [comment]
I agree with comment from @jonayreyes. Our users want to filter based on copy-past from other systems which is impossible now. Also workaround mentioned by @dannyeuu is not available for us.

**Comment by darksciencebase** [comment]
is this https://github.com/metabase/metabase/issues/40265? if so, the fix has just been released in 49.1.

**Comment by hss-iullah** [comment]
Hi this still doesn't appear to work. If I copy and paste a batch of cells fom CSV/Excel/G.Sheet, only the last cell pasted returns a result. All cells / value before appear to be getting a CRLF added to the end which seems to be causing the issue. When I fire the SQL created by MB, it's definitely adding a CR to the end of each value. 
Oddly, if I copy and paste the cells which someone has sent to me via Teams, it works.

**Comment by paoliniluis** [comment]
@hss-iullah please post in https://github.com/metabase/metabase/issues/40265
