### ISSUE TITLE
Compute results of timestamp/current-date functions during query processing

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#21518]
**Is your feature request related to a problem? Please describe.**

A customer reported that as the GETDATE function is evaluated at query time, so it'll evade Redshift caching. This is documented on [Redshift performance tips](https://docs.aws.amazon.com/redshift/latest/dg/c_challenges_achieving_high_performance_queries.html).

**Describe the solution you'd like**

Calculate as much as possible at the app level rather than at the DB level in Redshift

**Describe alternatives you've considered**

None, unless you want to use text as filters for dates

**How important is this feature to you?**

Very important for Redshift users

**Additional context**

Reported by one of our customers
We should fix this for all databases, so we can close #20988 too.

**Comment by camsaul** [comment]
I think this is by design.

If someone writes a query like "sales over the 24 hours", we have to use something like `getDate()` to get the current moment in time to compare against. "sales over the last 24 hours" changes every time you run the query. Not caching those results makes sense to me, since `getDate()` **is** supposed to be computed at query run time/

How else would this actually work for these sorts of queries? If there's an alternative I'm missing that doesn't bust the cache please let me know. But the only alternative I can really think of off the top of my head is either use the Metabase caching mechanism. Or just don't run these types of queries, which is not really a real solution.

**Comment by paoliniluis** [comment]
Agree with you @camsaul that for certain queries a getDate() makes sense (like gimme the orders from the last 24 hours, the hour/minute is dynamic and there won't be any caching there), but check the following: orders from last week (you can use any redshift from stats and any dataset with a similar query), this is the query that gets generated
```
WHERE ("public"."activity"."timestamp" >= (CAST(date_trunc('week', (dateadd('week', -1, CAST(getdate() AS timestamp)) + (INTERVAL '1 day'))) AS timestamp) + (INTERVAL '-1 day'))
   AND "public"."activity"."timestamp" < (CAST(date_trunc('week', (CAST(getdate() AS timestamp) + (INTERVAL '1 day'))) AS timestamp) + (INTERVAL '-1 day')))
```
There, getDate() is used to get a fixed date (the last day of last week). That value won't change for the entire week that query is fired, and we're busting the cache simply by using runtime query functions.

There are many other examples like this one, (previous x months, next year, etc), so I think that using these functions is causing more harm than good?

**Comment by luizarakaki** [comment]
@camsaul During query processing, do we know if `GETDATE()` is used as a `timestamp` or `date`? In most cases, we need `GETDATE()` at the `day` precision.

If during processing we know this, we could use a date literal (`2023-02-07`, calculated in our backend and timezone aware) instead of `GETDATE()`. This would make caching work.

**Comment by camsaul** [comment]
yes we do

**Comment by lbrdnk** [comment]
Reopening I was unable to resolve UTC night failures, that popped up after the merge, by now. More context can be found in [this slack thead](https://metaboat.slack.com/archives/C5XHN8GLW/p1702332392764369?thread_ts=1701772468.810829&cid=C5XHN8GLW).
