### ISSUE TITLE
Slack preview image showing another image in some cases when using Subscriptions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21608]
**Describe the bug**
Subscription Slack images are showing the incorrect image, when opening the image in larger preview modal.
Regressions since the new Slack image implementation in 0.41.0

**To Reproduce**
1. Native > Sample > `select 1` - change viz to Table, save question as "Q1"
2. Native > Sample > `select 2` - change viz to Table, save question as "Q2"
3. Add "Q1" and "Q2" to dashboard and save dashboard
4. Go to Subscription > Slack > select a channel and "Send to Slack now"
![image](https://user-images.githubusercontent.com/1447303/162922009-e51cc802-b395-40e1-8bd6-2221cf0a93f1.png)
5. The received message looks correct
![image](https://user-images.githubusercontent.com/1447303/162922209-ece41892-6aa0-4965-9c2c-e2cf96f7a14d.png)
6. Now click the **first** image (1) to view it larger in a modal - it shows the **second** image (2)
![image](https://user-images.githubusercontent.com/1447303/162922859-18604a67-e8f3-42e3-93d7-8595f3d5f8c2.png)

**Information about your Metabase Installation:**
Only tested 0.42.4, because of deprecation, so it would be difficult to test previous versions.

**Comment by noahmoss** [comment]
I'm fairly sure this is a Slack bug, not a Metabase bug. I'll see if there's any way to verify, though.

**Comment by noahmoss** [comment]
Okay, this does seem to be a Slack bug. We're using [secondary attachments](https://api.slack.com/messaging/composing/layouts#building-attachments) for subscription message content, with nested `blocks` arrays for the non-dashboard content like the message header and footer. This bug only appears when a nested `blocks` array appears before the images.

Here's a way to reproduce independently of Metabase:

1. Go to https://api.slack.com/methods/chat.postMessage/test and paste in a Slack OAuth token (the same kind of token that would be used for Metabase).
2. Input the name of a channel to send a test message
3. Paste the following into the `Attachments` field, then click `Test method`. When you view the sent message, you should see the buggy behavior.

```
[
  {
    "blocks": [
      {
        "type": "header",
        "text": {
          "type": "plain_text",
          "text": "Slack Test",
          "emoji": true
        }
      }
    ]
  },
  {
    "title": "Test 1",
    "image_url": "https://i.picsum.photos/id/487/200/300.jpg?hmac=jDYxTxKFMi18Gu5h9qt9ttwJKCk1-J6bZeHDtXGL2Vk"
  },
  {
    "title": "Test 2",
    "image_url": "https://i.picsum.photos/id/72/200/300.jpg?hmac=8tyK7lgBqIQNIGPVnmsVP3SL5bYCsSDmdZtnIJNQv3o"
  }
]
```

4. Send a new message with the following in the `Attachment` field. (This is the same as above, but with the `blocks` array removed from the JSON). You should no longer see the buggy behavior.

```
[
  {
    "title": "Test 1",
    "image_url": "https://i.picsum.photos/id/487/200/300.jpg?hmac=jDYxTxKFMi18Gu5h9qt9ttwJKCk1-J6bZeHDtXGL2Vk"
  },
  {
    "title": "Test 2",
    "image_url": "https://i.picsum.photos/id/72/200/300.jpg?hmac=8tyK7lgBqIQNIGPVnmsVP3SL5bYCsSDmdZtnIJNQv3o"
  }
]
```

The secondary attachments mechanism in the Slack API is apparently a legacy (but not deprecated) mechanism, so this seems to be a real bug on their end but they might not be in a rush to fix it.

Nevertheless we can probably fix it by migrating to using blocks at the top level, for all parts of the dashboard subscription message. I think there used to be some blockers to doing this but I don't remember offhand exactly what they were.

**Comment by noahmoss** [comment]
OK, I've done a bit more experimentation. It seems that image URLs in `blocks` must be fully public, or else the `chat.postMessage` API call will fail with an error like `downloading image failed [json-pointer:/blocks/8/image_url]`. This seems to be an intentional restriction and is explicitly called out [in this comment](https://github.com/slackapi/bolt-js/issues/1278#issuecomment-1019000233). However, for some reason, images in `attachments` do not have this same restriction, which is what we're currently leveraging for dashboard subscriptions.

So the only way to make dashboard subscriptions work with `blocks` would be to generate a public URL for each image, either using Slack's [files.sharedPublicURL](https://api.slack.com/methods/files.sharedPublicURL) API or by some other method, and using these URLs in the message. But this would mean that these images could be accessed by anyone with the URL, not just members of the Slack workspace. We'd have to think carefully about the privacy risks involved in doing that. 

For now, I'll mark this issue as a limitation. (I did reach out to Slack support on Twitter and they said they've repro'd this and filed a bug, so there's a chance it'll be fixed eventually without our intervention.)

**Comment by safvanplp** [comment]
@noahmoss Do we get any updates from the Slack team on this bug?

**Comment by noahmoss** [comment]
@safvanplp No, unfortunately

**Comment by safvanplp** [comment]
This seems to be resolved now. I have tested it both on Mac and Windows. It is showing same image only when clicking on the card.

**Comment by flamber** [comment]
@safvanplp Thanks for testing. Confirmed it works correctly now, even for older notifications, so it was fixed internally in Slack.
