### ISSUE TITLE
We should display joined Saved Question in Query Builder rather than `Question <id>`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#21646]
Example:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/1455846/163092107-df56a1c3-4adf-46bd-8c8c-53f50b07ca06.png">

`Question 4498` in this case is the Saved Question I'm joining against (I think) altho I'm also starting from a Saved Question so that's not entirely clear. We should show the actual name of the Saved Question instead of just `Question <id>` which is pretty much meaningless

**Comment by flamber** [comment]
That would be very useful, but might get a little problematic with long question names to make them fit nicely.
But isn't the information shown in the frontend retrieved from the backend results dataset.rows.display_name/source_alias?
![image](https://user-images.githubusercontent.com/1447303/163120617-30df8555-517d-40a6-8f2d-d04d9b7b8e59.png)

Related to #10551 and #12930

**Comment by iethree** [comment]
This is particularly problematic in areas like Audit where we only expose data via models, not the raw tables, so the question number rather than the name appears for all non-source table joins. It serious hinders the usability of both filters and aggregations.

This goes back to at least v44, and probably has never been supported.

![Screen Shot 2023-10-17 at 3 01 58 PM](https://github.com/metabase/metabase/assets/30528226/199207a5-abab-47e0-9d35-9195abc5da77)
![Screen Shot 2023-10-17 at 3 01 52 PM](https://github.com/metabase/metabase/assets/30528226/7d6267c1-6e36-4f74-99d5-9218782fba67)

**Comment by camsaul** [comment]
I think the issue here is that MLv2 doesn't have the Card metadata and falls back to `Question <id>`, if you give it the Card metadata then this should work
