### ISSUE TITLE
New chart type: horizontal bar chart / row chart

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#2167]
How about adding a horizontal bars chart? It's useful for longer label text. E.g.

![ekran goruntusu 2016 03 16 21_00_04](https://cloud.githubusercontent.com/assets/844008/13825248/5efbe104-ebba-11e5-9ffe-cd584b761c39.png)

**Comment by MrMauricioLeite** [comment]
+1

They are visible if you add a bar chart question to a pulse and receives it via e-mail, the preview on e-mail uses horizontal instead of vertical bars, but I really want to have this option on dashboards

**Comment by kdoh** [comment]
Hey @maliayas @MrMauricioLeite. Would be interested to get  a sense of the kind of cases where horizontal vs vertical bars are most useful to you.

**Comment by maliayas** [comment]
For my case, the biggest advantage is being able to have more place for labels. For vertical bars, there is very little space for label text.

**Comment by kdoh** [comment]
Gotcha. So it sounds like it'd be more of a case by case editorial decision on your part vs fitting a common data set or shape? Very useful to know!

**Comment by maliayas** [comment]
Another benefit is being able to have a lot more bars as there is no vertical limit. You're right, it's about editorial comfort. Thanks for listening.

**Comment by MrMauricioLeite** [comment]
Sure @kdoh but I'm afraid it depend mostly on what the user is used to use. Don't you think? 

Here we always work with horizontal bar charts when we are comparing (for example) total sales by manager. We like this visualization because it resembles progress bars and we sort from by value.

In other hand, when we are comparing the same data with two timespans, like (for example) total revenue by department - last year to date vs current year to date we are used to have a vertical column chart.

Well, it's just a suggestion, feel free to ignore it.

**Comment by kdoh** [comment]
@MrMauricioLeite Thanks for adding a couple more example us cases.

**Comment by louis-eyond** [comment]
+1
Usage for us would also be longer labels on the Y-axis, specifically customer names, vendor names, market segments and other types of text that get squished on the X-axis labels currently.  Note that vertical (slanted) text as an option for the X-axis labels may also meet the same challenge, though personally I would prefer the horizontal bars chart option.

**Comment by federicokeen** [comment]
+1. We have many bars as well for some charts and this would help

**Comment by machupichu** [comment]
+1 on it, would be very useful for long labels.

**Comment by devaxel** [comment]
+1
Metabase is awesome. Great Job. 
But I really miss the horizontal bar chart type. Usually it is an essential chart type, because it is the only one that makes sense to visualize data with long label titles. Would be great to add this in future releases.

**Comment by romone22** [comment]
+1 
Quite indispensable to compare performances without any timeseries.

**Comment by tlrobinson** [comment]
I looked into this and dc.js does have a "row chart" https://dc-js.github.io/dc.js/examples/row.html but it's not as full-featured as the regular bar chart (mainly no stacking, so no multi-series). Also, the Y axis labels appear inside the bars rather than to the left of the axis (might be able hack around that)

If we're ok with that, then this should be an easy one to implement. I've got a prototype working:

![screenshot 2017-02-03 15 15 28](https://cloud.githubusercontent.com/assets/18193/22613429/1c91f304-ea2d-11e6-9d35-a8f8c6a80264.png)

**Comment by maliayas** [comment]
Thanks for the solution.

> Also, the Y axis labels appear inside the bars rather than to the left of the axis (might be able hack around that)

Does it look fine with long y axis labels?
