### ISSUE TITLE
View Detail on Foreign Key does not work when targeting an item outside the first 2000 rows

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#21756]
**Describe the bug**
When clicking "view detail" on a foreign key - if it is not in the first 2000 rows of the table, it will give the user a not found message.

Because of the nature of the bug, I don't think it's reproducible with the sample DB.

**Logs**

(nothing material)

**To Reproduce**
1. Go to a table with more than 2000 foreign keys defined
2. Click on a foreign key (that's not in the first 2000 rows of the table) and select "View Details"
3. Instead of seeing the object's details, you will get a "we're a little lost" error

**Expected behavior**
The user should see the detail view of the object selected

**Screenshots**

https://user-images.githubusercontent.com/30528226/164040471-68409750-8641-4d3e-b452-65741ce339f0.mp4

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Google Chrome Version 100.0.4896.127 (Official Build) (64-bit) 
- Your operating system: Ubutntu 20.04
- Your databases: Postgres 14.2
- Metabase version: master branch - 2022-04-19 - v0.42.1-SNAPSHOT"
- Metabase hosting environment: local development
- Metabase internal database: H2

**Severity**

Makes foreign-key object detail view useless for most large tables.

**Comment by flamber** [comment]
Regression in 43 since #20101 @kulyk 

P1 contender.

**Reproduce 1 - problematic**
1. Question > Sample > Orders
2. Filter ID - input `2` and `18000`
![image](https://user-images.githubusercontent.com/1447303/164684893-34a936b4-6a8c-4f3e-8ddb-1a80184d880e.png)
3. Click User_ID=2392 > View details
![image](https://user-images.githubusercontent.com/1447303/164685184-d9b73765-d02e-4d12-b0d3-d54f41f42676.png)
4. `We're a little lost...`
![image](https://user-images.githubusercontent.com/1447303/164689109-64e17733-7a17-46f3-9568-5b9864915799.png)

**Reproduce 2 - less problematic**
1. Question > Sample > Orders - save as "Q1"
2. Add to dashboard and create Dropdown filter connected to Products.Category
3. Filter by `Doohickey` and click question title
![image](https://user-images.githubusercontent.com/1447303/164687286-8789e1d0-9b11-4960-8392-d72d6fa53142.png)
4. On the question, it shows a table with everything correct - and clicking ID=6 will show "Previously" correctly disabled
![image](https://user-images.githubusercontent.com/1447303/164688036-fb89fdb6-4ba5-4637-8e7f-d79da6f19a1e.png)
5. Go back to the dashboard and filter by `Doohickey` and click ID=6
![image](https://user-images.githubusercontent.com/1447303/164688251-ddacb016-a237-44e2-8900-a643b7e93dc4.png)
6. Show Object Details with "Previous" enabled, which is incorrect
![image](https://user-images.githubusercontent.com/1447303/164688609-69ff7b27-d906-4cd5-a057-2fbfec098145.png)

**Comment by ranquild** [comment]
After spending a few hours on trying different approaches I believe that the correct way to fix this is to refactor the detailed view to load data for the selected entity and NOT use data from the active query. This would allow opening the view within a query for related entities without loading another table.

**Comment by mazameli** [comment]
@ranquild I'm not sure how to unblock you. Questions:

1. What is the user-facing/UX consequenc(es) of "refactor the detailed view to load data for the selected entity and DO NOT use data from the active query", if any?
2. How long do you think this proposed refactor would take? Does @flamber et al think this needs to block 0.43?
3. Does @kulyk have any thoughts that could help?

**Comment by ranquild** [comment]
@mazameli If we change the object details view in this way we would not navigate to a different table when browsing details. We could make `Up` and `Down` buttons work by navigating between results in the current dataset.

**Comment by ranquild** [comment]
fyi @kulyk @flamber @mazameli an easy fix would be to add a primary key filter when navigating to another table. E.g. when clicking on `User ID` in `Orders` table we currently open `People` without filters and fail when there is no selected entity. But we could open the table with a filter for the primary key and it won't fail.
