### ISSUE TITLE
Improve organization and filtering of saved questions

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2204]

**Comment by agilliland** [comment]
Includes addressing #1875 , #1818 , #1273

**Comment by kdoh** [comment]
to give a bit of a preview of what we're thinking here:
![saved_questions_all](https://cloud.githubusercontent.com/assets/5248953/14006033/21a8ede4-f126-11e5-8156-3f26fccfd2b2.png)

# labels
you know your business better than we do, so we want to give you the ability to group saved questions in the way that makes the most sense for you. add labels for marketing, quarters, specific teams, your spirit animal, you do you.

![labels](https://cloud.githubusercontent.com/assets/5248953/14006032/21a8b3ec-f126-11e5-8ddc-d3f4d31c6050.png)

and since we’re living in the #slack era, of course you can change the label to the emoji of your choosing.

# favorites
we all have different needs from our company’s data and chances are you work with the same data frequently. in our proposed update you can mark any question as a favorite so you never have to work to hunt it down.

# archive questions
your data needs change as your business changes, but that doesn’t mean you need to get rid of old questions forever. archiving questions lets you keep your list of questions trim and up to date without having to worry about losing any of your previous work.

# recents
![recently_viewed](https://cloud.githubusercontent.com/assets/5248953/14006034/21aa58f0-f126-11e5-9a15-bb2cc39f40c6.png)

Metabase already surfaces recently viewed questions and dashboards on the activity feed when you login, but a dedicated recents tab for questions means you never have to work too hard to find the question you know you were looking at the other day

# popular questions
it’s important to know what data people care about across your team. the popular tab surfaces questions that have been viewed the most across your entire company so you can get a sense of what data is resonating most.

# topics
![topics](https://cloud.githubusercontent.com/assets/5248953/14006055/731addae-f126-11e5-8f77-93fce021812d.png)

one of our principles is that you shouldn’t have to provide info to Metabase that Metabase should be able to infer. topics is an attempt to help surface questions related to the different parts of your business. right now its simple and looks at which tables have the most questions (> 5) asked against them, but over time it’ll expand as Metabase’s knowledge of your business expands.


all of this is on top of a greatly simplified design for saved question items themselves and a search filter for each section.
![saved_questions](https://cloud.githubusercontent.com/assets/5248953/14006058/7ec5835c-f126-11e5-8732-b75e12672725.png)


we hope these proposed changes will give those of you using Metabase across large teams, or those of you just starting out better tools to keep your data organized and make sure everyone is on the same page.

please give us feedback on these concepts and the designs and as always, thanks so much for using Metabase.

**Comment by kdoh** [comment]
@snarfed would be particularly interested to get your thoughts on this direction if you have a second to take a look.

**Comment by snarfed** [comment]
whoa, looks great! this would definitely be a big addition. i like it. I've pinged our internal users, so they may weigh in too.

**Comment by MrMauricioLeite** [comment]
Congratulation @kdoh and @agilliland 
This definitely made my day. Really beautiful design and useful features.

**Comment by Addvilz** [comment]
Can not emphasize enough how much we need this. We are now using Metabase in production to also pass on qestions and data from tickets for business intelligence - and that's a lot of questions. We really need a way to organize this.

**Comment by mazameli** [comment]
@Addvilz glad to hear this will scratch an itch, and glad to hear you're using Metabase in production. This feature is part of our 0.17 milestone, which is scheduled for April 26, so you can look forward to that.

If you or your team have any additional feedback, please don't hesitate to reach out to me directly.
