### ISSUE TITLE
Permission graph does not support schemas with slashes

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#22047]
**Describe the bug**
Schemas like `special_/_#_%_'__._&_>_:_ _end` can't be added to the permissions graph because they got trimmed:

Metadata request contains the correct schema name starting with `special_/`
<img width="732" alt="Screenshot 2022-04-26 at 01 54 05" src="https://user-images.githubusercontent.com/14301985/165181905-f23ef5be-5867-40ad-8b92-24628e95fdf1.png">

Permissions graph returns a trimmed name
<img width="749" alt="Screenshot 2022-04-26 at 01 54 26" src="https://user-images.githubusercontent.com/14301985/165181980-6ab8ee22-01bf-48c1-b50e-ad34c7e5261e.png">

**To Reproduce**
1. Connect a database with a schema called `special_/_#_%_'__._&_>_:_ _end`
2. Go to the permissions page and try setting data permissions for the schema

**Expected behavior**
Permissions graph contains full schema names

**Information about your Metabase Installation:**
Latest master

**Comment by qnkhuat** [comment]
I'm fixing this in https://github.com/metabase/metabase/pull/22090

But I also found a bug in FE when I change Permissions Data Access Permission to Granular of a scheme with special characters, FE it'll fail because the schema name is not encoded.

Reproduce:
1. Connect a database with a schema called `special_/_#_%_'__._&_>_:_ _end`
2. Go to Admin -> Permissions -> Data
3. Change Permissions of schema `special_/_#_%_'__._&_>_:_ _end` to Granular


https://user-images.githubusercontent.com/25661381/165533557-4471b21b-1c85-4291-b5a8-fee97a04b890.mov

**Comment by qnkhuat** [comment]
Reopen since we still have a bug in FE

**Comment by flamber** [comment]
@alxnddr I think you can quickly fix this, since its likely very similar to the other FE fixes you did.
