### ISSUE TITLE
Cancel query after timeout

### ISSUE THREAD

**Issue by cwelton** [metabase/metabase#22430]
**Is your feature request related to a problem? Please describe.**

- For charts with long running queries metabase can timeout with "There was a problem displaying this chart.", after which it will never display the results of the query if it were to complete. 
- On a reload of a page a query can be re-issued even when a copy of the query was already running

In both these scenarios long running queries that will never be presented back to a user will be taking up query load and capacity within the database.

**Describe the solution you'd like**
When the results of a query will never be displayed, for the above listed reasons or potentially others, metabase should cancel the query so that the database can free up those resources.

**Describe alternatives you've considered**
- Rewriting slow queries obviously helps, but doesn't prevent one user from substantially impacting another
- Putting resource limits on queries can help, but there are limitations in that regard as well:  https://github.com/metabase/metabase/issues/22421

**How important is this feature to you?**
While we can live without it, it requires additional scripting to identify long running queries and kill them through other means.  This has the downside that we don't actually know if the results would eventually have been displayed so is a less ideal solution than having the awareness built into the dashboard.

**Additional context**
We are using the bigquery adaptor

**Comment by flamber** [comment]
Hi @cwelton 

That sounds like a bug. Please post "Diagnostic Info" from Admin > Troubleshooting.
Without seeing the full stacktraces, then it's not possible to understand fully what is going on.

Metabase should cancel the query (or at least close the database connection, so the db should handle it).
Cancelling queries can be tricky depending on the database, but Metabase tries to do it on BigQuery in the new driver #17959.
BigQuery can be difficult to debug, since it doesn't have a native `sleep` function like Postgres/MySQL, so it's difficult to trigger a long-running query without having a large dataset.

Can you provide details from BigQuery logs, which could help narrow down the problem?

There's places, where the frontend is holding on to a connection (e.g #12926), but with the details you mention, then it sounds like your reverse-proxy is closing the connection before response from Metabase has been delivered to the browser.
Though, in those cases, it should behave similarly to starting a query and closing the browser tab.
