### ISSUE TITLE
Adding/removing columns on an existing Model will drop all configured metadata

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22517]
**Describe the bug**
Adding/removing columns (or any other action that causes a dirty-state) on an existing Model will drop all configured metadata.

**To Reproduce**
1. Question > SQL > Sample - save as "Q1"
```
select * from orders
```
2. Turn into a Model
3. Click "Customize metadata" and spend time on configuring that - Save changes
![image](https://user-images.githubusercontent.com/1447303/167289611-2a9cee43-e537-4328-bdbe-26ba0e6846ef.png)
![image](https://user-images.githubusercontent.com/1447303/167289687-d1e79519-3649-415e-987f-a3468773cae3.png)
4. Click "Edit query definition" - change the query, so it adds/removes a column - e.g:
   ```
   select *, case when quantity>4 then 'large' else 'small' end size from orders
   ```
   ![image](https://user-images.githubusercontent.com/1447303/167289856-e18fc91c-568e-459b-a782-de0963a67aa1.png)
5. Now all metadata has been lost (the 37% comes from auto-magic, which causes problems by itself [#19133](https://github.com/metabase/metabase/issues/19133))
![image](https://user-images.githubusercontent.com/1447303/167290027-5e1633bb-a7a9-4ceb-bde8-429efe3d91b4.png)

**Expected behavior**
Don't drop metadata

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Comment by iPurpl3x** [comment]
I just discovered this issue as well, I hope there is a fix soon, I already had to set up the Metadata 3 times and that makes me loose a lot of time... :/

**Comment by dpsutton** [comment]
So this bug happens because of the frontend. Editing the query doesn't actually erase the metadata. The problem happens when you run the query in the metadata editor. That hits a generic endpoint `POST api/dataset` with the edited query. This endpoint is not model related so doesn't use the model metadata. So the results end up without the edits you have in place. The bug is that the frontend keeps this metadata around instead of retaining the original metadata. 

The metadata from this query run without a model context has only the "regular" metadata from the query itself. The frontend keeps this metadata associated with the model and sends it.

There are at least two possible ways to fix it:
- The frontend should just ignore this metadata from running the updated query. The backend will correctly handle this situation with the original edited metadata
- The frontend needs to send along the metadata when hitting the `POST api/dataset` when running the edited query. Either by enhancing `POST api/dataset` or a new endpoint that can handle this.

Between these two, I think the second solution is better. Right now when previewing the edited query it does not show the effects of the edited metadata (column formatting, renaming, etc) so this feels like a bug. If we do the second option it allows this query preview to reflect the metadata changes.
