### ISSUE TITLE
'YYYY-MM' is interpreted as 'YYYY-MM-DD' --> narrow bars 

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2282]
Hey,

since upgrading to v0.16 I'm faced with the very skinny bar problem again, that happened a few versions back (for example #1558). 

I want to chart monthly values by grouping by month. I do that by using `to_char(timestamp, 'YYYY-MM')`.
Unfortunately for the resulting chart these values are interpreted as complete timestamp. Another problem is, that the visualized timestamps are cast to (I suppose) another timezone which means they are also off by one hour.

Example table:
![image](https://cloud.githubusercontent.com/assets/8144392/14170279/2be84a04-f72d-11e5-8928-2d732fd2b4cf.png)
Resulting chart:
![image](https://cloud.githubusercontent.com/assets/8144392/14170311/54f6bd18-f72d-11e5-8945-7a055fe9f957.png)

If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  I'm running Metabase on AWS
*  My database is postgres.
*  My Metabase version is 0.16.0.

**Comment by tlrobinson** [comment]
Ok so there are a few things going on here. The thing that broke this is we changed our client-side date/time parsing from `new Date()` to `moment.parseZone()` in order to retain the timezone information normally returned by the backend query processor, and `moment.parseZone()`'s behavior when parsing strings without timezone offsets is different than `new Date()`, and IMHO wrong. 

For whatever reason, if no timezone offset is in the input string `parseZone` will parse it in your browser's timezone (which is what `new Date()` and `moment()` do), but then set the `offset` to 0 and `isUTC` to true. I've filed an issue here https://github.com/moment/moment/issues/3083

Because of this, and the fact that your browser's timezone is (I assume) in a timezone with daylights savings, and the data you have spans DST/standard time months, the code the detects the granularity of the data is getting confused and thinking it's hourly data instead of monthly.

The moment documentation says `moment.parseZone(s)` is equivalent to `moment(s).utcOffset(s)`. I think if we use `moment.utc(s).utcOffset(s)` things will work correctly, but I need to do some more testing.

**Comment by tlrobinson** [comment]
The general version of this problem is actually a bit trickier than I thought. The problem is if your report timezone is something like PST then times that are within DST will be returned with a UTC offset of -7 while times not in UTC will be returned with a UTC offset of -8.

e.x.:

```
SELECT DATE_TRUNC('week', tm) as week, count(*)
FROM (VALUES
  (timestamp '2016-03-08'),
  (timestamp '2016-03-15'),
  (timestamp '2016-03-22')
) AS t(tm)
GROUP BY week
ORDER BY week;
```

returns rows:

```
[
  ["2016-03-07T00:00:00.000-08:00", 1],
  ["2016-03-14T00:00:00.000-07:00", 1],
  ["2016-03-21T00:00:00.000-07:00", 1]
]
```

When we try to detect the granularity of that timeseries it thinks it's hourly because `00:00.000-8:00` and  `00:00.000-7:00` are off by 1 hour.

**Comment by agilliland** [comment]
when you say "it thinks it's hourly", what are you referring to?  moment.js?  d3?  is that something in our own code?
