### ISSUE TITLE
Chinese weekdays in calendar widget are incorrect

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#22871]
**Describe the bug**
Chinese weekdays in calendar widget are incorrect.
There were several MomentJS adjustments in 43, so likely caused by one of those.
I have no idea what is correct or not, or what the values mean. Someone who understands the difference between the various `zh` dialects should validate it's correct.

**To Reproduce**
1. Account Settings or Admin > Settings > Localization > change language to Chinese
2. Question > Sample > Products - filter by specific date on Created At
![image](https://user-images.githubusercontent.com/1447303/169527048-b645960a-2f16-43f5-8cc0-ee6093a50db8.png)

**Expected behavior**
0.42.4 was correct
![image](https://user-images.githubusercontent.com/1447303/169526556-f7cd863a-3320-4666-ba77-3bfe69954249.png)

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by noahmoss** [comment]
In case this is helpful, I asked a Chinese speaker I know and they suspected at least some of the wrong translations are due to translating the English abbreviations directly (like "wed" instead of "wednesday")

**Comment by noahmoss** [comment]
Did a bit more digging and can now confirm, this is due to the shortened (two-letter) day names being translated literally, without the context of what they represent. Here's where these translation strings are defined: https://github.com/metabase/metabase-private/blob/e9409ca9670883c4816961c3e3855b27ab3c892f/frontend/src/metabase/components/Calendar.tsx#L133

Not sure if we have a good way to guard against stuff like this.

**Comment by asdio** [comment]
so how to fix this bug?
