### ISSUE TITLE
Queries using Cross Join, stopped working on Postgres after x.43 upgrade

### ISSUE THREAD

**Issue by LobeTia** [metabase/metabase#22914]
**Describe the bug**
After the rollout of x.43 on our Cloud instance we started noticing that some queries stopped working, apparently Metabase handles CROSS JOIN on Postgres in a different way from previous versions

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Execute this query on the database using a different tool than Metabase (es: DataGrip)
```
WITH calendar AS
         (SELECT DISTINCT DATE_TRUNC('month', start_date) "month" FROM contracts_view ORDER BY 1)

SELECT calendar.month,
       SUM(CASE
               WHEN DATE_TRUNC('month', contracts_view.start_date) = calendar.month THEN 1
               ELSE 0
           END) new_active

FROM contracts_view
         CROSS JOIN calendar

WHERE calendar.month BETWEEN contracts_view.start_date AND coalesce(contracts_view.end_date, now())

GROUP BY 1
ORDER BY 1;
```
2. Create a new question using the SQL editor
3. Execute the same query from Metabase

**Expected behavior**
Metabase should return the same results as any other tool since we're executing a native query on our database

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 101.0.4951
- Your operating system: Mac OSX 10.15.7
- Your databases: Postgres
- Metabase version: 1.43.1 hash: 7f1a1c4 
- Metabase hosting environment: Cloud

**Severity**
Some of our queries are effect (~5%) the real issue is that now we cannot rely effectively on results quality since executing the query inside Metabase yield different results than any other tool that we tested

**Comment by flamber** [comment]
Hi @LobeTia 
Metabase 43.0 upgraded the Postgres driver from [42.2.23](https://github.com/metabase/metabase/blob/release-x.42.x/deps.edn#L121) to [42.3.2](https://github.com/metabase/metabase/blob/release-x.43.x/deps.edn).

You say "queries stopped working" initially, but later on you say that you are getting different results - which is it?
If the queries stopped, then I'm guessing you're seeing an error?
If different results, can you provide some type of DDL, which we can use as reference.

DBeaver is a good tool to compare with, since it is also using the JDBC driver, but you can easily switch between driver versions.
