### ISSUE TITLE
feature request: select all columns when joining, not just the starting table's

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#2305]
currently, when you filter/group across a foreign key (ie do a join), you only get the initial table's data back. it'd be nice to optionally also get the joined table's data.

i know #2214 may be one way do this (and #1173 is related), but this would be a nice smaller step that wouldn't require setting up a view ahead of time. ideally you could even join using foreign keys without filtering or grouping at all, just to see/visualize the joined rows.

feel free to close if this is a dupe!

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by nielsonsantana** [comment]
+1

**Comment by dhirenpratap** [comment]
+1

**Comment by kristian-elder** [comment]
I was about to create a ticket for exactly this but realized there is one already - somewhat surprised to see that this hasn't been updated ro replied to for a very long time. Are there technical reasons for why this would be particularly difficult or has it just not been deemed useful?

We are currently pre-processing tables for use in Metabase, or relying on custom SQL queries, due to this issue and would be very happy to see built in support for it!

**Comment by camsaul** [comment]
@kristian-elder, we're prioritizing new features based on the impact we think they'll have and by community feedback such as upvoting (:+1: reactions). There are lots of issues with much more upvotes; #3681 is a good example.

If this is a feature you desperately need ASAP, PRs are always welcome 😃 .

**Comment by paulopenagent** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by flamber** [comment]
Closing this, since it's now (since many versions ago) possible to add columns via [visualization Settings](https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#tables) or via [joins in the Notebook editor](https://www.metabase.com/docs/latest/users-guide/custom-questions.html).
