### ISSUE TITLE
Filter definition in Segment Revision history doesn't scroll sideways

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2313]
The filter definition of a segment has a scroll bar which does not actually scroll.

according to @kdoh "it has a pointer events none on it so you can’t use the scrollbar"

*  I am using the _Chrome_ browser.
*  My computer's OS is _Mac OS X_.
*  I'm running Metabase _on Elastic Beanstalk_
*  My database is _Postgres/RDS_.
*  My Metabase version is _0.16.1_.

**Comment by tlrobinson** [comment]
I'm not sure I understand this. It doesn't look like the segment's filter is scrollable at all, it just makes the page too wide (this has been happening since at least v0.15.1)

![screenshot 2016-04-21 13 34 07](https://cloud.githubusercontent.com/assets/18193/14723417/df655da8-07c5-11e6-9dc5-9a39443f14a0.png)
![screenshot 2016-04-21 13 34 11](https://cloud.githubusercontent.com/assets/18193/14723418/df6668e2-07c5-11e6-99b2-c56f78e3801f.png)

**Comment by agilliland** [comment]
I think the general intention is that box would actually scroll horizontally rather than just keep getting bigger and bigger to the point of stretching the page to look like ass.

Looks like something similar happens on the summary on the listing page too ..

![screen shot 2016-04-21 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/1987787/14727508/82a73bca-07e0-11e6-890a-7dda496e8f47.png)

**Comment by mazameli** [comment]
I think that on the segment revision history page, the items should wrap. On the data model page under the Definition column, I'd suggest truncation (…) after it exceeds a max width.

**Comment by tlrobinson** [comment]
@kdoh I think I'm going to need some help with these

**Comment by kdoh** [comment]
Cool. I can take a look.
