### ISSUE TITLE
Setting "Currency Label Style" is ignored for some currencies

### ISSUE THREAD

**Issue by cwelton** [metabase/metabase#23157]
**Describe the bug**

When "Currency Label Style" is set to Symbol, often the currency code is displayed instead of the symbol.

(This is a result of the Intl library formatting)

**Expected behavior**
When a user select to display a currency using the symbol, use the symbol.

**Screenshots**
<img width="341" alt="Screen Shot 2022-06-04 at 9 24 03 AM" src="https://user-images.githubusercontent.com/411822/172016186-15f530bb-6db0-4109-ad83-2e847089e4a3.png"> <img width="344" alt="Screen Shot 2022-06-04 at 9 27 30 AM" src="https://user-images.githubusercontent.com/411822/172016296-17a56d16-ebc0-4bf7-9ebb-24a19b17bcba.png">

Expected format of the numbers would be to use the format selected, e.g. `₿ 3.22`

**Severity**
Annoying

**Comment by cwelton** [comment]
This is a direct result of the Intl libray.

Proposed fix:
```
        if (options["currency_style"] === "symbol") {
          formatted = formatted.replace(options["currency"], getCurrencySymbol(options["currency"]))
        }
```

**Comment by noahmoss** [comment]
This could almost be considered a regression. I remember making a change a while ago to hide the "Symbol" option for currencies where we don't actually support it. Not sure why it's appearing again.

The main issue with indiscriminately replacing the currency code with the symbol is that some currencies require the symbol on the right side of the number instead of the left.

**Comment by gusaiani** [comment]
@cwelton If you can direct me straight to it: where should your proposed fix go?
