### ISSUE TITLE
Don't offer custom expressions when they are not supported

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#23266]
**Describe the bug**
Relative temporal filters with offset like "past 7 days starting from 3 years ago" generate expressions that are not supported by all drivers and this leads to errors. Currently the Druid and Google Analytics drivers have this problem. We might add support for Druid in the future, but it's unlikely that Google Analytics will be supported.

**To Reproduce**
Add a relative filter with offset to a temporal column.

**Expected behavior**
The filter in the image below should not be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/103100869/172924105-0e803a83-0229-4d04-a333-930f1e29b57b.png)

**Additional context**
This issue is related to #22531.

**Comment by flamber** [comment]
Looks like we need a new supported parameter in the backend otherwise I'm not sure how the frontend should detect that this is specifically for relative time.

**Comment by camsaul** [comment]
Don't think we need to add anything to the backend. The frontend is the one generating the `[:+ <field> <interval>]` expression and it can check the Database/driver `:features` to see whether `:expressions` are supported or not. If they're not supported, don't offer that "Starting from" UI.

Also I think this should be at least a P2 since it's more than purely a cosmetic bug. The original backend issue #22531 was a P2.
