### ISSUE TITLE
Metabase should sync more frequently to capture schema changes

### ISSUE THREAD

**Issue by infomofo** [metabase/metabase#2329]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Mac.
*  I'm running Metabase ??. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Psql.
*  My Metabase version is 0.16.1.

-----

I added a new column to a table yesterday- this column (tracked_events.referrer) is queryable in the sql editor, or datahub query, but it doesn't show up in the GUI query builder or in the data model view in admin.  I've tried hitting the "sync" button on my database and it still hasn't shown up 10 mins later.

**Comment by agilliland** [comment]
I suspect that's just a timing thing.  It takes a little while for Metabase to scan a database and find everything.  If you give it a little more time and then check back I suspect you'll see the column you are looking for.

**Comment by tlrobinson** [comment]
Related: #649

**Comment by infomofo** [comment]
as @agilliland predicted- the issue just kind of resolved itself after an hour- but this was already about 7 hours after our normal automated db sync so it did seem pretty weird.  it's no longer an active problem for me though so feel free to close the issue if you like

**Comment by agilliland** [comment]
Cool.  I'm going to tweak the title and keep this open because I think the feedback is still sound.  Ideally Metabase would be a bit faster at identifying changes to the underlying schema so that confusion like this can be avoided.

**Comment by tlrobinson** [comment]
@agilliland If I understand @infomofo's comments correctly, it wasn't the frequency of the syncing that was the problem (he manually hit the sync button as well), it was that the sync took a long time and there's no way of knowing if a sync is in progress or completed, i.e. #649.

That said, if there are ways to get the schema to update faster when starting a sync that would be worth looking into as well. I don't know if we sync the schema and the "in-depth database analysis" stuff concurrently, but it would make sense to do the faster, schema only, sync first, then the more in-depth analysis after, since it's less critical.

**Comment by agilliland** [comment]
That is what we do ;)

**Comment by agilliland** [comment]
Sorry, I jumped the gun because I've been working on some of that code recently and thought it was done.  The current version combines the 2 which makes it slower, but the newer code that I have separates the processes so that the basic introspection process completes 100% and then after it's done we do the analyzing.  So that's indeed coming soon.

**Comment by agilliland** [comment]
Turns out that someone else submitted an issue about the sync taking a long time and making it confusing because some of the basic schema metadata hadn't been updated yet, so I'm going to track that aspect of this issue via #2337 and leave this issue just dedicated to running the sync more frequently so that changes are captured more quickly.
