### ISSUE TITLE
Drill-through to questions with add columns (implicit join) causes no filtering to be defined

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23293]
**Describe the bug**
Drill-through to questions with add columns (implicitly joined) causes no filtering to be defined.

Workaround: Use explicit join in the first question (join Products table instead of step 2), or use [remapping](https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html#remapping-column-values).

**To Reproduce**
1. Question > Sample > Orders
2. Visualization Settings > Visible columns and More columns > Remove Orders.ProductID, and add Products.Category
![image](https://user-images.githubusercontent.com/1447303/173195602-72dd1d7e-eb19-4c90-8440-ad09a2c792ca.png)
3. Save question as "Q1"
4. Question > Saved Question > "Q1" - summarize Count by Category
![image](https://user-images.githubusercontent.com/1447303/173195624-2811664b-5e67-4ea7-9882-29ce3e6dfd63.png)
5. Save question as "Q2" (try drill-through on the question, works as expected)
6. Add "Q2" to a dashboard, click the bars to do a "View these Q1"
![image](https://user-images.githubusercontent.com/1447303/173195522-db9ceede-334a-4153-ad77-47dca4dfc103.png)
7. Shows all results instead of filtered accordingly to the drill-through
![image](https://user-images.githubusercontent.com/1447303/173195665-3d4d4ef7-6327-4703-93fc-807cf0ed5293.png)

**Information about your Metabase Installation:**
Tested 0.43.2

**Additional context**
Likely done this way because of https://github.com/metabase/metabase/issues/15163#issuecomment-990132061.

**Comment by nemanjaglumac** [comment]
The fix has been reverted. Reopening.

**Comment by WiNloSt** [comment]
I tested with this commit b64cd2674581716b5ce68186fee62c2c46f47b83–which is before https://github.com/metabase/metabase/pull/31117 is merged–and couldn't reproduce the issue anymore.

The thing is that https://github.com/metabase/metabase/pull/31117 is very similar to the original fix https://github.com/metabase/metabase/pull/28022 which says it is also supposed to fix this issue. So I made sure https://github.com/metabase/metabase/pull/31117 isn't actually fixing this issue, but something else does. And that's why I didn't include this issue in https://github.com/metabase/metabase/pull/31117.

**Comment by nemanjaglumac** [comment]
@WiNloSt I'll add a repro just in case.
Thanks for bringing it to my attention.

Do you think it was fixed by #31117?

**Comment by WiNloSt** [comment]
@nemanjaglumac I don't think this is fixed by #31117. Please see https://github.com/metabase/metabase/issues/23293#issuecomment-1567952365 (hope that's not too confusing)

**Comment by nemanjaglumac** [comment]
Added E2E repro that confirms the fix.
