### ISSUE TITLE
Prevent multiple sync processes

### ISSUE THREAD

**Issue by cstuder** [metabase/metabase#2337]
*  I am using the Chrome 49 browser.
*  My computer's OS is Windows 7.
*  I'm running Metabase locally from the JAR.
*  My database is MariaDB 5.5 (Using the MySQL connector).
*  My Metabase version is v0.16.1.

When syncing a particular database with 140 potentially big tables, I've inadvertently started multiple sync processes due to big tables with non-ideal indices. Some executed SQL queries by the sync took so long that it looked like the sync process failed. (Most tables didn't show any metadata)

I propose to make the syncing process more visible to the user, informing her that when selecting a database for questioning while it's still in sync.

(Side note: I'm a first time Metabase user and thought that this application was broken because I couldn't filter due to the missing metadata.)

Additionally one should be unable to launch multiple sync processes for the same database at the same time.

**Comment by agilliland** [comment]
Yeah, we had a similar comment on #2329 .  I've already got some code going that will make the sync process happen in a more natural progression so that the basic information about the tables and fields will be captured and become available within a matter of seconds, then the slower stuff can happen over a longer period of time without really affecting the ability to use the app.

I also agree that we should prevent multiple syncs from running at the same time.  Probably never a valid use case for that to happen.

**Comment by tlrobinson** [comment]
Also #649 addresses sync visibility/progress. I'm going to change the title of this one to just address the duplicate sync issue.
