### ISSUE TITLE
Drop support for Mongo version < 4 and run all :expressions tests for Mongo

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#23422]
MongoDB 3.x was EOL'ed over a year ago so now it's probably safe to say we don't support MongoDB 3.x anymore. We don't test against it anyway -- we test against 4.0 and 5.0. 

We could replace the `driver/database-supports?` method for `[:mongo :expressions]` with a `drvier/supports?` method in `metabase.driver.mongo` and then we could get rid of the special case code in `metabase.query-processor-test.filter-test/timezone-arithmetic-drivers`. This would also provide the added benefit of having other `:expressions` code run against Mongo without us needing special case code here, so we might catch some more bugs.

**Links**
- [PR](https://github.com/metabase/metabase/pull/23292) which led to the discovery of this issue with some more discussion

**Comment by camsaul** [comment]
I think we should prioritize this because it seems like a lot of stuff is actually broken in MongoDB. For example a simple expression like `[:/ [:field ...] 2]` is broken because [MongoDB doesn't allow use of the `$divide` operator in the `$group` stage](https://stackoverflow.com/questions/67287143/the-divide-accumulator-is-a-unary-operator). So there is a lot of stuff actually broken. Even tho I'm using MongoDB 4.0 which we advertise as supporting `:expressions`

**Comment by camsaul** [comment]
We should probably fix `mt/normal-drivers-with-feature` and the like and have them check `driver/database-supports?` instead of `driver/supports?` while we're at it, because that would have identified broken expression support in MongoDB 4.0 at the time we added it

**Comment by camsaul** [comment]
These are the operators allowed in the `$group` stage https://www.mongodb.com/docs/manual/reference/operator/aggregation/group/#accumulator-operator

**Comment by calherries** [comment]
@cam I've fixed that here https://github.com/metabase/metabase/pull/27112
