### ISSUE TITLE
Metabot shouldn't add a duplicate title or use "pulse" terminology

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2343]
An artifact of reusing the pulse code, we're showing duplicate titles (since there's no pulse title we use the card title) and calling it a "pulse" even though it's not:

![screenshot 2016-04-08 13 06 41](https://cloud.githubusercontent.com/assets/18193/14396151/d471b95e-fd8a-11e5-826e-8e296a284725.png)

**Comment by agilliland** [comment]
One quick thing though is that I don't think you can remove the second title, which is really just the name of the file attachment.  That's something that Slack does and we have no control over it.  I agree though that the first title is both wrong, because it's prefixed with "Pulse: ", and ultimately unnecessary when Metabot is posting the answer to a question.
