### ISSUE TITLE
Allow sending Alerts to private Slack channel

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23483]
**Describe the bug**
Same as #20867, but just for Alerts.

**Expected behavior**
Same functionality as Subscriptions - including being able to send to private channel.
It would also be great if there was a "Send now" button, but I'm unsure if we're missing an API endpoint for that.

**Information about your Metabase Installation:**
0.43.3

**Additional context**
Would be good to address #22496 and #18608, as well as #13834 (which might fix #15831).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by noahmoss** [comment]
Does the subscription side of this still work, even?

I'm testing out something unrelated but I noticed that I was getting `channel_not_found` errors when trying to send a subscription to a private channel. I then looked at [the docs](https://api.slack.com/methods/chat.postMessage#channels__post-to-a-private-channel) and saw that a bot needs to already be a member of a private channel to send messages to it.

This must have changed recently, because I'm pretty sure it worked when @gusaiani merged in his changes. And we don't have any logic on the backend to auto-join a private channel (I don't think it's even possible without including private channels in the cache, which we don't currently do.)

A solution to this would be to add instructions to the UI for adding the bot to the private channel before trying to set up a subscription. @alxnddr if you're working on this now, maybe you can add it.
