### ISSUE TITLE
Dashboard click behavior with connected public dashboards do not work for unauthenticated users

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#23873]
**Describe the bug**

When connecting a dashboard click behavior to the public version of another dashboard, it does not work for unauthenticated users.

**To Reproduce**
1. Create D1 dashboard and share it
2. Create D2 dashboard and add the click behavior which should lead to the public version of D1
3. Share the D2 dashboard
4. Open D2 in an incognito mode and try the click behavior
5. It does not work

**Expected behavior**
It should open the D1 dashboard

**Information about your Metabase Installation:**

The feature was merged after 43 release and it needs to be fixed until the 44 gold release.

**Comment by flamber** [comment]
For history #14009

**Comment by camsaul** [comment]
For history purposes I suggested the right way to fix this would be to include the public UUID of Dashboard D1 in the appropriate click action information in Dashboard D2. This can be hydrated on the backend. See 

https://metaboat.slack.com/archives/CKZEMT1MJ/p1658773970996769

for more info. I was worried about potential security implications about this but after discussing with the product team here

https://metaboat.slack.com/archives/C01LQQ2UW03/p1658776907515509

the consensus is that this should be fine.

So our action items are two steps 

- [ ] [Backend] hydrate `public_uuid` in Dashboard click actions pointing at other Dashboards. I think this should only be done when accessing the Dashboard via the public endpoints to keep the public UUIDs somewhat more private
- [ ] [Frontend] Once `public_uuid` starts coming back, hit the public Dashboard endpoint to fetch D1 instead of trying to use the authenticated version of the endpoint.

**Comment by flamber** [comment]
Closing as reverted #24496
