### ISSUE TITLE
Columns not visible in Data Model

### ISSUE THREAD

**Issue by ttotev** [metabase/metabase#2401]
If this is a bug report, please fill in the blanks:

*  I am using the Chrome browser.
*  My computer's OS is Windows 7.
*  I'm running Metabase locally from the JAR.
*  My database is MySQL.
*  My Metabase version is v0.16.1 build on 2016-04-05.

The first Database I add to Metabase shows correct columns for all tables.
The second Database - shows columns only for the first table.

![image](https://cloud.githubusercontent.com/assets/30994/14727101/cf6f84e8-07dc-11e6-80d9-f3d960cac669.png)

**Comment by tlrobinson** [comment]
@ttotev How long did you wait after adding the database before checking? It can take some time to synchronize the schema. We have issue #649 to improve the visibility into the sync process.

**Comment by ttotev** [comment]
It's been about an hour. Is there a way to see the current sync process status?

**Comment by agilliland** [comment]
Yeah.  It's mostly a matter of how much data is in the database which is going to affect how long it takes because it's going over each table that gets added and trying to analyze the data shape.

In the upcoming version of Metabase this isn't an issue because we inspect the whole schema first and complete that work before doing any of the slower work to analyze the data shape.

**Comment by ttotev** [comment]
Thanks! Looking forward to it.
