### ISSUE TITLE
Filtering with an empty cell using operators '<' and '>' returns an error in the table(question)

### ISSUE THREAD

**Issue by KlingerMatheus** [metabase/metabase#24149]
**Describe the bug** 
A table(question) that has empty cells, when you click on an empty cell to make some operation such as `<` or `>` it returns an error and these actions doesn't make sense since it is not possible to say if `[COLUMN]` is `less than` or `greater than` to `empty`.
 
 **Logs** 
 ![console_error](https://user-images.githubusercontent.com/50892465/180027169-23bedccd-a051-4710-9a9f-58134a98d22d.jpg)
 
 **To Reproduce** 
1. Open some question that has some `empty` cell (e.g. Sample Database > Orders --- the "Discount" column has empty cells)
2. Click on an `empty` cell;
3. Click on `<` or `>`;
4. Now it should display the error.
 
 **Expected behavior** 
 When an `empty` cell is clicked, the actions buttons `<` and `>` should be **disabled** or **not be displayed**.
 
 **Demo** 
[Click here to see](https://www.loom.com/share/eab0e63b9d1e4acabec8080d49553e32)
 
 **Information about your Metabase Installation:**
 
Your browser and the version: **Opera GX 102 on Windows 11**
Your operating system: **Windows 11 64-bits**
Your databases: **H2**
Metabase version: **1.44.0-RC1**
Metabase hosting environment: **Unknown**
Metabase internal database: **1.4.197 (2018-03-18)**

**Additional context** 
NA

**Comment by KlingerMatheus** [comment]
I am working on this issue.

**Comment by kamilmielnik** [comment]
Reproducible in 0.44.0.
Fixed in `master` ([d35c779](https://github.com/metabase/metabase/commit/d35c779976ae6bd79369e9cc6bec8540908f37d2)) - [screenshot](https://github.com/metabase/metabase/assets/6830683/8eafa3f5-3876-49b3-a2bd-8680b57d8a29):
- the `<` and `>` options have been removed for empty cells ([screenshot](https://github.com/metabase/metabase/assets/6830683/d1686211-633c-4b8d-b824-a290cb8be622))

Marking as fixed in the next version (48).
Closing.

**Comment by snoe** [comment]
Tested here:
https://github.com/metabase/metabase/blob/master/test/metabase/lib/drill_thru_test.cljc#L316-L334
