### ISSUE TITLE
Not possible for admins to change name for SSO users

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#24757]
**Describe the bug**
It's not possible for admins to change the name of users who are using SSO, since this limitation is for all types of SSO, but sync of name was only added to some SSO types.
History #15483

**To Reproduce**
1. Sign-in with SSO user
2. As admin, go to Admin > People > edit (SSO user) > change the name and click save - errors with `Editing first name is not allowed for SSO users`.
![image](https://user-images.githubusercontent.com/1447303/184489717-2a3783ae-f153-4006-881c-32861efc6fdd.png)

**Expected behavior**
Admins should be able to change the name. There's no reason to limit this for admins.

**Information about your Metabase Installation:**
Tested 1.44.0

**Comment by camsaul** [comment]
> There's no reason to limit this for admins.

The names come directly from the IdPs, that's why you can't edit them. That restriction was clearly put their on purpose. Why would an admin need to change a user's name to something other than it what it was when it came back from LDAP or SAML? Seems like a potential security risk. 


> sync of name was only added to some SSO types

Which SSO types are you talking about? Maybe the right fix is that we should be doing name sync for all SSO types, not removing this restriction

**Comment by paoliniluis** [comment]
A customer requested to change names **of the deactivated users** for GDPR reasons, makes a lot of sense to me. They want to anonymize those

**Comment by luizarakaki** [comment]
@paoliniluis I'm adding an issue to enable user anonymization and closing this as "not-planned". I agree that we should support user anonymization, but I don't think we should enable IdP prop overwriting.

**Comment by luizarakaki** [comment]
Closing in favor of this feature request #32151

**Comment by allocate-engineering** [comment]
Names are coming over as empty from Google Workspace, and I can't set them to anything because of this behavior.  This sorts them all to the end of my user list, and finding people is way more difficult than it needs to be. @luizarakaki 

<img width="1126" height="1060" alt="Image" src="https://github.com/user-attachments/assets/27271c7a-0f03-400e-8fd9-e06f34333d36" />
