### ISSUE TITLE
[SerDes 45] Support offline data-model-only SerDes for a particular Database

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24767]
Part of #24795

I'm not sure how much of this is already in place -- we can close this if this is already actually working 100%. Otherwise if we need to make small tweaks or whatever we can do it and close this out.

We want to be able to offline serialize just the synced metadata (Database/Table/Fields/etc.) for a data warehouse without including anything that might depend on it like Cards/Dashboards/permissions/etc. We should be able to do this easily with a single command.

It should be possible to do an offline "upsert" deserialization with a single command to update the synced metadata. It should support things like adding/removing new Tables/Fields, etc. for an existing Database.

**Comment by bshepherdson** [comment]
I'm not certain what you mean by "offline" serialization - I take it to mean (de)serializing as a separate command, rather than from/to a running instance.

### Filtered export

This is not currently supported but is easily added. It could either be done as a new specific flag, perhaps `--schema-only`; or as an explicit filter `--only-models=Database,Table,Field,FieldValues`.

Since we're going to want several other flavours of selective export soon, it probably makes sense to design a general scheme for that, and fit this into it.

### Deserialization and upsert

The current deserialization is an upsert - common entities are updated, new ones are added. **Existing entities not present in the import are not touched.** I don't think we care to delete dead eg. tables currently?

"Common entities" are determined by having the same key, which for Databases, Tables and Fields is their human-selected `name`s. (Namespaced inside each other, `Database -> (Schema ->) Table -> Field`).

### Needed Work

If I'm understanding this properly, there are two independent changes needed:
- Include `FieldValues` (and any other such sync-produced data? I think that's it but I don't know for sure.) in serdes.
    - This is straightforward if there's only one (non-sandboxed) FV per field. If not, then they'll need a new key to portably identify one FV with another.
- Add the selective export flags.

**Comment by camsaul** [comment]
@bshepherdson implemented the remaining stuff here earlier in the cycle

**Comment by camsaul** [comment]
See also https://github.com/metabase/metabase/issues/24769 which was part of this

**Comment by camsaul** [comment]
Resolved by https://github.com/metabase/metabase/pull/24855
