### ISSUE TITLE
[Models] Don't rerun the query when saving from edit mode if we already have the results

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#24825]
After saving, the query runs again and can be very slow.

More info here: https://www.notion.so/metabase/Make-model-editing-faster-and-easier-ee31edef605c486e8f9c0fbe70fa3af2

**Comment by gusaiani** [comment]
@luizarakaki This is what I understood from [your comment](https://www.notion.so/metabase/Make-model-editing-faster-and-easier-ee31edef605c486e8f9c0fbe70fa3af2).

Please correct everything you'd like or let me know and I can edit it.

**Comment by luizarakaki** [comment]
I think this issue has the same root cause of #24821.

The problem is not exactly the comment:

1. Open a model and edit query
2. Change anything
3. Run the query
-- Now I have the results from the latest version of the query
4. Save
-- The query runs again (even if I already have the results of the latest version on my page)
