### ISSUE TITLE
Pie/donut charts should have more colors

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2489]
Right now I think we have only 5. It makes it hard to make sense of pie charts with many segments (the downloads by version chart in the office is a perfect example).

Back in the day I think we had closer to a dozen different colors

**Comment by camsaul** [comment]
Here is a prime example 🙀 

![screen shot 2016-04-29 at 2 54 29 pm](https://cloud.githubusercontent.com/assets/1455846/14930630/4b6cdb2a-0e1a-11e6-822f-6623c20688a0.png)

**Comment by tlrobinson** [comment]
True, but we also shouldn't encourage the use of pie charts with a ton of slices since it's basically impossible to compare a bunch of similar sized slices.

**Comment by camsaul** [comment]
Fixing a broken use-case doesn't have to mean we explicitly encourage it. Either way right now even non-crazy ones are broken. Even six slices (which is pretty reasonable) produces a chart with duplicate colors. It's basically impossible to compare a bunch of slices that are all the same color.

**Comment by MrMauricioLeite** [comment]
Well that will help other chart visualization too.
Take a look at my case below. I have a dashboard that shows the performance of our ETL routines every night and plot it to a area chart.

The problem here is that we have one line/area by Job and more jobs than colors available. that makes the user, and even me, really confused. On top of that the last two series looks broken and won't hide in case of a move-over on another series. (pictures below)

![capturar](https://cloud.githubusercontent.com/assets/1953457/15371646/e3a037a0-1d12-11e6-92ad-f291b8b3a345.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/1953457/15371647/e3ed9522-1d12-11e6-82cb-a8cc0165ce17.PNG)

**Comment by kdoh** [comment]
So we'd previously solved this via our color harmony - https://github.com/metabase/metabase/blob/master/frontend/src/lib/colors.js#L25.  Looks like after our dashboard and charting upgrades we didn't apply the logic we'd been applying that cycled through various shades and tints based off of our primary color palette.

**Comment by moumny** [comment]
I received this feedback from various person in my team. I think its pretty common to have more that 5 "things" you want to show at the same time.
Also you cannot limit the number of rows (during a group by for ex) to 5 (minimum is 10)

**Comment by kdoh** [comment]
I'd like to change the designation of this from a proposal to a bug / regression. We introduced this functionality in #954 and lost it (most likely when we did the major refactoring of charting for the new dashboards).

**Comment by camsaul** [comment]
should we add this to 0.19? I like colors they are #fun
