### ISSUE TITLE
Allow specifying non-existing path for `MB_DB_FILE` in the Docker image

### ISSUE THREAD

**Issue by astrojuanlu** [metabase/metabase#24935]
**Is your feature request related to a problem? Please describe.**
I'd like to run the Metabase Docker image with `MB_DB_FILE=/var/lib/metabase/metabase.db`, but since `/var/lib/metabase/` does not exist, Metabase fails to initialize.

**Describe the solution you'd like**
The Docker image will create the non-existing path if `MB_DB_FILE` is given.

**Describe alternatives you've considered**
Possibly there's a way to run `mkdir -p /var/lib/metabase && MB_DB_FILE=... metabase` upon initialization of the Docker image, but I don't know if it's possible.

**How important is this feature to you?**
I'd like to have a single directory of my own choosing containing `metabase.db`.

**Comment by flamber** [comment]
Hi @astrojuanlu 
You can use a volume: https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker.html#mounting-a-mapped-file-storage-volume

Metabase already tries to create the directory, though not the full path: https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L136

Though, we would likely not make this change, since you should not be using H2 in production: https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker.html#production-installation

You can make your own Dockerfile if you need this, and add it to the RUN command: https://github.com/metabase/metabase/blob/master/bin/docker/Dockerfile
