### ISSUE TITLE
Can't change filters via 'Show filters'

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#24994]
**Describe the bug**

In a saved question, when I clicked on "Show filters" and try to change any of the filters (date, is empty, etc), the Update filter button grays out immediately. 

**Logs**
None

**To Reproduce**
1. Go to any saved question with filters
2. Click on "Show filters"
3. Try to change any filter's value (is empty to not empty, date to another date, etc)
4. Update filter button grays out immediately

**Expected behavior**
Update filter button shouldn't gray out, so the new filter can be applied. 

**Screenshots**

n/a as it's pretty simple / screenshot won't provide much value

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",

- Your operating system: MacIntel
- Your databases: Redshift
- Metabase version: master / 1fca705
- Metabase hosting environment: Metabase Cloud
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's a bit inconvenient as I need to go to the question's editor page to make changes instead. 

**Additional context**
None

**Comment by flamber** [comment]
Regression since 0.44.0 - related to #11957/#14193/#15620

Workaround: It is possible to change the filter via the filter modal or Notebook editor.

Reproduce:
1. Question > Sample > Products
2. Filter Category=(select all) and CreatedAt=past 30 years
3. Count grouped by Category
4. Filter Count > 0
![image](https://user-images.githubusercontent.com/1447303/186667130-8d993222-6345-4b2d-86f4-dc4d7f42dd3f.png)
5. Try making any changes to the Category or CreatedAt filter pills - it will disable the "Update filter" button
![image](https://user-images.githubusercontent.com/1447303/186667480-2d034792-89e8-4367-a49a-d6b6eb7c8843.png)
