### ISSUE TITLE
Pulses stopped posting to Slack

### ISSUE THREAD

**Issue by maxbeatty** [metabase/metabase#2499]
*  I am using the Chrome 50 browser.
*  My computer's OS is OS X 10.11.4.
*  I'm running Metabase on AWS 
*  My database is postgres.
*  My Metabase version is v0.16.1.

Everything about my Metabase instance appears to be healthy (health checks passing, questions returning results, etc.) but pulses have stopped posting to Slack.

1. "Test Slack Now" successfully sends a message
2. Toggling Slack off and on didn't fix it
3. Deleting a pulse and recreating it hasn't fixed it either

Any other ideas to get it posting again? Is [Discourse](https://discourse.metabase.com/) a better place to discuss seemingly non-technical issues like this?

**Comment by agilliland** [comment]
Hmmm, we have quite a few pulses which publish to our Metabase Slack instance every day and we haven't seen any disruption.  Also, given that the test sends it's definitely odd that you are seeing an issue.

One thought though is are you only seeing this happen today?  a.k.a. on Sunday?  Were the pulses sending yesterday?  I fixed a bug recently where the day of week logic was causing an error on Sundays which was affecting the sending of pulses just on that one day .. https://github.com/metabase/metabase/pull/2427

Oddly that's been in the code since pulses were launched and we only recently found it, but it's fixed and set to come out in our next release which goes out in a couple days.  So it's possible this is just localized to Sundays 😢

**Comment by maxbeatty** [comment]
They stopped posting after 4 PM PST yesterday (2016-04-30) so 5 PM PST would have turned over to Sunday UTC. One pulse is hourly and the other is daily. After recreating the hourly one and giving it more than an hour to post, I rebooted the app instances on AWS Beanstalk. After waiting for two more hours, still no notifications in Slack.

I know that's not a ton to go on. I'm happy to provide any other details that would help. If they do start appearing again, I'll update the issue with any hunches.

**Comment by maxbeatty** [comment]
At 5 PM PST today, UTC turned over to Monday and pulses started coming back to Slack. Must have been that Sunday bug

![nevermind. all good](http://replygif.net/i/387.gif)
