### ISSUE TITLE
Data Selector opens with database field picker if no saved questions exist, but models exist

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#25142]
**Describe the bug**

<img width="300" alt="image" src="https://user-images.githubusercontent.com/380816/187703280-eee90415-75c1-42dd-b674-965e3af545b5.png">

**To Reproduce**

1. Have no saved question in the system
2. Save one or more model.
3. `+New` › `Question`
4. Data selector will open with the Sample Dataset field picker (if that's the data you use) 

**Expected behavior**

Data selector should open with the option to choose between Raw Data or Models.

**Comment by flamber** [comment]
Related to #21511

**Comment by nemanjaglumac** [comment]
Not possible to reproduce anymore on `master` at [d1c59da](https://github.com/metabase/metabase/commit/d1c59dabec616f3f3f7770ae36792df29284e518). We have a different issue right now. Even when there are no saved question, nor any saved models, the data selector always initializes as if there are saved questions.
![image](https://github.com/metabase/metabase/assets/31325167/7ab653b5-a190-4366-bbee-cbba70607583)

Maybe because of the internal analytics?
