### ISSUE TITLE
Heroku deployment should use an email provider which doesn't require activation

### ISSUE THREAD

**Issue by zusamann** [metabase/metabase#2522]
I just installed metabase on heroku, every thing seems to be working fine so far, except when I add a new user. Since I don't have an SMTP server integrated in the email settings it should generate a password for me according to the documentation [here](https://github.com/metabase/metabase/blob/5c9a3a50411dad3ed951050b73274d28be350284/docs/administration-guide/04-managing-users.md). Instead it says the invite has been sent to the user and the user never recieves the email invite.

Apart from this glitch, I have to say I'm thoroughly impressed by the tool and would try and suggest more features and suggestions down the road.

*  I am using the Chrome browser.
*  My computer's OS is Windows.
*  I'm running Metabase on Heroku.
*  My database is MongoDB.
*  My Metabase version is  v0.16.1.

**Comment by agilliland** [comment]
@zusamann , are you sure that you didn't input some SMTP information on the `Email` settings page?  The only reason that you would get the behavior you mention is because the system thinks you've input SMTP information.  This is what I see when adding a new user on a fresh install of Metabase ...

<img width="476" alt="screen shot 2016-05-04 at 11 28 00 am" src="https://cloud.githubusercontent.com/assets/1987787/15024839/71499980-11eb-11e6-9784-21b42f3e3bd2.png">

This is done on 0.17.0, so if you want to upgrade real quick that would be helpful, but nothing in this part of the code changed from the v0.16.1 code that you ran.

**Comment by tlrobinson** [comment]
@zusamann If you deployed to Heroku using the one-click button at http://www.metabase.com/start/heroku.html then we automatically provisioned Metabase with the Heroku Mailgun add-on, which is why it's saying it's sending emails. If you want to disable that you can remove the addon in the Heroku app settings (https://dashboard.heroku.com/apps/APP-NAME/resources)

I'm not sure why they're not being received. I'm going to try deploying a new Heroku app to see if I can reproduce it.

**Comment by tlrobinson** [comment]
@zusamann Ok if you look in your Heroku app's logs you'll likely see something like 

```
2016-05-04T18:50:06.611220+00:00 app[web.1]: 05-04 18:50:06 WARN metabase.email :: Failed to send email:  554 Please activate your Mailgun account. Check your inbox or log in to your control panel to resend the activation email.
```

It looks like Mailgun recently started requiring you to activate your account. Check your email to see if you got an activation email from Mailgun. Alternatively you can remove the Mailgun add-on, and either use the non-email flow or add a different SMTP add-on (Metabase has built in support for (Sendgrid, Postmark, and Sparkpost)

I'm going to change this issue to specifically address the Heroku deployment scenario, and we also have an issue at #1692 for surfacing email errors.

**Comment by zusamann** [comment]
@tlrobinson Yes I did use the one-click deploy to heroku. And yes after removing the mailgun addon the flow works as documented, I'm able to generate passwords while adding people and also reset the passwords of already added people that never got an invite.

Cheers!

**Comment by tlrobinson** [comment]
So it looks like all of the Heroku SMTP addons require the user to enter their billing information (which isn't surprising given the potential for spam abuse), so I'm going to remove Mailgun and not replace it with another.

Instead we could either:

1. provide instructions for adding a SMTP addon (it can be done via the Heroku dashboard)
2. have a second "Deploy to Heroku" button which includes the addon and warns the user they'll need to enter billing information on their Heroku account (but it will not charge them).
