### ISSUE TITLE
Feature Request: Hyperlinks on Dashboards

### ISSUE THREAD

**Issue by marketingnerds** [metabase/metabase#2529]
I wish that record IDs and connections were hyperlinked in dashboard tables, as they are on their card pages. 

No links : (
![linkondash](https://cloud.githubusercontent.com/assets/15113386/15017463/b5983b26-11e3-11e6-87ee-06cceea1d646.png)

Links : )
![linkondash2](https://cloud.githubusercontent.com/assets/15113386/15017590/21bbd84e-11e4-11e6-9ccb-2cd8f3f5f0fe.png)

Incidentally, this is my first Issue post so I'll take the time to mention how happy I am with metabase so far. Thanks for the great work!

**Comment by ejhayes** [comment]
I think it'd also be pretty useful to generate hyperlinks from concatenated strings.  For example:

"https://www.example.com/users/" + user_id

That way it would be possible to go right to a dynamic link from the dashboard.

**Comment by schellkenig** [comment]
It would be great if you could use that link source as input for another card. The example would be that a user clicks on an ID and in another card the details for this ID are shown.

**Comment by drorm** [comment]
This would be amazing since it will really allow us to chain different dashboards. So we can have a dashboard with a world map and the user clicks and it gives info about a specific country.

It's not just a question of string manipulation. I can already generate the href using SQL. The problem is that the UI just shows the text rather than the link. That's probably a good thing. Here's an example:
 
![Link](https://cloud.githubusercontent.com/assets/517479/25157587/1673bb9c-2457-11e7-89ca-4ba25cb1cec6.png)

So we need  specific support to indicate that something's a link (need to watch for XSS issues).

@schellkenig you can already use a parameter to a dashboard so that's the easy part.

**Comment by wvengen** [comment]
It looks like #4503 might be of help here.

**Comment by motti** [comment]
#4503 is a browser extension which users would have to install separately. A built-in solution would make metabase a more more useful tool as an overview chart or table could deep-link directly into an record via a webapp (like @ejhayes said).

**Comment by wvengen** [comment]
@motti I think you're confusing something, #4503 has been merged, and makes hyperlinks for http and email addresses for those fields that have not specified the type otherwise.
Something like https://github.com/metabase/metabase/issues/2529#issuecomment-226331282 should already work now, but not putting html in the output like https://github.com/metabase/metabase/issues/2529#issuecomment-295019235.

**Comment by wvengen** [comment]
I did not test this on dashboard, though (instead of a query), but I'd expect it to work there as well.

**Comment by motti** [comment]
@wvengen Yes, sorry. I was confused with  a recommendation from [elsewhere](http://discourse.metabase.com/t/result-as-a-link/1705/9) to use a linkify-type extension

Even without arbitrary HTML, just allowing anchor text and perhaps link attributes (like target="_blank") would make the output much more useful and as stated means a metabase dashboard can be dorectly linked to a webapp.

**Comment by wvengen** [comment]
Let's close this issue, and if desired create a new issue for (whitelisted) html formatting (either a specific metabase column type or in the fallback string type).

**Comment by salsakran** [comment]
boosh https://www.metabase.com/docs/latest/enterprise-guide/customizing-drill-through.html
