### ISSUE TITLE
[ux issue] Not apparent you have to click on "labels" to create a label

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#2533]
I spent a couple minutes messing with v17 before I finally figured out how to add labels.  I tryed to create them directly with the label popup thing, look in admin, etc...

I finally clicked on the menu header titled "labels" and then could create them.

See this screenshot: 
![image](https://cloud.githubusercontent.com/assets/113870/15026872/45278e00-1206-11e6-8725-8544c5f1d01a.png)

It just never occurred to me to click on a menu header to create something.    This is confusing to the new user probably.

**Comment by javiercr** [comment]
Yep, I thought the label feature was not implemented or something. In fact, I didn't know how I could create a label until I found this issue.

**Comment by michnath** [comment]
I was looking for how to create a metabase label on google.
Thanks to that0n3guy for bringing it up. Yes it was pretty confusing for me until I came across to this issue.

**Comment by MrMauricioLeite** [comment]
yeah, apparently it's a problem here too. Our users are confused about that.

**Comment by mazameli** [comment]
I'm thinking we need to do two things:
1. make the empty state for the labels section have a clearer action to create an initial label:

![empty state](https://cloud.githubusercontent.com/assets/2223916/17573656/b414711e-5f10-11e6-9bb6-81aea70c8c29.png)


2. Provide a clearer link to edit/create labels. Rather than having the heading be a link, we could have a persistent item at the bottom of the list of labels:

![edit labels link](https://cloud.githubusercontent.com/assets/2223916/17573751/56a8c150-5f11-11e6-924a-4c214df0d4f4.png)

**Comment by that0n3guy** [comment]
I think that looks pretty good.   I'm not sure I like the "Edit Labels" thing as it looks too much like a label and could be mistaken.   

Maybe put it at the top? or next to "labels"?   What do others think?

**Comment by aagarwal-gtr** [comment]
+1 didn't think it was at all apparent

**Comment by kdoh** [comment]
Going to close this as labels have been deprecated in favor of collections.
