### ISSUE TITLE
Comma separated filter value would not hand over from dashboard to question

### ISSUE THREAD

**Issue by mskako** [metabase/metabase#25374]
**Describe the bug**
Comma separated filter value would not hand over from dashboard to question

**Logs**

**To Reproduce**
1. Create Dashboard with default value of comma separated multiple values
2. Open dashboard
3. Click question title which uses 1's default value
4. Only top 1 value will be taken over. Rest of them will be omitted.

**Expected behavior**
All of separated values will be taken over.

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2455462/189796664-a1441286-92f0-4baa-b17c-7cb5355618e3.png)

**Information about your Metabase Installation:**
Docker image metabase/metabase:v0.44.2

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 105.0.5195.102, Firefox 104.0.2
- Your operating system: Windows 10 Enterprise 21H2(Client)
- Your databases: MySQL
- Metabase version: v.0.44.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Customers' use case always starts with this dashboard and they move to each questions and export CSVs. Unless values taken over properly, their business flow will be stopped.

**Additional context**
On v.0.41.5, it doesn't happen.

**Comment by flamber** [comment]
Regression since 0.44.0

A possible workaround is to change the variable to Text and turn it into an array #4728, or use a Field Filter. But both options might be difficult to implement depending on dashboard count, database type or how the query is created.

Reproduce:
1. Native > Sample > `select count(*) from orders where id in ({{number}})` - change variable to Number - save question
2. Add question to dashboard, add filter Number equal and connect to card, save dashboard
3. Input `1,2,3` in filter, which gives expected results
![image](https://user-images.githubusercontent.com/1447303/194753838-99dad265-9c95-47ce-b58a-352efea008bc.png)
4. Click question title goes to the question, and the URL quickly flashes from `=1,2,3` to `=1` and give unexpected results
![image](https://user-images.githubusercontent.com/1447303/194753906-69e0ba82-77a0-4e7a-bf46-8b8ac413a7c4.png)

**Comment by nemanjaglumac** [comment]
Refreshing the dashboard also removes all values except the first one.
Which is also the equivalent of visiting the dashboard while trying to pass parameters through URL:
`/dashboard/:id?equal_to=1%2C2%2C3`

**Comment by mskako** [comment]
I just have checked on v.0.45.2, it works properly. Thanks!!
