### ISSUE TITLE
Changing Saved Question used as Custom View for Sandboxing doesn't update the Dashboard Drop down Filter with new list but keeps the old one

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#25411]
**Describe the bug**
When you have a Filter with a drop down in a dashboard that is used against a sandboxed table it should show the distinct rows available to filter. When you change the query used for sandboxing and filter for a different set of rows. The filter keeps the old values rather than the new. It takes a lot of time to update, with the only current workaround being that of pressing the Database option of `Discard saved field values` 

**To Reproduce**

1. Create a Group:
![image](https://user-images.githubusercontent.com/110378427/190161926-2998c1f5-93f8-4c3b-aa5c-2a7585a48727.png)

2. Create a User & Assign it to this Group

3. create a question on the ORDERS Table, Select all columns AND filter where product_id = 1, 2, 3) and use it for sandboxing on group 1:

![image](https://user-images.githubusercontent.com/110378427/190162249-68ab1875-633a-44be-b81a-a4ee0c127f6e.png)

![image](https://user-images.githubusercontent.com/110378427/190162288-1c3595b7-5a2a-4c07-96c7-f6412fe64ad0.png)

4. Create a simple dashboard with a Filter on the Product_ID against the Orders Table:

![image](https://user-images.githubusercontent.com/110378427/190162735-bc278bbc-38e6-487b-90c5-a0e0d320ae14.png)

5. Login with the user and check the dashboard (notice the 1, 2, 3 options):

<img width="818" alt="image" src="https://user-images.githubusercontent.com/110378427/190163072-cc41df17-7e6a-425d-92c0-f0510b7fabb5.png">

6. Go back to the question created for sandboxing permission and this time change it to 4,5,6 ... the user will still be seeing the previous options. Even if they are selected no results come out since the sandboxing is still working:

![image](https://user-images.githubusercontent.com/110378427/190163668-cda11c62-233f-424b-bcec-c7572b2f79e9.png)

<img width="833" alt="image" src="https://user-images.githubusercontent.com/110378427/190163854-a676e87d-e3c4-4b7e-8e72-8071931be069.png">

7. You either wait until Metabase updates on it's own, may take a couple of min to hours or go to Admin -> Database -> Discard saved field values and you will see the new available options

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/110378427/190164147-8b1c4e3e-6162-447d-8962-6f5a644a282c.png">

**Expected behavior**
Metabase automatically detects that the sandboxing question was updated and in turn it would require discarding the values automatically , so it gets new values

**Information about your Metabase Installation:**

- Your browser and the version: Chrome
- Your operating system: OS X 
- Your databases: H2 (Sample DatabasE)
- Metabase version: 44.2
- Metabase hosting environment: H2

**Comment by flamber** [comment]
Caused by the field-values hash does not also include the query hash of the question used to apply the sandboxing, so it continues using the old field-values hash until it's discarded even after the question has been modified.

Before v44, a simple restart could solve it as well, since sandboxed field values was stored in memory, but now they are stored in the application database with a hash.

The field values will likely not correct themselves on normal daily scan (unless there's changes to them), which means discarding saved values is the only option after modifying questions used for sandboxing.

Reproduce:
1. Question > Sample > Products - filter by ID=1 - save as "Sandbox"
2. Question > Sample > Products - save as "Products"
3. Add question "Products" (step 2) to a dashboard, add a Dropdown filter and connect to Category
![image](https://user-images.githubusercontent.com/1447303/194746911-b1e2d6ef-0794-4e03-b521-2cb5c9817484.png)
4. Admin > People > create user "U1"
5. Admin > Permissions > All Users > Sample > Products > Sandboxed
![image](https://user-images.githubusercontent.com/1447303/194747211-ea57b9c0-d173-4fa6-b0dd-132a53a8c46f.png)
6. Login as "U1" and go to dashboard and open filter dropdown - shows the correct value as expected
![image](https://user-images.githubusercontent.com/1447303/194747005-f6d67073-4910-4ab5-9773-657724065bce.png)
7. As admin, modify the question "Sandbox" (step 1) - example filter by ID=2, save
8. Login as "U1" and go to dashboard and open filter dropdown - it now still shows the old value, because the hash hasn't changed and the only solution is to discard the field values
![image](https://user-images.githubusercontent.com/1447303/194747330-bd06704c-2190-410c-9567-b05871315ab5.png)

**Comment by dpsutton** [comment]
I think this issue reveals a pretty gnarly bug.

I think we would want to have a hash of the card's query as part of the key. This would ensure that we invalidate when the query actually changes. The problem is that our [query hash function](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/util.clj#L83) can be called at different times.

In [query-processor/card](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/card.clj#L32) it is called on the query un-expanded, read directly from the `Card`. In the [cache middleware](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/cache.clj#L182) it is called on the query somewhere in the middleware chain. Not clear from the source if fetch-source-query has run, row-level-restrictions, etc. And because of this, how you use `qp.util/query-hash` can give different results for the same query depending on how much processing we have done.

I think we need to standardize a fully-expanded canonical query when taking a query hash. This ensures nested queries have been expanded (and should small differences in the associated metadata affect the hash?), row level restrictions have been applied, etc. And any time we want to use a query hash, we should make sure to use the hash of the canonical form of the query.

At the moment I think there's an argument that every use of `qp.util/query-hash` is a potential bug report. Especially as nested queries with models usage becomes more prominent, consistent hashing of the entire query will become more important.
