### ISSUE TITLE
Line series of 2d breakout is confusing

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2549]
The treatment of columns 2-N of a table as additional metrics on the dimension represented by column 1 in the result table.

Eg, using Orders in the sample dataset:
Count by days, user_id
results in the below line chart. This is not what I would expect given the query builder contents.

![screen shot 2016-05-05 at 4 58 12 pm](https://cloud.githubusercontent.com/assets/107439/15060695/5c0cc9f0-12e2-11e6-907f-f7c65ac13374.png)

**Comment by tlrobinson** [comment]
The problem is there is an ambiguity between dimension-dimension-metric and dimension-metric-metric type queries if you have a numeric dimension. I let D-M-M take precedence since that was what we implemented first and I didn't want to break existing cards.

We should do two things, either of which would fix this particular cases (but 1 would fix more cases)

1. Look at the query definition. If it's a structured query and the query has 2 breakouts then it's definitely a D-D-M. In fact it's actually currently impossible to construct a D-M-M query from the query builder (besides raw data that happens to fit) but that could change in the future.
2. Don't consider entity ids or foreign keys to be metrics (even if they're numeric)

Additionally we should give the user more control over how columns are mapped to parts of the chart, but that's a bigger thing.

**Comment by salsakran** [comment]
Yeah, I think it's really weird to have IDs/FKs be treated as metrics and am struggling to think of a situation where that comes up. Best I can make up is "top spender by day", and even that feels contrived. 

I like the idea of doing (1) automagically, and am in violent agreement re: control over column mapping being needed in the short/medium term.

**Comment by agilliland** [comment]
I would recommend that we focus a bit more on putting the right information in the query results where possible and rely less on having to pre-suppose things based on the query that was just run.  For example, if the first 2 columns in the results are breakouts and the third is an aggregation that seems like it should just be there in the metadata on the results.

**Comment by tlrobinson** [comment]
@agilliand That sounds good to me, at least for query builder queries. Just need to come up with a scheme. Something like `"breakout": true` or `"aggregation": true` on the appropriate `cols` object?

The caveat is we can't know that for native queries. So we still would need heuristics (and/or explicit mapping by The user)

**Comment by tlrobinson** [comment]
Do we want to pull this into 0.17.1 along with the other line chart fixes? I think it's just a matter of having the query processor annotate the fields with the breakout/aggregation information, and adding checks to `isMetric` and `isAggregation`.

**Comment by agilliland** [comment]
I think this should be a 0.18 thing.  We should keep the patch releases strictly focused on bug fixes.

**Comment by salsakran** [comment]
@tlrobinson did this get fixed in PR #2563 ? 

I'm still seeing the same behaviour on staging.

**Comment by tlrobinson** [comment]
No it didn't. I suggested we change the query processor annotate columns as aggregations or breakouts and use that in `isMetric` and `isAggregation`.
