### ISSUE TITLE
Add a "Ask This DB a Question" (or other "next step") Button to the DB added confirmation dialog box

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2558]
I find myself doing this a lot: 
1.  Adding a new DB
2.  Pressing "Done" on the confirmation modal (pictured below)
3.  Exit Admin
4.  Press New Question
5.  Pick my DB from the list

![screen shot 2016-05-06 at 3 53 37 pm](https://cloud.githubusercontent.com/assets/1455846/15087996/2c0cf38a-13a3-11e6-8d78-d5f9da00222f.png)

It would be handy, IMO, if the dialog had an extra button that combined steps 3-5 for me.

**Comment by salsakran** [comment]
Generally, I'd say for most people adding a DB will be a very infrequent action. So not sure how much we should optimize that workflow. Is this in the context of development / testing or in actual Real Life use?

**Comment by mazameli** [comment]
Might be more interesting to think about putting a link to `Ask a Question About This` on table details in the Data Model, particularly if we ever merged the Admin Panel with the rest of the app.

**Comment by mazameli** [comment]
So, I don't think the go-ask-a-question flow is actually something that's very common for real users, nor do I think we even want to encourage it, because it takes a few minutes for us to analyze the DB, so pushing a user to ask a question of the DB right away is likely to cause them to run into some weirdness with the query builder.

I do like the idea of having a button to take them to the metadata section, though isn't that going to have the same problem of displaying incomplete info until the analysis is done? In any case, here's a comp:

![artboard](https://cloud.githubusercontent.com/assets/2223916/17607795/e3c00ef6-5fdc-11e6-96ad-2f37d00cc33c.png)

**Comment by tlrobinson** [comment]
I think asking a question or editing the metadata are going to be by far the most common tasks after adding a database, so it seems like the real solutions to that problem are a) optimizing the sync process to sync important stuff like the basic schema first so the database is usable more quickly, even if things like field values haven't been synced (we may have already done that) and b) adding some sort of indication for sync progress, i.e. #649

**Comment by salsakran** [comment]
we've added x-rays to this modal

![Screen Shot 2019-10-11 at 3 25 11 PM](https://user-images.githubusercontent.com/107439/66688410-584a4a00-ec3b-11e9-9d7b-68c0ec583a2d.png)
