### ISSUE TITLE
New custom columns won't appear in a dashboard card with reordered columns (custom viz settings)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#25592]
**Describe the bug**
If you did changed the order of the columns in a dashboard card, then editing the source question and adding new custom columns won't appear in the dashboard card. The only way to making them appear is to reset it to defaults and start the customization again

**Logs**
NA

**To Reproduce**
1) create a question (new->question->people), save it and add it to a dashboard
2) now edit the viz settings of the card and move some columns around, save the dashboard
3) now go to the question and add a custom column (like concat(name, email)), save the question
4) go to the dashboard, you won't see the custom column, not either on the custom viz settings
5) reset to defaults the card, now you'll see the column appear

**Expected behavior**
At least have the column in the hidden section so the user can add it manually without having to reset to defaults the card

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Metabase version: 1.44.3
- Metabase internal database: Postgres 14.5

**Severity**
P3

**Additional context**
NA

**Comment by wheeler-harness** [comment]
We're experiencing a variation of this behavior that's not limited to custom columns.

After updating a report that's already on a dashboard, report field additions and removals are not reflected on the dashboard instance. That is, in the dashboard instance of the report:
1. removed report fields are still present in the dashboard instance, and
2. added fields are not available to be added

**Comment by jeffmax** [comment]
I have noticed this happens if you've hidden any columns on the dashboard card as well.

**Comment by WiNloSt** [comment]
I haven't managed to figure out the solution yet, but I conclude the problem comes from the props we pass to `ChartSettingOrderedColumns` are different when we view this settings from
- dashcard -> viz settings vs
- question -> viz settings

*Disclaimer: The following info is a mixed of guessing and piecing info from troubleshooting so some info might be inaccurate.*

When viewing question viz settings directly we seem to use pass `columns` data from question's `result_metadata` while when viewing the dashcard viz settings, we pass `columns` data from `data.cols` from calling `/api/dashboard/*/dashcard/*/card/*/query` API, this creates a discrepancy between the different of columns the settings component get and result in the different behaviors like missing custom column.

There is a logic inside https://github.com/metabase/metabase/blob/d54caf88943c255fb6e51465041ee337a369ab59/frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx to determine what extra column it should display and maybe we could work something out of that.

But we also need to pass `question` as a prop to `ChartSettingsWithState` [here](https://github.com/metabase/metabase/blob/d54caf88943c255fb6e51465041ee337a369ab59/frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/ChartSettingsButton.tsx#L43). Since we pass already pass `question` when viewing question viz settings, but not viewing dashcard viz settings.

**Comment by npfitz** [comment]
Issue resolved and backported. The issue had to do with the way the visualization settings were merged between the source card and the dashboard card. The dashboard card settings take priority, but in this case we were just completely overwriting the source card table columns with the dashboard cards. The fix was to merge the 2 arrays

As a side note, @paoliniluis and @likeshumidity, it is possible that existing dashboards may show added columns after running this version, if folks didn't realize that this was actually a bug
