### ISSUE TITLE
Metabase not recognizing timestamp field

### ISSUE THREAD

**Issue by fmitchell** [metabase/metabase#2602]
Metabase isn't recognizing a field as a timestamp field making it difficult to group data over time.

The data is currently being pulled in via RJMetrics from a Segment.io warehouse and loaded into our Redshift cluster.

Screenshot of query builder: https://www.evernote.com/l/AOzaW-zl8DFL6YxSRVHvNtqhL87CqKuiX6A
Screenshot of schema: https://www.evernote.com/l/AOwJaZ2IaQhCUoTQfqlgMeeF4kQRBxb0UR8

As an additional test, I have Segment.io loading the same data warehouse (without RJMetrics) to another database inside of the same Redshift cluster and Metabase recognizes it as a DateTime field.

Screenshot of query builder: https://www.evernote.com/l/AOx17gf7jNJLB43vsUA5KtcCScj5T55ttFI
Screenshot of schema: https://www.evernote.com/l/AOyobhZmOR9IJ4gCAPbBDojfCH3FXxaSTUs

Is there a way to change the schema manually?

*  I am using the Chrome browser.
*  My computer's OS is OSX 10.11.4.
*  I'm running Metabase on AWS.
*  My database is Redshift.
*  My Metabase version is v0.17.0 built on 2016-05-02.

Possibly related to #1576

**Comment by salsakran** [comment]
It looks like the timestamp is being stored as a string in your screen shot. We don't currently parse date strings automagically, so I think you'd either need to look into getting RJMetrics to import it as a postgres/redshift  `timestamp with timezone` rather than a string. 

#1576 would fix this, but it's not currently scheduled. Do you have any control over what RJM does in terms of imported schema?

**Comment by fmitchell** [comment]
I don't. It's one of the reasons why I have it coming directly from Segment.io as a backup. I'll contact RJMetrics.

Great product and I'll work with what we have. Thanks for the response!
