### ISSUE TITLE
SSO with group sync mappings does not remove users from groups

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26079]
**Describe the bug**
SSO with group sync mappings does not remove users from groups. Historic #13820.

Workaround: Manual remove users from groups in Admin > People.

**To Reproduce**
1. Admin > People > Groups - create two groups, MB_1 and MB_2
2. Admin > Settings > Authentication > JWT
   1. Set signing key to `1111111111111111111111111111111111111111111111111111111111111111`
   2. Set group mapping `grp1` to MB_1
   ![image](https://user-images.githubusercontent.com/1447303/197516268-b424da19-7767-476d-b1dc-74d64f1d987c.png)
3. Login as JWT user via
`/auth/sso?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp3dEB0ZXN0LnRlc3QiLCJmaXJzdF9uYW1lIjoiSldUIiwibGFzdF9uYW1lIjoiVXNlciIsImdyb3VwcyI6WyJncnAxIl19.FXlfAwd7wZWJZwbRWdXwtpQZQ17TG6hRg5X5SjjlcHQ&return_to=/`
4. Admin > People - mapping is as expected
![image](https://user-images.githubusercontent.com/1447303/197516072-8592f2a8-f467-4ac5-a8f7-e2b5a8ca8635.png)
5. Admin > Settings > Authentication > JWT > Group Mapping > change `grp1` to MB_2, Save, and Save changes.
![image](https://user-images.githubusercontent.com/1447303/197517246-a869efc0-a87f-41dc-807a-073f63f9805b.png)
6. Login as JWT user just like step 3
7. Admin > People - the user is now in group MB_1 and MB_2, when the user should just be in MB_2
![image](https://user-images.githubusercontent.com/1447303/197517634-677b331f-e0f3-4bdc-947b-ed44f5e88969.png)

**Information about your Metabase Installation:**
Tested 1.44.5 with JWT and SAML, might behavior similar with LDAP.

**Comment by noahmoss** [comment]
I believe the current behavior is expected, at least according to the most recent update to group sync (which was [this project](https://www.notion.so/metabase/Overhaul-SSO-admin-group-sync-3b02520bc4e74fa19f7e40464a23dda6)).

The group mapping copy includes "Users are only ever added to or removed from mapped groups" which accurately describes what is happening here. In step 5, group `MB_1` is no longer mapped to any JWT groups, so we don't touch it on the next login. A workaround to remove a user from `MB_1` automatically would be to explicitly map it to a non-existent JWT group.

The main motivation behind the current behavior was that it enables an admin to create some groups which are not managed by SSO. Groups are essentially "opted-in" to being synced rather than all groups being synced automatically, which we did in the past. But I'll cc @luizarakaki to confirm that this is the desired behavior. Perhaps we could rethink the UI in some way to clear things up, since there seems to be confusion from both the former and current logic.

**Comment by noahmoss** [comment]
For internal folks, [here's a product discussion](https://metaboat.slack.com/archives/C03E3Q5T4P4/p1666706997616559) on this. The conclusion is basically that the current behavior is correct, but we could add some more user education when you unmap a group about the fact that users aren't removed automatically.

@flamber I'll leave it up to you how this should be prioritized/categorized based on this

**Comment by flamber** [comment]
I'll leave it prioritized as is, since the current behavior is incorrect and the in-app helper text says something different from the "correct" behavior, and the documentation is extremely vague about the specifics.
It would be like if we synced attributes, but never deleted attributes that aren't present on the IdP (feature request #21682).

**Comment by noahmoss** [comment]
@flamber could you clarify how the current behavior is incorrect? The group mapping UI says "Users are only ever added to or removed from mapped groups" which I think accurately describes what's currently happening

**Comment by flamber** [comment]
I don't even know what that means. It should probably either be written completely technical or in human-language.
I thought "sync" means two ways, but I'm guessing we only support one-way-sync. If that's the case, then we can close this issue and change #21682 to a bug.

**Comment by noahmoss** [comment]
Oh, interesting, I didn't realize that wording was a source of confusion.

The way I interpret it (and the current behavior) is that two-way sync applies to the set of Metabase groups that have mappings set up to SSO groups. If a Metabase group doesn't have a mapping set up, we don't touch it.

I'll mention in the Slack thread that the wording might need to be revised.

**Comment by noahmoss** [comment]
Closing now that https://github.com/metabase/metabase/issues/27212 is closed, which is a substantial refactor to the group mapping UX which hopefully should make everything clearer
