### ISSUE TITLE
[P1] Auto-Select Action Database based on Model

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26348]
_Will assign to Agnes when she creates a GH account._

We currently ask people what model to add an Action to _after_ they've created it. It may be smoother to first ask where the action should go, and then create it (which would allow us to pick the DB in the editor already).

This issue means to capture the design work, which may or may not get built depending on what we discover.

**Comment by agnes-pinhanelli** [comment]
**Design:** WIP

**Comment by agnes-pinhanelli** [comment]
For documentation: 

The designs above were based on what we see on` data-apps-main` but @ryancw is working on the branch `data-apps/data-ref-action-creator` that already changes this behavior. 

From Ryan: This removes the global "add action" button completely, and you can only create actions from a model detail page or the add-action sidebar, so it always auto-populates a model to start with (but allows you to change it). 

So if you're creating an action from a model, we don't really need this design, because it already shows the model selected in the modal, and you are in the model detail page so that's enough context imo.

But I suggest that when we're creating an action from the add-action sidebar, we flip the logic and [show the save modal first](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=2005%3A29237), so that we can pick the model it should live in, and go from there. 

Another comment was "we don't auto-select a DB, but I think we could" – and yes, that would be nice.

[More details in this thread. ](https://metaboat.slack.com/archives/C03SX8EDNC9/p1668103066393049)
