### ISSUE TITLE
[P2D] Update drill copy on object details to remove "filter" reference which is awkward always, but especially in data apps

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26446]
Clicking on values in a detail view offers me to "filter on that value". It could be useful in odd situations, but is it worth keeping? Is it worth blocking?

**Comment by kdoh** [comment]
I'd vote we just disable it for now.

**Comment by kdoh** [comment]
Current thinking is we should keep drill always (no dead ends is a god thing) but that rather than keep the existing copy we should change it to be better regardless of the context of data apps or not.

The updated drill copy should take the form of `See <table name plural> with the same <field name>`. So in the case of a user you'd see `See Users with the same Birthday`.
