### ISSUE TITLE
Use of global search multiple times very fast can cause blank screen under certain conditions

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26466]
**Describe the bug**
When going to the search page very fast multiple times with the same search string can lead to the frontend crashing.

**To Reproduce**
1. Native > Sample > `select 1` - save a "Break search"
2. Use the global search - type "break" and press enter, so we go to the search page and should list the question created in step 1
3. Click the search result to go to the question
4. Either move or archive the question - any action that triggers a toast notification
5. Very quickly, before the toast message disappears, use the global search and type "break" and press enter - frontend crashes with blank screen

```
Uncaught TypeError: Cannot read properties of null (reading 'id')
    at M (utils.js:35:40)
    at getCollection (questions.js:79:19)
    at W.G.<computed> [as getCollection] (entities.js:594:24)
    at M (InfoText.jsx:35:16)
    at Qo (react-dom.production.min.js:153:146)
    at xa (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

https://user-images.githubusercontent.com/1447303/201517862-22296593-33b2-40e9-a57e-af4a8b1e24ac.mp4

**Information about your Metabase Installation:**
Tested 0.44.6

**Comment by iethree** [comment]
Still exists on 46. I think this occurs when there is some missing/outdated collection metadata related to the root collection.

https://github.com/metabase/metabase/pull/30082 adds an error boundary to the search bar so that the whole app doesn't crash anymore.

![Screen Shot 2023-04-25 at 3 16 07 PM](https://user-images.githubusercontent.com/30528226/234410426-8f695bac-6f36-41b2-86dc-ef1b8ec06aa9.png)
