### ISSUE TITLE
Page hangs when deleting database / takes forever to delete

### ISSUE THREAD

**Issue by robinfrick** [metabase/metabase#2655]
I'm trying to delete a database but it doesn't work. On the front end the button isn't reacting. If I look into the console I see two bad requests and one timeout. This happens both on the Database overview page and on the Database details view.
I suppose each error correspond to a failed try from me. 
![image](https://cloud.githubusercontent.com/assets/8144392/15507869/8a8329a6-21cd-11e6-9342-db510a1ad638.png)

If this is a bug report, please fill in the blanks:
-  I am using the Tested on both Chrome and Firefox browser.
-  My computer's OS is Mac, also tested on Chrome Ubuntu.
-  I'm running Metabase v0.17.1. on AWS
-  My database is Postgres.

**Comment by robinfrick** [comment]
Ok the server is deleted now (~10min after the first attempt). I suppose it just took a very long time and Metabase didn't give me an error message. Any indication that I need to wait a long time.

**Comment by camsaul** [comment]
That's weird. It shouldn't take 10 minutes to delete a database. Have you ever had this problem before?

**Comment by robinfrick** [comment]
Luckily I don't have to delete databases frequently. So no, haven't experienced it before.

**Comment by camsaul** [comment]
+1 from #3259

**Comment by camsaul** [comment]
I'm guessing what's happening here is that the page is hanging while it waits for the `DELETE /api/database/:id` endpoint to return. The endpoint runs the `cascade-delete!` logic on the database which recursively calls the function for every object belonging to that DB, so it could be making several hundred DB calls here.

I guess our options are either:

*  Have the API endpoint run the `cascade-delete!` logic on a background thread and return instantly
*  Don't block the UI waiting for the endpoint to return (perhaps show a little "Deleting..." animation)

The second option is probably the better of the two since we could run into the same scenario if someone's internet connection barfs and the endpoint never returns

**Comment by salsakran** [comment]
Preference for the second, so that errors get surfaced.

**Comment by camsaul** [comment]
We can probably debug this locally by just sticking a `(Thread/sleep 30000)` or something in the endpoint code to force it to take a long time

**Comment by Slayr** [comment]
+1 to that, occured to me this week, On Mongo and MySQL databases across different instances each of these databases have 100+ collections/ tables.

**Comment by vinceall** [comment]
Is it possible to add an "archive database" functionality instead of deleting it physically? Since users just want it gone, so we can make it very fast and get away from the timeout situation.

**Comment by flamber** [comment]
@vinceall 
There has been several optimizations, so deletion of a database shouldn't take long anymore.
Where are you seeing the timeout from? Are you using a reverse-proxy in front of Metabase?
Have you tested with latest release 0.35.1?
You can open a new issue to request an archive/disable database functionality.

**Comment by vinceall** [comment]
> @vinceall
> There has been several optimizations, so deletion of a database shouldn't take long anymore.
> Where are you seeing the timeout from? Are you using a reverse-proxy in front of Metabase?
> Have you tested with latest release 0.35.1?
> You can open a new issue to request an archive/disable database functionality.

Yeap, I use a Nginx in front of metabase, I'll try the latest version, thx
