### ISSUE TITLE
[P2N] For scaffolded views, navigate back to the list after deleting

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#26584]
We already know the association between scaffolded list / detail views but not sure about non scaffolded ones.

**Comment by iethree** [comment]
This is tricky because there's currently no way to detect if a page is a scaffolded detail page, and hard-coding behavior onto delete implicit actions feels like a very hacky solution - and could introduce weird behavior when adding delete buttons to non-scaffolded detail pages.

One stop-gap is maybe to only "go back" after delete on nested pages, but probably the correct way to do it is to introduce a sort of "chained action" where you can configure something to happen after an action executes.

**Comment by iethree** [comment]
The more I think about this, the more I think we should not do this. I don't think we should build functionality into scaffolding that users cannot create for themselves. Once we have the ability + data structure to define "after X go to Y", it makes sense to scaffold it for users, but I don't like this sort of bespoke, hidden, hard-coded behavior. I think it's a recipe for user confusion (why doesn't my custom delete action do this?) and bugs (e.g. it being very non-obvious that if we change the nav structure that it will break the scaffolded-after-delete-redirect)

**Comment by brunobergher** [comment]
Agreed, closing.
