### ISSUE TITLE
[P2D] The primary button in forms (which runs the action) should have a spinner/disabled/waiting state (or maybe the modal should be closed anyway)

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#26585]

**Comment by iethree** [comment]
currently, the button gets disabled during form submission while waiting for a response. This is the same behavior as all other forms in the app. Do we want to do something different?

spinners get tricky because you have to detail with changing widths, etc.

![disableUpdate](https://user-images.githubusercontent.com/30528226/207982529-314bc2be-a2eb-4b15-a6c9-0d662968904f.gif)

**Comment by kdoh** [comment]
I think what you have in the GIF there works for me, I think the big thing in this not so great issue title was just making sure we had a solution that would prevent double submissions and "did anything happen?" confusion and looks like we're there. 👍
