### ISSUE TITLE
New display_name logic capitialized "reciever_id" as "Recieve R ID"

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2660]
Working on a new "Avian Singles" test database and saw this 

![screen shot 2016-05-24 at 12 29 02 pm](https://cloud.githubusercontent.com/assets/1455846/15517170/397edfc2-21ab-11e6-9dac-697ad70fa2ad.png)

**Comment by camsaul** [comment]
Another bit of weirdness is `url` is getting capitalized as `URL`

**Comment by tlrobinson** [comment]
I used a word frequency list generated from a subset of Wikipedia. We should audit the 1-2 character words and make sure they make sense to include. I think we can take out "R"...

It's also probably worth dumping all table and column names from all the schemas we have access to and verifying the results make sense.

**Comment by camsaul** [comment]
how does the algo work? I think it would make sense to prioritize a single, longer-length word like `Receiver` instead of 2 shorter words like `Recieve R`

**Comment by tlrobinson** [comment]
I'm re-opening this since it's clear we need to aggressively trim down the word list, in particular 2-3 letter words. http://discourse.metabase.com/t/weird-spacing-of-table-and-field-names-on-v0-18/498/3

**Comment by camsaul** [comment]
I think the problem here is just that the dictionary is English-only. It's still going to incorrectly break words in other languages whether we take out small words or not

**Comment by tlrobinson** [comment]
If we cut down the list enough (in particular short words) I think it will still work well for common English words but not break up foreign words.

It would be nice if we collected table / field names and could build a word list based on actual usage.

**Comment by jlowin** [comment]
Came across this issue because this feature has decimated an enormous database. Is there an easy way to turn it off or selectively roll back the changes? To be sure, when it works, it's wonderful. But wherever we have abbreviations it's terrible, even common ones like "MTD", "QTD", or "YTD". Here is a sampling of some of the thousands of affected tables and columns:

"Gl Tr An" (gltran, general ledger transactions)
"Ac Ct Hist" (account histories)
"Cu St Class" (customer class)
"Cu St Com Mis Class" (customer commission class)
"Cu Ry Ac Ct Orig" (original currency account)
"Pr Oj In I Nv Pr Oj All Oc By Wh Se" ??
"Pr Oj Ed Dr Ece Iver" Project Receiver ??

**Comment by tlrobinson** [comment]
@jlowin This should only happen when you first add a new database to Metabase (or tables/fields to a db already in Metabase)... or did it happen on tables/fields you already had in Metabase?

If it's the former you could delete the recently added database and roll back to a previous version of Metabase, or as a workaround to disable this feature in the current version of Metabase, run these commands on the jar  (zeros out the word list, which effectively disables this feature):

```
touch words-by-frequency.txt
jar uf metabase.jar words-by-frequency.txt
zip -d metabase.jar 'META-INF/*.SF' 'META-INF/*.RSA' # removes our jar signature, since it will no longer validate
```

If neither of those solutions are sufficient we can push out a v0.18.2 release that disables this feature.

If we actually somehow screwed up a database you already had in Metabase let me know and we'll figure out a way to reset the humanized names.

Apologies to every affected by this... clearly it needed a lot more testing. If you would like to submit your schema (or just the table/field names) to me for testing that would be super helpful in ensuring it works well, please email it to tom@metabase.com

**Comment by tlrobinson** [comment]
@jlowin Also, I'm a little confused by some of those names. Was the last one originally called `projeddreceiver`, for example? All it should be doing is adding spaces and capitalizing the first letter of each word, not changing any letters.

**Comment by jlowin** [comment]
@tlrobinson it's an annoyance but not the end of the world, since discovering Metabase last year it's made a big (positive) impact on our team -- and that's probably why the UX effects of this issue were deeply felt!

This is a new database in Metabase, but it happens to be identical to one already in Metabase that we reloaded as of a different date for to examine how some tables had changed. I was confused because we did the same thing about a month ago with no issue, but I believe we're running Metabase in Kubernetes with instructions to always pull the latest image, so it probably restarted recently and updated itself. I will try the workaround -- I personally don't require an 18.2 release but you may want to consider it since a number of users who come to Metabase for the first time on 0.18.X will encounter this and may not know to undo it later.

To be totally honest I'm not 100% sure what that last column is an abbreviation of -- Perhaps "Proj[ected] EDD Receiver". It and the example above it are both cases where extensive abbreviations were used in the column names.

To be clear, I am all for this functionality in general (especially having spent a few hours doing it by hand in other databases) however I think it needs to be implemented in a way that makes it easy to turn on selectively and should only be done automatically where the word split is very obvious (for example, long words in the most common 1000 words in the English language). There are far too many instances where databases are going to have names that aren't necessarily concatenations of full English words to make this universally applicable.

Thanks!

**Comment by salsakran** [comment]
I also think we should provide a way to undo humanization if things get borked. It could be command line if that's easier.

**Comment by tlrobinson** [comment]
I played around with cutting down the word list a bit but had trouble eliminating the issues with non-English words, so maybe it's better to just remove this for now, or make it opt-in.

**Comment by salsakran** [comment]
👍 for making it opt-in or even opt-out. But the ability to say "hey, that didn't seem to work,nevermind" is imo very important.
