### ISSUE TITLE
Admin > People > Last Seen is not accurate

### ISSUE THREAD

**Issue by marketingnerds** [metabase/metabase#2668]
Showing "14 days" for my account, which might be the last time I authenticated or was cookied. Maybe this should be based on activity?

If this is a bug report, please fill in the blanks:
-  I am using the ____chromium_______ browser.
-  My computer's OS is **_linux_____**_.
-  I'm running Metabase **on AWS_**. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
-  My database is **_mariadb_____**_.
-  My Metabase version is **_0.17.1_____**_.

**Comment by tlrobinson** [comment]
Yeah, looks like we're currently using `last_login` for that. Not sure if we keep track of a true "last seen" yet.

https://github.com/metabase/metabase/blob/master/frontend/src/admin/people/components/AdminPeople.jsx#L383

**Comment by salsakran** [comment]
@marketingnerds did this come up in scenario where you wanted to get the time a user was "last seen" or was it just a matter of checking and having it look odd?

If the latter, we should probably just re-label that column "last login" as that is what the field captures. 

If the former, would you mind giving us a bit more context? It will involve new functionality, and we'd like to do our best to solve the underlying problem/workflow vs a symptom "downstream" of your actual problem.

**Comment by marketingnerds** [comment]
@salsakran that's a good point re: changing the label to "last login." In my case, I was thinking that I could use that value to get a sense for user engagement. This starts to get into a feature request rather than a bug, i.e. it might be nice to see a user's action history, like the one on the welcome screen, to gauge that user's engagement or just to follow along on their progress. I guess what I'm saying is that the recency of activity is, in my opinion, a proxy for assessing how users value the solution.

**Comment by tlrobinson** [comment]
I think I'd also prefer "last seen" to "last login" since, as @marketingnerds points out, it's a better sign of engagement. "last login" depends on things such as the number of different browser the user uses, the cookie expiration period, whether they clear their cookies, etc, while "last seen" would update any time a logged in user is "seen" on Metabase.

As far as implementation of tracking "last seen", could we just add a field to the user table with a "last_seen" field and update it on certain conditions? We probably wouldn't want to update it on *every* action (at least not without some rate limiting), but maybe whenever the user loads the `index.html` or successfully logs in.

**Comment by javiercr** [comment]
+1 for "last seen" vs "last login", if you're sharing your metabase with potential investors, it's a good signal of "engagement" :)

**Comment by salsakran** [comment]
closing as this was switched to "last login" in the app
