### ISSUE TITLE
Pie Chart Percentage shows wrong value while using Sum

### ISSUE THREAD

**Issue by sranes** [metabase/metabase#26690]
**Describe the bug**
I have summarized data for gender demographic (Male - 125 and Female 38). To plot this as pie chart, I used the SUM (value).
While the data is coming properly, the percentage is shown incorrectly.

**Logs**
The data for the chart is as below
--------------------
Gender      |     Value
--------------------
"Female"   |    38
--------------------
"Male" 	  |   125
--------------------

**To Reproduce**
1. Create a table with values
2. Create a new question
3. Use SUM(value) in the Summarize section
4. Group by Gender
5. Use Pie chart for visualization 

**Expected behavior**
For "Female" the percentage should be shown as 23.31 and Male 76.69, whereas it is shown as 0.23312... for Female and 0.76687... for Male

**Screenshots**
<img width="767" alt="Diversity" src="https://user-images.githubusercontent.com/16079361/203492880-e4f3ffee-8af2-4848-aeb3-676068c0cff5.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome Version 107.0.5304.110 (Official Build) (x86_64)
- Your operating system: Mac 13.0.1
- Your databases: Postgres
- Metabase version: v0.44.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
While this is not blocking, it is showing the wrong data.

**Comment by flamber** [comment]
@sranes It's caused by the Sum field is using "Category" as it's field type. Change it to "No semantic type" then it'll work.

Reproduce:
1. Admin > Data Model > Sample > Products > Rating > change Field Type to "Category"
![image](https://user-images.githubusercontent.com/1447303/203985073-fdcc8b38-212a-41fb-8a75-1f801a4f06d0.png)
2. Question > Sample > Products > summarize Sum of Rating grouped by Category
![image](https://user-images.githubusercontent.com/1447303/203985196-81135501-9980-47cf-afcf-4f4b4ba2d294.png)
3. Change to Pie chart
![image](https://user-images.githubusercontent.com/1447303/203985304-b2463537-9d04-45c7-aab8-2fa4b5cb236f.png)

**Comment by sranes** [comment]
Hi @flamber , You are right. Once I changed the type to Numeric, it shows correct percentage.
