### ISSUE TITLE
Adds Series button not working, difficulty finding out corrupt question

### ISSUE THREAD

**Issue by marcelommm** [metabase/metabase#26871]
Hello!

"Add Series" button is not working in our instance, for multiple users.

Same issue as described in #15222 , there is a suggested solution, iterating through each question manually in frontend. But we have more then 1800 questions, hence it's not quite doable.

All our jsons in **report_card.dataset_query** seem valid, and we don't have any empty. We do not know what to look for **report_card.visualization_settings** that means it's corrupted.

Below a snapshot of our report_card table, if you would be kind to point out the corrupted questions or a method to find out, would be eternally thankful.

[report_card.csv](https://github.com/metabase/metabase/files/10134139/report_card.csv)
[diagnostic_info.txt](https://github.com/metabase/metabase/files/10134165/diagnostic_info.txt)

**Comment by BertrandToulas** [comment]
Hi! Like I suggested in #15222 , if you need the problem solved quickly (i.e. before version 0.45 is out, since solving that bug is now one of its milestones), the iterative process I detailed is surprisingly doable as a one-time thing. Not ideal, mind, but doable. In our case, I forgot to mention that we had roughly half as many questions as you do in your organization, and that I had to do all the debugging myself, but it took me "only" half a workday anyway. If you can afford to devote a day to the task, that should be more than enough for you to track down the corrupt questions, especially if you can share the workload with one of your teammates. Good luck!

**Comment by marcelommm** [comment]
Hi @BertrandToulas thanks! I tought it was easily identified through report_card table output. The problem would be spending a day on it. But thanks for your reply.

**Comment by paoliniluis** [comment]
Thanks @BertrandToulas. As you mentioned, the issue is https://github.com/metabase/metabase/issues/15222
