### ISSUE TITLE
Aggregating with Custom Column first doesn't show sub-totals in pivot table

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#26919]
**Describe the bug**
When aggregating with Custom Column and this column is placed first in a pivot table it doesn't show totals when collapsed. This doesn't happen for all Custom Functions but was able to replicate for the `case`

**To Reproduce**
1. Go to New -> Question -> Products
2. Add Custom Column -> `=case(isnull([Category]), [Category], [Category])` -> Name it test
3. Summarise by Count -> Aggregate by Test and Rating (Auto Binned)

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/110378427/205320488-435a9f57-42b6-4ee0-854e-d8a436d278a8.png">

4. Click Visualisation -> Pivot Table -> put test as the first column

<img width="823" alt="image" src="https://user-images.githubusercontent.com/110378427/205320660-757373ae-a736-4322-8e7e-7c08f17fcc54.png">

5. Notice how values when collapsed don't show.

**Expected behavior**
If we swap the Rating before the test you will notice that the collapsed rows have values

<img width="866" alt="image" src="https://user-images.githubusercontent.com/110378427/205320950-313dd86c-43d0-41f7-9d77-a13563fa7f0b.png">

**Information about your Metabase Installation:**

Tested on 1.44.6 and 1.45

**Comment by flamber** [comment]
Note that fixing this issue would prevent it being used as a workaround for #14979

Workaround:
1. Create just a question without aggregation (or change it into a Model)
![image](https://user-images.githubusercontent.com/1447303/205492215-c71268b6-c45b-4cf8-9aad-96372f28f90a.png)
2. Then use that Saved Question (or Model) to apply aggregation
![image](https://user-images.githubusercontent.com/1447303/205492277-735a1c31-3d1b-4dd7-9018-d72fbd82522a.png)
3. Here's an example of the Pivot Table with two collapsed rows
![image](https://user-images.githubusercontent.com/1447303/205492344-07d097b7-6667-494c-9d52-ff3470654f16.png)

**Comment by npfitz** [comment]
Dug into this today. This is happening because when the custom field is added as a breakout, we are adding the expression field_ref with an `null` options, so it looks like `["expression", {{name}}, null]`. This is provided by StructuredQuery.breakoutOptions(), but doesn't line up with what we have in the column settings in `pivot.js -> getPivotColumnSplit()`. Interestingly enough, when we reload the page (and thus load the query from the API), the null option is removed from the breakout and things work as expected. I'm assuming the fix here is to adjust how the breakout is added to the query

**Comment by kamilmielnik** [comment]
I can reproduce in v46, v48.
Cannot reproduce in v49.
Can't reproduce in `master` at 53955c281e.
