### ISSUE TITLE
Calculated columns for Druid driver

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#2693]
Druid driver doesn't support calculated columns at the moment.
Its possible to do this in druid using post-aggragations http://druid.io/docs/latest/querying/post-aggregations.html

**Comment by moumny** [comment]
BTW: There is https://github.com/implydata/plyql that can be used for druid driver
At the moment it doenst work with the MySQL driver because CREATE SHOW TABLE is not implemented yet.

**Comment by salsakran** [comment]
@moumny after playing with this + a possible approach in branch https://github.com/metabase/metabase/tree/druid-calculated-columns , a couple things have surfaced that make this a bit dicey. We'd love to get your feedback on a few things.

**By way of background, our expectations of normal calculated columns**

I can create a fake column using MATH + any column in the table
* I can use that fake column in
* aggregations
* filters
* groupings
* downloaded csv's
* raw data

With the following possible in the future
* I can save fake columns in a semi-virtual table?
* I can take the raw data + fake columns and save it as a starting point for subsequent question?

**Issues with Druid:**

Select columns don’t have aggregators or post-aggregators 

Filter clauses can’t filter on aggregations
--> you’d need to either do them as “extracts” i.e. transformations on a single dimension
these don’t correspond directly to SELECT items in SQL

Can’t group by aggregations
--> need to do as extracts or single dimension whatnotery

**Possible approaches:**

*Use Druid post-aggregators*
Pros:
* Happens in druid → a single place for type, date, etc quirks
* Performant
* no moving parts server-side

Cons:
* Can’t filter or group by the column unless it’s expressible as an extract --> Means you can’t do this for the timestamp directly → You’d need to use intervals here
* Raw data doesn’t have calculated columns
* Can only use aggregated columns or post-aggregators 
--> So for dimensions, we’d need to create a custom JS aggregator to roll it up somehow. Not sure this would work in all situations
--> Since timeseries queries don’t accept dimensions

*App-server post-aggregation*
pros	
* Raw data has calculated columns
* ability to provide almost any functionality given the data present in the result set (or accessible by the app server)

Cons
* moving parts in the app server
* Can’t filter by the column

*Javascript aggregation*
Pros
* Happens in druid → a single place for type, date, etc quirks
* No moving parts server-side 

Cons
* Raw data doesn’t have calculated columns
* CSV downloads wouldn’t have them
*Can’t filter or group by the column unless it’s expressible as an extract

The branch above uses the "app server post aggregation" approach, but that still leaves a ton of holes in expected functionality.

Could you share the kinds of uses you foresee for calculated columns? We're kind of at a point where none of the approaches really provide a seamless experience, and it might make sense to instead try to take the effort and ship #3365 if that will cover you situations.

**Comment by moumny** [comment]
Thanks for taking a look at this.
I dont know what would be the effort required for each solution but for us the first solution would cover all the usecases we have. This is generally summing two timeseries or dividing one by a constant etc... In druid world it is accepted  to not filter and group by on metrics. 

While it would be nice to have all the other features the blockers for us is being able to ask for things like:
(sum of metric A + sum of metric B / sum of metric C) / 1000

Let me know if you have more questions

**Comment by Digma** [comment]
Hi,

Thanks for working on this. As @moumny said, summing metric would be an important feature for us. Having calculated columns in Raw data would be a plus although it is not primordial. As he said, filtering or grouping on a calculated columns is not provided by Druid so I don't think it is a big con if this is not implemented in metabase.

I tried playing with the last version of `druid-calculated-column`. I manage to create new columns in raw data mode properly. However I do not manage to do any of the operators ("sum of ...", "average of ..."). I get a `No matching clause:` error.

Maybe my flow is not correct:
1. I create a custom field which is a sum of two fields (defined as Number in metabase Data Model
2. "Sum of ..." this new field
3. I get an error (you can find my log in the text file below)

[druid-calculated-column_sum_error-log.txt](https://github.com/metabase/metabase/files/493517/druid-calculated-column_sum_error-log.txt)

**Comment by salsakran** [comment]
On thinking more about this and talking it over with @camsaul , There seems to be a bit of a mix up in this conversation. Specifically I think there is a conflation between "calculated columns" which is when we create a fake "field" in the underlying data that can be used in aggregations, and post-aggregation math (#3365 ).

What you are describing is #3365, which has a few UI elements missing, but which we're planning on getting to soon. This issue will remain for calculated columns themselves, but it sounds like there isn't really a clean way to do this in druid.

**Comment by moumny** [comment]
Thanks for the explanation. I understand now that calculated column would be the wrong way to achieve #3365. Let's wait for that instead then !

**Comment by salsakran** [comment]
this is closed via #3876, which provides both intra-row and post aggregation calculations. merged into master, so kick the tires if you have a chance!
