### ISSUE TITLE
Should we prevent or warn people when graphing "raw data"?

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2708]
Someone asked me why they couldn't make a multiseries out of two cards with the same breakouts, and it turned out the cards were something like `raw data, by created_at and total`, which happens to graph basically the same as `sum of total by created_at` (assuming the raw data query isn't truncated to 2000 rows) due to the way our dc.js graphing code works (it basically sums up rows where the X value is the same), but it's clearly not the right way to get that result. It's also not great because we only show the "Showing max of 2000 rows" warning when showing the table.

Could we somehow warn or otherwise push users in the right direction when they do something like that?

**Comment by salsakran** [comment]
I think this is a symptom of a weak charting system. Graphing raw data is often pretty useful, and I think we should allow people to have more control over which series goes to which axis instead. 

#612 is in 0.19, and I think that would help out here.

**Comment by camsaul** [comment]
Our charting system is a fortnight! 2 week.

**Comment by tlrobinson** [comment]
I don't think #612 really addresses the problem I'm talking about. If the query returns this for example:

created_at | total
------------ | -------------
2016-01-01 | 10
2016-01-02 | 15
2016-01-02 | 12
2016-01-03 | 5

Should we really be doing an implicit client-side aggregation that results in this:

created_at | total
------------ | -------------
2016-01-01 | 10
2016-01-02 | 27
2016-01-03 | 5

And if the query is truncated at 2000 rows we're definitely showing an incorrect chart.

Or are you suggesting picking the columns to chart on a raw query will modify and re-run the query?

**Comment by camsaul** [comment]
If the query returns new clothing, is that post-traumatic dress syndrome?

**Comment by salsakran** [comment]
Ahhh, got it. 

Yeah, I'm not sure what to do in that case. An underlying assumption in graphing two columns as x and y axis in a line chart is that there is only one value. Warning does make sense when that assumption isn't true.

**Comment by camsaul** [comment]
A feel like a tailor could address this issue

**Comment by agilliland** [comment]
I'm not sure exactly how to fix this case, but I will say that my vote is that charting code should very explicitly avoid manipulating the underlying data.  Allowing charting code to modify data is a guaranteed way to introduce inconsistencies into the system and I believe that in almost all cases the best approach is to use the querying process as the mechanism for properly describing the data shape, then simply expecting the charting code to use the data as provided or give a warning/error if the data shape is incorrect.

I believe there are some data operations that may still take place in charting code, but those should be limited as much as possible and white listed only if we are sure they are safe.  For example, pie charts sum up the metric value so that a % of total can be calculated, which is safe and doesn't disrupt the original data.

**Comment by tlrobinson** [comment]
I think the original problem could be solved by some subset of the following:

1. always showing the 2000 rows truncation warning, not just on tables
2. being smarter about what can be combined in multiseries, and how
3. requiring the user manually select columns when charting "raw data"
4. warning if there are duplicate values for the dimension (i.e. the data isn't aggregated)

At least # 3 has implications for #2931

**Comment by mazameli** [comment]
> always showing the 2000 rows truncation warning, not just on tables

I like it.

> being smarter about what can be combined in multi-series, and how

sgtm

> requiring the user manually select columns when charting "raw data"

Yeah, I think we can probably try to make some special-cased guesses (like with 2 or 3 columns), and then pop open the field selection part of the relevant options modal as a fall-back.

> warning if there are duplicate values for the dimension (i.e. the data isn't aggregated)

A little bit of a tangent, but I have an overall nagging concern that, since `raw data` is our default `View` option, and that you can now graph raw data, that, even if you ask the user to select which columns to plot, less sophisticated users are going to have a hidden assumption that some kind of aggregation is happening. Like, "yeah, I want to see the `Subtotal` column plotted by `Ordered At`," and then they'll end up either seeing warnings or a bunch of unaggregated data points. I think we should probably show this to a few people in person to see if they make weird assumptions.

**Comment by tlrobinson** [comment]
Yeah, that last suggestion was specifically to address the original "implicit aggregation" problem, which will be exacerbated by allowing users to pick columns on raw data queries (although the original problem wasn't with raw data but two breakouts, and it's no longer possible to chart that anyway). I wouldn't even consider the user who originally reported this to be "less sophisticated".

I think special-casing default columns (which we already do) for non-"raw data" structured (including all native) cards is fine since the user has some control over the resulting columns. However for "raw data" structured queries the column order is defined by the table schema (I think?), so if it fits a special case that's pretty much due to luck. Requiring the user pick the columns for a "raw data" query would suggest (either implicitly or explicitly via a warning message) they're doing something slightly out of the ordinary.

If they then pick columns that appear to be un-aggregated then we can show a warning, something like "It appears you are trying to chart unaggregated (?) data, which is not recommended. Click here for more information." We could only show the warning in the chart settings modal so if they decide it's ok it won't appear any time someone views the question.

**Comment by mazameli** [comment]
Cool, I'm with you.

Maybe, if the user is looking at `raw data`, and they change the visualization setting from a table to a chart, we could give them a modal before showing them the chart options that says,

"We don't recommend charting with **raw data** unless you know what you're doing. Most of the time it's better to [change your **View** option]() to something else before charting." (That link would close the modal and open up the `View` menu.) Then have two buttons: `I know what I'm doing` and `Cancel`. If the user ever clicks `I know what I'm doing`, we can stop showing them the warning. But inside the options modal, if they're looking at raw data, we can continue to have some small explanatory text:

"You're charting raw data, which won't combine or aggregate the numbers in the fields you've chosen. If you're trying to graph a sum, average, etc., [change your view option](url)"

I think it's so likely that a new user is going to run into this scenario that I want to make sure we can nip confusion in the bud.

**Comment by salsakran** [comment]
Food for thought:
There exist a LARGE class of tables (eg, rollups, data cubes, etc) where the point is to graph the table as-is. I wouldn't want a confirmation on this sort of thing on the regular.

**Comment by mazameli** [comment]
Yeah, that's why I was thinking it would be a one-time-only warning, that once you click past you wouldn't ever see again.

On a separate note, might be interesting in the future to have the ability to mark certain tables as rollups, cubes, etc. in order to hide or tuck away some (or all?) of the aggregation options to prevent people from accidentally doing something dumb.

**Comment by salsakran** [comment]
yeah, I'm just disagreeing with the idea that there's something at all different or strange about charting raw data. 

If I want a scatter plot of signup date vs user birth date, that's a perfectly normal thing to chart.

If we're talking lab data, then similarly there are going to be lots of records that are something that might be explicitly chartable.

I'd like to avoid over-specializing in the specific set of charting we're drawn to via the sample dataset or our early users have had. 

IMO this is a problem with how DC.js does implicit aggregations, and we shouldn't try to explain that away. 

There's nothing warning-worthy about someone wanting to chart two columns of numbers. 

Strong 👍  on having table/column metadata guide users to (or automagically figure out) the right visualization and aggregation choices.

**Comment by mazameli** [comment]
Cool, so maybe it's the language (I get that it's not esoteric to plot raw data, but that the proposed language makes it sound like it is). I'm just speaking up for the cases where charting a non-aggregated raw data table is going to give a new user something that _looks_ like the thing they want, but isn't actually what they think it is. 

Charting and charting options are probably a great candidate for some usability testing.
