### ISSUE TITLE
Give better names to aggregation columns returned by query processor

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2725]
Right now we are just returning things like "sum" and "count" for columns that represent aggregations in queries from the Query Builder.

We should consider how to give these more descriptive names. We should also discuss whether we want these to be user editable.

**Comment by timabe** [comment]
Now that you can do multiple aggregations in metabase, I think this issue is more relevant.

![screen shot 2017-03-22 at 4 54 08 pm](https://cloud.githubusercontent.com/assets/1427277/24225887/3d5e705e-0f20-11e7-9ae1-ab27352adc04.png)

I was expecting to be able to fix this by giving my own names to the columns by way of the gear icon.

**Comment by camsaul** [comment]
I thought we added the ability to give aggregations custom names in 22? I implemented backend support in #3915

**Comment by mazameli** [comment]
You can give _custom expressions_ custom names, but not basic aggregations, as far as I can recall.

**Comment by camsaul** [comment]
oh word :D

**Comment by joevandyk** [comment]
Yeah, this is getting painful for us :)

**Comment by mazameli** [comment]
This is super annoying still. If you have a bunch of metrics all using the same aggregation function, it's impossible to tell what the heck you're doing. Even though you can now rename these columns, it's really really hard to do so because the default names are indistinguishable, so you don't even know what the column _should_ be named.

A really simple suggestion would be to include the name of the column being used in the aggregation, e.g. `Sum of Subtotal` or `Avg of Quantity`.

![screen shot 2018-12-07 at 11 52 05 am](https://user-images.githubusercontent.com/2223916/49669660-e996d180-fa16-11e8-94bf-abf6e4a86be5.png)

**Comment by kurumpa** [comment]
I have no idea what i have just broken, but it might be a good start:
[annotations-patch.diff.txt](https://github.com/metabase/metabase/files/2979478/annotations-patch.diff.txt)
Cheers

**Comment by camsaul** [comment]
Implemented by #10245
