### ISSUE TITLE
Way to add a country map other than US?

### ISSUE THREAD

**Issue by zusamann** [metabase/metabase#2740]
Specifically I'm looking to add the map of UK as a data visualization. Currently I only see US and World map as the options. 

Is there a way to add another country?

**Comment by salsakran** [comment]
We don't currently, but are definitely interested in supporting other maps.

**Comment by zusamann** [comment]
How are the current maps (US, World) added to the tool? Is there a modular way in which similar maps can get added.

**Comment by MrMauricioLeite** [comment]
relates to #2737

**Comment by tlrobinson** [comment]
@zusamann unfortunately currently you'll need to copy/edit a couple source code files and recompile the application. Take a look at https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/WorldMap.jsx and https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/index.js and I can provide more help if you need it

@mrmauricioleite that issue isn't really related since its dealing with pin maps rather than "chorpleths" like the World and US State maps.

**Comment by MrMauricioLeite** [comment]
Sorry @tlrobinson

**Comment by shahinism** [comment]
We actually have tried to create a choropleth map using `Leaflet` library, Here is the result:
![selection_155](https://cloud.githubusercontent.com/assets/698857/16179440/3ff4614e-367b-11e6-974c-226a3e3f1aa5.png)
You can find the code here in FoundersBuddy/metabase@f1097386155f8a845fa31506ec627e32826f3a12. The process of providing such map is actually quite easy if you have proper `geojson` map data. For our scenario we used shape files from [here](http://www.gadm.org/country) and generated the `geojson` file for china map with a combination of [geojson.io](http://geojson.io) & [mapsharper](http://www.mapshaper.org/) tools. 
But our implementation there is not general enough (Actually we implemented it inside pinmap view for some reasons). This is why I didn't proposed a pull request :)
I think we can put some time to make this solution as general as needed. The process of generating `geojson` files can be automated, But my problem is with UI itself. We can't create a list of 196 countries in the menu right? 
I think it'll be a good idea to read `country` special field and load choropleth map for countries present in that field. It'll make it possible to create multiple chropleth map on a single view, probably inside WorldMap view. But the possible problem is the need to have `country` special field in data, which may make it un-compatible with older versions in use.
What do you think?

**Comment by tlrobinson** [comment]
Nice, it would be nice to unify our pin maps and chorpleths. I'll definitely look into this more.

**Comment by mazameli** [comment]
Here's a loose set of screens to help talk through how we might enable admins to manage custom maps and their corresponding geoJSON files.

1. First, the most logical place I could find to put this option was in a new menu item in the main Settings section of the Admin Panel. Right now the menu title is just "Custom Maps," but we could consider turning this in the future into a more general "Customize" section, which could even have a way to search for custom packages, etc.
![settings with new menu item](https://cloud.githubusercontent.com/assets/2223916/17870848/fb57f490-686d-11e6-9a19-1a1b6ec7b705.png)

2. The empty state:
![custom maps page](https://cloud.githubusercontent.com/assets/2223916/17870925/46b4f460-686e-11e6-85b5-062c1c64c655.png)

3. Clicking on `add a map` takes you to a new screen. It was either that or a modal (like we do for adding a new person) or doing some kind of inline addition (which I didn't think was appropriate since there are several required fields for the add map form). This interaction pattern is what we use for adding a new database.
![add new map screen](https://cloud.githubusercontent.com/assets/2223916/17870929/4ef5eb70-686e-11e6-8c18-bf30d53f7029.png)

4. After the user inputs the map's URL and clicks `load`, they're presented with dropdowns to let them pick from the file's props so they can pick the identifier and display name properties:
![map loaded](https://cloud.githubusercontent.com/assets/2223916/17871006/997496b0-686e-11e6-9467-cb76787e280c.png)

5. Here's the state with the props picked. One enhancement we could consider is having a `preview` button like I've shown here, which could open up the map in a lightbox or to the right. What's nice about that is it assures the user that they've linked to the correct map and that the selections they've made are working. Falling short of that, we'll want to do some basic error checking to make sure they've made valid selections.
![properties chosen](https://cloud.githubusercontent.com/assets/2223916/17871052/c1d054d2-686e-11e6-987c-e2d5c79df39b.png)

6. Once the map is added, it would appear in a list like this so that the user could edit or remove it:
![list of maps with new entry](https://cloud.githubusercontent.com/assets/2223916/17871127/1fb4d776-686f-11e6-9c38-f093fa467c9e.png)

**Comment by kdoh** [comment]
@mazameli What does "Refresh" do in the create / edit views of those wireframes?

**Comment by mazameli** [comment]
The idea was that the button would change from `load` to `refresh` after the initial load of the map so that in the event that the user changes the map URL, or if the file itself gets overridden, there'd be a way to refresh the geoJSON file so that the dropdowns would be populated with the correct properties.

**Comment by tlrobinson** [comment]
@mazameli I'm thinking we might as well use the same system for the built in GeoJSONs. Do we want the user to be able to remove `US State` and `Country`?

**Comment by mazameli** [comment]
I mean, I suppose that makes some amount of sense for users who aren't using those maps and who want to clean up their map options, but it kind of feels like an unnecessary complication to have to figure out things like how/if we'd let them restore the maps Metabase includes out of the box. I wouldn't worry about that case right now.
