### ISSUE TITLE
Hide Data option in side nav

### ISSUE THREAD

**Issue by yasergsi** [metabase/metabase#27456]
**Is your feature request related to a problem? Please describe.**
I want some users to access few tables (3 to be specific) only when they are JOINED with another table ABC to implement row level restriction since the column used for row level restriction is present only in the table ABC.

**Describe the solution you'd like**
I need to hide the entire Data element from side navigation bar so that I give the access to the JOINED tables from a collection.

**Describe alternatives you've considered**
I've tried removing table access from Data permissions and giving table access in the collection permissions but it doesn't work.

**How important is this feature to you?**
It's very important and a matter of security since users shouldn't view data which is not meant for them

**Additional context**
None required I hope !!!

**Comment by flamber** [comment]
Hi @yasergsi 
Please use the support email, when using the Pro/Enterprise plans.

This is already possible by doing Advanced Sandboxing, example https://www.metabase.com/learn/permissions/data-sandboxing-column-permissions#create-a-sql-query

Hiding things should not be used for security, since it would still be accessible.

Also, there's a big difference between Data permissions and Collection permissions.
