### ISSUE TITLE
Inconsistent hover effects on charts

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#2751]
(This is on our stats instance)

With pie charts, the slice that's being hovered on stays opaque while the other slices fade back:

![screen shot 2016-06-13 at 4 36 22 pm](https://cloud.githubusercontent.com/assets/2223916/16026701/291f8480-3185-11e6-8e48-1fad39d152ea.png)

Same thing with multiline charts:

![screen shot 2016-06-13 at 4 38 27 pm](https://cloud.githubusercontent.com/assets/2223916/16026727/549bb8ae-3185-11e6-8e5c-f93110e3779e.png)

But bar charts do the opposite:

![screen shot 2016-06-13 at 4 36 13 pm](https://cloud.githubusercontent.com/assets/2223916/16026705/2ce3bed8-3185-11e6-8d3d-f37a597974ea.png)

Except in cases where there are multiple bars, where the bar being hovered on fades back, but other bars that belong to the same metric stay opaque:

![screen shot 2016-06-13 at 4 38 46 pm](https://cloud.githubusercontent.com/assets/2223916/16026730/58a0ac2a-3185-11e6-99f1-4fa0611d8695.png)

I feel like the best would be for all the charts to follow the pie chart pattern: the thing being hovered on stays opaque, the other things fade back.

cc @kdoh

**Comment by kdoh** [comment]
@mazameli Good catch. Your description is the intended behavior.

**Comment by tlrobinson** [comment]
Does "the thing" mean the individual element or the whole series? Perhaps the individual element if it's a single series, or the whole series if it's a multiseries?

**Comment by lewisl9029** [comment]
Gave this a try just now, but it seems like Pie Chart is implemented very differently compared to some of the other visualizations, and I couldn't quite figure out how to apply the right styles to the right hover elements for the other chart types. So I decided to move on to something else rather than continuing to bang my head on this issue, since Tom will probably have a much easier time than me when tackling this.
