### ISSUE TITLE
Do not prompt non-admin users to configure email or Slack

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#27784]
**Describe the bug**
If email and/or Slack are not already configured in admin > settings, a non-admin user is prompted to do so when opening a dashboard subscription sidebar. If they click on a prompt, they will end up in `/unauthorized` page ("Sorry, you don’t have permission to see that.")

---
**Expected behavior**
Non-admins should see a different copy. Something like "Contact your Metabase admin to set up email/Slack first".

_Product Side_

> From the Product side, we would like the following expected behavior:
- [x] If neither email nor slack has been set up, if the user is a non-admin, don’t show them the dashboard subscription button at all.
- [x] If either email or slack has been configured but not the other, and there are no existing subscriptions, take them straight to the new subscription form for the channel that is configured.
- [x] If there are existing subscriptions they can see, show them that list first, and if they click new subscription, if only one channel has been configured, take them straight to the new subscription form for that channel.

---
**To Reproduce**
1. Have at least email or Slack not configured (or both)
2. Have at least one dashboard
3. As a non-admin user with sufficient permissions to see that dashboard, click on "Subscriptions" icon
4. In the subscriptions sidebar click on "Configure Slack" (for example)
5. You are now redirected to `/unauthorized` page

---
**Information about your Metabase Installation:**
local dev, `master`, d3837c217d8f1a7405c75541429869ed7925cc66, H2, Sample Database

**Severity**
Just a slight UX annoyance. P3.

**Comment by cdeweyx** [comment]
From the Product side, we would like the following expected behavior:
- If neither email nor slack has been set up, if the user is a non-admin, don’t show them the dashboard subscription button at all.
- If either email or slack has been configured but not the other, and there are no existing subscriptions, take them straight to the new subscription form for the channel that is configured.
- If there are existing subscriptions they can see, show them that list first, and if they click new subscription, if only one channel has been configured, take them straight to the new subscription form for that channel.

**Comment by EmmadUsmani** [comment]
The expected behavior came from this discussion on Slack (internal): https://metaboat.slack.com/archives/C02H619CJ8K/p1677254146782909

**Comment by EmmadUsmani** [comment]
Moving on from this for now due to complexity/effort.
