### ISSUE TITLE
Dashboard crashes after upgrade to v1.45.2

### ISSUE THREAD

**Issue by LukeAbell** [metabase/metabase#27883]
**Describe the bug**
After upgrading from v1.44.5 to v1.45.2, one of our dashboards crashes while loading.

**Logs**
<img width="1514" alt="screenshot_1842" src="https://user-images.githubusercontent.com/3343530/214734740-38d07ef6-a75e-4b37-98e2-fee33d661098.png">

**Information about your Metabase Installation:**
- Your browser and the version: Chrome Version 109.0.5414.87
- Your operating system: OSX 13.1
- Your databases: MySQL
- Metabase version: 1.45.2
- Metabase hosting environment: Kubernetes
- Metabase internal database: MySQL

**Severity**
Severe. Dashboard broken.

**Comment by Tony-metabase** [comment]
Hi @LukeAbell ,

Are you currently a Metabase Customer? Since I see you are using 1.xx.x, the 1 at the beginning denotes an enterprise build

Is there anything in the logs that is useful? Please share Admin -> Troubleshooting -> Logs when you try to access the dashboard 

Also please share your Diagnostic Info

**Comment by Tony-metabase** [comment]
If you are a customer please send this over to help@metabase.com ... So we can help you come to a resolution faster :)

**Comment by paoliniluis** [comment]
This ended up being a FE caching problem
