### ISSUE TITLE
Dashboard subscriptions are not working on dashboards with actions or links

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#28424]
**Describe the bug**
Dashboard subscriptions are not working on dashboards with actions or links

**To Reproduce**
1. Set up email integration on your instance
2. Connect any PG db
3. Create one action
4. Create a dashboard, and add the action on the dashboard
5. Try sending a test email subscription — it does not work

The same happens when adding a link instead of an action.

**Expected behavior**
Sending subscription fails

**Logs**
```
[backend] 2023-02-17 18:30:21,056 DEBUG middleware.log :: POST /api/pulse/test 400 9.8 ms (0 DB calls) 
[backend] {:errors
[backend]  {:cards
[backend]   "value must be an array. Each value must satisfy one of the following requirements: 1) value must be a map with the following keys `(collection_id, description, display, id, include_csv, include_xls, name, dashboard_id, parameter_mappings)` 2) value must be a map with the keys `id`, `include_csv`, `include_xls`, and `dashboard_card_id`. The array cannot be empty."}}
```

**Information about your Metabase Installation:**

`master` branch, commit `c91fc1dfac13407a657f2c472fe75a1c687d4678`

**Comment by qnkhuat** [comment]
We do not plan to include actions in subscriptions ([slack](https://metaboat.slack.com/archives/C01LQQ2UW03/p1676887944441469?thread_ts=1676887796.766269&cid=C01LQQ2UW03)).

The purpose of `cards` parameter is to let BE knows which cards will be included in the subscriptions and also do a permission check. Since actions are not included in subscriptions, BE shouldn't include actions in `cards`.

So I think should be fix from FE @alxnddr

**Comment by qnkhuat** [comment]
Fixed by https://github.com/metabase/metabase/pull/28527
