### ISSUE TITLE
Pie Graph Visual enhancements/improvements

### ISSUE THREAD

**Issue by rNianios** [metabase/metabase#2861]
Hi Metabase Team,

Although it's easy to create charts and pull data from databases and play with data but we have no options when it comes to chart options like colors, labels etc.

I have some recommendations from Pie charts:

Please take a look at the Pie chart below. There are two Percentage fields, one create from my Query and one created automatically from Metabase. Although I can see that it's handful to have it being created automatically sometimes it's not so convenient and I will explain my self.

So let's say I have 8 fields on a table and I want to report only on the top 3 and return the relevant percentage of them from the table and not from the Pie chart it self. So lets say I have the following:

AAA - 25%
BBB - 20%
CCC - 15%
DDD - 10%
EEE - 10%
FFF - 10%
GGG - 5%
HHH - 5%

If I report on the top 3 the automatically created percentage will show something less than the real percentages but I want to return the real percentage which is 25% , 20% and 15%.

![pie_issue](https://cloud.githubusercontent.com/assets/1166321/16517952/262da9cc-3f78-11e6-9001-5033412517cf.png)

The second one is on the hover if the returned text is lengthy it will be overlapped by the pie chart itself. Maybe you should bring the label in front?

![pie_issue_2](https://cloud.githubusercontent.com/assets/1166321/16518085/e595f21a-3f78-11e6-938f-b69a9c37b3b3.png)

**Comment by tlrobinson** [comment]
@mazameli @kdoh Any ideas how to handle overflowing labels in the center (last screenshot)?

**Comment by tlrobinson** [comment]
Regarding the duplicate "percentage" tooltip, I see 2 options:

1. Add YAT (yet another knob) to hide it
2. Use some heuristic (column name is `/^percent.*$/i`?) to determine when to hide it.

@salsakran @kdoh @mazameli?

**Comment by camsaul** [comment]
3. Don't do anything and tell people to squint and pretend it doesn't exist

**Comment by camsaul** [comment]
sorry that's supposed to be 3

**Comment by camsaul** [comment]
#MarkdownProblems

**Comment by mazameli** [comment]
I say #2 if it's easy-ish. I think we need to draw a knob-shaped line in the sand regarding adding more options.

**Comment by camsaul** [comment]
yeah but what if they name it something like `sales percent` or `prcnt` or ? And for that matter are we going to handle permilles 😳 

</RabbitHole>

**Comment by salsakran** [comment]
Regarding the matter of pie charts based on things that already have percentages, I'm suggesting we punt. I think there are too many edge cases here. I think eventually we might at YAK but not at the moment. 

@rNianios we suggest just dropping the % calculation from the underlying query for this. Metabase is predicated on a world where saved questions are cheap, easy and relatively lightweight. We've actively taken this stance and a lot of our design choices are centered on this fact. This is a great example of a place where a bit of work upstream (in the query) keeps the end user interface slim and easy to work with.

Regarding the overlapping, that's fairly annoying. I see two options:
1. Move it to below the Bru-nut
2. Adjust the font size to fit.

I'm not a huge fan other either option. @kdoh any thoughts on getting out of this? There's also a connection to card sizes as at smaller card sized this shows up for shorter strings. 

In either case, I'm removing this from 0.20.

**Comment by kdoh** [comment]
As far as the overlapping goes I'm thinking:

- We don't do anyone any favors by trying to force the content to fit and resizing it to do so.
- We could truncate, like we do for long strings elsewhere but that seems like it doesn't really give anyone any benefit here either.

I've at least personally always viewed the content in the center of the donut (usually the count and the slice label) as a nice plus rather than a core interaction or contextual element since the information is almost entirely duplicated in the case of the tooltip content and the legend content at larger sizes.

So to solve this I'm of the opinion that if it doesn't fit, we should hide it, since there should be enough context elsewhere to still understand the data. That route also gels well with our general visualization display philosophy of "show as much as required, but not more than necessary" to make the data make sense at a chosen card size. I'd argue that when it can't easily fit the info in the center isn't actually required and is an enhancement.

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0
