### ISSUE TITLE
Boolean fields have string icons in SQL editor data browser

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#28622]
**Describe the bug**
In the SQL Editor data browser, boolean fields show the string icon ("Aa") instead of the boolean one ("I/O"). This is similar to #27681 which I fixed earlier this week.

**Logs**
No relevant logs on FE or BE.

**To Reproduce**
1. +New
2. SQL Query
3. "Learn about your data" (book icon)
4. Accounts
5. `TRIAL_CONVERTED`, `ACTIVE_SUBSCRIPTION`, and `LEGACY_PLAN` appear to have string icons when they are booleans.

**Expected behavior**
Those boolean fields should have the boolean icon.

**Screenshots/videos**

![Screenshot 2023-02-24 at 12 10 49 PM](https://user-images.githubusercontent.com/37751258/221313894-c5f4694c-d51d-43e7-bade-a2ddff9f584d.png)

**Information about your Metabase Installation:**

Local dev environment, master, commit `0c56664819`

**Severity**
Not severe, minor visual bug.

**Comment by abdulazizali77** [comment]
Hi @EmmadUsmani 
my first look at the metabase codebase and still many things unknown, these are the findings from my analysis in the past week

- `BulkFilterModal` (the filter) through `InlineCategoryPicker` gets the icon from `field.dimension().icon()` by fetching `Field` entities
- `TablePane` (the notebook)  through `FieldList` gets the icon from `field.semantic_type` by fetching `Field` metadata
- From backend perspective it seems all `base_type` `type/Boolean`s get mapped to `type/Category` semantic type
- IMHO, there are some issues in `BulkFilterModal` like hardcoded boolean icon string instead of calling `dimension.icon` and also very complex switch case decisions 
- There are still various components (at least 2) using `getSemanticType` i did not attempt to fix them
- I dont actually know what `Dimension` means in terms of data model/architecture :)

**Comment by shaunlebron** [comment]
Thank you @abdulazizali77 for your notes and patch, very helpful!

Starting from your notes, I found two ways to resolve a field icon:
1. `getSemanticTypeIcon` uses a flat list of semantic types, and is missing the `io`  icon
2. `getIconForField` uses a flat list of core types, and does hierarchical matching. the `io` icon is present
    * and actually, it won’t ever return the `birthday` 🎂 icon that `getSemanticTypeIcon` will 🤔

The fields in the original screenshot above are generated from this array below.  The “null” semantic types explain the warning icons, and the “type/Category” semantic types are resolved to strings.  `getIconForField` does better by accounting for all the base/effective/semantic types:
<img width="896" alt="AKEKxhzDVJer5gyFJmMLFC-2" src="https://github.com/metabase/metabase/assets/116838/682d5cd1-af68-4da0-a69f-9ff9385aa301">

Also, it looks like we have to use `getColumnIcon` instead of `getIconForField` which deprecated in favor of it.  It seems to have the same behavior.

Some actions for me:
* I will ask the design team how icons should really be chosen based on a field’s base/effective/semantic types (since that cute birthday icon is missing).
* I will ask someone (who has worked on metabase-lib types) how to get a column type compatible with `getColumnIcon` from a normal field object.

**Comment by abdulazizali77** [comment]
@shaunlebron i already put up a PR #31016 and i actually do think the correct way is to use `dimension.icon()` im sorry to say there seems to be alot of disconnect between the front end implementors/implementation, many things are harcoded and repeated and unused
