### ISSUE TITLE
Cumulative aggregations with multiple breakouts should reset count/sum when values of one specific breakout columns change

### ISSUE THREAD

**Issue by underyx** [metabase/metabase#2862]
Steps to reproduce:
- create a new question with a Postgres data source
- set view setting to 'Cumulative count of rows' (or 'Cumulative sum of ___')
- add two columns to group by

You'll see a chart like this one:
![](https://i.imgur.com/GajxvoK.png)

You can see that the green line's tally starts off where the blue one's ends.

I would expect each line to start from zero on the Y axis to be able to see how the different datasets compared to each other at different points in time.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
Which DB are you using here @underyx ?

Ca you get a reproduction case using the sample db by any chance?

**Comment by underyx** [comment]
Nope, I seem to be unable to reproduce with the sample dataset. I'm using PostgreSQL here.

**Comment by Gurado** [comment]
+1 same issue also applies if the databases is mysql. [Combining two existing saved questions](http://www.metabase.com/docs/v0.18.1/users-guide/08-multi-series-charting.html) can serve as workaround but I am not sure it extends to more than two exsiting questions.

**Comment by camsaul** [comment]
I'm not able to reproduce these charts but I've noticed something else weird: with the Sample dataset when I run a cumulative count of rows query with two rows only two columns are displayed even though the backend returns 3. 

![screen shot 2016-07-13 at 6 52 48 pm](https://cloud.githubusercontent.com/assets/1455846/16825608/090ec22e-492b-11e6-805c-2b22bdb7b3c3.png)

![screen shot 2016-07-13 at 6 52 37 pm](https://cloud.githubusercontent.com/assets/1455846/16825606/0590228c-492b-11e6-9ab7-c129370ce4f8.png)

Maybe it's being pivoted in a weird way or something?

**Comment by salsakran** [comment]
@Gurado + @underyx is there any way you can generate a fake dataset that triggers this in postgres or mysql?

**Comment by Gurado** [comment]
Somewhat artificial but there you go:

`CREATE TABLE IF NOT EXISTS `dw_hip`.`test_pivot` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `metric` int,
  `dayname` VARCHAR(3),
  `daynumber` INT(10), 
  `week` INT(10), 
  PRIMARY KEY (`id`),
  INDEX `date` (`date` ASC),
  INDEX `dayname` (`dayname` ASC),
  INDEX `daynumber` (`dayname` ASC),
  INDEX `week` (`week` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-11 00:00:00', 10, "Mon",1,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-12 00:00:00', 11, "Tue",2,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-13 00:00:00', 12, "Wed",3,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-14 00:00:00', 13, "Thu",4,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-15 00:00:00', 14, "Fri",5,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-16 00:00:00', 15, "Sat",6,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-17 00:00:00', 16, "Sun",7,2);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-18 00:00:00', 17, "Mon",1,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-19 00:00:00', 18, "Tue",2,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-20 00:00:00', 19, "Wed",3,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-21 00:00:00', 20, "Thu",4,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-22 00:00:00', 21, "Fri",5,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-23 00:00:00', 22, "Sat",6,3);
INSERT INTO test_pivot (`date`,`metric`,`dayname`,`daynumber`,`week`) values ('2016-07-24 00:00:00', 23, "Sun",7,3);`

![cursor_and_metabase](https://cloud.githubusercontent.com/assets/3722155/17093192/1acaa79e-528b-11e6-8302-145b513613dc.jpg)

**Comment by camsaul** [comment]
Able to reproduce this with the sample dataset.

Selecting multiple group by columns in the query builder will do a combined `GROUP BY`. For example, using the sample dataset, we can get the number of products added by category and year:

#### Count of Rows w/ 2 breakouts

```sql
SELECT \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", year(\"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\") AS \"CREATED_AT\", count(*) AS \"count\" 
FROM \"PUBLIC\".\"PRODUCTS\" 
GROUP BY \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\", year(\"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\") 
ORDER BY \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" ASC, year(\"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\") ASC
```

<table>
  <tr>
    <td>CATEGORY</td>
    <td>CREATED_AT</td>
    <td>count</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2015</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2016</td>
    <td>27</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2017</td>
    <td>1</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2015</td>
    <td>27</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2016</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2017</td>
    <td>7</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2015</td>
    <td>20</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2016</td>
    <td>23</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2017</td>
    <td>4</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2015</td>
    <td>19</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2016</td>
    <td>19</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2017</td>
    <td>3</td>
  </tr>
</table>

![screen shot 2016-07-26 at 1 35 11 pm](https://cloud.githubusercontent.com/assets/1455846/17154483/0ddbd426-5336-11e6-92d3-38a6f4a16ea1.png)

![screen shot 2016-07-26 at 1 44 19 pm](https://cloud.githubusercontent.com/assets/1455846/17154779/4dbbc9ba-5337-11e6-8481-42c26627f202.png)


That all makes sense. Now if we switch to *cumulative count*, we get data like this:

#### *Cumulative* Count of Rows w/ 2 breakouts

(SQL is the same, counts accumulated in post-processing).

<table>
  <tr>
    <td>CATEGORY</td>
    <td>CREATED_AT</td>
    <td>count</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2015</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2016</td>
    <td>52</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2017</td>
    <td>53</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2015</td>
    <td>80</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2016</td>
    <td>105</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2017</td>
    <td>112</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2015</td>
    <td>132</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2016</td>
    <td>155</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2017</td>
    <td>159</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2015</td>
    <td>178</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2016</td>
    <td>197</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2017</td>
    <td>200</td>
  </tr>
</table>

![screen shot 2016-07-26 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/1455846/17154804/633d1fd2-5337-11e6-8b77-2c165a088cf1.png)

![screen shot 2016-07-26 at 1 44 47 pm](https://cloud.githubusercontent.com/assets/1455846/17154796/5c84a0de-5337-11e6-928a-a929d98720c2.png)

**Comment by camsaul** [comment]
How to "fix" this is a tough question; depending on how you look at it, the current behavior makes sense. The [MBQL aggregation used in this query](https://github.com/metabase/metabase/wiki/Query-Language-'98#cumulative-count-aggregation) merely says to do a cumulative count of `count`; currently that does a simple accumulation without regards to values in other columns. In the example above, grouping is done by *category + year* ; they are effectively treated like a single column, and the accumulation is done with values of the other column, `count`.

If we wanted to tweak that behavior to do multiple cumulative counts for each unique value of another column, it wouldn't be clear which column that should be. In the example above, it seems like we'd want the data to look like this, re-starting the accumulation for each new value of `CATEGORY` :

<table>
  <tr>
    <td>CATEGORY</td>
    <td>CREATED_AT</td>
    <td>count</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2015</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2016</td>
    <td>52</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2017</td>
    <td>53</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2015</td>
    <td>27</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2016</td>
    <td>52</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2017</td>
    <td>59</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2015</td>
    <td>20</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2016</td>
    <td>43</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2017</td>
    <td>47</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2015</td>
    <td>19</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2016</td>
    <td>38</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2017</td>
    <td>41</td>
  </tr>
</table>

Although it could just as easily be done by `YEAR` instead:

<table>
  <tr>
    <td>Doohickey</td>
    <td>2015</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2015</td>
    <td>52</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2015</td>
    <td>72</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2015</td>
    <td>91</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2016</td>
    <td>27</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2016</td>
    <td>52</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2016</td>
    <td>75</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2016</td>
    <td>94</td>
  </tr>
  <tr>
    <td>Doohickey</td>
    <td>2017</td>
    <td>1</td>
  </tr>
  <tr>
    <td>Gadget</td>
    <td>2017</td>
    <td>8</td>
  </tr>
  <tr>
    <td>Gizmo</td>
    <td>2017</td>
    <td>12</td>
  </tr>
  <tr>
    <td>Widget</td>
    <td>2017</td>
    <td>15</td>
  </tr>
</table>

So it's not clear what the expected behavior should be in this case. I believe the current behavior does make sense, although the other two alternate behaviors are useful as well; it's not particularly clear to users which of the three possible behaviors we'd use. 

This may be a case where a multiseries chart is appropriate. @underyx and @Gurado, check out our [documentation about multi-series charting](http://www.metabase.com/docs/latest/users-guide/08-multi-series-charting.html). That will let you create charts with multiple cumulative series starting from zero on the y-axis today.

Meanwhile, @metabase/core-developers, we should discuss how we expect cumulative aggregations to behave in this case. It might make sense to give the cumulative-count clause an optional field to "group" the cumulative count by when there are multiple breakout fields. 

I think this isn't a bug so much as it is a case of current behavior being somewhat confusing, so I'll reclassify accordingly.

**Comment by mazameli** [comment]
Just a note that we received customer feedback that the current behavior is confusing, and that e.g. in the case of breakout out by `Created At` and then `Category`, the expected behavior would be to see multiple lines, all of which start at 0, and each of which individually add up the count or sum only for that one category across time.

**Comment by sbelak** [comment]
A good heuristic that would probably cover most cases is that you use the ordinal-like field in the group by for the x axis and do a breakout on all others. Not perfect, but at least the basic cases such as cumsum x date x category should just work.

**Comment by OliverEvans96** [comment]
I fully agree with the customer feedback @mazameli received. I found this to be confusing and not well documented. Otherwise, metabase is great!

**Comment by vitorbaptista** [comment]
Any estimate on this?

**Comment by itai-codefresh** [comment]
joining here as well, any estimate here?
and what could be a workaround to be able to do this via sql query?

**Comment by chasleslr** [comment]
update?

**Comment by rajat20gl** [comment]
This is Not fixed yet
:(

**Comment by mvtemple** [comment]
Hi all - is there an update on the timeline for this? I see that the issue has been open since 2016.

**Comment by lindsay-stevens** [comment]
I think this is a bug. The current behaviour produces results that are incorrect/misleading in that they do not match the question implied by the question builder choices, when multiple breakouts are selected. The results are as expected in terms of the generated SQL. So the bug is that the generated SQL doesn't match up with what the QB implies that the query will be.

Below are some examples. The generated SQL should partition by the first `n` - 1 selected groupings and order by the `n`th grouping. The implied / default window frame in each case is `RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW` ([Postgres docs](https://www.postgresql.org/docs/current/sql-select.html#SQL-WINDOW)). A full query for 2 breakouts would be like:

```
SELECT g.a, g.b, sum(coalesce(c.count, 0)) OVER (/*the window clause*/)
FROM (SELECT /*the unique groupings*/) AS g
LEFT JOIN (SELECT /*the grouped counts*/) AS c ON g.a = c.a AND g.b = c.b
```

Example data (which skips the step for getting unique groupings):
```
WITH d (a, b) AS (
SELECT i.a, chr(j.b)
FROM generate_series(1, 2) AS i(a),
     generate_series(97, 99) AS j(b)
)
SELECT * FROM d
```
![image](https://user-images.githubusercontent.com/6345269/129149658-74a1fca2-60eb-43a5-9597-f0227d764447.png)

*Current Behaviour*
If I choose groupings "a" then "b", I get results like:
![image](https://user-images.githubusercontent.com/6345269/129149034-660a8aa7-5482-48a1-ae3b-6d31e966144f.png)
Equivalent to SQL like:
```
SELECT a, b, count(*) OVER (ORDER BY a, b) AS "Cumulative Count" FROM d
```

If I choose groupings "b" then "a", I get results like:
![image](https://user-images.githubusercontent.com/6345269/129150183-31b081c3-2f4c-4e07-99f8-878774848cc0.png)
Equivalent to SQL like:
```
SELECT a, b, count(*) OVER (ORDER BY b, a) AS "Cumulative Count" FROM d
```

*Expected Behaviour*
If I choose groupings "a" then "b", I get results like:
![image](https://user-images.githubusercontent.com/6345269/129148920-1f37d328-428e-4e70-ab46-54fdc9920e4c.png)
Equivalent to SQL like:
```
SELECT a, b, count(*) OVER (PARTITION BY a ORDER BY b) AS "Cumulative Count" FROM d
```

If I choose groupings "b" then "a", I get results like::
![image](https://user-images.githubusercontent.com/6345269/129149620-6380cf8e-0a55-4bb7-ad4a-be5e6b6a84bd.png)
Equivalent to SQL like:
```
SELECT a, b, count(*) OVER (PARTITION BY b ORDER BY a) AS "Cumulative Count" FROM d
```

Which then extends to 3+ groupings ("a", "b", "c") as follows:
![image](https://user-images.githubusercontent.com/6345269/129170016-a1ba7242-1f9d-4730-bb7f-8f44e9e3778f.png)
From SQL like:
```
WITH d (a, b, c) AS (
SELECT i.a, chr(j.b), k.c
FROM generate_series(1, 2) AS i(a),
     generate_series(97, 98) AS j(b),
     generate_series(5, 6) AS k(c)
)
SELECT a, b, c, count(*) OVER (PARTITION BY a, b ORDER BY c) AS "Cumulative Count" FROM d
```

**Comment by evajaum** [comment]
Hello, are there any updates on this topic? It confuses me a lot when using break outs in cumulative charts.

**Comment by brunnopleffken** [comment]
I'm having these same problems.

This is my table: the count of new clinics by state, by month.
<img width="431" alt="Screen Shot 2022-05-26 at 13 27 02" src="https://user-images.githubusercontent.com/3427344/170531966-8225c907-5a80-4b8e-97aa-c61e92ad8afe.png">

I'm unable to get the cumulative sum of clinics grouped by created_at and by state. This is the result:
<img width="1896" alt="Screen Shot 2022-05-26 at 13 27 50" src="https://user-images.githubusercontent.com/3427344/170532064-8d894b3d-3f70-4595-aa2e-2aeee52bbf8b.png">

This is so wrong! The state of PR, for example, is just ONE USER for months in a row. I want to get the cumulative count BY STATE over time. Metabase is just adding the "count" column regardless of it.

A solution would be in the chart itself. The line chart could do the count.

**Comment by camerondavison** [comment]
I ran into this same problem trying to do a cumulative count broken down by month and state. Seems like that could be a common use case. Is there a work around?

**Comment by igorlaguiar** [comment]
This should really get fixed.

**Comment by tiaradwiputri** [comment]
Do we have any update on this issue? I stumbled upon the same bug. I can do a work around using SQL but would like to let non-technical people play around with the different filter and configuration through the editor.

**Comment by bcipolli** [comment]
Agree that this is a bug. No other tool operates in this way that I'm aware of (aware of 2 others that do the "right" thing).

The fix seems simple - there should be partitioning done here.

**Comment by camsaul** [comment]
I'm relabeling this as a bug but I think we'll probably want to fix it via #9393, i.e. switching from doing cumulative sum/count in post-processing to doing them via window functions directly in the SQL. This was previously not an option because H2 v1 did not support window functions, but we switched to H2 v2 earlier this year.

**Comment by kamilmielnik** [comment]
Reproducible in `master` at 78cb28816a.

**Comment by SBUP24** [comment]
Hi - Is there a fix for this accessible for the metabase end user using the build question interface on metabase?
I really want to graph cumulative sum by category over time and am tearing my hair out wondering why they don't all start at zero.
Thanks

**Comment by routes-unobserved87** [comment]
@Gurado https://stackdev.space/questions/generating-a-running-total-column-in-mysql
