### ISSUE TITLE
Add remarks to Snowflake queries

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28865]
**Is your feature request related to a problem? Please describe.**
I can't see any remark on the queries
![image](https://user-images.githubusercontent.com/1711649/222546553-30d1c199-6662-4686-8dae-f7e947440e0a.png)

these are important as we can see context of queries and also we might be able to tie these with what's on query_execution

**Describe the solution you'd like**
Add remarks in the query

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by laura-radaelli** [comment]
Thanks for opening this @paoliniluis :) The most important information for us is the Query ID.

**Comment by fernandobrito** [comment]
Hi! I'm very committed to improving our Snowflake cost visibility where I work and right now Metabase is sort of a black box for us. Besides knowing that a query comes from Metabase, we don't know much in terms of which users are triggering with questions, which dashboards are costly, what's the cost based on different workloads (pulses vs dashboards vs ad-hoc analysis), etc.

I recently started going deeper into how to address some of the questions above, and here are my learnings so far. This is a very long message. A TL;DR version will be added as a new comment below it.

## Vocabulary

As already mentioned in this issue, Metabase can add metadata to the queries it sends to the databases by injecting a comment into the query with additional information. This is called a `remark` and it was first introduced back in 2016, through https://github.com/metabase/metabase/issues/2386.

## Default implementation

The `remark` feature is implemented in such a way that Metabase provides a "default remark" that is available to all drivers, and each driver can either pick this default format or come up with their own custom format. The default format can be found at https://github.com/metabase/metabase/blob/v0.46.0/src/metabase/query_processor/util.clj#L39 and looks like:

```
Metabase:: userID: <userID> queryType: <"MBQL"|"native"> queryHash: <queryHash>
```

## Drivers customization

The following drivers add remarks to their queries:

### BigQuery

Uses the default format, prepending it as a string (plus a line break) before the query. Referenced at:

https://github.com/metabase/metabase/blob/0ca7df376a56669965cad963b919ae63f5bef973/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj#L361-L369

This is a live example of what it looks like (taken from BigQuery's query history):

![image](https://user-images.githubusercontent.com/196840/229093817-86f8fd9f-82fd-486c-8420-fab3fed187ac.png)

Note that this driver actually allows Metabase administrators to disable remarks since it can have implications for caching.

<img src="https://user-images.githubusercontent.com/196840/229092070-1f848033-485d-4f27-af2b-29b6b70b1857.png" width="500">

### Spark

Uses the default remark. Referenced at:

https://github.com/metabase/metabase/blob/0ca7df376a56669965cad963b919ae63f5bef973/modules/drivers/sparksql/src/metabase/driver/sparksql.clj#L153-L164

### Redshift

This driver actually adds more metadata fields (dashboard id, an identifier for the Metabase deployment and filters used in the query). It also formats the remark as JSON, making it easier to be parsed later. Implemented at:

https://github.com/metabase/metabase/blob/0ca7df376a56669965cad963b919ae63f5bef973/modules/drivers/redshift/src/metabase/driver/redshift.clj#L318-L327

Note that the function above is adding the new JSON object but still calling the original `qp.util/default-query->remark`, so both comments will be added. This can be confirmed in the tests: https://github.com/metabase/metabase/blob/v0.46.0/modules/drivers/redshift/test/metabase/driver/redshift_test.clj#L80. Interesting that it ends up adding a comment inside a comment, which is valid syntax but a bit redundant.

```
-- /* <custom JSON remark> */ Metabase:: <default remark>
<query>
```

### All SQL JDBC drivers

All JDBC-based drivers also get a remark added automatically, using the default formatting. Referenced at:

https://github.com/metabase/metabase/blob/0ca7df376a56669965cad963b919ae63f5bef973/src/metabase/driver/sql_jdbc/execute.clj#L489-L497.

I could confirm it by triggering queries against a local MySQL instance and then checking the logs:

![image](https://user-images.githubusercontent.com/196840/229111689-4ed5b98f-cd88-4dfe-b835-ff3502278606.png)

The following drivers are JDBC-based: h2, sqlite, vertica, sparksql, sqlserver, athena, oracle, presto-jdbc, mysql, postgres, **snowflake** ([source](https://github.com/metabase/metabase/search?q=%22%3Aparent+%3Asql-jdbc%22)).

## Snowflake? Wait, what?

Wait, if Snowflake's driver is JDBC-based and Metabase by default adds marks to all JDBC-based drivers, how come this message is written on an issue named "Add remarks to Snowflake queries"? Here is the climax of this whole message:

**Metabase already adds remarks to Snowflake queries, but Snowflake is removing them!**

It turns out that Snowflake strips comments added to the beginning of queries. You can easily reproduce it from Snowsight (Snowflake's "new" UI). If you send this query to Snowflake:

<img src="https://user-images.githubusercontent.com/196840/229115875-aff6f9e5-ebaf-49ab-b3fa-2ca5d5cb1d29.png" width="500">

It will execute this (screenshot from the query history):

<img src="https://user-images.githubusercontent.com/196840/229114474-d833f74e-3257-423f-ae0c-1f94036e60fb.png" width="500">

You can also run it from SnowSQL (Snowflake's CLI) to confirm that it's not just Snowsight that is removing the comment, but the engine itself.

Running `snowsql -q "/* comment */\nselect 1"` will show just `select 1` in the query history.

## More experiments

No matter if I use `--` or `/* ... */`, if the comment is prepended as a new line before my query, Snowflake always removed it based on my experiments.

I noticed that if I remove the line break, in some cases it does preserve the comment. Here are some of the tests that I have done. ❌ means that the comment was removed, and ✅ that the comment was preserved.
* Prepended `--`, with new line: `-- comment \n select 1;`: ❌
* Prepended `/* */`, with new line: `/* comment */ \n select 2;`: ❌
* Prepended `/* */`, without new line: `/* comment */ select 3;`: ❌
* Appended `--`, with new line: `select 4; \n -- comment`: ❌
* Appended `/* */`, with new line: `select 5; \n /* comment */`: ❌
* Appended `--`, without new line: `select 6; -- comment`: ✅
* Appended `/* */`, without new line: `select 7; /* comment */`: ❌

The only way I managed to get it working was by appending a `--` comment without a new line. Note that Snowsight actually removed the comment in this case, but triggering it from Snowsql made the comment stay.

## Bonus: what about caching?

The fact that the BigQuery driver has remarks as an optional feature reminded me that this could also have implications on Snowflake caching.

Control group:
* Running `select * from snowflake_sample_data.tpch_sf1.customer limit 1;` triggered a table scan.
* Running it once again benefitted from Snowflake's [persisted query results](https://docs.snowflake.com/en/user-guide/querying-persisted-results).

Then:
* Running `select * from snowflake_sample_data.tpch_sf1.customer limit 1; -- comment` actually triggered a table scan again, which is sad.
* However, running it again made Snowflake use the query result cache, which is good!
* Changing the comment to something completely different like `select * from snowflake_sample_data.tpch_sf1.customer limit 1; -- foo` still made the query result cache work.

My early conclusion: somehow queries without comments will not share the query results cache with queries with comments. However, queries with comments will have it shared among each other, even if the comments are different, which they will be in case of metadata being added by Metabase with IDs. Adding markers to Snowflake should only have a very minor performance impact (query results cache will not be shared between Metabase users and non-Metabase users).

## Conclusion

I will add a TL;DR below.

**Comment by fernandobrito** [comment]
Summary:
* Metabase already adds remarks to Snowflake queries, but Snowflake is removing them.
* We could override the remark on Snowflake's driver to have it appended instead of prepended.
* There's inconsistency between what kind of metadata each driver is adding to the remarks, and the format.

I have some working proof-of-concept code which I plan to open as a Draft PR next week so we can discuss how we could fix the remarks for the Snowflake driver. My vote is to have it formatted as JSON and add as much metadata as we have available.

![image](https://user-images.githubusercontent.com/196840/229124415-57d172aa-fce8-4fe0-93bd-248712f1e4fe.png)

**Comment by ian-whitestone** [comment]
Bumping this! @fernandobrito thanks for such a great write up and exploration ❤️

**Comment by Aostojic** [comment]
Bumping this again!

**Comment by nikolearnerbly** [comment]
This would be wonderful for us as well.
