### ISSUE TITLE
Dashboard update makes too many app DB calls

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#28956]
This is actually causing crazy amounts of load and problems for our hosted instances. How could Dashboard update possibly need to make so many DB calls? Do we have an N + 1 situation? We should investigate and fix this.

![image](https://user-images.githubusercontent.com/1455846/223181144-a50d161a-cc2d-4df1-9bbf-d6c0e5695d15.png)

**Comment by calherries** [comment]
It's probably not a blocker anymore, since DB calls and response time from `PUT /api/dashboard/:id/cards` have already roughly halved from the previous PRs we've merged. But I'd still like to get in https://github.com/metabase/metabase/pull/29252, which will drop DB calls further for dashboards with parameters and customized visualization_settings.

**Comment by calherries** [comment]
https://github.com/metabase/metabase/pull/29252 is merged, so I'm saying this is good enough for 46. Without having the exact numbers in front of me right now, the changes give a roughly ~4x improvement in performance for typical updates to dashboards of reasonable size (dashboards with 5-10 dashcards with 2-5 parameters).
