### ISSUE TITLE
Intelligently default to SQL Question view for active SQL users

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2914]
For users that are mainly creating SQL cards, perhaps we should default to SQL as the default view they get on 'Ask Question'?

We could do something like keep a counter for the # of successive SQL questions they've created and if that is greater than say 3, default to SQL view. 

Or a running counter of SQL and GUI questions for their last 10 questions and default if the ratio is greater than 1:1 SQL to GUI?

**Comment by mazameli** [comment]
That might be too clever by half: you could just default their New Question mode to whatever mode they were in when they saved their last saved question, or whatever mode it was when they last left the New Question view. Additionally, this could be a preference in `Account Settings` that would override this behavior (i.e. always default to SQL/native view).

The only weirdness would be that if your default mode is SQL but you want to toggle back to GUI, you'd have to do that on a blank SQL question since right now we disable the switch-to-GUI toggle when you have a dirty SQL query. Or we'd have to enable the switch-to-GUI toggle if the SQL query is dirty and just discard the SQL (with a warning modal).

Is this a common-enough annoyance for users that we should do this? I could see it being annoying for sure if I were an analyst and were tasked with creating the most-often-asked questions.

**Comment by salsakran** [comment]
So the main reason I'm bringing this up is that for many installations that have messy data models, 90% of questions are SQL. I've watched people use MB where every time they click on "Ask Question", they jump straight to the toggle. While in an ideal world, the data model is clean, and the QB is powerful enough to answer most questions, I don't want MB to be crippled in the less than ideal scenario. 

The specific heuristic I think we'd need to tune.

**Comment by marketingnerds** [comment]
I fit the pattern that @salsakran describes above. I'm generally not in favor of surprise UI changes but I would welcome some toggles in the Account Settings section. The option to default to the SQL editor would be nice. I would like to default to a specific Dashboard as the "home" page and/or post-login page as another user configuration. Sorry, scope creep.

**Comment by scpike** [comment]
@mazameli this has definitely come up for me and some colleagues as we've explored Metabase. A user level account setting (maybe hinted at somewhere on the query editing page, but even just hidden in account settings to start would be useful) seems like clearer UX to me than the app doing some auto-detection. 

If you point me in the right direction I'd be interested in helping contribute this.
