### ISSUE TITLE
Fix performance issues when loading all users' personal collections for large numbers of personal collections

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#29177]
When a large number of personal collections exist the "Other users' personal collections" menu item takes a very long time load. The below gif shows this. The solution is probably to introduce paging to the "/" endpoint in the `metabase.api.collection` ns on the backend and integrating the paged endpoint on the frontend.

![Image](https://user-images.githubusercontent.com/8381441/224753668-6d0adfb6-af9e-4c7d-bcc1-b4f2636f05a9.gif)

This is related to #28190 and #24330. The only fix that went out with those was the initial on load performance fix.

**Comment by npfitz** [comment]
The UserCollectionList component fetches all users and all collections, but uses the users to drive the list and uses the collections to generate the slugified URLs to use in the links. @luizarakaki, would we be able to have simple URLs on these cards rather than have slugified ones? IE: use `http://localhost:3000/collection/47` instead of `http://localhost:3000/collection/47-big-boi-1-s-personal-collection`. Otherwise, we may need to extend `api/collection` to only return personal collections (maybe this already exists?)

**Comment by npfitz** [comment]
As an aside, while looking into this I also discovered https://github.com/metabase/metabase/issues/36215, which should will need to be handled as well for us to notice any real gains here
