### ISSUE TITLE
"Trend" (aka Smart Number) charts don't work with Druid

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#29248]
If you create a simple Druid query that does e.g. a count of rows broken out by a time field, then select the `Trend` chart to visualize the result, you get an error message that reads `Group by a time field to see how this has changed over time`. It appears that MB is no longer recognizing columns with a data type of `type/Instant` or `type/Text` as time columns even if their metadata is set as such.

**Comment by camsaul** [comment]
Seems like this might be a Metabase lib v1/FE bug of some sort? I don't think anything related to the type hierarchy has changed

**Comment by camsaul** [comment]
Another possibility is that we're syncing Druid columns differently now as a result of upgrading the driver dependency? Need to dig a bit

**Comment by camsaul** [comment]
If this is an MLv1 bug we might want to just wait until we ship MLv2 and fix it there. TBD

**Comment by thedavidprice** [comment]
Ran into this. Let me know if I can help provide a use case or debug further.

cc @Josh-Walker-GM

**Comment by cdeweyx** [comment]
Cannot reproduce. See created trend chart [here](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNjEsInR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NTE5NDUsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiw2NjE0NzcseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lIiwidGVtcG9yYWwtdW5pdCI6Im1vbnRoIn1dXX19LCJkaXNwbGF5Ijoic21hcnRzY2FsYXIiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==). Strongly suspect this was fixed by Mlv2 per [Cam's comment](https://github.com/metabase/metabase/issues/29248#issuecomment-1470521051) so I'm going to close this.
