### ISSUE TITLE
Why clojure?

### ISSUE THREAD

**Issue by trifolium-wang** [metabase/metabase#29258]
Why not use java more broadly

**Comment by e-gaulue** [comment]
I'm not a Metabase developer... but...

I follow a lot of project on github (more than those I flagged) and often, those projects are linked to a framework.
- Prestashop: PHP, then Symfony
- Wekan: Meteor
- Metabase: Clojure
- ...

Why? Because the main developers/creators used those, and so they estimate it's easier for them to work/maintain/recruit... I'm getting old now and of course I would prefer everything to be written in C/C++/bash/Perl/PHP, but I have to adapt (the harder for me has been javascript).

Those are opensource projects everybody can fork. Anyone who want to port it to another framework can do it and if it's a good idea, he will be followed... but it's look to be a lot of work.

When Prestashop has moved from PHP to Symfony, there has been a lot of tears. The project is quite more professional now (I mean more closed because it's harder to understand the code), but more reliable and secure.

My experience regarding Metabase: you follow their dependencies request, then you go in `bin/build` and it gets build. It took me about 2 hours to find the places I wanted to change in the code and build a custom version. I've no idea of what is clojure. But I'm sure Metabase developpers will easily explain why they use clojure.

On my side I wouldn't say the trouble is clojure, but the lack of documentation (maybe I just didn't find it) regarding the project architecture: what is used, where and why... Maybe videos for developers would help to gain a bigger community of patchers. 🤷‍♂️  

Regards,

**Comment by paoliniluis** [comment]
https://clojure.org/about/rationale

**Comment by trifolium-wang** [comment]
Thanks
