### ISSUE TITLE
Scalar value font size noticeable delay on dashboards

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29304]
**Describe the bug**
Scalar values in dashboard cards have noticeable delay in rendering the full font-size.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Make an X-ray of Product table
2. Go to automatically generated dashboard "A look at your Products table"
3. Look at the first two cards in this dashboard and notice how the initial font size is small but then abruptly scales to the full font size about 1s later

**Expected behavior**
The transition should either be smooth or we shouldn't display the initial small font size.

**Screenshots/videos**
https://www.loom.com/share/7621add49aad47839d290b191eb598c8

**Severity**
Cosmetic, but it can be quite distracting especially if a dashboard has a lot of scalar cards

**Additional context**
Seems to be related to https://github.com/metabase/metabase/pull/24028 (cc @alxnddr )

**Comment by WiNloSt** [comment]
More reported at https://metaboat.slack.com/archives/C057T1QTB3L/p1689205319242359

**Comment by WiNloSt** [comment]
The problem is rather easy to fix. But I hit a huge problem when trying to test this.

First of all, testing in unit test isn't possible because `ExplicitSize` rely on the DOM dimension which it doesn't know.

Second, Cypress behaves differently between the window that has Cypress GUI and browsers. More context in https://metaboat.slack.com/archives/C505ZNNH4/p1689851816473099
