### ISSUE TITLE
"Only in detail views" visibility for columns makes column invisible in the detail view

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#29426]
### Bug description:

If you set the visibility of a column to "Only in detail views" the column will not show up in the detail view.

### Steps to reproduce:

1. Create a new question with the Orders table in the Sample Database, and select two columns:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/39073188/226880950-774987ec-78f8-44e7-bbd1-f8947940ba3d.png">
2. Visualize the results, and click the "View details" button next to one of the rows. Note both columns are visible.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/39073188/226882248-2ac14529-87a1-43e4-847f-7d7f032b670b.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/39073188/226883639-ddbf4a96-1e87-42fe-bce3-eb9e091d9deb.png">

2. In another tab, go to the data model settings for the Orders table, i.e. Admin Settings > Data Model > Data > Sample Database, and change the visibility of the `USER_ID` column from "Everywhere" to "Only in detail views".
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/39073188/226881706-e08a0a18-7288-4dc8-8bba-b949888aad89.png">
4. Return to the question and refresh the query. Click the "View details" button again. Note only the `ID` column is visible.

### Metabase version:
Reproduced on master (d91edd7)
This is a regression since everything is fine on release-x.45.x (a9803fa)

**Comment by calherries** [comment]
I git bisected this issue and found [Revert column settings changes](https://github.com/metabase/metabase/pull/28709#top) to be the offending PR.

**Comment by npfitz** [comment]
That PR was really just restoring functionality from before we tried to implement bulk show/hide columns, so that may not actually be the offending PR. I'll dig into this a little bit

**Comment by npfitz** [comment]
This is happening because the object details view leverages the `table.columns` viz setting to determine what to show. If you haven't "written" anything to `table.columns` and we're computing a default, we always default columns with a visibility type of `"details-only"` to false. Which puts us in a weird position, I'm not totally sure what the expected behavior is here.

If the Object Details view should reflect the series, then we don't really have a good way to say "Don't show this column in the table, but show it in the details view". If it's not a part of the table, then it won't be in table.columns, which for structured queries means it also won't come back in `data.cols`. It sorta works when computing the default values, but otherwise it's a bit awkward. 

@cdeweyx Do you have any thoughts?

**Comment by cdeweyx** [comment]
@npfitz Not sure if there's any more product context to add re next steps.

> We don't really have a good way to say "Don't show this column in the table, but show it in the details view"

If this is indeed the case, then what I'm hearing is that the "Only in detail views" data model option is just flat-out broken, and will require some data-restructuring to make it work as expected.

**Comment by calherries** [comment]
Closing because I can't reproduce this on master anymore (892368e550c692ca31f5e85c506166c60c85426a).
I can still repro on master when this ticket created though (d91edd7133134633c2c21a88ce8fc312a48e7dc4).
