### ISSUE TITLE
Cannot set custom y-scale range from zero when it is logarithmic

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#29494]
**Describe the bug**
Cannot set custom y-scale range from zero when it is logarithmic. The error message about it is not clear too.
There is a workaround: use very small integer like `0.0000001` instead of `0`.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create any line/area/bar chart 
2. Go to visual settings -> axes
3. Set the y-axis scale to `log`
4. Try set the y-axis range from 0 to 100

**Expected behavior**
It should allow setting the min value to 0

**Screenshots/videos**

<img width="1249" alt="image (3)" src="https://user-images.githubusercontent.com/14301985/227294197-801766e4-59fc-48fa-979a-e1fac2500ded.png">

**Comment by yugander-krishan-singh** [comment]
@alxnddr I am interested in picking up this issue. Kindly let me know if there are concerns with that.

Also I tried reproducing the issue using latest metabase docker image and have question mentioned below:

As displayed in the image from issue description, metabase is allowing to set `min` value to `0` at present. This is because I am able to click on `Done` button and after that I visit the `axes` again under `Visualization` I can see the `min` value still set to `0` on `log` scale which, in my understanding, is the expected behavior.

Could you pls let me know what am I missing here with respect to the expected behavior?

**Comment by alxnddr** [comment]
Fixed by https://github.com/metabase/metabase/pull/41395
