### ISSUE TITLE
Allow making string/contains and string/does-not-contain filters in native questions case-insensitive

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#29887]
Epic https://github.com/metabase/metabase/issues/29881

We need to make `string/contains` and `string/does-not-contain` field filters in native questions to be case-insensitive. It should work for both parameter values and default values.

The BE already accepts parameter options to make `string/contains` case insensitive (e.g. in `/api/dataset`). However it works only when there a value for the parameter set, and it doesn't with default values for template tags in native queries. If there is no value for the given template tag and the tag has a default value, no parameter instance is created.

**Proposed api changes**

Add optional `options` field in `TemplateTag` with parameter options. For new `string/contains` template tags the FE will set 
`{ "case-sensitive": false `}. When there is a default value for such a template tag, the BE should honor case sensitivity options included in the tag. The shape of this object matches what we send for regular `Parameter`s.

```
"dataset_query": {
  "native": {
    "template-tags": {
      "id":  {
        "options": {
          "case-sensitive": false
        }
      }
    }
  }
}
```

**Comment by bshepherdson** [comment]
I'm a little wary of a `false` option. It seems error-prone to distinguish missing from `false`.

Is there a reason not to add this as a positive option `"ignore-case": true` instead?

Either way, this plan looks good to me overall.

**Comment by camsaul** [comment]
In general I'd agree with you @bshepherdson, but I think in this case this does make sense because it matches the shape we have for the corresponding string filter clauses like `:starts-with`. I'd rather have one slightly-less-than-optimal shape in two places than have it in one place and a different slightly better shape in the other place.

Either way, I think including `options` in that location works for me.
