### ISSUE TITLE
Revisit Edit Mode on Questions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#2992]
I'm finding myself (and @tlrobinson has expressed the same feelings) never hitting "edit" when I'm updating a question on dashboards. Especially with SQL, I over and over again that I just start editing the SQL immediately and then get to the new save dialog.

What's especially wack is that when I get there and click `overwrite` I'm *still* staring at two input fields for the name + description. And if I click back to `new question`, the old name overwrites the autosuggested name for a derivative question.

**Comment by mazameli** [comment]
So I think one thing you're implicitly suggesting is that we consider changing the default option in the Save/edit dialogue to `replace` instead of `Save new`. I think this could make sense, as it's probably a more common pattern in other applications.

If we do that, it would also feel natural to remove the `Name` and `Description` fields from the `replace` state, and only show them if you're saving a new question.

So it would be like this:
![replace original question](https://cloud.githubusercontent.com/assets/2223916/17575507/8db1fac4-5f1e-11e6-8172-610a39539665.png)

![save cloned question](https://cloud.githubusercontent.com/assets/2223916/17575522/94e1f5e2-5f1e-11e6-8ae0-4a0d2be98397.png)

Also, if someone starts working on this, it would be awesome to make the radio selections match the custom CSS style instead of using default radio buttons, and also to add a `cursor: pointer` on the click targets. Here's how it looks currently, which is sad:
![screen shot 2016-08-10 at 5 19 57 pm](https://cloud.githubusercontent.com/assets/2223916/17575548/f1049b4a-5f1e-11e6-9f0f-b28cfa207e28.png)
