### ISSUE TITLE
"People can pick" ->multiple values in dashboards and custom dropdown filter don't go together

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29997]
**Is your feature request related to a problem? Please describe.**
If you make a SQL question in the form of 
```
select * from people where state = {{state}};
```
you use custom values, and you add it to a dashboard, the dashboard filter will tell you that you can use "multiple values" which is confusing
![image](https://user-images.githubusercontent.com/1711649/233155991-5d65874b-2ea3-4ff3-9605-b10a614a1a92.png)

If the question has a custom filter, then the filter will need to show only "a single value"

**Describe the solution you'd like**
Disable the "Multiple values" if you're connecting the filter to a SQL question that doesn't use a field filter

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/4728

**Comment by brunobergher** [comment]
Why is this a feature request and not a bug? Shouldn't the multiple-values one be, well, passing multiple values?

**Comment by paoliniluis** [comment]
I thought this was made on purpose, seems like it wasn't

**Comment by WiNloSt** [comment]
The repro for this issue needs an extra step. That is to add custom values to the parameter. Could be from a custom list or another question or model.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/1937582/233116224-b954a13c-d2c1-4ca6-a40f-92effd6762ab.png">

Normally, if you just add a text parameter you'll get just a text input without any autocompletion
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1937582/233117276-0120a8a3-1f52-42c7-97bf-5d0cb97bf2ac.png">

This allows us to type multiple values in a comma-separated format.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/1937582/233117655-a863e381-b64d-4a51-b701-172b9dc565d1.png">

However, the problem is that when we set custom values to a parameter the parameter widget will only support a single value.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/1937582/233118363-8f3ac05e-0f06-4101-9684-53e2b9220e6c.png">

This means the parameter widget behaviors are different which I think we should address.

One solution is to change the FE so that even when we show the widget that supports multiple values, we still send a single value as if there are no values set for a parameter. And the reason for this solution is also that we know we only support single value for question with template tags (native questions), so this is a FE quality-of-life change for parameter widgets to support multiple values.

cc @ranquild

**Comment by paoliniluis** [comment]
So tested this with 3 questions: a gui question, a sql question with a parameter and a sql question with a field filter

#GUI question with category:
##dropdown list from connected fields
- multivalue: ok
- single value: ok

##from another model or question - gui question:
- multivalue: ok
- single value: ok

##from another model or question - sql question:
- multivalue: ok
- single value: ok

# SQL question with normal param
##dropdown list from connected fields
- does not appear: ok

##from another model or question - gui question:
- multivalue: does not appear (great, we don't want multi value here if the query is x = y)
- single value: ok

##from another model or question - sql question:
- multivalue: does not appear (great, we don't want multi value here if the query is x = y)
- single value: ok

# SQL question with field filter
##dropdown list from connected fields
- multivalue: ok
- single value: ok

##from another model or question - gui question:
- multivalue: ok
- single value: ok

##from another model or question - sql question:
- multivalue: ok
- single value: ok
