### ISSUE TITLE
When accessin questions and dashboards, OSX app sometimes reloads

### ISSUE THREAD

**Issue by MarkVillacampa** [metabase/metabase#2999]
* My OSX version is Sierra 10.12 beta 3.
*  I'm running Metabase locally with the Mac App H2 database.
*  My data is in a Postgres database.
*  My Metabase version is 0.18.1.1.

Sometimes, when I open a dashboard or a question, the app reloads and I get to the initial screen.

I would appreciate any hints on how to debug/provide more info to see what would be causing these reloads.

**Comment by camsaul** [comment]
@MarkVillacampa are they particularly slow dashboards or questions?

**Comment by MarkVillacampa** [comment]
Yes, they are kinda slow

**Comment by salsakran** [comment]
someone else is hitting this http://discourse.metabase.com/t/dashboard-loads-for-a-sec-and-redirects-me-back-to-activity-feed/596/2

**Comment by camsaul** [comment]
The problem was the Mac App would restart the server if it became nonresponsive for 15 seconds. This number was too low, which caused issues like this one.  

In 4c2f9f74524202796084399b24069d4378fb3cf9 I upped the timeout to 60 seconds, which resolves this issue in the test cases I was able to come up with.

@MarkVillacampa Metabase 0.20 is expected to ship in the next few weeks and contains the aforementioned fix. Please reöpen this issue if you are still seeing it after you've upgraded to 0.20.

Fixed by #4c2f9f74524202796084399b24069d4378fb3cf9

**Comment by doodlebro** [comment]
Can this issue be re-opened? It doesn't appear to be related to the timeouts discussed earlier, however on the latest Mac App (0.22.2) I have added a tenth tile to my dashboard, yet when I go to the dashboard to check it, the app is kicked back to the activity feed in less than 3 or 4 seconds.

Let me know if I should open a new issue for this. It seems related enough to re-open this one.

**Comment by camsaul** [comment]
@doodlebro we have a new open issue to track this bug #3950
