### ISSUE TITLE
Feature Request: Support BigQuery Standard SQL

### ISSUE THREAD

**Issue by tomkanjam** [metabase/metabase#3012]
Would be nice to have an option in the Question SQL editor to specify that the Standard SQL flag should be included in the query.

https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql

**Comment by gitram** [comment]
Here's my hack for this issue: https://gist.github.com/8eebbb2f6695583d0bf9b9181cfbbeef

As long as you have "--nolegacy" as a comment it should interpret as standard SQL.

**Comment by camsaul** [comment]
@gitram that looks like a workable solution. 👍 

@salsakran BigQuery has two SQL syntaxes, the older "legacy" syntax that looks like legacy SQL Server syntax (e.g. brackets are used to quote identifiers), and a new more ANSI-compliant syntax (double-quotes to quote identifiers, like Postgres). In the BigQuery web console there's a switch to disable legacy syntax.

We've been using legacy syntax thus far but we could give people to use ANSI-compliant syntax either by doing something like @gitram's solution or perhaps instead adding a toggle switch to the SQL editor specifically for BigQuery. If we go with @gitram's solution we'll want to make sure we add documentation so people know they can use it. Thoughts?

**Comment by salsakran** [comment]
can we just just respect/pass through the 
```
#legacySQL	Runs the query using legacy SQL
#standardSQL	Runs the query using standard SQL
```

**Comment by camsaul** [comment]
I didn't realize they already had a way to do that. Using `#legacySQL` or `#standardSQL` sounds like the way to go.

@salsakran we've been using legacy SQL this whole time and our BigQuery driver is set to generate legacy SQL so: 

1.  We'd break existing people's SQL queries if we made standard the default. We could work around this if we write a data migration that prepends `#legacySQL` to existing bigquery SQL cards
2.  The BigQuery QP will have to be tweaked

It still might be worth it. Either way, we should open a new issue to look into making standard SQL the default for BigQuery and go ahead and close this out since BigQuery already has a way of doing it.

**Comment by gitram** [comment]
We may have to default to Legacy (and allow people to switch default in the settings)? as this could break existing handcrafted SQL questions.

**Comment by salsakran** [comment]
Yeah, if we *do* make StandardSQL the default, I think we'd need to migrate folks current cards that are LegacySQL. 

I'd rather not keep digging the hole deeper by encouraging people to use what and older syntax. 

I haven't kept up, but is there a reason to prefer LegacySQL to StandardSQL at this point?

**Comment by camsaul** [comment]
@salsakran we're just using legacy SQL because standard SQL support wasn't around when we started supporting it

**Comment by salsakran** [comment]
I get that, my question, restated would be:
If I was writing BQ queries at this point in time, is there anything that's possible or easier in LegacySQL that's impossible in StandardSQL? Eg, would a reasonable sane person prefer LegacySQL (or GQL or whatever the previous incarnation was) for any reason?

**Comment by camsaul** [comment]
The only reason you'd prefer it I think would be if you already have existing queries written in it. [Google wants people to switch because apparently the standard syntax is more flexible](https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql#standard_sql_highlights)

**Comment by salsakran** [comment]
Can we verify that the JDBC driver respects the '#blah' opening line?

**Comment by camsaul** [comment]
Actually after reading the dox I don't know that it will because we prepend the comment with query hash / user / etc. to all SQL queries before running them.

Sounds like it only works if it's on the first line:

> Some third-party tools might not support this prefix if, for example, they modify the query text before sending it to BigQuery.

**Comment by camsaul** [comment]
We could do something like what @gitram was suggesting and just scan the query for that directive and if we see it switch legacy mode on or off ourselves

**Comment by camsaul** [comment]
alternatively we could just skip prepending the query info if we see a directive like that at the beginning of the query, it's probably not super-important here and it's only for "legacy" queries

**Comment by salsakran** [comment]
I'd rather not start to accumulate weird special cases wrt to query info pre-pends.

**Comment by Cidan** [comment]
Any update on this?

**Comment by bedeoverend** [comment]
@camsaul @salsakran my vote is for:

- Default to standard SQL
- Toggle switch in admin on database saying which query to default to
- Set toggle on old bigquery databases (when upgrading) to use legacy to preserve backwards compat
- Use @gitram's suggested or similar syntax for toggling on a per-query basis

For that last point, and @salsakran's concern about adding special case flags, can you add in `#standardSQL` and _scan_ it using same method as @gitram and switch the flag? It wouldn't be a passthrough (due to issue flagged by @camsaul) but it would follow the same interface and end up with the same result - therefore you can consider the weird special case a BigQuery special case, rather than something metabase added in. I feel like that's a clean delineation, and allows people to follow easily along with BigQuery's docs.

**Comment by joshreuben456** [comment]
👍

**Comment by joshreuben456** [comment]
Have a standard SQL `WITH` statement
here is code:
```
#StandardSQL
--nolegacy
WITH channels_activity AS (
SELECT DISTINCT channel_id, DATE(event_timestamp) AS day
FROM apester_events.raw_events
WHERE event_name = 'interaction_published'
AND event_timestamp BETWEEN TIMESTAMP({{start_dt}}) AND TIMESTAMP({{stop_dt}})
), 
channels_categories AS(
SELECT channel_id, COUNT(*) as total, DATE_DIFF(DATE({{stop_dt}}), DATE({{start_dt}}), DAY)) AS category
FROM channels_activity
GROUP BY channel_id
)

SELECT category, COUNT(*) AS result
FROM channels_categories
GROUP BY category;
```
get error `Encountered " "WITH" "WITH "" at line 4, column 1. Was expecting: <EOF>`
`--nolegacy` is not working
`#StandardSQL` is not yet supported ?

**Comment by remydavid** [comment]
Same here !

Self contained test : 
`
#standardSQL
WITH T AS (
  SELECT 1 AS row, ['foo', 'param'] AS query_params,
    ['bar', 'val'] AS query_values UNION ALL
  SELECT 2, ['foo'], ['baz']
)
SELECT row, query_param, query_values[OFFSET(o)] AS query_value
FROM T, UNNEST(query_params) AS query_param WITH OFFSET o
WHERE query_param = 'foo';`

Works in BQ console, not in Metabase

**Comment by camsaul** [comment]
@joshreuben456 it's not yet supported, hence this issue still being open 😉

**Comment by camsaul** [comment]
Implemented by #4433 

In the next release of Metabase, just add the `#standardSQL` directive to the beginning of the query to use standard SQL.

**Comment by VikramTiwari** [comment]
Are there any plans to put this flag in UI as well, so that queries after MBQL are converted to Standard SQL?

**Comment by camsaul** [comment]
@VikramTiwari not at the moment. Our BigQuery driver was written before standard SQL was available so it still produces queries in legacy SQL. At some point in the future I might get some time to rework it to produce standard SQL instead of legacy.

**Comment by VikramTiwari** [comment]
@camsaul I liked your idea of investigating available ODBC drivers, which might reduce some of work required for that.

**Comment by camsaul** [comment]
@VikramTiwari switching the the official JDBC driver wouldn't help here since compiling queries to SQL would still be the same amount of work. It would make running those queries and getting metadata a little more straightforward.
