### ISSUE TITLE
Support Treasure Data

### ISSUE THREAD

**Issue by dlackty** [metabase/metabase#3044]
[Treasure Data](https://www.treasuredata.com/) is a hosted big data analytics solution based on Presto / Hive.

They provide [a simple JDBC driver](https://docs.treasuredata.com/articles/jdbc-driver) to execute Presto / Hive SQL queries (We mainly use Presto).

See also #2749.

**Comment by camsaul** [comment]
Hi @dlackty, we're adding support for various DBs based on community demand. Since you're the only person who's asked for Treasure Data thus far, that might be a while 😉 

If you're feeling adventurous you can try [writing a driver yourself](https://github.com/metabase/metabase/wiki/Writing-A-Driver). I'm available to help with any questions you might run into.

**Comment by toru-takahashi** [comment]
Now, you can connect to TreasureData via Presto connection.
https://docs.treasuredata.com/articles/metabase

**Comment by flamber** [comment]
As previously noted, a regular PrestoDB connection is enough, which Metabase already supports:
https://docs.treasuredata.com/display/public/PD/JDBC+Driver+for+Presto
