### ISSUE TITLE
remove emails case sensitivity

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#3047]
All the emails are case sensitive as of now which stops users from logging in (and other operations) when the case is not matched with DB value.

Should lowercase all email values, right after user input.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
The local address part of emails is technically case-sensitive:

> The local-part of a mailbox MUST BE treated as case sensitive. Therefore, SMTP implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith". However, exploiting the case sensitivity of mailbox local-parts impedes interoperability and is discouraged. Mailbox domains follow normal DNS rules and are hence not case sensitive.

Source: [RFC 5321](http://www.rfc-editor.org/rfc/rfc5321.txt)

**Comment by VikramTiwari** [comment]
Good reference. Even though we see almost all public email providers making the local part insensitive, it might not be the same for organizations who maintain their own email servers. Looking for suggestions on best possible fix, if any.

**Comment by camsaul** [comment]
I agree that it would probably be more useful for *almost* everybody if we treated email as case-insensitive for login purposes but I am wary of doing things that might break Metabase for one random person out there who broke our assumptions

**Comment by pate** [comment]
Our CEO couldn't log into Metabase each time after resetting their password. Turns out their autocomplete email address had a capital in the input, which ruined their login attempt after the reset.

I am in the same camp as Jeff Atwood, who has [blogged about this](https://blog.codinghorror.com/the-case-for-case-insensitivity/): Metabase is meant for humans, and humans do not care about case-sensitivity.

**Comment by pate** [comment]
I see there is a [pull request](https://github.com/metabase/metabase/pull/3048/commits) for this, but it will need a migration to lowercase any existing email usernames. I can't tell if this has been accepted in to the master codebase or not?

**Comment by salsakran** [comment]
@pate We don't ever store unhashed passwords, so the migration you describe is impossible.

**Comment by camsaul** [comment]
@pate, of course Metabase is meant for humans. But the email standard says that the beginning of email addresses is case-sensitive, and pretending it's not means potentially breaking things for a random person or two out there. I agree that overall it would probably be for the best, but it's a decision whose consequences we need to carefully consider.

**Comment by qerim** [comment]
Can we please add a toggle in settings for people who want to make email login case insensitive?

**Comment by slickrock22** [comment]
I agree with making the login case-insensitive.  Store compliant with email standards but validate without case sensitivity.

**Comment by QCaudron** [comment]
We just found out why one of our users couldn't log in. Thankfully, this is a known thing !

+1 for case-insensitive emails. I can't think of **any** system out there where logging in with an email address requires me to be case-sensitive. A toggle is fine, but I'd hazard a guess that it isn't necessary for anyone.

**Comment by mkopinsky** [comment]
I'd like to add another vote for making emails case insensitive, or at a minimum adding that as a configuration option. On multiple occasions (say, 4 out 12 users in out metabase instance) a user's first experience with Metabase was "I can't log in, I tried resetting my password, halp!", and this is from technically capable people who don't usually struggle with logging into things. I know now that I shouldn't invite them as John.Doe@example.com even though that's the "correct" version in Outlook, because they're inevitably going to try to log in as john.doe@example.com instead.

I don't think the solution is to lowercase all emails - as mentioned above, that can cause compatibility issues if an email server will only accept email to John.Doe but not john.doe. Instead you should store the email address as originally invited but use case insensitive comparisons. This means that you have to restrict creating an account for JoHn.DoE even though it's a unique email address, but I think it's almost never the case that two such email addresses would ever exist for two separate users.

**Comment by theronic** [comment]
RFCs are out-of-date documentation for how humans actually uses the Internet. Nobody wants case-sensitive login comparison, but we want our cAsE-sensitive input preserved. Facebook even stores 4 passwords which is tests hashed input agains: Original, iNVERTED, UPPERCASE and lowercase.

The solution seems to be to store case-sensitive emails, but to compare input against lowercase. And perphaps that means having two columns, `email_lowercase` and `email`.

**Comment by mazameli** [comment]
This is silly. I'm strongly in favor of making emails case insensitive. I can't remember ever encountering a login page that was case sensitive.

**Comment by trentreese** [comment]
we've had the same issues at my company. I realized this because postgres queries are case sensitive and the config is based on a postgres db. This is super confusing for an application to fail on this, frustrating for business users and not very intuitive to troubleshoot.

**Comment by amex-doug** [comment]
We had this same issue just now and it led to a lot of confusion for our users because the message kept saying the password did not match the stored one.

**Comment by danlopez** [comment]
This has been an issue for us as well, this should be configurable. It's highly non-standard and has led to quite a bit of confusion amongst our user base.

**Comment by danlopez** [comment]
@flamber - this appears to be the root cause for the issue we reported to support.

**Comment by flamber** [comment]
@danlopez That was what I suspected. I've added internal notes on your ticket, so we can track it.

**Comment by Caerbannog** [comment]
A possible mitigation mentionned in #12987 would be to warn admins about this behaviour when an account is created with capital letters.
Another mitigation would be to show the same warning on the "Users" page, where admin are likely to look at when troubleshooting related problems.

**Comment by mazameli** [comment]
@Caerbannog Thanks for those completely reasonable suggestions, but the reality is that that's just putting a bandaid over the real problem — we just need to fix this and remove the case sensitivity.

**Comment by camsaul** [comment]
to fix this we'll want to:

1.  Add a migration to convert existing values of the email column to lower-case
2.  Make sure all new values of the email column are converted to lower-case when saved

**Comment by sbelak** [comment]
shouldn't we also downcase inputed emails (when eg. logging in)?
