### ISSUE TITLE
Cannot Integrate Slack. 

### ISSUE THREAD

**Issue by achouhans** [metabase/metabase#3049]
This below is the 500 error.

ERROR metabase.middleware :: PUT /api/slack/settings 500 (1 s) {:message "Read timed out", :stacktrace ["integrations.slack$do_slack_request.invokeStatic(slack.clj:33)" "integrations.slack$do_slack_request.doInvoke(slack.clj:31)" "api.slack$fn__24628$fn__24631$fn__24632.invoke(slack.clj:18)" "api.slack$fn__24628$fn__24631.invoke(slack.clj:15)" "api.common.internal$wrap_catch_api_exceptions.invokeStatic(internal.clj:219)" "api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:216)" "api.slack$fn__24628.invokeStatic(slack.clj:9)" "api.slack$fn__24628.invoke(slack.clj:9)" "middleware$enforce_authentication$fn__24926.invoke(middleware.clj:78)" "api.routes$fn__25050.invokeStatic(routes.clj:55)" "api.routes$fn__25050.invoke(routes.clj:55)" "routes$fn__29978.invokeStatic(routes.clj:24)" "routes$fn__29978.invoke(routes.clj:24)" "middleware$log_api_call$fn__25011.invoke(middleware.clj:260)" "middleware$add_security_headers$fn__24971.invoke(middleware.clj:197)" "middleware$bind_current_user$fn__24930.invoke(middleware.clj:93)" "middleware$wrap_current_user_id$fn__24917.invoke(middleware.clj:61)" "middleware$wrap_api_key$fn__24937.invoke(middleware.clj:104)" "middleware$wrap_session_id$fn__24910.invoke(middleware.clj:52)"]}

For more details: http://discourse.metabase.com/t/cannot-integrate-with-slack/551

**Comment by salsakran** [comment]
@achouhans are you using a test token or a bot token?
and are you still seeing this error?

**Comment by camsaul** [comment]
@achouhans ?

**Comment by camsaul** [comment]
@achouhans ?

**Comment by camsaul** [comment]
@achouhans ?

**Comment by camsaul** [comment]
@achouhans ?

**Comment by camsaul** [comment]
@achouhans We've made several fixes for the MetaBot in the meantime, including exponential backoff for reconnections and support for using a proper Bot token instead of a test token; I think those should fix the issue you're describing here. 

Since we don't have enough information to diagnose the problem you experienced and haven't heard back since July I'm going to go ahead and close this issue. Feel free to open a new issue if you run into this problem again.
