### ISSUE TITLE
[MLv2] [Bug] Phantom columns in queries based on questions/models

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30950]
Seems like `orderableColumns` and `breakoutableColumns` can return columns from foreign tables of a source/joined question/model

### To Reproduce

1. New > Question > Raw Data > Sample Database > Orders > Save
2. New > Question > Saved Questions > Pick the question from step 1
3. Click the sort icon to add a new order-by clause
4. Notice the "People > Name" column in the "Order" column group

### Demo

https://github.com/metabase/metabase/assets/17258145/e98b2528-12f7-4ee8-a2da-7120cb2322a6

**Comment by camsaul** [comment]
So, we do want to show those implicitly joinable columns initially when you're creating a new query, (I explicitly added them to `orderableColumns` to match the MLv1 behavior), is the expectation that we don't want to show implicitly joinable columns if you're using a Saved Question or Model as your "source" rather than a Table? Table = show implicitly joinable columns, Saved Question/Model = only show columns in the results? 

We're intentionally including that stuff so it seems weird to special-case it and only include it sometimes but not others. If you think of a Model as a drop-in replacement for a Table, then I would expect it to include the same implicitly joinable columns in the order by drop-down. CC @luizarakaki for product perspective

**Comment by luizarakaki** [comment]
Today, we show implicit columns from Models: https://stats.metabase.com/model/4520-orders-model/notebook

But we don't for questions.

I think this behavior makes sense, as the question can manipulate data in a way that prevents implicit joins (like aggregations), and joins are defined explicitly in Models.
