### ISSUE TITLE
Cumulative Sum is no longer Cumulative after transfer to SQL

### ISSUE THREAD

**Issue by hivre** [metabase/metabase#3110]
If I make a question containing a `Cumulative Sum`, and then convert that question to SQL, the sum is no longer cumulative.

I'm not sure if this is expected behaviour? I'd like to edit the SQL, as I'd like to display month-over-month graphs, which need the date format to be 'day of the month' instead of the actual day (thus [1...31] instead of [1-7-2016 - 31-8-2016]).
(I looked at extending Metabase to get a 'day of the month' feature, but I haven't programmed Java for such a long time that I got lost in the code)

If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is Win10.
*  I'm running Metabase locally from the JAR and it is using the MySQL database.
*  My data is in a MySQL 
*  My Metabase version is 0.18.1/0.19 on Ubuntu

**Comment by camsaul** [comment]
Unfortunately the actual cumulative summing for the column in question is done with the results of the query on the server since there's no workable way (that I'm aware of) to do that in our various supported dialects of SQL. We should make this explicit so there isn't confusion when converting a query of that type to SQL.

@tlrobinson, are we exposing the day of month option on the frontend? It's implemented in the query processor.

Also @hivre our code is in Clojure, not Java 😏

**Comment by hivre** [comment]
Thanks.
The clojure thing explains so much :-P 

Anyhow, feel free to close.
