### ISSUE TITLE
Deprecate Elastic Beanstalk

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31151]
### Describe the bug

We can’t encourage anyone to use elastic beanstalk anymore:
- it’s a black box, our users can’t see the logs easily, and I’m not even considering when things don’t go well where you can’t see what happened with the machine
- AWS doesn’t upgrade it at the same pace it does with other products
- it fails a lot with certain configurations (e.g it obliges your to use multi az on rds when you don’t want to spin up an rds)

If we want to make Metabase easy to use, we can ni longer recommend nor have guides for an AWS product that we wouldn’t use. It would be even easier and more sustainable if we built terraform or cloudformation scripts with a simpler architecture (you can run Metabase in a server connected to an rds db, why would we use a product that was made to deploy entire stacks?)

### To Reproduce

NA

### Expected behavior

NA

### Logs

NA

### Information about your Metabase installation

```JSON
NA
```

### Severity

P1

### Additional context

I know that many people will put a thumbs down to this issue, but if we want to build the simplest way of getting information out of your DB, Beanstalk shouldn’t be on that list.

**Comment by brunobergher** [comment]
That's entirely fair. Do we mention it anywhere in the product or just on docs/website?

**Comment by paoliniluis** [comment]
Just docs

**Comment by brunobergher** [comment]
Let's do it, I'll get it going.

**Comment by paoliniluis** [comment]
Another reason to deprecate beanstalk https://discourse.metabase.com/t/aws-elb-launch-configuration-to-launch-template/25648/3

**Comment by likeshumidity** [comment]
@paoliniluis , I think it makes sense to deprecate AWS Elastic Beanstalk and instead maintain a Terraform provider like this request:
-  https://github.com/metabase/metabase/issues/17059

Maybe we publish a few example `docker-compose.yml`'s showing different architectural/configuration options like we already do in our public example repos.

**Comment by likeshumidity** [comment]
Related to:
- https://github.com/metabase/metabase/issues/17263
- https://github.com/metabase/metabase/issues/19383
- https://github.com/metabase/metabase/issues/18290
- https://github.com/metabase/metabase/issues/29508
- https://github.com/metabase/metabase/issues/21140

**Comment by brunobergher** [comment]
Let's make sure to suggest 1+ alternatives and provide basic guidance on what would be needed to migrate *out* of Beanstalk. In other words: explain what needs to be done to get an appdb dump and how it can be used elsewhere later.

**Comment by matulef** [comment]
Small request to bring back the documentation for upgrading an existing elastic beanstalk deployment. e.g. this section here: https://www.metabase.com/docs/v0.46/installation-and-operation/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase-on-elastic-beanstalk

Even though EB is no longer recommended, folks with existing deployments might need to apply patch releases before fully migrating off. You can preface this section with a warning about how EB is deprecated, etc., but I think it's still useful to include the instructions.

**Comment by paoliniluis** [comment]
@jeff-bruemmer 👆🏻

**Comment by cycomachead** [comment]
I want to second the request to keep the EB docs with a link.
I'm not sure if it's intentional, but it looks like the EB bundle still gets built, and even when I go to the [v0.46 docs](https://www.metabase.com/docs/v0.46/installation-and-operation/running-metabase-on-elastic-beanstalk#deploying-new-versions-of-metabase-on-elastic-beanstalk), what URL I actually see is this: https://downloads.metabase.com/v0.47.2/metabase-aws-eb.zip

I'm grateful the zip keeps getting built. 

I'm 100% on board with EB not being great and having...challenges... but it is effective at minimizing the time spent, at least when things aren't too complex. I would definitely love a recommended "simplest AWS Metabase" guide that migrates off EB. I've already got by primary database in RDS, so I'm looking into probably setting up ECS on Fargate.
It sounds like y'all don't use AWS much from the initial post, but I will say that having _something_ that lives in AWS can be helpful. The advantage for me of the EB config was that it was quick enough to get SSL setup too, which some of the current guides don't provide automatically.

**Comment by ds-clearago** [comment]
Just to clarify – there is no upgrade path in the docs what to do if I'm currently running Metabase in Beanstalk. I.e. highest version I can easily upgrade to is 0.47.2 because after that the metabase-aws-eb.zip is not published anymore right?

And if I want to upgrade to something newer, then I have to use one of the other installation paths mentioned in the docs, right?

It would be great if this was explicitly mentioned in the docs and some recommendations were given what the simplest alternative to EB within AWS would be (whether that's docker ECS or Fargate or something else). 

Right now I'd love to just quickly upgrade and do this migration later, but I'll just stay with 0.47.2 for now then :/

**Comment by paoliniluis** [comment]
Added a few lines https://github.com/metabase/metabase/pull/34715
