### ISSUE TITLE
log() - logarithm function calculates wrong result in BigQuery because parameters backwards

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#31153]
### Describe the bug

- Using the Metabase `log()` function with BigQuery calculates the wrong result because Metabase mixes up the parameters
- As per [these BigQuery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log), `log()` should be used like `log(x, base)`, but Metabase is sending `log(base, x)` to BigQuery resulting in incorrect results.

### To Reproduce

1. Create a Question on a BigQuery table
2. Add a custom expression called log10 - `log(10)`
3. Add a custom expression called log100 - `log(100)`
4. Add a custom expression called log1000 - `log(1000)`
5. Click Visualize to see the results of the custom expressions
![image](https://github.com/metabase/metabase/assets/8808703/56074cd6-c6c9-4d27-8560-2c8a318502b9)

Values:
  - log10 should be 1
  - log100 should be 2
  - log1000 should be 3

6. Click View SQL and see that x and base are reversed:
```
SELECT `zendesk_16700.datesAndAmounts`.`date` AS `date`, `zendesk_16700.datesAndAmounts`.`amount` AS `amount`, log(10, 10) AS `log10`, log(10, 100) AS `log100`, log(10, 1000) AS `log1000` FROM `zendesk_16700.datesAndAmounts`
```

### Expected behavior

- Should use BigQuery `log()` function like `log(x, base)` instead of `log(base, x)`

### Information about your Metabase installation

```JSON
- Metabase version: v1.46.4
```

### Severity

P1 - producing incorrect result with no error or warning

**Comment by mayankagarwals** [comment]
Hey, I'd love to take this up. @qnkhuat @nemanjaglumac Could you please help me with which file to start from. I believe the change will be in the query translation that happens from metabase's modelling of query to DB's format of query

**Comment by qnkhuat** [comment]
@mayankagarwals awesome.

From the high level, we translate from an MBQL -> honeysql -> native query. In this case, the bug comes from the fact that we're generating the wrong honeysql form, this is done by the method `metabase.driver.sql.query-processor/->honeysql [driver :log]`

So to fix this you need to define a custom method for bigquery, [here](https://github.com/metabase/metabase/blob/master/src/metabase/driver/h2.clj#L346) is an example of how we define for h2. You need to put the implementation for bigquery in [this](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj) file.

And of course, don't forget to add tests for it.
