### ISSUE TITLE
Export to PDF just exports the current tab

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#31228]
### Describe the bug

Is this the intended way this should work?

### To Reproduce

1) Build a dashboard with 2 tabs
2) put 2 different questions, one on each tab
3) export to PDF, it's going to print just the active tab

### Expected behavior

Is this the intended way we thought this feature?

### Information about your Metabase installation

```JSON
master
```

### Severity

?

**Comment by oisincoveney** [comment]
After a little bit of investigation, it seems that the way we're saving Dashboard PDFs is based on _what is actually on the screen at the time_ rather than using a dashboard object - essentially, the PDF logic is taking a screenshot of the page. I completely agree that maybe we should be able to provide an option to save a single page or the whole dashboard to a PDF, just not sure how technically feasible it is with the current state.

@npfitz maybe you can chime in since you worked on this? Happy to be corrected if I'm wrong about the PDF logic

**Comment by cdeweyx** [comment]
👆 If it's not feasible given the current implementation (I have a suspicion multiple tabs could be tricky) then this is `.WontFix` for now and I'll make a note to call this out in the docs.
