### ISSUE TITLE
Load from H2 blows up on raw_column fk_target_column_id that aren't present in the table yet

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3151]
When loading a database that contained foreign keys, dncpax got an error - 
http://discourse.metabase.com/t/migrate-from-h2-to-postgresql/597

Given that this table allows self references and the order can't really be constrained, we should be more graceful in how the command handles this. 

Can't tell if this is a situation where `insert-self-referencing-entity!`   https://github.com/metabase/metabase/blob/master/src/metabase/cmd/load_from_h2.clj#L112 is buggy or just not catching this case.

**Comment by camsaul** [comment]
The `insert-self-referencing-entity!` stuff was added as part of a fix for a similar issue, #2632 

I'm guessing this is what's happening:

Someone has a foreign key field ("A") pointing to another foreign key field ("B"). In that case whether A or B is inserted first would be indeterminate; if A was inserted first it would fail because the FK constraint to B would fail. And that's what I'm guessing is happening.

**Comment by camsaul** [comment]
As mentioned in #2632 we *might* be able to do [something like](https://www.postgresql.org/docs/9.5/static/sql-set-constraints.html)

```sql
SET CONSTRAINTS REFERENCES DEFERRED;
```

Not sure off the top of my head how to do that for MySQL

**Comment by dncpax** [comment]
"It might even make sense to drop indexes, constraints, and triggers, and then rebuild them after the import is complete"? (source http://stackoverflow.com/questions/3437398/how-to-import-huge-chunks-of-data-to-postgresql)
