### ISSUE TITLE
[MLv2] Port legacy metrics to MLv2

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#31871]
People can use legacy metrics in aggregation clauses, and we need first-class support from them in MLv2:

- [x] we need a method to list available metrics
- [x] `display-info` should handle an opaque legacy metric object (required fields: display name, description)
- [x] if a metric is used in a clause, it has to have a `selected: true` property in a metric list
- [x] it should be possible to construct a clause with the `aggregation-clause` method and pass it to the `aggregate` method

**Comment by camsaul** [comment]
`display-info` definitely already works on Metric objects from the DB, not sure if we set it up to work on a `:metric` MBQL clause or not but that would be trivial to do.

**Comment by camsaul** [comment]
> it should be possible to construct a clause with the aggregation-clause method and pass it to the aggregate method

Not really sure this makes sense, since `aggregation-clause` takes and aggregation operator like `:sum` and (optionally) a column and returns an MBQL clause like `[:sum {} [:field {} 1]]`... a `:metric` clause already has that stuff in it. You would probably just pass the Metric directly to `aggregate` to attach it to a query.

**Comment by camsaul** [comment]
Ok, so `display-name` works on both Metric metadatas and `:metric` MBQL clauses, not sure about `display-info` tho.
