### ISSUE TITLE
Error message about GA driver instead of CSV upload settings

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#31950]
(from Kyle)
Just tried going to the CSV upload settings on stats and got this fun message.

![image](https://github.com/metabase/metabase/assets/125455699/ec9f6d45-27d3-45b1-9d18-02acf43544db)

[Slack Message](https://metaboat.slack.com/archives/C04S696LRUM/p1687457373030259?thread_ts=1687457373.030259&cid=C04S696LRUM)

**Comment by iethree** [comment]
`/api/database` is broke

![Screen Shot 2023-06-28 at 8 52 40 AM](https://github.com/metabase/metabase/assets/30528226/97ab2b68-5fba-4530-80bb-375a0420d723)

**Comment by john-metabase** [comment]
Yeah, this is definitely because the `:googleanalytics` driver is gone, but a `:googleanalytics` DB is still there. Removing that DB should clear it up, so I'm just looking for approval on the actual instance. We may need some additional upgrade logic or at least a note. The driver is long deprecated and there has been a lot of warning so far, at least.

**Comment by john-metabase** [comment]
I'm going to try to make this work without removing the DB first, per @camsaul's suggestion of just handling this error gracefully where it is occurring.

**Comment by john-metabase** [comment]
Update: making the UI handle this gracefully is possible, but the scope is not very well defined. Handling a connection with a missing driver would involve changes to the whole stack, and could be done at at some point, but it would be better to avoid this. A missing driver is a pretty big problem for a lot of areas of code, and it may even be appropriate to refuse to start in such a case.

**Comment by john-metabase** [comment]
Closing this for now since this issue won't happen after restoring the `:googleanalytics` driver. We can decide if we need to do more work handling missing drivers later. The Google service itself is now in EOL and is read-only, and we should see customers move off of these connections as they migrate their data out. We should reach out to those cloud users who are still using the driver in a few months.
