### ISSUE TITLE
Numbers aren't formatted in table visualizations of SQL queries?

### ISSUE THREAD

**Issue by federicokeen** [metabase/metabase#3201]
-  I am using the Chrome Version 52.0.2743.116 (64-bit) browser.
-  My computer's OS is MacOS 10.11.6 (15G31).
-  I'm running Metabase ubuntu server and locally. and it is using the H2 (default)] database.
-  My data is in split between two DBs, one in MySQL and one in Postrgres
-  My Metabase version is v0.19.3.

When using Query Builder and Table as a viewing option, number columns are formatted using decimal separators. When using SQL cards, this doesn't happen.

**Comment by camsaul** [comment]
@federicokeen what types are the numbers in your database? `INTEGER`?

**Comment by federicokeen** [comment]
In the case I'm looking at, its actually a row count from the query builder, which in SQL is translated to count(*) AS `count`

**Comment by camsaul** [comment]
@federicokeen is talking about this:

![screen shot 2016-08-15 at 5 14 42 pm](https://cloud.githubusercontent.com/assets/1455846/17683902/d165d79a-630b-11e6-8a73-23c87ffe2af7.png)


This is a localization issue. I will just quote [Oracle's explanation of the issue here](http://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html) so I don't have to do words.

> Great Britain and the United States are two of the few places in the world that use a period to indicate the decimal place. Many other countries use a comma instead. The decimal separator is also called the radix character. Likewise, while the U.K. and U.S. use a comma to separate groups of thousands, many other countries use a period instead, and some countries separate thousands groups with a thin space. Table 1-3 shows some commonly used numeric formats.

In terms of making this an actionable issue I we should consider how to support different number formatting styles for our international audience; that might mean something like adding a new setting in admin (perhaps auto-magically determined based on the system locale) or sniffing the user-agent string in the browser and formatting numbers as appropriate in the frontend. 

Thoughts, @metabase/core-developers ?

**Comment by mazameli** [comment]
This is available as of 0.19 as a scalar visualization option:

![screen shot 2016-08-15 at 5 21 49 pm](https://cloud.githubusercontent.com/assets/2223916/17684026/dc81eec4-630c-11e6-8bbc-44df3bbb3207.png)

It's accessed by clicking the gear icon next to the visualization dropdown. Could be it's not obvious enough. It also doesn't solve the larger problem, which is that a user very likely would want their numbers to be formatted in a particular way throughout the app, not just for a given scalar.

**Comment by federicokeen** [comment]
It works for me if the visualization option is a number btw. 

**Working for Numbers with Query Builder:**
<img width="1376" alt="screen shot 2016-08-16 at 1 24 47 am" src="https://cloud.githubusercontent.com/assets/2558719/17684093/8cf9356c-6350-11e6-8671-d233893c6334.png">

**Working for Numbers with SQL:**
<img width="1418" alt="screen shot 2016-08-16 at 1 27 51 am" src="https://cloud.githubusercontent.com/assets/2558719/17684112/bc631034-6350-11e6-9425-e7a173cba44c.png">

**Working for Table with Query Builder:**
<img width="1377" alt="screen shot 2016-08-16 at 1 26 20 am" src="https://cloud.githubusercontent.com/assets/2558719/17684118/ce4741d0-6350-11e6-88a6-3668110a7aa3.png">

**NOT Working for Table with SQL:**
<img width="1381" alt="screen shot 2016-08-16 at 1 26 41 am" src="https://cloud.githubusercontent.com/assets/2558719/17684122/dc9e3d74-6350-11e6-9f51-67ac1bd17a5e.png">

**Comment by mazameli** [comment]
Ah, so this is both about i18n, but it's also a bug: table view for SQL queries doesn't have _any_ kind of number formatting (Or rather, the formatting it uses is no commas for thousandth places, but periods for decimal place. Expected default is commas and periods). I'm able to reproduce:

No commas:
![screen shot 2016-08-16 at 10 07 24 am](https://cloud.githubusercontent.com/assets/2223916/17708341/6ba7592c-6399-11e6-9a92-d7280afb86f9.png)

But periods work:
![screen shot 2016-08-16 at 10 09 39 am](https://cloud.githubusercontent.com/assets/2223916/17708394/a15e869e-6399-11e6-9c4a-b8eb1f1905b6.png)

**Comment by federicokeen** [comment]
Yes seems like a bug in table view for SQL queries

**Comment by tlrobinson** [comment]
Actually, this is (sort of) intentional behavior. We put in logic to prevent formatting non-"number" numeric values (such as zip codes and IDs) with comma separators, and SQL queries aren't able to give us the metadata about columns, so we default to not formatting with commas.

At one point we talked about allowing you to provide metadata for SQL query result columns. Alternatively we could blacklist types which shouldn't be formatted, rather than whitelist those that should.

We should also be more consistent. The Number visualization formatting code diverged a bit when we added chart settings.

**Comment by federicokeen** [comment]
I see, thanks for the update. Blacklisting fields that should not be formatted sound good to me

**Comment by mazameli** [comment]
This was fixed in https://github.com/metabase/metabase/pull/8479 and https://github.com/metabase/metabase/pull/8620 

![screen shot 2018-10-10 at 12 14 27 pm](https://user-images.githubusercontent.com/2223916/46760168-2a2bd600-cc86-11e8-859b-6073994ca3ca.png)
