### ISSUE TITLE
Restore googleanalytics driver

### ISSUE THREAD

**Issue by john-metabase** [metabase/metabase#32096]
Tracking revert of #31410 for logistical reasons, for now.

The driver will eventually be removed again. Google have announced the EOL for read access as July 1, 2024.

**Comment by bshepherdson** [comment]
Adding some more context here, since it's mainly confined to Slack threads:

Google had originally announced that GA3 would be read-only as of July 1 2023, and that deadline has passed. Since the GA driver has been obsolete for a while and deprecated since 45, it was removed in time for 47. However, for users with existing connections to GA there were issues in the UI. CSV uploads failed for such users and they couldn't even load the settings for the GA connection in order to delete it.

More recently, while Google was planning to end read-only access within a few months and turn down GA3 altogether, they have adjusted the date for that to July 1 2024. So we are keeping the driver for now, at least until 48, so we have time to make sure there are no issues caused by the remains of old GA connections.

[Slack thread with more details](https://metaboat.slack.com/archives/C010ZSXQY87/p1687973862806419)
