### ISSUE TITLE
Smoother transitions for charts when the window is resized.

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3227]
I think it would make visualizations feel a bit less jarring if we added in transitions for the height, width, and position of our bars, lines, pies, etc. so that we a user resizes their browser window there isn't that funky popping-into-place effect that we currently have. 

Here's the current behavior that's bugging me:
[chart resizing.zip](https://github.com/metabase/metabase/files/423741/chart.resizing.zip)

**Comment by kdoh** [comment]
Yeah it'd be great if we could smoothly transition charts in the QB as the browser resizes. This isn't a CSS thing specifically and is more of a function of the fact that currently in order to properly draw the charts and axes we need to grab the avaliable size of the parent element. It does seem like the redraw is taking a hilariously long time in the screencast you linked to.

I'm gonna update the title and labels to reflect the desire for smoother transitions.

**Comment by mazameli** [comment]
These transitions seem to be drastically improved these days. Not sure what did the trick, but I'm going to close this as fixed.
