### ISSUE TITLE
Visualization on grouped data breaks after a breakout and adding a second grouping category

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#32370]
### Describe the bug

Breaking out on a grouped data series, removing the filter applied by the break-out step, and re-adding it as a second grouping category breaks the visualization temporarily. The visualization is fixed as soon as the question is saved.

### To Reproduce

1. Browse data >> Sample Database >> Invoices
2. In Summarize, group by Date Received (by month)
3. In the chart click on a data point, and select Break out by a Category
4. Select Invoice.Plan for the category (--> a correct chart is displayed)
5. Remove the filter for Date Received that was added in the break out step
6. In Summarize add back Date Received (by month) as a second grouping category
--> this results in an incorrect chart: only one series displayed and the legend shows the same color and name for the Plan category.
7. Save the question
--> the chart is updated and has the correct contents

### Expected behavior

Expected: in step 6 we get a correct chart even before saving the question

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-14",
      "tag": "v1.46.5",
      "branch": "release-x.46.x",
      "hash": "272e3e6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

Incorrect chart:
![step6_incorrect_chart](https://github.com/metabase/metabase/assets/11080638/fc2055bd-ba95-45ab-91aa-5cb6f3a75681)

Correct chart after saving the question:
![step7_correct_chart](https://github.com/metabase/metabase/assets/11080638/d0694c66-91ed-48e8-82fa-9f5703307cea)

Similar sequences of steps to reproduce the problem on the same table:
- Summarize by Count, group by Plan
- Break out on a category: Expected Invoice
- Add Plan as a second grouping category
- Remove the filter on Plan
</br>

- Summarize by Count, group by Plan
- Break out on a category: Expected Invoice
- Remove the filter on Plan
- Add Plan as a second grouping category

**Comment by darksciencebase** [comment]
Is the behavior the same on `master`?

**Comment by zbodi74** [comment]
Yes, it is reproducible on `master` (54109ee).

**Comment by kulyk** [comment]
Seems to be a visualization settings issue. We seem to have a correct series up until we build an "ordered series" in `LineAreaBarChart` right [here](https://github.com/metabase/metabase/blob/c64c7cc9397f759ab95f74217487da85e3fe5bcd/frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx#L269). I noticed that the [`getOrderedSeries` function from `metabase/visualizations/lib/series`](https://github.com/metabase/metabase/blob/c64c7cc9397f759ab95f74217487da85e3fe5bcd/frontend/src/metabase/visualizations/lib/series.ts#L19) behaves differently before/after saving a question (7th repro step). Specifically, a "key" we're using to get a series object [here](https://github.com/metabase/metabase/blob/c64c7cc9397f759ab95f74217487da85e3fe5bcd/frontend/src/metabase/visualizations/lib/series.ts#L34) is "Basic", "Premium", "Business" _after_ a question is saved, but "count", "count", "count" _before_ it's saved. That makes me think we might be getting a single series object three times because the look up key is the same

**Comment by JesseSDevaney** [comment]
Could not reproduce:


https://github.com/metabase/metabase/assets/22608765/20ec5324-5a9c-4196-b5ac-7229eb20daff
