### ISSUE TITLE
Unable to add joined columns in table settings after removing through notebook editor on nested Question

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#32373]
### Describe the bug

- After hiding/removing columns in the question notebook editor on a question using a model or saved question as a data source, no longer able to add them back with ➕ in the table settings.
- Getting browser console log error `missing join? n n`

### To Reproduce

1. Create and save a question using Sample Data > Orders with a left join to to Sample Data > People on Orders.user_id = People.id as Question A
2. Create a new Question (Question B) using Question A as the data source
3. Hide a few columns using the Question Notebook editor and click Visualize
<img width="618" alt="image" src="https://github.com/metabase/metabase/assets/8808703/703fdb8d-eef5-4890-ba2c-ab888a6ad192"> 

4. Click the Table settings ⚙️ gear icon and try to add the columns back
5. See error (columns are not added back, and browser console has errors) and all columns show as addable (show up under "Add columns" in table settings) even when the are already added.

6. In `master`, visiting the Notebook editor shows all options unchecked at this point:
<img width="394" alt="image" src="https://github.com/metabase/metabase/assets/8808703/e7c42516-1896-4f19-ad6b-d8e7d7a26525">

### Expected behavior

- Should be able to hide/remove and add columns from Question notebook editor and table settings

### Logs

<img width="952" alt="image" src="https://github.com/metabase/metabase/assets/8808703/946019e0-3410-4117-94cf-2dcee5379487">

### Information about your Metabase installation

```JSON
- Metabase v1.46.6 and `master` as of `7dc11856`
```

### Severity

P1: Unable to use common functionality (adding and removing columns in table visualization after joining data)

### Additional context

- Related to
  - https://github.com/metabase/metabase/issues/30546
  - https://github.com/metabase/metabase/issues/31321

**Comment by ranquild** [comment]
Broken by https://github.com/metabase/metabase/pull/24817, exactly by these 2 lines https://github.com/metabase/metabase/pull/24817/files#diff-c4c21b81c632fbe5182c50d342a80a6a7b2e89027f659a3211316dae6cfffa3fR248

The difference is that columns from the nested question have `join-alias` set in `field_ref`. Before the PR `field.dimension()` and `dimension.mbql()` would return field references without `join-alias` because we ignored `field_ref` and used the field id directly. After the PR `join-alias` is preserved, which triggers this check when adding a new column https://github.com/metabase/metabase/blob/f37183e919a3c41ea0e05dabfe46eacee56dc71a/frontend/src/metabase/lib/dataset.js#L152. It tries to find the corresponding join clause and fails, resulting in the column not being added.

**Comment by likeshumidity** [comment]
Still exists in x.47.4

**Comment by darksciencebase** [comment]
#33977 never got backported. [slack thread](https://metaboat.slack.com/archives/C04DN5VRQM6/p1697788576907939)

**Comment by darksciencebase** [comment]
the effort and risk of backporting has been deemed too high. this will go out with 48.
