### ISSUE TITLE
[MLv2] [Bug] Join `fields` generate unexpected field references

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32437]
When selecting just a few columns from a join RHS table, MLv2 produces field references that can't be processed by the BE. For example, if we join the sample Orders table with the Products table, and only pick Products' ID and Title columns, here's how joins will look in MLv1 and MLv2:

### MLv1

```js
{
  alias: "Products",
  "source-table": 1,
  condition: [ ... ],
  fields: [
    ["field", 5, { "join-alias": "Products" } ],
    ["field", 1, { "join-alias": "Products" } ],
  ]
}
```

### MLv2

```js
{
  alias: "Products",
  "source-table": 1,
  condition: [ ... ],
  fields: [
    ["field", 5, { "base-type": "type/BigInteger" } ],
    ["field", 12, { "base-type": "type/Text" } ],
  ]
}
```

Notice the `join-alias` option is missing in MLv2, but has `base-type` options

As a result, the BE returns an error when trying to run a query with MLv2 join:

```
Cannot determine the source table or query for Field clause [:field 5 {:base-type :type/BigInteger}]
```

**Comment by camsaul** [comment]
Maybe a regression of #28724

**Comment by camsaul** [comment]
`join-condition-rhs-columns` can't return columns with the join alias because we might not one yet, because we could be in the process of constructing a join still... I think it's better if we have `with-join-condition` just make sure the RHS of all the join condition(s) includes the join alias if it's a field reference
