### ISSUE TITLE
Aggregation Parameter at the Dashboard Filter Level

### ISSUE THREAD

**Issue by pjutard** [metabase/metabase#3244]
Periscopedata has a great feature where on each Dashboard you can pick not only the date range but the aggregation interval (day, week, month, quarter):

![image](https://cloud.githubusercontent.com/assets/1218897/17822580/585b7b0e-662e-11e6-9c0f-a6179e8dd121.png)

Is there any way of accomplishing this in Metabase?

**Comment by moumny** [comment]
Linked to #3207  and few other issues. It seems all related to having a special way to filter and group by on timestamp for timeseries data.
It definitely makes sense since Metabase is aimed at users that do not need to know SQL. Asking our users to add a filer and make a group by is too complicated for them.

**Comment by flamber** [comment]
Closing in favor of #6583
