### ISSUE TITLE
Feature request: Sum/multiply/divide different Questions

### ISSUE THREAD

**Issue by tmattimore** [metabase/metabase#3251]
Feature Request:
Would be awesome if I could set up cards on a dashboard that were a sum/product/quotient of multiple questions. This would work well for queries/questions that respond with a number or a table/line graph/etc.

Realize this is possible to do with writing my own query (select statement + select statement), but ideally want to do it all within Metabase UI.

Thanks!

**Comment by MixMe** [comment]
Yes that would be great !!!

**Comment by mknippen** [comment]
+1

**Comment by afuggini** [comment]
@tmattimore how did you achieve this writing your own query? Is it in MongoDB?
Otherwise does anyone know if this is possible in MongoDB with queries?

**Comment by prigal** [comment]
This would be awesome to get "real" conversion rate from sessions in google analytics and orders from our ecommerce database.

**Comment by beyerz** [comment]
I know this is quite old, and I haven't yet found a solution other than using a direct query as stated previously to make this work.

What I would like to be able to do is to multiply (as this already exists) the result of a "question" by the result of another "question".

The ability to do this has two use cases for me.
1. Using different data sources, I can now combine results. This is most relevant when I don't own the data source, such as google analytics, but want to take results from one data source to enrich the results of another data source.
2. This will allow me to present conversion ratios and goal rates based on generic questions that can be reused throughout my system.

**Comment by salsakran** [comment]
you can now do this in the notebook mode of the query builder via a join + calculated columns. We'll probably find ways to make it simpler, but for now it's at least possible.

**Comment by tmattimore** [comment]
thanks for following up @salsakran !

**Comment by denisesenguel** [comment]
@salsakran is there any plan on making this possible for non-sql Databases? We use Druid for the most part so joining is not an option for us. neither is questions based on questions. all we need is being able to divide aggregate numbers from two different datasources to get conversion rates! very similar to what a 100% stacked barchart from two combined questions already does in a dashboard, but with one of the series being the 100% rather than the combination of both. This is getting extremely critical for us, as we are able to find a feasible workaround in many cases :(
