### ISSUE TITLE
Modifying an underlying question model leaves invalid dashboard parameters and breaks cards

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32573]
### Describe the bug

When a dashboard filter is connected to a model field that was removed it crashes the dashboard card.
We may want to remove invalid filters when models are being updated.

### To Reproduce

- Sample Dataset -> Orders -> Save as a model M1
- Create Q1 from M1 
- Add Q1 on a dashboard D1
- Add an ID filter, connect it to Q1: Orders.Id and set any default value
- Edit model definition of M1 and in the notebook editor simply remove Id column from it
- Go to the D1 dashboard, ensure the chart is broken

### Expected behavior

Cards should work

### Logs

Above

### Information about your Metabase installation

```JSON
master
```

### Severity

P1ish?

### Additional context

NA

**Comment by NevRA** [comment]
@darksciencebase @alxnddr will assign to PP because it looks like in the viz scope: `visualizations/Scalar/Scalar.jsx`. Please reassign if i'm wrong

**Comment by luizarakaki** [comment]
We can't simply remove the filter assingment because this could lead to data leaks. Filters are used to control data access, especially in static embedding.

In this case, we should show a better error message:
`A dashboard field is assigned to a column that doesn't exist anymore, assign the filter to another field or remove it`
