### ISSUE TITLE
Data Model page makes 60+ API calls, 40 of which are duplicates; crashing servers due to overload

### ISSUE THREAD

**Issue by DannyDouglass** [metabase/metabase#3276]
*  I am using Chrome 52
*  My computer's OS is Mac OS X 10.11.4
*  I'm running Metabase on Heroku and it is using the Hobby Basic Postgres DB.
*  My data is in a Postgres database
*  My Metabase version is 0.19.3 (latest per the app)

When I click on `Data Model` in `Site Administration` in an attempt to create segments, I get a blank page:

![image](https://cloud.githubusercontent.com/assets/266481/18032456/0dd6600c-6cba-11e6-9bea-d9bfd6d4f6fd.png)

I've setup a few dashboards, a handful of cards, integrated SSO, added a Pulse, and upgraded my PG add-on. I'm also running as a 2X dyno in Heroku. This appears to be the only area not functioning.

Would love some insight on how to get past this issue.

**Comment by camsaul** [comment]
I think I've figured out the problem here. It looks like there are some bugs in the data loading logic for the page that cause it to put such a heavy load on the server it probably overloads it, which would explain the 503 (Service Unavailable). @DannyDouglass I'll add these bugs to the Milestone for the next release and we can address them before it goes out.

First, it looks like the page makes about **60 API calls** on my local machine 😱 :

![screen shot 2016-08-29 at 11 19 51 am](https://cloud.githubusercontent.com/assets/1455846/18062187/a4ede58e-6dda-11e6-94e3-4c466eb699d0.png)

20 of them alone are duplicate calls to `GET /api/table/11/query_metadata 200`. 🙀  Furthermore`GET /api/database/:id/metadata` should be returning everything we need for this page so all of the subsequent calls are probably unnecessary.

Second, it looks like the call to `GET /api/database/2/metadata` is making a **few hundred DB calls**, which is definitely some sort of N+1 problem in the API endpoint itself.

**Comment by camsaul** [comment]
I've opened #3278 to address the N+1 problem with `GET /api/database/:id/metadata`; we can keep this one to look at the issue of the unnecessary / duplicate API calls in the Data Model page. 

This issue looks similar to #1726 (a similar issue we previously fixed in the Query Builder).

**Comment by DannyDouglass** [comment]
yikes!! 😱  thanks for the quick response / triaging.

**Comment by salsakran** [comment]
closed in #3485

**Comment by DannyDouglass** [comment]
awesome work - thanks all!! is there a timeline for the `0.20.0` release?

keep up the great work!
