### ISSUE TITLE
Split Setup process into two atomic stages

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#32768]
**Context**
The unauthenticated use of `/api/setup/validate/` was a bit of a problem recently. In theory the setup token is a credential, but given that recent history shows we might not always control it being leaked, we should add another layer of protection.

I think we should split the setup process into two api calls -
/api/setup/create_user, which creates the first admin user and the remainder into a separate api endpoint. `/api/setup/validate` can then require an admin account to access just like in the normal app.

Downside - we'd need to figure out what to do with the setup equivalent of an abandoned cart, where a user is created but a database never added.

**Comment by camsaul** [comment]
I think this is all we need to do

1. Remove ability to create a database from `POST /api/setup`
2. Remove `POST /api/setup/validate` entirely
3. Update FE to use separate (authenticated) call `POST /api/database` to validate/create Database on launch 
4. Update FE so the admin details inputs are locked (uneditable) if you hit submit but run into Database errors, because the admin user will already have been created by then

**Comment by camsaul** [comment]
RE

> we'd need to figure out what to do with the setup equivalent of an abandoned cart, where a user is created but a database never added

we already show a little to-do checklist item for this, since you've always been able to skip adding a Database in the setup flow

**Comment by alxnddr** [comment]
## Current state

At the end of the setup wizard FE sends to `POST /api/setup` the following data:
- Admin user info
- Database connection info
- Settings
    - Instance name
    - Locale settings
    - Analytics tracking setting

An instance becomes activated because `has-user-setup` which checks [users count > 1] starts to return true.

## New state

We want to create a user on the second step of the setup which also includes setting the instance locale and the instance name. Users can refresh their page or abandon the process after this stage.

The previous `has-user-setup` has to be changed and the FE needs to explicitly complete the setup flow only after users go through all steps.

If we keep the existing UX more or less the same, the flow would be:

1) User selects a locale
2) User enters their name, email, password, and instance name
    - On the “Next” click FE needs to create a user, we need an endpoint `/api/setup/create_admin`. The endpoint also authenticates the user: creates a session and sets the cookie
    - Now, as an authenticated admin, FE updates locale and instance name settings through the existing endpoints
3) User optionally creates a DB connection, FE uses the existing database endpoint
4) User decides on the analytics settings, FE uses the existing settings endpoint
5) FE sets `has-user-setup` to `true` and the instance becomes active

### Possible differences with the previous flow

#### Returning to abandoned setup process

Before: 
Reloading page restarted the entire setup.

After:
If users abandon setup after the second stage, they will need to login to the app in order to proceed with the setup.

#### Ability to return to previous steps and change data

Before: 
Free to do, no data is saved until the finish.

After:
After the second step, since the user is already created, we cannot allow users just type their new password twice and update it. The existing endpoint for changing the password requires entering the previous one for security reasons. However, changing first/last name or the instance id can and should be done without asking for a password. UX-wise it is slightly obscure to have a form where some fields can be updated right away but one, the password field, requires adding and filling another input for the old password.

**A possible simplification is to disable going to the previously filled steps at all.** 

@luizarakaki @dhuniverse please let me know what do you think about this.

### BE changes

#### Removed endpoints
- `POST /api/setup/validate`
- `POST /api/setup`

#### New endpoints
`POST /api/setup/create_admin` with the following body:
```
{
    "email": string,
    "first_name": string,
    "last_name": string,
    "password": string,
    "password_confirm": string
}
```

It should fail if an instance has one or more users.

#### Allow setting `has-user-setup` by admins

It becomes a regular setting with `false` as the initial value. 

@camsaul how does this look to you?

**Comment by luizarakaki** [comment]
@alxnddr discussed with the product team [here](https://metaboat.slack.com/archives/C01MS7DQKR6/p1692298531163689) and it is fine to disable going back to previously concluded steps.

**Comment by camsaul** [comment]
Why don't we just leave `POST /api/setup`, but remove the ability for it to create a Database (basically take out the chunk of code that deals with the database parameters). No need to rename the endpoint too, that's just making more work for us. It already does the other stuff we want like creating and returning a Session.

Yes, we should remove `POST /api/setup/validate`.

I don't really like making `has-user-setup` something that is set by the FE. I'd rather have it be purely calculated, where no users means it's false and 1 or more users means its true.

I think if someone creates a User and then exists the flow (refreshes the page or something like that), it's fine to just take them to the home page at that point. The "finish setting up your instance" admin checklist will remind people to add a Database in that case, and they can disable anonymous stats from the admin panel; the only thing they'd be missing out on I guess it signing up for the mailing list, but they can always do that from metabase.com.

**Comment by camsaul** [comment]
That's just my two cents, I don't think we need to make an easy fix into a complicated one by having special "abandoned cart" behavior, but it's ultimately product's call.

If we absolutely have to redirect you back to the setup flow so you can sign up for the mailing list, then I guess your proposal is ok with me, other than what I said about keeping `POST /api/setup`, that still stands. I can't see a good reason to rename that endpoint.
