### ISSUE TITLE
Frontend breaking when selecting another group by

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32948]
### Describe the bug

Can't reproduce from scratch but, there's an issue on question 12740 on our internal instance where the frontend breaks when selecting a field to group by in the joined question
[Screencast from 08-04-2023 10:38:43 AM.webm](https://github.com/metabase/metabase/assets/1711649/20c28e30-3606-4ef6-80f5-95c5e9f6a7a1)
```
Error: No matching clause: dispatch-type/map at R.s4
```

### To Reproduce

Go to question 12740, notebook
then add a group by from the joined question

see the error

### Expected behavior

Frontend should not break

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by kulyk** [comment]
Seems like a BE issue similar to what we have on MLv2 joins feature branch.

It seems like the MLv2 metadata code expects `GET /api/card/:id` request to happen for each card object in a query (e.g. source card, joined card). But the FE would only send it for the source card; for joined cards, the FE would send a `GET /api/table/card__<id>/query_metadata` request. I believe the fix should rework this part of the code not to rely on data coming from `/api/card` — `query_metadata` should have everything needed

**Comment by kulyk** [comment]
Steps to reproduce on `master` using the sample data:

**Preparation**

1. New > Model > Raw Data > Sample Database > Accounts > Save
2. New > Model > Raw Data > Sample Database > Feedback > Save

**Via joins**

1. Open a new Metabase tab (at the homepage)
2. New > Question > Models > Accounts
3. Try to join the Feedbacks model (not the raw table) on Accounts.EMAIL = Feedbacks.EMAIL
4. FE crashes when selecting the Feedbacks.EMAIL column as the join condition RHS column

**Via breakouts**

1. Open a new Metabase tab (at the homepage)
2. Open the Accounts model page from search or from a collections page
3. Open the Feedbacks model page from search or from a collections page
4. New > Question > Models > Accounts
5. Join the Feedbacks model (not the raw table) on Accounts.EMAIL = Feedbacks.EMAIL (it's going to work because metadata has `GET /api/card/:id` data)
6. Save a question
7. Reload the page
8. Aggregate by whatever
9. Breakout by any column from the RHS card
10. FE crashes when selecting any RHS card column

**Comment by darksciencebase** [comment]
I tried to reproduce this on 47 RC3 to decide whether this is a blocker or not. The steps via joins did not crash the FE
![image](https://github.com/metabase/metabase/assets/125455699/df79ad64-2783-4078-b144-6ba1ddca46f5)

**Comment by kulyk** [comment]
@darksciencebase oh, I think there's a missing step for `master`. You should get a crash if you add another clause using a column from the joined model/question (a breakout or a sort for example)

**Comment by darksciencebase** [comment]
thanks @kulyk, indeed. i've been able to reproduce via the joins route by adding a sort clause. on both `master` and the RC3 jar. so, a blocker for the release after all
