### ISSUE TITLE
e.some is not a function breaks the FE on the filter modal

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32985]
### Describe the bug

1) New question->Go to hosting insights->select the "pulses" table->filter modal
2) instance dns -> search for one, type a few chars --> hit the error

same as always
![image](https://github.com/metabase/metabase/assets/1711649/ed1e527b-13f9-413b-8c90-4a243fa9f08a)

### To Reproduce

Above

### Expected behavior

We shouldn't break the FE

### Information about your Metabase installation

```JSON
master
```

### Severity

P1

**Comment by paoliniluis** [comment]
EDIT: it won't work if you go to the notebook as well...

**Comment by iethree** [comment]
not limited to the filter modal, also occurs in the column field filters.

https://metaboat.slack.com/archives/C505ZNNH4/p1691433488598059?thread_ts=1691429382.920669&cid=C505ZNNH4

possible race condition with field values fetching that swaps out the state of the options such that `option` is momentarily undefined. might be hard to repro locally, probably manifests on stats due to some combination of request latency and a large set of field values.

![Screen Shot 2023-08-07 at 12 41 27 PM](https://github.com/metabase/metabase/assets/30528226/313a3690-d3f0-482d-969f-94198eb8d937)

**Comment by qnkhuat** [comment]
Steps to reproduce locally:

1. Admin -> Table Metadata -> Sample Dataset -> Accounts -> Email -> Change Field Type to Entity Key
2. Feedback -> Email -> Gear Icon -> Change Field Type to FK and link to Account.Email
3. Also change the "Filtering on this field" to Search Box
4. New question -> Feedback -> Filter by Email column
5. Type in anything and you will see the error page

**Comment by NevRA** [comment]
Never work before, context: https://metaboat.slack.com/archives/C505ZNNH4/p1691429382920669

**Comment by iethree** [comment]
Downgrading to P2 because this no longer crashes anything, it just has empty field values results.
