### ISSUE TITLE
When moving a collection do not suggest its children as a target

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#33026]
### Describe the bug

When moving a collection do not suggest its children as a target.

### To Reproduce

1. Create a Parent collection
2. Create a nested Child collection within the Parent
3. Go to the Parent and try to move it to the Child collection
4. The UI does not filter out Parent and all its subchildren so when you try to do so it just does not work

### Expected behavior

When moving a collection filter out itself from the target selector

### Information about your Metabase installation

```JSON
Latest master
```

### Severity

Cosmetic bug

**Comment by SauravChanda** [comment]
Can someone review my PR #34290 , I am trying to write tests for this change, but `yarn test-cypress-run` keeps failing for me, without even adding any tests.

**Comment by rafpaf** [comment]
Can reproduce. The backend throws:

```
 :cause "You cannot move a Collection into itself or into one of its descendants.",
 :message "You cannot move a Collection into itself or into one of its descendants."}
```

There is no indication in the frontend that an error has occurred. Simply, nothing happens.

Desired behavior:
* When moving the collection, the UI should show that an error has occurred.
* The UI should prevent the user from moving a parent to its children in the first place.

Note that currently it is impossible to move a collection onto **itself**, and the UI indicates this by disabling the 'Move' button.

Perhaps an analogous UI behavior could be used to indicate that it's impossible to move a collection into one of its own descendants.

Or it may be better to gray out the parent collection in the list, so that its descendants cannot even be found through the 'Move' dialog.

**Comment by rafpaf** [comment]
This could be a good early bug for @rafpaf to work on, fwiw.

**Comment by iethree** [comment]
duplicate https://github.com/metabase/metabase/issues/21786
