### ISSUE TITLE
Add missing translations

### ISSUE THREAD

**Issue by nomorethat** [metabase/metabase#33046]
### Describe the bug

Hi! We often find a missing translation on the metabase pages. With a deeper investigation of the problem, we learn that this is due to the fact that not everywhere the text is wrapped in t`...` (ttag).

My team and I have collected several such places and will make a pull request to help you fix it =)

Best regards ;)

Thanks for your work =)

### To Reproduce

-

### Expected behavior

-

### Logs

-

### Information about your Metabase installation

```JSON
-
```

### Severity

-

### Additional context

We will create a pull request and post the link in the comments

**Comment by paoliniluis** [comment]
probably similar to https://github.com/metabase/metabase/issues/13002, https://github.com/metabase/metabase/issues/27350 and https://github.com/metabase/metabase/issues/25485 ?

**Comment by paoliniluis** [comment]
@nomorethat why? you should be able to create a PR by creating a fork and then doing the PR against the upstream

**Comment by nomorethat** [comment]
I also made changes to the PoEditor for the location "ru" (native speaker)

**Comment by WiNloSt** [comment]
Hi @nomorethat, first of all, thank you for your PR contribution! Though our timing is a bit unfortunate. We've worked on the same fix at the same time and we've ensured our fix adds all visible missing translations you reported.

Thank you for being vigilant.

This issue is now closed by https://github.com/metabase/metabase/pull/33123.

**Comment by nomorethat** [comment]
@WiNloSt Thank you very much! =) Good job =)
