### ISSUE TITLE
Including new JDBC jars in uberjar?

### ISSUE THREAD

**Issue by erp12** [metabase/metabase#3306]
Me again! Still working on the Vertica driver.

I have made a `vertica.clj` file that does the stuff listed on [this wiki page](https://github.com/metabase/metabase/wiki/Writing-A-Driver) and made a JDBC vertica spec in `metabase.db.spec`. 

I have a Vertica jdbc jar that I can use to connect to Vertica databases in other jdbc environments, and I need to point metabase to it. (more specifically, I need to point clojure.java.jdbc to it, right?)

I tried to find out where the postgres jdbc jar lives. I built the `metabase.jar` uberjar (using ./bin/build) and ran a `jar -tf target/uberjar/metabase.jar | grep "postgres"`.

Sure enough, I saw a bunch of lines starting with `org/postgresql/jdbc4/...`. So I assume that the postgres jdbc driver is packaged with the uber jar. Then I tried to figure out how to include my Vertica jdbc jar in the `metabase.jar` uber jar. 

Searching through the repo, it seemed like adding a `plugins` folder in the same spot as `metabase.jar` with the vertica jdbc jar in it *might* do the trick. I tried that, and then re-built the uberjar. The `plugins` folder disappeared with the vertical jdbc jar in it and `jar -tf target/uberjar/metabase.jar | grep "vertica"` did not yeild anything relating to jdbc.

I feel as though I might be missing something obvious. The metabase uberjar build process is a mystery to me, and I was hoping that there would be some documentation I overlooked on adding new jdbc jars. Any help is much appreciated. Thanks!

**Comment by camsaul** [comment]
The plugins folder doesn't pull in things from the `plugins/` directory. Is the Vertica JDBC driver you're trying to include redistributable? If so, just include dependency information for it in `project.clj`. Otherwise you can use a Lein plugin like [`lein-localrepo`](https://github.com/kumarshantanu/lein-localrepo) to install it as a virtual local dependency.

Either way, you shouldn't be worried about building the uberjar at this point in the development cycle. You should use `lein ring server` while you're working on development because it takes care of things like hot reloading namespaces when files change. With an uberjar, you need to recompile everything and restart the server every time you make a change.

**Comment by erp12** [comment]
Thanks for the very helpful response. I am not sure if the jar I am using is redistributable, but I thought I would post my solution in case it is helpful to anyone:

1. First I created a [local maven repository](https://maven.apache.org/guides/introduction/introduction-to-repositories.html) in the `metabase` project folder. I called mine `local_jar_dependencies`.
2. Then I added my jar to the maven repository. In my case (OSX) I ran this command outside the maven repo folder:
```
mvn install:install-file \
    -Dfile=vertica-jdbc-7.2.2-0.jar \
    -DgroupId=self \
    -DartifactId=vertica-jdbc \
    -Dversion=7.7.2 \
    -Dpackaging=jar \
    -DgeneratePom=true \
    -DcreateChecksum=true\
    -DlocalRepositoryPath=local_jar_dependencies
```
3. In my `project.clj` I added the following line to the `:repositories` vector:
```
["local" ~(str (.toURI (java.io.File. "local_jar_dependencies")))]
```
4. call `lein deps` and you are good to go!

I don't think this will be acceptable in a PR, but it was very easy to setup and use for developing. I will revisit this later, once I have finished the driver.

**Comment by camsaul** [comment]
Hi @erp12, I the [`lein-localrepo`](https://github.com/kumarshantanu/lein-localrepo) plugin I mentioned above takes care of all those steps for you.

Either way, you shouldn't need either approach since Metabase will automatically add any JARs it finds in `plugins/` to the classpath when it launches. All you should need to do is copy the JAR to `plugins/` and then check to see if classes it defines exist, the same way the Oracle driver does.

**Comment by erp12** [comment]
Hi camsaul. I think what confused me about the way the Oracle driver works is this:

>"By default, the plugins directory is called plugins, and lives in the same directory as the Metabase JAR."

I initially thought this meant the uberjar, which is also called `matabase.jar` but you seemed to indicate that was incorrect.

In my metabase project folder (aka top level folder of our fork) I don't see a `metabase.jar` file, nor do I see one anywhere in the project. Could this be slightly different depending on OS? I am on OSX.

Being unsure of what I was missing regarding the `plugins` folder, I went with a local maven repo. Perhaps I should give the `lein-localrepo` a try! Thanks.

**Comment by camsaul** [comment]
If you're running via `lein ring server` then `plugins` should go in the project root, the same directory `project.clj` is in.

**Comment by camsaul** [comment]
I'll update the Driver wiki to clarify this 👍

**Comment by erp12** [comment]
Thanks!
