### ISSUE TITLE
Version the uploaded CSV tables

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33272]
### Describe the bug

As we don't delete the tables when we delete the models (https://github.com/metabase/metabase/issues/32566), a customer mentioned that they would like people to add a new version of the CSV when they want (just writing over the table)

### To Reproduce

1) upload a CSV file, then you would like to upload a new version of it
2) upload the same CSV file, it will be a new table

### Expected behavior

We should offer the possibility of versioning the uploaded models

### Information about your Metabase installation

```JSON
v47.x
```

**Comment by amosmills** [comment]
Yes - A lot of effort can go into creating dashboards and questions off this CSV upload, and if you have to recreate them all each time, I suspect this feature will go under-utilised.

**Comment by mootah01** [comment]
Having the CSV replace existing is really what we need. Perhaps versioned so that we get standard upload versioning... and you can choose to get the latest version, or versions by effective from/to dates

**Comment by coreyaus** [comment]
Hi team,

I'm scoping Metabase as a potential solution for a client and would need this functionality. It looks like it was closed in this epic: #38788, based on the release of this PR: #40363.

Are you please able to confirm whether this issue is indeed resolved, or if there's a reason it's still open?

For more info on my use case, it's essentially just that dashboards/graphs can be created from an uploaded CSV table, and that those visualizations can be updated with new data periodically by uploading a new version of the original CSV. It sounds like that should be possible, assuming this issue is now resolved?

Thanks for your help, and have a great day!

**Comment by luizarakaki** [comment]
Yes, it is possible to replace the existing data or append new data to CSV uploaded tables/models.
