### ISSUE TITLE
[MLv2] Fix `drill_thru` method to handle additional drill parameters

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#33480]
Calling `drill_thru` lib method throws an error in case any additional parameter has been passed, which most of drills require. Example - sort drill: `Error: No method in multimethod 'metabase.lib.drill-thru/drill-thru-method' for dispatch value: :drill-thru/sort`

You can use this unit test to reproduce - https://github.com/metabase/metabase/blob/mblib-drill-thru-fe/frontend/src/metabase-lib/drills.unit.spec.ts#L713

I did some investigation and it seems the root cause is that compiled Closure-to-JS code filters out additional function attributes.

**Comment by bshepherdson** [comment]
I'll make this the first task when I'm free to work on drills; probably still a day or two away.

It's possible that dynamic dispatch (`defmulti` and `defmethod` in Clojure) doesn't mix with variadic arguments, but I don't think that's the case.

I think the issue here is that there is no implementation of `drill-thru-method` for `:drill-thru/sort`. It should look like [this](https://github.com/metabase/metabase/blob/mblib-drill-thru/src/metabase/lib/drill_thru.cljc#L425) 
```clojure
(defmethod drill-thru-method :drill-thru/summarize-column
  [query stage-number {:keys [column] :as _drill-thru} aggregation & _]
  ...)
```
but with `:drill-thru/sort` of course -  there's no such implementation.

This is a known incompleteness - roughly 90% of the drills are implemented in `available-drill-thrus` and only maybe 40% have `drill-thru` implemented to actually apply the drill to the query.

If you want to test the whole workflow, try a drill that does have `drill-thru-method` implemented, perhaps:
- `quick-filter` (the `<`, `>`, `=`, etc. on specific scalar values like `subtotal`)
- `fk-filter` (click eg. a specific `User ID` on Orders to see all Orders from that user)
- `distribution` (click a numeric, temporal or geographic column header and `Distribution`)
- `summarize-column` (likewise, click `sum`, `avg`, or `count` )
