### ISSUE TITLE
Questions or dashboards with lots of metadata take a lot of time to dismiss the spinner

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33499]
### Describe the bug

Seems that if a query (many custom columns or joins) or dashboard (many questions or many filters) has lots of properties, it will take a lot of time to render.

E.g.: question 13003 in our internal instance
![big_question](https://github.com/metabase/metabase/assets/1711649/d8e1765f-c4d6-428e-9892-7cd33cd27e05)

We need to think a way of giving the user a faster response in those cases. Probably a sibling of https://github.com/metabase/metabase/issues/33220

### To Reproduce

1) Build a big question or dashboard, with lots of stuff
2) do a fresh request

### Expected behavior

We should make the UI smoother, spinner should appear the least amount of time as possible

### Logs

NA

### Information about your Metabase installation

```JSON
Since the beginning of the times. I guess that the spinner dismisses once all the endpoints finished loading, but in a question or dashboard you don't want to have everything loaded to interact
```

### Severity

P2

**Comment by paoliniluis** [comment]
Second example Dashboard 2116

**Comment by alxnddr** [comment]
I changed the label to the BE because frontend shows loader correctly since it waits for the response

**Comment by markbastian** [comment]
The slow endpoint is https://stats.metabase.com/api/dashboard/:dashboard-id.

Here's what I've been able to do to attempt to reproduce this issue so far:

* @paoliniluis referenced https://stats.metabase.com/dashboard/2117 as a similarly slow dashboard to load
* To try to reproduce this locally, I created a large dashboard (36 cards) with a variety of queries (nested, custom columns, multiple sources, native, visual)
* Made as many filters as I could think of, many with enumerated values
* The json output of the referenced slow response on stats is 13770 lines at 388639 bytes
* My local response body is 15032 lines of formatted json at 443866 bytes

My expected response time would be higher locally as the dashboard is larger.

Results:
* That stats board (baseline) takes 4.39s to load
* My attempted reproduction loads in under a second (297ms)
* Assuming a similar level of complexity, `master` is an order of magnitude faster to load

Here's a side by side view of the two scenarios. Note that the local dashboard (left side) loads much faster than the baseline. Also note that qualitatively, individual dashcard loading appears similar on both sides.

![slowdash1](https://github.com/metabase/metabase/assets/8381441/938c3368-a81a-4872-88af-f07abe9528f2)

After adding opentelemetry spans to the `metabase.api.dashboard/get-dashboard` endpoint, we get the following trace on the **local** setup:
<img width="1202" alt="image" src="https://github.com/metabase/metabase/assets/8381441/c91bece7-5fab-4d7b-9b6d-fe18ebdb958d">

They `hydrate` function takes almost 80% of the invocation. The next step is to close the gap between the baseline and local by either getting a better complicated case locally or instrumenting the baseline issue to see what's happening differently there.

**Comment by markbastian** [comment]
Viewing the logs on grafana shows that the delay appears to be in the audit code.
<img width="1616" alt="image" src="https://github.com/metabase/metabase/assets/8381441/10ff379e-7af8-4c1e-9e79-35f672ea9a8a">

After adding more instrumentation locally, it looks like the problem is in `publish-event!`
<img width="1272" alt="image" src="https://github.com/metabase/metabase/assets/8381441/802caa2c-60e6-46b5-a074-1f965bd80908">

We could merge this branch in to verify on stats, but I think that's the issue. It looks like https://github.com/metabase/metabase/pull/33392 made `publish-event!` synchronous rather than async. My current hypothesis is that's the issue. I think we want to make event publication async. Thoughts, @camsaul?

**Comment by camsaul** [comment]
I don't understand how you reached the conclusion that synchronous `publish-event!` is the problem here. Your screenshot shows `publish-event!` taking ~28ms while `get-dashboard` takes ~356ms.

**Comment by paoliniluis** [comment]
De-escalated

**Comment by markbastian** [comment]
Here's a more up-to-date trace. Looks like something's going on with `publish-event!`.
<img width="2115" alt="image" src="https://github.com/metabase/metabase/assets/8381441/5379f4e9-dce1-4a42-82fd-ed8c87163ea0">

**Comment by markbastian** [comment]
The issue has been discovered and fixed. We'll be doing a single cleanup PR on our instrumentation, but the issue is that massive objects were being logged using a very slow pretty printer. The logger shouldn't be printing these objects (we'll follow up on this), the amount of data written should be much smaller either way, and we should use a faster prettier. the first two have already been addressed.

Here's a trace and screen recording of the new behavior:
![image](https://github.com/metabase/metabase/assets/8381441/98e1d20c-964c-4f5f-a28c-37c13833d107)

![image](https://github.com/metabase/metabase/assets/8381441/7c1a7b73-a54d-4004-bbd4-91346efd08ee)

I also did a check on [question 13003](https://stats.metabase.com/question/13003-test-massive-custom-columns). The initial page load is now snappy. The actual processing of the data is slow due to all of the custom columns, but that is a different issue. @paoliniluis, if you have a separate ticket for that please LMK. Otherwise, let's create one.

**Comment by paoliniluis** [comment]
This question went from 6 seconds to 200ms... nuf said
![image](https://github.com/metabase/metabase/assets/1711649/9580404c-adb1-4f8e-90d7-31a5a801a1a6)
