### ISSUE TITLE
Notebook editor crashing if there is some special breakout clause

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#33490]
### Context
[Slack convo](https://metaboat.slack.com/archives/C05NXACAG1G/p1692955216365799)

### Describe the bug

Notebook editor crashes for some questions with breakouts

### To Reproduce

1. Open https://stats.metabase.com/question/4494/notebook
2. See the FE crashing with the MLv2 error

```
Error: No matching clause: dispatch-type/nil
    at T.j4 (metabase.lib.join.js:15:291)
    at s (metabase.lib.field.js:10:252)
    at metabase.lib.field.js:18:272
    at nr.g.j (cljs.core.js:503:460)
    at Function.e [as j] (metabase.lib.metadata.calculation.js:25:55)
    at metabase.lib.breakout.js:2:148
    at cljs.core.js:303:80
    at nr.g.Fa (cljs.core.js:316:248)
    at nr.bb (cljs.core.js:59:248)
    at nr.Ik.g (cljs.core.js:303:48)
```

### Expected behavior

Not crash

### Information about your Metabase installation

```JSON
- 0.47
```

### Severity

P1

**Comment by metamben** [comment]
The problem can be reproduced by creating a join (e.g., Orders joined with Products), adding some filters and a breakout using Products fields and then marking the Products table as crap in the Admin UI. After this, when the MLv2 query is created, the metadata passed in doesn't contain information about the Products table or its fields. Some FE assistance would be welcome to find out why that happens.

**Comment by WiNloSt** [comment]
[Example repro from Slack](https://metaboat.slack.com/archives/C05NXACAG1G/p1693382213337159?thread_ts=1692955216.365799&cid=C05NXACAG1G)

**Comment by WiNloSt** [comment]
The shorter repro
1. On a fresh Metabase instance
1. Create a new question *Orders* join *Product*, summarize *count* by *Products -> Category* (could be any field from product afaik)
1. Click visualize so that we save the current query to the URL, now you should see a bar chart.
1. Open another tab go to Admin > Table Metadata then hide the Products table
1. Go back to the opened question tab, refresh then click *Show editor* to open the notebook editor. You should see something like this
    ![image](https://github.com/metabase/metabase/assets/1937582/2237e603-22c9-47ba-be09-43f66a7251a6)

If the cleanup works as expected you shouldn't see the broken query there. By the way, it's there because of [this change](https://github.com/metabase/metabase/pull/33618/files), that was supposed to help us troubleshooting this issue easier. If we remove that BE change the broken breakout will crash the notebook.
