### ISSUE TITLE
When new users are signing up, confirmation link arrived already expired

### ISSUE THREAD

**Issue by maksim2042** [metabase/metabase#3356]
This is what we observed:
- New user signs up
- Within a couple of seconds I (admin) receive an email "User XYZ has accepted the invitation"
- User XYZ receives invitation email later
- The link inside this email is already expired. 

This happens on AWS deployment, but not on a similar deployment on Digital Ocean.
### Bugs
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
  Chrome, Firefox, Safari on Mac and Windows
- Your operating system:
  Client: Mac, Windows. Server: Ubuntu Linux
- Your databases: 
  Postgres
- Metabase version:
  0.19.3
- Metabase hosting environment: 
  AWS Ubuntu 14
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
  Postgres

**Comment by camsaul** [comment]
@maksim2042 how do you have SMTP set up?

It sounds almost like something is automatically following the links in those emails (maybe as some sort of security scan?). That would explain why you're receiving the "invite accepted" confirmation right away. The invite tokens are single-use, so that would also explain why people aren't able to use the links when they get the emails.

**Comment by salsakran** [comment]
Maybe we should expire the tokens *after* the user changes or sets their password?

**Comment by camsaul** [comment]
That would probably make sense

**Comment by salsakran** [comment]
I suppose it would open up an attack if someone was sniffing traffic and the link was over http. 

Don't think this new surface area outweighs the usability issues, as really anyone should be running Metabase over https in any event.

**Comment by camsaul** [comment]
Since the reset token is part of the URL it wouldn't matter whether someone was using HTTPS or not in this case 🙀 

But if they were running Metabase over HTTP keep in mind that people could just get passwords by sniffing the body of login commands anyway so that's bad news no matter what we do here.

**Comment by salsakran** [comment]
https covers the url get params. There would still be possible issues around the url being cached client side, in server logs, being passed as a referrer, etc.

**Comment by lindsay-stevens** [comment]
I noticed a similar issue that may be a symptom of the same problem. 

**Story**
- Admin creates regular user account
- User is sent email with invitation link
- Admin is sent email to tell them about the new user
    - Expected result: email indicates that the account was created (using the Admin's credentials)
    - Actual result: email indicates that the user accepted the invitation, despite the user not having followed the invitation link yet

**Causes**
The Admin notification email is generated in the user creation handler here: https://github.com/metabase/metabase/blob/1810ab1d181ddd11ab31386ae7ee5511c8773096/src/metabase/models/user.clj#L132

- If either of these are true:
    - the Admin user that sent the invitation has an active account
    - Google SSO auth is active in the Metabase instance
- Then:
   - Send an email to the Admin about the new user

The Admin notification email template used is here: https://github.com/metabase/metabase/blob/master/src/metabase/email/user_joined_notification.mustache#L7

- Message about what happened is selected:
    - If the user **did** join using Google SSO, then say: User X "created a Metabase account."
    - If the user **didn't** join using Google SSO, then say: User X "accepted your Metabase invitation."

**Resolution**
I think the above email template should instead say for the non-SSO case something like User X "was sent a Metabase invitation", because that's all that can be reliably said at that point. If this makes sense let me know and I'll do a PR for it.

Alternatively, to accurately inform the Admin if/when the user actually followed the invitation link & reset their password, it seems like it would need to be achieved by hooking in the handlers for the reset process. But an email for that seems like over-communication to me.
