### ISSUE TITLE
READ ONLY transactions for Postgres

### ISSUE THREAD

**Issue by jonahwh** [metabase/metabase#3381]
For context, this is based on a feature that Heroku Dataclips has. 

Whenever a Heroku Dataclip executes a query on a Postgres database, it prepends the query with, `BEGIN READ ONLY;`, which, as it says, runs the query in a read only transaction.

I'd like to see this feature in metabase so that when a database is added to metabase, there would not have to be a concern with users accidentally or otherwise making modifications to data or schema.

I'm not familiar enough with other DBMSs, but they probably have similar features that could be implemented as well.

**Comment by camsaul** [comment]
Hi @jonahwh, we don't make the transactions read only because some databases don't allow you to `SET` the session timezone on a read-only connection. Instead we run the queries inside a transaction that is aborted at the end which means no changes are committed. This has the same effect and prevents accidental modifications.

**Comment by jonahwh** [comment]
Alright, thanks!
