### ISSUE TITLE
Angular-related ERRORs on metabase webpack-dev-server

### ISSUE THREAD

**Issue by wiadev** [metabase/metabase#3402]
------
@metabaseops  Hi I'm trying to use metabase and on the first run of webpack-dev-server, it gives me several errors related with angularjs.

http://prntscr.com/cmw1gk

Here is the screenshot.

Also, I need to use ReactJS for front-end and I don't need angularjs.

but under resources/frontend-client, we have angularjs.

What is this for and can we remove this?

Thanks.

-----

**Comment by tlrobinson** [comment]
I assume you actually do want to use the development workflow, otherwise you should just get a prebuilt jar or docker container, of if you want to build from source you should use the `./bin/build` command.

It looks like you're somehow loading the index.html directly rather than via the backend. You need to run both the backend with `lein ring server` and build the frontend with `npm run build` (normal single build),  `npm run build-watch` (normal build but watches for changes),  or `npm run build-hot` (hot reloading), then load the app from http://localhost:3000/

More info here https://github.com/metabase/metabase/blob/master/docs/developers-guide.md

**Comment by wiadev** [comment]
@tlrobinson Thanks for support.
btw, in localhost:3000, hot reloading is not working. even if I've built the front-end with `npm run build-hot`.

**Comment by wiadev** [comment]
it works now. another question , though.
Is there any service I can call to external REST API? 
Is there any development guideline?

Many Thanks. @tlrobinson

**Comment by tlrobinson** [comment]
@wiadev Hmm, hot reloading is working for me. Are you getting any errors?

Regarding REST API are you wanting to create a Metabase driver to connect to an external REST data source, or do you want to access Mwtabase via a REST API?

**Comment by wiadev** [comment]
@tlrobinson I wanna connect to external service.

**Comment by tlrobinson** [comment]
@wiadev There's a guide for writing drivers at https://github.com/metabase/metabase/wiki/Writing-A-Driver

I believe the Druid driver uses a REST API, so that one might be worth looking at.

@camsaul is the resident driver expert so he can answer any other questions you have.

**Comment by tlrobinson** [comment]
Also, I'm not sure how easy it would be since REST APIs vary quite a bit, but it would be neat if we could write a `generic_rest_json` driver that we can build other drivers off of. Maybe use Metabase's own (currently internal) REST API as an example.

**Comment by camsaul** [comment]
@wiadev we have an open issue for a Google Cloud Datastore Driver: #1322. Feel free to add a 👍  reaction to that issue.
