### ISSUE TITLE
Prevent/block or warn when a question in personal collection is added to a non-personal dashboard

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#34045]
#### [Notion doc](https://www.notion.so/metabase/Prevent-users-from-adding-questions-from-personal-collections-to-dashboards-in-public-collections-d94438b13f974e0fbe97d99f732433d1)
**Is your feature request related to a problem? Please describe.**
Quite often, users save questions to their personal collection (accidentally or not knowing that others can't see them) and then add them to public dashboards, which seems to work fine for the author / admin but not for other users.  There is no use case for a personal question to be added to a non-personal dashboard (it's almost like a bug), so can we implement some sort of block/prevention when a user tries to do that? 

Once that happens, it's hard to tell which question without asking another user or opening each question in a dashboard to check. If we don't implement prevention/blocking, then at the minimal I think it would be a great to show a warning for each question in the dashboard that came from a personal collection, so it can be easily found / fixed.  

**Describe the solution you'd like**
See above -- prevent/block users from adding in the first place or show warning on dashboard afterward. 

**Describe alternatives you've considered**
No other way

**How important is this feature to you?**
It's bad user experience and not what Metabase should allow you to do. 

**Additional context**
n/a

**Comment by cdeweyx** [comment]
Confirmed this is straightforward from a product perspective [here](https://metaboat.slack.com/archives/C01MS7DQKR6/p1695335725746949). 

As far as the solution goes, I have a strong bias towards blocking rather than warning. The ideal behavior looks like:
* When I save a question in a personal collection, and we present the "Add to dashboard" modal, when I select "Yes" we then filter out all dashboards in that aren't in that same personal collection.
* When I am on a dashboard _not in a personal collection_ and I "Add a new question" then we filter out all questions in personal collections.

**Comment by WiNloSt** [comment]
There are some scenarios from [Improve the flow for adding a question to a dashboard](https://github.com/metabase/metabase/pull/30347#top) that come into play.

> To improve UX of adding question to the dashboard, we added next changes:
>
> - if there was a dashboard visited during last 24hrs, we preselect this dashboard in the ItemPicker by default
> - if there wasn't any dashboard visited during last 24hrs, we show root collection

That project changes how we display the first collection in the dashboard selector.

Some common scenarios:
1. When I save a question in a personal collection, and we present the "Add to dashboard" modal, when I select "Yes" we then filter out all dashboards in that aren't in that same personal collection.
2. Similar to 1) When I am on a question in a personal collection and I "Add to dashboard" then we should filter out dashboards that aren't in that same personal collection.
3. When I am on a dashboard not in a personal collection and I "Add a new question" then we filter out all questions in personal collections.

These are changes needed for the 3 scenarios above:
- For 1) and 2) We need a way to filter out all non-personal collections. Or shows non-personal collections, but doesn't show any dashboard.
- For 3) we could fix FE to not show a personal collection. Or shows a personal collection, but doesn't show any dashboard inside there.

Feels like it might be easier for (in fact I've implemented the following scenario)
- 1) and 2) to only show questions from a personal collection and hide all other collections.
- 3) to only show dashboards from other collections and hide a personal collection.

Unanswered questions:
- What about actions? We probably want to make sure this applies to actions i.e. we shouldn't be able to add actions from models in personal collections to dashboards in public collections.
- Would it make sense to follow this up with better UX e.g.
  - For 1) and 2) we filter out all dashboards in public collections. Maybe it's better to show user's personal collection from the start and we might also want to hide all other public collections since we only allow users to add this private question to dashboards in their personal collection anyway.
  - For 3) It might make more sense to hide personal collections altogether rather than showing the personal collection, but showing nothing inside it.

**Comment by cdeweyx** [comment]
I agree with the overall approach above. As for the open questions:

> What about actions? We probably want to make sure this applies to actions i.e. we shouldn't be able to add actions from models in personal collections to dashboards in public collections.

Let's capture this in an issue for later consideration, but it's not necessary for this at first.

> Would it make sense to follow this up with better UX e.g.
> * For 1) and 2) we filter out all dashboards in public collections. Maybe it's better to show user's personal collection from the start and we might also want to hide all other public collections since we only allow users to add this private question to dashboards in their personal collection anyway.
> * For 3) It might make more sense to hide personal collections altogether rather than showing the personal collection, but showing nothing inside it.

Yeah, in both of these cases, showing collections here that aren't relevant with these new constraints is bad UX. If it makes sense to split these optimizations out into a Milestone 2 then let's do that, but I think this is important enough to include in scope. 

> For 1) and 2) we can still select public collections in the dashboard selector and click Create a new dashboard, this won't actually create a dashboard in the selected collection but rather in the personal collection, so this is confusing. I think ideally we should hide Create a new dashboard button

Good catch. I agree. I think of this similar to the optimizations above.

**Comment by qnkhuat** [comment]
Completed in https://github.com/metabase/metabase/issues/34733
