### ISSUE TITLE
fix-dashboard-cards-without-positions can fail

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3473]
While this is an old migration, given that this is still in the codebase, and still potentially being run, all of the data migrations should be 100% bulletproof, and if they fail, should be fixable by the end user. Think we need to be a little more OCD about this portion of the code base. 

![screen shot 2016-10-07 at 11 05 53 am](https://cloud.githubusercontent.com/assets/107439/19200654/09329de2-8c7f-11e6-8005-c3a80c093c0f.png)

**Comment by camsaul** [comment]
Strange

**Comment by camsaul** [comment]
Looks like this was added in #2213 which was part of 0.16.0. So, an old one.

I can take a look at this and see if I can figure out what it's supposed to do, why it broke, and fix it.

Honestly it would have just made more sense to make `row` and `col` `NOT NULL` and give them default values. We could have done this in a Liquibase migration instead of doing it here

**Comment by camsaul** [comment]
I agree @salsakran we should be more careful when writing data migrations. I think we should also use Liquibase migrations to add `NOT NULL` constraints and default values instead of writing migrations like the one that broke here to "fix" `nil` columns.

I'm replacing this with a proper Liquibase migration in PR #3596

**Comment by camsaul** [comment]
@salsakran did somebody upgrade from pre-0.16.0? Because that's the only situation where this bug would have occurred 😳
