### ISSUE TITLE
Application name from appearance settings erroneously used for embedding license explanation

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#34920]
### Describe the bug

<img width="504" alt="image" src="https://github.com/metabase/metabase/assets/24216/0e9b1295-cc46-4faa-a00a-ad70e714b2c5">
<img width="738" alt="image" src="https://github.com/metabase/metabase/assets/24216/fe66ab93-5d91-4780-beba-d5bbb1c1b040">

### To Reproduce

1. Admin Settings/Appearance - Set application name
2. Admin Settings/Embedding (needs to be off)
4. Click on "more details"
5. Text contains the application name where it should be Metabase, including `Powered by APPLICATION NAME` instead of `Powered by Metabase`

### Expected behavior

We don't replace the Metabase here.

### Information about your Metabase installation

```JSON
- v1.47.4
```

### Severity

Medium

**Comment by iethree** [comment]
Currently we do a global replace on the "metabase" string for white-labeling. you have to exclude a string from `ttag` to exclude it.

https://metaboat.slack.com/archives/C505ZNNH4/p1682978941068939
https://metaboat.slack.com/archives/C057T1QTB3L/p1692711434412609?thread_ts=1692711380.023879&cid=C057T1QTB3L

**Comment by WiNloSt** [comment]
@albertoperdomo This looks somewhat to be in conflict with [With Whitelabel custom name, Metabase name is still shown multiple places in Admin Panel](https://github.com/metabase/metabase/issues/17043#top).

In that issue, we try to replace a bunch of **Metabase** occurrences with the whitelabeled application name, but we seem to want to do the opposite here. Should there be some rules on how we should apply the whitelabeled name replacement so it's easier to understand when and where we should and should not do so? e.g. We should replace the application name everywhere in the app for sure, but I'm not sure where in admin settings we want to replace and where we don't want to.

I want to get this clear before I start working on a draft solution since it would mean redefining the foundation of the code.

**Comment by WiNloSt** [comment]
This is [the Slack conversation](https://metaboat.slack.com/archives/C505ZNNH4/p1700480382374239) regarding the desired implementation
