### ISSUE TITLE
[MLv2] [Bug] FE - Values from a different filter clause aren't discarded when selecting another column in the picker

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#34960]
Steps:
- Filter on Product -> Vendor
- Add filter
- Click on filter
- Click back and select Category
- The value from the previous clause isn't removed

<img width="389" alt="Screenshot 2023-10-23 at 17 10 01" src="https://github.com/metabase/metabase/assets/8542534/0693928e-2e23-40dd-a160-b671a3a3526b">

Expected:
- Treat `filter` in `FilterPicker` as an initial value. When the column is changed, reset it to `undefined`

**Comment by iethree** [comment]
This is the behavior in the existing MLv1 filter picker. I suspect it's not intended.

**Comment by mazameli** [comment]
Hah, this is indeed not intended behavior! When I follow @ranquild's steps instead of this screenshot, I would expect to see the four product categories all listed, unchecked, and that's it. It's weird to see the vendor here.

<img width="442" alt="image" src="https://github.com/metabase/metabase/assets/2223916/598f1074-5d40-4281-ab4d-3eea9afaf2c3">
