### ISSUE TITLE
Serialization v2 export doesn't include parameter_card entity_ids which breaks the import

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#35097]
### Describe the bug

Importing an export in a new environment doesn't include `entity_id` values in the `parameter_card` table

<img width="1145" alt="image" src="https://github.com/metabase/metabase/assets/110378427/befda07a-b671-49fa-9fad-916dfc41a0e4">

The import would work at this point but when you take another export from the development environment (the one that actually has entity_ids in the 'parameter_card'  table) and go to import in the above environment the import will fail with the following error:

`Command failed with exception: No method in multimethod 'hadh-fields' for dispatch value:  :model/ParameterCard`

### To Reproduce

1. Go to New -> Question -> Products -> Save
2. Go to New Dashboard -> Add Text Filter -> Dropdown list -> Edit -> From another model -> Products -> Category

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/bead6427-e905-402d-b4ef-e33167787200">

3. Go to the application database and look at the table `parameter_card` you should find an entry with an entity_id:

<img width="1211" alt="image" src="https://github.com/metabase/metabase/assets/110378427/c7ee2329-1895-4943-8d2c-2138557affff">

4. Simply run ` java -jar metabase.jar export export_name` and if you go to the dashboard yaml and this newly created file you will only find an entity_id for the dashboard and the parameters section is just empty:

<img width="701" alt="image" src="https://github.com/metabase/metabase/assets/110378427/ac3ada51-8661-4aee-879a-ba7cf1fa09e7">

5. Now import this in a new clean environment and it will work. Try to re-import a second time and it will fail with:

<img width="994" alt="image" src="https://github.com/metabase/metabase/assets/110378427/618ce1bf-acf5-4b12-b1a7-bf117a2ceb04">

You will notice that it will try to perform a `backfilling entity_id for rows of ParameterCard` but it fails with:

`Command failed with exception: No method in multimethod 'hadh-fields' for dispatch value:  :model/ParameterCard`

### Expected behavior

I should be able to import. As a matter of fact if Serialization v2 uses entity_ids then everything should be exported with entity_ids

### Logs

`Command failed with exception: No method in multimethod 'hadh-fields' for dispatch value:  :model/ParameterCard`

### Information about your Metabase installation

```JSON
1.47.4
```

### Severity

This is actually is a borderline blocker for some customers which build a really neat git based workflow but currently have their environment broken since they cannot update anymore and as a workaround have to manually each time add the entity_ids directly via the Database

**Comment by bshepherdson** [comment]
I've got a [Slack thread](https://metaboat.slack.com/archives/CKZEMT1MJ/p1698351098837369) open to tackle this properly.

There are a couple of workarounds the customer could use in the meantime.

The most direct, if they're comfortable with patching Metabase, is to add the following to [`metabase.models.parameter-card`](https://github.com/metabase/metabase/blob/master/src/metabase/models/parameter_card.clj)
```clojure
(defmethod serdes/hash-fields "ParameterCard" [param-card]
  (if (:parameter_id param-card) :parameter_id :id))
```
Then run `UPDATE parameter_card SET (entity_id = NULL);` on the **target** instance, the one being `import`ed into. From then on, imports should work.

Alternatively, they can add the `entity_id`s from the source instance to the YAML files, and they should be respected by the target instance when `import`ing. Something like this:
- Get the `entity_id`s from the `ParameterCard`s in the source instance.
- Update their scripts(?) to add that field to the YAML files for dashboards.
    - (Use the `id` field in the YAML (eg. `id: "f0822a96"`) as the key to match up rows of the `parameter_card` table, where it's known as `parameter_id`.)
- Either delete all the `ParameterCard` entries in the target and let them get added by `import`, or update them all so the `entity_id`s match the source instance. (Otherwise they'll get duplicates.)
