### ISSUE TITLE
Broken question on stats (“Error running query”)

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#35219]
> <https://stats.metabase.com/question/12371|This question> hasn’t been changed since 4 months ago and now it is broken with an error: *`Error running query`*
If you convert to SQL, it works fine. It feels like a regression.

[Slack Message](https://metaboat.slack.com/archives/C01LQQ2UW03/p1698681372971629?thread_ts=1698681372.971629&cid=C01LQQ2UW03)

**Comment by metamben** [comment]
If I run this question, it fails because of an invalid pivot (breakout) index. I guess the visualization settings got corrupted somehow, because I could fix it by fiddling with the viz settings:
<img width="1011" alt="image" src="https://github.com/metabase/metabase/assets/103100869/5a9937be-1386-4f20-9560-739ba8302060">
Since it's a bit difficult to debug on stats, I'm afraid it would take a significant effort to find out what and when went wrong.

**Comment by paoliniluis** [comment]
Agree @metamben , probably we corrupted stuff . Any way we can put some defensive measures (frontend probably?) to output the issue rather than this generic error?

**Comment by metamben** [comment]
I wonder if this is related to #35025. If it is, then hopefully it has a fix too.

**Comment by paoliniluis** [comment]
Just received a ticket with a customer that hit this one.

So the issue is that we send the wrong MBQL?

**Comment by metamben** [comment]
@paoliniluis I think this is the same as https://github.com/metabase/metabase/issues/35025 and has been fixed (https://github.com/metabase/metabase/pull/35441). The problem is running the _saved_ queries.

**Comment by paoliniluis** [comment]
Got it, thanks
