### ISSUE TITLE
Get impersonation working in SQL server

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35271]
**Is your feature request related to a problem? Please describe.**
Simple as that, the new impersonation feature in SQL server

**Describe the solution you'd like**
Make it work

**Describe alternatives you've considered**
NA

**How important is this feature to you?**
Requested by a customer

**Additional context**
NA

**Comment by outinspace** [comment]
Not having this feature may block us from integrating Metabase into our product. I'm trying to implement SQL Server row-level security to restrict access for several hundred users.

**Comment by paoliniluis** [comment]
@outinspace row level security works for SQL server, why do you need impersonation?

**Comment by outinspace** [comment]
Hi @paoliniluis! Good question. Are you referring to row-level sandboxing in Metabase or native SQL Server row-level security? I don't think Metabase sandboxing will satisfy our needs for a few reasons:

1. Primary: We want row-level security at the database layer instead of the application layer for security.
3. We don't want to duplicate row-level security logic between Metabase saved questions and SQL Server policies.

We plan to have third party clients integrate directly with our database. To support this, we will have to configure SQL Server row-level security anyways.

**Comment by paoliniluis** [comment]
got it, thanks

**Comment by paoliniluis** [comment]
duplicate of https://github.com/metabase/metabase/issues/9947
