### ISSUE TITLE
[MLv2] - Visible Columns errors when source query is a table joined on itself

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#35290]
Right now in Stats, if you create a question that is Orders joined onto Orders, save the question and then use that as the source for another question you will get an error if you try to open the viz settings panel 

<img width="708" alt="chrome_fz4zilLelE" src="https://github.com/metabase/metabase/assets/1328979/2ea4891e-8b8a-4b15-a661-9a0a9376e8ab">
<img width="441" alt="chrome_92AL5CBtf1" src="https://github.com/metabase/metabase/assets/1328979/07584f34-d5cc-405f-acdf-efd16cdedaec">

**Comment by bshepherdson** [comment]
My defensive check is serving its purpose here. When coming from an earlier stage the names are used rather than the IDs. But when doing that we should be detecting the collision and using the full column alias rather than the simple column name.

I'm busy with #35205 right now, so if someone else from the QP+D team wants to pick this up, here's my pointers:
- Check if the ambiguous matches have any fields (eg. `:join-alias) we can use to disambiguate them; if so, add a new check under `metabase.lib.equality/disambiguate-matches-prefer-explicit`.
- Failing that, we may need to update how `ref`s are generated, to make sure they're using unambiguous names in cases like this. (Like using the `:lib/desired-column-alias` rather than `:name`.)

**Comment by bshepherdson** [comment]
This might be related to #33427 or might not be.

**Comment by bshepherdson** [comment]
The error that causes this to crash is turned into a warning by #36197 . That mitigates the impact of this bug so I'm removing this from the 48 blockers.

**Comment by darksciencebase** [comment]
removing this from the board as it's highly likely caused by https://github.com/metabase/metabase/issues/36185 and will be tackled as part of that cluster

**Comment by uladzimirdev** [comment]
the issue is not valid, I checked 49.13 and 50
