### ISSUE TITLE
Make `max-results` configurable for aggregated and non-aggregated queries

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#35428]
**Context**
https://github.com/metabase/metabase/issues/12729
https://github.com/metabase/metabase/issues/4564
https://github.com/metabase/metabase/issues/8622
https://github.com/metabase/metabase/issues/8322
https://github.com/metabase/metabase/issues/7622

Prior PR
https://github.com/metabase/metabase/pull/32401/files

Product doc: [link](https://www.notion.so/metabase/Increase-max-results-default-value-and-enable-configuration-using-env-vars-ab5ef784175a40629650afed033bf8df)

**Desired behavior**
If the admin doesn't change anything, we should apply the defaults:
- aggregated queries return up to 10000 rows
- unaggregated queries return up to 2000 rows

If the admin wants, they can change the following env var and change the limit:
- `MB_UNAGGREGATED_QUERY_ROW_LIMIT`. This value must be equal or less than the aggregated limit. This env var replaces `MB_MAX_RESULTS_BARE_ROWS`
- `MB_AGGREGATED_QUERY_ROW_LIMIT`. This must be less than [absolute-max-results](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/interface.clj).

**Comment by paoliniluis** [comment]
Did we merged this in 48? or 49?

**Comment by luizarakaki** [comment]
> Did we merged this in 48? or 49?

48

**Comment by Thossine** [comment]
Do you mean this issue is included in https://github.com/metabase/metabase/releases/tag/v0.48.0 release ?

**Comment by luizarakaki** [comment]
Yes, this is the relevant PR https://github.com/metabase/metabase/pull/35600

**Comment by Thossine** [comment]
I'm not used to use GITHUB, therefore i'm not able to find any of the issues numbers (35600, 35248, 32401) into the change log of 0.47.0 & 0.48.0.
Would someone help understand please ? 
Best regards

**Comment by darksciencebase** [comment]
@Thossine it is quite possible that it didn't make to the release notes (changelog), since those are generated from the milestones, and we had forgotten to add a milestone to this issue here prior to releasing. The milestone was added by Arakaki yesterday, and the release happened a few days ago.
But I have checked that the change itself was included (even though it's not mentioned in the changelog).
Here are the branches that contain [the commit with the change](https://github.com/metabase/metabase/commit/057149b606668a06da52bbaa16c7d56617387824):

```
❯ git branch --contains 057149b60666
  master
* release-x.48.x
```
It is in 48.

**Comment by Thossine** [comment]
> @Thossine it is quite possible that it didn't make to the release notes (changelog), since those are generated from the milestones, and we had forgotten to add a milestone to this issue here prior to releasing. The milestone was added by Arakaki yesterday, and the release happened a few days ago. But I have checked that the change itself was included (even though it's not mentioned in the changelog). Here are the branches that contain [the commit with the change](https://github.com/metabase/metabase/commit/057149b606668a06da52bbaa16c7d56617387824):
> 
> ```
> ❯ git branch --contains 057149b60666
>   master
> * release-x.48.x
> ```
> 
> It is in 48.

Huge thanks !

**Comment by desilvaNSP** [comment]
I am using self-host open source build, How do I change MB_UNAGGREGATED_QUERY_ROW_LIMIT into 100000, Because, I need to Transaction per second count for day. When I check admin settings panel. there is not option for than. What is the correct way to do that.

Do I need get the source code and build? Please help me on this.

**Comment by tonye-pexit** [comment]
Hi Team, what version of metabase does not limit files sent by email to 2000 lines???
I'm currently using version 0.46.6 and have the same problem.
