### ISSUE TITLE
Macros Issue

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#3557]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

Chrome 53

- Your operating system: (e.x. OS X 10, Windows XP, etc)

Mac

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)

BigQuery

- Metabase version: (e.x. 0.19.3)

0.20.0 (also present in 0.19.3)

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)

Ubuntu

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

Default

- *Repeatable steps to reproduce the issue*

Trying to create any macro with BigQuery.

Thanks for being part of the Metabase project!
-------

Unless I have missed something following the tutorials, the macro is not being replaced.

![screen shot 2016-10-13 at 09 11 13](https://cloud.githubusercontent.com/assets/425262/19341469/650e898c-9125-11e6-92f6-5083ac3588d3.png)

![screen shot 2016-10-13 at 09 11 29](https://cloud.githubusercontent.com/assets/425262/19341473/6a6d2136-9125-11e6-8fb5-791f6ca09e0d.png)

**Comment by camsaul** [comment]
Hi @cwbeck, unfortunately we don't support SQL parameters in BigQuery yet. We already have an open issue for this: #3303, so I'm going to close this as a duplicate. I'm going to go ahead and add #3303 to the 0.21.0 milestone because I think I should be able to tackle it fairly easily.

@tlrobinson I think we need to be checking whether the DB supports the `native-parameters` feature, or we shouldn't show the Variables pane in the native query editor. So this probably affects MongoDB and Druid as well. I'll open a new issue for that.
