### ISSUE TITLE
Check if inactive tables are being used by questions before deleting them

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#35615]
Related to https://github.com/metabase/metabase/pull/35443

We should check if the table is being used by any question before deleting it.
Delete only tables that are not being used.

If this is not enough to solve the AppDB size problem, we can consider removing this condition in a following release.

**Comment by qnkhuat** [comment]
to be clear, we don't delete inactive tables if there are active questions referenced to them.
if they are referenced in joins or used in SQL questions, we will still delete those.

for joins: it'll be very hard to check there because that means we need to scan the query of all the questions for a given database.

for SQL questions: pretty much nothing we can do here until we can parse the sql.

**Comment by likeshumidity** [comment]
Just making a note on this, if tables are in joins, they should also be preserved. The question breaks whether the deleted table is the first table in the FROM clause or the last one, so only preserving the tables listed first does not adequately cover the orphaned records issue.

I think a regex comparison can work re: SQL questions like mentioned here:
- https://metaboat.slack.com/archives/C01LQQ2UW03/p1700573672305939?thread_ts=1700165152.110229&cid=C01LQQ2UW03
