### ISSUE TITLE
Collection tree returns other's personal collection

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#35652]
### Describe the bug

The API `GET /api/colleciton/tree` return other's nested personal collection at top level.

### To Reproduce

Not really sure how to reproduce this on a fresh instance, but here is how to reproduce it on stats

1. I think you need to be a non-admin user on stats
2. create a new question
3. save it to your personal collection
4. When prompted to add the question to a dashboard, click yes
5. Now you should see the “Hosting Accounts” collection at the top-level

This "Hosting Accounts" is a nested personal collection so it should:
1. not be shown for non-admins
2. should be nested, not at the top level

Context: slack [thread](https://metaboat.slack.com/archives/C0641E4PB9B/p1699849571252549)

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

P2?

**Comment by qwef** [comment]
I believe this is because when we select collections, we first filter by visible collections, then exclude user collections. I think this is problem isn't actually possible to replicate through the UI anymore. But I do believe there's an optimization here where we don't need to pass all user collections through SQL. We can add a clause on where `:personal_owner_id` must equal nil or our current id, and filter any collection which root collection is not in our current list. This is fix this likely legacy issue, and also pass less data from sql to metabase. Thoughts? cc @metabase/core-backend-admin-webapp
