### ISSUE TITLE
[AuditV2] All items in custom reports collection are read only

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#35836]
### Describe the bug

Anything you save in the custom reports collection becomes read only (it gets `can_write: false`). found this in the bug bash.

https://www.notion.so/metabase/AuditV2-Bug-Bash-2a4e0f1ed37242bba90b7c267730c7e3?pvs=4#6197a4f8a241442bba88dc09ebccb9f1

### To Reproduce

- Create a question from the sample db
- save it in "our analytics" 
- see that you can edit it
- move it to "custom reports" under metabase analytics
- you can no longer edit it, see that it got a can_write flag.

### Expected behavior

you should be able to edit content in the custom_reports collection
### Information about your Metabase installation

```JSON
latest master 11/15/23
```

### Severity

P2, blocks a main analytics feature

**Comment by escherize** [comment]
The way permissions for cards and dashboard work is by overwriting how `mi/can-write?` works for different models. [Here is where we do it for a card.](https://github.com/metabase/metabase/blob/bcm-conditional-audit-logging/src/metabase/models/card.clj#L68-L75).

I think that _direct children_ of `Metabase Analytics` *and* `Custom Reports` are ending up being read-only (aka un writable) because of this check: `(perms/is-parent-collection-audit? instance)`. 

We basically check if the parent of the card/dashboard is the default audit collection (that is right), but also the `(:id (default-custom-reports-collection))`, which is what is causing this bug.

```clojure
(defn is-collection-id-audit?
  "Check if an id is one of the audit collection ids."
  [id]
  (contains? (set [(:id (default-audit-collection)) (:id (default-custom-reports-collection))]) id))

(defn is-parent-collection-audit?
  "Check if an instance's parent collection is the audit collection."
  [instance]
  (let [parent-id (:collection_id instance)]
    (and (some? parent-id) (is-collection-id-audit? parent-id))))
```

Just removing the check for the card/dashboard's Custom Reports collection id should fix this issue
