### ISSUE TITLE
Can't set "Field Filter" variables in SQL editor

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3586]
I'm sure someone else has already noticed this so feel free to close if a duplicate.

If I pick "Field Filter" as my variable type in the SQL editor there's no way to set the value

![screen shot 2016-10-14 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/1455846/19404016/b1cf82a8-921f-11e6-82ea-54ba4d9b4b4a.png)

**Comment by camsaul** [comment]
Possibly related: #3243

**Comment by tlrobinson** [comment]
IIRC this was an intentional decision because we didn't know which type of widget to show. If it's a date field should we give you a single, range or relative date widget?

We can certainly just pick one. Or provide a way to select the widget type, but that's slightly more involved.

In general I'm not a huge fan of the way we currently require you to choose a specific widget up front on dashboards, and not override it (especially not without deleting and adding another widget).

**Comment by camsaul** [comment]
Not sure I would call this a limitation. I think we should genuinely think about a way to make this interaction better.

I was trying to look into fixing #3538 and the honest truth is I can't even figure out how to get a Field filter widget at all. It's really a very confusing flow.

**Comment by camsaul** [comment]
Do I need to create a MBQL card and add a field filter to that, then add it to the same dashboard? And then it will prompt me for the filter type?

**Comment by tlrobinson** [comment]
If it was intentional behavior it's not a bug. Whether it's a limitation or bug doesn't have any bearing on whether or not it should be fixed.

**Comment by camsaul** [comment]
I would say being confusing / not obvious / not doing anything when people expect something to happen is a bad experience. We might just want to do something simple here like at the very least show a message like "Add this question to a dashboard to use your field filter"

**Comment by salsakran** [comment]
Yeah, we need to work on our overall parameter support.

The original goal  of a FieldBasedFilterClause was to add support for QueryBuilder style filters, specifically in dashboards. We decided to not add a widget on the saved SQL question page due to time constraints. There's a fair number of wrinkles to iron out here, but I'm not sure this is an actual bug.

**Comment by camsaul** [comment]
This has been implemented for a while now

**Comment by camsaul** [comment]
Closed as Already Fixed
