### ISSUE TITLE
Scrolling issue in sort dropdown with many values

### ISSUE THREAD

**Issue by albertoperdomo** [metabase/metabase#36074]
### Describe the bug

When scrolling up from the bottom of the sort dropdown, it automatically takes you to the top again after two or three scrolls

### To Reproduce

1. Open https://stats.metabase.com/question/notebook#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNCwicXVlcnkiOnsic291cmNlLXRhYmxlIjoxMjMyfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==
2. Click on Sort
3. Scroll down to the bottom of the dropdown
4. Scroll up a couple of times on the trackpad (with mouse wheel you could keep scrolling so it's a different pattern)
4. After two or three scrolls the dropdown auto-scrolls to the top by itself

### Expected behavior

It doen't interfere with my desired scrolling

### Information about your Metabase installation

```JSON
- Chrome 119.0.6045.159
- Metabase Built on 2023-11-23 Hash: 3481e43
```

### Severity

Moderate, it can be quite annoying if you have a dropdown with many values and you know the value you want is near the bottom

### Additional context

* [Slack thread](https://metaboat.slack.com/archives/C05NXACAG1G/p1700741371396719?thread_ts=1700739852.134059&cid=C05NXACAG1G)

**Comment by uladzimirdev** [comment]
Same issue happens when you update metadata 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to New -> Question -> Orders -> Custom Column ( Field Formula =[Total] * 1 and name = custom_tax) -> Save -> Turn into model 
2. Go to Metadata -> Custom_Column -> Set field_type to Quantity

Scroll down/up and scroll position will jump
