### ISSUE TITLE
Drill Through get's ignored on Questions having Models as datasource with Filters after Aggregation 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#36225]
### Describe the bug

Drill Through Questions having Models as datasource and filters after aggregation causes Filters to be dropped so losing the drill through altogether

### To Reproduce

1. Go to New -> Question -> Orders -> Save - > Turn into a Model
2. Go to New -> Question -> Orders -> Count and Created At by Month -> Filter by Count Greater than 0 -> Visualize as Line -> Save

<img width="1188" alt="image" src="https://github.com/metabase/metabase/assets/110378427/63462a1e-8895-4159-a7da-f7eafc873c4f">

3. Add this to a Dashboard -> Then press on `See these Orders`

<img width="1277" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e5c318d4-aac7-4bb3-b5c8-72ce00684ecf">

4. Notice that the month selected gets ignored and we get all the data

<img width="1511" alt="image" src="https://github.com/metabase/metabase/assets/110378427/8762a93a-ec80-43b9-8dda-46f925d3860c">

### Expected behavior

You get orders which are filtered based on your selection i.e. Drill Through needs to work

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.47.8 and master
```

### Severity

Causes Models to be unreliable with the only workaround to suggest clients to use Questions.

**Comment by ranquild** [comment]
Not fixed in MLv2 drills branch. The filter is appended but the temporal unit is not taken into account, leading to empty results. A date range filter should have been created.

<img width="1087" alt="Screenshot 2023-12-05 at 14 39 14" src="https://github.com/metabase/metabase/assets/8542534/ecf04e40-8cd2-4bbd-be02-6a4460c2a187">
<img width="1129" alt="Screenshot 2023-12-05 at 14 39 21" src="https://github.com/metabase/metabase/assets/8542534/79ad0e7f-56fc-4e6b-b17a-bacec730acc7">
<img width="1168" alt="Screenshot 2023-12-05 at 14 39 35" src="https://github.com/metabase/metabase/assets/8542534/c36b37eb-3e35-481e-a73a-55e2e41ecab9">

**Comment by camsaul** [comment]
Removing from MLv2 implementation epic since fixing bugs that already existed should not block the MLv2 migration project. We can fix this in the future. See https://metaboat.slack.com/archives/C04CYTEL9N2/p1701903974393029?thread_ts=1701903742.985089&cid=C04CYTEL9N2

**Comment by snoe** [comment]
@Tony-metabase I believe this was fixed in the mlv2 drill downs work. Can no longer reproduce.

**Comment by Tony-metabase** [comment]
Yep, works on 1.48

<img width="1202" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e9912faf-d36e-4ca1-b8ad-4ea0a5ac200c">
