### ISSUE TITLE
Version Metabase H2 database files

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3666]
Include the Metabase version number in the filename. Always use the DB that matches the current Metabase version. When upgrading to a new version, copy the most recent DB from an older version.

e.g. if I'm running Metabase 0.19.0:

``` bash
metabase.0.19.0.db.mv.db # created on first launch
```

And when I upgrade to 0.20.1:

``` bash
metabase.0.19.0.db.mv.db # no longer used
metabase.0.20.1.db.mv.db # copied from metabase.0.19.0.db.mv.db
```

If I launch 19.0 again:

``` bash
metabase.0.19.0.db.mv.db # application uses this database
metabase.0.20.1.db.mv.db # newer versions are ignored
```

This should be easy enough to do and would let people revert to an older version without things breaking. It would also back up people's databases for them because people aren't really good about doing it themselves.

Related to #1762

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
the most fun thing about this would be being able to go back and look at year-old versions of Metabase and then being like lulz compared to the new hotness

**Comment by camsaul** [comment]
Another thing we might consider is periodically backing up the Metabase DB file every day or week or whenever by making a copy like

```
metabase.2016-10-24.db.mv.db
```

so if it implodes people aren't SOL

**Comment by tlrobinson** [comment]
👍 

What about Postgres and MySQL, which are what we recommend for production use?

**Comment by camsaul** [comment]
Bring your own backup? RDS can do it for you or you can do it yourself

**Comment by salsakran** [comment]
I'm a little skittish about the disk-space implications of this. Also, as the size of the DB gets larger, it'll also slow down these copies.

**Comment by camsaul** [comment]
My local DB is only 450K. We can run the copy on a background thread and even delete backups after a certain age

**Comment by salsakran** [comment]
your local DB isn't being used in any kind of production setting with real data, query executions (and potentially stuff like a result cache, revisions, metadata, etc)

**Comment by salsakran** [comment]
I think the base situation (copying on upgrade on behalf of the user) makes a ton of sense. Some of the elaborations make me itchy.

**Comment by camsaul** [comment]
Neither should any H2 DB. But if one is I think people would wish they had that backup when the file explodes 😉 

Either way if the DB file is like 5MB that's still not much, especially when the uberjar is 82MB

**Comment by camsaul** [comment]
i.e. keep the last 10 daily backups only equals 50MB. And that's if you have a gigantic DB

**Comment by diwu1989** [comment]
I kind of think of the embedded database as just a simple tool to enable local development & toy use-cases. Getting a real Postgress or MySQL database set up is really easy these days.

If the usecase is database backup and recovery, then I think these kind of responsibility should be delegated over to the database infrastructure (ie, use RDS with a backup strategy, etc...)

I can totally see that if periodic db backup is built into Metabase, then you'll end up seeing tickets complaining about the vanilla installation eating up disk spaces over time and then we can get into a rabbit hole of implementing additional cleanup logic, file rotation, etc...

My 2 cents is that the concern from this issue is best solved at a different abstraction level. Whether its moving into a real database or a linux Cron job to manually take backup, it doesn't feel to me like something that should be built into core Metabase.

**Comment by camsaul** [comment]
closing as no longer relevant
