### ISSUE TITLE
[E2E] Fix the flake and remove the @flaky tag on embedding/embedding-smoketests.cy.spec.js

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#36688]

**Comment by WiNloSt** [comment]
![Screenshot 2023-12-14 at 5 12 16 PM](https://github.com/metabase/metabase/assets/1937582/4ca8db86-1e49-4b2e-a0ec-64770a22f62a)

When it flakes, it's calling `PUT /api/dashboard/:id` twice, and the second call would be initiated when we're navigating to the iframe URL which should *never* happen. I think there's something wrong with Cypress in this case. I'd rather wait to see the result on Cypress Cloud since we just upgraded Cypress to version 13, and maybe that might have some effect.

**Comment by npretto** [comment]
I couldn't reproduce it either, I tried to stress test it on the CI with no luck: https://github.com/metabase/metabase/actions/runs/7472804533

Hopefully it stopped being flaky with the latest changes on the e2e setup, let's keep this monitored.
I created a dashboard to monitor it, find the link in this slack thread: https://metaboat.slack.com/archives/C063Q3F1HPF/p1704888813165949
