### ISSUE TITLE
Provide a public sharable link for a dashboard

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3681]
As per designs in #2683, allow a user to share a given dashboard to users without a Metabase login.

This should have an instance wide admin toggle, and should use a generated, secure UUID for the public facing link.

**Comment by Sarrae1406** [comment]
Do we finally have a solution towards this ?

**Comment by edmarriner** [comment]
+1

**Comment by anki-code** [comment]
+1

**Comment by tlrobinson** [comment]
@anki-code Please use the 👍  reaction instead of +1 comments. Thanks.

**Comment by mrnnn** [comment]
That'd rock 👍

**Comment by lowiebenoot** [comment]
+1

**Comment by Steerlin** [comment]
+1

**Comment by axelwegener** [comment]
+1

**Comment by camsaul** [comment]
Relevant designs from #2683 (cut-and-paste of comment by @mazameli):

A public dashboard link should look something like this:
![public-dashboard-link](https://cloud.githubusercontent.com/assets/2223916/19708771/eff5df6e-9ad5-11e6-9343-1c9b69738804.png)

**Comment by camsaul** [comment]
@lowiebenoot @Steerlin @axelwegener Please use the 👍 reaction instead of +1 comments. Thanks.

**Comment by camsaul** [comment]
Isn't this the same as #3366?

**Comment by camsaul** [comment]
^ Adding you guys to the assignees list bc this is a team effort just like Steph KD Dray and Klay

**Comment by green2k** [comment]
+1

**Comment by camsaul** [comment]
Hi @green2k, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by camsaul** [comment]
Implemented by #4123

**Comment by dtheodor** [comment]
It's really good that you implemented this. A request: When creating a shareable link for a dashboard, and the dashboard has filters, I may create the link for a target audience that I want to limit to a particular filter value. The simpler example would be a 'customer ID' filter, where I would want to share the dashboard for a fixed customer ID value, without the ability for the user to switch to a different one. Now, I could do this by manually creating different dashboards for each customer ID, but this quickly turns out to be unyieldy.

**Comment by richardjzhang** [comment]
@camsaul just on dtheodor's comment above, are there any plans to implement a feature where a 'Public Link' for a dashboard has locked parameters?

**Comment by federicoBetti** [comment]
> It's really good that you implemented this. A request: When creating a shareable link for a dashboard, and the dashboard has filters, I may create the link for a target audience that I want to limit to a particular filter value. The simpler example would be a 'customer ID' filter, where I would want to share the dashboard for a fixed customer ID value, without the ability for the user to switch to a different one. Now, I could do this by manually creating different dashboards for each customer ID, but this quickly turns out to be unyieldy.

Hey @dtheodor, did you find a solution to this problem?

I am facing the same issue. Thanks in advance.

**Comment by flamber** [comment]
That functionality is available in Signed Embedding https://www.metabase.com/docs/latest/embedding/signed-embedding - see comparison https://www.metabase.com/docs/latest/embedding/introduction
This issue is closed, and has been for many years. Use the forum for questions and troubleshooting: https://discourse.metabase.com/
