### ISSUE TITLE
Provide a JSON download of a saved question

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#3682]
Similar to how we provide a CSV download, we should also allow users to download a JSON file with the results. 

The intention is that this will be used programmatically most of the time, and often in connection with #3680

**Comment by camsaul** [comment]
The backend for this is done in #3747 so now we just need to create the new UI and wire it up 

The designs look like this:

![image](https://cloud.githubusercontent.com/assets/1455846/20156534/87d6d3fa-a685-11e6-8608-cf1e05e9b883.png)

Since we're doing the public links as a next step for now I think we can just do the top half of the widget.
