### ISSUE TITLE
Moving up and down calendar near the bottom

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#3707]
Hi there!
I'm not sure if this is actually a bug but it is something that bother me.
When using a required date variable the calendar keeps moving up when you go to a specific month and down when you move forward. This happens because the calendar is opening up.

Check this gif:
![metabase](https://s21.postimg.org/8vne604ef/metabase.gif)

- Your browser and the version: Chrome 54.0.2840.71 (64-bit)
- Your operating system: Ubuntu 15.10
- Your databases: Postgres
- Metabase version: 0.20.3
- Metabase hosting environment: Ubuntu 14.04
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue:*
- Create a SQL question;
- Add variables enough so the last one is closer to the bottom;
- Change type to date and required;
- Try to set a date and changing between months.

**Comment by salsakran** [comment]
Yeah, the underlying issue is that some months need 5 rows and some need 6 rows. Either we have enough free space in that modal to allow 6 and leave one blank, or we need to resize in some way.

Resizing vertically seems less egregious than having there be a ton of un-used white space in the more typical situation where a month spans 5 rows.

**Comment by mazameli** [comment]
I think that, if and when the popover needs to resize, we could make it increase its height from the bottom rather than from the top. The only thing will look slightly funny is that, in the event that the popup is above the dropdown like in the example gif, the tip of the popup would move down into the dropdown a little. But I think that's a small price to pay to make these buttons not be infuriating.

**Comment by sabino** [comment]
How about filling all days?
Like this one: http://codepen.io/arqex/pen/BNRNBw

**Comment by salsakran** [comment]
That seems like a pretty good approach.

**Comment by mazameli** [comment]
Our friend Tim just brought this up today. This would be a nice, hopefully easy thing to fix.

**Comment by flamber** [comment]
Closing in favor of #14546
