### ISSUE TITLE
Pivot visualization no longer displays after editing - 'invalid metadata returned' error

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#37083]
### Describe the bug

After editing, cards with a pivot visualization may end up in a statewhere they can't be displayed. Backend API calls complete normally. Recreating the same viz from scratch works, but it is not possible to bring the failing one into a workable state via editing.

A pair of working and non-working questions created the same way on the GUI are available on stats:
https://stats.metabase.com/collection/1418-pivot-table-corruption

### To Reproduce
The problem occurs randomly and infrequently, approximately every tenth attempt in my local instance (probably more frequently on busier instances). My steps were:

- Create a question: Sample database, Orders, Summarize: Distinct values of ID, by: Total: Auto binned
- Visualize as pivot table, and save it.
- Open it, add Product -> Category to the grouping
- Probably optional: click on Visualize, the updated pivot table is displayed correctly
- Save it
- (!) Reopen the question, and the visualization is broken. This occurs randomly, most of the times the question created will work fine.

If the creation fails the question remains in a broken state:
1. Go to the question, the visualization won't display
2. Convert it to a table visualization, the viz still won't display
3. Save it and reload
4. The table visualization will display
5. Edit the question and set visualization to pivot
7. The visualization will display
6. Save it and it is broken again

### Expected behavior

Since the viz displays in the editor, it should continue to work after the question is saved

### Logs
See the attachment in the comments below for a HAR file about a local reproduction.

Comparison of the `/api/card` responses of the broken card and the newly created one that works: 
[api_card_response.broken_vs_from_sratch.redacted.txt](https://github.com/metabase/metabase/files/13754685/api_card_response.broken_vs_from_sratch.redacted.txt)

Console logs:
<img width="1027" alt="image" src="https://github.com/metabase/metabase/assets/11080638/1874e0d2-1319-4584-96d1-7f42b5ee3e35">

### Information about your Metabase installation

```JSON
Observed in 1.47.9, but the actual corruption might have occurred earlier, likely in 1.47.7 or 1.47.8.
```

### Severity

Reported by two customers. The workaround is to recreate the card from scratch which is frustrating, and it does not prevent the issue happening again at later edits.

### Additional context

<img width="864" alt="image" src="https://github.com/metabase/metabase/assets/11080638/7a3baa45-f26e-4247-90bc-a855fe732a17">

**Comment by markbastian** [comment]
I've tried the following based on the above:
* Created a pivot table
* Manually edited the database viz settings to set `valueHeaderWidths` to `{}` (to try to mimic what I can see being different in the output)
* Manually set the `result_metadata` on the card to an empty vector to simulate missing metadata.

When I refreshed my generated pivot table, the metadata was recomputed and the pivot table displayed correctly.

Some potential next steps:
* The "Invalid metadata returned for cell 2" seems to be tied to `calculateSizeAndPositionData` in `vendor.bundle.js`, leading me to think that this metadata isn't `result_metadata`, but something FE-related. My inclination is to see if there's something defensive we can do on the FE to ensure cell sizes are valid (my suspicion is that a cell size is somehow invalid).
* If we think this is related to `result_metadata` it might be worth asking someone on the query processor team to take a look.

Also, would it be possible to also attach those two responses as two separate attachments instead of a diff?

**Comment by zbodi74** [comment]
@markbastian - I have finally reproduced the issue on a clean local instance using the H2 sample database. Unfortunately, the problem occurs randomly and infrequently, approximately every tenth attempt. The steps I did:
1. Create a question: Sample database, Orders, Summarize: Distinct values of ID, by: Total: Auto binned
2. Visualize as pivot table, and save it.
3. Open it, add Product -> Category
4. Click on Visualize, the updated pivot table is displayed correctly
5. Save it
6. (!) Reopen the question, and the visualization is broken.

Attaching a HAR file and logs of a failed question creation, as well as another HAR showing the load of exactly the same visualization.
[pivot_error_local_reproduction.tgz](https://github.com/metabase/metabase/files/13866074/pivot_error_local_reproduction.tgz)

**Comment by zbodi74** [comment]
I could also create a pair of working and non-working questions on stats:
https://stats.metabase.com/collection/1418-pivot-table-corruption
On stats I managed to create a failing one at my second attempt, so I wonder if this occurs more frequently on a busy / slower instances?

**Comment by markbastian** [comment]
To be clear, the working and non-working versions above are identical except one "just failed?" If so, I think I might be able to work with that.

**Comment by markbastian** [comment]
Here are some consistent repro steps ([loom](https://www.loom.com/share/d5a48ffa733b4c4ab237cf459924768b?sid=0a72db10-c293-4b40-975b-7cd4f1880c5b)):
1. Create a question: Sample database, Orders, Summarize: Number of distinct values of... ID, by: Total: Auto binned
2. Visualize as pivot table, and save it.
3. IMPORTANT! Adjust the width of the "Distinct values of ID" column in the pivot table (click and drag to make it wider)
4. Save
5. Click "Summarize" at top right
6. Add Product -> Category to the grouping -- this should preview just fine
7. Now just refresh your browser and it will break

VERY IMPORTANT NOTE!!!
If the category you add just adds one more column to the pivot table it will break. I've noticed that in some cases the new category reshapes the pivot table to add multiple columns (instead of adding a single new column for product category it adds a new column for each category). If you see this happen, do not refresh, but instead try a different new category like User -> Source. I think the reshape operation resets all of the column widths so you won't see the broken display. The key is to add one new column when the existing columns have width values.

**Comment by markbastian** [comment]
If you view the network and console traffic here it looks like a FE logic error. The BE returns the data just fine, but then the FE breaks with the error:
> calculateSizeAndPositionData.js:17 Uncaught Error: Invalid metadata returned for cell 1:
        x:104, y:0, width:NaN, height:30

![37083](https://github.com/metabase/metabase/assets/8381441/414cd9f7-5dca-414f-a694-6965116e6249)
