### ISSUE TITLE
error result when shared dashbord has boolean type filter

### ISSUE THREAD

**Issue by chaoliu332** [metabase/metabase#37125]
### Describe the bug

I create a question use sql, and add a boolean type filter like `where 1=1 [[ AND {{is_seccuss}}]]`. Then I add this question to a dashbord and share it. 
When I open the url to see the dashbord, and add a filter to this question filter. I set the filter value 'true' or 'false', the result always be the result of 'false'. 
But in the metabase system to see the dashbord, the result has no problem.

### To Reproduce

1. create a question use sql, and add a boolean type filter like `where 1=1 [[ AND {{is_seccuss}}]]`
2. Then I add this question to a dashbord and and a filter linked to the table column of the sql, share it.
3. Use nodejs to make the url
4. Open the url in browser, and set the filter value with 'true'.
5. The dashbord away be 'false' result, no mater what I set the filter.   

### Information about your Metabase installation

```JSON
-metabase version (v0.41.5)
```

### Severity

I totally can't use metabase to display a wrong result

**Comment by ranquild** [comment]
@chaoliu332 You need to use `CAST` for boolean fields because Metabase currently doesn't support them natively. Like this:

```
SELECT * FROM ACCOUNTS WHERE 1 = 1 [[AND TRIAL_CONVERTED = CAST({{flag}} AS BOOLEAN)]]
```

You can set `true` and `false` as dropdown values to make it easier to use:
<img width="365" alt="Screenshot 2024-07-09 at 09 09 33" src="https://github.com/metabase/metabase/assets/8542534/90ae60d9-d02a-45e3-93ce-609cf058657b">
<img width="1159" alt="Screenshot 2024-07-09 at 09 09 37" src="https://github.com/metabase/metabase/assets/8542534/0384de2c-60a6-4f65-88d7-88f926d0aded">

You can do this in dashboards and SQL queries.
