### ISSUE TITLE
All V2 data/query permission paths are wiped when any non-data permissions are modified, or a new DB is added

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#37193]
This is a bug in the work-in-progress project https://github.com/metabase/metabase/issues/26918

The expected current behavior is that `/data/` and `/query/` permission paths are stored in conjunction with V1 paths, and updated in sync.

However:
* These paths are not being created correctly when a new database is added
* These paths are being entirely wiped when non-data access permissions are edited. For instance, if you update "Manage data model" permissions, all v2 data and query permissions are removed.

The root cause is [these two lines](https://github.com/metabase/metabase/blob/master/src/metabase/models/permissions.clj#L1059-L1060) which bluntly remove all v2 paths whenever `grant-permissions!` is called. I think this was a stopgap measure during the first phase of development, but because it's been already been included in a release, we can't assume anything about the state of v2 permission paths in customer app DBs. We should wipe them all and re-run the v1 -> v2 migration before shipping 49.

**Comment by escherize** [comment]
[That bit of code](https://github.com/metabase/metabase/blob/master/src/metabase/models/permissions.clj#L1059-L1060) looks to be deleting too many (unused) v2 permission paths to me too.

Seems like that function should have some logic that takes the incoming (v1) paths, converts them to v2 paths, and deletes the v2 records based on that, instead of just deleting all of them.
