### ISSUE TITLE
Available Databases don't get updated in Query Builder after adding/removing them in admin panel

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#3746]
I had two databases, and then I deleted one and clicked the link to "Bring the Sample Dataset Back" in the Admin panel. When I went back to the query builder (New Question) I still see the original two databases.

If I refresh the page the list is updated with the correct database list.

This is on 0.21.0-SNAPSHOT / master.

**Comment by salsakran** [comment]
@camsaul is this still happening? can't reproduce it on 0.22.2

**Comment by camsaul** [comment]
@salsakran, yes, this is still an issue. I reproduced it a few months ago and accidentally opened a duplicate issue, #5275

**Comment by tlrobinson** [comment]
I think this would be resolved by porting `DatabaseEditApp` to use the `entities` system, which should automatically invalidate the previously loaded list of databases when a database is added. I think it's one of the last few parts of the app we haven't ported from custom Redux actions/reducers to `entities`.

#9027 is related but slightly trickier since saving a question implicitly adds a "table" to the "Saved Questions" fake database.

**Comment by paulrosenzweig** [comment]
I'm unable to repro this. I just added a database and without a refresh it appeared both in the data model tab and query builder. The same worked when deleting that database.

**Comment by paulrosenzweig** [comment]
I hadn't read the original comment closely enough. I was able to reproduce it with the sample dataset. Just opened #10800 to fix it.

**Comment by paulrosenzweig** [comment]
Fixed in #10800
