### ISSUE TITLE
Mutiple requests are sent to /api/permissions/graph/group/n when loading data permissions page

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#37807]
### Describe the bug

The API sending multiple requests to /api/permissions/graph/group/1 could be intentional or not. It's essential to investigate the reason behind this behavior
and determine if it's necessary for proper functionality or if it's a bug that needs to be fixed.

### To Reproduce

1. Go to Admin > Permissions
2. Open the browser devtools and refresh the page

![Screen Shot 2024-01-16 at 4 03 17 PM](https://github.com/metabase/metabase/assets/343288/becea30a-10ad-4583-b965-b30f345970e3)

### Expected behavior

I expected to see 1 request to each endpoint to get a group's graph data, but I see two:

### Logs

see attached screenshot

### Information about your Metabase installation

```JSON
running master
```

### Severity

not severe

**Comment by npfitz** [comment]
I think what you're seeing here are the requests made by the parent component that ensure we fetch data for the Administrators and All Users groups. That data always needs to be present in the graph so that we are able to give various warnings in the editor (`All users has a higher permission, so this doesn't make sense` etc). The reason you're probably seeing it twice is because we always fetch fresh data on these pages so we can monitor the revision

**Comment by escherize** [comment]
Thanks Nick!
