### ISSUE TITLE
You shouldn't be able to set alerts on models

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#37893]
## Context
Models are data sources. You wouldn't set up an alert on a table. That doesn’t make much sense, right? You’d want to set an alert on criteria for existing or new rows on that table, aka a query. Allowing this results in bugs like https://github.com/metabase/metabase/issues/35091.

[More context](https://metaboat.slack.com/archives/C064QMXEV9N/p1705439180887609).

**Comment by yangmingtao** [comment]
![image](https://github.com/metabase/metabase/assets/8136462/e52655bf-4ef1-4fbf-b0c4-0ea1f674a260)

**Comment by nemanjaglumac** [comment]
The frontend portion of this has been fixed in https://github.com/metabase/metabase/pull/45611.
Re-assigned the issue to the backend team.

**Comment by ignacio-mb** [comment]
Can't reproduce this in master. Should we close this?

**Comment by nemanjaglumac** [comment]
@ignacio-mb @cdeweyx have you seen this comment?
https://github.com/metabase/metabase/issues/37893#issuecomment-2231429159

Have you double checked with the backend team(s) that the proper solution has been implemented?
The reason you can't reproduce it on `master` is because I removed the UI option. But I think we didn't solve the problem on the backend.
