### ISSUE TITLE
Table filter multiselect input box does not work

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#37955]
### Describe the bug

If you try to filter "Suite Name" or "Test Name" on this model, https://stats.metabase.com/model/14829-test-result, the filter input box doesn't work. You cannot enter text in the input box and there are no dropdown values.

<img width="252" alt="image" src="https://github.com/metabase/metabase/assets/39073188/54a788bf-2229-4862-b6aa-fb49552eaeab"> 

Loom:
https://www.loom.com/share/08ac4a92258640c58da3ad189fcd3efa?sid=815694aa-f78a-420e-bab3-d51c919d11d4

### To Reproduce

I couldn't reproduce the bug with any of the test tables unfortunately, I just saw this on stats.

### Expected behavior

typing should search a list of values

### Logs

2cd8c5f

### Information about your Metabase installation

```JSON
master (2cd8c5f)
```

### Severity

filtering is a pretty common operation, but not sure how common this is

**Comment by kamilmielnik** [comment]
I checked today in `master` at c09ec3ddeb and I can enter text into the input box.
However GET `/api/field/*/search/*` request takes around a minute in this case - that's why no dropdown options are shown.
It looks like a performance issue, so I'm sending it to BEC team.

![image](https://github.com/metabase/metabase/assets/6830683/78b413bb-411f-4fbe-aaa7-e22fadd2b83f)

**Comment by luizarakaki** [comment]
I believe the problem here is the lack of feedback of what is happening.
We need some visual indication that the search is happening in the background.

Besides that, I'm not sure what we can do. This model is insanely slow (took more than 2 minutes to run a count). A search is a query in the field, we can't know beforehand how long the query will take to run.

There is some work we can do to improve search in Model fields, but that's not the issue here.
