### ISSUE TITLE
Initializing MB from a config file is broken

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#38009]
### Describe the bug

If you start up a new instance of Metabase with `MB_CONFIG_FILE_PATH` set, and `MB_PREMIUM_EMBEDDING_TOKEN` set to a token that provides the `config-text-file` feature, it will nevertheless error with:
```
Execution error (ExceptionInfo) at metabase-enterprise.advanced-config.file/initialize! (file.clj:261).
Metabase config files require a Premium token with the :config-text-file feature.
`````

### To Reproduce

1. Set `MB_CONFIG_FILE_PATH` as described [here](https://www.metabase.com/docs/latest/configuring-metabase/config-file)
2. Set `MB_PREMIUM_EMBEDDING_TOKEN` to a token with full features
3. Start up Metabase with a fresh app DB

### Expected behavior

Should not error

### Information about your Metabase installation

```JSON
Current master
```

### Severity

unsure, feature might be totally busted

**Comment by noahmoss** [comment]
@crisptrutski @calherries Looks like this was introduced by https://github.com/metabase/metabase/pull/37849

**Comment by noahmoss** [comment]
@paoliniluis This is at least a P2 I think? It's a documented feature which is completely busted on master

**Comment by paoliniluis** [comment]
yup

**Comment by crisptrutski** [comment]
The route cause is a concurrency bug that broke the loading of feature flags the first time a server connects to the token server. Due to the bug we'd fall back to disabling all feature flags.

### Concurrency bug details

Lines prepended with a 🥈correspond execution that happens on the same background thread, whereas all other lines corresponds to execution on the main thread.

1. We start writing the first audited setting from the config file.
2. The auditor checks the `is-hosted?` flag to see if it should publish.
3. The getter calls `valid-token->features*`, which calls `fetch-token-status`.
4. The getter takes an intrinsic lock.
5. The getter calls a memoized version of `fetch-token-status*`
6. This function uses a future to call the Metabase API on an async thread.
7. 🥈 The async thread calls `site-uuid-for-premium-features-token-checks` to build the request payload.
8. 🥈 If the uuid has not been initialized, i.e. its a fresh app db, we set a generated value.
9. 🥈 The auditor again calls `is-hosted?` to see if it should publish.
10. 🥈 We follow the same path until we take the intrinsic lock.
11. 🥈 The lock is held by the main thread, so we block.
12. The main thread times out after 10s.
13. We cache an exception as the result of `fetch-token-status*`, with 5m expiry.
14. We cache an exception as the result of `valid-token->features*`, with 24hr expiry.
15. We catch the exception and treat all feature flags as false until the caches expire.
16. 🥈 The async thread resumes, and makes its own call to the memoized function.
17. 🥈 We treat `is-hosted?` as false, i.e. will not audit and the settings we write.
18. 🥈 We write `site-uuid-for-premium-features-token-checks` to the database.
19. We continue loading any remaining settings, also without auditing any of them.
20. Once all the settings are loaded, we assert that the `config-text-file` flag is set.
21. We are still treating all feature flags as false, so the application crashes.

Note that since `site-uuid-*` setting is still populated, and the app should start correctly if launched a second time. 

### Notes

Besides the fact that this ability to deadlock is a straight bug, there are a bunch of concerning behaviors that exacerbate the problem and were necessary for the specific breakage in this case. Without (1) we would simply have skipped the first audit event.

1. We cache exceptions for up to a day, even if they are once off or transient failures.
2. We do not log the underling failures.
3. We fallback to treating each flag as false, rather than having hard failures during startup.
4. We have two layers of caching with mismatched durations, i.e. parts of the app that use the lower level API will recover quicker, but be working with inconsistent values to other parts of the code.
5.  We have not been auditing the initialization of the UUID nonces.
  If we had this, we would likely have noticed [the previous regression](https://github.com/metabase/metabase/issues/37801), and the logging could have been used to fix any affected databases.
  IMHO we should either enable this auditing, or explicitly update the settings to set `:audit` to `:never`.
6. We write the config file's settings to the database **before** we check that they're allowed to use a config file.
7. During start-up we call `application-name` repeatedly *before* we have initialized the app db, a prerequisite for loading the feature flags. Since this setting is gated on the `:whitelabel` flag, we return the default ("Metabase") instead of the configured value from these early calls. I'm not sure how its used - this might be the cause of any bugs.
8. We are not performing type validation on any of the settings in the config file.
