### ISSUE TITLE
Creating label in Chinese failed

### ISSUE THREAD

**Issue by ryanchang** [metabase/metabase#3818]
When creating labels with Chinese characters, an error with message "A label with this name already exists" occurs, and the creation of new label failed.

- Browser: Chrome Version 54.0.2840.98 (64-bit)
- OS: macOS Sierra
- Database: MySQL 5.6
- Metabase version: 0.20.3
- Metabase hosting env: Ubuntu 14.04 LTS
- Metabase internal database: H2

![metabase_issue](https://cloud.githubusercontent.com/assets/363083/20657072/09588d78-b56e-11e6-8d88-f86528c528ce.png)

**Comment by salsakran** [comment]
can you share the other labels (ideally as raw strings) you already have? It's possible we're casting somewhere and losing information.

**Comment by camsaul** [comment]
This is happening because each label has to have a unique slug for the URL. e.g. if you create a label called "Cam's Business Metrics" it creates a corresponding slug `cams_business_metrics` so you can view the label at `http://my.metabase.instance/questions/label/cams_business_metrics`.

The logic lowercases all letters and then removes anything that isn't alphanumeric so as to avoid anything that doesn't belong in a URL.

That logic is probably a little too aggressive, and we can definitely tweak it to make sure unicode characters are properly supported. 

@ryanchang we're planning on replacing labels with a new way to organize questions. I'm working on the implementation so I'll make sure we handle unicode correctly for the new system.
