### ISSUE TITLE
Improve Application Setting inheritance

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#38250]
# Description

The `defsetting` mechanism allows us to define various kinds of settings for the application, notably 

An important type of setting is the `uuid-nonce`, a class of random identifiers used to identify customer installations with respect to billing, enabling feature flags, etc. This kind of setting needs to generate a UUID the first time the application loads, save this value, and never allow it to be changed.

The original implementation for this type involved overriding the low level `get-value-of-type` multimethod to do the initialization. This hidden side-effect violated the principle of surprise, especially in a immutable-first language, and led to a serious bug when we introduced setting validation during start-up. It also meant that auditing mechanism was being side-stepped, something that was accidentally "fixed" when we introduced a first-class initializer property, which led to another show-stopper bug due to a concurrency bug when auditing enterprise settings.

An issue with using the new initializer property is that there's no mechanism to set this via the existing type mechanism. We needed to revert all the instance to `{:type :string}` and add the the new `:init` setting explicitly at each site. Another failing with the previous `::uuid-nonce` type was that it did not encapsulate being read-only, not being audited, and having an underlying string representation, meaning that we needed to be careful to repeat these properties for every usage of the type.

TLDR - the `::uid-nonce` "type" is now a collection of 4 properties that need to be repeated together across their 6 usages. This repetition brings the usual risk of missing a spot to update, and its inherent noise.

It would be nice to have a mechanism that allows the `uuid-nonce` type to be fully encapsulated. There are probably also existing patterns that could be cleaned up with this mechanism. Particularly if we decide to open source this utility, I believe we should have good support for richer types we will not have foreseen.

## Proposals

1. Add more multimethods
2. Introduce a type map registry
3. Overload the `:type` property
4. Introduce `:base` property
5. Allow a map argument to `defsetting`
6. Do nothing.

### Multimethod

We could introduce a new multimethod

- Unable to extend base types
  - Only namespaced keywords can be used with `derive` in the global hierarchy
  - Would need to either namespace the base types or introduce a custom hierarchy.
- Large code surface area
  - Definition of each type is spread across a number of methods
  - Needs a new multimethod for each behavior to cover
- Inconsistency
  - Top level definitions just use keys and values for all properties
  - Harder to extract types, and more chance for errors.
  - A `get-base-setting-properties` multimethod is inconsistent with the other methods
- Does not feel idiomatic ("just data")

### Type map registry

This was my initial idea. Instead of registering multimethods, we could introduce a map of type keys to maps of their encapsulated properties. 

For now just putting this map in a `def` would be fine, but we could introduce an atom and a `register!` method if we want it to be extensible. A downside of having mutable state would be its impact on the stability of the REPL environment when changing branches, and more difficulty in finding the code where things have been defined.

### Type property

Instead of providing a key to a property map, what if we just linked to a var holding the map? The idea here was to allow the `:type` property to be a symbol for a var defining the map. Based on feedback this was extended to allow map literals and even code that defines a map, although in practice I think both of these would be anti-patterns.

By  allows us to enforce, disallowing the inheritance of`:export?` (it should always be explicit), making read-only "final", etc. We can also support transitive references to other maps to get transitive inheritance. 

**This is my favored approach.**

Implementation: https://github.com/metabase/metabase/pull/37863/files

### Base property

Instead of overloading the `:type` property, we could instead introduce a new key. This has a few advantages:

- We do not overload the type of `:type`
- We can inherit properties that are orthogonal to `:type`, e.g. just things like visibility and auditing.
- We could allow `:type` to be inherited

In my opinion it is confusing to have "parallel" hierarchies for `:type` and `:base`, and I don't think the additional affordances have real world value - in fact I think they would be foot guns.

Implementation: https://github.com/metabase/metabase/pull/37863/files

### Map argument to `defsetting`

Clojure keyword argument syntax allows for a final map argument. We could just allow a map to be passed directly.

This would be the most powerful and flexible approach allowing a la carte composition, e.g. `merge` for mixins, `dissoc` for "mixouts", `update` for decorators.

The downsides of this approach in my opinion:

- If we support mixing explicit pairs with a map, the map will shadow the explicit keys. This could be suprising 
  - Supporting mixing also creates issues for linting and producing good compile time errors, as it would not yet be a map at compile time for the macro, so we cannot make use of the `& {:as}` destructuring.
  - In short, we should probably only support a map if it's the only parameter.
- There's a large syntax inconsistency between flat keyword definitions and a map manipulation expression.
  - All explicit keys move to a final assoc operation at the bottom of the definition.
  - All explicit keys are now also far more indented than
  - Top level properties like `visibility` and `export` are now further down
- By not being opinionated, we introduce danger and sacrifice ergonomics.

Technically speaking we could expose an "extend setting properties" method to use, which takes the explicit keys as the first argument, enforces limitations on what can be overridden. In principle I have no problem with supporting "map only" as an escape hatch even if we go with one of the other options as the typical idiom.

WIP implementation: https://github.com/metabase/metabase/pull/38090

### Do nothing

Perhaps this is all YAGNI

---

### Note on existing multimethods

If we introduce one of these map-based approaches, we could even replace the multimethods with keys like `parse` and `stringify`. In my opinion that would be a nice ergonomic and consistency improvement. The top level type keywords could instead be replaced by maps. This could even get rid of the type's type-overloading if we go with Option 3.

IMHO it's awkward that `:type` is used to define the default values of `getter` and `setter`, but both of the latter can be overridden as regular options.

----

### Issue links

- https://github.com/metabase/metabase/issues/37801
- https://github.com/metabase/metabase/issues/38009

**Comment by calherries** [comment]
The elephant-in-the-room is that after 9 years of using defsetting, this is the first instance that the need for naming and reusing a specific combination of setting options has come up. That alone suggests we should keep our solutions to this problem pretty simple conceptually for users of `defsetting`, or else the solution can do more harm than good in making `defsetting` harder to understand, both in its interface and implementation.

**Type property vs base property**

I strongly prefer `:base`.

I'm comparing these together because their upsides/downsides compared to the map argument approach are similar. I favour the `:base` approach over `:type` for the advantages that you listed, and don't care so much for the downside you listed. Basically, because the scenario you're worried about you listed for `:base` is unlikely to happen as long as `:type`'s meaning is limited to how `get` and `set` behave. I'm referring to this:

> In my opinion it is confusing to have "parallel" hierarchies for :type and :base, and I don't think the additional affordances have real world value - in fact I think they would be foot guns.

I don't think it's very confusing, because `:type` and `:base` mean completely different things to me: a `:type` is solely responsible for how `get` and `set` behave. That's included in the [docstring](https://github.com/metabase/metabase/blob/f5bbee75c0b9ab913a1c4061787f845a77e91f69/src/metabase/models/setting.clj#L1102-L1106). The name of the key might imply something more general, but in reality its meaning is relatively narrow. `:base` on the other hand is a map of options that get merged with the rest of the top-level options in the `defsetting` definition. These seem pretty orthogonal to me. So it's actually a good thing these are separated.

**Map argument to defsetting vs base property**

I very weakly prefer the base property approach

I'm pretty split here. Excluding base inheritance (which IMO feels like overkill, and I'd lean towards its removal), the difference to me feels purely syntactic. As a user of `defsetting`, with the base approach you're referencing a map to merge in with top-level options, and with the map argument approach you're supplying a map and assoc'ing in top-level options. The difference is with the map argument approach, the assoc'ing is explicit and separate from `defsetting`, but with `base` it's hidden inside the defsetting implementation. I think both are fine solutions. I don't love the current implementation of the base approach because of its inheritance feature. That's pretty unnecessary at the moment and complicates `defsetting` beyond what's required at this point. The main benefit of the `:base` property is that you could enforce that top-level keys on the `defsetting` do not conflict or overwrite properties of the base, which indeed improves safety.

**Comment by crisptrutski** [comment]
> :type and :base mean completely different things to me: a :type is solely responsible for how get and set behave.

Considering the "base" can provide a custom `:getter` and `:setter`, and along with `:init` and `:default` their definitions will be case specific,I don't see how they are decoupled at all. The fact that `::uuid-nonce` was implemented originally as a type, when it could have passed in a  `:getter` also speaks to the writer seeing it as a "type" in the broader sense than just an ad hoc setting.

I agree we're splitting hairs over something ultimately inconsequential to us right now, happy to go with `:base` if that's the consensus.

**Comment by calherries** [comment]
> Considering the "base" can provide a custom :getter and :setter, and along with :init and :default their definitions will be case specific,I don't see how they are decoupled at all

True, `:base` can include properties that are coupled to `:type`. But it's possible for `:base` to only include properties that aren't. You even said so yourself:

> We can inherit properties that are orthogonal to :type, e.g. just things like visibility and auditing.

**Comment by calherries** [comment]
I've reviewed the `:base` approach PR https://github.com/metabase/metabase/pull/38088
