### ISSUE TITLE
Zoom in from dashboard change visualization

### ISSUE THREAD

**Issue by Michael-cd30** [metabase/metabase#38307]
### Describe the bug

When a question use the bar chart visualization, if you click on "Zoom in" directly from the question, the zoom is displayed as a bar chart.
But, when this question is on a dashboard, then "Zoom in" clicked from the dashbord displays the question as a line chart.

### To Reproduce

Create a question that sums a value by "date > day"
Set visualisation to bar chart
Save the question
Add the question to a dashbord
From the dashbord, on the question click on Zoom In to see the value by hour
--> the question is displayed as a line chart

### Expected behavior

The question should use its initial visualization after zoom in

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.14.0-362.8.1.el9_3.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5 (Debian 15.5-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-11",
      "tag": "v0.48.3",
      "hash": "80d8323"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

Low

**Comment by adam-james-v** [comment]
Thanks for reporting this. I was able to reproduce this and have this recording:

https://github.com/metabase/metabase/assets/21064735/2e6d4348-3a5a-4e65-86c8-d4f9fe1e8f53


That zoom in feature works by making a new question (not saved). The settings for the query and the viz are encoded in the URL. I suspect the bug here is that from a question, the correct viz setting is being used, but from a dashboard it's a different viz setting encoded in the URL. 

It seems to be a matter of ensuring we use the correct viz setting in the dashboard context.
