### ISSUE TITLE
[dc.js migration] bars become stacked in static viz

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#38827]
http://localhost:3000/question/250-combo-bars-become-stacked-in-static-viz

<img width="925" alt="Screenshot 2024-02-15 at 10 47 20 AM" src="https://github.com/metabase/metabase/assets/37751258/d144a02d-160a-4a06-9716-943c72fbbeb2">

in dashboard

<img width="577" alt="Screenshot 2024-02-15 at 10 47 33 AM" src="https://github.com/metabase/metabase/assets/37751258/cbb3bc22-f880-4f9a-8e34-851a9c76e720">

in subscription

**Comment by alxnddr** [comment]
The fix needs to be reimplemented.
https://github.com/metabase/metabase/pull/38988/files#diff-a996e07afd884cc1340bdeffa0eb577d7828cf4e6418c547d4dc201d1511f96dR290 card display can be `combo` and have bar/area series which would make it valid. Going to revert the PR in my branch since it broke stacking settings selector.
