### ISSUE TITLE
Is there an API to export chart image?

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#3883]
### Feature requests and proposals
It would be great if metabase can provide api to export chart images like the current slack bot does.

**Comment by tlrobinson** [comment]
There's actually an (undocumented) API that will render the same image as is used in Pulses/Slack bot, `/api/pulse/preview_card_png/CARD_ID`

**Comment by gilhs** [comment]
The thing with Pulses is, though, that they do not offer the same types of visualization and data amount support that Cards do. 
I actually stumbled upon this question specifically because Pulses currently can't deliver the type of emails I want to push to my team, and I'm looking for workarounds (which do not include rendering results myself - can run directly ontop of the DB for that).

**Comment by anki-code** [comment]
+1

**Comment by camsaul** [comment]
@gilhs more visualization options for pulses sounds like a separate issue, feel free to open it if you want :wink:

@thucnc there is actually documentation for the Pulse API endpoint [here](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apipulsepreview_card_pngid) (and a guide to using the API [here](https://github.com/metabase/metabase/wiki/Using-the-REST-API)) but as the disclaimer notes Metabase is a pre-1.0 product and the REST API is subject to change.

Let me know if that satisfactorily answers this question so we can close this issue 👍

**Comment by camsaul** [comment]
It sounds like this question was answered, so I'm going to go ahead and close this issue. Open a new one if you still have questions 💯
