### ISSUE TITLE
CSV upload fails on rows with float type among mostly integer values

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#38958]
https://metaboat.slack.com/archives/C04S696LRUM/p1707242309280519?thread_ts=1707238777.488509&cid=C04S696LRUM

**Comment by crisptrutski** [comment]
I think that the issue here is that we infer the schema based on a [subset](https://github.com/metabase/metabase/blob/ddfd9f636072034b9bff9681f3391ad17ee39b60/src/metabase/upload.clj#L340) of the rows, and are missing the sparse float values.

The solution for this will build on https://github.com/metabase/metabase/issues/37069

**Comment by crisptrutski** [comment]
The issue was indeed the row sampling. 

With the optimized inference method there's no longer any need to do the sampling, and the reference file loads correctly.

The merge for the fix is just waiting behind the implicit int to float column promotion PR.
