### ISSUE TITLE
Copy question name when "save as new question"

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#3921]
Hi guys! Thank you for great product!

I suggest copy the question name when "save as new question". It makes process a bit faster.

![image](https://cloud.githubusercontent.com/assets/1708680/21095981/e8be759e-c06e-11e6-9831-e5e40a421831.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Good idea. I'd just add an "of" so it would be `Copy of [name of original question]`.

**Comment by anki-code** [comment]
It looks like a simple feature. Isn't it?

**Comment by mazameli** [comment]
Four years later, here's a slightly better design, which makes it easier to edit the title:

In this example, I opened up a saved question titled, `Average of Rating by Category` and then added a filter. When I click save and then select "Save as a new question," the `Name` field should be in the format: `{Original question's title} - modified}, and the name field should be focused with the cursor positioned at the end, so that I can easily and quickly edit the name.

The rationale is that when I'm modifying an existing question, I'm very often doing something small like editing or adding a filter, or changing the granularity of the grouping dimension, and it's likely the name that I want to give the new question is just a permutation of the original question's name.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/2223916/103923665-3784d480-50ca-11eb-90d9-9d83f0bed80a.png">

**Comment by brunobergher** [comment]
This is what we ran with, closing.
