### ISSUE TITLE
Database Type option list is missing values

### ISSUE THREAD

**Issue by davidjhpgcc** [metabase/metabase#3934]
Using Metabase for Mac, upgraded today to the latest version v0.21.0.

Site Administration -> Databases -> Add Database

Database Type option list does not have Vertica, although website states it is supported.

Screenshot attached.

<img width="1481" alt="screen shot 2016-12-11 at 4 08 57 pm" src="https://cloud.githubusercontent.com/assets/16598413/21124332/25b1e14c-c093-11e6-82d7-fb4d1232cf4a.png">
<img width="1698" alt="screen shot 2016-12-11 at 4 08 20 pm" src="https://cloud.githubusercontent.com/assets/16598413/21124333/25bd76ec-c093-11e6-92ca-bbfec0de75ca.png">

**Comment by camsaul** [comment]
Hi @davidjhpgcc, as mentioned [in the documentation](http://www.metabase.com/docs/latest/administration-guide/databases/vertica.html) we can't ship the a dependency needed for the Vertica driver along with Metabase because it's not open source. 

Follow those instructions and download the JDBC driver and restart Metabase and you'll see the option.
