### ISSUE TITLE
Refuse to execute script from because its MIME type ('') is not executable

### ISSUE THREAD

**Issue by QuentinLuc** [metabase/metabase#39449]
### Describe the bug

Hey!  

We have a metabase instance deployed in a Azure Web App following the [documentation](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-azure).  It works really well except for some users who cannot access it because of this error:
`Refused to execute script from 'https://metabase.xxx.azurewebsites.net/app/dist/app-main.2557cfcbb410eb3199ba.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.` 
Most of the type, hard reload the page works but for some, they always got a white page because they get a 404 on the `app-main.xxx.js` script.

On this session, it loaded perfectly the first time, but I refreshed the page and got the problem:
<img width="1507" alt="image" src="https://github.com/metabase/metabase/assets/5237095/0a461d42-859d-48e2-917f-62debe388d2e">

### To Reproduce

1. Deploy Metabase on Azure Web App
2. Open the base URL

### Expected behavior

It should work all the time

### Information about your Metabase installation

```JSON
- Chrome lastest
- Azure Web app
- Container image: metabase/metabase:latest
```

### Severity

Blocking some users

**Comment by paoliniluis** [comment]
What's the web server there? is there any caching whatsoever?

**Comment by QuentinLuc** [comment]
Hey! Nothing special and no cache (at least not configured specifically in Azure).  The only config done is that one to pull the   Docker image.
<img width="1250" alt="image" src="https://github.com/metabase/metabase/assets/5237095/35f0216e-a1db-489e-afa4-a894b14db64e">

**Comment by gyanidude** [comment]
We are also facing the same issue. For some users, hard refresh works but for others it does not. Did we find the solution? @QuentinLuc

**Comment by guiernew** [comment]
Same issue here, some news? @QuentinLuc

**Comment by NizarHafizulllah** [comment]
same issue here, some news ? @QuentinLuc

**Comment by npfitz** [comment]
Hi all, I'm able to confirm that the issue is caused by a 404 for a static resource (which isn't really a surprise). The `MIME Type` error is a bit misleading. The fact that it resolves itself on a refresh seems curious though. @QuentinLuc @gyanidude @guiernew @NizarHafizulllah, Do any of you have any usage metrics around the time of the errors? Are they still happening for you? I'm wondering if the host machine is being overwhelmed and dropping requests because it it.

**Comment by guiernew** [comment]
@npfitz it was happening when upgrade to 0.48.0, after new releases the problem have been solved, never faced this error anymore.

**Comment by npfitz** [comment]
@guiernew Well that's certainly encouraging! I'll see if there was anything on our side that may have obviously impacted that around that time. Fingers crossed that everyone else has had a similar experience

**Comment by npfitz** [comment]
For anyone else who might be encountering this issue, we diagnosed this error on a deployment yesterday and found that the multiple Metabase instances were behind a load balancer without sticky sessions enabled, and not all the instances had the same version of Metabase. This meant that index.html was being served by `version a`, but the request for script.js was being sent to `version b`. Because the assets have a hash in the filename (which changes from version to version), the browser was getting a 404. 

This is one scenario that can cause this. Another avenue that was explored involved ensuring that index.html was no being cached (by a CDN or by the browser), and I am sure there are other possibilities as well.

**Comment by QuentinLuc** [comment]
I'm still getting it almost every time now.  To fix it, I open the Chrome DevTools console -> Application -> Clear Site Data, then the page refreshes automatically and it works 🤷‍♀️. Also we don't use any CDN.

**Comment by QuentinLuc** [comment]
Hi!  I still have the issue today.  

See the logs here: 
![Image](https://github.com/user-attachments/assets/dbffd567-51fc-4239-9d0e-2cbff42414fb)

Could you please check again?

**Comment by paoliniluis** [comment]
@QuentinLuc please wipe the CDN cache and your browser cache

**Comment by QuentinLuc** [comment]
@paoliniluis , yes this is exactly what I do every time.  But it's quite annoying to have to do that and to explain to non technical people.

**Comment by paoliniluis** [comment]
@QuentinLuc then don't use a CDN
