### ISSUE TITLE
Region map legends are bucketed oddly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3972]
I did a simple count of rows on the orders table grouped by state, but the legend gave me some decimal values:

![screen shot 2016-12-16 at 10 21 33 am](https://cloud.githubusercontent.com/assets/2223916/21273771/e8e3ca84-c379-11e6-8cde-c6bd1049b7d7.png)

It would be preferable when dealing with strictly integer sets like this that the legend would round up or down, so that for example the first bucket in that screenshot would be from 177–228, and the second one from 229–279.

**Comment by tlrobinson** [comment]
Yeah. There are actually 2 issues.

1. `type/Integer`: We can just round down the min and round up the max of each range, since we know there will never be anything in between.

2. `type/Float`: Currently we round the min and max (using our somewhat magic `formatNumber` function), but we can do better by adjusting the domain a bit, either manually or using something like d3 v4's `nice()` function: https://runkit.com/tlrobinson/58543834e921e70013340100

**Comment by salsakran** [comment]
mostly fixed via #4593
