### ISSUE TITLE
Optimize CLJS performance for common operators in the notebook editor

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#39754]
For context https://metaboat.slack.com/archives/C05MPF0TM3L/p1708940856401629

![image](https://github.com/metabase/metabase/assets/8542534/c39e57fc-6cbe-4467-9c97-6c114cecdb25)

```[tasklist]
- [ ] Optimize `expressionParts`.  We believe it re-computes something per-query which is not cached. It should/might be possible to add some internal caching in CLJS to make at least subsequent calls to `expressionParts` fast (for different expressions - join conditions).
- [ ] Optimize `displayInfo` for join condition columns. Probably something similar to `expressionParts` where some inner caching could be added.
- [ ] Optimize `canRun`. it’s supposed to be a simple check. 
```

**Comment by bshepherdson** [comment]
I looked into this but I'm seeing surprising results. Caching `lib.js/expression-parts` is ineffective, because the expressions are different instances in every case. I'm not sure exactly what's wrong, but it seems like the query is getting re-converted from legacy on every click, which means it shares nothing with the original MLv2.

We should probably start attaching the "twin" query when converting in both directions, in such a way that it will get dropped by any query manipulation in legacy or MLv2. Then when we take several actions in a row, round trips from edited MLv2 to legacy and right back to MLv2 don't start from scratch. It'll be faster to skip conversion, but it'll also be faster downstream because any caches and other memoization on the original MLv2 query will persist.
