### ISSUE TITLE
Collection permission graph is slow because the collection perm graph response, and revision info are very large

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#39997]
### Describe the bug

The size of the the collection permissions graph grows quadratically with the number permission groups, and collections. So it can get rather large.

That slows things down when:

1) returning the entire collection permission graph
2) writing the json blob to the revisions table (see @escherize's comment below).

### To Reproduce

1) create a metabase instance with 5000 collections and probably 5000 groups and then make permissions change to these collections

### Expected behavior

Getting and setting permissions should be fast

### Logs

Same thing as data permissions, you can't insert or get permissions to collections

### Information about your Metabase installation

```JSON
Always been like this
```

### Severity

P1

**Comment by paoliniluis** [comment]
A few tests and where it struggles:
![image](https://github.com/metabase/metabase/assets/1711649/b084d598-b4ed-4bdf-989a-cdcdc18b4066)

The most interesting part of the entire issue: when we're doing this a single CPU is at 100%, when the container has 8vcpu's
![image](https://github.com/metabase/metabase/assets/1711649/7c9a3517-d681-415f-a204-70fae8d3ce5a)

**Comment by paoliniluis** [comment]
Note for the MySQL people: as we're inserting a JSON in the database which can get pretty big, make sure that your MySQL will allow that

**Comment by escherize** [comment]
We found that this happens when inserting (in this case) 65mb string of json into the collection_permission_graph_revision table. That happens on every collection permissions update, in lock-step with revision number generation. 

It is redundant and expensive: usually there's one or 2 changes per update, but we rewrite a new complete json string with the whole collection perm graph in there every time. I don't know what (if any) value we are getting from keep the prior versions of the permission graph around, otherwise we could outright remove it.

**Comment by escherize** [comment]
Hey @paoliniluis, We've audited the codebase and there isn't any code that reads the saved collection perm-graph out of the `collection_permission_graph_revision` table. Since it's the before column that can get very large with many `(permission-groups * collections)`, we are considering simply not updating it anymore.

But we need to be sure noone uses it. Do you know of anyone who _might_ use it?


The table for reference:
```
                       Table "public.collection_permission_graph_revision"
   Column   |           Type           | Collation | Nullable |             Default
------------+--------------------------+-----------+----------+----------------------------------
 id         | integer                  |           | not null | generated by default as identity
 before     | text                     |           | not null |
 after      | text                     |           | not null |
 user_id    | integer                  |           | not null |
 created_at | timestamp with time zone |           | not null |
 remark     | text                     |           |          |
Indexes:
    "collection_revision_pkey" PRIMARY KEY, btree (id)
    "idx_collection_permission_graph_revision_user_id" btree (user_id)
Foreign-key constraints:
    "fk_collection_revision_user_id" FOREIGN KEY (user_id) REFERENCES core_user(id) ON DELETE CASCADE
```

**Comment by paoliniluis** [comment]
@escherize seems reasonable but let’s make sure that there’s audit info somewhere so we know who did what

**Comment by escherize** [comment]
@paoliniluis do you know how much faster this needs to be to actually fix the issue?

In any case, here are some low hanging fruits we can use to improve the performance on this endpoint:

```tasklist
- parallelize group permission lookups
- use partial graph PUTs with the `skip_graph` query param
- make coll perm graph revisions async
```
