### ISSUE TITLE
CumulativeSum and CumulativeCount do not work with post-aggregation math expressions

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4001]
`CumulativeSum(Total) + 1` gives the error `No matching clause: :cumulative-sum`

`CumultaiveCount + 1` gives the error `Assert failed: Aggregations of type ':cumulative-count' must specify a field. (= aggregation-type :count)`

**Comment by atharvai** [comment]
Is there a workaround?

**Comment by iFloris** [comment]
Just now I also ran into this. I want to display a series of values as a % of a goal, so I thought I would just divide the CumulativeCount by the goal number and multiply by 100. Like @atharvai I wonder if there is a way to work around this using Metabase. @camsaul since you referenced this issue on #4348, perhaps you know of a way to use CumulativeCount with simple math?

**Comment by camsaul** [comment]
I referenced this issue in #4338 because that issue was a duplicate of this. This doesn't work yet which is why this issue is still open 😉

**Comment by flamber** [comment]
Hi @tlrobinson 
I cannot reproduce this in 0.31.2.
Both `CumulativeSum(Total) + 1` and `CumultaiveCount + 1` returns the expected value.
![image](https://user-images.githubusercontent.com/1447303/52880896-d3994180-3128-11e9-93f7-626440ddc9f9.png)

**Comment by tlrobinson** [comment]
@flamber You're right, it looks like this was fixed.
