### ISSUE TITLE
[dc.js migration] timeline event line renders on top of bars

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#40180]
question/13475
https://metaboat.slack.com/archives/C06G94JTWBS/p1710341008223099

**Comment by JesseSDevaney** [comment]
Attempted the fix for this, but because `markLine` is being used here, it does not respect the z-index given. `markLine` has a fixed z value of 5 ([see ECharts src](https://github.com/apache/echarts/blob/fbee94d5dd3fe8a957524620eb3657145670bd50/src/component/marker/MarkLineModel.ts#L116)). This value is greater than the series `z-index: 2`, so it appears in front of the data points/bars. This fix seems more involved than an on-boarding/easy fix should require.

Relevant Files
- [timeline-events/options.ts](https://github.com/metabase/metabase/blob/echarts/frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/option.ts#L52-L103)
- [styles.ts/CHART_STYLE](https://github.com/metabase/metabase/blob/echarts/frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts#L32-L37)
  - See [line #3](https://github.com/metabase/metabase/blob/echarts/frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts#L3) for the comment talking about `markLine` having a fixed z-index value of 5

**Comment by alxnddr** [comment]
We need to submit a PR to ECharts and create a local patch to fix this

**Comment by JesseSDevaney** [comment]
I attempted making a local patch for this, but I ended up in a rabbit hole of JavaScript class inheritance while trying to figure out where options are getting merged and why the `z` option is not being overwritten when explicitly provided a custom value.

Perhaps someone else will have better look here, or I may figure out more about option merging as I complete other issues.

But for now, I am moving on from this.
