### ISSUE TITLE
we're waiting till the end of the /database endpoint to return to load the saved questions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40216]
### Describe the bug

Seems that for some reason we're waiting till the end of the /databases endpoint call to complete the load of the saved questions in the question builder

### To Reproduce

1) reduce the speed of your browser
2) go to the question builder on stats
3) see the load cadence

### Expected behavior

We should load everything asynchronously

### Logs

NA

### Information about your Metabase installation

```JSON
v48+
```

### Severity

P2

### Additional context

![Peek 2024-03-15 22-58](https://github.com/metabase/metabase/assets/1711649/0ee39708-3bc1-4cab-999e-4dcc1d5af705)

**Comment by nemanjaglumac** [comment]
@paoliniluis not sure exactly what you meant by "waiting till the end of the /database endpoint` because I can see TWO calls to that endpoint in your recording.

The first one calls `GET /api/database, and then the last one calls `GET /api/database?saved=true`.

In any case, this is not reproducible anymore because we switched to the new EntityPicker.
Leaving the issue open until we figure out whether or not to fix it specifically for v49.
