### ISSUE TITLE
Parameter filter widget jumps and doesn't allow to pick a value

### ISSUE THREAD

**Issue by oleggromov** [metabase/metabase#40232]
### Describe the bug

Instead of allowing to pick the value for the filter, the widget jumps (as if sorting has begun) and does nothing.

https://github.com/metabase/metabase/assets/2196347/96c8f918-c677-47df-b0bc-15a41642e60d

Must be related to `Sortable` because when I comment it out, the bug no longer exists. https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/ParametersList.jsx#L53-L59

### To Reproduce

1. Create a native query with a template tag. Literlaly `{{ x }}` will work
2. Set it to a list of values (shouldn't contain actual values)
3. Try clicking the filter widget, entering a value and clicking "add" or "update"

May not be 100% reproducible every time but at some point you'll see awkward jumping and the actual adding/change won't happen.

### Expected behavior

The value should be selectable. 
It shouldn't "jump" without actual dragging happening. 

### Information about your Metabase installation

```JSON
True as of `6fe41dd4379f4476b3eb78215b600393dd34474d`
```

### Severity

P3

**Comment by urkle** [comment]
The issue seems to be that the popup filter chooser is draggable and drags the field to a different order.

e.g. I have a question with 2 date filters and I try to "select" the date text and instead it MOVES the filter to a different position instead of selecting the text.   and clicking + dragging anywhere on the popup drags the field instead.

This is a new issues in 0.49.0 (did not exist in 0.48.9 or lower)
