### ISSUE TITLE
Tell variables not to automatically add quotation marks

### ISSUE THREAD

**Issue by Avey777** [metabase/metabase#40419]
How to tell variables not to automatically add quotation marks when using SQL queries

**Comment by Avey777** [comment]
Or can you tell me which file I should go to to modify the code to remove the function of setting variables to strings!

**Comment by paoliniluis** [comment]
@Avey777 can you please give us some hint of what you're trying to achieve here so we can help you better?

**Comment by paoliniluis** [comment]
closing due to lack of response/issue not correctly filled

**Comment by ksnyder** [comment]
The question is how to use a Metabase variable without it automatically being wrapped in quotes.  Sometimes the text variable set by the user needs to be manipulated as a string so that a query like this would work:

```
SELECT
  *
FROM
  plus.get_policy_chars_snapshot_in_time (
    '2025-01-01 00:00 America/Los_Angeles',
    '{{timestamp}} 00:00 America/Los_Angeles',
    TRUE
  )
```

Currently this query will be interpolated as: 
```SELECT
  *
FROM
  plus.get_policy_chars_snapshot_in_time (
    '2025-01-01 00:00 America/Los_Angeles',
    ''2025-01-21' 00:00 America/Los_Angeles',
    TRUE
  )```
and clearly it should not have the quotes around the date.  Where is it documented what can be done with string variables, it's a very common need to be able to manipulate them rather than having them go straight from user input into the query.
