### ISSUE TITLE
Allow pulse to set relative dates

### ISSUE THREAD

**Issue by parisholley** [metabase/metabase#4042]
Similar to the dashboard functionality, allow a question added to a pulse to have a date filter.

**Comment by salsakran** [comment]
What are you trying to do exactly? 

Are you using SQL or GUI queries?

**Comment by benjR** [comment]
That would allow Pulse to send weekly updates on the "last week" relative date for instance, in my case Pulse are not really useful without this. Happy to give more details if needed.

**Comment by stem** [comment]
Hi, I have the exact same need : I have a few questions saved with a variable date filter and I would like to send 2 pulses with the same questions on slack :
 - daily with yesterday data
 - weekly with last week data

Duplicating the questions is possible but a PITA because we would end up with a lot of unnecessary duplicated questions 😢

**Comment by pierrerigal** [comment]
up.

Exact same need here too, I just ended building my first dashboard with 20 important questions and complex SQL queries that I can filter by date on dashboard. 

Like @stem I'd like to send 5 most important question on daily and weekly basis with last day and last week data. 

Actually I had to duplicate each questions 2 times and remove date variable to do it in each questions :(

**Comment by flamber** [comment]
Closing in favor of #5770/#5771, which has much more upvotes.
