### ISSUE TITLE
Users with 'Editors' role don't see Dashboard subscriptions created by Admin

### ISSUE THREAD

**Issue by ismayil22** [metabase/metabase#40573]
### Describe the bug

When 'Admin' creates a Dashboard subscription and there recipients with 'Editors' role.

Users with 'Editors' role don't see this subscription at all and can't manage it (correct timing, add/remove new recipients etc)

It looks like a bug as before it was working OK and Dashboard subscriptions were always visible for 'Editors', regardless who created   it

![image](https://github.com/metabase/metabase/assets/26248319/3786eb05-15e6-4b3e-8533-230c60dfbd38)

### To Reproduce

1. Go create a 'Dashboard' as an 'Admin' and create a Subscription
2. Add users with 'Editors' role as recipients of subscription
3. Save subscription
4. Ask user with 'Editors' role open this 'Dashboard'
4. He won't see a Subscription at all

### Expected behavior

All users with 'Editors' should see Dashboard subscriptions, regardless who created it

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.57-060157-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by johnswanson** [comment]
Hi @ismayil22, thank you for the bug report! Looking into this, this was actually an intentional change. You can read a bit about it [here](https://github.com/metabase/metabase/security/advisories/GHSA-ch8f-hhq9-7gv5), but essentially, the old behavior was a security concern. A user with fewer *data* privileges could add themselves to a dashboard subscription created by someone with *more* data privileges, and thus get access to more data than they should have.

There [is a proposal to allow non-admins to view and edit subscriptions](https://github.com/metabase/metabase/issues/33131) on questions they can access, with a new permission. I think that would solve the problem for you, so you might want to subscribe to that if you're interested.

Thanks again for submitting the issue! I'll close for now since it was an intentional change.

**Comment by ismayil22** [comment]
Thanks @johnswanson for more details 👍, will subscribe to the mentioned discussion
