### ISSUE TITLE
"Cannot read properties of undefined (reading 'id')" when deleting custom user properties

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#40750]
### Describe the bug

If I want to delete user properties I get that error (users were created via sso without first or last name)

### To Reproduce

1) create a user via SSO without first name or last name
2) add user properties
3) save
4) then try to delete those

### Expected behavior

admins should be able to delete user properties

### Logs

middleware.log :: PUT /api/user/2 400 1.7 ms (0 DB calls) 
{:errors {:first_name "nullable value must be a non-blank string."},
 :specific-errors {:first_name ["should be at least 1 characters, received: \"\"" "non-blank string, received: \"\""]}}

2024-03-28 17:01:12,834 DEBUG middleware.log :: GET /api/health 200 184.0 µs (0 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (2 idle, 0 queued) (39 total active threads) Queries in flight: 0 (0 queued)
2024-03-28 17:01:18,981 DEBUG middleware.log :: PUT /api/user/2 400 5.4 ms (1 DB calls) 
{:errors {:first_name "Editing first name is not allowed for SSO users."}}

### Information about your Metabase installation

```JSON
v49
```

### Severity

P3

### Additional context

workaround: users should have first or last name

**Comment by Tony-metabase** [comment]
The problem is not just around user attributes and even if you create a user manually (not via SSO) without Last Name you end up with the same problem:

<img width="1217" alt="image" src="https://github.com/metabase/metabase/assets/110378427/7030447a-81f5-4629-a1cf-1d94327ceba1">

Even updating the email address won't work and will expect you to add the Last Name:

<img width="715" alt="image" src="https://github.com/metabase/metabase/assets/110378427/89bb6644-19a6-4e75-bf8e-690f9303f309">

I will increase this to P2 cause you have to add misleading information to a user to be able to use that user and the error message isn't clear which brings confusion to customers.

**Comment by sloansparger** [comment]
Glanced at this a bit, it appears to be two things:
1. The frontend isn't treating failed user update requests as errors, so it's expecting the response body to be an updated user when it's actually error details. (this subsequently causes the mistake of accessing the `id` property incorrectly in `frontend/src/metabase/redux/user.ts`).
2. The specific failure in this case is that we're setting along first and last names as an empty string. The backend is allowing these fields to be null, but isn't treating empty strings as the null case. This is different from how we validate the creation of the user, so we should likely remove this validation / coerce the value to null on the backend.
