### ISSUE TITLE
[Epic] Allow changing data source in join

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#40890]
Product doc https://www.notion.so/metabase/Allow-changing-data-source-in-join-10ce822731284486bec5de934789f376

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/40891
- [ ] https://github.com/metabase/metabase/issues/40916
```

**Comment by bshepherdson** [comment]
I assume there's a reason why this is tricky, but it's worth asking:
When we're creating a new join, the FE holds a partial join with no condition set (if we can't guess a good FK -> PK condition). Why can't the same approach be used here?

I guess it results in a confusing UX, since the join editing isn't a modal, there's not really any indication of it being a draft and not saved, nor that if cancelled the original join would still be there.

Can you expand on what join conditions should be generated when "forcefully" generating a join condition? If we have a good suggestion, great, but if not, do we fall back on `t1.PK = t2.PK`? If the PKs are different types, is it acceptable to fall back to `0` = `1` or something else that would always be false?

**Comment by ranquild** [comment]
@bshepherdson agree. I found a way to make it FE-only. Hopefully the UX is not bad.

**Comment by bshepherdson** [comment]
@ranquild is #40916 still necessary here?
