### ISSUE TITLE
Frontend E2E tests intermittently failing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#4095]
I've seen this a couple of times, they look like:

```
Backend ready (host=http://localhost:4000 dbKey=frontend/test/e2e/support/fixtures/metabase.db)
taking screenshot: screenshots/failures/auth_login_should_start
F  auth/login
    ✗ should start
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      - Failed: ENOENT: no such file or directory, mkdir 'screenshots/failures'
```

https://circleci.com/gh/metabase/metabase/9513#tests/containers/6

**Comment by tlrobinson** [comment]
It looks like it's unable to connect to Selenium. I'm not sure if that's due to an issue with Sauce Connect (proxy to Sauce) or connectivity with Sauce itself.

**Comment by camsaul** [comment]
I'm seeing this on `master` now:

```
Chrome 43.0.2357 (Linux 0.0.0): Executed 167 of 288 (skipped 3) SUCCESS (0 secs / 0.418 secs)
Chrome 43.0.2357 (Linux 0.0.0) utils generatePassword can enforce uppercase requirements FAILED
	Expected false to be true.
	    at Object.<anonymous> (test/unit/lib/utils.spec.js:75:107)
Chrome 43.0.2357 (Linux 0.0.0): Executed 168 of 288 (1 FAILED) (skipped 3) (0 secs / 0.423 secs)
Chrome 43.0.2357 (Linux 0.0.0): Executed 169 of 288 (1 FAILED) (skipped 3) (0 secs / 0.424 secs)
Chrome 43.0.2357 (Linux 0.0.0): Executed 170 of 288 (1 FAILED) (skipped 3) (0 secs / 0.427 secs)
Chrome 43.0.2357 (Linux 0.0.0): Executed 171 of 288 (1 FAILED) (skipped 3) (0 secs / 0.429 secs)
Chrome 43.0.2357 (Linux 0.0.0): Executed 172 of 288 (1 FAILED) (skipped 3) (0 secs / 0.431 secs)
ERROR: 'Warning: Failed prop type: The prop `fieldOptions` is marked as required in `FieldName`, but its value is `undefined`.
    in FieldName'
```

Not sure if it's related (?) https://circleci.com/gh/metabase/metabase/9713#tests/containers/5

**Comment by tlrobinson** [comment]
The first one seems like Sauce might have been down or network issues. I haven't seen it again recently.

The second one is an actual failure, though it's pretty rare. Basically our password generation function generates a random string, then checks that it satisfies some complexity requirements, and if it doesn't it tries again, up to 100 times. I'm not sure whether this actually increases or decreases security, since it seems like it's technically reducing the search space. https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/utils.js#L11-L37

There's also a bug in **both the function and unit test** for handling special characters. I'll leave it as an exercise to the reader to figure that out...
