### ISSUE TITLE
Axis tick labels in charts incorrectly using serif font

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4115]
This is on master:

![screen shot 2017-01-10 at 2 53 32 pm](https://cloud.githubusercontent.com/assets/2223916/21828305/a18b6bc2-d744-11e6-9176-08b2c89910ed.png)

The font should be rendered in our standard sans-serif typeface, Lato.

**Comment by kdoh** [comment]
This is a fun one. I think this is happening because of a change in the `dc.js` package when we bumped some of our dependencies since I can only reproduce this on master.

Our labels never actually used Lato itself and a oversight in [a recent CSS change of theirs](https://github.com/dc-js/dc.js/commit/44c8d62164a8466b403f99ff03ed6ac2b79f60e3#diff-38c031a294722a2e1dd3c13af6c5f61aL83) is defining the text for dc ticks as "sans-serif" which makes the browser look for a font called "sans-serif" not use a default sans-serif font.

**Comment by tlrobinson** [comment]
We should probably just override their font choice with our own anyway (Lato?)

**Comment by kdoh** [comment]
@tlrobinson Yeah we should but as I noted in #4160 I'd want to spend a little more time making sure we get the size / spacing right so I'm inclined to treat that as a separate issue.
