### ISSUE TITLE
Digits being lopped off during csv export

### ISSUE THREAD

**Issue by rojomisin** [metabase/metabase#41226]
### Describe the bug

After upgrading to v1.49.0 (currently on v1.49.3) a CSV export of a postgres sql data resource with `AMOUNT` for example turns a value like `99145` to `991`, perhaps rounding, perhaps truncating/lopping, not sure.
<img width="311" alt="Screenshot 2024-04-04 at 2 07 37 PM" src="https://github.com/metabase/metabase/assets/3313148/6802ffa6-e982-4037-a054-4e7c5ecd4203">
![Screenshot 2024-04-04 at 2 07 29 PM](https://github.com/metabase/metabase/assets/3313148/a3f6ab02-076b-4a64-955a-88d343172354)

### To Reproduce

0. Using postgres 15 as a backend
1. Go to a table view
2. Click on Download 
4. Scroll down to CSV
5. Compare values one should have 2 trailing characters lopped off

### Expected behavior

should not truncate values on export

### Information about your Metabase installation

```JSON
gke metabase 1.49.3
```

### Severity

blocking normal export and reporting use

### Additional context

we do not want to roll back to 1.48 can you help fix this or offer a workaround?

**Comment by adam-james-v** [comment]
Since you're on 49.3, it would be helpful if you could try to download the data 'unformatted'. To do this, before you click download, if you hold the 'option'/'alt' key and then hover over the .csv download option, you should see (Unformatted) to the right of the .csv label.

Then, download your results and see if the issue still happens with this unformatted version. If not, that might be a useful workaround for you while we solve the reported bug.

**Comment by rojomisin** [comment]
yes this worked thank you
