### ISSUE TITLE
[dc.js migration] data labels are less readable when overlap with goal and trend lines

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41280]
https://metaboat.slack.com/archives/C06G94JTWBS/p1712762682431379

**Comment by EmmadUsmani** [comment]
![image](https://github.com/metabase/metabase/assets/37751258/42d33325-39e4-424e-89c6-9d19a58dac94)

#### Problem

Data label z value is the same as the series z value. Since we render trend and goal lines above the series, they will also render above the the data labels

#### Solution

Use a separate series with higher z value for data labels, like stacked bars and waterfall
