### ISSUE TITLE
Query Builder time filters don't generate correct queries

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4192]
If you add an absolute date/time filter with a time, the time is ignored entirely and the entire day is used.

This happens on at least Postgres and H2.

Here's the generated query for Postgres:

```sql
SELECT date_trunc('hour', "public"."entries"."time") AS "time"
FROM "public"."entries"
WHERE CAST("public"."entries"."time" AS date) BETWEEN CAST('2016-09-10T18:30:00.000Z' AS date)
   AND CAST('2016-09-10T23:30:00.000Z' AS date)
GROUP BY date_trunc('hour', "public"."entries"."time")
ORDER BY date_trunc('hour', "public"."entries"."time") ASC
LIMIT 2000
```

I think we should be casting to `timestamp` instead of `date`

**Comment by mazameli** [comment]
More specifically, you're talking about the specific hour+minutes filter, I believe.

**Comment by tlrobinson** [comment]
Correct, I meant the "time" part but not the "date" part.

**Comment by camsaul** [comment]
It looks the Query Builder isn't specifiying the date bucketing for the field:

```json
[
    "BETWEEN",
    [
        "field-id",
        49
    ],
    "2016-09-10T18:30:00",
    "2016-09-10T23:30:00"
]
```

instead of 

```json
[
    "BETWEEN",
    [
        "datetime-field",
        [
            "field-id",
            49
        ],
        "minute"
    ],
    "2016-09-10T18:30:00",
    "2016-09-10T23:30:00"
]
```

[It's the default behavior of the Query Processor to assume day bucketing](https://github.com/metabase/metabase/wiki/Query-Language-'98#datetime-fields) if bucketing isn't specified, mostly so if people do queries like "where date = 2016-01-01" it would work the way the average user would expect.

The default has been that way for a long time, mostly to avoid breaking existing queries, but we could definitely change it. If we do, it would probably break existing queries :/

**Comment by tlrobinson** [comment]
Could the bucketing be inferred from the granularity of the timestamp (which I think is how I assumed it worked), i.e. `YYYY-MM-DD` would be `day`, `YYYY-MM-DDTHH:MM:SS` would be `second`, etc. Since I believe the QB previously only ever produced `YYYY-MM-DD` nothing should break, and this seems intuitive to me.

**Comment by camsaul** [comment]
We could do something like that but we'd need to be pretty careful with all the issues surrounding time zones (a timestamp intended as a day could get misinterpreted if it's shifted by a few hours due to timezone wackiness)
