### ISSUE TITLE
Can't launch Metabase on AWS ec2 in browser

### ISSUE THREAD

**Issue by jerryhall** [metabase/metabase#4195]
I'm unable to launch metabase in mybrowser:3000  or with myip:3000
I downloaded the jar to my project directory in my ec2 instance using wget  
I opened the ports wide and narrowed back down to original inbound of 80/22/443/3000  
The permissions for the /jar dir are at 0755, and the metabase.jar are set at 0664 with both with owner:root and user: ec2-user   
Netstat shows the port 3000 open best I can tell.  

I'm also running Apache Tomcat and GeoServer with default ports (8009, 8443)
I've checked my mod_jk and error logs and don't see any issues there. 
If you could give me any indication of what I should do to get this working I'd appreciate the help. Thanks!  
  
-----------  
Metabase v0.22  
I'm on a Windows 7,   
Server is Centos 6 AWS ec2  
OpenJDK is v 1.8.0_111  
Browser is Chrome v55.0.2883.87, and tried Firefox v50.1.0  
Haven't switched dbs yet (to PG95) so default there

**Comment by jerryhall** [comment]
I'm so over software that '...up and running in 5 minutes'. Back to d3.js. Ugh.
Feel free to delete this. Not trying to rain on anyone's parade.

**Comment by salsakran** [comment]
Hey, @jerryhall 

Sorry you haven't been able to get things going. To be clear, our "X minutes" refers to our heroku, beanstalk and mac deployment options. We don't make any promises regarding getting a jar up and running and can't really debug arbitrary network setups. 

For production usage, we recommend binding to port 80 http://www.metabase.com/docs/v0.22.0/operations-guide/start.html#running-metabase-on-another-port and running HTTPS. 

Our docker image, heroku deployment button and beanstalk recipes are our standard reference setups, and we *strongly* recommend using those where possible unless you have a specific custom setup in mind. The expectation is that if you're using the bare jar file, you have specific ideas on how you want thing to run, and the bandwidth to debug the resulting setup.

**Comment by jerryhall** [comment]
Hey Sameer, sorry for the snark. I really appreciate all you and the others are doing with this project. I'm committed to the EC2 so I'll use those references and get this ironed out. (The debugging bandwidth implies skill... which I'm working on acquiring as soon as possible :). Thanks!

**Comment by jerryhall** [comment]
Well, I give up. Hopefully someone in the future will suggest some clues how to launch in EC2. The other options aren't really options if my whole service is centered on EC2/Tomcat/Postgres... Thanks in any case.

**Comment by salsakran** [comment]
Hey @jerryhall -

I'd strongly suggest a couple steps to figure out what the problem is.

1. Run the jar locally and  familiarize yourself with what things should look like in the server logs. Run the server, connect to a browser, etc, all on a local host.  Once you've got the mechanics of running the jar down, setting up the server, and interacting with a working setup, it'll be easier to spot issues.

2. Run `java -jar metabase.com` from an instance (ec2 or otherwise) and make sure the server logs that are spit out match what you saw in step 1. If there are errors or warnings here that differ, you should debug those.

3. Assuming you have a working server process on your machine, do a `wget localhost:3000/index.html` and make sure the process is serving up the application. If anything is broken here, debug that.

4. At this point you should have a fair bit of confidence that sans network everything is working, so try accessing it from your local machine. 

Now, for a detour on ec2 networking. Ec2 instances have both security groups and possibly a "virtual private cloud" or VPC attached to them. Debugging connectivity issues if your local machine can't reach the instance in question is way outside the scope of what we can do for you, but if you got to step 4, you'll at least have narrowed down the potential set of issues to strictly network connectivity.

**Comment by olegshulyakov** [comment]
Hi @salsakran ,
Is there an easy way to integrate metabase into exsiting Tomcat instance,  for example using war file.
I haven`t found it under your downloads. Is it hard to do it by myself?

**Comment by salsakran** [comment]
@olegshulyakov we don't currently support war files as a stable build artifact. If you want to build them yourself you can create a war file from leingen. We evaluated that a year or so back, and decided that the support footprint on our end wasn't really sustainable. (eg, people asking "my server isn't working").
