### ISSUE TITLE
Set permissions for all questions which are not assigned to a collection

### ISSUE THREAD

**Issue by maximilianmessing** [metabase/metabase#4197]
First of all, the new collection feature is amazing and the ability to have permissions for each of them helps to give some questions/dashboard access to outside partners 🎉 .

It would be great to also set permissions for all questions which are not assigned to a collection, as they would appear to outside partners if they have data access to the database (which they need to have if they want to do csv exports of the questions in their collection). These Partner should be read only for their assigned collection and should not see any other generated questions.

**Comment by tlrobinson** [comment]
@maximilianmessing To clarify, I believe this is a UX issue, not a security issue. Users can recreate any question that appears in "Everything Else" because they have access to the underlying tables (otherwise the card wouldn't appear in "Everything Else" for that user).

Regarding "they have data access to the database (which they need to have if they want to do csv exports of the questions in their collection)": if the user has access to the card (via collections permissions) they should be able to download the CSV even if they don't have access to the database/table (via data permissions)

**Comment by maximilianmessing** [comment]
@tlrobinson you are totally right. #4200 will resolve the issue, we currently have. I gave the user group data access as they couldn't access the details of the question.

Awesome, can't wait for the release. 👍
