### ISSUE TITLE
[dc.js migration] Tooltip position sometimes is not correct

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#42114]
Details: [comment](https://github.com/metabase/metabase/issues/42114#issuecomment-2116433369)

---
https://metaboat.slack.com/archives/C01LQQ2UW03/p1714587141945559

**Comment by JesseSDevaney** [comment]
**Discussion of Issue**

https://github.com/metabase/metabase/assets/22608765/b217768f-8b27-4c50-bbda-aa212f6acd1c

---
**Too Long, Didn't watch**
Investigated the issue and determined that the ECharts data sent by the ECharts events is correct, but that the DOM element it returns as the target, does not always correspond to the correct ECharts element.

This is occurring because some painted ECharts elements have invisible areas painted on top of those elements. When hovering those elements, it passes the invisible area as the target element instead of the corresponding ECharts element.

There are solutions to fix these individual tool-tip issues, but then it breaks other parts of the application, so those are not viable.

It appears that the only long-term, viable, and stable solution would be to switch to the native ECharts tooltip.

---
- For Updates:
