### ISSUE TITLE
A user can view answers derived from multi-table SQL queries if they have access to any of the tables

### ISSUE THREAD

**Issue by brnt** [metabase/metabase#4248]
Browser: Chrome 55.0.2883.95 (64-bit)
OS: OSX 10.12.2
Database: PostgreSQL
Metabase: 0.22.0
Host: Heroku
Metabase DB: PostgreSQL

Expected behavior:
If a user is denied access to any table accessed in the query, the query as a whole shouldn't be available.

Actual behavior:
Given this query:

    SELECT A.foo, B.bar
    FROM A,B
    WHERE A.id = B.a_id

If the user has access to table A but not table B, they can still see the output of the query, including the values retrieved from B.

Suggestion:
Should the permission pattern to be reject on any deny, rather than accept on any allow? This change seems to be the more common approach to security in other projects. Additionally, it would result in fewer "surprise" disclosures (admittedly, with the burden of some surprise denials of access).

**Comment by brnt** [comment]
P.S. Revoking the user's access on all tables (`A` and `B` above) denies access to the question/answer, as expected.

**Comment by tlrobinson** [comment]
@brnt Are you referring to SQL queries? The database/table level permissions only apply to the GUI query builder, which is why there's a separate permission for SQL queries:

<img width="354" alt="screen shot 2017-01-26 at 9 10 58 am" src="https://cloud.githubusercontent.com/assets/18193/22341892/75cd95cc-e3a7-11e6-8ff4-a706209315e2.png">

**Comment by brnt** [comment]
Interestingly, if I revoke access to all tables at the Data Access level, the user gets rejected even though the question uses an SQL query. Also interestingly, the user has no SQL query access, but can still access the answer to the question (this might be OK) and can also see the raw SQL query above the answer (not OK; see issue #4237).

**Comment by tlrobinson** [comment]
@brnt Is the user a member of the collection the question is saved to? Collection membership gives users access to questions in the collection, even if they don't have data access permissions.

It doesn't make any sense to give a user SQL write permissions but no data access permissions since they'd have access to the entire database via SQL anyway.

**Comment by brnt** [comment]
> Is the user a member of the collection the question is saved to? Collection membership gives users access to questions in the collection, even if they don't have data access permissions.

Yes (if by "is a member of" you mean that they're in a group which has permission to view the collection), and good to know.

> It doesn't make any sense to give a user SQL write permissions but no data access permissions since they'd have access to the entire database via SQL anyway.

Agreed. I'm more concerned with the inverse. The UI seems to indicate that the user can be given data access, but still have SQL (read or write) access limited. In practice, this doesn't seem to be the case, though (write appears to be appropriately limited, but user can still see the SQL query, even with all SQL access revoked; but that issue is another ticket (#4237) altogether...).

Not sure that the original issue I described in this ticket is a bug any more, but it is worth noting that revoking all table access from the user (via the group) did revoke access to the SQL-based question, even though it sounds like the table-level permissions should only apply to GUI-based questions and that they should still have access by virtue of their membership in a group that has access to the collection containing the question.

Thanks for your clarification on a couple of points and feel free to close this.

**Comment by tlrobinson** [comment]
> The UI seems to indicate that the user can be given data access, but still have SQL (read or write) access limited. In practice, this doesn't seem to be the case, though (write appears to be appropriately limited, but user can still see the SQL query, even with all SQL access revoked; but that issue is another ticket (#4237) altogether...).

We haven't yet considered viewing the SQL itself (rather than the results of the SQL query) to be something that needs to be restricted, but I agree we shouldn't show the SQL if the user doesn't have the ability to write SQL (same for GUI queries where the user is only able to view the question due to read or write access of a collection)

> revoking all table access from the user (via the group) did revoke access to the SQL-based question

Since it doesn't make sense to allow SQL write access if the user doesn't have table access we automatically revoke SQL access if you revoke Data Access. You should see that reflected in the UI.

Before:

<img width="310" alt="screen shot 2017-01-26 at 10 56 55 am" src="https://cloud.githubusercontent.com/assets/18193/22345749/3c571a70-e3b6-11e6-9642-1de999206bbb.png">

After setting "Data Access" to "Revoke":

<img width="325" alt="screen shot 2017-01-26 at 10 57 00 am" src="https://cloud.githubusercontent.com/assets/18193/22345764/4b392d76-e3b6-11e6-9df5-4c0272f0d2d5.png">

However, I did realize this prevents you from only giving a group the ability to view SQL cards, and nothing else. I think we are planning on deprecating the SQL "read" permission in favor of collections.

**Comment by flamber** [comment]
This was fixed in 0.30 - giving a user group access to "Write raw queries" gives them access to the entire database (or whatever privileges the database user has).
There's a request for controlling permissions via SQL #10525 - upvote by clicking :+1: on the first post
