### ISSUE TITLE
Show a tooltip for all metrics in one point on chart

### ISSUE THREAD

**Issue by anki-code** [metabase/metabase#4263]
For example (most painful). When one point has a few metrics in stacked area. Chart shows tooltip only for last metric in list:

![image](https://cloud.githubusercontent.com/assets/1708680/22421679/6f839860-e6f9-11e6-89b2-51e64dce14ab.png)

On this chart you can't to know the value of the metric "A".

SQL for example:
```
select 1t,1A, 2B, 3C union all
select 2, 2, 0, 0  union all
select 3, 1, 2, 3 
```

⬇️ Please click "like" instead of "+1" comment

**Comment by tlrobinson** [comment]
I've got this basically working, but wondering how exactly it should be formatted, since just showing the full tooltip data for each results in some duplicated info.

We also have 3 different cases, which are all a little inconsistent (and maybe they need to be?)

1. breakout:

![screenshot 2017-02-07 17 16 59](https://cloud.githubusercontent.com/assets/18193/22719224/54f0d3da-ed59-11e6-932f-d72461a48608.png)

2. multiple metrics on a single card

![screenshot 2017-02-07 17 17 09](https://cloud.githubusercontent.com/assets/18193/22719230/5f1a16fa-ed59-11e6-9bdf-e43a467cee8b.png)

3. multiple metrics from different cards (i.e. dashboard multiseries)

![screenshot 2017-02-07 17 16 51](https://cloud.githubusercontent.com/assets/18193/22719243/674dbe1c-ed59-11e6-9b57-3e5c23d9dabf.png)

**Comment by tlrobinson** [comment]
@mazameli @kdoh It might be nice if we somehow incorporated the series color into the tooltip.

**Comment by anki-code** [comment]
@tlrobinson Could be a solution: to show the X value one time in the tooltip.

Example:
x1: 123
y1: 2
y2: 3
y3: 4

**Comment by anki-code** [comment]
@mazameli @kdoh Could you please help to @tlrobinson to resolve this issue in his PR?

It's really painful issue:
![image](https://user-images.githubusercontent.com/1708680/30160096-b4d75230-93d3-11e7-8b42-85d120d3822d.png)

**Comment by anki-code** [comment]
Still actual.

**Comment by anki-code** [comment]
Sad but still actual for 0.27.1

**Comment by mazameli** [comment]
This was implemented a while ago. Not sure exactly when:

![image](https://user-images.githubusercontent.com/2223916/72575058-0f301480-3880-11ea-834a-f6ac3f3ad95b.png)
