### ISSUE TITLE
Admins can't create queries on Metabase Analytics models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#43088]
### Describe the bug

Following a specific path, admins can't create questions on Metabase Analytics models.

The reproduction is inconsistent, but we have a customer that can't create questions at all.

### To Reproduce

1. New
2. Select a Metabase Analytics model
3. See a locked notebook editor

Repro Loom: https://metaboat.slack.com/archives/C064EB1UE5P/p1716475760677229

### Expected behavior

Admins (and any user with view access to the model) should be able to create questions

### Information about your Metabase installation

```JSON
- Stats
```

### Severity

A high priority P2

**Comment by noahmoss** [comment]
Root cause: because we don't return the audit DB by default in `GET /api/databases`, the metadata provider on the FE doesn't have knowledge of it. This results in the MLv2 query having a `null` database ID, which breaks the logic for displaying the notebook editor.

Returning the audit DB in `GET /api/databases` fixes this issue, but leads to audit content showing up elsewhere (i.e. it allows the raw audit views to be selected as data sources). We'll probably need some magic to add the audit DB metadata in the right spot on the FE.

Debugging thread for context: https://metaboat.slack.com/archives/C064EB1UE5P/p1717094345309169
