### ISSUE TITLE
Using specific dates in Date field filter automatically adds unwanted time filter

### ISSUE THREAD

**Issue by osayedTFL** [metabase/metabase#43196]
### Describe the bug

When filtering on the "date" field in our this txns table, as you can see these are the parameters set with no time selected whatsoever
![image](https://github.com/metabase/metabase/assets/114496083/cde20c2a-45a0-40a8-813c-8d262d175536)

however, after clicking on apply/update filter right after, you can see in the image below that a time filter is automatically added.
![image](https://github.com/metabase/metabase/assets/114496083/3d5a5725-76f5-403e-9366-fb905fb13951)

Also this only happens when choosing April 26th, and it is the day when Daylight Savings took effect in my local timezone.
Issue is not reported across all users, but no solution found so far.

### To Reproduce

1. Go to txns table
2. Filter by "specific dates"
3. Make sure specific dates end or begin on 26th april
4. Time filter gets automaticall applied

### Expected behavior

This should work as a normal date filter. If i don't have any time added or specified in the date filter then it should not appear automatically

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.214-202.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-22",
      "tag": "v0.49.7",
      "hash": "f0ff786"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking users, misrepresenting numbers on dashboards

**Comment by bshepherdson** [comment]
This is definitely DST-related. I suspect this is only a UI quirk, and not impacting the query results, but I'm not certain.

@osayedTFL Are you able to look at the Network tab for either the `/api/card/1234` for this card, or a `.../dataset` request for this card? It would be helpful to see how this filter is represented internally. Also, what are the time zones here? (DST start/stop rules vary significantly.)

There's not really such a thing as a "date filter" for a `datetime` column - the filter will need to specify the exact times at the SQL level, something like `date >= 2024-04-01T00:00:00 AND date < 2024-04-27T00:00:00`.

But the latter time might not really exist, if DST skips the hour of midnight and the day begins at 1am. I think we're rendering this badly in two ways: (1) we're showing the time when we don't want to be, because one of the times is not midnight; and (2) making it look like the 26th isn't included, when the SQL might include it.

Time zones and DST are a perennial pain point in Metabase. There may be no perfect way to reconcile the time zones of (1) the query author, (2) the database being queried, and (3) the query viewer, but there's still a bug to clean up here.

**Comment by osayedTFL** [comment]
Actually it does affect query results when filtering for 26 April specifically, especially as an "end date" in the field filter. All results for 26 April should show, but in this way it only shows results until 1 am on 26 april.
 This is the day when the DST jump happened and you are correct, it was the case that the clock went straight from Midnight to 1 am. The timezone is Africa/Cairo or UTC +2. This still shouldn't happen as our db is set to UTC, but the "date" field here specifically has a data type of "DateTimeWithLocalTZ"
 
 As for the network tab, I have here the payload of a "dataset" request.
 
 As you can see, a "temporal unit" key is added in the field filter for some reason.
{`"database":2,"type":"query","query":{"source-table":9,"filter":["between",["field",263,{"base-type":"type/DateTimeWithLocalTZ","temporal-unit":"minute"}],"2024-04-01T00:00:00","2024-04-26T01:00:00"]},"parameters":[]}`


however, as stated before, this issue does not appear for everyone in my organization, when I open the request from their device, this is the payload that is sent, notice that no time units are used.
`{"database":2,"type":"query","query":{"source-table":9,"filter":["between",["field",263,{"base-type":"type/DateTimeWithLocalTZ"}],"2024-04-01","2024-04-26"]},"parameters":[]}`

Do let me know if you need any more information on my end and I appreciate the response.

**Comment by ranquild** [comment]
Fixed by https://github.com/metabase/metabase/pull/44859
