### ISSUE TITLE
Multiple rows dashboard filters

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#4328]
We have highly dimenensional data and often add several filters in our dashboards. Unfortunaltly after a certain number of filters it starts overflowing on the right. It would be better if it could extend over multiple rows if needed. 
Another possibility would be an option to have a vertical filter bar instead of horizontal. (looks better with 5-10+ filters)

**Comment by luissancho** [comment]
Same for us, it would be so useful to have it jump to the next line after 4-5 filters.

**Comment by tlrobinson** [comment]
Here's what it might look like with multiple rows (just added a simple `flex-wrap: wrap` and some vertical margin). I don't love it since they're staggered, depending on the names sizes:

![screenshot 2017-02-09 16 47 25](https://cloud.githubusercontent.com/assets/18193/22809450/8ba2c124-eee7-11e6-98cc-0f4b72a97aea.png)

@kdoh @mazameli ?

**Comment by mazameli** [comment]
I've been playing around with a few different arrangements the last hour or two, actually, so I'll post some concepts this evening or tomorrow morning. 👍

**Comment by mazameli** [comment]
Okay, I have a few small prototypes that I'd love feedback on. First, I should note that all of these designs assume that #2963 gets implemented first or as part of this.

1. [Simple wrapping](https://invis.io/6CAEWQ53D). This is basically what you have now, Tom. The third screen shows how this gets wacky with lots of filters (but it's pretty wacky to have that many filters anyway, so…). The primary downside of this is that the filters persistently take up a lot of height (i.e., vertical width :trollface: ).
2. [More/fewer button](https://invis.io/3GAEWRRSJ). This version just adds a `More…` link when the number of filters exceeds four. If you collapse the overflow filters back down, and n number of them are active, the `More…` link changes to indicate how many hidden active filters there are.
3. [Show/hide filters](https://invis.io/6CAEWSR2H) Similar to option 2, but this version hides all filters by default, and hides all of them when you collapse the filters. It has the benefit of displaying the values of active filters, but might run into the overflow problem in that state, which would necessitate another solution.
4. [Side filters](https://invis.io/6UAEWTZPQ). This is the other possibility moumny suggested. The filters start out hidden, but can be slid out from the left side. This seems to work well if there are lots of filters, but looks a little weird if there's only one or two filters. I also like that it uses horizontal real estate instead of vertical real estate. It has the downside of obscuring active filters behind a tooltip/click.
5. Option 5 is not shown, but would be a combination of what we currently are already doing, plus option 4. I.e., collapse the filters down into the side button in the event your dashboard contains more than 4 filters. This would preserve the benefits of our current design (immediacy/obviousness of filters), while providing an adaptive outlet for complex dashboards that require lots of filters.

I'm kind of in favor of option 5.

**Comment by tlrobinson** [comment]
A couple thoughts:

1. I think they work relatively well except for the overflow issue so I'd prefer minimal changes required to address this issue (though I might be biased since I have to implement it :) )
2. Keep in mind we also have parameters on the query builder, fullscreen dashboards, and now public links / embeds. Preferably we won't need drastically different implementations for all of them.
3. I don't particularly love how the location of the parameter name changes from inside the widget to above depending on whether it has a value.
4. Related to that, keep in mind one of the widgets is a text box you enter text into, rather than a popover

I think my preference would be for 2, but with the current style (tweaked a bit). A possible enhancement would be the ability to re-order parameters so you can pick which ones show up in the first row.

I think if the the extra rows are hidden by default I'm not too concerned about the staggered-ness I mentioned before. Also it will be hard to eliminate the potential for them being staggered completely anyway, since the widgets resize to fit long values (e.x. date ranges):

![screenshot 2017-02-10 14 16 09](https://cloud.githubusercontent.com/assets/18193/22846255/7d1b7376-ef9b-11e6-90ca-65dfbda546eb.png)

Finally, I think we could decrease the min-width a bit so that more of them will fit, especially ones that don't have a value. This is a lot of wasted space:

![screenshot 2017-02-10 14 10 43](https://cloud.githubusercontent.com/assets/18193/22846095/bbd8c4ac-ef9a-11e6-865f-d44803417b8f.png)

**Comment by mazameli** [comment]
> Keep in mind we also have parameters on the query builder, fullscreen dashboards, and now public links / embeds. Preferably we won't need drastically different implementations for all of them.

Yeah, I think SQL question params also suffer from this problem, so ideally the solution we go with here could be extended to work over there.

> I don't particularly love how the location of the parameter name changes from inside the widget to above depending on whether it has a value.

Could you elaborate? I'm strongly in favor of this; I think it saves a lot of space, and looks cleaner.

> Related to that, keep in mind one of the widgets is a text box you enter text into, rather than a popover.

Not sure how that's a problem. I'd imagine that when the user clicks into the text box, the label would float above, even before the filter is committed.

> I think my preference would be for 2, but with the current style (tweaked a bit). A possible enhancement would be the ability to re-order parameters so you can pick which ones show up in the first row.

I could probably live with this depending on others' feedback. And I 100% agree it would be far better if you could reorder the filter widgets.

> I think if the the extra rows are hidden by default I'm not too concerned about the staggered-ness I mentioned before. Also it will be hard to eliminate the potential for them being staggered completely anyway, since the widgets resize to fit long values (e.x. date ranges).

Yeah, aesthetically I'd prefer having the filters' width be responsive (like 25% of the available space) so that they could be a uniform width. Dates could be dealt with by reducing them down to `Feb 6, 2017 – Feb 16, 2017`, or `2017-2-6 – 2017-2-16` (the latter being more contentious). Other long input could be helped by, for all filters values, decreasing the font size/weight very slightly. But I get that that's a less foolproof way to ensure the entirety of filters' values are visible.

> Finally, I think we could decrease the min-width a bit so that more of them will fit, especially ones that don't have a value. This is a lot of wasted space.

I'd much rather do the floating labels thing.

**Comment by moumny** [comment]
Wow great mockups !
I believe option 2 is the best tradeoff of complexity and value but i do like the option 5.
BTW #2963 is cool as well. Space in dashboards is a very scarce resource ;)

**Comment by luissancho** [comment]
I think options 1 or 2 are both fine, because some filters have default values and would be uninformative if we collapse them into a filter button. Also it makes sense making them to have the same size, like the 25% mentioned by @mazameli, as it results in a more harmonious design.

**Comment by luissancho** [comment]
I believe it is very important to have this at least fixed for 0.23.0, so the simple `flex-wrap: wrap` would be enough until we address the more/less solution (or any other).

**Comment by mazameli** [comment]
So we're going to shoot for what I called option 5 above, which means:
- If a dashboard has 4 or fewer filters, we keep doing what we currently do
- If there are more than 4 filters on a dashboard, we hide the filters under a toggle button over on the left. If any of the filters are active, the collapsed state of the toggle shows a number to indicate how many filters are active. [Designs/prototype here](https://projects.invisionapp.com/share/6UAEWTZPQ#/screens). When dashboard edit mode is entered, I think we should expand out the filters automatically so it's clear that you can edit them.
- Once implemented, we can quickly evaluate if we like that we're hiding the filters by default, or if we think we should display them expanded by default.
- I would also really, really love it if #2963 gets implemented as part of this. The InVision prototype shows a slightly updated version of the design, the only difference being the font styling for the floating label, and the addition of an icon in the filter's empty state.

**Comment by mazameli** [comment]
The team talked this morning and we decided instead to start off small with just option #1 (simple wrapping), with the option of including a `more…` / `fewer` link if we feel we need it. Another possible tweak would be consistent filter widths in order to make the grid of filters look nicer.

But we're definitely doing #2963. :)
