### ISSUE TITLE
Possibility to copy/paste list of value in filters 

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#4330]
Often our users have list of comma separated values to add to a IN filter. Lists can be from 10 to 100s. (eg. list of products, or user group)  Currently it requires to add each value one by one, which is quite tedious.

There are two places where this could be useful:

- The query builder: Ideally in the filter popover next to "add another value" there would be "add list of values" where copy pasting comma separated list of values would be possible.
- Since it is not possible to have IN filters in dashboards this would be a way to add it. Perhaps, this could be a "IN catergory" widget thats separate from the normal one.

**Comment by mazameli** [comment]
This seems useful. Here's how it might look to add this to the query builder filters:

![enhancing is](https://cloud.githubusercontent.com/assets/2223916/22806805/a9dc9aca-eed8-11e6-8bc0-0683b391180e.png)

![enhancing is - expanded](https://cloud.githubusercontent.com/assets/2223916/22806810/b08af6a0-eed8-11e6-926a-1f8be1f151f3.png)

What I like about this is that it doesn't add another option in the list, and it could subsume the existing "add another value" interaction." One small concern: if we tokenize the input by using commas as delimiters, I'm not sure how this could handle a case where your list of values contain meaningful, non-delimiting commas, like "San Francisco, California" and then "Bern, Switzerland." Maybe with returns? I'll let the engineers figure that out…

Another, probably hackier, direction we could go would be adding a new condition option, "Is in:"
![is in version](https://cloud.githubusercontent.com/assets/2223916/22806866/0f215b32-eed9-11e6-91c7-f1fbaa358828.png)

![is in version - filled](https://cloud.githubusercontent.com/assets/2223916/22806867/138c86b0-eed9-11e6-8de2-085f32fb5702.png)

**Comment by orware** [comment]
This would certainly be useful and would be a good starting point for something like this without too much extra effort on the development side I think and would be particularly useful for the non-technical end users.

Related to this would be having the ability to specify a subquery that provides the list of values to be included. Metabase seems to try and do a bit of connecting with other tables if it can, but that seems to be reliant on what it can figure out from the metadata and maybe some more manual work after that (I haven't looked into this in much detail yet).

Quite often though in our reporting tool that we use (which is primarily evisions' Argos) a lot of our reports have various dropdowns that are populated by other queries and you have to select one or more values before running your report. Obviously if those dropdowns had to be handcoded and manually updated it'd be a pain in the butt for those maintaining the reports for users, but being able to populate them via a query helps make it more maintainable over the long run since generally those dropdowns get updated automatically with that approach.

**Comment by moumny** [comment]
Great i love the mockups ! 
Would be great if we have a widget "IS IN" for dashboard's category filter as well :)

**Comment by mazameli** [comment]
In looking at this again, I don't know if we need a toggle at all. We can just have some helper text indicate that multiple values are allowed, and let the input box grow (up to a max-height) accordingly:

![enhancing is copy](https://cloud.githubusercontent.com/assets/2223916/24024145/47f00412-0a6e-11e7-8176-efcfc63c8593.png)

![enhancing is - expanded copy](https://cloud.githubusercontent.com/assets/2223916/24024147/4af5c372-0a6e-11e7-974f-a565f600146a.png)

**Comment by tlrobinson** [comment]
I think newlines would be better. It's a lot harder to quickly scan a long list of comma separated values (and newlines are less likely to appear in a value)

**Comment by mazameli** [comment]
Hmm. I think the scannability point is most valid when dealing with fewer than 10 or so items, in which case I'd wager you might be typing the values, where separating items by commas feels more common to me (think Gmail) than separating them by hitting `return`. For much longer lists, I think newlines make it _harder_ to scan, particularly in a constrained space like this where you'd have to scroll a lot. We could of course support both/either commas and newlines, but I hear your point about commas being within values (probably relatively uncommon, but not outside the realm of possibility).

**Comment by attekei** [comment]
Implemented in #4577
