### ISSUE TITLE
Options for Variables in Questions/Dashboards?

### ISSUE THREAD

**Issue by orware** [metabase/metabase#4366]
### Feature requests and proposals

I just went through creating a set of questions (# of Student Registrations for the upcoming Spring 2017 term across a variety of time periods...Last 5 Minutes, Last 30 Minutes, Last 1 Hour, etc. up to Last 120 Days). For each time period I created a new question.

Then I added all of them to a Dashboard.

Now let's say in the Fall I'd like to reuse this format/questions.

At the moment I'm not really sure that I'd be able to really quickly?

Yes, we have the option of creating new copies of each question and changing the Term value out for the new one, and then going through the steps of adding each new copy into a new dashboard, but it'd be nice if there was a simple way to do this all at once / more quickly I would think?

This may be related to #1543 and #3575 but may also be slightly different so feel free to merge/close if it's really the same thing.

-------

**Comment by tlrobinson** [comment]
@orware You can parameterize dashboards: http://www.metabase.com/docs/latest/users-guide/07-dashboard-filters You could set the default value for the term to be the spring for now, then change it to the fall in the fall. Or just bookmark the dashboard with the correct range in the URL (`/dash/123?term=spring2017` or whatever).

Note that the (GUI / non SQL) questions themselves should *not* be filtered by term, since the dashboard filter adds, rather than replaces, filters on the questions. SQL questions can have a parameters with a default value.

#1543 is about adding a top-level filter widgets / URL params, like we have for dashboards and SQL cards.

#3575 would let you avoid creating questions "across a variety of time periods", and instantiate multiple instances of the same question with different fixed periods on the same dashboard.
