### ISSUE TITLE
Google Analytics days/months/etc off by one

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4372]
http://discourse.metabase.com/t/problem-with-dates-from-google-analytics-data/1158

Seems like maybe a timezone issue. The backend is returning `2017-01-31T16:00:00.000-08:00` for the month of Feb 2017, and `2017-02-12T16:00:00.000-08:00` for Feb 13, 2017.

Backend timezone is PST, report timezone is US/Pacific (but I don't believe the GA driver uses that for anything?)

**Comment by spanndemic** [comment]
Wanted to confirm this bug, and give some additional findings...

Using the Metabase OS X app version 0.23.1.0 connected to a Google Analytics database with '(GMT-04:00) Eastern Time' timezone set... The Metabase app is also set to the 'US/Eastern' timezone in the admin settings.

I think @tlrobinson is correct in saying that the GA driver does not use the timezone, because changing the timezone in either the app settings or GA view settings does not change the time display in the charts.

If I create this question:

```
{
  "ids": "ga:999999999",
  "start-date": "3daysAgo",
  "end-date": "today",
  "metrics": "ga:users",
  "dimensions": "ga:dateHour",
  "sort": "ga:dateHour",
  "include-empty-rows": false,
  "max-results": 2000
}
``` 

At 6 PM the chart only shows data up until 2 PM, and the data syncs up to the data shown in the Google Analytics dashboard offset by 4:

| Metabase Chart Time        | Google Analytics Time           | Users  |
|:-------------:|:-------------:|:-----:|
| 11:00 AM | 3:00 PM | 24 |
| 12:00 PM | 4:00 PM | 27 |
| 1:00 PM      | 5:00 PM | 31 |
| 2:00 PM      | 6:00 PM      |   25 |

It's interesting that it's off by the same amount as the GMT offset for Eastern time (GMT-04), but in the wrong direction, not sure if that's a clue or not.

Furthermore I've also witnessed the one month offset, similar to above if I do a question by month and compare with Google Analytics, the data is offset by one month (December data is shown in Metabase as November data, etc).

P.S. I love this program!

**Comment by TomUssery** [comment]
We are seeing the same issue with 0.23.1 any idea when this will be addressed? Or do you know of any work arounds for it?

**Comment by VikramTiwari** [comment]
Not sure if this is caused by same issue:

Issue 1: Past 1 week contains 1 extra day

![screen shot 2017-04-17 at 15 04 12](https://cloud.githubusercontent.com/assets/1330677/25106622/57858a3a-237f-11e7-9b54-0154e5f30052.png)

Issue 2: On getting data for past 2 weeks it shifts the date range to today - 2 weeks rather it should give me data for past week and past week - 1 week both.
![screen shot 2017-04-17 at 15 04 00](https://cloud.githubusercontent.com/assets/1330677/25106623/578b0a5a-237f-11e7-8be4-2799cf29e39d.png)

**Comment by KimchaC** [comment]
I can confirm this issue too and I think it is simpler than timezones :)

I setup my search to limit dates between June 6 and 13, but the raw query is:
`{
  "ids": "ga:XXXX",
  "start-date": "2017-06-05",
  "end-date": "2017-06-12",
  "metrics": "ga:users",
  "dimensions": "",
  "include-empty-rows": false,
  "max-results": 2000
}`

So, for some reason the date picker uses the previous date instead of the one selected.

**Comment by senior** [comment]
In the case of the google analytics driver, the Metabase instance really needs to be set to the same timezone as the google analytics backend. In the example above, it appears to be in UTC and the Metabase instance appears to be in the Pacific timezone. The dates are in UTC and then get adjusted by 8 hours, which shifts it to the previous day.
