### ISSUE TITLE
Stacked charts are not available in metabase (supporting JCharts would create vast range of chart types )

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#4386]
Metabase is really limited in chart types. I cannot find Stacked chart for instance or a gauge chart. Is it possible to integrate JChart library into metabase? This enhancement would shift all the charts in metabase really high.

Can we have this enhancement in Metabase?

**Comment by kdoh** [comment]
Hey @alirezastack.

We actually do support stacked charts. Here's an example using the sample dataset we ship with Metabase.

If you hit the gear next to the visualization option in the query builder you can access a range of chart options.
<img width="1397" alt="screenshot 2017-02-15 09 17 48" src="https://cloud.githubusercontent.com/assets/5248953/22986352/1030e7e6-f360-11e6-9c2f-c9fe9c81edbd.png">

Here are the chart settings options I picked to get a stacked bar chart.
<img width="1396" alt="screenshot 2017-02-15 09 17 34" src="https://cloud.githubusercontent.com/assets/5248953/22986290/da3b8998-f35f-11e6-83bf-660fc0bee0bb.png">

As far as "gauge" charts go we offer a similar type we call progress. You can create a progress bar out of any scalar value and add a goals.
<img width="1400" alt="screenshot 2017-02-15 09 18 26" src="https://cloud.githubusercontent.com/assets/5248953/22986393/360ae6c4-f360-11e6-8457-a5152ea2708d.png">

Our general design philosophy is to not overwhelm less technical users with options so that's why they're currently hidden away the way they are but we know they may be a bit too hidden and we're constantly working on improving our charting experience.

Let me know if these options meet the needs you described above.

**Comment by kdoh** [comment]
Hey @alirezastack. I'm going to go ahead and close this since I haven't heard back from you. Feel free to chime in with feedback on the gauge / stacked charts and if there's something actionable we can create a new issue.
