### ISSUE TITLE
Slack/Email Exportation Inconsistencies

### ISSUE THREAD

**Issue by stwonary** [metabase/metabase#43927]
### Describe the bug

There are two issues related to the Slack/Email export functionality:

	1.	Visual Bug: The type of the chart exported to Slack/Email does not match the type specified in the editor. In the editor, I am using a Line chart with a smooth style (as shown in the screenshot). However, the exported chart in Slack appears with hard lines.
	2.	Data Inconsistency: The data displayed in the editor does not match the data exported to Slack. The screenshot clearly shows this discrepancy.

### To Reproduce

1.	Create a Line chart in the editor with a smooth style.
2.	Export the chart to Slack/Email.
3.	Compare the chart type and data between the editor and Slack/Email export.

### Expected behavior

•	The exported chart in Slack/Email should match the Line chart with smooth style as seen in the editor.
•	The data exported to Slack/Email should be consistent with the data displayed in the editor.

### Logs

```
[247d9ff0-ce4d-4eac-98cf-3aad002a9d97] 2024-06-10T10:00:00-03:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[247d9ff0-ce4d-4eac-98cf-3aad002a9d97] 2024-06-10T10:00:00-03:00 INFO metabase.query-processor.card Question's average execution duration is 2.1 s; using 'magic' TTL of 21.0 s 💾
[247d9ff0-ce4d-4eac-98cf-3aad002a9d97] 2024-06-10T10:00:01-03:00 INFO metabase.query-processor.middleware.cache Query took 1.7 s to run; minimum for cache eligibility is 60.0 s; not eligible
[247d9ff0-ce4d-4eac-98cf-3aad002a9d97] 2024-06-10T10:00:02-03:00 INFO metabase.query-processor.card Question's average execution duration is 2.6 s; using 'magic' TTL of 26.0 s 💾
[247d9ff0-ce4d-4eac-98cf-3aad002a9d97] 2024-06-10T10:00:04-03:00 INFO metabase.query-processor.middleware.cache Query took 2.2 s to run; minimum for cache eligibility is 60.0 s; not eligible


```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.153-100.162.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.15 (Debian 13.15-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-05",
      "tag": "v0.49.14",
      "hash": "3606ed3"
    },
    "settings": {
      "report-timezone": "America/New_York"
    }
  }
}
```

### Severity

This issue is blocking our usage of Metabase entirely. 

### Additional context

Data Table:
<img width="374" alt="image" src="https://github.com/metabase/metabase/assets/59780143/ff1ae24d-7215-4317-9a07-c7c26c73e5f0">

Preview Editor:

<img width="324" alt="image" src="https://github.com/metabase/metabase/assets/59780143/3d511c45-ab71-4083-af9c-10ca9f31e36d">

Preview Editor:
<img width="1294" alt="image" src="https://github.com/metabase/metabase/assets/59780143/6ffc96fa-24a3-4480-8a5e-c6500f601488">

Slack Output:
<img width="916" alt="image" src="https://github.com/metabase/metabase/assets/59780143/c1b9e042-2b61-4efe-a7c8-3073982cfb14">

**Comment by adam-james-v** [comment]
Hi @stwonary , thanks for creating this issue.
I've noticed that you're running Metabase 49.
We've put in lots of effort to improve our subscription's visualizations in v50 and these 2 concerns of yours are addressed in that version.

If you're able to update to v50, that will be your best option.

If you need to stay on 49, here are some things you can try to help make your subscription look a bit closer to what you are expecting:

- for each series in the visualization, explicitly set the axis position to 'left':
![image](https://github.com/metabase/metabase/assets/21064735/e640e65d-7012-49aa-9cfb-a5ff7341f693)
- turn OFF the auto split y-axis feature.
![image](https://github.com/metabase/metabase/assets/21064735/2d910228-9028-49be-a9cb-d6bb577ab64e)


These should at the very least make the data look more correct. The reason it appears wrong is (at least in part) related to the fact that in the subscription's render, the Y-axis is being 'auto-split' and has a different scale. Since it's hard to see which series is associated with either axis, the data looks wrong at a glance. You are correct to point out that this is not great, and is why we've made changes in 50!

Since this is addressed in 50, and is fixed alongside a larger set of changes, I'm closing this since the fix won't be in 49. 
I hope you're able to either update or successfully work around the issue!

**Comment by stwonary** [comment]
Hi @adam-james-v, thank you for your response. I can confirm that it is fixed in version v50.

**Comment by adam-james-v** [comment]
Happy to hear that worked for you :)
