### ISSUE TITLE
Metabase Division by zero

### ISSUE THREAD

**Issue by thoughtfuldata** [metabase/metabase#4393]
### Database support
Redshift AWS; Cluster Version: 1.0.1174

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

Your browser and the version: Chrome 56.0.2924.87
Your operating system: macOS Sierra 10.12.2
Your databases: AWS Redshift
Metabase version: 0.22.2
Metabase hosting environment: Azure VM - Ubuntu 14.04 16 Cores 55G Memory
Metabase internal database: Local H2 File
Started with: java -Xms2g -Xmx6g -jar metabase.jar

Suppose we have a table with the following information:

## my_table

| ID  | requests | impressions |
| ---|--------- | ------------- |
| 1   | 0             | 0
| 2   | 0             | 0

When building the following custom expression:

```
SUM(impressions) / SUM(requests)
```

When the divisor is 0 we get the following error: `Error: divide by zero`.
Metabase should be able to construct a SQL query that knows if the divisor is 0 to default the result to 0 instead of throwing an error.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gukras** [comment]
Any news on this? Its a bit basic for this types of application to do cumulative sums, imposible to work with this issue. come on!

**Comment by kevinob11** [comment]
Any news or workarounds on this? We were hoping to move to Metabase for reporting but this makes quite a few of our reports error out.

**Comment by joboyx** [comment]
Any updates on this?

**Comment by joboyx** [comment]
I just found a workaround!

You can use a custom expression something like this:
```
Sum("Calculated Amount") / (Sum("Amount Net") + 0.000001)
```

I've added a very small value to the divisor so that we're not dividing by zero.
Not an elegant workaround but this is better than none.
Not sure also of the smallest value you can add so that you can minimize the inaccuracy.

**Comment by xFixx** [comment]
Another workaround, use sql native queries instead of customs where you can do something like inside code field

`COALESCE(SUM(val) / NULLIF(SUM(devider),0), 0)`

**Comment by kdoh** [comment]
Want to bump / draw some attention to this since I just hit this myself working with a local dataset. We really should handle this more elegantly out of the box. I'm going to reclassify this a bug, not an enhancement since it effectively makes doing a very simple `(A / B) * 100` blow up the query builder if your data has a 0 lurking in A or B. What's even more of a bummer is if you do it and it works but then you change the sort and you're out of luck.
