### ISSUE TITLE
Login doesn't work when adding leading or trailing spaces to email address

### ISSUE THREAD

**Issue by iamkyu** [metabase/metabase#4439]
When I sign in to my metabase account at `/auth/login` page,
I getting an error ‘enter a valid formatted email address’,  if I include white space leading or trailing.
I think removes whitespace from both sides of a string when validate email for login.

#### e.g
- “ test@test.com”
- “test@test.com ”

According to [RFC822 email address validator](http://sphinx.mythic-beasts.com/~pdw/cgi-bin/emailvalidate), leading and trailing spaces are allowed.
But I think it's for some special cases (https://www.w3.org/Protocols/rfc822#z8).

Wikipedia describes (https://en.wikipedia.org/wiki/Email_address)
- a valid address with a leading space
- a valid address with a trailing space

cases are invalid email addresses.

**Comment by salsakran** [comment]
Do you have users with significant trailing or leading whitespace?

**Comment by camsaul** [comment]
I suspect that email validator you found (which looks like it's just from random validator from some random web hosting company's site) is just trimming the leading trailing whitespace from the email you enter. 

If you read RFC 822 it's looks like spaces aren't allowed inside email addresses except in certain cases we're they're quoted

> atom =  1*<any CHAR except specials, SPACE and CTLs>
>
> [...]
>
> When the local-part of an addr-spec must contain a special character, a quoted string must be used. Therefore, a specification such as:
>
>                       Full\ Name@Domain
>
> is not legal and must be specified as:
>
>                       "Full Name"@Domain

So I think the issue here is with the validator you found rather than Metabase itself. Any reason you're trying to including leading and trailing whitespaces in your email address when you log into Metabase?

**Comment by iamkyu** [comment]
@salsakran @camsaul 
so sorry,  I’m not proficient in English. Perhaps I have not expressed myself very well.

1. I joined by an email address (with  no any white spaces e.g “test@metabase.com”),
2. then I try to login the email address with include white space trailing by mistake 
(e.g "   test@metabase.com ").
3. I getting an error ‘enter a valid formatted email address’, if I include white space leading or trailing.

I think it is better to specify the preprocessor (before id validation)  for removes whitespace from both sides of a string.

**Comment by camsaul** [comment]
Trimming the email string sounds easy enough. We should probably do it on the frontend because the API endpoint validates the email address is valid before we would get a chance to trim it. This would be a perfect starter project for anyone interested in contributing. @iamkyu if you're interested in submitting a PR we'd love to have you as a contributor
