### ISSUE TITLE
Big Pivot Tables export breaks or fail silently

### ISSUE THREAD

**Issue by felipe-curebase** [metabase/metabase#44556]
### Describe the bug

While trying to export a pivot table "Download full results" button fails silently without any errors shown (both formatted and unformatted options doesn't work). Metabase is running on Kubernetes on 2vcpu and 8 GB memory. On one try I also got a 502 error and Metabase crashed and restarted (doesn't show in the logs).

### To Reproduce

Pivot table size: 42000 rows
row columns: 5 (300 total rows)
pivot columns: 2 (that expand to 70 columns when pivoted)

### Expected behavior

Pivot table CSV file is exported succesfully

### Logs

Didn't find relevant logs.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.216-204.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v1.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P1

**Comment by perivamsi** [comment]
@felipe-curebase I am sorry for this experience. We will work on providing you a fix as soon as possible.

**Comment by adam-james-v** [comment]
@felipe-curebase , as we work on a fix, if you really need a possible workaround and are staying on 50.6, the .xlsx downloads do not behave the same was as the csv downloads. 
If you can temporarily use .xlsx exports for your needs, you should see the data shape you're used to in those downloads. 

To be clear, we're still working on a proper reversion/fix for the issue, I'm just offering a potential temporary workaround.

**Comment by felipe-curebase** [comment]
@adam-james-v appreciate the quick feedback, thank you. 
I can confirm that I was able to successfully download the file using xlsx format. I was hoping to have a file that has the same formatting that shows up in the screen but looks like the data is not pivoted. 
Also the xlsx file exported looks odd,  it has an additional pivot-grouping column and at the end of the file looks like there are some data that doesn't exist in the source data where some of the pivot columns are empty. maybe because it is calculating permutations of the groupings?

**Comment by adam-james-v** [comment]
@felipe-curebase , yes that's what I expected, and in fact that is how our pivot exports have always behaved.

I'll try to explain a little bit, I know it can be a little confusing :) 

Prior to 50, even the csv downloads would appear in this 'unpivoted' state with the pivot-grouping column and the 'odd' rows at the end (those rows correspond to row/column and grand totals).

Unfortunately, the bug you're reporting here is actually a consequence of a change that tries to address what you expected, which is an export that IS pivoted. The PR for that change is here: https://github.com/metabase/metabase/pull/41668

To understand what I mean, if you create for yourself a much simpler pivot table (that has fewer total rows/columns) and download a .csv of that, you should see something that indeed looks pivoted.

Since our code paths for .csv and .xlsx exports differ, this 'looks pivoted' download was not implemented for .xlsx. 
Instead, this PR: https://github.com/metabase/metabase/pull/43791 is merged into the next minor release and it produces an excel file that:
 1. has the 'unpivoted' rows in 1 sheet and 
 2. a 'native' (real, editable) pivot table referencing said rows in the sheet.

BUT, to set your expectations: because of this issue you've reported, the next minor release will have both csv and .xlsx downloads 'looking pivoted' *disabled*. So, for the time being, if you update to the next minor version (once it's released), your downloads are more likely to succeed, but the data shape will be as you see it in your excel file (not pivoted).

The goal, and in my opinion, proper fix for this issue is not to just revert to the old behaviour indefinitely, but to more gracefully handle the use case of yours, which are quite large pivot tables 

If you play around with smaller pivot tables on your instance, you might find that in many cases things work alright, if you're in the mood to play around a bit ;)

I underestimated the size of pivot tables that users would realistically be using. To be clear, that's not me dismissing the problem, I'm interested in fixing this properly, I'm just acknowledging that you *might* still find success with your current version for some of your other (smaller) pivot tables.

I hope that is a little bit helpful. Please ask any other clarifying questions if you need.
