### ISSUE TITLE
Feature request: Cards with relative change

### ISSUE THREAD

**Issue by brankokovac** [metabase/metabase#4479]
Having cards with relative change like this: https://demo.baremetrics.com would be great.

Basically it would be a number card which would display a value and relative change (percentage) comparing to the same period before. For example: weekly/monthly/yearly profit with a relative change comparing to previous week/month/year.

**Comment by jornh** [comment]
Since this request was raised Metabase has been extended with the *time series x-ray* feature: https://www.metabase.com/docs/latest/users-guide/14-x-rays.html#time-series-x-rays 

Does that visualization work for you guys who 👍 voted this request?

It’s a card you can navigate to interactively - but currently you can’t “pin it” to a dashboard (for more passive/static use).

**Comment by sbelak** [comment]
We've implemented this as "Smart numbers" in 0.31. See blogpost for an example https://www.metabase.com/blog/0.31/
