### ISSUE TITLE
Can not get the minimum or maximum of datetime

### ISSUE THREAD

**Issue by sailxjx** [metabase/metabase#4482]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome

- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10.12.2

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Redshift

- Metabase version: (e.x. 0.19.3)
0.22.2

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
h2

Hi, guys, I can only find the numeric fields in the builder when I chose minimum of, however min(datetime typed fields) is supported in sql editor. Why does this happend?

<img width="599" alt="2017-03-03 16 32 17" src="https://cloud.githubusercontent.com/assets/909853/23544013/f78e9760-002f-11e7-83be-b014c6aeafb2.png">

<img width="661" alt="2017-03-03 16 40 08" src="https://cloud.githubusercontent.com/assets/909853/23544037/1c140cb4-0030-11e7-8450-f8a461f2c22f.png">

Finnaly, thanks for your great job and product.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sksembhi** [comment]
+ 1 need this.

**Comment by emetselaar** [comment]
Would be nice to have this. I use it to create a tile in a dashboard that indicates until when the data is updated. This can be done with SQL, but not all users are allowed to run SQL, so they get "no permission" in that tile.

**Comment by flamber** [comment]
Another workaround is to create a Custom Expression:
![image](https://user-images.githubusercontent.com/1447303/52925303-57ecef80-32f6-11e9-8731-3b736172b0f9.png)

**Comment by Nico-P-FR** [comment]
+1 
I just had this problem today too. Woorkaround solution from @flamber doesn't work, at least in my case, because the date type field are not available, even in custom expressions.

**Comment by vvaezian** [comment]
I created a view where I added another column by converting the date column to Unix timestamp. Since Unix timestamp is a number, the max/min functions work on this field. But the data is shown as a big number and is not very helpful.
On the other hand if in Data Model I set the data type of this column to "UNIX Timestamp", then the data in that column is shown as a date which is nice, but I no longer can apply max/min functions on it.
So I suggest as a feature request: Enabling the max/min functions for fields with the type "UNIX Timestamp". I guess the implementation is easier that the date types in general, because we just need to apply the max/min on the underlying number.

**Comment by lamourj** [comment]
Hey, what's the status on supporting this ?

**Comment by mtthsbrr** [comment]
Using the version v0.35.3 curently the workaround is not working with "date" fields. The editor accepts the column name and also the generated SQL looks fine but when applying the changes in the editor, the field is simply ignored it seems.

![image](https://user-images.githubusercontent.com/49281986/80373422-57a29980-8895-11ea-8788-838c19e86bdb.png)

![image](https://user-images.githubusercontent.com/49281986/80373444-5f623e00-8895-11ea-9f94-81de71f8039e.png)

Any advises?

**Comment by flamber** [comment]
@mtthsbrr Interesting. It seems like it's dropping the Custom Column after clicking Visualize, so the workaround does not work anymore.

**Comment by rafaelsdellama** [comment]
I have the same problem.. Any updates?

**Comment by kenbollen** [comment]
@camsaul any update when this will be fixed? Seems to be open for a long time and has a high vote. Thanks

**Comment by arutama** [comment]
Hi @flamber , is there any foundation or base problem that makes these issues still open? I would like to take a look of what the problem are and see what I could contribute. Any pointer are much appreciate as I am very new to Metabase code.

**Comment by ranandlp** [comment]
Is there any workaround while we are waiting for the fix?

**Comment by flamber** [comment]
There isn't any workaround anymore (besides using SQL), since even if adjusting the Custom Expressions in Simple view after creating temporary (`1 * 1`) expressions in Notebook, then when saving, the fields will be dropped.
Pre-save
![image](https://user-images.githubusercontent.com/1447303/120638238-2c16b900-c470-11eb-8329-c616c959580f.png)
Post-save
![image](https://user-images.githubusercontent.com/1447303/120638418-5f594800-c470-11eb-82db-d28c022d1c2a.png)

**Comment by sconstantini** [comment]
Hey there.
I've been looking after a solution for finding minimum or maximum datetime values.
Turns out there's a simple solution you can do via "Custom Column".

1) Edit your question
2) Create a custom column
3) Select the column you wanna find the lowest or highest date value and multiply and divide by 10, for example:
![image](https://user-images.githubusercontent.com/38232597/125123813-8b9a6100-e0cd-11eb-9321-759bc8ed88ff.png)

4) Apparently, if your original column was a Datetime, it will convert to a value type, with the "YYYYMMDD", which is now ready to summarize by min or max, amongst other or combined summarizations:
![image](https://user-images.githubusercontent.com/38232597/125124254-2dba4900-e0ce-11eb-903d-e9f4f3cb9a5b.png)

Hope this helps

**Comment by ranandlp** [comment]
I get an error when I attempt this with Snowflake:

`SQL compilation error: error line 1 at position 279 Invalid argument types for function '*': (TIMESTAMP_NTZ(9), NUMBER(2,0))`

**Comment by felici1b** [comment]
Same error with PostgreSQL :
`ERROR: operator does not exist: timestamp with time zone * integer Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
`

**Comment by flamber** [comment]
There's now a workaround for this. Only tested 0.40.5 and master: https://github.com/metabase/metabase/releases/latest

Example:
1. Custom question > Sample Dataset > Products
2. Custom Column `[Created At]` as "CustomColumn"
3. Summarize "Minimum of CustomColumn" and "Maximum of CustomColumn", grouped by Category
![image](https://user-images.githubusercontent.com/1447303/134905030-840e3aff-8b3a-4f8c-9fb8-10f3ad56f7fe.png)
4. Result:
![image](https://user-images.githubusercontent.com/1447303/134905079-218d3a1a-0700-4aeb-87ce-5345b93d1837.png)

----

It's even possible to work with strings similar to `First()`/`Last()` functions.
Example:
1. Custom question > Sample Dataset > Orders
2. Custom Column `[Product → Category]` as "CC"
3. Summarize "Minimum of CC" and "Maximum of CC", grouped by CreatedAt:Day
![image](https://user-images.githubusercontent.com/1447303/134906768-5e6664e8-d0ea-4693-85e0-1aadb61a6c16.png)
4. Result:
![image](https://user-images.githubusercontent.com/1447303/134906904-9f3080a5-5e0d-4fb7-8d5c-33729c0d7608.png)
