### ISSUE TITLE
Unclear Error Message When Using Offset in Custom Column

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#45327]
### Describe the bug

If you try to use the offset() function in a custom column you receive the error "OFFSET is not supported in custom expressions". 

### To Reproduce

1. Open Metabase v50.10
2. Create a Question on the sample DB
3. Try to write a basic offset in a custom column

### Expected behavior

I believe this should say "OFFSET is not supported in custom columns."

You can/should use it in a custom expression in the summarize box.

### Information about your Metabase installation

```JSON
v50.10
```

### Severity

annoying / unxclear

**Comment by calherries** [comment]
@kamilmielnik I've triaged this to your team because it looks related to https://github.com/metabase/metabase/pull/43224. 

The message is coming from metabase.lib Clojure code here:
https://github.com/metabase/metabase/blob/ab3eff95d7488ec3759f3282951a422f78060770/src/metabase/lib/expression.cljc#L486-L488

Looks like you made the latest changes to this message
