### ISSUE TITLE
Snowflake RSA Private Key stored in /tmp directory on single node in load balanced setup

### ISSUE THREAD

**Issue by troyharvey** [metabase/metabase#45393]
### Describe the bug

When using a local file for the Snowflake RSA Private Key, the key should not be stored in a `/tmp` file. This breaks when running Metabase in load balanced mode where the private key is only available on the node where the connection was originally created.

### To Reproduce

Run Metabase in load balanced setup with multiple nodes/pods. Create a Snowflake database connection using a local private key. Attempt to query Snowflake. You'll see this error if you are serviced by a pod that doesn't have the `/tmp` private key file.

```
Private key provided is invalid or not supported: /tmp/metabase-secret_5371015221724238340.tmp: null
```

### Expected behavior

If possible, it would be good to bypass the `/tmp` file pointer to the private key. If you look in the contents of `/tmp/metabase-secret_5371015221724238340.tmp` it's just a file path to the private key not the actual contents of the key.

### Logs

Private key provided is invalid or not supported: /tmp/metabase-secret_5371015221724238340.tmp: null

### Information about your Metabase installation

```JSON
Metabase 1.50.11. Postgres backend. Snowflake data warehouse. Running on EKS with 3 pods.
```

### Severity

Blocking us from using Snowflake as a Pro customer

**Comment by troyharvey** [comment]
Thanks for working on this @escherize! If you need to hop on a call for me to demonstrate or have any questions just let me know. Fellow Escher fan 🙌

**Comment by escherize** [comment]
Hey Troy, I am going to have a fix for this out soon. In the meantime there is a quick fix that while not ideal should have your snowflake connections working again.

If you are able to put the file containing your RSA Key on each cluster at the same path, then that should sidestep this issue.

Another quick fix would be to upload the key instead of using a local one, if you tried that and it didn't work can you give me some more info?

**Comment by troyharvey** [comment]
Hey @escherize! Checking in to see if there are any updates on this one.

**Comment by perivamsi** [comment]
Moving this to QPD after discussion with Bryan

Here's a doc Bryan wrote summarizing the current state: https://www.notion.so/metabase/Snowflake-RSA-Key-HA-setup-secrets-a9c53a10ffb443969a0f783387027a8d

**Comment by perivamsi** [comment]
@troyharvey we don't have a fix for this yet, sorry. will keep you posted.

**Comment by dpsutton** [comment]
I've got some news.

Everything works as expected with passwords, and with upload files (please confirm or dispute). I can recreate this locally in a cluster. 

The great thing is I can recreate this locally _without a cluster at all_. And it's because there's nothing special about the "other" instances. Restarting a single process is enough to make it behave as a second instance in a cluster.

The gist is that we memoize some information when you point it to the local file. We correctly check that we can connect and that information stays around. 

I suspect it's in this function that we memoize

```clojure
(def
  ^java.io.File
  ^{:arglists '([{:keys [connection-property-name id value] :as secret} & [driver? ext?]])}
  value->file!
  "Returns the value of the given `secret` instance in the form of a file. If the given instance has a `:file-path` as
  its source, a `File` referring to that is returned. Otherwise, the `:value` is written to a temporary file, which is
  then returned.

  `driver?` is an optional argument that is only used if an ostensibly existing file value (i.e. `:file-path`) can't be
  resolved, in order to render a more user-friendly error message (by looking up the display names of the connection
  properties involved).

  `ext?` is an optional argument that sets the file extension used for the temporary file, if one needs to be created."
  (memoize/memo
   (with-meta value->file!*
     {::memoize/args-fn (fn [[secret _driver? ext?]]
                          ;; not clear if value->string could return nil due to the cond so we'll just cache on a key
                          ;; that is unique
                          [(vec (:value secret)) ext?])})))
```


In the cluster setup, when it was "good" (on the machine that configured the db connection):

```clojure
snowflake=> (let [details (:details (toucan2.core/select-one :model/Database :id 3))]
              (select-keys (sql-jdbc.conn/connection-details->spec :snowflake details) [:private_key_file :connection-uri]))
{:private_key_file #object[java.io.File 0x31bebf2a "snowflake.key"],
 :connection-uri
 "jdbc:snowflake://host?user=USER&private_key_file=%2Fapp%2Fsnowflake.key"}
```

On the other instance in the cluster i see

```clojure
snowflake=> (let [details (:details (toucan2.core/select-one :model/Database :id 3))]
              (select-keys (sql-jdbc.conn/connection-details->spec :snowflake details) [:private_key_file :connection-uri]))
{:private_key_file #object[java.io.File 0x60d9f23a "/tmp/metabase-secret_4021735193230304791.tmp"],
 :connection-uri
 "jdbc:snowflake://host?user=USER&private_key_file=%2Ftmp%2Fmetabase-secret_4021735193230304791.tmp"}
```

but you can recreate this in a regular dev setup by configuring a local file path, seeing the query succeeds, restarting the process, and seeing that the query fails.

I would check the differences in what happens in `defmethod driver/can-connect? :snowflake` and `defmethod sql-jdbc.conn/connection-details->spec :snowflake`. My guess is that we changed how secrets work and never updated the snowflake implementation, just the stuff in the core app.
