### ISSUE TITLE
Allow sorting by error type

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#45552]
Discussion here: https://www.notion.so/Query-Validator-d481e94b9f8c49deb1d8c83b0a6de9d6?d=58b964609ee542a3a8fc8dbbdbf2322f&pvs=4#139106dd91a74104b520bb671345b14a

**Comment by crisptrutski** [comment]
Since we currently group by card, and each card can have multiple error types, it's unclear how this ordering would work. While it makes sense as a secondary ordering, that doesn't seem that useful. We could "ungroup" by card when sorting this way, but that seems a bit surprising and complex.

Additional notes related to the  linked thread:

- We would either need to sort in-memory (I don't think this is OK), or rework our two-phase (get cards, get errors) approach. The latter means widening the interface between the webapp and BEC modules, and making it more complex.
- The backend uses error codes rather than messages, which the frontend renders into text. We may want to sort by the rendered messages, so we'd need to move that mapping to the backend and ideally push it down into the database query.
