### ISSUE TITLE
Metabase v0.50.1+ doesn't work on Safari 15.2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#45647]
### Describe the bug

Safari refuses to load the app because of an unsupported regex syntax. Works on chrome. No issues with 0.49.20.

### To Reproduce

1. Download `0.50.1` jar
2. Run it
3. Open the app in Safari
4. Open the browser console and see the error

<img width="1727" alt="Screenshot 2024-07-16 at 10 39 34" src="https://github.com/user-attachments/assets/898db501-2ced-433b-a3d8-33410ad48386">

This line causes issues https://github.com/metabase/metabase/blob/08613cb3b64f87eb1260c3a1eb5f918632dff156/frontend/src/metabase/admin/performance/utils.tsx#L128

### Expected behavior

It should work as before.

### Information about your Metabase installation

```JSON
- Metabase 0.50.1
- Safari 15.2
```

### Severity

P1

**Comment by iethree** [comment]
there's more than one offending regex here, found another one in our CLJS code

https://github.com/metabase/metabase/blob/0293ce541f905996cbc56ccf1c97e1bed9a808fc/src/metabase/legacy_mbql/util.cljc#L346

![Screen Shot 2024-07-17 at 3 16 08 PM](https://github.com/user-attachments/assets/22f05a57-b4ed-4338-8aa0-bde1c2c988b3)

@bshepherdson do you think you can rewrite these regexes to not use lookbehind so that we can support safar < 16.3 ?
https://caniuse.com/js-regexp-lookbehind

**Comment by lbrdnk** [comment]
Closing as FE and also cljs PRs were merged and backported.
