### ISSUE TITLE
Dashboard Boolean Filter Values Sent as String On Page Load, Boolean on Filter Value Change

### ISSUE THREAD

**Issue by adam-james-v** [metabase/metabase#45670]
### Describe the bug

In a Dashboard, if you have a Filter connected to a Card with a Boolean Field Filter in its (native) query, when the dashboard first loads, the paramter value is sent as a string eg. "true", which causes the query to fail.

If you then change the filter, the value is sent as a boolean `true` or `false`, or `[true, false]` when selecting both. In this case, the query succeeds.

NOTE: this may only apply to Postgres dbs, I haven't double checked that.

Initial dashboard load:
![image](https://github.com/user-attachments/assets/858febcd-a9c7-4106-9f91-cc20e5e14b95)

And after changing the filter's value:
![image](https://github.com/user-attachments/assets/09d111f0-ab1d-4981-aba5-7aa72f503129)

### To Reproduce

1. Set up a field filter on a card, where the field in question is a boolean field.
2. Add this card to a dashboard
3. Create a drop down list filter, link it to the field filter on the card, set default value to true (or false, just set it)
4. Save dashboard, and refresh.

Here is a dashboard on stats with the setup:
https://stats.metabase.com/dashboard/2520-boolean-field-filter-test-dashboard?text=true

### Expected behavior

The query should succeed. As I see it, this means either the frontend should send booleans, not strings OR the backend should permit stringy booleans and work nicely, not sure if that's in endpoints, in QP, or in drivers.

I think that things are a little confusing here because to get the filters, we're using a 'Category' filter type, which is clearly meant to work on lists of string values, not really booleans.

### Logs

The relevant error message from `POST /api/dashboard/:dashboard-id/dashcard/:dashcard-id/card/:card-id/query`:
```
ERROR: operator does not exist: boolean = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 197
```

### Information about your Metabase installation

```JSON
- Firefox
- Postgres
- Master: f961d4f
```

### Severity

P2

**Comment by nemanjaglumac** [comment]
To be able to reproduce this, both the native question filter and the dashboard filter **must be** required.
It is also true that it is not reproducible on H2. Use Postgres (data warehouse, not app db) for that.

Related #45877
Filter will render the option twice but this time because it stores one option as a string, and the other one as a boolean.
![image](https://github.com/user-attachments/assets/cef372ca-fd45-4cc7-b398-e76b78f69d3a)

**Comment by nemanjaglumac** [comment]
This is happening only on the first page load (including when we visit the dashboard and set the link directly through URL query params).

The problem is that the `dashboard` is still not in the `state` at that point so we have to rely on parsing the URL query parameters. This is why frontend sends the value as a string.
```js
const parameterValuesById = preserveParameters
  ? getParameterValues(getState())
  : getParameterValuesByIdFromQueryParams(
      result.parameters ?? [], // no fields
      queryParams,
      lastUsedParametersValues,
    );
```
The logic starts from this "lovely" thunk:
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/actions/data-fetching-typed.ts#L32-L193

In order to "build" (set) fields, we need to use `getDashboardUiParameters`, and for that we need the dashboard in the state. And we need fields in order for this condition to be met:
```js
const { fields } = parameter as FieldFilterUiParameter;
if (Array.isArray(fields) && fields.length > 0) {
  return parseParameterValueForFields(coercedValue, fields);
}
```

`parseParameterValueForFields` is dealing with converting string values to booleans:
```js
if (fields.every(f => f.isBoolean())) {
  return value === "true" ? true : value === "false" ? false : value;
}
```

One potential (hacky) solution that @ranquild proposed is to delay setting the parameters while we dispatch the action to set the dashboard in state.

For the posterity, the original Slack discussion is [here](https://metaboat.slack.com/archives/C0645JP1W81/p1724338292252369).
