### ISSUE TITLE
Column names with special characters are created with encoded characters

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#45689]
### Describe the bug

I don't know why it happens with only this file and not if I generate a new one

### To Reproduce

1) just import this as a CSV
[colegios_alumnos_activos.csv](https://github.com/user-attachments/files/16257255/colegios_alumnos_activos.csv)

### Expected behavior

we should not create columns with special characters

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

**Comment by bshepherdson** [comment]
This file is not encoded in UTF-8, and I suspect that's why it's getting mangled.

`Dirección` is encoded as (hex) `44 69 72 65 63 63 69 f3 6e`. The trouble is that the `ó` is encoded as `0xf3`, which is correct **extended ASCII** (ISO 8859-1, aka Latin-1). But I suspect we're trying to ingest it as UTF-8, which would fail to decode correctly.

`f3` (`1111 0011`) looks like the start of a 4-byte character (U+010000 to U+10FFFF), beginning with `0 11__ ____ ____ ____`.
The three further bytes should all start with `10__ ____`, but they don't - the next byte is `n = 6e = 0110 1110`.

**Comment by bshepherdson** [comment]
@paoliniluis I'm not sure what the Right Thing for Metabase to do here is. Do we document the input formats we expect? Should we be rejecting encodings we can't understand with an error message?

**Comment by paoliniluis** [comment]
the issue here is that we end up trying to insert encoded characters... there has to be a way in which we can enforce utf-8

**Comment by crisptrutski** [comment]
We are inserting valid utf-8, the problem is on the read side. This file is in `ISO-8859-1`, which hopefully we can detect with the same library that we're using to detect the mime-type. Should be an easy enough fix, will look at this today.
