### ISSUE TITLE
Query Cache Environment Variables Ignored in v50

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#45886]
### Describe the bug

In version 50, using environment variables to set default query cache values doesn't work.

### To Reproduce

1. Set up Metabase v50+ with the following environment variables:

MB_ENABLE_QUERY_CACHING=TRUE
MB_QUERY_CACHING_MIN_TTL=5

2. Navigate to the performance tab in Admin Settings and note that there are no references made to the environment variables having been set
3. Connect to a Postgres sample DB
4. Create a question with the query "SELECT pg_sleep(10);"
5. Note that no cache is created for the question in the "query_cache" table

You can manually enable cache from the performance tab and rerun the pg_sleep query to see that it will generate a cache if the cache is configured manually. If you already have a Snowflake connection set up you can also test this with "SELECT SYSTEM$WAIT(5);" .

### Expected behavior

The environment variables should be respected

### Information about your Metabase installation

```JSON
v50.13
```

### Severity

Not fun for self hosted folks managing these settings programmatically.

**Comment by luizarakaki** [comment]
This is a breaking change from v49, because the caching system evolved significantly on v50.

Now, there are 3 available policies: `ttl`, `schedule`, and `duration`.
There is a new API endpoint to configure cache: https://www.metabase.com/docs/latest/api/cache

`MB_QUERY_CACHING_MIN_TTL` was removed on v50. We are verifying why they are still in docs.
