### ISSUE TITLE
Can't set variable as field name

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#4610]
- Your browser and the version: Chrome 55.0.2883.87 (64-bit)
- Your operating system: Ubuntu 16.04
- Your databases: Postgres
- Metabase version: v0.23.0
- Metabase hosting environment: Ubuntu 12
- Metabase internal database: Postgres

Before the 0.23.0 update I was able to make queries using this syntax:

`select 1 as {{variable}}`

![metabase_error](https://cloud.githubusercontent.com/assets/982190/24297543/ebd6e3d4-1081-11e7-955d-d6d8a9aab1ae.gif)

Now I can't. I don't know if there is another way to make this work.
It was really useful.

-- edit --
This was the correct syntax:
![metabase_error](https://cloud.githubusercontent.com/assets/982190/24297942/413bf5de-1083-11e7-9ba6-ced47f6cf05a.png)

**Comment by mazameli** [comment]
Is this possibly related to or a dupe of #4545?

**Comment by salsakran** [comment]
Yeah. We're basically not letting you inject SQL tokens into templates any more. This was a huge security hole, and in closing it we've unfortunately limited what you can do with sql templates.

**Comment by salsakran** [comment]
@sabino are you trying to have the alias for a given column be entered by the end user? Or was this a simple example of things that are broken.

To re-iterate, while we're not going to allow open-ended sql injection, we are going to create a new set of template tags that will hopefully allow you to do what you are trying to do. It would be great if you could tell us more about the specific way you were using template tags.

**Comment by salsakran** [comment]
Hey @sabino -

First off, really sorry for the mess you've been dealing with. We didn't expect quite so many people to be using sql parameters in as many creative ways. We also think some of this was due to the weakness of the input options for number/date/string filters, and the lack of date filters equivalent to the dashboard filter widgets.

We've just released 0.23.1, which will hopefully remove a bit of the pressure. You can now take a field-based filter clause, and assign it a filtering widget, just as if it were a dashboard.

You'll be able to do things like filter by last 7 days, etc without your end users need to remember the formats or typing.

We're also going to be extending the template language over the next couple of versions in response to any other uses you were finding for the old style completely freeform template variables.

We really want to un-muck this up for you, but like I said, SQL injection attacks are a real worry of ours and we're going to try to do so in a type-safe way.

**Comment by sabino** [comment]
@salsakan Yes, basically we had some questions and dashboards that would show the column name as the user input. We had to change things a little bit but no worries.

You guys are doing a rock solid work here and I completely understand the SQL injection threat.

Can you tell me more about the field-based filter clause? Couldn't find anything about it other than the release notes but I couldn't understand what has changed/how to use it.

We had to create some views to achieve this result but, a nice thing to do would be create a Field Filter by using a query (or a question), that way I could limit the distinct possible values. But that's another thing.

**Comment by mazameli** [comment]
> Can you tell me more about the field-based filter clause? Couldn't find anything about it other than the release notes but I couldn't understand what has changed/how to use it.

Documentation for field-based filter clauses is on the SQL parameters doc page, under the `Defining Variables` section: http://www.metabase.com/docs/latest/users-guide/12-sql-parameters.html

The main thing that's changed about them is that, previously, they were used primarily as a way to let you use dashboard filters with SQL questions; now, you can use them to create filter widgets on the SQL question itself.

**Comment by sabino** [comment]
Thank you @mazameli :+1:

**Comment by flamber** [comment]
Closing in favor of #4545
