### ISSUE TITLE
We keep the "you've made changes to permissions" bar on top after we pressed "save"

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#46170]
### Describe the bug

FE state bug in 50.16. change the permissions and the bar will still be there
![image](https://github.com/user-attachments/assets/55d5e9a6-fbba-4fae-b8da-db242b9223d6)

### To Reproduce

1) add a database, probably with many schemas. 
2 Do a lot of changes at the same time (e.g. block all users, then jump into a schema and do granular stuff)
3) press save, see the bar still there

### Expected behavior

The bar should dissapear after the api call and a 200 status code

### Logs

NA, as everything ends fine, but the bar stays there

### Information about your Metabase installation

```JSON
v50.16
```

### Severity

P2

**Comment by iethree** [comment]
Unable to reproduce on 50.16 or on 17f64439966227756b4080934a6bb70a8f917307

**Comment by sloansparger** [comment]
Can confirm that I fixed this in v50.20 by #46509.

Reproduction steps:
- remove all permissions from all columns permissions columns for all databases for a group
- hit save

v50.16 will maintain the save button at the top, v50.20 (with the fix) will remove it

Background context:
The BE was sending no info back for this group since all values were set to the default. The FE merges in updates for the modified groups into it's state, but was doing updates for each group present in the response. The fix just makes sure that we use the groups that were modified in the request instead.
