### ISSUE TITLE
When using API keys, we use a lot of CPU time for cryptographic operations

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#46358]
### Describe the bug

Something I just discovered doing load testing: when using API keys, there's a lot of CPU time for crypto operations, which doesn't happen if you're using a normal session token. The load was so big that it was using all the cpu's for a small amount of users

### To Reproduce

1) do a load test with an api key
![image](https://github.com/user-attachments/assets/630d3529-206f-4ee2-a746-01f6e6a837df)

### Expected behavior

It shouldn't be this hard for the CPU

### Logs

NA

### Information about your Metabase installation

```JSON
v49.x
```

### Severity

P2

**Comment by darksciencebase** [comment]
from @dpsutton 
>this is by design and necessary.
When a user logs in once, we don’t compare their password to a copy of it in the db, we do some cryptographic work on it and compare that. The point is that we don’t have a copy of a way to become that user. You must know it.
Once proven that the password hashes to what we have in the db, we give them a once time token that we compare for equality. This does live in the app-db (in the session table) but new ones are generated on each login.
For an API key, there’s no negotiation like this: the key must always work. So there are two options for how this can work:
Generate a token and compare that to the database each time. This is really quick: just fetch the db and compare two strings. The problem here is that anyone with db access can act as that user in our system.
Have keys in the headers, but require them to go through the same hashing work that happens when a user logs in but do it on every API request. We do this work here.
The consequence of this is that we are doing the work of a login on every request.
