### ISSUE TITLE
Row charts don't display date labels in nice format

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4672]
They're displayed in full timestamp format instead, like this:

![screen shot 2017-04-03 at 10 39 35 am](https://cloud.githubusercontent.com/assets/2223916/24622463/ff0ec676-1859-11e7-9e2b-c638a59d66ed.png)

**Comment by flamber** [comment]
Hi @mazameli 
I guess this was fixed by all the formatting changes in 0.31, but now seeing other problems in 0.31.2:
Do you want to close this and create a new issue with the list below - or just rename this?
- Hover makes it almost impossible to read the date
- Date formatting has no impact on the row, only on the tooltip
- And then it also includes regular browser tooltip (`title` attribute)
![screenshot 2019-02-13 22 43 37](https://user-images.githubusercontent.com/1447303/52763364-0c2e0380-2fe1-11e9-8465-c2f20ac038fb.png)

**Comment by oBoMBaYo** [comment]
@flamber #12185

**Comment by flamber** [comment]
Closing this in favor of #12523
