### ISSUE TITLE
Migrating down from 48 to 47 reruns all the migrations from the beginning

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#47232]
### Describe the bug

Seems that we're trying to re-run all migrations when downgrading

### To Reproduce

1) Start in staging a v50
2) then migrate down to v47
3) see that the core_user table wants to be re-created (since it's running from the beginning

### Expected behavior

It should work and not try to re-create all the tables

### Logs

Check the logs of cynthiastaging47 in staging

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1

**Comment by qnkhuat** [comment]
#caused by #34400

This broke 48->47, **but** only if the instance starts from >= 48.
So if you go 47->48->47 then it’s not a problem.

The reason for this is that #34400 was introduced in 48, and from that point, any new instance will run an “init” migration “00.00-000" where its contents basically are migration from v0 -> v45.
So if you downgrade from 48 to 47, these v0->v45 migrations does not exist, so that’s why it was trying to run all of them again.

To fix this, we’ll need to and make sure the  databasechangelog for instances from >=48 is a record for all the migrations from v0->v45 that we skipped.
