### ISSUE TITLE
The custom datetime columns are automatically truncated by day when aggregated

### ISSUE THREAD

**Issue by Jerrylovescoding** [metabase/metabase#47341]
### Describe the bug

The custom datetime columns in MySQL and StarRocks are automatically truncated by day when aggregated whether using functions convertTimezone() or datetimeAdd().

![image](https://github.com/user-attachments/assets/7fb09ab7-30b7-47ea-a682-8f1b2bb82a77)

P.S.
The data types of columns are datetime in db and displayed on metabase like this:
![image](https://github.com/user-attachments/assets/f4c05680-1aa8-4cbc-b999-4314d31f814a)

### To Reproduce

-

### Information about your Metabase installation

```JSON
* Browser: Chrome 128
* OS: CentOS 7
* Databases: MySQL, StarRocks
* Metabase version: v0.50.22
* Metabase hosting environment: Docker
* Metabase internal database: PostgreSQL
```

### Severity

Medium

**Comment by zbodi74** [comment]
Replicated, and also happens on PostgreSQL. 
Raising priority as this is a regression in a common function.

**Comment by bshepherdson** [comment]
Some data points across versions for reference:

| Version | Breakout on Field | Breakout on custom column |
| :-- | :-- | :-- | :-- |
| 0.49.20 | Explicitly bucketed, defaults to `day` | No bucketing visible; unbucketed output |
| master | Explicitly bucketed, defaults to `month` | No bucketing visible; appears to silently bucket by `day` |

In both cases the breakout on the custom column is spelled `[:expression "NY Date" {:base-type :type/DateTime}]` and doesn't specify a `:unit`.

I'm debugging further to find out where the unit is coming from.

**Comment by zbodi74** [comment]
Reopening as it works properly when binning is specified, but there is still a `date` cast when the column is not binned. I checked this in `1.50.24.2`.

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/5a6a6efc-72f3-4c41-b6c8-5222cb9452c1">

**Comment by bshepherdson** [comment]
This was an intended change, making breakouts on expressions work like breakouts on fields.

## Background

In 0.49.20, breakouts directly on fields defaulted to bucketing by day. Even if you selected `Don't bin` it would still be forced to `:day` by the [`auto-bucket-datetimes` middleware](https://github.com/metabase/metabase/blob/release-x.49.x/src/metabase/query_processor/middleware/auto_bucket_datetimes.clj). If you didn't want to bucket it, you could create a basic expression instead, since those didn't support bucketing in 49.

Bucketing for `:type/Date` and `:type/DateTime` expressions was added to the BE by #45492 and FE by #47427. So as I say, this is an intentional change.

## Intended?

In practice, there's no way to force bucketing off for a `Date(time)`-valued breakout. Both fields and expressions are auto-bucketed. We show a `Don't bin` option in the UI, but it gets represented by **omitting the `:temporal-unit` option**, which then gets defaulted to `:day`. There's no way for the BE to distinguish between "unset" and "deliberately turned off", right now; I think that is a bug but it's also been around forever (for fields).

As a workaround, you can bucket by `:second`, which is probably sufficiently unbucketed for most purposes.

@zbodi74 and @mngr for comment.

**Comment by mngr** [comment]
@ranquild Why don't we show explicitly the binning by day here? 
![image](https://github.com/user-attachments/assets/909e6b24-4bbb-4fd9-8cd1-703c36f8acaa)
