### ISSUE TITLE
The latitude and longitude columns whose data types are decimal in StarRocks cannot autobin when aggregated

### ISSUE THREAD

**Issue by Jerrylovescoding** [metabase/metabase#47387]
### Describe the bug

All of latitude and longitude columns whose data types are decimal in StarRocks cannot autobin when aggregated, even though I specify the specific data type Latitude or Longitute in metabase backgroud.
![image](https://github.com/user-attachments/assets/e268f610-4c22-48ba-a46c-61422c35a8e3)
![image](https://github.com/user-attachments/assets/f622bee2-4e83-448f-96f6-69f6c38a7307)

I feel like that's because the fingerprint field in metabase_field table is null. Is the mechanism of fetching fingerprint values related to the database_type field in metabase_field table or to something else?
![image](https://github.com/user-attachments/assets/cb4fd434-2b52-4168-b4c2-a2006a479ce2)

### To Reproduce

-

### Information about your Metabase installation

```JSON
- Browser: Chrome 128
- OS: CentOS 7
- Databases: MySQL, StarRocks
- Metabase version: v0.50.22
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL
```

### Severity

Medium

**Comment by alxnddr** [comment]
Hi @Jerrylovescoding 👋 We do not provide an official StarRocks driver so it seems you are using their third-party driver. Since this functionality works with the official drivers, I assume the problem is in the StarRocks driver implementation. It is better to reach out to the team that developed the StarRocks driver about this problem
