### ISSUE TITLE
Auto-wire up dashboard field filters

### ISSUE THREAD

**Issue by dtheodor** [metabase/metabase#4767]
I'm building dashboards that contain several filters (field filters on DB fields), and finding myself constantly repeating the same manual procedure:

1. Add a dashboard filter, name it like the db field I am about to filter on
2. For each of my charts: click on the filter dropdown, select the db field (it's the exact same db field for all the charts)

I have to do this for 8-10 filters for 10-15 charts, it feels plenty of unnecessary work. (It also isn't possible to re-arrange filter order so right now I have to drop and re-create filters in the right order which takes forever)

I think this should be done automatically by metabase: When I create a category filter, I could hint at which DB field this filter will be about; then metabase can automatically give the DB field name to the filter, and pre-select the db field in all charts where it is contained

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Here's what I'm thinking for this feature:

**Add a new filter (nothing new here)**

![03 add filter menu](https://user-images.githubusercontent.com/2223916/30301028-eda61bbe-970c-11e7-93a7-c8c22e54c452.png)

**Pick its type (nothing new here either)**

![04 time filter sub-menu](https://user-images.githubusercontent.com/2223916/30301037-f5138bc0-970c-11e7-8d15-769fc5cd8716.png)

**I'm still working on the text for this, but I thought it might be useful the first time a user adds a filter to give them a little heads up about what's about to happen:**

![05 connect filter to cards](https://user-images.githubusercontent.com/2223916/30301044-ff751bce-970c-11e7-98d5-a0cff1751f28.png)

**The new filter is automatically mapped to each card on the dashboard. For every filter type other than Category, we can just grab the first valid field matching the filter's type. If none match, we'll just do what we already do when there are no valid fields.**

**Also, while in this state, it would be smart to disable the other action buttons in the top-right, until the user clicks the Done button on the filter.**

![06 map filter to cards](https://user-images.githubusercontent.com/2223916/30349121-aa10db0e-97c6-11e7-8fa3-5089ba53baa8.png)

**As @dtheodor described, Category filters are a little trickier, and one way we could approach them is by asking the user to give their new Category filter a label:**

![09 category filter labeling](https://user-images.githubusercontent.com/2223916/30348958-0728b2cc-97c6-11e7-8d8b-9941012b0c30.png)

**In this example, I'm naming my filter `Color` because I want to filter on the color of my food:**

![10 category filter labeled](https://user-images.githubusercontent.com/2223916/30349009-32ea203a-97c6-11e7-91a4-db2c2251ead3.png)

**Because I named it `Color`, Metabase can look for fields that contain or match that string. If we can't find a good guess, we can just degrade to the unselected dropdown.**

![11 automapping based on label](https://user-images.githubusercontent.com/2223916/30349054-63c1c988-97c6-11e7-9e8a-ddfb4173643d.png)

**Comment by mokra** [comment]
@mazameli Category filters - may be one could add a property "filter type" (contains, equals) directly to individual cards?

**Comment by janmpeterka** [comment]
Would really like to see this, seems like a must-have.

Have some other idea on functionality:

1) Filter can have set default table->column to link with
- possibly after I connect one, I can in filter setting set it as default?
- or just select it manually from a) all tables or, smarter b) from tables->columns used in my dashboard

or

2) It could automatically link cards based on the first one set
_this would only work if I add one question, set filter, and start adding other. Sometimes I want to add all questions before adding filters, but doesn't seem like that big issue to me._
