### ISSUE TITLE
Sorting does not work for numerical results - Google Analytics

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4811]
- Your browser and the version: Chrome 57.0
- Your databases: Google Analytics
- Metabase version: 0.23.1

- *Repeatable steps to reproduce the issue*
Query for GA data and then try to sort on numerical columns. One example of query is:

`View: Users` `grouped by: Campaigns`, sorting on result's users columns does not work and gives following error in console.
![screen shot 2017-04-18 at 17 05 35](https://cloud.githubusercontent.com/assets/1330677/25157920/450f96fe-2459-11e7-842d-9b8297866c3a.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by lawrencedudley** [comment]
So... interestingly, turning it into a native query and then sorting, like this works:

`{
  "ids": "ga:75306573",
  "start-date": "7daysAgo",
  "end-date": "yesterday",
  "metrics": "ga:pageviews",
  "dimensions": "ga:pagePath",
  "sort": "-ga:pageviews",
  "include-empty-rows": false,
  "max-results": 25
}`

So that would suggest this is a GUI issue.

**Comment by apostoltego** [comment]
Are there any updates on this one? It's quite problematic for end users trying to explore GA data

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
