### ISSUE TITLE
Colors of series change randomly on bar and area charts

### ISSUE THREAD

**Issue by aronri** [metabase/metabase#4814]
I have 2 charts on a dashboard (both bar charts, stacked) in which the series keep changing colors randomly. The same happened with an area chart.
The colors change regardless whether I look at the card or the dashboard. They don't change instantly after the first reload, but a few hours later they do.

I haven't seen this issue here yet.

details:
Google Chrome, Version 57.0.2987.133 (64-bit)
OS X Yosemite 10.10.5
MSSql database
Metabasev0.23.1

**Comment by flamber** [comment]
Hi @aronri 
I've tried to reproduce your issue without success on 0.31.2 - could you try that version and see if your issue is still valid? If yes, then please describe a way to reproduce.
Also, the later versions have added a lot of features, like color selection for series:
![image](https://user-images.githubusercontent.com/1447303/52809594-4685b800-3056-11e9-907a-bc6a35ddcf7b.png)

**Comment by tlrobinson** [comment]
@flamber You are correct this was resolved by #8541
