### ISSUE TITLE
Subscriptions: Dashboard is squeezed in email body, not using full width as it is in Metabase - v50.10

### ISSUE THREAD

**Issue by MyckeTap** [metabase/metabase#48797]
### Describe the bug

Metabase v50.10

Still dashboards are squeezed in the email and they don't look like in Metabase. 
Do I miss something? Any configuration or Env var that I need to add?
I thought this would change with v50, reading that in release  notes:
"Chart appearance in subscriptions the same as in Metabase (https://github.com/metabase/metabase/issues/41764)"

I have updated from v49.1 to v50.10, still no luck.

In Metabase:
![Image](https://github.com/user-attachments/assets/b0ef9366-a495-4576-9a62-facc02a73ca2)

In email body:
![Image](https://github.com/user-attachments/assets/7cc50555-e467-41dd-b713-ab1b2603f6db)

### Information about your Metabase installation

Metabase v50.10

### Severity

Minor

**Comment by alxnddr** [comment]
Hey @MyckeTap 👋 While individual chart types now have improved feature parity between the app and emails, the overall dashboard layout and responsiveness in emails remain limited due to email client constraints. In emails, we can't have a responsive dashboard that adjusts to different screen widths, so emails have fixed-width charts displayed as a list.

However, we could render entire dashboards as images or PDF files. There's an existing issue for this feature: https://github.com/metabase/metabase/issues/34907
