### ISSUE TITLE
Actions are broken in 50.30 when Models are based on SQL

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#48878]
### Describe the bug

Actions fail to load on dashboard for release 50.30  when using models based on SQL ... This used to work on 50.27.4

### To Reproduce

1. Go to Admin -> Database -> Sample Database -> Enable Actions
2. New -> SQL Question -> `Select * from orders` -> Save and turn to a Model
3. Go to Model Details and just create a basic action:

![Image](https://github.com/user-attachments/assets/115eaf35-33b6-4d22-9dda-ed01722f301f)

4. Go to Dashboard -> Add an action and pick up any action from orders -> It will work and you see this:

![Image](https://github.com/user-attachments/assets/e9dc0c75-f561-426b-a7ac-ceeaa6670ab9)

5. Refresh the page maybe a couple of times (for me happens once):

![Image](https://github.com/user-attachments/assets/9a86dfcd-1d5b-494e-8f53-a8180ff0ebbe)

you can also try this on stats https://stats.metabase.com/dashboard/2662-fail-action-model-based-on-sql

### Expected behavior

The button loads

### Logs

Nothing relevant

### Information about your Metabase installation

50.30 and master

### Severity

Broke a couple of dashboards

**Comment by NevRA** [comment]
Context: https://metaboat.slack.com/archives/C052ZBWRG3W/p1729248994578069

**Comment by kamilmielnik** [comment]
Debugging notes:
- this issue reproduces only when GET `/api/collection/root/items?models=dataset` ends before GET `/api/card/:id`
- GET `/api/collection/root/items?models=dataset` populates `entities.questions` in redux store (entity framework) with an incomplete card object (it does not have `dataset_query` attribute)
- `ActionViz/Action` component uses `useQuestionQuery` which will give this incomplete card from redux store (entity framework)

Possible solutions:
- quick: use `isLoading` from `useQuestionQuery` to delay trying to use card data
- proper: use `useGetCardQuery` instead of deprecated, entity-framework-using `useQuestionQuery`
