### ISSUE TITLE
EXT: MetabaseProvider reloads excessively

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#49081]
See more information on how to reproduce this in [this Notion document](https://www.notion.so/metabase/SDK-Customer-Feedback-Oct-26-12a69354c90180a38713e92076d8161b?pvs=4#12a69354c901805287d9f5f7d7980dac)

Slack Thread: https://metaboat.slack.com/archives/C07166YL2UU/p1729760797338199

**Comment by heypoom** [comment]
I couldn't reproduce the exact issue with `iat` being `null` yet; even trying the exact code and payload from the customer.

On an unrelated note, I noticed that when I do not provide any `exp` at all when signing the JWT (e.g. providing only `email`, `first_name` and `last_name` in the payload), it did indeed make 3 separate requests to `/sso/metabase` instead of 1.

![Image](https://github.com/user-attachments/assets/b92ac6ff-2578-46bf-849c-2226558015ce)

**Comment by npretto** [comment]
> I couldn't reproduce the exact issue with `iat` being `null` yet; even trying the exact code and payload from the customer still never results in `null`.
> 
> On an unrelated note, I noticed that when I do not provide any `exp` at all when signing the JWT (e.g. providing only `email`, `first_name` and `last_name` in the payload), it did indeed make 3 separate requests to `/sso/metabase` instead of 1. I'll look into this further if this is the same behaviour that causes the MetabaseProvider to reload excessively.
> 
> ![Image](https://github.com/user-attachments/assets/b92ac6ff-2578-46bf-849c-2226558015ce)

That's because we check the expiration on the FE to see if we should refresh it: https://github.com/metabase/metabase/blob/842f3f358fc99757e6e3ab19ab93c202ee530031/enterprise/frontend/src/embedding-sdk/store/reducer.ts#L48-L49

If it doesn't have the exp, we fetch the session on each request, I think we should assume that exp is present, handling that case would require too much logic/change from our side.
I'll add an error to the console if exp is not present to make it easier to debug

**Comment by heypoom** [comment]
I can reproduce `iat` being `null` now. Turns out that the `jsonwebtoken` library automatically adds the issued at (`iat`) key in the payload automatically. In this case, the customer needs to pass `iat` manually using their library.

```ts
  const token = jwt.sign(
    {
      email: 'foo@example.com',
      first_name: 'Foo',
      last_name: 'Bar',
      exp: Math.round(Date.now() / 1000) + 60 * 20,
    },
    METABASE_JWT_SHARED_SECRET,
    {algorithm: 'HS256', noTimestamp: true}
  )
```

The plot thickens though, as I managed to have the exact same JWT as the customer in this case with only `exp` and not `iat`, and the auth works correctly and only loads once. I think it is not the missing `iat` that is the issue, but the React code of the customer that causes the `MetabaseProvider` to reload.

```
{
  "status": "ok",
  "id": "05e7a0ec-fc38-4255-8533-xxxxxxxxxxx",
  "exp": 1730314324,
  "iat": null
}
```

**Comment by heypoom** [comment]
For the parent re-rendering issue, the root cause stems from the fact the `store` is currently [not a singleton](https://github.com/metabase/metabase/pull/48071/files#r1776753555), and therefore when the parent re-render the reference to store changes, and that likely triggers auth to reload.

PS. in addition, we also make a bunch of dispatch calls on `store` reference changes, which in this case is on every parent re-render:

```tsx
  useEffect(() => {
    if (fontFamily) {
      store.dispatch(setOptions({ font: fontFamily }));
    }
  }, [store, fontFamily]);

  useEffect(() => {
    store.dispatch(setPlugins(pluginsConfig || null));
  }, [store, pluginsConfig]);

  useEffect(() => {
    store.dispatch(setEventHandlers(eventHandlers || null));
  }, [store, eventHandlers]);

  useEffect(() => {
    store.dispatch(setLoaderComponent(config.loaderComponent ?? null));
  }, [store, config.loaderComponent]);

  useEffect(() => {
    store.dispatch(setErrorComponent(config.errorComponent ?? null));
  }, [store, config.errorComponent]);

  useEffect(() => {
    store.dispatch(setMetabaseClientUrl(config.metabaseInstanceUrl));
  }, [store, config.metabaseInstanceUrl]);
```

**Comment by heypoom** [comment]
Update: we [received confirmation from our customer](https://metaboat.slack.com/archives/C07166YL2UU/p1730728154724929?thread_ts=1729760797.338199&cid=C07166YL2UU) that this is indeed caused by their parent component re-rendering, so fixing the non-singleton `store` issue should indeed do the trick.

**Comment by heypoom** [comment]
Opened a separate issue in https://github.com/metabase/metabase/issues/49482.
