### ISSUE TITLE
Editing and saving a question when a dashboard time grouping parameter is applied with new time granularity breaks the parameter wiring

### ISSUE THREAD

**Issue by alexyarosh** [metabase/metabase#49202]
### Describe the bug

If you connect a time grouping widget to a question, select a grouping that different from original, then edit and save the question, the time grouping will not be doing anything anymore.

This can be confusing because someone can go edit the question to, for example, add filters (which is how I ran into this issue) or change chart settings, and it'll break the connection between the parameter widget and the column.

Here's an [example stats dashboard+questions](https://stats.metabase.com/dashboard/2681-time-parameter-testing?time_grouping=quarter)

Disconnecting and reconnecting the widget will fix the issue.

### To Reproduce

1. Create a question Sample DB > Orders > Count of Orders by `Created At: Month`
2. Add the question to a dashboard
3. Add a time grouping widget to the dashboard and connect the widget to `Created At`
5. Save
6. Pick a different time grouping (e.g. week)
7. While the grouping is applied, click on the question to edit it
8. Save the question and pick "replace"
9. Go back to the dashboard
10. Try to change the grouping 
-> doesn't do anything

### Information about your Metabase installation

51.1, master

### Severity

P2

### Additional context

https://github.com/user-attachments/assets/6f80cb12-b744-4fc8-ae5b-dc746ec45fb2

**Comment by ranquild** [comment]
The original issue with changing the temporal unit in the source question:
1. The breakout reference is used for the parameter mapping
2. The breakout gets changed so the breakout reference also gets changed
3. The parameter mapping is no longer valid, we cannot find the column

To fix it right now, we could add logic to the BE to try to find a breakout clause with another temporal unit for the same column. If we found exactly 1, then we can use it instead. If more than 1, then we should ignore this parameter mapping, like we do now. The fix is not ideal but it would work for simple cases where there are no multiple breakouts of the same column.
