### ISSUE TITLE
Migrated metrics do not respect collection permissions

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#49357]
### Describe the bug

If you move from <51 versions to 51 and you had metrics on your tables, then these will be moved to a new collection called "migrated metrics v1". If a group has "view" permissions on this collection then they won't be able to see it at all, but they'll be able to see the metrics in the table

### To Reproduce

1) spin up v50 and create 1-2 metrics in the people table
2) create a group and a user inside this new group. Leave permissions as they are
3) now move to v51, where metrics are an entity that live inside a collection (the metrics you created will be included in the "migrated metrics v1" collection)
4) Check that the All users "view only" to the collection and the new group has a "no access" permission
5) authenticate with the new user and check if you can see the collection (you can't), but the new user can see the metrics on the table

### Expected behavior

If the "All users" group has "view" access, then the user should be able to see the collection

Also, if the user can't see the metrics on the collection, then the user shouldn't be able to see the metric on the table

### Information about your Metabase installation

v51

### Severity

P2

### Additional context

The weirdest thing ever: several ways in which the user can see the new collection
1) giving curate to all users (?)
2) giving "view" on the collection to the new group, saving and then removing the "view" permission

**Comment by ranquild** [comment]
it seems that there are 2 related issues 1) access to "Migrated Metrics v1" collection, 2) Metrics read permission checks.

### Access to "Migrated Metrics v1" collection

It's now possible that some users won't have read access to "Migrated Metrics v1" when migrated to v51. This happens because we only grant access to "All Users" group and not others https://github.com/metabase/metabase/blob/d208d800c341f76c5cf66f351a44fecf852040bf/src/metabase/db/custom_migrations/metrics_v2.clj#L25. If a user was in a group (apart from "All Users") where access to "Our analytics" was blocked, they would not see "Migrated Metrics V1" collection after the migration.

Repro:
- Run v50
- Create a test user U1
- Create a group G1 and add U1 to it
- Change collection permissions so the G1's access to "Our analytics" is Blocked
- Run v51
- See that U1 doesn't see "Migrated Metrics v1" collection

Expected behavior:
- We should give read access to the newly created "Migrated Metrics v1" collection to all existing user groups during the migration.

### Metrics read permission checks

The repro is the same as for the issue above. While U1 cannot see the "Migrated Metrics v1" collection, U1 can create new queries in the query builder and see all metrics. It seems that `can-read?` checks still follow the legacy metrics model and are not based on the collection permissions.

Expetected behavior:
- Metrics, both migrated and new ones, should follow our regular collection permissions model.

**Comment by lbrdnk** [comment]
Removed my assignment and changed team label as per the discussion [on slack](https://metaboat.slack.com/archives/C0645JP1W81/p1730379488088189?thread_ts=1730318676.199629&cid=C0645JP1W81).
