### ISSUE TITLE
Column Headers in Exports Pivots are Sometimes Ordered Incorrectly

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#49416]
### Describe the bug

When pivots are exported to Excel in pivot format - values without results aren't exported in the same order in which they're displayed in the UI. Sort selections from viz settings are also ignored.

### To Reproduce

1. Create a pivot with a date grouping
2. Set the date as a column for the pivot
3. Ensure some of the results for the first row have a NULL result
4. Export the pivot
5. Note that columns with NULL cells are displaced in the final export (they're at the end)

https://www.loom.com/share/f24c12c571a84fbba3dfb81f8ad00ee2?sid=59120f7f-457a-4581-ba4b-a7dae2e1025a

### Expected behavior

The exported pivot should match the pivot that's visible in the user interface.

### Information about your Metabase installation

v51

### Severity

Annoying

**Comment by Tony-metabase** [comment]
@adam-james-v this might explain why that column we where looking at was always getting placed at the end of the CSV

**Comment by bshepherdson** [comment]
The querying folks discovered last week that the `:result_metadata` for pivot queries is busted. It seems to be the metadata for one of the possibly several SQL queries that were performed to build the pivot query, rather than for the pivot query as a whole.

Perhaps this is a symptom of the [same problem](https://github.com/metabase/metabase/issues/41896#issuecomment-2436169369)?
