### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by MaxiTalenti** [metabase/metabase#4963]
When I try to connect a slack I get the following message: **SSL peer shut down incorrectly**
I have configured ssl but it is not verified by a regulator. It must be because of that?

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: v0.23.0
- Metabase hosting environment: (e.x. Java in Windows)

**Comment by salsakran** [comment]
SSL should only involve connections made to your metabase instance by clients.

This sounds like an error connecting to slack.

**Comment by salsakran** [comment]
can you share server logs?

**Comment by camsaul** [comment]
@MaxiTalenti looks like you opened this issue twice, here and #4981. It's easier for us to fix things when the conversation is all contained in a single issue rather than split across several. Since there's more activity on the other issue I'm going to go ahead and close this as a duplicate of #4981
