### ISSUE TITLE
Trash accessible to people without permissions

### ISSUE THREAD

**Issue by TLazarevic** [metabase/metabase#49705]
### Describe the bug

I work with a use case of separate teams having separate collection access. I set different teams up with view access to only their collections. 
I was testing things out and realized teams have access to see the collections in trash, and every question inside them, and even run the questions they would never have access to! On another note, I was not able to perma delete the problematic trashed collections at all and revoke the access, so I had to move them somewhere else. This is a very recent behavior probably, introduced with trash sidebar

### To Reproduce

1. Have trashed collections
2. Give out view access to some collections to some user groups
3. Log in as a test user from said group
4. Freely roam trash

### Expected behavior

Trash is kept secret

### Information about your Metabase installation

v51.1.2, self hosted

### Severity

P1 to me

**Comment by noahmoss** [comment]
@TLazarevic I'm not able to repro. Could you provide more details about your permissions setup?

**Comment by TLazarevic** [comment]
> @TLazarevic I'm not able to repro. Could you provide more details about your permissions setup? 

I'd share more info but I had to react quickly. Maybe it's an issue on my side but it goes like this:

I'm an admin. I create collection C1 and user group G1. I add view access to G1 on C1 and it's subcollections. I log in as a member of G1 and I can see trashed collections that I shouldnt see. I don't think the whole trash was visible, just the stuff that was in a folder (collection) and then everything inside it. When I return to admin account, I can't perma delete those collections from trash

**Comment by TLazarevic** [comment]
> @TLazarevic I'm not able to repro. Could you provide more details about your permissions setup? 

I also quickly checked the docs for trash and it said that you should see stuff that you have a curate access to only, but my group members should not have curate access to anything, let alone stuff outside their scope, so I think it's a bug. But also, I could be doing something wrong with the permissions

**Comment by johnswanson** [comment]
@TLazarevic when you say

> On another note, I was not able to perma delete the problematic trashed collections at all and revoke the access, so I had to move them somewhere else

did you change permissions after the move to "somewhere else"? Or only move the trashed collections to a different location? If the permissions are unchanged, I'm wondering if I could ask you to go to the Permissions section of the admin panel, then go to Collections and navigate to one of the problematic collections, and just make sure that its permissions look correct - it should say "No Access" for all groups that the relevant user(s) are in. This would definitely include G1, but also "All Users," because permissions are additive (in other words, if your user has "Read" permissions from "All Users" and "No Access" permissions from "G1", the "Read" permission "wins"). If any group the user is in has "Read" or higher, the user will be able to view and run questions inside it.

Also, you probably know this, but note that collection permissions aren't recursive, so e.g. if a user has "No Access" to collection C1 but Read access to its subcollection C2, they'll still be able to get to and view C2. If C1 is in the "Our Analytics" collection and C2 is in C1, this user would instead see C2 in the "Our Analytics" collection.

Thanks for reporting this btw, definitely want to get this figured out as soon as possible.

**Comment by TLazarevic** [comment]
> @TLazarevic when you say
> 
> > On another note, I was not able to perma delete the problematic trashed collections at all and revoke the access, so I had to move them somewhere else
> 
> did you change permissions after the move to "somewhere else"? Or only move the trashed collections to a different location? If the permissions are unchanged, I'm wondering if I could ask you to go to the Permissions section of the admin panel, then go to Collections and navigate to one of the problematic collections, and just make sure that its permissions look correct - it should say "No Access" for all groups that the relevant user(s) are in. This would definitely include G1, but also "All Users," because permissions are additive (in other words, if your user has "Read" permissions from "All Users" and "No Access" permissions from "G1", the "Read" permission "wins"). If any group the user is in has "Read" or higher, the user will be able to view and run questions inside it.
> 
> Also, you probably know this, but note that collection permissions aren't recursive, so e.g. if a user has "No Access" to collection C1 but Read access to its subcollection C2, they'll still be able to get to and view C2. If C1 is in the "Our Analytics" collection and C2 is in C1, this user would instead see C2 in the "Our Analytics" collection.
> 
> Thanks for reporting this btw, definitely want to get this figured out as soon as possible.

I will check these things in a few hours when I'm available, I'm aware of the permission 'unioning' so I also did first check that All users have no access almost everywhere, but I'll recheck the little details and return with more confident answer. The deleted collections should be from different sources as well but I'll check, don't waste more time on this until then

**Comment by TLazarevic** [comment]
> [@TLazarevic](https://github.com/TLazarevic) when you say
> 
> > On another note, I was not able to perma delete the problematic trashed collections at all and revoke the access, so I had to move them somewhere else
> 
> did you change permissions after the move to "somewhere else"? Or only move the trashed collections to a different location? If the permissions are unchanged, I'm wondering if I could ask you to go to the Permissions section of the admin panel, then go to Collections and navigate to one of the problematic collections, and just make sure that its permissions look correct - it should say "No Access" for all groups that the relevant user(s) are in. This would definitely include G1, but also "All Users," because permissions are additive (in other words, if your user has "Read" permissions from "All Users" and "No Access" permissions from "G1", the "Read" permission "wins"). If any group the user is in has "Read" or higher, the user will be able to view and run questions inside it.
> 
> Also, you probably know this, but note that collection permissions aren't recursive, so e.g. if a user has "No Access" to collection C1 but Read access to its subcollection C2, they'll still be able to get to and view C2. If C1 is in the "Our Analytics" collection and C2 is in C1, this user would instead see C2 in the "Our Analytics" collection.
> 
> Thanks for reporting this btw, definitely want to get this figured out as soon as possible.

One of the collections I remember, after I moved it from trash to my personal collection and now to Our Analytics has Curate for admins, View for data team and All Users and other groups have No Access.
I will now try to reproduce with an empty collection

**Comment by johnswanson** [comment]
@TLazarevic 

> Can you repro inability to perma delete folders from trash? I still run into that one.

Yes, that is actually intentional for now. We'd like to be able to delete collections eventually, but it's not prioritized right now. Agreed that it's weird, and we should probably try to make it more obvious that it's expected.

Thanks again for reporting this and definitely let us know if you see it in the future.
