### ISSUE TITLE
Webhook Doesn't Allow HTTP Method to be configured?

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#49918]
### Describe the bug

Trying to use webhooks with discord. I have the discord URL, but the webhook test keeps failing (unsure what HTTP method it is using). So I get 404s

### To Reproduce

1. make a discord webhook
2. paste it into the box

### Information about your Metabase installation

```JSON
Metabase 0.51
```

### Severity

Medium

**Comment by k2xl** [comment]
Looks like every url is 404. I don't know what is going on (running metabase with docker, so unclear why it is having weird issues like this)

**Comment by piranha** [comment]
@k2xl we've looked into the issue and the request method (while it's static) is POST, as Discord expects it to be. The problem is that we send an empty request to check that the URL exist and lots of services do not expect this — we're removing that check (you'll be able to "test" webhook in Card interface) and also plan to surface service response somewhere.

So if everything goes well this will work a bit better soon. :)

**Comment by k2xl** [comment]
Okay great, which version should have this fix?
