### ISSUE TITLE
"Distinct" function only estimate in BigQuery's legacy SQL (MB query builder)

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#4994]
There is a difference in results between using “Group by” and “Count disctinct”, when using the MB query builder for a question based on BigQuery.

This seems to be due to the fact that in Legacy SQL (which is the default for BQ in MB) the “Distinct” function is only an approximation for more than 1000 rows, and instead “Exact_count_distinct” should be applied. 
Would be great if this could be changed to get correct and consistent results from such queries.
Thanks!

**Comment by fernandosjp** [comment]
Same problem here. Statistical aproximation distinct is really misleading in BigQuery legacy code. There are two ways of fixing this issue.

**Instead of:**
`SELECT COUNT(DISTINCT column) FROM table`

**2 Options have distinct not as statiscal aproximation:**

1. Using exact count distict function
`SELECT EXACT_COUNT_DISTINCT(column) FROM table`

2. Using unique function
`SELECT COUNT(UNIQUE(column)) FROM table`

**Comment by flamber** [comment]
Closing, since Metabase has used Standard SQL since 0.30, which does not have this accuracy problem:
https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql#advantages_of_standard_sql
