### ISSUE TITLE
custom expressions in actions widget bauble overflows container

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#5015]
Do we even think it's a good idea to have custom expressions as part of this widget?

![screen shot 2017-05-08 at 4 44 25 pm](https://cloud.githubusercontent.com/assets/5248953/25829836/c6c24c96-340d-11e7-8b9c-7adb5f47d10f.png)

**Comment by tlrobinson** [comment]
> Do we even think it's a good idea to have custom expressions as part of this widget?

I think the conclusion was "no", we should replace this action with something more constrained. I don't recall what exactly the replacement should be though.

**Comment by mazameli** [comment]
Yeah, seems to me like the "summarize" actions list could be constrained down to:

- Count of rows
- Sum of ...
- Average of ...
- Number of distinct values of ...
- Minimum of ...
- Maximum of ...

So that removes:
- Raw data
- Cumulative sum of ...
- Cumulative count of rows
- Standard deviation of ...

Don't think we need the `Metabasics` or `Custom expression` headings either.

**Comment by attekei** [comment]
Addressed by #5516
