### ISSUE TITLE
Non-admins aren't able to unarchive questions

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5090]
In the questions/collections archive page, a non-admin user can't unarchive a question even if it has a full access to it. This contradicts with our API which allows non-admin users with sufficient permissions to unarchive questions.

This could be pretty easy to fix by checking for each archived question whether the non-admin user has full access to the question or not.

**Comment by mazameli** [comment]
I'll also add that non-admins _can_ currently archive and unarchive dashboards.

**Comment by sailxjx** [comment]
@mazameli is there an opened issue for non-admins can currently archive dashboards?

**Comment by flamber** [comment]
This is kinda fixed in 0.31.2 - most of this was probably fixed in 0.30 as part of collections overhaul:
- [ ] Unarchive via button for non-admins. (Button is missing)
- [x] Unarchive by multi-selection for non-admins.
- [x] Only allow archive/unarchive questions/dashboards/sub-collections, where user have "Curate collection" permissions to that collection (or Personal Collection).

- As user ("TEST 5090" and "TEST Dashboard" are in user's Personal Collection)
![screencast_00001](https://user-images.githubusercontent.com/1447303/53290174-17fa9200-3766-11e9-8c10-81cac1399ac7.gif)
- As admin (I'm unsure why "TEST 6010" is behaving like that, don't get any errors anywhere)
![screencast_00002](https://user-images.githubusercontent.com/1447303/53290182-1f21a000-3766-11e9-8551-88771f05c119.gif)

**Comment by camsaul** [comment]
Same issue as #15253; merging this issue into that one because we have a test repro for it
