### ISSUE TITLE
Synced database with new table added, UI does not update to reflect

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#5129]
I have added a new table to my datawarehouse, synced in metabase, and can see from the logs that the new table was found. When I try to access this table using the query builder, it does not show up. Is this intended behavior?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by doodlebro** [comment]
Took 10 minutes and re-initializing metabase to refresh. What is the limitation here? Metabase is lightweight and should be able to update the UI as soon as it detects new tables, right?

**Comment by salsakran** [comment]
Depending on how big the data warehouse is, it can take up a bit of time to perform a sync + analysis. 

We're aggressively refactoring and tuning this in #5046 and #4991

**Comment by sabino** [comment]
@salsakran 
Will you guys add a possibility of sync on a per-table basis? We currently have a huge database with 15 schemas and 381 tables that translates to 4080 columns. It takes roughly two days to finish syncing and by that time more columns and values will be added.

That's why a per table syncing possibility could really help us.

**Comment by Jyggafey** [comment]
I would like to add that when i encounter this issue that new tables are not showing up in the query builder the admin UI does display all new tables and fields i am looking for, so the analyze step is finished but the query builder UI does not update.
Usually i just restart metabase in this situation because the query builder immediately shows the new table after that.

**Comment by doodlebro** [comment]
Sounds like a bug in the UI implementation to me

**Comment by camsaul** [comment]
This sounds like the same thing as #5275.

The DBs list in the query builder doesn't get refreshed after you do different actions that affect it

**Comment by cottrell** [comment]
You can force refresh the table list through the admin on the UI, and I think the API POST sync_schema should be the same as the UI click (have not tested yet). 

Refreshing on a loop as default might be ok but likely requires more thought than it seems.

https://github.com/metabase/metabase/blob/master/docs/api-documentation.md

**Comment by cottrell** [comment]
Even after updating the schema in admin, the chart filter mechanism is not updating. Not sure how to kill this for force refresh yet.

**Comment by vitorfield** [comment]
You can "force" the refresh of the table using the toggle button for the visibility option. By switching Hide/show, metabase will trigger a action to synchronize the table fields.

**Comment by ranquild** [comment]
The underlying problem is that the endpoint just returns immediately and there is no observable status of the operation:
```
;; Should somehow trigger sync-database/sync-database!
(api/defendpoint POST "/:id/sync_schema"
  "Trigger a manual update of the schema metadata for this `Database`."
  [id]
  ;; just wrap this in a future so it happens async
  (let [db (api/write-check (Database id))]
    (future
      (sync-metadata/sync-db-metadata! db)
      (analyze/analyze-db! db)))
  {:status :ok})
```

We currently have `initial_sync_status`. If we had something similar but for sync happening after the initial one, we could use it on the frontend and fix this issue. I'm adding `Backend` label because it's not possible to fix without the backend.

**Comment by satyavarma** [comment]
We are facing the issue in the 0.45.1 version also. The job is scheduled for every 30 min. But sometimes we are observing that it is taking more than 5 to 6 hours.

**Comment by flamber** [comment]
@satyavarma There's no 0.45.1 (yet) and there's no way of setting the schedule to less than hourly. When the sync has completed, then do a browser refresh. Sounds like you are seeing different problems. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ranquild** [comment]
This might be easier with RTK query now - we need to invalidate the cache (maybe just after some big time interval, or after some endpoint call)

**Comment by ranquild** [comment]
This is already fixed and there is an e2e test for it https://github.com/metabase/metabase/blob/c44d88e97cb29a5ada406774836fb2f35743b035/e2e/test/scenarios/admin/admin-reproductions.cy.spec.js#L111.

If you changed the db schema via a different user / browser tab, you would need to wait for 1 minute (this is the current default value that might change in the future) for the FE cache to become stale in other tabs. Then try creating a new question or opening an existing one - you should see your new columns.
