### ISSUE TITLE
Plans to port metabase to cordova as client (iOS and Android)

### ISSUE THREAD

**Issue by ramonbmt** [metabase/metabase#5165]
Is there any plan to port Metabase to cordova and make it an IOS and Android App (Just the client)?

Or maybe there is a reason as not to do that, because as I see, the backend and frontend are nicely separated and will take some relatively small effort to isolate and compile with cordova.

Regards

**Comment by ramonbmt** [comment]
Posible app enhancement
-Create push notifications on query subscriptions with thresholds

**Comment by kdoh** [comment]
@ramonbmt We don't have any specific plans around a mobile client (Cordova or otherwise) at this time. A more native experience on mobile is something we definitely all want to see but as part of taking that on there are some design challenges around what the common tasks and needs on mobile are, so my two cents are that it would be a different enough experience that we'd want to take the time to do it right vs just wrap what we have in a more native container. 

That being said it'd be great to hear a bit more about what you'd like to see in a Metabase mobile client.

**Comment by ramonbmt** [comment]
@kdoh Thanks for your reply, well on the basic level it will be nice to have at least the dashboard to look the information on a mobile App. Because the configuration and creation of questions and dashboards could be done on a computer. 

It would be a nice addition to have push notification whenever a certain question hit a threshold.

**Comment by ramonbmt** [comment]
@kdoh removing Cordova from the equation, maybe react native? as I see that the frontend is developed in react.

**Comment by kdoh** [comment]
@ramonbmt When you say a question hits a certain threshold are you meaning when something hits a target or a percent change is above a certain level? (Alerts basically?)

**Comment by ramonbmt** [comment]
@kdoh yes, percent change or value equality. And yes, exactly, Alerts. 
But not exactly as a pulse. I don't know if that is something that is under development or merged in a recent version?

**Comment by kdoh** [comment]
@ramonbmt Not currently. I'm going to go ahead and close this issue since we don't have any plans to port MB to Cordova. If you'd like to discuss alerting in more detail [this is the original issue around that feature](https://github.com/metabase/metabase/issues/1373).
