### ISSUE TITLE
Is it possible to use variables as part of SQL statement in metabase questions?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#5181]
I'm trying to give end users an option to select interval for their questions like: yearly, monthly and or daily.

Please take a look at the following query:

```
select pdate as 'Payment Date', ROUND(@sum_amount := @sum_amount + `amount`) AS 'Total Amount' from
(
select @sum_amount := 0, date(issue_date) pdate, sum(amount) amount from payments group by {{interval_date}}(date(issue_date))
) inner_tbl
```

The part `{{interval_date}}` is used to get a parameter like DAY, MONTH, YEAR from users to change the chart accordingly. But MySQL gives syntax error (maybe because type of field is text).

The question is how should I use variables for SQL queries? How should I make part of it as a variable. Or is there any solution to get interval from user and solve this interval issue?

**Comment by salsakran** [comment]
We not longer allow strings to be treated a SQL tokens in the templates. We did this to reduce the surface area for sql injection attacks. All number, string, and date variables are used as SQL statement parameters rather than interpolated into a string SQL template. 

We suggest using field based filters which allow you to use our dashboard filter widgets rather than having users type in the intervals.
