### ISSUE TITLE
use session_id from api to enter frontend?

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#5203]
Is this possible?
Something like this: http://MB_URL:3000/session_id=[SESSION_ID FROM API] ?

Or would this be a security issue?

**Comment by kdoh** [comment]
@mokra That's not going to work (and while I can't say for sure it's a security issue it seems like a generally bad practice). The preferable way to use the REST API is to follow the instructions in [this guide](https://github.com/metabase/metabase/wiki/Using-the-REST-API). You should be passing the session ID you get as a header on requests you make to the API instead of trying to use the session ID in URLs.

**Comment by mokra** [comment]
thanks

**Comment by VikramTiwari** [comment]
@mokra You should be able to save that session ID in your cookie value for metabase website and then just head to base URL of your metabase instance and it should work.

**Comment by mokra** [comment]
Yes , thats exactly what I did and it work. But it really isn't a secure method
