### ISSUE TITLE
Query builder does not display failed query HTTP request errors

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#5210]
If a query *request* fails (i.e. an HTTP error, not a failed query itself, which returns a 200 status) the error is not displayed. The loading indicator just keeps spinning forever.

In most cases the when the query itself is bad or there's db timeout etc we catch exceptions and return a 200 with an `error` property, which works fine. This only applies when something catastrophic occurs, such as the backend being down completely (I also run into when working on backend code)

**Comment by attekei** [comment]
This was fixed as a part of #5134. 

The reason was that due to mistakes in both request creation and QB action code. I think that the "loading indicator spinning forever" was a metabase-lib regression that my code in `RUN_QUERY` caused. Even if the error was caught, it was still treated a same way as query cancellation because of how request logic in `lib/api` was built. 

These two issues have been fixed and now we show "We're experiencing server issues" error message properly.
