### ISSUE TITLE
There is any way for a user to run an update/create/delete query?

### ISSUE THREAD

**Issue by camilonova** [metabase/metabase#5287]
Just a question.

A user with access to the SQL Editor would be able to perform a query to alter data?

**Comment by camsaul** [comment]
Nope, SQL queries are read-only

**Comment by salsakran** [comment]
Not at this time. We've occasionally talked about the idea of having the ability to write back into DBs, but at this point in time we're focusing on being read-only.

**Comment by Varunram** [comment]
This might be counter-productive. For e.g. you may be working on a database, experimenting with fks and stuff, but you really might not want to write that into the DB. And if you do write to the DB by accident and it is on your production server, you will be in a bad place. I feel its better to keep it this way in order to avoid accidents (GitLab and stuff). My 2 cents

**Comment by camilonova** [comment]
Thats the way it should be!

Thanks.
