### ISSUE TITLE
Improve card layout on dashboards

### ISSUE THREAD

**Issue by lukabirsa** [metabase/metabase#5289]
As an end user, I'd like to split my dashboards into logical sections and add visual hierarchy. 

This could be achieved by:
- adding a text-only card that enables me to add text-headings,
- adding a horizontal rule card that enables me to split the dashboard into sections,
- adding support for changing card background/graph color (a couple of presets would be fine),
- adding a group card that has a title and holds other cards

**Comment by jornh** [comment]
@lukabirsa with text cards introduced in v0.27 and the v0.29 text card option of removing the box for titles like shown in first picture of https://www.metabase.com/blog/metabase-0.29/index.html I personally think your intention with bullet 1, 2 and 4 is covered (though it’s with adding *less* lines and boxes instead of more. I think that’s actually preferable as it lets your data stand out instead of adding “more clutter”.

This leaves this issue with your only bullet 3 as a potential to-do it seems?

**Comment by lukabirsa** [comment]
@jornh sure. Only 3 is still valid. We're using the text boxes since you launched them - great work!

**Comment by flamber** [comment]
Closing this, since all but the background color options is implemented.
For card background, have a look at #3168 - upvote by clicking :+1: on the first post
