### ISSUE TITLE
wrong graphic on the dashboard

### ISSUE THREAD

**Issue by LauraSom** [metabase/metabase#5290]
this is what you see on the (Online Marketing Operative) dashboard: 
![bildschirmfoto 2017-06-07 um 09 33 02](https://user-images.githubusercontent.com/28920848/26867645-7a318d40-4b66-11e7-82a3-5de0ae6c8354.png)
this is what you see when you click on the graphic and what should be seen on the dashboard:
![bildschirmfoto 2017-06-07 um 09 32 38](https://user-images.githubusercontent.com/28920848/26867651-82d74624-4b66-11e7-975d-3079916452a1.png)

**Comment by mazameli** [comment]
It looks like you're breaking out by 2 different fields (`Date: week of year` and `Product SKU`), but the x-axis on the dashboard is `Product SKU` instead of `Date: week of year`. It's odd that it's doing one thing on the dashboard, and something else on the question detail view.

What version of Metabase are you using? I noticed from a different issue you opened that I think you're using Google Analytics as your driver. If that's the case, this bug might have something to do with the specific peculiarities of that driver.

**Comment by LauraSom** [comment]
I'm using version v0.24.2 of Metabase. And yes we use google analytics for
this report. So is there a possibility to fix it?

2017-06-08 0:27 GMT+02:00 Maz Ameli <notifications@github.com>:

**Comment by flamber** [comment]
Closing in favor of #11218
