### ISSUE TITLE
Data table popovers positioned incorrectly when target is scrolled out of view

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5302]
### Metabase Mac App

<img width="1280" alt="issue" src="https://user-images.githubusercontent.com/18598959/26971012-2ce6fb5a-4d29-11e7-9aa2-019ffd90ff33.png">

Sometimes, the query bar shows up in a totally unexpected place. This is not intended to happen, although I do not know the reason for it. Any ideas?

**Comment by kdoh** [comment]
To reproduce:

1) On a table click on a cell (not a table heading) to get the action popover for that cell.
2) Scroll the table so that cell is out of view.
3) Watch as the popover takes flight.

This isn't Mac App specific, the behavior is the same regardless of what browser you're in as far as I can tell.

At a high level what seems to be happening here is that since the table cells are virtualized, once the initial target cell is removed, the popover has no point of reference in the DOM anymore and it positions itself relative to the window as a result.

It seems like the right fix here is to close the popover when we detect a scroll event on the data table. I can't think of a good reason to keep showing it while you're scrolling since it can obscure content.
