### ISSUE TITLE
Reset Email settings

### ISSUE THREAD

**Issue by od3n** [metabase/metabase#5345]
I can't reset changes i made to the email setting. How do i reconfigure this?

**Comment by kdoh** [comment]
@od3n To clarify do you mean you can't change an existing field or you can't clear out the entire form? (I'm assuming you mean the latter).

**Comment by od3n** [comment]
@kdoh yes i mean the latter

**Comment by JLevski** [comment]
@kdoh 👍  - may or may not be related, but seems I can't save changes when i do edit individual fields (including after clearing cookies etc.)

**Comment by kdoh** [comment]
Took a crack at fixing the complete reset case, but it's a little more involved than I thought. I initially thought it might be possible to just check to see if all values are empty in the form on the front end and consider that intent to reset and fire off an API response with nulls (not the most kosher but maybe an acceptable short term fix). No dice though; the email API endpoint and the DB both enforce a NOT NULL constraint (as they probably should for most cases).

It looks like you can remove a setting by doing a `PUT` to `/api/setting/:setting-key` with a null value, which is why it's possible to provide nulls to other settings to remove them, but firing off 4 api requests seems a little jank too.

Some possible options I see:
1 - purely FE solution, have a specific method to reset email that hits the relevant settings endpoints
2 - modify the email endpoint to allow for a reset via nulls
3 - add the ability to do a bulk update of settings, similar to the settings `PUT` endpoint
4 - something smarter / cleaner I haven't thought of

**Comment by flamber** [comment]
Hi @od3n 
This issue was fixed by #7330 - and I think it was included in 0.29 - it looks like this on 0.31.2:
![image](https://user-images.githubusercontent.com/1447303/52921578-2b2cde00-32de-11e9-89ae-86b6167b4324.png)
