### ISSUE TITLE
Improve Auto Refresh

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5347]
When deployed on a remote server, Auto refresh does not seem to do as specified. 

Expected Behaviour - Refresh every x minutes as specified
Current Behaviour - Refresh after x minutes and stop

I don't know if this is related to the number of dashboards, but the step to reproduce is to create 10 (or more dashboards) and set refresh time to one minute in each of them. After a while, you should notice that none of the dashboards refresh for more than one time.

I think "Auto Refresh" meant "refresh after x minutes" although I feel that it should be "refresh every x minutes". Maybe specify this somewhere in the docs?

**Comment by mazameli** [comment]
> create 10 (or more dashboards) and set refresh time to one minute in each of them

I'm unclear here: are you opening up each of these dashboards in different tabs? Or displaying them on a bunch of different monitors? We have one dashboard on a monitor that is set to refresh periodically, and it does indeed exhibit the expected behavior. But if you have 10 of them going _simultaneously on the same server_ and setting them each to _1-minute refreshes_, it could be you're just hammering your database, particularly if those dashboards contain large/intensive queries.

**Comment by Varunram** [comment]
Nah, those were more like experimental questions, so the server wouldn't be hammered so much. But, it does work on a single dashboard as expected. So, if I'm right, you're saying that if the server is *theoretically* under stress, our refresh gets reset? Thanks for your time!

**Comment by mazameli** [comment]
Are you still having this issue, @Varunram, or should we close this? Thanks.

**Comment by Varunram** [comment]
Yep, forgot about this, we can close this one!
