### ISSUE TITLE
Multi-language interface translation

### ISSUE THREAD

**Issue by stefanoeb** [metabase/metabase#5366]
Hi guys, just wondering about the possibility to translate the interface to another languages to improve accessibility, and I did not found any issue about that.

What do you think? Is it too much work to do?

**Comment by camsaul** [comment]
Hi, don't forget that you can use the search bar to see if an issue is already open. We already have an issue open for this: #1451

**Comment by Lanny2016** [comment]
Hi,
I have finished the translation of matabase on Poeditor and it has been updated. However, there are some problems on it because of Turkish charactor difference. I have downloaded to edit them again. Unfortunatelly, i was not able to find the correct file to fix them because of tons of files in it.
Can anybody help me who have done this before?
Thanks in advance.
