### ISSUE TITLE
Grouping widget can get into non-sensical states

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5367]
Not sure exactly how I got here, but if you switch between a categorical and time extract grouping, the extract remains attached to the widget. 

See below
<img width="1434" alt="screen shot 2017-06-20 at 2 55 20 pm" src="https://user-images.githubusercontent.com/107439/27357821-9e5a31f6-55c8-11e7-98c8-c70134f8cb6a.png">

**Comment by attekei** [comment]
I'm unable to reproduce and the query itself doesn't make a ton of sense because "Product ID" field shouldn't be available for Orders in breakout options. Last time I remember seeing it was in #3444 over one month ago (it was a query lib regression that FK fields were visible for your current table).

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 (and have never seen this happen).
