### ISSUE TITLE
Change the order of Columns in a Pivot

### ISSUE THREAD

**Issue by FDenker** [metabase/metabase#5370]
I have a count of orders of each city in each month of last year. This is the result of a SQL query.
The problem is that that the months are ordered alphabetically like this

>  [April .... August .... December]

There does not seem to be a way for me to order it accordingly.
The query should not be the problem, but here it is:

> GROUP BY DATE_FORMAT(`date`,'%M %Y'), Cities.City_Name
> ORDER BY Orders.Date

**Comment by salsakran** [comment]
If this is in a table, we don't do any parsing of the columns or type coercion. If you do an ORDER BY on a string, you'll get string comparisons. 
In general, we're going to respect the ordering that comes back from the database unless we're trying to parse a column to place on a time or other axis in a chart. 

I'm going to close this as it falls outside of the scope of what we'd do to "clean up" the results of a query on the users behalf. If any of the above is not that case, I'm happy to re-open it if there's a bug.

**Comment by MarkRx** [comment]
Here is a case. It appears the column order is based on string comparison when I don't want it to be.

I am converting date column to a string in order to have prettier date column formatting in a pivot table. Even though the results from the database and API are in the correct order it seems the pivot table is ordering the columns lexographically. Now I believe this is the right thing to do (otherwise you are dependent on the order of the first time you see a column which would be in indeterministic when data is missing - the same problem colors have in #5910). I would however like a way to determine the order of my pivot columns beyond just relying on a default text sort order.

Given the following (oracle 12.2) query:
```
with dates as (
    select trunc(last_day(sysdate)) + 1 start_next_month from dual
    union all select trunc(last_day(add_months(sysdate, -1))) + 1 start_next_month from dual
    union all select trunc(last_day(add_months(sysdate, -2))) + 1 start_next_month from dual
    union all select trunc(last_day(add_months(sysdate, -3))) + 1 start_next_month from dual
    union all select trunc(last_day(add_months(sysdate, -4))) + 1 start_next_month from dual
    union all select trunc(last_day(add_months(sysdate, -5))) + 1 start_next_month from dual
)
select to_char(start_next_month, 'MON YYYY') as mon,
    vcs_project_name || '/' || vcs_repo_name || ' (' || acqe_subclassifier || ')' as "Component",
    acqe_coverage_coveredlines || '/' || acqe_coverage_totallines || ' (' || acqe_coverage_percent || ') ' as "Coverage"
    from (
    select 
        start_next_month, 
        mbase.v_artifactory_acqe.*,
        row_number() over (
            partition by 
            vcs_project_name,
            vcs_repo_name,
            acqe_subclassifier,
            start_next_month
            order by aa_create_dt desc, acqe_qualifies asc, acqe_coverage_totallines desc) rn
        
    from dates
    left join mbase.v_artifactory_acqe on aa_create_dt < start_next_month
    where aja_lob = 'tax'
    and acqe_subclassifier is not null
) where rn = 1
order by "Component" asc, to_date(mon, 'MON YYYY') asc
```

Running the SQL query results in this:
| Month | Component | Coverage |
| ------- | ----------| ---------- |
| MAR 2018 | foo/C1 (root) | 419/437 (95.881) |
| APR 2018 | foo/C1 (root) | 419/437 (95.881) |
| MAY 2018 | foo/C1 (root) | 419/438 (95.662) |
| JUN 2018 | foo/C1 (root) | 419/438 (95.662) |
| JUL 2018 | foo/C1 (root) | 419/438 (95.662) |
| AUG 2018 | foo/C1 (root) | 419/438 (95.662) |
| MAR 2018 | foo/C2 (root) | 1012/1160 (87.241) |
| APR 2018 | foo/C2 (root) | 1012/1160 (87.241) |
| MAY 2018 | foo/C2 (root) | 1012/1160 (87.241) |
| JUN 2018 | foo/C2 (root) | 1025/1174 (87.308) |
| JUL 2018 | foo/C2 (root) | 1025/1174 (87.308) |
| AUG 2018 | foo/C2 (root) | 1025/1174 (87.308) |
| ... | ... | ... |

API Response:

```
"data": {
	"rows": [
		["MAR 2018", "foo/C1 (root)", "419/437 (95.881) "],
		["APR 2018", "foo/C1 (root)", "419/437 (95.881) "],
		["MAY 2018", "foo/C1 (root)", "419/438 (95.662) "],
		["JUN 2018", "foo/C1 (root)", "419/438 (95.662) "],
		["JUL 2018", "foo/C1 (root)", "419/438 (95.662) "],
		["AUG 2018", "foo/C1 (root)", "419/438 (95.662) "],
		["MAR 2018", "foo/C2 (root)", "1012/1160 (87.241) "],
		["APR 2018", "foo/C2 (root)", "1012/1160 (87.241) "],
		["MAY 2018", "foo/C2 (root)", "1012/1160 (87.241) "],
		["JUN 2018", "foo/C2 (root)", "1025/1174 (87.308) "],
		["JUL 2018", "foo/C2 (root)", "1025/1174 (87.308) "],
		["AUG 2018", "foo/C2 (root)", "1025/1174 (87.308) "],
	],
	"native_form": {
		. . .
	},
	"cols": [{
			"name": "Month",
			"display_name": "Month",
			"base_type": "type/Text",
			"remapped_to": null,
			"remapped_from": null
		}, {
			"name": "Component",
			"display_name": "Component",
			"base_type": "type/Text",
			"remapped_to": null,
			"remapped_from": null
		}, {
			"name": "Coverage",
			"display_name": "Coverage",
			"base_type": "type/Text",
			"remapped_to": null,
			"remapped_from": null
		}
	],
	"results_metadata": {
		"checksum": "NYIaoqaI9mE65QSUGoUSnA==",
		"columns": [{
				"base_type": "type/Text",
				"display_name": "Month",
				"name": "Month"
			}, {
				"base_type": "type/Text",
				"display_name": "Component",
				"name": "Component"
			}, {
				"base_type": "type/Text",
				"display_name": "Coverage",
				"name": "Coverage"
			}
		]
	}
}		
```"display_name": "Component",
				"base_type": "type/Text",
				"remapped_to": null,
				"remapped_from": null
			}, {
				"name": "Coverage",
				"display_name": "Coverage",
				"base_type": "type/Text",
				"remapped_to": null,
				"remapped_from": null
			}
		],
		"results_metadata": {
			"checksum": "NYIaoqaI9mE65QSUGoUSnA==",
			"columns": [{
					"base_type": "type/Text",
					"display_name": "Month",
					"name": "Month"
				}, {
					"base_type": "type/Text",
					"display_name": "Component",
					"name": "Component"
				}, {
					"base_type": "type/Text",
					"display_name": "Coverage",
					"name": "Coverage"
				}
			]
		}
	}
```

The UI is showing the columns in the following order (sorted lexographically presumably)
APR 2018, AUG 2018, JUL 2018, JUN 2018, MAR 2018, MAY 2018

Metabase 29.3
