### ISSUE TITLE
Make Funnel Vizualization Reorderable

### ISSUE THREAD

**Issue by cetra3** [metabase/metabase#5401]
At the moment when you use the Funnel Visualization, the funnel sections are listed in an alphabetical order.   

There should be a way to reorder the funnel sections.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by benjR** [comment]
Tried using it too and it's not possible as long as we can't sort the sections.

**Comment by kkalyan** [comment]
This would be really nice to have!

**Comment by ukritw** [comment]
_Resurfacing the issue with more context and proposed solution._ 

**Is your feature request related to a problem? Please describe.** 
The funnel diagram sort the steps alphabetically by default, which renders the ordering useless most of the time. The current workaround is to rename the steps alphabetically (e.g. a_step1, b_step2, c_step3) such that it can be sorted correctly or to add an additional column for specifying the order of steps in SQL (e.g. 1, 2, 3).

<img width="327" alt="Screen Shot 2021-03-31 at 3 05 12 PM" src="https://user-images.githubusercontent.com/2685753/113111750-b48b9a00-9232-11eb-9f66-a1069789ff65.png">

**Describe the solution you'd like** 
In the sidebar of the visualization menu, the users should be able to click on the gear icon that opens up a "steps ordering" setting. The setting should display the list of all possible steps with the ability move each step up and down the list by drag-and-drop.

**Describe alternatives you've considered** 
The alternative is let the user add one step at a time. Similar to what adding a series is like in the line chart visualization. Without the drag-and-drop functionality, this should be easier to implement.

**How important is this feature to you?**
It almost falls into the category of _must-have feature_ since every user needs to use the workaround to make the ordering of the funnel diagram display correctly.

**Related issues** 
[#13669](https://github.com/metabase/metabase/issues/13669) 
could be useful for bar charts as well [#2339](https://github.com/metabase/metabase/issues/2339)

**Comment by stonematt** [comment]
Our funnel labels are fed to metabase by an external system.  this makes the sales funnel is essentially useless w/out the ability to reorder steps.

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/issues/24840
