### ISSUE TITLE
Feature: Moving away from legacySQL to standardSQL in BigQuery

### ISSUE THREAD

**Issue by kritop** [metabase/metabase#5402]
### Feature
Are there any plans to remove legacySQL as default and move to standardSQL? Every time I start out with a "New Question" and move to the SQL Editor partly because this (https://github.com/metabase/metabase/issues/4218). I need to update the syntax because standardSQL has a lot of advantages over legacySQL!

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
Hi @kritop our eventual plan is to switch over to standard SQL for BigQuery. I'm not sure on the exact timeline but we've been talking about it for a while and I could see us making the switch within the next few releases.

We haven't made the switch yet because the process has a couple of tricky parts to it:

*  we'll have to rewrite our BigQuery query processing code to generate standard SQL instead of legacy 
*  We'll need to make sure defaulting to standard SQL is done in a way that doesn't break any existing queries written in BigQuery legacy SQL. This will probably mean we'll have to find and migrate over the relevant Questions, probably by modifying their queries to add `#legacySQL` directives at top. We'll have to be careful how we do this to make sure we don't add it to queries that already have a directive in them

**Comment by MiBaDK** [comment]
An idea for the migration could be to specify default on the connection when setting it up. Which you can then override per questions as well.

Then all existing connections will be set to legacy on upgrade and hopefully not break existing cards.

**Comment by GravityWinz** [comment]
As a BigQuery user I am very interested in this. I understand that not breaking the Legacy queries is a tricky thing to address. I might suggest that you have two separate BQ drivers, keep the existing one to support existing reports but then fork it to support Standard. Then as a user I can determine which way I will be querying BQ based on which driver I select?

**Comment by eebsidian** [comment]
Do you guys have any current workaround in order to query a BigQuery `view` from the Custom Query builder without getting this error: "Cannot reference a standard SQL view in a legacy SQL query."?  Asking for a friend ;)

**Comment by labianchin** [comment]
Would it work to do the following on the query:

```
#standardSQL
SELECT ...
```

**Comment by camsaul** [comment]
Implemented by #7945
