### ISSUE TITLE
Migrating to webpack 3

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5412]
Since webpack3 offers a lot of additional features plus loading time improvements, I think we should, in the long run plan to migrate to 3. What are your views on this? CC @camsaul @kdoh 
<a href="https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b"> New stuff in Webpack 3 </a>

**Comment by kdoh** [comment]
Seems interesting 👍  I know @tlrobinson had done [an initial PR to migrate us to webapck 2](https://github.com/metabase/metabase/pull/4175) but we'd held off at the time because we wanted to wait for more of the packages we use to start shipping es6 modules (according to Tom in that PR).

Having not looked into this very deeply myself I'm not sure if it would make sense to finish that migration to 2, make sure that's ok, and then go from there; or just try jumping straight to 3.

@Varunram If you're interested in trying out an experimental branch to migrate us over you should totally feel free to go for it.

**Comment by Varunram** [comment]
@kdoh Sure, I'll try doing something to take use to 3. Since v1 is deprecated, it'd be better for us to switch to a newer version. I'll take cues from @tlrobinson's PR which you linked :) Sorry for the late reply, had some stuff on the way!

**Comment by kdoh** [comment]
Closing this as we migrated to Webpack 3 in #6147.
