### ISSUE TITLE
Goal lines are twice as high in dashboards

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#5448]
I have a dashboard with few cards containing bar charts a set goal line. It also has a date filter (all options) with default value last 60 days.

When I change the date filter to "today" or "yesterday" the goal lines are twice as high as they should be. For example 2000 instead of 1000.

**Comment by salsakran** [comment]
Reproduced.

**Comment by tlrobinson** [comment]
This happens when there's a single point because goal lines are implemented as an additional overlaid chart, with data `[[xDomain[0], goalValue], [xDomain[1], goalValue]]`. If `xDomain[0]` and `xDomain[1]` are the same, crossfilter's `reduceSum` reduces it to essentially `[xDomain[0], goalValue + goalValue]`.

Here's a simple/hacky fix:

diff --git a/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js b/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
index c7d0b81b3..b10cbfa46 100644
--- a/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
+++ b/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
@@ -1175,7 +1175,8 @@ export default function lineAreaBar(element: Element, {
         const goalValue = settings["graph.goal_value"];
         const goalData = [[xDomain[0], goalValue], [xDomain[1], goalValue]];
         const goalDimension = crossfilter(goalData).dimension(d => d[0]);
-        const goalGroup = goalDimension.group().reduceSum(d => d[1]);
+        // take the last point rather than summing in case xDomain[0] === xDomain[1], e.x. single row
+        const goalGroup = goalDimension.group().reduce((p,d) => d[1], (p,d) => p, () => 0);
         const goalIndex = charts.length;
         let goalChart = dc.lineChart(parent)
             .dimension(goalDimension)
