### ISSUE TITLE
Saved Questions item in query builder Data menu not working

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5488]
Clicking on `Saved questions` doesn't do anything. Not seeing any JS console or log errors. This is happening on master as well as our stats instance, both on Chrome and Safari. Maybe it has something to do with the query lib refactor?

![screen shot 2017-07-17 at 10 52 40 am](https://user-images.githubusercontent.com/2223916/28282094-141435b6-6ade-11e7-89b6-42804e12e0d1.png)

**Comment by kdoh** [comment]
This seems to happen if any of the "nestable" queries are in a collection.

**Comment by attekei** [comment]
I'll try to fix this now

**Comment by attekei** [comment]
This is a regression caused by https://github.com/metabase/metabase/pull/5473; the problem is that if we have questions from more than one collection, we need `AccordianList` for showing the schema picker in a similar way as for multi-schema tables:
<img width="299" alt="screen shot 2017-07-17 at 14 18 02" src="https://user-images.githubusercontent.com/6034928/28290302-cc212f62-6afa-11e7-9fa7-68ec5ab65e88.png">
