### ISSUE TITLE
Pagination!

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5504]
We have quite a few "infinite" lists in Metabase, including:
* Search results
* Dashboards
* Collections and the "Everything Else" list
* Lists of saved questions
* Lists of metrics, segments, tables, and fields in the Data Reference

These lists have become unusable for some of our users who have tons of saved questions, dashboards, and metrics. 

~I think it would make sense to break these lists into pages once the list exceeds n number of items. One implication of that would be that lists with a filter/search widget would need to search across pages.~ Current thinking is to virtualize these lists and have them infinitely scroll, and load as you scroll.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kumudt** [comment]
Really looking forward to this pagination feature....

**Comment by moedeek** [comment]
Can't wait to see pagination in charts! I have lots of data that I want to present in charts, but they end up looking very bad when presented in one view, pagination would help me in charts.

**Comment by atapatel** [comment]
+1 for this feature.

**Comment by yoldar** [comment]
Especially in tables. All data is loading at client side. It would be better to download each page when it needed.

<img width="1297" alt="Screen Shot 2019-03-28 at 12 15 21" src="https://user-images.githubusercontent.com/1597578/55134583-5fa07f00-5153-11e9-9343-515bec0e08a9.png">

**Comment by marcnaweb** [comment]
Hi @yoldar (waiting for this feature to be available) how did you implemented the pagination displayed on your screenshot?

**Comment by flamber** [comment]
@marcnaweb There's visual pagination on tables, when displaying them on a dashboard.

**Comment by tlrobinson** [comment]
Since #10134 was closed I wanted to point out that for `GET /api/database` specifically we will likely be removing `include_cards` since it doesn't make sense to load every single question when showing the database/table picker when an instance has thousands of questions. We will probably need to replace `Saved Questions` fake "database" with a search widget, and/or just allow admins to promote specific questions to appear as tables.

**Comment by tlrobinson** [comment]
Also for clarification, there are two distinct types of pagination we're talking about here:

1. paginating Metabase artifacts (search results, questions, dashboards, etc) which @mazameli mentioned in the original issue
2. paginating query results, specifically in table views, which others have mentioned in the comments

**Comment by RobertLowe** [comment]
Pagination and Working Columns #9144 seem wildly important to me for a successful product

**Comment by Charuru** [comment]
I need pagination on the collections(tables) page as I have many hundreds of thousands of collections for all my buckets.

**Comment by aviam** [comment]
need pagination control as well, want to decide how many rows will be displayed per page.
it's a must feature in any BI tool.

**Comment by RobertLowe** [comment]
@camsaul is this a pro feature?

**Comment by MrKotov** [comment]
Is this feature(s) request going to be addressed for query on top of /api/dataset ? Really show stopper for us.

**Comment by eddyizm** [comment]
Agreed @MrKotov Would love to know either way in order to make a decision.

**Comment by camsaul** [comment]
This issue isn't about supporting pagination for running queries with the `/api/dataset` endpoint -- see the issue description above. We already limit queries to the first 2000 rows by default. 

Most of the stuff listed here as part of the #15767 project -- @howonlee can we close this issue out at this point? I think the only bullet point here not addressed in #15767 was the Data Model stuff but that's not as much of an issue anymore since we don't fetch every Database and **all** of their Tables in a single API call there anymore

**Comment by flamber** [comment]
Closing, there's separate issue for regressions regarding this. There's an issue about the hardcoded amount of rows #4564.
