### ISSUE TITLE
Foreign key remappings aren't applied to nested queries

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#5507]
This is related to nested queries and user-defined column remapping features that will be part of 0.25. I have both a FK remapping (Product) and a custom field value remapping (Review). In the original query the remappings are applied correctly:

<img width="1405" alt="screen shot 2017-07-18 at 16 58 07" src="https://user-images.githubusercontent.com/6034928/28344773-a7bf4c72-6bda-11e7-99d7-b4c3bf57ace0.png">

If I create a new question using that question as a basis, the FK remapping is missing and the original foreign key value is shown instead:

<img width="1387" alt="screen shot 2017-07-18 at 16 59 22" src="https://user-images.githubusercontent.com/6034928/28344757-8b6a88a2-6bda-11e7-863a-c33662ec1c3f.png">

**Comment by senior** [comment]
https://github.com/metabase/metabase/pull/8263 provides the backend work needed for this. I think all that is needed to get this to work is to convey to the query builder that the nested query has FK information.

**Comment by senior** [comment]
After talking with @tlrobinson, I realized that what this ticket is asking for (strictly FK remappings for nested queries) is fixed by https://github.com/metabase/metabase/pull/8263. The change needed for my comment above is a separate issue that I have written up as https://github.com/metabase/metabase/issues/8272.
