### ISSUE TITLE
Error when connecting to Azure Cosmos DB

### ISSUE THREAD

**Issue by sebastianbk** [metabase/metabase#5571]
I have just created a new [Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction) and I am trying to connect my Metabase instance to it. Azure Cosmos DB exposes a MongoDB-compliant interface, which should work out-of-the-box with any MongoDB driver ([see here](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction)). I successfully connected to the Cosmos DB instance from the `mongo` shell on my desktop so the connection seems to be working as it should. However, I cannot get Metabase to connect to it.

I am running Windows 10 along with Docker for Windows and I have pulled the latest image from Docker Hub (v0.24.2). During setup of my newly created Metabase instance I entered the credentials for my Cosmos DB, as it can be seen in the screenshot below.

![SS1](http://i.imgur.com/FJTORYi.png)

Everything should be fine but, when I try to click **Next**, I get the following error:

```
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=vrinnobitest.documents.azure.com:10255, type=UNKNOWN, state=CONNECTING}]
```

When connecting to the database with the `mongo` shell, it worked. Also, I made a small Node.js application connecting to the database. That also worked. I double-checked that the Docker container indeed does have access to the internet (it does) so the problem isn't that Metabase doesn't have an external internet connection. I also downloaded the SSL certificate used by Azure Cosmos DB inside of the container and trusted it but that wasn't the issue either.

I really can't seem to think of a solution to this problem so I am crossing my fingers that you will be able to help me. Metabase is an awesome product and I am really thankful for all of your work. Getting it to work with Cosmos DB would make me incredibly happy so hopefully there is a quick fix to this issue.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sebastianbk** [comment]
FWIW, I also tried setting the connection string options to `ssl=true&replicaSet=globaldb` but that didn't work either.

**Comment by sebastianbk** [comment]
To anybody interested in picking this one up, I would be happy to set up a test instance of Azure Cosmos DB to help solve this bug.

**Comment by alessandrotravi** [comment]
@sebastianbk same error

**Comment by farzadshafiee** [comment]
We are having a same issue with a mongodb deployment behind OpenShift.
We couldn't connect to mongo even from the `mongo shell v3.2.9`, but when we upgraded to `mongo shell v3.4.7`, we could successfully log into the database. We had the same issue with some older version of the `robomongo/robo 3T` and an update resolved the issue. 

I was looking at metabase dependencies and realized that it is using an older version of `monger` driver

https://github.com/metabase/metabase/blob/36bbc87120c79bb2ba4831bbdfb3fa01ecf0b660/project.clj#L53

If you look at the [monger](https://github.com/michaelklishin/monger/blob/master/project.clj) repository you will realize that [`monger v3.1.0` is using v3.3.0 mongodb driver](https://github.com/michaelklishin/monger/blob/3e5f16d14602f1ab83ddbbfed22d6188a07e4f94/project.clj#L8) and [`monger v3.2.0` is using the v3.4.0 mongodb driver](https://github.com/michaelklishin/monger/blob/319872d5bcb02a223e42e80fc7263a6359722b1f/project.clj#L8). If you look at commit message you'd see that this driver upgrade is specifically aimed to [resolve some issues with SSL connections.](https://github.com/michaelklishin/monger/commit/319872d5bcb02a223e42e80fc7263a6359722b1f)

**Comment by sebastianbk** [comment]
@salsakran, do you think the suggestion from @farzadshafiee could solve this issue?

**Comment by rafaheringer** [comment]
Exactly same error here :(

**Comment by sebastianbk** [comment]
@salsakran: Any update on this?

**Comment by camsaul** [comment]
@farzadshafiee [3.1.0 is still the latest stable release of Monger](https://github.com/michaelklishin/monger). Once 3.2.0 is released we'll upgrade Metabase to use it but we're generally wary of updating to "snapshot" dependencies since they might end up breaking something else

**Comment by sivarselva** [comment]
any update on this? Even I facing the same problem.. 

Thanks
Selva

**Comment by camsaul** [comment]
I just posted on the Monger mailing list asking when they plan to release the updated driver. If they don't plan on releasing it in the near future I think we should go ahead and switch to a snapshot version rather than wait what may be several more months

**Comment by toddheslin** [comment]
Hey everyone, could be related to this: https://jira.mongodb.org/browse/TOOLS-1920

**Comment by abn** [comment]
Verified that monger-3.1.0 can be used to connect and query Azure Cosmos DB. It seems that the issue reported here is caused due to 3 separate issues.

1. [Missing ability to enable SSL for database connections](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx#L165). This form field was removed, it would appear, during the [transition from angular to redux](https://github.com/metabase/metabase/commit/0824b4b56b8a1df4c9fb154db57c5c418da1e1f3#diff-d105eaaaeae1ef68029a359f76df3fdaR58). This has left this option non-configurable and relying on the defaults.
2. [SSL disabled by default for the mongo driver](https://github.com/metabase/metabase/blob/master/src/metabase/driver/mongo.clj#L194-L197). This default value gets used due to (1) and then overrides `ssl=true` even when specified in the additional parameters due to the [setting of `sslEnabled`](https://github.com/metabase/metabase/blob/master/src/metabase/driver/mongo/util.clj#L67).
3. DB stats returns with `ok=1` (integer) as opposed to the expected `ok=1.0` (float) when calling [`can-connect`](https://github.com/metabase/metabase/blob/master/src/metabase/driver/mongo.clj#L24-L29).

(1) can be side-stepped by relying on the additional parameter for ssl configuration, however this would mean that `sslEnabled` should not be set as indicated by (2).

(3) could potentially be worked around by casting the returned value into a float.
```clj
    (= (float (-> (cmd/db-stats conn)
                  (conv/from-db-object :keywordize)
                  :ok))
       1.0)))
```

By resolving these locally, I was able to connect to the Azure Cosmos DB instance, however there were other failures when doing data exploration etc. due to how the queries were done. Have not dug into it much, however it might be likely that support for Azure Cosmos DB should be added as a separate driver either from scratch or inheriting from the mongo one. Issues (1) and (2)  is likely what @farzadshafiee  has been encountering against a MongoDB server.

@sebastianbk @camsaul hope this helps.

**Comment by abn** [comment]
Looks like the logic in `metabase.api.database.test-connection-details` forces runs with both `ssl=true` and `ssl=false`. So (1) and (2) should be non-issues.
