### ISSUE TITLE
Materialize Questions used as Sub-Queries

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5596]
To allow end users to better optimize performance when users are using a slow query as a nested subquery, we could provide a way to "save" the question as a materialized view in databases that support.

Note that this would require us to change the default assumption that drivers are read-only.

Bonus points for then replacing the nested subquery with the new materialized table id in all questions that depend on it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by anshum4n** [comment]
Can the materialised view be a table in another database if the source doesn't support it?

For example, I am using Google Analytics and would love a materialised view to be created in my mysql data-store, allowing to join with rest of the tables and query on top of it.

Thats a light weight ETL and in principle allows querying across datasources as long as the data isn't too huge. If its too huge, moving from one source to another doesn't make sense. 

I have now used two dirty words - joins & etl in a single comment, so maybe that is in too complicated too powerful category. Would love to hear where everyone else stands on that.

**Comment by wvengen** [comment]
@anshum4n I think that would be a another feature that perhaps could build on this one, which is about using a database-native materialized view.

This reminds me of Metabase's caching functionality: but here the cache is not in Metabase but in the database.
I could imagine the save question dialog having a checkbox that would materialize the question, or a caching button the lower right (next to the sharing, alert and download buttons) where one could enable/disable materialization and refresh it when applicable.

A later feature could be to auto-refresh (selected?) materialized questions on a schedule, or apply the regular Metabase caching policies to the materialized questions as well.

We'd need to decide whether to store the generated views in the selected db schema, or if a custom db schema is used for that (like `metabase` instead of `public` for PostgreSQL). Does this need to be customizable?

Another question is whether all users can do this, only admins, or if an extra permission is required. When write permissions are not available on the database, the feature should certainly be not visible/accessible.

**Comment by wvengen** [comment]
What I imagine is a common scenario is connecting Metabase to a follower/slave, which Metabase cannot write to. Therefore materializing questions would require access to a database instance with write-capabilities. For PostgreSQL adding a write-database-server-address could be enough, but I'm not sure about other drivers.

**Comment by wvengen** [comment]
I've created an external webapp that implements this (with limitations): [metabase-matview](https://github.com/q-m/metabase-matview).

**Comment by camsaul** [comment]
This was implemented as Model Persistence in 0.44, in Epic #22538 and others
