### ISSUE TITLE
Allow editing permissions for saved questions "database"

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5610]
The Permissions admin panel is showing me that all groups are not allowed to use them, but when I go to the query builder I can still use a saved question at a table.

**Comment by camsaul** [comment]
Permissions for using saved questions are based on whether someone has permissions for the original question. e.g. if you have permissions for Question 2 then you can use Question 2 as a nested query.

Saved Questions should *not* be showing up in the permissions graph

**Comment by salsakran** [comment]
I think it should so that admins can do things like turn off nested queries for classes of users if they find they're having issues with it.

"eg don't let non-analysts create nested queries" seems like a reasonable sorta thing.

**Comment by salsakran** [comment]
Would this require a change to the nested query portion of the metadata fetching api endpoint?

**Comment by camsaul** [comment]
Having separate permissions for nested queries would require more than just changing the API endpoint, it would definitely require non-trivial changes. So probably not something that should go in a patch release IMO.

I think it makes sense for the time being just to make sure the Saved Questions DB isn't showing up in the permissions panel (I'm guessing it must be using the same metadata API endpoint that powers everything from the Query Builder to the Data Reference) since it shouldn't be in there based on the way the code currently works.

In the future (26?) we can do a follow-on to add a whole new level of permissions for using nested queries and showing that pseudo DB in the permissions graph if desired.

**Comment by salsakran** [comment]
cool. I'm going to change this from a bug to an enhancement then.

**Comment by salsakran** [comment]
if people decide they really need to turn it off for whatever reason, please chime in here and we'll prioritize based on urgency/demand.

**Comment by camsaul** [comment]
Saved Questions showing up in the admin panel is still a bug IMO, especially if it doesn't really do anything. And that should be an easy fix, just need to switch it to use the API endpoint without passing the `include_cards=true` param like you did for the Data Ref

**Comment by BlankRain** [comment]
@camsaul   when remove `include_cards=true` in the service.js 
As except, Saved Questions doesn't show in the admin panel . However, it also doesn't show in the QueryBuilder when I ask new question or edit question.

**Comment by BlankRain** [comment]
It should show in the QueryBuilder and not show in the admin panel. right?

**Comment by BlankRain** [comment]
@camsaul  remove `include_cards=true` is not a good solution.

change the code in this line .
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/permissions/selectors.js#L368
`
const databases = Object.values(metadata.databases).filter((x)=>x.is_saved_questions ==null);
`
Then , the saved question won't show in the admin panel.

**Comment by EvaSchreyer** [comment]
Hi, I use latest version 0.28 and still see saved questions in my permissions list and I am not able to change the permissions, as the administrators can´t get acces somehow, and all users, who could get access, are not allowed to have more permissions than admins. Can you please don´t show saved questions in the permissions section anymore? thank you :)

![grafik](https://user-images.githubusercontent.com/28557318/37472967-97b7f7f2-286d-11e8-8105-e5a821a6d0d7.png)

**Comment by RMMSecurity** [comment]
Still seeing it here. It only seems to show up at first load of the permissions page and not again until a new session.

**Comment by camsaul** [comment]
@RMMSecurity what version are you using?

**Comment by adamfeldman-ris** [comment]
I just set up a new instance of 0.32.7 and ran into this. It's left me unable to make questions which use SQL queries.

**Comment by adamfeldman-ris** [comment]
Issue still occurs on 0.32.8

**Comment by tlrobinson** [comment]
FYI part of the confusion here is there's a UI bug in the Permissions panel where it shows every database that has been previously been loaded, rather than just the list of databases from `/api/database`. If you happened to load the query builder before visiting Permissions panel then `Saved Questions` will appear in the Permissions panel even though you can't edit the permissions for it. 

Basically the selector for getting the databases is currently something like `Object.values(state.entities.database)` instead using the entities system, like `Databases.selectors.getList(state)` (but we need to make sure we use `Databases.actions.fetchList()` to populate that list)

**Comment by adamfeldman-ris** [comment]
@tlrobinson is it expected that this bug is preventing me from creating custom SQL-based questions?

**Comment by tlrobinson** [comment]
@adamfeldman-ris I'm not sure that's related. Can you try changing permissions without modifying any "Saved Questions" permissions, or are you in a state where you can't edit permissions even if you ignore the "Saved Questions" row?

**Comment by adamfeldman-ris** [comment]
Thank you for the quick response. I got it working -- when I make a particular mistake in the syntax of my SQL query it gives a permissions error.

**Comment by timmclaughlin** [comment]
I think there are two bugs:

@tlrobinson is correct in that after I load the query editor, the "Saved Questions" row shows in the UI.  Before Query editor use it looks like:
![image](https://user-images.githubusercontent.com/3425622/62423980-41650580-b696-11e9-8d2c-baa3233780e2.png)

And after loading the Query editor it looks like (and I attempted to fix my permissions):
![image](https://user-images.githubusercontent.com/3425622/62423967-2b574500-b696-11e9-9dce-30d0613bc887.png)

But it regardless of the UI problem, I still can't allow all users to use Saved Questions because "Save Changes" has no effect because it fails with this in the logs:
Aug 04 12:54:52 ERROR metabase.middleware.log :: PUT /api/permissions/graph 500 7 ms (0 DB calls) 
{:value
[{:revision 8,
:groups
{7 {3 {:native :none, :schemas :none}},
1 {3 {:native :none, :schemas :none}, -1337 {:native nil, :schemas :all}},
4 {3 {:native :none, :schemas :none}},
6 {3 {:native :none, :schemas :none}},
12 {3 {:native :none, :schemas :none}},
2 {3 {:native :write, :schemas :all}},
11 {3 {:native :none, :schemas :none}},
9 {3 {:native :none, :schemas :none}},
5 {3 {:native :write, :schemas :all}},
10 {3 {:native :none, :schemas :none}},
8 {3 {:native :none, :schemas :none}}}}],
:error [(named {:groups {1 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
:message "Input to update-graph! does not match schema: \n\n\t [(named {:groups {1 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)] \n\n",
:type clojure.lang.ExceptionInfo,
:stacktrace
("--> models.permissions$fn__26804$update_graph_BANG___26813.invoke(permissions.clj:603)"
"api.permissions$fn__61776.invokeStatic(permissions.clj:80)"
"api.permissions$fn__61776.invoke(permissions.clj:68)"
"middleware.auth$enforce_authentication$fn__45957.invoke(auth.clj:14)"
"routes$fn__63780$fn__63781.doInvoke(routes.clj:56)"
"middleware.exceptions$catch_uncaught_exceptions$fn__45861.invoke(exceptions.clj:104)"
"middleware.exceptions$catch_api_exceptions$fn__45858.invoke(exceptions.clj:92)"
"middleware.log$log_api_call$fn__45779$fn__45780.invoke(log.clj:170)"
"middleware.log$log_api_call$fn__45779.invoke(log.clj:164)"
"middleware.security$add_security_headers$fn__45822.invoke(security.clj:105)"
"middleware.json$wrap_json_body$fn__46040.invoke(json.clj:61)"
"middleware.json$wrap_streamed_json_response$fn__46058.invoke(json.clj:97)"
"middleware.session$bind_current_user$fn__46172$fn__46173.invoke(session.clj:193)"
"middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
"middleware.session$do_with_current_user.invoke(session.clj:170)"
"middleware.session$bind_current_user$fn__46172.invoke(session.clj:192)"
"middleware.session$wrap_current_user_id$fn__46161.invoke(session.clj:161)"
"middleware.session$wrap_session_id$fn__46146.invoke(session.clj:123)"
"middleware.auth$wrap_api_key$fn__45965.invoke(auth.clj:27)"
"middleware.misc$maybe_set_site_url$fn__45924.invoke(misc.clj:58)"
"middleware.misc$bind_user_locale$fn__45927.invoke(misc.clj:74)"
"middleware.misc$add_content_type$fn__45912.invoke(misc.clj:30)"
"middleware.misc$disable_streaming_buffering$fn__45949.invoke(misc.clj:119)"
"middleware.misc$wrap_gzip$fn__45942.invoke(misc.clj:101)")}

**Comment by timmclaughlin** [comment]
@salsakran Not sure why you don't consider this a bug...  It pretty much breaks the security model altogether that previously used to work for Saved Questions.

**Comment by mazameli** [comment]
@timmclaughlin The way this is supposed to work currently is via _Collection_ permissions. If a user has View access to a question in a particular collection, they should be allowed to select that question as starting data for a new question. Is that the behavior you're experiencing?

**Comment by timmclaughlin** [comment]
@mazameli I'm actually trying to give my users read only use of Metabase.  They have access to a particular collection, and then have read only access to the database so that they can view the results.  I do not want them to be able to create new questions.  I would be fine if they created new derived questions from the questions that they have access to, but that did not seem possible previously.  It would certainly be cool if that was possible now.

**Comment by flamber** [comment]
Fixed by #10692 in 0.33.1 - showing "Saved Questions" in Admin > Permissions was a bug.
