### ISSUE TITLE
Don't show saved questions in the permissions database lists

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5617]
Until #5610 is closed, there's no point in having it there as it is confusing to imply that its permissions are editable.

**Comment by mazameli** [comment]
Reopening this. It's reoccurring in `release-0.33.x`.

Repro by:
- clicking Ask a Question
- pick Custom Question
- then go to the Admin Panel, then click on Permissions
- you'll see the Saved Questions pseudo DB:

![image](https://user-images.githubusercontent.com/2223916/63117407-99322500-bf50-11e9-97ac-6bd68ecc6833.png)

This issue is what I believe is at the root cause of confusion in these newer issues:
- https://github.com/metabase/metabase/issues/8352
- https://github.com/metabase/metabase/issues/10499

**Comment by tlrobinson** [comment]
This is probably a frontend thing so I'm switching assignee to me.

**Comment by paulrosenzweig** [comment]
Resolved by #10692
