### ISSUE TITLE
frequency of taking data incorrect

### ISSUE THREAD

**Issue by miguinarry** [metabase/metabase#5752]

**Comment by camsaul** [comment]
Hi @miguinarry, it sounds like maybe you meant this issue for some other project? I'm guessing that's the case since it was about weird gyroscope/accelerometer readings on iOS 10 and Android, which isn't something we're planning on shipping until at least 0.29.0 later this year. 

If that's indeed the case please just close your issue instead of leaving it open and deleting the description.
