### ISSUE TITLE
Separate positive / negative stacked bar charts

### ISSUE THREAD

**Issue by koenbok** [metabase/metabase#5763]
I'm trying to achieve a specific kind of stacked bar chart for an active user graph separated out by retained, created, resurrected (positive) and lost (negative) like:

![image](https://user-images.githubusercontent.com/206779/29387932-c879903e-82e2-11e7-8679-2d351373fce1.png)

The way Metabase works is that it kind of draws the negative over the positive bars. It makes mathematical sense, but I don't really see why you would ever want that.

Is there a way to make Metabase draw a graph like the above?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
I'd call this a bug since it currently displays fairly nonsensical charts:


```sql
SELECT day, nu, ru, cu FROM (VALUES
  (1,200,300,-300),
  (2,100,400,-200)
) t1 (day, nu, ru, cu)
```

Unstacked is correct:

![Screenshot 2019-10-29 11 44 10](https://user-images.githubusercontent.com/18193/67798862-8f916700-fa41-11e9-9537-c4b1a61e689f.png)

Stacked is summing negative and positive values instead of separating them out:

![Screenshot 2019-10-29 11 44 05](https://user-images.githubusercontent.com/18193/67798902-9f10b000-fa41-11e9-807b-ee6c55a4e9eb.png)

**Comment by brettjarthur** [comment]
Hi; any news on when this bug will be fixed?

**Comment by billbither** [comment]
This is a limitation for us currently to visualize ARR movement, both positive (new ARR) and negative (churned ARR) on a single chart. Same use case as the one posting. The stacked version just doesn't make visual sense and seems to be a bug.

This is what we want it to look like:
![image](https://user-images.githubusercontent.com/5885418/121961856-f27a6380-cd35-11eb-8a81-c02ce48584dd.png)

**Comment by annafedotova** [comment]
what happens to me now is that when I display values for the stacked bar chart that has negative values, the sum only takes into account the positive values, but doesn't subtract the negative values

**Comment by flamber** [comment]
@annafedotova Please open a new issue with proper details filled out.
