### ISSUE TITLE
[Question] Merging 2 existing Metabase instances

### ISSUE THREAD

**Issue by zocoi** [metabase/metabase#5818]
### Question

We have 2 instances of Metabase one running on Heroku with postgres and another one running on AWS with local H2 db.

Due to growing demand and Heroku 30s limit, I need to consolidate 2 instances to a new one running AWS beanstalk

Each existing instance has its own dashboards and questions. Is there any feasible way to merge them into one?

My current approach is:
1. Convert H2 to postgres and use it as a base db
2. Dump the second postgres into SQL inserts
3. Import the SQL dump into the first db
-------

Let me know if you have any feedback. Thanks

**Comment by camsaul** [comment]
I think that's going to be tricky because you'll have multiple objects with the same ID. For example both will probably have a few Users in there with IDs 1 and 2. And trying to change those IDs would leave other things that have foreign keys to those Users broken. (And so on and so forth.)

Honestly I'm not sure how easy it will be to get this to work but please let us know how it goes for you. Best of luck.

**Comment by mbvictoria** [comment]
Closing - no responses/updates since 2017.
