### ISSUE TITLE
Feature request : Question's parameter containing the current username

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#5823]
Dear all, thank you for providing us with such a powerful analytics tool !

It would be great to show data relating only to the current user.
Could it be possible to have a constant string parameter containing its username ?
{{mb_login}} for example ?

This parameter could be also available in the Question filter, and as a possible default value in the Dashboard filters.

Thank you !

**Comment by mazameli** [comment]
This is possible to a limited degree by [embedding a Metabase dashboard or question in a wrapper web application](http://www.metabase.com/docs/latest/administration-guide/13-embedding.html), which would allow you to pass a user ID parameter to the dashboard/question. 

Are you trying to do something like enable clients/customers to log into a Metabase instance, but only see data pertinent to them? If so, another way we're looking at doing this is via [row-level permissions](https://github.com/metabase/metabase/issues/2824).

**Comment by sldorman** [comment]
This would be very helpful to me as well.  I don't want to embed the dashboards into my own app because the users want to interact with Metabase.  Ideally, my app would populate the table data with the user name and then launch Metabase, automatically logging in as that user (I know the auto login is a different issue, I'm just explaining my ideal use case).  The dashboards would appear and show only the data that pertains to that user.  Even if the filter id on the dashboard could be pre-populated with the logged in user name or email address, that would be helpful.  The {{mb_login}}  parameter is a better solution though.

**Comment by fetanchaud** [comment]
IMHO it is now included in #2824
