### ISSUE TITLE
Binning isn't available when using nested questions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5938]
On Chome on release-0.26.0. Not sure if this was known/expected.

Normal query, which allows binning this field:

![screen shot 2017-09-11 at 4 12 08 pm](https://user-images.githubusercontent.com/2223916/30300922-330461b2-970c-11e7-8797-01b3fb536d4e.png)

That same table, but as a saved question used as a nested query — notice the binning options aren't there:

![screen shot 2017-09-11 at 4 12 51 pm](https://user-images.githubusercontent.com/2223916/30300933-482af330-970c-11e7-8364-c19bf0df895b.png)

**Comment by senior** [comment]
While working on #6166, I looked into this issue as well. The fix #6166 works for dates and coordinates as the binning options are derived form the base type and special type. Those type values are stored with the card in the results_metadata field. To bin integer values we need min/max values from the fingerprint field which is not currently included in results_metadata. Once we get that added to results_metadata, the fix for #6166 should work here too.
