### ISSUE TITLE
Analysis should run at least once on the sample dataset

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6003]
We don't currently run analysis on the sample dataset (see [this code](https://github.com/metabase/metabase/blob/master/src/metabase/task/sync_databases.clj#L170)). This means we won't have fingerprints or binning on the sample dataset.

Not sure what the best way to go about this change is. Maybe run it after the sample dataset is populated? The problem with that is more around developer testing. Since we don't have a way to manually initiate analysis today, one and done analysis doesn't allow us to add to the analysis in the future. Another option would be to only run it if the fingerprint version is old? Not sure what the original intent was behind omitting the sample dataset, but seems like we want it.

**Comment by salsakran** [comment]
the original notion was that since the sample dataset was artificially generated, all the things that analysis produced back then could be directly inserted (eg, semantic types). Now that we're doing min/max,etc we should probably run it through.

**Comment by camsaul** [comment]
We should probably just take out the `:is_sample false` thing since analysis is going to take milliseconds anyway since the dataset is so small

**Comment by camsaul** [comment]
So actually analysis *does* happen when the sample dataset is added (either on first launch or if you click "bring the sample dataset back" in the Admin panel): https://github.com/metabase/metabase/blob/master/src/metabase/sample_data.clj#L30

Since the binning stuff wasn't added until 0.26 any instances that upgraded to that version won't see the new stuff. But manually triggering a sync in the admin panel should fix things.

We can add the sample dataset to sync task so it gets analyzed to bring older instances up-to-date if you guys want

**Comment by salsakran** [comment]
Does that behaviour (an upgrade from pre 0.26 not resulting in a new analysis) hold for real databases as well?

If so, that's problematic as that means binning shipped broken for all existing users. =(

**Comment by camsaul** [comment]
@salsakran no because sync gets ran for every other database on a regular basis and analysis is done when needed (when Fingerprint is out of date for column type). Except for DBs that aren't "full sync". We're specifically excluding the Sample Dataset from the scheduled sync/analysis process

**Comment by camsaul** [comment]
=)
