### ISSUE TITLE
[TABLES] Fixed decimal precision

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#6007]
Will be good if we can configure the number of precision in decimals, it's not good for insights:

![screenshot from 2017-09-19 10-46-03](https://user-images.githubusercontent.com/6808348/30595509-cddbe98c-9d27-11e7-8e5e-a62fdaaaf431.png)

**Comment by Sytten** [comment]
I support this proposal, my application requires at least 6 decimals to be significant...

**Comment by dannyeuu** [comment]
Please @Sytten send :+1: on the issue to get more visible.

**Comment by flamber** [comment]
Hi @dannyeuu 
Visualization settings supports defining minimum number of decimals since 0.31. You can define it for each question's column/data. But it's not possible to set a global value yet.
![image](https://user-images.githubusercontent.com/1447303/52974224-6be03200-3386-11e9-8111-ba7ec4686b56.png)

**Comment by dannyeuu** [comment]
That’s right @flamber ! We use the latest v0.31.1, I forgot to close this issue.
