### ISSUE TITLE
Field Filter's Default Value Not Working

### ISSUE THREAD

**Issue by ivanaclairineirsan** [metabase/metabase#6059]
Hi, I want to address an issue I encountered when using `Date Filter` on queries' field filter type variable. 
Our objective is to allow user custom their report date using Date Filter on Dashboard. 
However, when the Date Filter is cleared on the dashboard, all questions will show all data in the database, which is pretty huge, time consuming, and make the visualization too crowded. 
To avoid this, we wanted to set default value for `date filter` on each question, but it appears that default value for field filter is not working, and did not affect the date range of the report.

- Browser: Chrome 60.0
- Operating system: OS X 10
- Database: Postgres
- Metabase version: 0.25.2 and 0.26.0 (tested on 2 versions of metabase)
- Metabase hosting environment: Docker

`*Repeatable steps to reproduce the issue*`
1. Create new question, and add field filter variable to set the date (my query:

```
SELECT count(*) AS "count", "created_at"
FROM messages
WHERE {{filter_date}}
 ```

2. set Field to `Messages - Created` 
3. pick Date Filter for widget type
4. set default value to `Previous 5 days`, and run query.

This is the result I get when following steps above (on 27 September 2017). The oldest date that should be reported is 22 September 2017, but it shows reports from March 2017.
![image](https://user-images.githubusercontent.com/7076833/30920722-e274a1d8-a3ce-11e7-9874-494f930e6151.png)

please add a :+1: reaction to the description of this issue. Please DO NOT add `+1` or :+1: comments.

**Comment by EvaSchreyer** [comment]
Hi, I have a similar (maybe the same?) bug since we updated to v0.26.1 yesterday. Most of my dashboards have date filters and the default value is last 30 days. This default value is not updating anymore since yesterday, so it shows me data until the day before yesterday, not days including yesterday as it should today. 
When I change the filter to between date and date it works.

**Comment by salsakran** [comment]
bumping this up since it's a regression.

**Comment by mazameli** [comment]
There's definitely a bug with field filter default values not affecting the query. But there's also a weird UX behavior with default values that I _don't_ think is a regression, which is that [field filter default values don't carry over to dashboards](https://github.com/metabase/metabase/issues/4840).

**Comment by mazameli** [comment]
We should really fix this one before 0.27 if possible.

**Comment by EvaSchreyer** [comment]
Hi, this issue is still not solved (or again a new issue?) in v0.28. I use a SQL database and the relative date filter on dashboard level does not include the expected days.

**Comment by mazameli** [comment]
@EvaSchreyer Let me see if I'm understanding your situation correctly:

- You have a SQL question with a field filter variable that is mapped to a date field
- That SQL question is on a dashboard
- The dashboard has a relative date filter that is connected to the SQL question's field filter variable
- The dashboard relative date filter has a default value of `Past 30 days`
- This next part is where I'm confused: is it that whenever you open up that dashboard, it's not correctly filtering the SQL question to the past 30 days? Or is it that you keep the dashboard running/opened and auto-refreshing on a TV or something, and when a new day starts, the filter doesn't correctly update?

Would it be fair to say the problem you're describing is a different issue, and that we should open a new one for it? This issue is strictly limited to default values on filter widgets for SQL questions themselves, unrelated to dashboard filters.

**Comment by EvaSchreyer** [comment]
Hi @mazameli, it is as you describe it, when I open the dashboard in v0.25 the default filter value last 30 days works correctly and shows my data until yesterday. When I open the same dashboard in v0.28 I get only data until the day before yesterday (even if data until yesterday can be selected when I use the filter "yesterday". So I think it is the same issue again - as the filter works correctly, but the default value last 30 days is not working. What do you think?

**Comment by EvaSchreyer** [comment]
Also the new function "include today" does not change anything for the result in v0.28.

**Comment by mazameli** [comment]
@EvaSchreyer thanks for the additional info, Eva. I've opened a separate issue for this here: https://github.com/metabase/metabase/issues/6994

**Comment by EvaSchreyer** [comment]
Thanks @mazameli !
