### ISSUE TITLE
java date warning on initial launch

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#6080]
### Environment
- Linux Mint 18 Sarah
- Timezone operating system: CEST
- MySQL Ver 14.14 Distrib 5.7.19, for Linux (x86_64)
- Timezone MySQL: System = CEST
- Metabase version: 0.26.1
- Linux
- Metabase internal database: MySQL
- Java: openjdk version "1.8.0_131"

### Steps

- I downloaded the 0.26.1 jar file.
- I setup MySQL for metadata using environment variables.
- Launch metabase from command line with java -jar

### Warning message

While applying the database changes I saw this java error four times:

```
09-30 20:42:04 WARN sync-metadata.sync-timezone :: Error syncing database timezone
java.lang.Exception: Unable to parse date string '2017-09-30 20:42:04.414 CEST' for database engine 'h2'
Caused by: java.lang.IllegalArgumentException: Invalid format: "2017-09-30 20:42:04.414 CEST" is malformed at "CEST"
```

**Comment by senior** [comment]
This is just a warning and can be safely ignored. The issue is the Java library we're using (JodaTime) doesn't recognize the timezone abbreviation (CEST) MySQL is including the the date string. We are planning to move to `java.time`, a new time library included in the JDK that does recognize the timezone and will no longer give that warning.
