### ISSUE TITLE
Allow a `MB_DB_SSL` to force secure connection to the AppDB

### ISSUE THREAD

**Issue by alikhan-io** [metabase/metabase#6095]
AFAIK there is no easy way to enable SSL communications for the connection to the metabase database. We are deploying via Elastic Beanstalk.

Is there any documentation or workaround on this? Part of our goal is to be 100% encrypted end to end on communications.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by imsky** [comment]
@alikhan-io seems possible here: https://github.com/metabase/metabase/issues/3296

**Comment by salsakran** [comment]
We don't currently offer this in our quick start template. It should be doable, but you'd probably have to override the RDS configuration in the setup wizard.

**Comment by camsaul** [comment]
@salsakran actually you can only specify SSL/TLS for Postgres or MySQL application DB details if you pass them via the `MB_DB_CONNECTION_URI` (i.e., connection string) env var. If you pass app DB details via the alternative broken-out env vars (`MB_DB_USER`, `MB_DB_HOST`, etc.) we actually don't have a way for you to configure SSL. So I think we should probably add another env var and call it something like `MB_DB_SSL` to force SSL connections if you chose to pass in DB details that way. (Personally I prefer the broken-out details because it makes it easier to deal with DB passwords that have special characters.)

Once that's in place it would be nice to tweak our EB script to use TLS for the application DB connection

**Comment by camsaul** [comment]
Closing as Won't Fix. In Metabase 0.43.0 you can use `MB_DB_CONNECTION_URI` (in combination with `MB_DB_PASS` and `MB_DB_USER` if needed) to set any options you want
