### ISSUE TITLE
Can anyone please help me setup metabase?

### ISSUE THREAD

**Issue by Bryze** [metabase/metabase#6101]
Apologies if it may sound trivial. 
I want to develop a new visualization graph, so, I recently forked a copy of metabase and am trying to run it on my end.
Installed node,yarn. Did `npm install`.
Got these warnings
![image](https://user-images.githubusercontent.com/10598701/31214750-611a8c2c-a9ca-11e7-939d-f4d5749ddf6f.png)

When I compile it using, `npm run build` , it shows me this
![image](https://user-images.githubusercontent.com/10598701/31214782-80c2e416-a9ca-11e7-9f85-171faf632571.png)

Above is the error, please guide.

**EDIT** - I checked the `node modules` directory in the metabase root, it has all the files required. But, somehow the last few lines in the error shows that it's trying to search `node modules` in drive `D:` which is not the current location.

Here is an additional screenshot, if it helps
![image](https://user-images.githubusercontent.com/10598701/31214968-5ce15360-a9cb-11e7-9bf3-3e933a594d79.png)

**Comment by attekei** [comment]
Hi @Bryze! Could you install yarn and try `yarn install && yarn run build` instead? We don't support `npm` anymore although I'm not completely sure if the error is related to that or not.

Note also that there are some issues with some frontend build commands on Windows, see https://github.com/metabase/metabase/issues/5214#issuecomment-304957501. The basic `yarn run build` should work, though!

**Comment by Bryze** [comment]
Yes, tried it, but still the same error
![image](https://user-images.githubusercontent.com/10598701/31224202-9bcec5e8-a9ea-11e7-89c3-bc4cf80cee1e.png)

**Comment by attekei** [comment]
@Bryze Thanks! I think that the reason can be found here:
![screen shot 2017-10-05 at 14 02 08](https://user-images.githubusercontent.com/6034928/31224255-d80faf8c-a9d5-11e7-8e55-7ae7a9bd8c3e.png)

So Windows uses backslash and Mac uses slash as a directory separator and the build script gets confused because of that. I'll take a look on how to fix that.

**Comment by Bryze** [comment]
@attekei That might be issue but, does it explain why is it searching in some different directory than intended?

**Comment by attekei** [comment]
@Bryze It does because the backslashes in that path are ignored and as a consequence the relative path refers to  different location than where it should be.

Trying to address this and potential other issues with `yarn run build` in #6103

**Comment by lindsay-stevens** [comment]
@Bryze I had exactly the same issue yesterday. It seemed like there's something weird going on in the css-loader part of webpack (line 121 of the webpack config), but I didn't come to enough of an understanding to fix it.

However, a workaround that worked was to make a symlink from where webpack (or whatever) ends up trying to look for node_modules, back to where they actually are. That is (run as Admin):

```batch
mklink /D D:\node_modules D:\project\metabase-master\metabase\node_modules
```

This should allow the frontend build job to continue on it's merry way. However I ran into further issues trying to run the frontend integrated test suite. So I'm probably just going to use a Linux VirtualBox or cloud host for any work on this instead.

**Comment by attekei** [comment]
@lindsay-stevens 

> However I ran into further issues trying to run the frontend integrated test suite. So I'm probably just going to use a Linux VirtualBox or cloud host for any work on this instead.

Yeah, sadly there are other development issues on Windows too. A Linux VM is a working option but it makes the development work remarkably slower. I'll try to get at least the basic stuff working in #6103 and will notify you here when that is ready.

**Comment by jornh** [comment]
Depending on your Windows version you guys might have another option.

I’m on Windows 10 and I have it building nicely using WSL aka Bash on Ubuntu on Windows.

**Comment by Bryze** [comment]
@jornh can you reiterate the exact steps you used?

I think it has something to do with the underlying file system? I'm on a windows 10 as well and the screenshots are of the wsl bash

I don't know, probably yours might be a case of luck?

**Comment by jornh** [comment]
Yes, @Bryze looking at your second screenshot I now see the `$` prompt.

Not sure I’m able to give an exact step by step guide, it’s been a while since I installed and I struggled a but with getting yarn installed correctly. But looking above I spot a few differences:

- The Windows paths from your NPM run above suggests to me that you have the tooling installed as Windows versions. Is that correct? I installed everything inside WSL using `sudo apt-get ...`

- I use yarn as @attekei mentioned above

**Comment by Bryze** [comment]
> The Windows paths from your NPM run above suggests to me that you have the tooling installed as Windows versions. Is that correct? I installed everything (https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#install-prerequisites) inside WSL using sudo apt-get ...

@jornh  Yes, you're correct. Those are windows installations. I had some of the requirements already installed. So, I guess that might be the issue. The `.msi` installers might be the issue then. But, if that's the case, then all programs installed via executables, might have backward slashes in their path?

**Comment by mazameli** [comment]
@Bryze, you originally said:

> I want to develop a new visualization graph

What visualization type are you trying to develop?

**Comment by Bryze** [comment]
@mazameli I was thinking of a venn diagram visualisation. Where you can query the intersection points, and it relatively changes the size of the circles.

**Comment by attekei** [comment]
I tested the development workflow on Windows 10 (version 1703) with WSL and didn't have any issues. On my setup I cloned the repository and installed all dependencies inside Bash. I worked inside my Windows user directory because I wanted make sure that there are no problems with file system interoperability.

I will add a section to Developer's Guide about Windows development and emphasize there that dependencies installed outside WSL can cause problems.

**Comment by Bryze** [comment]
@attekei  Alright, I'll set it up again using WSL. Thank you for your time :)

**Comment by jornh** [comment]
@Bryze when you install “inside” WSL with `apt-get` you are doing a separate install in folders on the Linux side (in the Linux filesystem)

The only reason why you can call programs installed on the windows side from you WSL bash is due to this feature: https://msdn.microsoft.com/en-us/commandline/wsl/interop#invoking-windows-binaries-from-wsl

So it’s due to this interop feature that you were still getting Windows path problems from bash.

**Comment by camsaul** [comment]
@attekei Windows can use either backslash or forward slash as directory separators, it doesn't care

@jornh/@Bryze Most people recommend using `apt` instead of `apt-get` these days. e.g. `apt install`. It's easier to use

**Comment by camsaul** [comment]
These sorts of questions are best asked on https://discourse.metabase.com
