### ISSUE TITLE
Deleted table column not updating in metabase schema

### ISSUE THREAD

**Issue by Globegitter** [metabase/metabase#6146]
- Your browser and the version: Firefox 57.0b7 (64-bit)
- Your operating system: elementary OS 0.4.1 (built on Ubuntu 16.04.3)
- Your databases: Postgres
- Metabase version: 0.26.1
- Metabase hosting environment: Kubernetes Helm Chart
- Metabase internal database: Postgres

If I remove a column in a table from a database that is synced with Metabase, I see that this column is still showing up even after a manual database schema sync. Looking at the raw data for this table leads to following error:

`ERROR: column table.deletedColumn does not exist Position: 583` 

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by hennumjr** [comment]
Having the same issue.

- Your browser and the version: Firefox 56.0.1 (64-bit)
- Your operating system: iOS 10.12.6
- Your databases: Postgres
- Metabase version: 0.26.1
- Metabase hosting environment: Docker image
- Metabase internal database: Postgres

A table has changed and some fields are removed. Inspecting the Metabase metadata table, the rows look like this
```
  id  |   name    |       last_analyzed        | active
------+-----------+----------------------------+--------
 1    | deleted   | 2017-10-14 18:50:16.507+02 | f
 2    | exists    | 2017-10-14 23:50:07.893+02 | t
(2 rows)
```
The column that is deleted is correctly set to False in the meta data, but still shows up when looking at the data model in Metabase UI. When using the query builder, `ERROR: column table.deleted does not exist Position: 1` is thrown.

**Comment by disambiguator** [comment]
Seeing the same issue.

Your browser and the version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Your operating system: macOS Sierra
Your databases: Postgres
Metabase version: 0.26.1
Metabase hosting environment: Heroku
Metabase internal database: Postgres

Anyone have a workaround for now?

**Comment by cweems** [comment]
Not ideal, but if you hide the missing column from Metabase, you can run queries again. You can do this by following these steps:

* Go to the Admin Panel > Data Models
* Select the table from the side bar and scroll down to the missing column
* Click on the gear on the far right side
* Change visibility from "Everywhere" to "Do not include"

**Comment by danvanwijk** [comment]
Use at your own risk :)
Works for us to clean up all unused fields, field values and tables.

```
DELETE fv FROM metabase_fieldvalues fv
INNER JOIN metabase_field ON metabase_field.id = fv.field_id
INNER JOIN metabase_table ON metabase_table.id = metabase_field.table_id
WHERE (metabase_field.active=0 OR metabase_table.active=0);

DELETE f FROM metabase_field f
INNER JOIN metabase_table ON metabase_table.id = f.table_id
WHERE (f.active=0 OR metabase_table.active=0);

DELETE FROM metabase_table
WHERE active=0;
```

**Comment by sfortis** [comment]
i've the same issue. @danvanwijk how did you ran these queries on the metabase database?

**Comment by danvanwijk** [comment]
@sfortis what database are you using? Perhaps I should've made it more clear that we are running a MySQL database. If you are using a different one then the queries might need to be altered.

I've not tested this with the default built-in H2 database.

**Comment by sfortis** [comment]
@danvanwijk hmm ok, im (still) using the H2 embedded db. I've opened the db with H2 database browser and there are no metabase tables inside. Strange...

**Comment by Vadorequest** [comment]
Same issue with PostgreSQL, I deleted some columns in a view and Metabase doesn't seem to understand it was deleted.

I'll try to "Not include" those columns as a workaround for now, should work indeed.

**Comment by lenn4rd** [comment]
I adapted the SQL snippet @danvanwijk shared above for Postgres and successfully ran it to clean up orphaned tables:

```sql
BEGIN;

DELETE FROM metabase_fieldvalues AS fv
USING metabase_field, metabase_table
WHERE
  fv.field_id = metabase_field.id AND
  metabase_table.id = metabase_field.table_id AND
  (NOT metabase_field.active OR NOT metabase_table.active);

DELETE FROM metabase_field AS f
USING metabase_table
WHERE
  metabase_table.id = f.table_id AND
  (NOT f.active OR NOT metabase_table.active);

DELETE FROM metabase_table
WHERE
  NOT active;

COMMIT;
```

**Comment by amureki** [comment]
I am sorry for bringing this topic back, @camsaul, but could we reopen it?
The original issue (deleted columns are not cleared in Metabase schema/metadata) is not resolved. The PR #6601 only solved the related issue of not being able to query such tables.

Orphaned columns are still in place and running custom SQL suggested above is doable (thanks to the community), but does not look like a secure and tested solution.

Should I open a new issue instead?

Best,
Rust

**Comment by camsaul** [comment]
That is intentional. We mark the deleted tables and fields as `is_active = false` rather than deleting them entirely intentionally. Is this causing you any problems?

**Comment by amureki** [comment]
Oh, I see. Sorry, I missed the rationale behind PR, that's why I assumed a different thing.


In my use case, I dropped a significant number of fields from one of the tables, and then I had to go through each of the fields in the schema and change visibility from "Everywhere" to "Do not include". While it resolved the issue with the reports (I could use the table again) - the mess in the schema definitely reduced ability to drag and reorder fields and overall reactivity of the page. 

There are handy utils like "rescan table" or "clear cached field values", so I could imagine an extra destructive action to the schema "clear inactive/deleted fields" that will do the clean-up. For a better user experience, we even could have a proxy page that will list all inactive fields, which we could then mark to drop.

Or even simpler - we could add a destructive "delete field" action on the field settings page here:
![CleanShot 2023-03-13 at 16 18 33](https://user-images.githubusercontent.com/627183/224745904-3ed0d81c-b420-4920-a689-b5deaa522561.png)

I know that it might not be easy to implement, so I wonder if there are easier temporary workarounds for the issue.
I am afraid to run untested three years old SQL code on my Metabase instance, but if it'd be a tested and confirmed by Metabase engineers, it could work for me.
