### ISSUE TITLE
Field filter options not available

### ISSUE THREAD

**Issue by AlexGroves** [metabase/metabase#6169]
Field options below the Variable Type (when Field Filter is chosen) never appears.  I've tried with a variety of tables and variable types and nothing seems to work.  This was a problem in a previous version of Metabase so we upgraded to 24.2 and that did not fix the problem either.  If it could possibly make a difference, this version is running in a VPN.

![image](https://user-images.githubusercontent.com/8692571/31566041-d242ca50-b01d-11e7-8226-fed17aaa9b3b.png)

I've set the variables in the table to a number of different types: Category, Entity Name, Entity ID.  I have used a variety of different variable types: varchar, int, boolean.  None work.

- browser and the version: Firefox 56, Chrome 61.0.3163.100
- operating system: OS X 10.12.6
- databases: Redshift
- Metabase version: 24.2
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Comment by mazameli** [comment]
Hmm, Metabase v0.24.2 is still two major versions behind the latest. I'd start with upgrading to 0.26.1.

**Comment by AlexGroves** [comment]
True, however we have a separate installation of Metabase v0.24.2 and the Field drop down works, which makes me suspect it is not a version issue.

**Comment by mazameli** [comment]
I'm not sure if I understand. You're saying you have two separate instances of Metabase, both running v0.24.2, and one of them has this issue but the other doesn't? I still think the place to start is to upgrade to 0.26.2, because we've closed a ton of bugs since 0.24.2 was released.

**Comment by AlexGroves** [comment]
Yes, we've installed Metabase for two separate customers.  It works for one and does not for another.

We'll have a go at upgrading both again to the latest version.  Hopefully that solves the problem.

**Comment by Shanmu281291** [comment]
![a](https://user-images.githubusercontent.com/30283238/33014077-08bccc0a-ce0c-11e7-823d-41964bf65f5c.png)

**Comment by AlexGroves** [comment]
Upgrading to v.s26.2 did not solve the issue.

**Comment by mazameli** [comment]
@Shanmu281291 can you list your setup details so we can see if there's something similar between you and @AlexGroves?

- Metabase version
- Metabase hosting environment
- Metabase internal database
- Browser type and version
- Operating system
- Type of connected database(s)

**Comment by camsaul** [comment]
@Shanmu281291 ?

**Comment by jornh** [comment]
@beankylla your issue seems unrelated, so please open a separate issue.

This issue is specifically about a feature when doing a SQL query as shown in https://github.com/metabase/metabase/issues/6169#issue-265416405, your issue is about using the query builder mode.

It will also be useful if you give this info - and for your case in particular those in bold
-    Metabase version
-    Metabase hosting environment
-    Metabase internal database
-    **Browser type and version**
-    **Operating system**
-    **Type of connected database**

And please try with another browser, and/or in incognito mode + report if there are any error messages in the browser console when you do this with the different browser options.

Thanks! 🙂

**Comment by beankylla** [comment]
ok sorry!

**Comment by flamber** [comment]
Closing, since Field Type was probably not set to one of ones listed in the documentation:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables
There's also (since 0.33) a reference to documentation, when "Filter widget type" is "None"
