### ISSUE TITLE
Modifying (mongo) db connection details blanks password

### ISSUE THREAD

**Issue by vacri** [metabase/metabase#6262]
When modifying an existing Mongo connection and hitting save, the UI shows a connection error, and a database auth error is posted to the metabase log. It does not occur on creating a new database. This might happen in other DB connection pages as well, but I only have mongo available.

A colleague found that if he pasted in the correct password (along with his other edits), it'd save cleanly and there'd be no error. Presumably what is happening is the placeholder password 'dots' are being saved with the other connection details, changing the stored password to a series of dots - but I don't know for sure.

- metabase v0.26.1, running on docker/AWS ECS with RDS psql backend
- ubuntu 14.04/chrome v62 (colleague)
- ubuntu 14.04/firefox v56 (me)
  - who has time to update their work machine's OS? :)

Steps to recreate:
1. create a mongo connection and save it, confirm it connects cleanly
2. edit the mongo connection and re-save it
3. see red auth error text in web console and auth error appear in log
4. edit the connection and paste in the correct password and re-save it
5. save is clean, no error in web console or log

I ran into this problem when I tried adding some connection options to an existing setup.

Cheers

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by olmaga** [comment]
Same here!

**Comment by camsaul** [comment]
For security purposes we don't send the DB password back over the wire in API responses. So what's happening here is the form gets populated with the details it gets in the API response (including the blank password) and when you hit save it saves the entire set of details (including the blank password). Since this doesn't work you see the error message.

We can do one of a few things to fix this:
1.  Merge the old password back into the `details` map when saving if a new password isn't specified. This would however mean you couldn't remove a password from a DB entirely once one is set successfully unless we did some sort of hackery. 
2.  Explicitly, rather than implicitly, require you to reenter your DB password when updating DB connection details. Sort of as an extra security measure

Thoughts @salsakran @mazameli @kdoh ?

**Comment by salsakran** [comment]
I'm cool with either approach, as either is better than the current behaviour.

In an ideal world, I'd have a preference for a variant of (1) where only updated fields are submitted in a PUT rather than having the entire dictionary being submitted.

**Comment by vacri** [comment]
maybe an alternative - if the password field is blank, don't update the password; then include a small checkbox underneath to tick if you want to confirm actually updating a blank password? If field is blank + box checked, then the user explicitly wants a blank password.

**Comment by alitoufighi** [comment]
Guys is there any updates on this?

**Comment by flamber** [comment]
I cannot reproduce on 0.41.1, but the Form component was mostly rewritten last year.
