### ISSUE TITLE
Dates are off by one day in MongoDB with a pivot table when clicking on a item.

### ISSUE THREAD

**Issue by peterwilli** [metabase/metabase#6274]
Hi there,

I currently have made a list with objects that have a start and end date. It looks like this:

![screenshot 2017-10-26 at 11 20 04 am](https://user-images.githubusercontent.com/1212814/32045089-aa6ad712-ba3f-11e7-9003-39e502bd1a21.png)

For some weird reason, if I click on a cell, and click "View these registrations", it shifts my query by one day:

![screenshot 2017-10-26 at 11 21 47 am](https://user-images.githubusercontent.com/1212814/32045174-e46a5d0c-ba3f-11e7-86ac-68fe393bf0ba.png)

As you can see the final query goes at enter date July 6th to 7th, while the real object has July 7 and 8, making no objects to be shown.

If it matters, I try to do this with MongoDB, the objects in question look like this in raw json data:

```js
{ 
    "_id" : "9pNWrXHE8neHzDyHM", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}
{ 
    "_id" : "LnfSm5fW3Z79syTZL", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}
{ 
    "_id" : "fiqe44f3fTqKc3c52", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}
{ 
    "_id" : "cFmG3hjPaaG3EfcEv", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}
{ 
    "_id" : "ps49BZuNXcpjy7BBu", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}
{ 
    "_id" : "BZYRBFeu6a3iqcWZr", 
    "user" : "o3AjrvM9fiGFa8cFB", 
    "enterDate" : ISODate("2015-07-07T00:00:00.000+0000"), 
    "leaveDate" : ISODate("2015-07-08T00:00:00.000+0000")
}

```

**Comment by walterl** [comment]
I think is partially because of the [hard-coded use of the default time-zone](https://github.com/metabase/metabase/blob/master/modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj#L638), but removing that (allowing Metabase core to select the time-zone) does not help.

The other issue is that, in this issue's case, the dates are coerced to date strings (e.g. `2015-07-07`) _before_ Metabase has interpreted its time-zone. Without time-zone info Metabase will interpret the date in the context of the configured time-zone. That time-zone may be different from the one in which the original date was saved ([UTC by default](https://docs.mongodb.com/manual/tutorial/model-time-data/) for MongoDB), and that may cause a shift in the returned date's day.

It seems to me like a potential solution may be to always interpret dates from MongoDB as UTC-based (ignoring time-zones configured in Metabase), but I'm not sure if that will always be correct.

@camsaul: Any ideas?

**Comment by notrom** [comment]
This looks similar to #11251 which seems to apply to all date groupings, not just days.

**Comment by camsaul** [comment]
Not sure how easy this will be to fix.

**Comment by robdaemon** [comment]
@peterwilli Hi there, I believe this bug was resolved in a past release. I've recreated your dataset in MongoDB, and your query as above, and I see the proper results in the pivot table against Metabase version 0.36.3.

![Screenshot_20200817_144503](https://user-images.githubusercontent.com/287213/90447580-745b1b00-e098-11ea-9283-999b6bfa6cfe.png)
![Screenshot_20200817_144527](https://user-images.githubusercontent.com/287213/90447583-758c4800-e098-11ea-9b94-7f430695156d.png)
![Screenshot_20200817_144556](https://user-images.githubusercontent.com/287213/90447584-758c4800-e098-11ea-95cd-35b4992e492c.png)
