### ISSUE TITLE
Pulses: Unsubscribing fails if you don't have a write access to all its questions

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#6303]
If some other user has created a pulse where you are subscribed, but you aren't allowed to edit the pulse (because of missing write permissions to questions contained by that pulse), you aren't able to unsubscribe either.

The pulse looks like this in the pulses list:
![screen shot 2017-10-31 at 17 33 11](https://user-images.githubusercontent.com/6034928/32232918-d76a492a-be61-11e7-9eac-b873fd2e5313.png)

Trying to unsubscribe by clicking the cross next to "You get this email" produces `503 PUT /api/pulse/:id` and the UI displays a "Sorry, you don’t have permission to see that." status.

Seems like there should be a separate API endpoint for unsubscribing,

**Comment by mazameli** [comment]
There is no longer a `/pulses` list page since we redesigned collections a year ago, which makes this more of a `Completeness` issue than a bug. We'll need to determine a new UX for where and how a user could unsubscribe themselves from a pulse if they have View but not Curate/Edit permissions for a collection that a pulse is saved in.

Examples:
- Have some kind of UI in the collection list view on each pulse that can list all the recipients of it and allow editing recipients if you have curate access, or unsubscribing yourself if you have View access.
- Displaying a read-only version of `/pulse/:id` for users without Curate perms, which would allow self-unsubscribing.

Questions:
- Should you be allowed to _subscribe_ to a pulse that you only have View access for?

**Comment by luizarakaki** [comment]
We are shipping a new unsubscribe method on 47
