### ISSUE TITLE
support column alias

### ISSUE THREAD

**Issue by qianqingchen** [metabase/metabase#6332]
hi 

metabase cannot support column alias

when i query an question 

the result is 
![image](https://user-images.githubusercontent.com/18594020/32427793-455bd72e-c2fd-11e7-8d78-073e60da125e.png)

but i want result like this

![image](https://user-images.githubusercontent.com/18594020/32427562-086374d6-c2fc-11e7-8d8f-e29727e15576.png)

i need chinease column names, not english column names 

can support this?

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by Gio666** [comment]
I need same for spanish aliases... 

i'm using this query 

`select name as cliente from c_bpartner;` 

and the visualization shows
 [
![screenshot from 2018-05-04 16-40-04](https://user-images.githubusercontent.com/7320979/39654326-ebbd07f2-4fb9-11e8-8604-3d6c95d15768.png)
](url)

I need the Column as Cliente, not Cli En Te

**Comment by flamber** [comment]
Hi @qianqingchen 
Metabase is now translated to multiple languages - among other Chinese since version 0.30.3
All translations are done via https://poeditor.com/join/project/ynjQmwSsGh
And since version 0.31, it has been possible to change the column name via Visualization settings (:gear:)
![image](https://user-images.githubusercontent.com/1447303/53071125-e6a06e80-34a6-11e9-8621-111889073260.png)

Hi @Gio666 
You can disable "Friendly Table and Field Names" via Admin > Settings > General.

**Comment by mazameli** [comment]
Closing as fixed.
