### ISSUE TITLE
Time not correct (timezone?)

### ISSUE THREAD

**Issue by dgleba** [metabase/metabase#6368]
- *Repeatable steps to reproduce the issue*

### 1.
  - Time displays correctly in v25.2.
### 2.
- download fresh 26.2 jar
- start it on port 3262
 - connect to mysql database for data. [H2 for internal db]
- set timezone to us/eastern in admin panel general settings. (I have set it the same in all three versions.)
- make question to show raw data.
- timestamp is not correct in 26.1 and 26.2.

------

- I have 26.1 running with mysql internal db.
- I tested 26.2 above with H2 internal db.

-----

See pics at bottom

------
- I have looked for similiar issues, but I didn't see one like this. I didn't really understand 
https://github.com/metabase/metabase/issues/6273. Not sure if it is similiar.
-----

- browser and the version: any ( Chrome ,, IE)
- operating system:  any, W7 , W8, W10, any
- databases: MySQL
- Metabase version:  0.26.1, 26.2
- Metabase hosting environment: ubuntu 14 LTS - running the jar file
- Metabase internal database: H2 (default), and MySQL

------

![image](https://user-images.githubusercontent.com/4622715/32685889-b0468f20-c668-11e7-87e5-93bdda2d3e57.png)

------

### Time correct in 25.2
![image](https://user-images.githubusercontent.com/4622715/32685916-4f07935c-c669-11e7-9154-bfd3ea085aa4.png)

------

### Time not correct in 26.1 and 26.2
![image](https://user-images.githubusercontent.com/4622715/32685921-add9795e-c669-11e7-8049-86659f19b255.png)

------
------

**Comment by senior** [comment]
@dgleba I do think we still have timezone issues with MySQL. Can you provide the schema for that table and what timezone the Metabase instance and MySQL database are in?

**Comment by dgleba** [comment]
# Mysql:

Time zone is not specified in my my.cnf  ( ref:  @pmdsdata3/etc/mysql/my.cnf)

Below is a query I found at: https://stackoverflow.com/questions/2934258/how-do-i-get-the-current-time-zone-of-mysql

---

SELECT @@global.time_zone, @@session.time_zone, timediff(now(),convert_tz(now(),@@session.time_zone,'+00:00'))


@@global.time_zone | @@session.time_zone | timediff(now(),convert_tz(now(),@@session.time_zone,'+00:00'))
-- | -- | --
SYSTEM | SYSTEM | -05:00:00
---

# Metabase:

I show the report timezone in the pic above.  I left the H2 db as default. Just the way it started up.

# ??:

I am the US eastern timezone. So you can see that i have some things not specified, and some as US Eastern. Mysql is picking the timezone up from the Ubuntu server.

I have I answered your question properly?

**Comment by senior** [comment]
I need the schema of the database table you're trying to query. Specifically I'm wondering what kind of date/time fields you have in that query. There are some timestamp fields that MySQL does some automatic conversion on which adds another complexity to this.

I'm also wondering which timezone your metabase instance is in. H2 will use the timezone of the JVM that Metabase runs in. If you're not specifying the timezone via a parameter like `-Duser.timezone=...` it will use the system's timezone.

**Comment by dgleba** [comment]
## Mysql table:

DROP TABLE IF EXISTS `Scrap`;
CREATE TABLE `Scrap` (
  `ScrapID` int(11) NOT NULL AUTO_INCREMENT,
  `Date` datetime DEFAULT NULL,
  `PartID` varchar(50) NOT NULL,
  `DeptID` varchar(50) NOT NULL,
  `PlantID` varchar(50) NOT NULL,
  `MachineID` int(11) DEFAULT '0',
  `OpertaionID` varchar(50) NOT NULL,
  `UnitCost` double DEFAULT '0',
  `UnitWeight` double DEFAULT '0',
  `Cancelled` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`ScrapID`),
  KEY `Date` (`Date`),
  KEY `DeptID` (`DeptID`),
  KEY `MachineID` (`MachineID`),
  KEY `OpertaionID` (`OpertaionID`),
  KEY `PartID` (`PartID`),
  KEY `PlantID` (`PlantID`),
  KEY `ScrapID` (`ScrapID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

## H2:
For H2 I think I have answered that above. I left it as default. The timezone should then have come from the Ubuntu system.

Does this answer your question?

**Comment by dgleba** [comment]
I was testing/investigating some more on another machine, different database. I noticed this on the console.

---

11-14 08:55:06 WARN middleware.expand :: The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
11-14 08:55:06 ERROR generic-sql.query-processor :: Failed to set timezone:
 SQLException:
 Message: Unknown or incorrect time zone: 'US/Eastern'
 SQLState: HY000
 Error Code: 1298

---

My report timezone setting:

![image](https://user-images.githubusercontent.com/4622715/32783529-1948f8c4-c91a-11e7-9d25-2cb264848f6a.png)

---

Ubuntu 14.04 timezone

albe@pmdsdata4:~$ sudo cat /etc/timezone
America/Detroit

---

-- Adminer 4.2.2 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `answers`;
CREATE TABLE `answers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `body` text,
  `user_id` int(11) DEFAULT NULL,
  `question_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `issue_description` text,
  `action_taken` text,
  `survey_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_answers_on_question_id` (`question_id`) USING BTREE,
  KEY `index_answers_on_survey_id` (`survey_id`) USING BTREE,
  KEY `index_answers_on_user_id` (`user_id`) USING BTREE,
  CONSTRAINT `fk_rails_3d5ed4418f` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`),
  CONSTRAINT `fk_rails_584be190c2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_rails_f3ff571102` FOREIGN KEY (`survey_id`) REFERENCES `surveys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 2017-11-14 14:10:08

---

**Comment by senior** [comment]
This error is relevant:
```
11-14 08:55:06 ERROR generic-sql.query-processor :: Failed to set timezone:
SQLException:
Message: Unknown or incorrect time zone: 'US/Eastern'
SQLState: HY000
Error Code: 1298
```
That's telling me that your MySQL instance isn't setup to support changing timezones, which is the default for MySQL (unfortunately). Since that isn't setup, the report timezone in Metabase won't work. You could setup the timezone tables in MySQL by following the instructions [here](https://dev.mysql.com/doc/refman/5.5/en/time-zone-support.html), but I don't think you need to. If your database is in central time and your Metabase instance is in central time, we don't need to adjust it with a report timezone. You can unset that on the admin settings page. From reading the above, it looks like you are running Metabase in the eastern timezone. You can force it by adding `-Duser.timezone=America/Detroit` to how you launch metabase if you want to be REALLY sure, but it should inherit the system timezone.

If you remove that report timezone, do you still get incorrect results?

**Comment by dgleba** [comment]
I set my report timezone set to nothing per the pic below.

I still get the same incorrect time shown.

![image](https://user-images.githubusercontent.com/4622715/32794080-dd649b1c-c935-11e7-971a-2bc56af418f3.png)

**Comment by senior** [comment]
I am able to reproduce this error and I think I understand what's going on here.

**The Problem**

The two dates that you have above, the correct one is `2017-10-31 19:27:57` and the incorrect one is `2017-10-31 15:27:57` (after I've switched from 12 hour to 24 hour time). What's happening there is the correct date is in UTC and your Metabase instance (or more specifically, the JVM's timezone) is configured to `US/Eastern`. The MySQL database driver is converting the UTC datetime field to the JVM timezone (`US/Eastern`) which on 10/31 is -4 hours. I'm thinking that is the source of the regression. 0.26.0 fixed a lot of timezone issues and as part of that I added some MySQL connection paramters that would have Metabase handle the timezone conversions correctly when using a report-timezone.

I know you've got some example SQL statements above that show the database is in US/Eastern, but I don't think that's the case. From the Adminer output above you also included `SET time_zone = '+00:00';` which will set the session to UTC. If I have the MySQL instance set to UTC and my JVM timezone set to US/Eastern I get the same results as you have above.

**Quick Fixes**

1. You could populate MySQL's timezone tables. There are instructions [here](https://dev.mysql.com/doc/refman/5.7/en/mysql-tzinfo-to-sql.html).This will not impact other users of the database and is the most flexible. With those in place (and MySQL restarted) Metabase's report timezone functionality will work. You can set the report timezone to `US/Eastern` and it will interpret the datetimes coming out of the MySQL instance as `US/Eastern`. I get the results you expect when I set that.

2. Set your MySQL instance to US/Eastern. I'm not sure how that database was configured for UTC, but the data above indicates that it's in UTC and the MySQL driver is trying to convert it to US/Eastern incorrectly. 

**A regression?**
 
I need to investigate the conversion of UTC datetimes to the JVM's timezone to figure out what's the correct behavior there. With Metabase 0.25 and before, the date coming back from the database was assumed to already be in the JVM's timezone. In your case I think that was technically incorrect, but yielded the results you were looking for. As part of the 0.26 release I added some new parameters to the MySQL database connection so that it would convert datetimes correctly when users have configured a report timezone. It looks like that has also caused the MySQL JDBC driver to automatically convert those datetimes even when not using the report timezone. I'm going to take a closer look at the different options for the MySQL driver and try to figure out what the correct, or maybe least suprising behavior is there.

**Comment by dgleba** [comment]
I haven't digested everything you said above @senior, but my first comment is that the Adminer `SET time_zone = '+00:00';` is just for exporting the schema in that one command. I can tell you that there is no setting making my MySQL instance UTC. I could have  done `show create table [db_name.]table_name;` and it would not have said time_zone... and it would have shown the same schema output.

So here is the `show create table answers;`

```
 answers | CREATE TABLE `answers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `body` text,
  `user_id` int(11) DEFAULT NULL,
  `question_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `issue_description` text,
  `action_taken` text,
  `survey_id` int(11) DEFAULT NULL,
  `issue_followup_notes_by_lpa_admin` text,
  `issue_closed_by_lpa_admin` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_answers_on_question_id` (`question_id`) USING BTREE,
  KEY `index_answers_on_survey_id` (`survey_id`) USING BTREE,
  KEY `index_answers_on_user_id` (`user_id`) USING BTREE,
  CONSTRAINT `fk_rails_3d5ed4418f` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`),
  CONSTRAINT `fk_rails_584be190c2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_rails_f3ff571102` FOREIGN KEY (`survey_id`) REFERENCES `surveys` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=589 DEFAULT CHARSET=utf8 
```

I don't think you should let that Adminer time_zone thing influence you.

I believe that my MySQL instance has no timezone setting in my my.cnf and that it picks up timezone from the ubuntu time zone. 

```
mysql> SELECT @@session.time_zone;
+---------------------+
| @@session.time_zone |
+---------------------+
| SYSTEM              |
+---------------------+
1 row in set (0.00 sec)
mysql>
```

Also, I will study your response - that is just above this - more deeply.

thanks.

**Comment by tlrobinson** [comment]
Related to #6636?

**Comment by camsaul** [comment]
Same issue as #6273
