### ISSUE TITLE
Mysql Timezone Problem

### ISSUE THREAD

**Issue by pdiniz13** [metabase/metabase#6420]
This issue is the exact opposite of the issue https://github.com/metabase/metabase/issues/3584 which was closed. I tried requesting that it be reopened but its been a while and it remains closed.

This is the original issue: 
We are currently using MySQL as our database and our timestamps are saved as datetime fields in the database. When displaying the results with those fields included metabase has no issues converting those fields into PST time which we set in settings. The problem occurs when we try to filter by a datetime field. There doesn't seem to be any timezone conversion and the selected filter is added without being converted from pst to utc. As an example if I tried to select items by using today (PST time) as the filter(same thing happens for both relative and exact date searched) I would instead get orders that were booked between yesterday at 5pm until today at 5pm. This issue doesn't happen with hardcoded sql, even with params, because I can force a tz conversion on those values. But for things such as the dashboard and questions generated via the form there seems to be no solution. Again i'm not sure if this is a bug or if the driver was intended to work this way, but if there's some sort of workaround that you guys can point me too it would be greatly appreciated. Even if it involves just pointing to the area of the code where i could add the filter by default to those values in a forked repo it would help a lot.

Our workaround was switching all of out datetime fields to timestamps. When we tried to update to version 0.26 we started the same issue issue with timezone conversions we were having but this time with timestamp types. The datetime type now seems to be handling timestamps fine, but the timestamp field is not being converted.
### Bugs
- Your browser and the version: Chrome(latest), Firefox(latest). This issue is not browser related.
- Your operating system: Machine running metabase is running on ubuntu.
- Your databases: MySQL
- Metabase version: 0.25.2 upgrading to any of the 0.26 versions
- Metabase hosting environment: Docker DC/OS
- Metabase internal database: Postgres
- _Repeatable steps to reproduce the issue_
  Add a mysql table with a timestamp field in UTC, and try to filter the results based on that timestamp filter.

**Comment by senior** [comment]
What timezone is your MySQL instance running in? If you have report-timezone configured, what is it set to?

**Comment by pdiniz13** [comment]
MySQL is running on UTC, the report-timezone on metabase and the environment var JAVA_TIMEZONE are both set to to Pacific/US

**Comment by senior** [comment]
@pdiniz13 I tried to reproduce this locally and couldn't. Could you provide an example schema, data and query to reproduce the issue? Timestamps can be tricky with MySQL as they are always stored in UTC but there is some automatic conversion that MySQL does specifically with timestamps that it doesn't do with datetimes.

**Comment by pdiniz13** [comment]
```
create table test_table
(
    id int auto_increment
        primary key,
    dt datetime null,
    ts timestamp default CURRENT_TIMESTAMP not null
);

INSERT INTO test_table (dt, ts) VALUES ('2017-11-17 16:33:00', '2017-11-17 16:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-16 16:33:00', '2017-11-16 16:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-15 16:33:00', '2017-11-15 16:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-17 15:33:00', '2017-11-17 15:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-17 14:33:00', '2017-11-17 14:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-17 13:33:00', '2017-11-17 13:33:00');
INSERT INTO test_table (dt, ts) VALUES ('2017-11-17 12:33:00', '2017-11-17 12:33:00');
```


SQL Query: `SELECT * FROM test_table;`
![screen shot 2017-11-17 at 5 01 02 pm](https://user-images.githubusercontent.com/9104109/32975123-08c48eea-cbb9-11e7-8d5c-15a48ac3bba4.png)

**Comment by senior** [comment]
I'm not exactly sure what you were expecting here, but I think you might be getting confused by MySQL's timezone behavior. Was your expectation that the timestamp value should match the datetime value? Assuming that's the case, I can give an example using just the MySQL console that follows closely to what Metabase is doing. I setup the table you had above and inserted the same rows you have above. To follow your setup, the MySQL instance is in the UTC timezone. I then execute `select * from test_table` and I see the correct results:
```
 > select * from test_table;
+----+---------------------+---------------------+
| id | dt                  | ts                  |
+----+---------------------+---------------------+
|  1 | 2017-11-17 16:33:00 | 2017-11-17 16:33:00 |
|  2 | 2017-11-16 16:33:00 | 2017-11-16 16:33:00 |
|  3 | 2017-11-15 16:33:00 | 2017-11-15 16:33:00 |
|  4 | 2017-11-17 15:33:00 | 2017-11-17 15:33:00 |
|  5 | 2017-11-17 14:33:00 | 2017-11-17 14:33:00 |
|  6 | 2017-11-17 13:33:00 | 2017-11-17 13:33:00 |
|  7 | 2017-11-17 12:33:00 | 2017-11-17 12:33:00 |
+----+---------------------+---------------------+
7 rows in set (0.00 sec)
```
There are several ways that a timezone can be set in MySQL. One way is that it inherits it from the system timezone, another is the `TZ` environment variable. Those are global settings that affect the whole instance. When you set a report timezone in Metabase, we set a `session.time_zone`, that essentially tells MySQL it's in that timezone for the duration of the database connection. You can mimic what Metabase does with the following command at the MySQL console:
```
 > SET @@session.time_zone = 'America/Los_Angeles';
Query OK, 0 rows affected (0.00 sec)
```
Then if you issue that same query again:
```
> select * from test_table;
+----+---------------------+---------------------+
| id | dt                  | ts                  |
+----+---------------------+---------------------+
|  1 | 2017-11-17 16:33:00 | 2017-11-17 08:33:00 |
|  2 | 2017-11-16 16:33:00 | 2017-11-16 08:33:00 |
|  3 | 2017-11-15 16:33:00 | 2017-11-15 08:33:00 |
|  4 | 2017-11-17 15:33:00 | 2017-11-17 07:33:00 |
|  5 | 2017-11-17 14:33:00 | 2017-11-17 06:33:00 |
|  6 | 2017-11-17 13:33:00 | 2017-11-17 05:33:00 |
|  7 | 2017-11-17 12:33:00 | 2017-11-17 04:33:00 |
+----+---------------------+---------------------+
7 rows in set (0.00 sec)
```
I see the same results that you pasted in from Metabase. The datetime values are unchanged and the timestamp values are 8 hours earlier than the corresponding datetime value. The MySQL docs talk about this behavior [here](https://dev.mysql.com/doc/refman/5.5/en/datetime.html). Those docs describe our situation

`If you store a TIMESTAMP value, and then change the time zone and retrieve the value, the retrieved value is different from the value you stored. This occurs because the same time zone was not used for conversion in both directions.`

By inserting it using UTC, then changing the timezone to Pacific for the query, a different time is returned. Datetimes don't store their original timezone and are assumed to be in the current timezone.
I'd say in this example, the datetimes are wrong and the timestamps are right, but their behavior is surprising.

I think you have a few options but it really depends on what is the real value for those timestamps. Did the events really happen at i.e. 16:33 UTC? or was it 16:33 Pacific? If it was 16:33 pacific time then your data is wrong. You could update the values in that column to reflect the correct time in Pacific. If the UTC time is the correct time, then maybe you're wanting to view the data through UTC time. You could remove the report timezone or set it to UTC.

I hope that information helps!

**Comment by pdiniz13** [comment]
Thank you for the update, I forgot that metabase was not converting datetimes and was just setting the session timezone. However we are still experiencing the issue with time filtering.

As you can see the date pickers using a range work on both version 25 and 27. However date pickers using either a single date or a relative date defaulting to either today or yesterday are not returning any results.

Version 27
![screen shot 2017-11-29 at 3 21 57 pm](https://user-images.githubusercontent.com/9104109/33404593-ba5bf904-d519-11e7-9321-f97aad3cb41a.png)

Version 25
![screen shot 2017-11-29 at 3 21 49 pm](https://user-images.githubusercontent.com/9104109/33404594-ba745f9e-d519-11e7-8a3e-107499b8b6bf.png)

Version 27
![screen shot 2017-11-29 at 3 21 14 pm](https://user-images.githubusercontent.com/9104109/33404595-ba8cc476-d519-11e7-88b7-db06e82cd5f3.png)

Version 25
![screen shot 2017-11-29 at 3 21 06 pm](https://user-images.githubusercontent.com/9104109/33404596-baa4d822-d519-11e7-9c40-88003d92d87e.png)

Version 27
![screen shot 2017-11-29 at 3 19 51 pm](https://user-images.githubusercontent.com/9104109/33404597-babd181a-d519-11e7-8aa0-ec3c642ac0ab.png)

Version 25
![screen shot 2017-11-29 at 3 19 34 pm](https://user-images.githubusercontent.com/9104109/33404598-bad83d7a-d519-11e7-94b8-714fb9308c63.png)

They are both running against the same database.

**Comment by senior** [comment]
@pdiniz13 Sorry I missed your last comment, I'm just now seeing it. Do you have your logging level for MySQL such that you can see what query is being executed? Specifically the MySQL log will show the specific date/time parameter which could tell us if the date/time is having it's timezone incorrectly adjusted.

**Comment by senior** [comment]
@pdiniz13 I think what you were seeing with [this comment](https://github.com/metabase/metabase/issues/6420#issuecomment-348031957) is due to a bug I found in the MySQL driver. I wrote up some info on it [here](https://github.com/metabase/metabase/issues/6554#issuecomment-355683909).

A fix for this has been merged as https://github.com/metabase/metabase/pull/6643. Can you verify that the fix works for you?

**Comment by pdiniz13** [comment]
I tried running it based on this new build but it still didn't work. I did have a hard time creating a docker image off this build to test it so I might have done something wrong there. If you have a docker image with this fix that I can test I can give that a try. 

Right now this is whats getting saved to the db.

```
{
    "database": 2,
    "type": "native",
    "native": {
        "query": "SELECT sku_categories.name, orders.id, orders.created_at\nFROM orders\nJOIN services\nON orders.id = services.order_id\nJOIN skus\nON services.sku_id = skus.id\nJOIN sku_categories\nON skus.sku_category_id = sku_categories.id\nWHERE {{created_at}} AND orders.test_mode = FALSE;",
        "collection": "activity",
        "template_tags": {
            "created_at": {
                "id": "fc1dc0c3-1dc4-48f4-7bf0-559550dbc73e",
                "name": "created_at",
                "display_name": "Created at",
                "type": "dimension",
                "dimension": [
                    "field-id",
                    34870
                ],
                "widget_type": "date/relative",
                "default": "today"
            }
        }
    }
}
```

**Comment by pdiniz13** [comment]
I turned on general logging for the db, and believe I have found the issue. This is the query being generated:

```
-- Metabase:: userID: 1 queryType: native queryHash: 39f4e5b11d082f34b7381fcb3b19fb438bd83e651dca82f6e8aede1c64c78dff
SELECT sku_categories.name, orders.id, orders.created_at, services.sku_id
FROM orders
JOIN services
    ON orders.id = services.order_id
JOIN skus
    ON services.sku_id = skus.id
JOIN sku_categories
    ON skus.sku_category_id = sku_categories.id
WHERE date(`orders`.`created_at`) = '2018-02-08 08:00:00' AND orders.test_mode = FALSE
```
As you can see the date field is getting added with the time included.

The same thing is happening with the single and range date filters. With the range one still showing results, albeit incomplete, because it includes the range in between.

On version 0.25.2 this is what that query looks like

```
-- Metabase:: userID: 1 queryType: native queryHash: 4f125ab4c750c37d5f6cbb23c0584cb2783fdaa504913ea123e07ea5dec37d47
SELECT sku_categories.name, orders.id, orders.created_at
FROM orders
JOIN services
ON orders.id = services.order_id
JOIN skus
ON services.sku_id = skus.id
JOIN sku_categories
ON skus.sku_category_id = sku_categories.id
WHERE date(`orders`.`created_at`) = '2018-02-08 00:00:00' AND orders.test_mode = FALSE
```
Which because of the way MYSQL just handles data conversions ends up working, but the "DATE" function is supposed to return a string with the date part of the method timestamp. So the easies solution would either be to just drop the time values when the param is inserted into the query, of if thats an for the db driver the just also wrap the inserted values in a "DATE" function of its own.
```WHERE DATE(`orders`.`created_at`) = DATE('2018-02-08 00:00:00') AND orders.test_mode = FALSE```

**Comment by maliayas** [comment]
I agree with @pdiniz13 's solution. Datepicker should not output time value there, so only outputting date part will fix the issue.

**Comment by pdiniz13** [comment]
@senior has there been any updates on this issue?

**Comment by senior** [comment]
@pdiniz13 We've moved around quite a bit in the context of this issue, so I want to make sure I understanding what you are asking for an update on. I'm assumuing it's the suggestion at the end of https://github.com/metabase/metabase/issues/6420#issuecomment-364233163?

Am I understanding your example above correctly that you have written a native query, with a DATE call in the SQL. When you select a date to populate that parameter, it's injecting the date and the time which isn't what you want. Assuming I'm correct there, why not just wrap your parameter in a date call?  We treat native SQL as opaque and would have no way of knowing that you're using a `DATE` function and that function returns a particular type.

If you're hitting this issue using the query builder, we do have a known issue around treating dates like timestamp that is written up in https://github.com/metabase/metabase/issues/5859

Sorry if I dropped this on this one! I wasn't clear about what the bug was.

**Comment by pdiniz13** [comment]
@senior yes I am referring to  [#6420 (comment)](https://github.com/metabase/metabase/issues/6420#issuecomment-364233163). Yes this does seem to be the same issue as https://github.com/metabase/metabase/issues/5859.

As to
> Am I understanding your example above correctly that you have written a native query, with a DATE call in the SQL. When you select a date to populate that parameter, it's injecting the date and the time which isn't what you want. Assuming I'm correct there, why not just wrap your parameter in a date call? We treat native SQL as opaque and would have no way of knowing that you're using a DATE function and that function returns a particular type.

This would be native query but it would be using the variables feature so that we could either select a date or range. The query would have been created like this:

`SELECT sku_categories.name, orders.id, orders.created_at
FROM orders
JOIN services
    ON orders.id = services.order_id
JOIN skus
    ON services.sku_id = skus.id
JOIN sku_categories
    ON skus.sku_category_id = sku_categories.id
WHERE {{created_at}} AND orders.test_mode = FALSE;`

So despite this being a native query it's still based on the variable created_at and I can't wrap that variable on a DATE function.

**Comment by senior** [comment]
Hrm, not sure how what you're doing is different, but this seems to work fine for me. When I setup a field filter like you are using and a "Single Date" widget type, it does the right thing.
![native-date-param](https://user-images.githubusercontent.com/215910/38505118-0a9cdfae-3bdc-11e8-85d3-ca4585eff835.png).

In the above `period` is a date and I used a date picker to select that date, it's bringing back the two correct rows there.

**Comment by pdiniz13** [comment]
@senior the reason the query is probably working for you is that the period times in you range are `2013-04-26 00:00` and the date format is being generated with 00:00 (or whatever that would be given the timezone) as the time. So `2013-04-26 00:00 = 2013-04-26 00:00`. But if the time for that date was something different like `2013-04-26 09:00` it would not pass the where check. `2013-04-26 09:00 = 2013-04-26 00:00`

**Comment by senior** [comment]
When you disable the report timezone for your Metabase instance does it behave like you expect?

**Comment by pdiniz13** [comment]
If I disable report timezone then it does show the results. I can go ahead and create another issue. How would you like me to format the request?

**Comment by senior** [comment]
I'd suggest including the native query with the parameter info along with the possibility of the dates being wrong when using a report timezone. It's a bug that we'll want to get fixed. I can chime in on it with more details and get it tagged properly once it's there.

**Comment by pdiniz13** [comment]
I'm closing this issue and creating issue #7393
