### ISSUE TITLE
Elastic Beanstalk build fails due to "failed to create: [AWSEBRDSDBSecurityGroup]"

### ISSUE THREAD

**Issue by gitsh84** [metabase/metabase#6471]
When trying to build a new app/env of Metabase using AWS elastic beanstalk (latest version), I keep getting this error:

Current state: 'CREATE_FAILED' Reason: The following resource(s) failed to create: [AWSEBRDSDBSecurityGroup]
Creating RDS database security group failed Reason: You have already reached your quota of 25 DB security groups

From the error is seems that the problem is with the AWS account limit but even after I've increased the limit for RDS security groups to 50 (AWS support confirmed the increase), I still get this error.

Is there any chance this error is "hiding" another/different error ?

Thanks.

**Comment by salsakran** [comment]
While there is a chance it's underlying cause is something else, it seems unlikely that this is a Metabase-specific bug.

You might have more luck asking on our discussion forum (discourse.metabase.com) or the AWS forums. 

Closing this, but if you find it's due to our beanstalk template, I can re-open it.

**Comment by zzaacchh** [comment]
FWIW, I had the exact same problem and [found this suggestion on StackOverflow](https://serverfault.com/questions/920834/cant-add-rds-database-to-elastic-beanstalk-environment) quickly got me past it.
