### ISSUE TITLE
Provide status/progress of data warehouse sync/introspection process

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#649]
this is particularly relevant on initial setup when a new user can be dropped into the app with nothing to see.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by MrMauricioLeite** [comment]
As said in my closed issue #2194 we can to make it clear for the user doing questions too. 

My sugestion is that on the question screen, where you get to pick a database we place a blue badge saying: "in sync" that on hover have a tooltip with "Sync progress: xx% (We don't recommend asking questions on databases that are syncing.)"

**Comment by MrMauricioLeite** [comment]
Can we add this to the milestone 0.16.0?
If it's a issue since august and apparently have a 'quick-win' solution can't we add to the next milestone?

**Comment by agilliland** [comment]
Hey @MrMauricioLeite , that sounds like a possibility.  What page are you talking about where you "pick a database", can you provide a more detailed example of what you are envisioning?  Maybe even something with visual mockups to look at?

Regarding the assignment of issues/features to milestones, that's something that the Metabase core development team handles.  Only issues that have been discussed, designed, and approved are going to be considered for scheduling into milestones.  And of course if you can code we are always willing to accept PRs :smiley:

**Comment by MrMauricioLeite** [comment]
Sure, @agilliland I'll sure contribute as soon as I figure my way out on metabase source. I'm not a closure dev yet but I'll try my best.

Abou where I'm talking about with 'where the user pick the database' is the Question screen, when we are asking a new question.

Sure the sync progress is a useful feature for the admin on backend. But users on frontend may get confused also. So if added to the backend we solve the admin knowing that the database is syncing. Adding a little badge to the database name (on 'new question's screen) will let the user know that he should not be using this database right now.

**Comment by mazameli** [comment]
At a minimum, we could add a spinner/loader on the database detail in the admin panel:
![syncing in database detail](https://cloud.githubusercontent.com/assets/2223916/15051323/d569d5f8-12ac-11e6-99e9-5b54f94e0897.png)

A step further would be to give an indication on the data model page as well:
![syncing in data model](https://cloud.githubusercontent.com/assets/2223916/15051899/c85bf2ee-12af-11e6-87cc-a4f4941be9a2.png)

There's probably also this intermediate state, where some columns, etc., have started appearing, but possibly not all because we're still syncing:
![syncing with some info present](https://cloud.githubusercontent.com/assets/2223916/15051909/ddb8583a-12af-11e6-8d04-3c7329f0c826.png)

Last thing would be to potentially add a treatment in the database selector in the query builder, like this (maybe the DB link is disabled until some tables are present, but the `Syncing` indicator remains until the sync is done):
![syncing in db menu](https://cloud.githubusercontent.com/assets/2223916/15052073/8e82dd70-12b0-11e6-9c07-15fe02e24eba.png)

**Comment by salsakran** [comment]
@camsaul / @agilliland: Do we currently hold onto errors that get generated by the sync process? 

For situations where there are major errors (eg: this database went away), it would be useful to have that be something an admin can get hold of to debug.

**Comment by agilliland** [comment]
no, nothing is captured right now.

**Comment by agilliland** [comment]
One thing to keep in mind is that realistically this should only be that relevant the very first time a database is added because you are trying to know when the db is actually ready for use.  After that the sync progress is of significantly less value.

**Comment by salsakran** [comment]
With respect to to the in-query builder notification, that's true. I'm still uncertain that is necessary with the new, faster sync.

With regards to the db detail page, I still think we should show progress on the introspection part of the process and if possible surface errors. Given the wide number of places server logs can live (Console on the Mac app, Elastic Beanstalk console, std out for the jar, Heroku, etc), errors that only surface in the error logs expand support load considerably. I.e. I feel like half the discourse issues have something like "go look in the logs" as a step that blocks further debugging.

**Comment by mazameli** [comment]
This proposal still seems relevant to me. There are often times our users do something to their underlying schema to try to make something change or become visible in Metabase, but then they think it didn't work because they didn't realize MB kicked off a new sync which is still in progress. See [this discourse thread](http://discourse.metabase.com/t/no-dropdown-menu-option-for-filter/1186/2) for a recent example.

**Comment by MrMauricioLeite** [comment]
The layouts @mazameli proposed are awesome. If the same concepts are implemented we would have a great solution, at least for a start.

In addition, from an admin perspective I would like to know if that sync process resulted in any errors but that's completely unrelated to know if a db is syncing or not.

**Comment by salsakran** [comment]
this is effectively solved in the new troubleshooting tab in the admin.

**Comment by gajop-ptx** [comment]
Sorry for potentially necroing an old issue, but I don't think this is solved.

I'm trying to give metabase a go on our BigQuery data, and well, the sync is ongoing but there's no way to figure out the actual progress and remaining time estimate:

- I've looked into Docker logs and all it gives is an idea of active workers, threads and DB calls
- The Admin->Troubleshooting tab gives us the same log, and Tasks/Jobs tab doesn't provide any extra information
- The Admin->Database tab just gives us a spinner
- The actual tables (under Browse Data) all have a spinner, so you can't manually introspect their sync status.

With all this, I can expect it to finish in a couple of minutes but also might take days or just never finish (is it even progressing?) -> it leaves quite a bit of uncertainty to the user/admin.

PS: I had the same sync spinner in the GUI when I had permission issues (errors) and the thing wasn't progressing, so just because I'm not seeing any errors in the logs doesn't guarantee that things are actually moving along imo.
