### ISSUE TITLE
Bug: Questions tab does not load, times out with the HTML of a "gateway timeout" response rendered on the page

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#6573]
**Browser:** Chrome 60.0.3112.101
**OS:** Kubuntu 16 LTS
**Databases used:** MySQL (Cloud CQL) for both data and metabase storage
**Metabase version:** 0.27.1
**Metabase hosting environment:** Running in Google Cloud under Kubernetes (docker)

**Steps to reproduce:**
- Try to load the "questions" page

**Expected result:**
- Categories and uncategorized questions are loaded

**Observed behaviour:**
- Categories are loaded, but individual questions are not. The loading spinner runs indefinitely. 

The above behaviour happens only occasionally, and more for some users(!).

The logs are full of entries such as:

```
12-13 09:11:39 INFO middleware.fetch-source-query :: 
FETCHED SOURCE QUERY FROM CARD 467 :
```

Additionally I see these warnings in the logs occasionally, not sure if they're related:

```
12-13 09:17:06 WARN middleware.expand :: It doesn't make sense to use `field-literal` forms inside `field-id` forms.
Instead of [field-id [field-literal ...]], just do [field-literal ...].
```

The system does seem to recover on its own.

Is there some periodic / background process that could cause this?

**Comment by salsakran** [comment]
How many questions + collections do you have?

**Comment by kristian-elder** [comment]
9 collections and 500+ questions.

**Comment by fabioperrella** [comment]
I have the same problem, but the loading spinner does not appear for me. 

Looking in the browser console, there is an ongoing request to `/api/database?include_tables=true&include_cards=true`

After 1min, it timed out and the page finished to render.

**Comment by camsaul** [comment]
"gateway timeout" is coming from your reverse proxy, not from Metabase. What's happening is the reverse proxy is killing the connection before Metabase gets a chance to respond.

In Metabase 0.32.x we write bytes to the connection every second to keep it alive while the query is running so reverse proxies don't kill the connection because it reached some timeout. However if you're using multiple reverse proxies the first might be buffering the response and the keepalive bytes aren't being passed thru to the second reverse proxy, which is killing it after seeing no response after 60 seconds.

We ran into this exact problem running on Elastic Beanstalk. The setup was basically

```
Browser <---> Elastic Load Balancer <---> nginx <---> Metabase
```

nginx was the first reverse proxy, and it buffered our keepalive bytes; the second reverse proxy was an Elastic Load Balancer, which killed connections after 1 minute). I fixed this by passing an HTTP header to nginx to disable buffering along with the API responses that used the keep-alive bytes.

I suspect you're having the same problem. To fix it, you can:

1.  Increase the timeout on second reverse proxy (e.g. Elastic Load Balancer in example above)
2.  Disable buffering on the first reverse proxy (e.g. `nginx` in example above)
3.  Figure out what, if any, headers can be passed to first reverse proxy to disable buffering for some requests, then let me know and we can add them in

**Comment by flamber** [comment]
Closing, since a lot has changed since the original post, and `/api/database?include_tables=true&include_cards=true` was changed in 0.34.2, and 0.35.0 doesn't send keep-alive every second.
Related #12423 and #11806 and #10163
