### ISSUE TITLE
Database connection exceptions should be caught and translated to a human readable message

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6628]
For commonly expected errors (like a file name not being found as in #6627), we shouldn't be leaking cryptic errors like `java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V` into user-land.

**Comment by camsaul** [comment]
In general we already do translate common error messages; see https://github.com/metabase/metabase/blob/master/src/metabase/driver/postgres.clj#L162 for example. The problem here is `java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V` isn't supposed to be a commonly expected error.

**Comment by camsaul** [comment]
Duplicate of #881

**Comment by camsaul** [comment]
Duplicate of #881
