### ISSUE TITLE
Bigquery: limit query size 

### ISSUE THREAD

**Issue by id0Sch** [metabase/metabase#6705]
Hi,
first off we just started integrating metabase into our DB and it seems great! 
however, we are missing a key feature that is a show-stopper for us.
we are lacking the feature to limit the Bigquery query size as mentioned [here](https://cloud.google.com/bigquery/docs/best-practices-costs)
since we have big tables, if a wrong query is executed  - it could cost us a lot of money.
this goes hand in hand with the feature to query by the pseudo column _PARTITIONTIME as well, we saw that queries that can take 5mb take up to 350mb of processing.

let me know if clearance is needed.
thanks!

**Comment by PerThoresson** [comment]
Any updates on this?

Also, the default query (similar to `SELECT * LIMIT 2000`) being fired when navigating Our Data -> dataset -> table, is kind of a blocker as well in order to use BigQuery with Metabase. 

With Big Query, the LIMIT clause has no effect and will still scan the whole table. Since BigQuery is pay-per-processed-byte this leads to an unnecessary cost every time you go through the table to start a question instead of clicking the "Ask a question" button.

**Comment by Saurabh-Shrivastava-Narvar** [comment]
On similar note on cost optimization - it would be great if we could get the query cost before running the actual query like bigquery console and looker provides. This will help users to see the query cost before executing any rouge query.

**Comment by flamber** [comment]
Closing in favor of #5904
