### ISSUE TITLE
URL must point to a valid (Geo)JSON file, but already does

### ISSUE THREAD

**Issue by unaipme** [metabase/metabase#6714]
Hi!

I'm trying to add a custom GeoJSON map to Metabase, but all I get is the following error:

`Value does not match schema: {:72d349a2-0a71-a76f-7cd6-8d5bb5894318 {:url (throws? ("URL must point to a valid JSON file." a-java.lang.String))}}`

I've tried this with Chrome 63, Firefox 57 and MS Edge 41, and none worked for me. I'm running Metabase inside a Docker container. I'm using the latest image, which as for now is v0.27.2. I haven't done anything special, really just tried to add the map on this [gist](https://gist.githubusercontent.com/unaipme/b096662df6881d449d32a466c113ad6b/raw/bc35ca19bc2a261df07c45bfe879c354890e4f62/spain.json). I've verified it works on geojson.io.

Thanks beforehand for any help!

**Comment by salsakran** [comment]
what is the url in question?

**Comment by unaipme** [comment]
The URL I link to on the issue: 

https://gist.githubusercontent.com/unaipme/b096662df6881d449d32a466c113ad6b/raw/bc35ca19bc2a261df07c45bfe879c354890e4f62/spain.json

**Comment by camsaul** [comment]
@salsakran @unaipme The issue here is that we set a 5-second timeout to fetch and parse the file in question. This file is about 18MB and can easily exceed that limit (it took me 9 seconds alone to fetch it with `wget` just now)

So I can do one of two things here:

1.  Raise the timeout limit to something higher so we can handle larger files (to what?)
2.  Fix the error message so it's more meaningful

Opinions @salsakran @kdoh @mazameli ?

**Comment by salsakran** [comment]
5s seems way too short a timeout. 60s is a fairly common load balancer timeout, and is as good a threshold as any.

**Comment by camsaul** [comment]
👍

**Comment by tlrobinson** [comment]
Perhaps we should also warn the admin if they add an 18MB GeoJSON.

**Comment by camsaul** [comment]
FWIW once I raised the GeoJSON file in question seems to load just fine for me
