### ISSUE TITLE
Feature Request/Assistance Needed: Static data entry and representation

### ISSUE THREAD

**Issue by funkeyfreak** [metabase/metabase#6725]
I am a software engineer who has been tasked with researching the availability of a future within your product, namely the addition of a new card/visualization which would function as follows:

A user can enter in static data. This data would be a simple key-pair, such as a "sales" with a percentage value, or a "velocity" with a value representing that quarter's sales.

The user can then enter-in many such key-pair values, and then create a card that would represent this key-pair value and it's relation to it's last entered value over some span of time:

diff( "sales", latest, (aggregate( avg ("sales", date_start, date_end)))

An example would be the latest "sales" key-pair with some percentage value with it's relation to the selected time-range. Let's say this relation is the difference between the average "sales" over the past month. This would then be represented by a visual, let's say an up or down arrow, with the difference between the latest "sales" and the average-over-time. The latest "sales" figure would als be visualized.

My question is, is this functionality present/already being worked on, and if not, is there anyone I could speak to as a resource of knowledge concerning Metabase and what modifications to the MBQL I would need to take on?

Thank you all!

**Comment by jornh** [comment]
It think to make this more generic (and to better understand what’s needed/missing) this could be broken down to some smaller features. 

Is it fair to break it into these?

1. **Data entry**/storage

1. **Logic** to determine two values that each represent a (time) range

1. **Trend visualization** of the two results and the relation between them

If you agree(?) to this breakdown of the feature then we can start looking for related GitHub issues or ideas/solutions from *anywhere else*... the more you can steal and cheat (aka reuse) the better! 😄 

For **Data entry** I would challenge if it’s needed to be part of the same card - or even part of Metabase. Depending on your usage scenario wouldn’t you already have that data keyed into/sent to a data storage somewhere else? See #6094 and even the abandoned PR #1704 for related discussion. That’s not saying that it couldn’t be built though ...

The **Logic** you specify seems like a special case with comparing only the latest value as contrasted to other people requesting e.g Year-over-Year comparison. YoY, MoM, WoW calculation - and visualization - is discussed in http://discourse.metabase.com/t/display-difference-over-the-previous-time-period/2209 and already implemented as part of [x-ray](https://www.metabase.com/docs/latest/users-guide/14-x-rays.html#time-series-x-rays). If *exactly*  comparing not-same-sized time intervals (e.g. your `latest` vs  `date_start, date_end` intervals) is _**the** killer feature for you_ then I guess an option to make this configurable should be simple to add on top of x-rays. It could potentially be reusing [segments](https://www.metabase.com/docs/v0.27.2/administration-guide/07-segments-and-metrics.html). Oh and I just saw there’s a proposal in #4257 to pull out the logic as a query builder operator.

**Trend visualization** comparing intervals relates to #4479 (which links to very nice looking cards) and x-ray I linked to just above.

I guess it’s something that can be visualized in a gazillion other ways like:

* conditional icon/emoticon visual indicators like you suggest (📈 👍 ➕ ⬆️  / 📉 👎 ➖ ⬇️ ) etc

* conditional color, as discussed in http://discourse.metabase.com/t/conditional-coloring-of-data-variable-progress-bar-goal/1404 and different issues here it links to.

That’s why I think it would be nice to separate the calculation logic (backend `.clj` or frontend `.js`) and the visualization as a card (purely frontend). Because then you can first define the *question* logic, then select between specific visualization *card(s?)* types with more or less detail (maybe even dynamic based on available pixels) and lastly as an option 🍒 pin it to a *dashboard*.

You said:
> My question is, is this functionality present/already being worked on, and if not, is there anyone I could speak to as a resource of knowledge concerning Metabase and what modifications to the MBQL I would need to take on?

And I realize this ended up being a bit lengthy ;) But I hope there’s something useful for you/others to chew on - and we can take it from there... as it might shine through I’m interested in seeing some of this happen as well!

**Comment by salsakran** [comment]
Data entry isn't really on our roadmap at this point in time, and would absolutely require a serious design conversation. Absolutely not the sort of thing we'd accept a drive-by PR for unless it was extremely well thought out. 

We're actively interested in picking out trends and generally getting better at Granularity-over-Granularity (eg Week over week) trends. We'll be unbundling the various things we're doing in X-Rays and introducing them via cards and the query builder over time. 

Visualization is a moving target, and we'll be actively improving that.

None of these three changes should touch MBQL in any way.

**Comment by funkeyfreak** [comment]
@jornh, thanks for the breakdown. Also, sorry for my lack of response - I had two weeks to mock up an example for my team. I ended up needing every last one to make a demo feature. Not to say it is at all production ready, but hey - I always say it's better to do than to just say. Take a look the dev branch on my personal fork of Metabase on the dev branch which can be located here. Again - it's hacky as hell, but a prototype is a prototype. And yes totally didn't steal any of these ideas 😅

**Data Entry**. Oof, That's a big one. I've added a few references to PR/Questions on data entry, namely one around the creation of free-form text entry in PR #6436. Rather than add it directly to Metabase via a card, it could be stored as some auxiliary field to Metabase's h2/internal database, as done with text data in PR #6436. IMO, I don't that design personally - puts too much weight on the VisualizationSettings props and ends up being a bit hacky... One would handle the majority of the calculations on the front-end application and might incur far too many trips to and from the backend. Redux state could help, loading a copy of these key-pairs to the client on the application's load, but that'd be a nightmare to manage scalability.

We could add a table to Metabase with an API that leverages to in-build security/parsing that is a part of the Metabase we know and love. As for the physical storage of the document, that could be in a separate database as suggested in #6094, or in an H2 table that allows only certain, formatted data to be entered, such as a key, a value, and some DateTime value.  That still brings the risk of filling Metabase's internal storage with erroneous/broken data, or possible duplicate data, but it could serve as a legit first step to providing some basic key, value entry. and date associations to user data. Any other ideas?

I'd personally like to follow Metabase's current process for adding any document/data - digest any incoming data source into an abstraction. Just as Metabase takes fields and tables and 'saves' them internally, so should the process be for storing files. As for the physical location of the files - your assumption is as good as mine. I've not thought that bit out, as I'm focusing on the manual entry a simple key with a value. For the first iteration of the feature, you could have some key+date and value pair value entered via a simple form directly from the dashboard similar to the [entry and storage method of text cards](https://github.com/metabase/metabase/pull/6436), that is stored as DashCards. 

Now excuse me while I run and get my "but I meant to say" bucket for the incoming firestorm 🏃🏾‍♂️💨🔥🔥🔥

As for the **logic**, the comparison would be all of your given examples, YoY, MoM, WoW, and the like.  The only difference is that this would be constrained to the _selected key_:

> An example would be the latest "sales" key-pair with some percentage value with it's relation to the selected time range. Let's say this relation is the difference between the average "sales" over the past month. This would then be represented by a visual, let's say an up or down arrow, with the difference between the latest "sales" and the average-over-time. The latest "sales" figure would also be visualized.

I'll need to look into x-ray - This is exactly what I'd like to do to an existing static data item. Thanks for pointing this out! I'll be back as soon as I can with what I've been able to find 💪🏾😬

As for re-using segments, this could be done, but wouldn't the ripples in logic changes be absolutely massive? As far as I can tell, segments are used primarily as a means to reference some _range/semgment_ of data, not a static instance of data. It may be better to refer to some new item that references this static data point? But as @salsakran stated, we don't want to add any changes to the MBQL. I'll continue to look 👀

As for the **Trend Visualization**, #4479 hits the visualization right on its nose. I'm working on the ability to create a simple visualization of the icon/emoticon visual indicators - 
> conditional icon/emoticon visual indicators like you suggest (📈 👍 ➕ ⬆️ / 📉 👎 ➖ ⬇️ ) etc
With the conditional color as you've (referenced)[http://discourse.metabase.com/t/conditional-coloring-of-data-variable-progress-bar-goal/1404]. We'll see how exactly that turns out!

**Comment by funkeyfreak** [comment]
@salsakran, I agree - there is a lot to consider, and a serious design needs to be in hand. Do you mind if I share the design that I have in mind? I'd like to have this process than create a drive-by PR 😊\

As for unbinding the X-Ray logic, I'll drop into any conversations that I can find and see if I can't learn a thing or twenty. If you have any specific resources/PR/Questions that I can either help with/learn from, I am more than willing to put in the time to do so.

Thank you so much!

**Comment by funkeyfreak** [comment]
Sample Use Case 

* **Sally:** Jim, total number of opened bugs on our new system in Jira are 42 for this week, can you show that on your dashboard?
* **Jim:** Alright - _Jim navigates to the monthly-bugs-report dashboard, selects a button labeled "add static key-pair"_
_in the popup, enters the existing **key** of jira_bugs, enters in the integer **value**  42, and selects todays **date** - 02/06/2018@1513_
* **Metabase:** _given the **key** of jira_bugs, we will compare the **value** with any existing **keys** of name jira_bugs_
_Will display &uarr; or &darr; based on the calculated differences with all **keys** of name jira_bugs with respect to the date_
* **Jim:** We're down by 15%
* **Sally:** Fantastic! John in management will be happy to know!

**Comment by jornh** [comment]
> thanks for the breakdown. Also, sorry for my lack of response

 No problem - agree sometimes action beats talk 👍 at other times talk is exactly what's needed to specify the right thing, think: "measure twice, cut once" ... *ahem, and now it's me taking long time to respond!*

I see a lot of stuff went in over on your fork, and then it went quiet. Have quickly glanced over most of your PR's (which BTW is a pattern I should try to steal, bundling commits on my own fork into PR's) but I have not tried to run it, yet.  

Some comments:

**Data Entry** Still not convinced it's the route I would take, so good you got your 🔥 suit on 😉. Let me try rephrasing your sample use case with what we *already* do (with our Jira - and do or plan to do with other sources in general):

* @funkeyfreak: *Does not build the data entry part - but opts to either connect directly to Jira's DB or set up an ETL job to extract the historic values to an analytics DB that would otherwise get lost by overwrites later on* (For Jira we have actually done both - connected to it's MySQL, and set up some ETL, and both works nicely)

* **Sally:** - *Does other meaningful work*

* **Jim:** - *Does other meaningful work*

* **Metabase:** *based on @funkeyfreak's setup connects and pulls historic and current **keys** and **values** of jira_bugs* - then as above: *given the **key** of jira_bugs, we will compare the **value** with any existing **keys** of name jira_bugs
Will display ↑ or ↓ based on the calculated differences with all **keys** of name jira_bugs with respect to the date*

* **Jim & Sally:** *Says in unison:* Look, we're down by 15% ... Fantastic! John in management will be happy to know!

I guess this all comes down to the balance between the cost of work time spent on setting up automation for the different data sources vs cost of manually moving data. One benefit of the automated approach is that there is next to no extra cost of more frequent/timely updates.

**Logic** good observations you have there. I guess short term you can start small here. Then over time the scope can be broadened out to cover more variations. 

**Trend Viz** *REALLY looking forward to see what you come up with. That ↑ or ↓ one is of immediate use to me* 😄

**Comment by jornh** [comment]
Brought over from https://github.com/metabase/metabase/issues/2882#issuecomment-425461909:

> One idea I had that is different but related (let me know if this should be a separate issue): The ability to visualize custom data without persisting it. I think Metabase has great visualisation capabilities, and depending on the user skills it may be quicker / easier to enter / paste some data and ask Metabase to visualize it to make sense out of it, rather than do that in Excel or some other tool.
>
> I understand that persisting data is not Metabase's business, and that therefore that question would not be shareable (or maybe live only in memory), but even with this limitation it could be useful.

I think your “*... depending on the user skills it may be quicker / easier to enter / paste some data and ask Metabase to visualize it to make sense out of it ...*” is exactly the **key point** here. The answer varies depending on which type of user you want to target here:

* If the user doesn’t mind entering/reformatting into a [SQL `VALUES` statement](https://modern-sql.com/feature/values) the feature is actually already there! Example use in Metabase: https://github.com/metabase/metabase/issues/8433#issuecomment-417732233

* If you want more polish - then - what user and UX scenario do you have in mind? Though I think it shouldn’t grow into a too bloated feature. Because sometimes you simply have to say no: https://youtu.be/9AM6QQlgLSQ
