### ISSUE TITLE
import/export questions, dashboards and pulses feature

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6738]
In metabase if by accident and for any reason it crashes I do not have access to all the questions, pulses and dashboards that I have been created so far. Or in the case that I need to move these questions to another server I cannot import these questions and dashboards.

Is there any plan to add `import/export` feature to `Metabase`?

**Comment by jornh** [comment]
Sound a lot like https://github.com/metabase/metabase/issues/6485 already covers this. Which is already marked as a `feature` request (though I think the subject of this issue is more clear for a feature request)

**Comment by salsakran** [comment]
For the moment, we suggest backing up either the H2 database file or the MySQL/PG application database like you would any other database.

**Comment by ghsatpute** [comment]
@salsakran 
First of all, thanks for this amazing product.

I deployed Metabase using docker container, I tried it out and I instantly loved it. But now I realized the problem, in case my docker container stops working, all of my data is going to go away. Then I have to reconfigure all the users/questions/dashboards/data sources. 

In my case, I'm not sure how can I access the H2 database to take a backup of it?

**Comment by jornh** [comment]
@ghsatpute the [Running Metabase on Docker](https://metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html) chapter of the Operations Guide has you covered in the situation with how to get your data out of the container.

Note: Generally speaking questions are better asked/answered on https://discourse.metabase.com

**Comment by ghsatpute** [comment]
@jornh Apologies for asking this here. Will keep that in mind in future. 

The documentation was helpful. 
So that it helps other people who are facing the same issue let me summarize what steps I followed 
1. Get the `metabase.db` directory outside the docker container
`docker cp <container-id>:/metabase.db ~/metabase-data`
2. Stop the container
`docker stop <container-id>`
3. Start the new container with copied Metabase data files. 
`docker run -d -p 80:3000 -v ~/metabase-data:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" metabase/metabase`

**Comment by mazameli** [comment]
This is now possible via the [serialization](https://www.metabase.com/docs/latest/enterprise-guide/serialization.html) feature in the enterprise edition of Metabase.
