### ISSUE TITLE
Feature Request: Group Admins

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6799]
As a group "admin", I want to be able to view, add, and delete fellow group members.

Acceptable Criteria:

- Administrators can specify which users in a group have "group admin" abilities.
- A group "admin" can view, add, and delete group members.
- A group "admin" can make a group "user" a fellow group "admin".

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by CrazyZhangsk** [comment]
I'm especially glad to see the same ideas as I expected. I think this request has a substantial effect. It will directly improve the quality of Metabase and make it a better open source software. At that time, user group administrators can add data to their own user groups, so that each user group will manage their own data independently, of course, this is more detailed. Even if a super administrator manages data between groups and then manages users within his own group by a group administrator, it's a great experience.

**Comment by HosAkh** [comment]
I would really this option as well. Also the feature of allowing the admin of each group to be able to only create a certain number of users.

**Comment by luizarakaki** [comment]
Group managers are now available in Pro/EE plans
https://www.metabase.com/docs/latest/people-and-groups/managing#group-managers
