### ISSUE TITLE
New Question on a BiqQuery standard SQL view issue

### ISSUE THREAD

**Issue by totogo** [metabase/metabase#6803]
I'm trying to create a New Question in Metabase on a BigQuery view, which was created on standard SQL, then I got this message: 

> ### There was a problem with your question
> Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
> Show error details
> ### Here's the full error message
> ```
> Cannot reference a standard SQL view in a legacy SQL query. 
> ```

From this issue #3012, I understand that in SQL editor, Metabase already supports standard SQL. But in my case, how can it generate standard SQL?

**Comment by salsakran** [comment]
We're currently using Legacy SQL for BigQuery, and you can't mix modes.

**Comment by JoaquinIbar** [comment]
It works fine the in the advance editor (just like it is mentioned in issue #3012) but it will be nice to have it in the UI query builder so any none advance user can access a StandardSQL view as well.

**Comment by eebsidian** [comment]
Is there a way around this issue?  We are building our data model in BigQuery views, and want to allow the custom query builder to read from these views.  Did you guys create a hack to solve it?

**Comment by kimroen** [comment]
Just to share a use case:

We use [Segment](segment.io) to send data from various sources to BigQuery, and then we wanted to view that data using MetaBase.

The issue with this is that the way Segment handles de-duplication of data in BigQuery is by creating a view for each table, which is what you're supposed to use to view the data. When I try this I get the error this issue mentions.

Ideally we'd like to allow non-programmers to add new sources and things, so some options we've looked at like only using SQL-mode in MetaBase for this or re-writing the views Segment makes in legacy SQL mode aren't real options.

Recreating what the views do in MetaBase is not an option either as far as we've been able to work out (especially not without using SQL-mode).

We're currently looking at using Redshift instead of BigQuery to get around this, but the price difference between these is quite substantial.

**Comment by eebsidian** [comment]
We have exactly the same setup as you @kimroen .

**Comment by eebsidian** [comment]
Perhaps this @kimroen ? 

https://gist.github.com/gitram/8eebbb2f6695583d0bf9b9181cfbbeef

**Comment by kimroen** [comment]
@eebsidian Not sure what that would do, but it's worth noting that the SQL modes does have differences, so you can't just say that the code is using a different syntax without changing anything in all cases.

**Comment by eebsidian** [comment]
Right, point taken @kimroen :)

**Comment by andras-sereny** [comment]
Wouldn't it be possible to create a completely new database type `BigQuery Standard SQL`, alongside the database type `BigQuery`? This new database type would then build up a connection that always uses standard SQL.

**Comment by jkradddic** [comment]
Any update on supporting standard SQL default for custom query builder? We're using Views a lot and want to be able to give more people internally access.

**Comment by mazameli** [comment]
This has become an issue for one of our larger users who are migrating from Postgres to BigQuery using standard SQL.
