### ISSUE TITLE
Dashboard revision history revert bugs

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6884]
Can’t confirm that this is a regression, but I’m seeing some funky behavior with dashboard revision history when attempting to revert, specifically when trying to revert back to a state before a card was added. This video gets cut off, but you get the idea. It is *not* restricted to text cards, though that was my original suspicion.

[can't-revert.mp4.zip](https://github.com/metabase/metabase/files/1701324/can.t-revert.mp4.zip)

It sometimes causes the cards to get resized really tiny instead of getting properly removed:

![screen shot 2018-02-06 at 4 48 18 pm](https://user-images.githubusercontent.com/2223916/35892524-8c298058-0b5e-11e8-8b44-7171ed71785e.png)

This is the 500 error I'm seeing in the logs right after an attempted reversion that failed:

```
Feb 07 00:51:47 ERROR metabase.middleware :: POST /api/revision/revert 500 (13 ms) (14 DB calls)
{:message "Assert failed: (integer? dashboard_id)",
:stacktrace
["models.dashboard_card$dashboard.invokeStatic(dashboard_card.clj:61)"
"models.dashboard_card$dashboard.invoke(dashboard_card.clj:61)"
"models.dashboard_card$delete_dashboard_card_BANG_.invokeStatic(dashboard_card.clj:173)"
"models.dashboard_card$delete_dashboard_card_BANG_.invoke(dashboard_card.clj:168)"
"models.dashboard$revert_dashboard_BANG_.invokeStatic(dashboard.clj:121)"
"models.dashboard$revert_dashboard_BANG_.invoke(dashboard.clj:104)"
"models.revision$fn__25176$G__25152__25187.invoke(revision.clj:17)"
"models.revision$revert_BANG_$fn__25263.invoke(revision.clj:153)"
"models.revision$revert_BANG_.invokeStatic(revision.clj:151)"
"models.revision$revert_BANG_.doInvoke(revision.clj:140)"
"api.revision$fn__37370$fn__37373.invoke(revision.clj:39)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:248)"
"api.revision$fn__37370.invokeStatic(revision.clj:29)"
"api.revision$fn__37370.invoke(revision.clj:29)"
"middleware$enforce_authentication$fn__32961.invoke(middleware.clj:123)"
"api.routes$fn__46092.invokeStatic(routes.clj:81)"
"api.routes$fn__46092.invoke(routes.clj:81)"
"routes$fn__47843$fn__47844.doInvoke(routes.clj:106)"
"routes$fn__47843.invokeStatic(routes.clj:101)"
"routes$fn__47843.invoke(routes.clj:101)"
"middleware$log_api_call$fn__33060$fn__33062.invoke(middleware.clj:342)"
"middleware$log_api_call$fn__33060.invoke(middleware.clj:341)"
"middleware$add_security_headers$fn__33010.invoke(middleware.clj:255)"
"core$wrap_streamed_json_response$fn__48454.invoke(core.clj:64)"
"middleware$bind_current_user$fn__32965.invoke(middleware.clj:144)"
"middleware$maybe_set_site_url$fn__33014.invoke(middleware.clj:279)"]}
```

**Comment by flamber** [comment]
**Reproduce**
1. Empty dashboard
2. Add a table and resize it, and click Save dashboard
![image](https://user-images.githubusercontent.com/1447303/111635250-961bac80-87f7-11eb-9221-40962292082c.png)
3. Add textbox and move it to the right, and click Save dashboard
![image](https://user-images.githubusercontent.com/1447303/111636041-67ea9c80-87f8-11eb-84d9-1a05e6944f27.png)
4. Revert back to the first listing of added card
![image](https://user-images.githubusercontent.com/1447303/111635994-5bfeda80-87f8-11eb-9ed6-952aceb9e859.png)
5. (might have to browser refresh - #12581) Dashboard now looks like this:
![image](https://user-images.githubusercontent.com/1447303/111636225-8ea8d300-87f8-11eb-8418-13ddc9215b4b.png)
6. Editing the dashboard and dragging the visible card will reveal the other card underneath
![image](https://user-images.githubusercontent.com/1447303/111636531-df203080-87f8-11eb-9822-1b54b51ffd82.png)

I have a feeling that this is what might have been behind #13498

**Comment by calherries** [comment]
This is an old issue and I can't reproduce Maz and flamber's issues entirely. The issues have mostly been fixed. However, the root cause of the issue persists and it is manifesting in a different way. 

Repro:
1. Create a dashboard.
2. Add a card. Don't change its size (it should be 3x4). Save.
3. Observe the revision history. There should be three revisions: created dashboard, added a card, and rearranged the cards.
4. Revert to the last "added a card" revision. It should show the card with a different size. 4x4.

There are two things wrong:
1. There shouldn't have been a "You rearranged the cards" revision. You just added a card.
2. Reverting to the "added a card" revision shouldn't change the size of the card to a size it's never been. It should revert to the size of the card when you first saved it.

The root cause of this issue is that there are two API calls that happen when a card is added to a dashboard:

1. The card is added to the dashboard with a POST request, which contains only the card and dashboard ID. The BE creates a dashcard filling in default data where it is not provided (like a default size and position). This generates the first revision, with a description "added a card".
3. The card is then immediately updated with a PUT request, with all the data from the frontend including the position of the card in the dashboard. This updates the position and size of the stored dashcard, creating a second revision with the description "rearranged the cards".

The solution to this madness is to send all the dashcard data in the first POST request that creates the dashcard, including the size and position of the dashcard. Then there will be no second revision, even if the same card is in the following PUT request.
