### ISSUE TITLE
Command Lein Uberjar Failed

### ISSUE THREAD

**Issue by navdeepghai1** [metabase/metabase#6933]
I executed **lein uberjar** command in ubuntu Ubuntu 16.04.3 LTS. While execution this command process many Jar files but suddenly suspended with some errors.

**I Executed this command inside metabase repository** 
**Same error I am also getting while building repository using ./bin/build command**

**Please check the error detail below for more information.**

```
$ lein uberjar
Could not find artifact io.crate:crate-jdbc:jar:2.1.6 in central (https://repo1.maven.org/maven2/)
Could not find artifact io.crate:crate-jdbc:jar:2.1.6 in clojars (https://repo.clojars.org/)
Could not transfer artifact io.crate:crate-jdbc:jar:2.1.6 from/to bintray (https://dl.bintray.com/crate/crate): sun.security.validator.ValidatorException: No trusted certificate found
Could not find artifact io.crate:crate-jdbc:jar:2.1.6 in redshift (https://s3.amazonaws.com/redshift-driver-downloads)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Uberjar aborting because jar failed: Could not resolve dependencies
```

**Comment by jornh** [comment]
Probably was an intermittent certificate error (my browser at least says the cert at https://dl.bintray.com/crate/crate/io/crate/crate-jdbc/2.1.6/ is OK right now)

The `lein` output actually has a pretty good explanation of what went wrong: 

Could not transfer artifact io.crate:crate-jdbc:jar:2.1.6 from/to bintray (https://dl.bintray.com/crate/crate): sun.security.validator.ValidatorException: No trusted certificate found

**Comment by jornh** [comment]
@navdeepghai1 we’re you able to resolve this?

I think this should be closed as not an issue with Metabase

**Comment by navdeepghai1** [comment]
@jornh, I am able to run production version of metabase in my machine, even with open-jdk-9.

but building process keep failing due to security issues with open-jdk-9. 
I just removed open-jdk-9 and installed new version of Oracle-Java, now its working fine.

**Comment by jornh** [comment]
Great find @navdeepghai1 regarding root cause 👍 clearly my judgement in https://github.com/metabase/metabase/issues/6933#issuecomment-364700147 now seems wrong to me.

Looks like a google for it: https://www.google.dk/search?q=no+trusted+certificate+found+openjdk+bintray spits out similar things with workarounds from StackOverflow etc. on other libs.

In particular this post on the Bintray blog is interesting/enlightening... maybe even a bit scary: https://blog.bintray.com/2014/08/04/feel-secure-with-ssl-think-again/. Apparently Bintray and OpenJDK applies stricter security.

@salsakran do I remember correctly you were the one driving Metabase JDK 9 effort? Maybe worth noting this issue with OpenJDK 9 if the local .m2 cache is clean? (Which I assume is enough to reproduce the issue)
