### ISSUE TITLE
Is it possible to show x-axis marks vertically instead horizontally for graphs ?

### ISSUE THREAD

**Issue by vipulgupta-cpi** [metabase/metabase#6937]
Is it possible to show x-axis marks vertically instead horizontally for graphs ?

for the below graph what I want x-axis marks to be shown as vertically.
![defect](https://user-images.githubusercontent.com/27348488/36085153-96588e4a-0fe9-11e8-9487-57ef8a48026c.png)

**Comment by jornh** [comment]
Not currently as far as I know. 

As an alternative I would suggest using the **Row Chart** graph (basically just a bar chart turned sideways). It's IMO superior to bar charts for showing splits across (many!) different categories like you do here because you can easily read the texts without turning your head.

Only problem right now is that I see you added a goal line - and that's currently *not* supported with Row Charts (but I just asked for it in #6938). What I would do to work around that would be to add the visualization *two times* to a dashboard. One where you have all your categories - and a smaller separate one where you with a filter have limited the display to only the ones with Average Time above your goal. This puts an extra highlight on "the slow one's" which I guess is what you want to communicate?

**Comment by vipulgupta-cpi** [comment]
Row chart too doesn't solves the problem as they summed everything in the last row with name "others"

**Comment by salsakran** [comment]
Not currently.

Related to #6576

**Comment by mazameli** [comment]
Fixed by #7103
