### ISSUE TITLE
One date field for two filters

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#6947]
Hello,

Is there a way to do the following thing:

I am doing a SQL query where I join different tables which contain a date column. It looks like this: 

`
select orders.sclient_name as "Name", orders.sclient_phone as "Номер", iname as "Product", outcalls.campaign_name as "Campaign"
from orders inner join outcalls on orders.iparty_id = outcalls.iparty_id inner join items it on orders.iid = it.iid
where  {{DateB}} and {{DateC}}
`

Can I somehow add only one filter to my dashboard in order to set the date range in the tables at once? 

`
where  orders.datetime = {{DateA}} and outcalls.datetime = {{DateA}}
`

When I try to do something like the above mentioned I receive an error saying "**No operator matches the given name and argument type(s). You may need to add explicit type casts.**"

Thank you in advance!

**Comment by lindsay-stevens** [comment]
> No operator matches the given name and argument type(s). You may need to add explicit type casts.

This looks like a postgres error. What it means is that it's trying to compare your `orders.datetime` column with the value supplied via Metabase in `{{DateA}}` but it can't do the comparison because they're not the same type - possibly Metabase is passing in a string, or some other type that isn't the same as the type as `orders.datetime`.

I think there's a postgres setting to allow implicit casts but it's better to follow the tip in the error and add an explicit type cast. For example if `orders.datetime` is a timestamp with timezone, you could do the explicit type cast either with SQL syntax: `CAST({{DateA}} AS timestamptz)` or postgres-specific syntax: `{{DateA}}::timestamptz` - note I didn't test either of these but it's generally how explicit type casts are done in postgres.

**Comment by salsakran** [comment]
@petar777 What is the type of variable you are giving `DateA`?

**Comment by petar777** [comment]
Sorry for the late response. @lindsay-stevens  I tried doing what you mentioned but unfortunately it does not help. @salsakran  it is a timestamp.

**Comment by JMGGarcia** [comment]
Hello,

Is there any update on this? In my case, I want to compute the ratio of one metric over another that are in two different tables over a given period of time. I can't really have them in the same table since these metrics are aggregated in different ways.

**Comment by petar777** [comment]
@JMGGarcia I found a way around this that worked for me. If you want set to set the date of one table to be equal to a metabase variable which is from another one you can do it like so:

    SELECT *
    FROM table_A
    WHERE cast(table_A.date_value AS date // hour // whatever you need) IN (
     SELECT cast(table_B.date_value AS date // hour // whatever you need
              FROM table_B
              WHERE {{table_B.date_value}})

I hope it helps :)

**Comment by JMGGarcia** [comment]
@petar777 Thanks for the help! Your solution works in the case the all the dates in `table_A` appear in `table_B`, which is not always the case for my problem. Either way, if there is no better solution, I can always add these values to `table_B` (or a new table just for this purpose). Thanks!

**Comment by petar777** [comment]
@JMGGarcia if you can explain your problem in further detail I might help.

**Comment by JMGGarcia** [comment]
@petar777 Imagine I have two tables (`tA` and `tB`) that aggregate the number of times sone events (say `eA` and `eB`) happen by the hour. So `tA` might look like: 

```
timestamp           | total_eA 
-------------------------------
01-01-2000T01:00:00 |        5
01-01-2000T02:00:00 |        6
01-01-2000T04:00:00 |        1
...
```

And `tB`:
```
timestamp           | total_eB 
-------------------------------
01-01-2000T01:00:00 |       23
01-01-2000T03:00:00 |       46
01-01-2000T04:00:00 |       13
...
```

And I basically want `sum(total_eA) / sum(total_eB)` within a given time interval. Since I don't store hours where there are no events, following your solution, hours that appear in one table and not in the other might not count for the total (i.e. they are ignored by the `IN` operator). Hopefully I was clear on what the problem was.

**Comment by JoaquinMontesinos** [comment]
@JMGGarcia @petar777  Did you solve this issue? I have same problem. I am trying to use one filter to both tables. It works when I use 1 filter value but not for various values. I have not idea how to solve this problem, could you explain me how did you solve it?
I am using subqueries.

SELECT (b.count_one/b.count_two) as CPI, b.count_two, b.count_one, b.M_S
FROM
(SELECT count(table1.Name) as count_two , a.count_one, a.M_S
FROM table1,
(SELECT sum(table2.Cost) as count_one, M_S
FROM table2
WHERE 1=1
[[AND {{filter}}]]
)a
WHERE 1=1
[[AND table1.M_S = a.M_S]]
)b

I thought to use two filters and equalize 1 of them with the other, using at really only one for the filtering, but it give me errors. 
[[AND {{filter2}} = {{filter}}]]

**Comment by joshhornby** [comment]
Did anyone work this out? I have a query which joins two tables and I want to use 1 date filter across two tables. Looks like this currently isn't possible.

**Comment by herrycriestian** [comment]
> Did anyone work this out? I have a query which joins two tables and I want to use 1 date filter across two tables. Looks like this currently isn't possible.

I Also need this feature

**Comment by JoaquinMontesinos** [comment]
@herrycriestian,  @joshhornby Try this:

SELECT count(xyz)
FROM
(SELECT max(date_column) as min_dt , min(date_column) as max_dt
FROM table1_calendar
[[AND {{column_with_date}}]]
)dt, table2
inner join table3  on  table2.x = table3.y
WHERE 1=1
AND table2.dt BETWEEN dt.min_dt AND dt.max_dt
AND table3.dt BETWEEN dt.min_dt AND dt.max_dt

**Comment by flamber** [comment]
Closing in favor of #4509/#3156. Related to #3324
