### ISSUE TITLE
[IMAGE / TEXT] Possibility to add logo and texts and others images on Dashboards

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#6986]
A feature that I think that is missing on Metabase is the possibility to add **images** and **titles** on dashboards, I searched for issues and I did not find any of type. This feature for us will be very useful.

Please, who needs, give a :+1: on this Issue.

**Comment by jornh** [comment]
Sounds like what you want is the **Text Card** feature part of version 0.28 (that’s why there are no open issues but some closed ones 😀)

See the https://metabase.com/blog and look for the v0.28 release post

**Comment by kdoh** [comment]
@jornh is spot on once again. At present our solution to this is our Text Card feature which supports including images via markdown. 

![text-boxes](https://user-images.githubusercontent.com/5248953/36441533-ccd656ca-1627-11e8-9d84-ad169f405bf7.gif)

I'm going to close this since it is possible to do this, but we'd love your feedback on the feature so feel free to give us your thoughts in this thread or [in our discussion forum](http://discourse.metabase.com/).

**Comment by dannyeuu** [comment]
Wowow Thanks, I will update it now!

**Comment by Schusti91** [comment]
It seems the image gets stretched automatically to the full size of the text box.
![image](https://user-images.githubusercontent.com/22288752/41314335-cc9e44b6-6e8c-11e8-8954-90a681fe255b.png)
the actual size is 64px

**Comment by jornh** [comment]
@Schusti91 the issue your commenting on is already resolved and closed. It’s better to open a separate issue with your enhancement request or bring it up in the discussion forum linked to above. I guess the scaling to 100% is done to avoid overflowing with wider images. Hard to make everyone happy in all cases with one autoscaling behavior. 

If you want to have a go at tackling this yourself here’s a related pointer to the Markdown library in use: https://github.com/rexxars/react-markdown/issues/174 I’d imagine consensus has to be found on a good syntax for specifying non-default scaling. AFAIK there is nothing standardized for Markdown
