### ISSUE TITLE
Document what does "enum" do?

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#7038]
When I click Metabase Admin -> Data Model -> select any field -> Cogwheel -> Type, one option is "Enum"

I think the documentation page at https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html should explain what the "Enum" value is supposed to be used for.

@mazameli ?

**Comment by jornh** [comment]
I think it’s there it probably just need the word `enum` in the description, search for:

> Another option is custom remapping, which is currently only possible for numeric fields. This lets you map every number that occurs in ....

Which even has a picture in the page you linked to. 

So a slight rewording is probably all that’s needed - any suggestions?

**Comment by eladeyal-intel** [comment]
I don't know what Enum does (and the documentation does not help).

I use custom remapping heavily with "Categories". Is enum the same or different than "category"?

**Comment by mazameli** [comment]
"Enum" is an abbreviation for "enumerated type," which is a special kind of variable which can only be set to one of the values in a static, set list which is defined ("enumerated") when the variable is declared. So I wouldn't set a field in Metabase to "enum" unless you're sure the actual field type in your database is an enumerated type.

Setting field types in the data model section of Metabase is a good idea, because Metabase tries to do intelligent things based on what it knows about your data, and we'll continue to ship new features which will be even better when there's good metadata to rely on. However, there are also some metadata settings which we acknowledge are confusing because they don't immediately appear to do as much as other field type settings do. 

I'll see if I can carve out some time this week to clarifying what the various data model settings do in the docs.

**Comment by flamber** [comment]
Closing this in favor of the more generalized #6425
