### ISSUE TITLE
Date labels overlapping (how to control date label formatting?)

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#7055]
We have a date column in PostgreSQL, which is storing data in YYYY-mm-dd format (no hh:mm:ss or timezone). When rendering a line chart on a dashboard, the date labels overlap:

![screenshot from 2018-03-02 12-10-24](https://user-images.githubusercontent.com/17307/36894231-59febdce-1e13-11e8-8910-3388a3b7478e.png)

As can be seen, the date labels are including the full time, even though it does not exist in the data. How can I override the label (date formatting) for the date axis?

# Environment
- Metabase version: 0.28.1
- Metabase hosting environment: AWS
- Metabase internal database: Postgres

# Similar issue
This issue is related to, but not entirely a duplicate of #5246

**Comment by salsakran** [comment]
when you say `date column in PostgreSQL, which is storing data in YYYY-mm-dd` do you mean a `date` column in PG or a `char`/`vchar`/`text` column that contains a date?

**Comment by brylie** [comment]
Data type is `date`, data is in `YYYY-mm-dd` format.

**Comment by mazameli** [comment]
Addressed in #7103, but leaving this open until we figure out the logic for using abbreviated labels for months and days of week.

This issue is also referencing the same problem reported in https://github.com/metabase/metabase/issues/5859, where Dates are incorrectly getting times appended to them, consequently showing a time in the axis labels "even though it doesn't exist in the data."

**Comment by salsakran** [comment]
closing this since we've improved the situation significantly in #7103, the time attachment issue is covered in #5859
