### ISSUE TITLE
Add function to customize number in the pie chart

### ISSUE THREAD

**Issue by abmj1979** [metabase/metabase#7094]
Hi,

In the Pie Chart, actually isn't possible customize the number.

When using multiples charts on the dashboard , its hard to see different formats :(

Ex..: 194.160,32 in different formats 

![image](https://user-images.githubusercontent.com/22889283/37150028-eefcf3f6-22ae-11e8-84fd-7fba89ae5d58.png)

**Comment by flamber** [comment]
Hi @abmj1979 
This was fixed in version 0.31, which introduced a lot of formatting settings (Visualization :gear:)
![image](https://user-images.githubusercontent.com/1447303/53134571-53664800-353d-11e9-92ed-e4911443f261.png)

Hi @jbrooksuk 
I can understand what you're asking for, but it's different from the original question. Have you seen the Gauge visualization, which would probably do what you're asking for - without the "Total" :wink: 
![image](https://user-images.githubusercontent.com/1447303/53134879-97a61800-353e-11e9-93bb-55a5c35e993d.png)

**Comment by abmj1979** [comment]
hi @flamber, tks for your tip!!

i'm closing the issue.
