### ISSUE TITLE
Default parameters are missing when a metabase question  is shared/embedded in any applications

### ISSUE THREAD

**Issue by yaswanthpsl** [metabase/metabase#7120]
### Bugs
- Your browser and the version: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
- Your operating system: (Mac Sierra)
- Your databases: Sample Dataset
- Metabase version: v0.28.1
- Metabase hosting environment: Doker

- *Repeatable steps to reproduce the issue*
1. Create a question with default parameters
![image](https://user-images.githubusercontent.com/25974743/37394775-968139bc-279a-11e8-8d25-f514d3727c6d.png)

2. Sharing and Embedding (Need Admin access)
- Click on embedding icon, which opens preview/code for embedding 
![image](https://user-images.githubusercontent.com/25974743/37394828-bdf55924-279a-11e8-8e6b-74c2155765e0.png)

Issue: 
Even though default parameters are configured in the question SQL, they are not getting populated (ProductId), only the last parameter gets populated (Total).

Good to have (Not a bug):
Loading indicator when filtering is applied in shared/embedded metabase question. (Right now: no loading indicator when new search happens) 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by s-andringa** [comment]
I'm running into a similar problem with prefilled values of dashboard filters that are disabled for sharing.

**Comment by yaswanthpsl** [comment]
Hey s-andringa,  by default parameters to the question are locked, you need to make them editable in order to view in the embedded question in iframe. 
![untitled diagram 4](https://user-images.githubusercontent.com/25974743/37830755-31850a9e-2ec9-11e8-8f13-2c4a7a08deaf.png)

**Comment by s-andringa** [comment]
Thanks @yaswanthpsl! What I need is to _hide_ the filters from the embedded dashboard (not question), so I disable them. But if I do that, no filter values are applied, while I'd like the default values to be applied (as filled out in Metabase, where the filters are visible). I realize now that this is a bit different from the issue here. I might open a new issue.

**Comment by adjenks** [comment]
My parameters are set to editable and they do not show up in the embedded iframe.

**Comment by slickrock22** [comment]
We are experiencing a similar problem.  We allow a embedded filter to be editable.  It shows up.  The we pass a value into that filter when we pass a user to Metabase and it filters the data but the Filter is no longer available on the embedded dashboard to either remove or add to.  Is this by design?

**Comment by iamvishalbisht** [comment]
**Which version of metabase has this issue fixed ?** 

We are experiencing a similar problem. We allow a embedded filter to be editable. It shows up. The we pass a value into that filter when we pass a user to Metabase and it filters the data but the Filter is no longer available on the embedded dashboard to either remove or add to. Is this by design?

**Comment by flamber** [comment]
**Steps to reproduce**
1. Native question > Sample Dataset
2. `SELECT * FROM PEOPLE WHERE {{birthdate}} AND {{source}} AND {{state}}`
3. `{{birthdate}}` as Field Filter of People.BirthDate with default of `Past 30 Years`
`{{source}}` as Field Filter of People.Source with default of `Affiliate`
`{{state}}` as Field Filter of People.State with default of `CA`
![image](https://user-images.githubusercontent.com/1447303/83874787-571fdd00-a736-11ea-94d0-f44053c5d666.png)
4. Enable Public Sharing and go to URL `/public/question/<uuid>`, which updates the URL on load to `/public/question/<id>?state=CA`. Only the last filter gets the default value defined automatically.
![image](https://user-images.githubusercontent.com/1447303/83875457-63f10080-a737-11ea-8d48-5ed7774b9caa.png)
5. Enable Embedding, also, only the last Editable filter gets the default value defined automatically.
Go to the URL `/embed/question/<token>`, which updates the URL on load to `/embed/question/<token>?source=Affiliate`. Only the last Editable filter gets the default value defined automatically.
![image](https://user-images.githubusercontent.com/1447303/83875644-c34f1080-a737-11ea-81c7-c3db93642200.png)

Workaround is to apply the parameters manually to the URL, which of course defeats the purpose of having a default value set on the variable filter, but that is still applied for anyone viewing the non-shared question, or when using the question on a dashboard.
Public Sharing:
```
/public/question/<uuid>?birthdate=past30years&source=Affiliate&state=CA
```
Embedding Sharing (only possible for Editable filters):
```
/embed/question/<token>?birthdate=past30years&source=Affiliate
```

Related to #9266
