### ISSUE TITLE
Admin menu not working in ES

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#7155]
I have been working in ES translation to catch some missing strings and general functionality.

I have found a few issues that I will create as I verify them. For the moment the important one is that the admin menu is not working correctly. I think we translated some keys instead of labels.

In English when I click on the Setup menu the URL changes to

```
admin/settings/setup
```

in Spanish, it changes to

```
admin/settings/configura
```

and obviously does not work. Some other entries on that menu also fail while some do work.

**Comment by kdoh** [comment]
@joebordes Good catch! I'm pretty sure [this line](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/selectors.js#L435) is causing the problem since it's using the translated names as slugs to use in the URLs. My gut here is the right thing to do is just be explicit about our slugs here instead of slugify-ing the name.

**Comment by tlrobinson** [comment]
@kdoh Yes, that sounds right.

If someone wants to submit a PR that removes the lines @kdoh linked to and adds `slug` properties to the `SECTIONS` above that would be lovely.

I dumped the current slug names for reference: `["setup","general","updates","email","slack","single_sign_on","authentication","ldap","maps","public_sharing","embedding_in_other_applications","caching","x_rays"]`

**Comment by kdoh** [comment]
Working on it right now.
