### ISSUE TITLE
Unable to find Add text box in Dashboard

### ISSUE THREAD

**Issue by atishi1** [metabase/metabase#7158]
Hey,

I am using metabase version 0.23.1, but on editing the dashboard , I am unable to see the option of "Add Text Box" as stated in earlier isssue!
"Free-text markdown boxes in dashboards #6360"

<img width="924" alt="untitled" src="https://user-images.githubusercontent.com/34337973/37646982-20a2c8b2-2c51-11e8-9dae-bf51fe634b12.png">

**Comment by mazameli** [comment]
Hi there! The version you're using, 0.23, came out a year ago, and the latest version, which includes text boxes, is version 0.28. Because Metabase is self-hosted, you have to upgrade it yourself; here are instructions on how to upgrade, depending on how you have it set up: https://www.metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase
