### ISSUE TITLE
Trying to detect the timezone?

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7190]
Not sure how many times this does happen but querying database to detect timezone probably isn't a great idea. Esp with databases such as BigQuery where the cost structure is based on queries. 

![screen shot 2018-03-22 at 23 22 12](https://user-images.githubusercontent.com/1330677/37814620-1dd14b26-2e28-11e8-9083-783c3d0ddaff.png)
![screen shot 2018-03-22 at 23 22 20](https://user-images.githubusercontent.com/1330677/37814622-1deaa382-2e28-11e8-9e2b-fd7d4b1fcb24.png)

**Comment by salsakran** [comment]
I believe this happens fairly infrequently. Can you verify @senior ?

With bigquery, given that it process 0 bytes, it should be free.

Closing this, as we're doing this to fix a category of timezone bugs, and my belief is that it only happens when you add a database. If I'm wrong, @senior, please re-open.

**Comment by senior** [comment]
@salsakran It runs as part of sync, so once per hour on most setups. We can adjust how often it runs or change it up if needed.

**Comment by VikramTiwari** [comment]
@salsakran Ah! I thought that 10MB min query size was applicable here as well. It isn't.

@senior It being part of sync process sounds fine as well.
