### ISSUE TITLE
Increase JETTY logging verbosity 

### ISSUE THREAD

**Issue by kkuchta** [metabase/metabase#7255]
Forgive me if this is already documented somewhere, but: Is it possible to configure metabase to log all web requests it receives?

I've been messing around with a custom `log4j.properties` file, but the best I been able to do is get metabase to log api requests like:

```
GET /api/dashboard 200 (160 ms) (52 DB calls). Jetty threads: 8/50 (3 busy, 7 idle, 0 queued)
```

Unfortunately I'm currently trying to track down a problem where non-api requests (index.html, vendor-bundle.js, app-bundle.js, etc) are taking minutes to load.  I don't yet know if this is a metabase problem or an issue with our hosting or what.  It'd be really useful to have metabase log somewhere if/when it receives the request for these resources, but I can't seem to find any way to do that.  Any ideas or suggestions?

(If it matters at all, I'm using the `metabase/metabase:v0.28.4` docker image).

**Comment by salsakran** [comment]
what are you running Metabase on?

We've also occasionally hit minute long load times on beanstalk but haven't been able to reproduce them.

**Comment by kkuchta** [comment]
We're running on Aptible, a heroku-like platform-as-a-service focused on HIPAA.

It seems like these hanging requests are less "slow" and more "non-responsive."  Sometimes they eventually complete, and other times they time out after 5 minutes:

<img width="745" alt="screen shot 2018-04-02 at 5 00 39 pm" src="https://user-images.githubusercontent.com/820965/38222039-7d854000-3697-11e8-8c1c-18dca09bd4dd.png">

I'd love to contact aptible support and see if they have any ideas, but it'd be good to know for sure whether the request are even getting to metabase or not (eg via logging all requests).

**Comment by jornh** [comment]
Since Metabase runs on top of an embedded Jetty via clojure ring I guess https://www.google.com/search?q=jetty+log+requests could be what you are looking for? 

Not sure if `log4j.properties` tweaking based on http://zetcode.com/java/jetty/logging/#request-log can do it or if it might involve adding a bit of code like in the fairly recent https://spinozakotlin.github.io/tutorials/jetty-request-log post. Oh maybe that should be done in clojure 😉 using [some ring middleware](https://www.google.dk/search?q=ring+log4j+requests)
