### ISSUE TITLE
Empty pulses sent when the database times out

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7279]
It's currently possible to get a database related failure, such as a timeout and have that error manifest itself as an empty body to a pulse. The pulse should not be sent if there was an error retrieving the data. Instead we should write the full exception to the log as an error and not send the pulse.

**Comment by salsakran** [comment]
The glib answer is "that's what the activity feed is for". 

Also, we can email the admin.

We should _not_ be sending out pulses with error messages in them to civilians (admins is ok so long as the title says something like "ERROR").

**Comment by mazameli** [comment]
Fair enough. My main point of feedback is that the fact the pulse didn't get sent should be exposed or communicated, and emailing the pulse creator makes sense. I think it probably needs to be a push communication rather than expecting admins to go check the activity feed. I.e., I think it's better for them to be proactively informed it didn't get sent than to get "WTF where is my pulse?" messages from customers or VIPs and then have to go figure out what's up.

**Comment by senior** [comment]
Agreed on the not emailing errors to users. Probably the most we would want to do is to let the user know that there was an error creating the pulse (no specifics or error messages) and that admin intervention is required. Going the extra mile would include a reference id that the admin could correlate with an error message in the log.

**Comment by senior** [comment]
@mazameli @salsakran Looking at the code and thinking about this, if we're going to let the user know via pulse that something went wrong, my guess is we need to handle failures at the card level, rather than just "the pulse failed". Since pulses can have many cards and maybe just one of them fails (or maybe all of them). Should we have a failure image or something similar that we would include instead of the results? We currently have an image like that for no results.

**Comment by flamber** [comment]
I've not been able to reproduce this, nor have I ever seen this problem.
