### ISSUE TITLE
Mac installer doc does not cover uninstall

### ISSUE THREAD

**Issue by germanviscuso** [metabase/metabase#7280]
This is a feature request for the docs project. Please add a description on how to uninstall the Mac version since this is not covered anywhere AFAIK:
https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-the-metabase-mac-app.md
And maybe, as there seems to be a formula in Homebrew for Metabase you might want to describe how to install it with this defacto package manager for OSX which will make the uninstall process a no brainer:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/metabase.rb
Thx!

**Comment by camsaul** [comment]
Since you uninstall almost all Mac applications the same way (by dragging them from `Applications` to the Trash) I can't think of any time I've actually seen a Mac app need offer an explanation for how to do it. That being said, if you would like to open a PR to add that information to the documentation we will happily consider it
