### ISSUE TITLE
Card query results API endpoint ignoring ignore_cache: true and returning cached results anyway

### ISSUE THREAD

**Issue by jchin17** [metabase/metabase#7282]
I have caching on for my questions but if I go to the question page and hit the Refresh button, it still immediately returns the cached result. The documentation suggests that hitting this button should override / replace the previously cached result.

Browser: Chrome 65.0 and Firefox 59.0
OS: OS X 10.11.6
Database: MySQL, Metabase is also using MySQL
Metabase Version: 0.28.1 (Not the latest but I don't see any of the newer patches mentioning caching)

**Comment by tjmcewan** [comment]
We're hitting this too.  Backed onto Aurora MySQL.  Let me know if there's any debugging info we can provide.  Thanks!

**Comment by pint-drinker** [comment]
@tlrobinson 
I am using v0.36.5.1 and I think this bug is back.

I have caching on, and I execute a query that takes ~30 seconds. It is properly cached so when i view it in dashboards and such, it appears instantly. However, when I refresh the query, it continues to appear instantly.

I went to the logs to confirm what was happening, and interestingly enough, every time I clicked refresh, the average execution duration continued to drop, as if the pulling of the data from the cache counted as a fully baked query. As a side effect, each refresh execution replaced the entry in the cache for the query before it, even though the query execution time (as the logs report below) was far below the minimum value i have specified in settings to warrant a cache (20 seconds, the default). Actually, I eventually got the average time down so low that the cache lifespan expired and did eventually re-perform the query (after like 10-15 refreshes when the average execution time was hundreds of milliseconds). 

I would expect that the refresh button would perform a fresh query, not pull from the cache, and properly replace the cache entry after the query is performed.

Here are my logs that confirm this behavior:

11-12 20:03:35 INFO middleware.cache :: Query took 29.9 s to run; miminum for cache eligibility is 20.0 s
11-12 20:03:35 INFO middleware.cache :: Caching results for next time for query with hash "95bf4675". 💾
11-12 20:03:35 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 29.9 s (12 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:39 INFO api.card :: Question's average execution duration is 6.2 s; using 'magic' TTL of 2.1 mins 💾
11-12 20:03:39 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 31.5 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:45 INFO api.card :: Question's average execution duration is 5.0 s; using 'magic' TTL of 1.7 mins 💾
11-12 20:03:45 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 12.8 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:48 INFO api.card :: Question's average execution duration is 4.1 s; using 'magic' TTL of 1.4 mins 💾
11-12 20:03:48 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 31.7 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:49 INFO api.card :: Question's average execution duration is 3.3 s; using 'magic' TTL of 1.1 mins 💾
11-12 20:03:49 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 30.3 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:50 INFO api.card :: Question's average execution duration is 2.7 s; using 'magic' TTL of 54.0 s 💾
11-12 20:03:50 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 44.6 ms (5 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:50 INFO api.card :: Question's average execution duration is 2.2 s; using 'magic' TTL of 44.0 s 💾
11-12 20:03:50 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 27.0 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:51 INFO api.card :: Question's average execution duration is 1.8 s; using 'magic' TTL of 35.0 s 💾
11-12 20:03:51 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 34.5 ms (5 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:51 INFO api.card :: Question's average execution duration is 1.4 s; using 'magic' TTL of 29.0 s 💾
11-12 20:03:52 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 29.0 ms (5 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:52 INFO api.card :: Question's average execution duration is 1.2 s; using 'magic' TTL of 23.0 s 💾
11-12 20:03:52 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 11.3 ms (5 DB calls) App DB connections: 4/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:53 INFO api.card :: Question's average execution duration is 947.0 ms; using 'magic' TTL of 19.0 s 💾
11-12 20:03:53 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: completed] 32.0 ms (5 DB calls) App DB connections: 3/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)
11-12 20:03:53 INFO api.card :: Question's average execution duration is 772.0 ms; using 'magic' TTL of 15.0 s 💾
11-12 20:03:54 DEBUG middleware.log :: POST /api/card/1230/query 202 [ASYNC: canceled] 1.0 s (9 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (118 total active threads) Queries in flight: 0 (0 queued)

**Comment by flamber** [comment]
@pint-drinker Excellent details about getting the duration down will trigger a cache flush.
This is a regression since 0.35.0 (tested 0.34.3, which behaves as intended). It correctly sends the `{"ignore_cache":true}` in the request, but it just seems like it is ignored.
Only tested SQL, since I can consistently reproduce (not sure if QB behaves differently, but I don't think so).
`SELECT pg_sleep(10)` (Postgres) - `SELECT sleep(10)` (MySQL)

**Comment by pint-drinker** [comment]
@flamber thank you for the quick response. Let me know if I can provide more details down the line.

**Comment by nautilus28** [comment]
I believe the bug occurs because the [*ignore-cached-results*](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/cache.clj#L40) dynamic binding is not bound to the async thread that runs the query.

**Comment by camsaul** [comment]
We're binding the value here:

https://github.com/metabase/metabase/blob/b7180693544069490f37c076adc0b8d8365ed6dd/src/metabase/api/card.clj#L652

and looking at the value here:

https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/src/metabase/query_processor/middleware/cache.clj#L150

We don't have end-to-end backend tests around the API endpoint, just that cached results get returned if the dynamic variable is bound. So I'm guessing the bug is related to the binding
