### ISSUE TITLE
Public questions with filters showing error message

### ISSUE THREAD

**Issue by abmj1979** [metabase/metabase#7338]
- Your browser and the version: 65.0.3325.181
- Your operating system: Windows 10 64 bits
- Your databases: Postgre
- Metabase version: v0.28.5
- Metabase hosting environment: Ubuntu 16.04.4 LTS
- Metabase internal database: Mysql

Steps to reproduce the error

1)Create a question with variables

2)Make the question public

If the variables aren't set as required/mandatory, the question made public will show an error message. I think the correct way would be enable the user to set the value before the question run.

![image](https://user-images.githubusercontent.com/22889283/38681582-688f5f14-3e3f-11e8-944e-b55e370340d7.png)

If the variables  are not set as required/mandatory, the question made public will run, but won’t bring the first value of the variable, only the last one.
![image](https://user-images.githubusercontent.com/22889283/38681652-975f2e00-3e3f-11e8-87a5-b0ba7327101d.png)
![image](https://user-images.githubusercontent.com/22889283/38681687-ac2f0ed6-3e3f-11e8-81ad-05cee010e350.png)

-------

**Comment by salsakran** [comment]
can you share the JS and server logs for that time?

**Comment by abmj1979** [comment]
hi @salsakran 

sorry for my english. Is this what you need?

When param is required:

`04-20 14:45:56 [1mWARN metabase.query-processor[0m :: [31mQuery failure: 'Data inicial' is a required param.
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$fn__31387$process_query_and_save_execution_BANG___31392$fn__31393.invoke(query_processor.clj:281)"
 "query_processor$fn__31387$process_query_and_save_execution_BANG___31392.invoke(query_processor.clj:267)"
 "api.card$run_query_for_card.invokeStatic(card.clj:607)"
 "api.card$run_query_for_card.doInvoke(card.clj:593)"
 "api.public$run_query_for_card_with_id$fn__40258.invoke(public.clj:65)"
 "api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
 "api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
 "api.public$run_query_for_card_with_public_uuid.invokeStatic(public.clj:75)"
 "api.public$run_query_for_card_with_public_uuid.doInvoke(public.clj:71)"
 "api.public$fn__40264$fn__40265.invoke(public.clj:86)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.public$fn__40264.invokeStatic(public.clj:81)"
 "api.public$fn__40264.invoke(public.clj:81)"
 "middleware$genericize_exceptions$fn__37923.invoke(middleware.clj:359)"
 "api.routes$fn__46968.invokeStatic(routes.clj:79)"
 "api.routes$fn__46968.invoke(routes.clj:79)"
 "routes$fn__47029$fn__47030.doInvoke(routes.clj:106)"
 "routes$fn__47029.invokeStatic(routes.clj:101)"
 "routes$fn__47029.invoke(routes.clj:101)"
 "middleware$log_api_call$fn__37915$fn__37917.invoke(middleware.clj:347)"
 "middleware$log_api_call$fn__37915.invoke(middleware.clj:346)"
 "middleware$add_security_headers$fn__37865.invoke(middleware.clj:249)"
 "core$wrap_streamed_json_response$fn__52214.invoke(core.clj:67)"
 "middleware$bind_current_user$fn__37820.invoke(middleware.clj:138)"
 "middleware$maybe_set_site_url$fn__37869.invoke(middleware.clj:273)"]
[0m
04-20 14:45:56 [1mWARN metabase.middleware[0m :: An error occurred while running the query.
04-20 14:45:56 [1mDEBUG metabase.middleware[0m :: [31mGET /api/public/card/ba922aa3-58f6-47dc-a79c-d8efac03acf2/query 400 (1 s) (9 DB calls).[0m
"An error occurred."
`

when param is not required:

Apr 20 14:53:07 WARN metabase.query-processor :: Query failure: Unable to substitute 'data_inicial': param not specified.
Found: ("loja" "data_inicial" "data_final")
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
"query_processor$fn__31387$process_query_and_save_execution_BANG___31392$fn__31393.invoke(query_processor.clj:281)"
"query_processor$fn__31387$process_query_and_save_execution_BANG___31392.invoke(query_processor.clj:267)"
"api.card$run_query_for_card.invokeStatic(card.clj:607)"
"api.card$run_query_for_card.doInvoke(card.clj:593)"
"api.public$run_query_for_card_with_id$fn__40258.invoke(public.clj:65)"
"api.public$run_query_for_card_with_id.invokeStatic(public.clj:63)"
"api.public$run_query_for_card_with_id.doInvoke(public.clj:58)"
"api.public$run_query_for_card_with_public_uuid.invokeStatic(public.clj:75)"
"api.public$run_query_for_card_with_public_uuid.doInvoke(public.clj:71)"
"api.public$fn__40264$fn__40265.invoke(public.clj:86)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
"api.public$fn__40264.invokeStatic(public.clj:81)"
"api.public$fn__40264.invoke(public.clj:81)"
"middleware$genericize_exceptions$fn__37923.invoke(middleware.clj:359)"
"api.routes$fn__46968.invokeStatic(routes.clj:79)"
"api.routes$fn__46968.invoke(routes.clj:79)"
"routes$fn__47029$fn__47030.doInvoke(routes.clj:106)"
"routes$fn__47029.invokeStatic(routes.clj:101)"
"routes$fn__47029.invoke(routes.clj:101)"
"middleware$log_api_call$fn__37915$fn__37917.invoke(middleware.clj:347)"
"middleware$log_api_call$fn__37915.invoke(middleware.clj:346)"
"middleware$add_security_headers$fn__37865.invoke(middleware.clj:249)"
"core$wrap_streamed_json_response$fn__52214.invoke(core.clj:67)"
"middleware$bind_current_user$fn__37820.invoke(middleware.clj:138)"
"middleware$maybe_set_site_url$fn__37869.invoke(middleware.clj:273)"]

Apr 20 14:53:07 WARN metabase.middleware :: An error occurred while running the query.
Apr 20 14:53:07 DEBUG metabase.middleware :: GET /api/public/card/ba922aa3-58f6-47dc-a79c-d8efac03acf2/query 400 (1 s) (9 DB calls).
"An error occurred."
`

**Comment by senior** [comment]
@metabase/core-developers I've done some investigation on this and can describe what happens, just not sure what the best approach is to fixing it.

Currently when there is a question with required parameters (public or not public) and a user attempts to bring up that question, it immediately tries to run the question which fails due to the parameter not being populated. When logged in and not using the public URL, the user can see the parameter above the query, populate it and rerun the query, it works fine.

With public questions, the same initial failure happens as above when the question is initially loaded, though no details are given on that failure. It tries to run the query, the query fails. Only with the public URL of the question, there are no parameter boxes above the query, so the user is not able to populate the parameters (and the query will continue to fail).

It seems like we shouldn't try to run a question with required parameters before the user has been able to populate them. Maybe where we usually put the results we should include some indication that they need to populate parameters before running the query.

For the public URL, it seems like we need to include those parameter input fields somewhere or not allow these kinds of questions to be made public.

**Comment by mazameli** [comment]
@senior and I talked about this, and here's what we're thinking in terms of sequencing:

1. Resolve the immediate issue by enabling the user to set the parameter values, ideally merging that fix in 0.29 or 0.29.1
2. Improve the UX for queries (public or otherwise) with required variables (i.e., either ones explicitly marked as Required _or_ variables that are not inside an optional clause and not a field filter) by providing a friendly help message instead of an error, and visually indicating which filter widgets are required.
3. Remove the "Required" variable toggle, which is superfluous and confusing; always give the option to set a default value for a variable; and make it visually more clear when a filter widget has a default value.
4. In dashboards, if a question has required variables, we should somehow indicate that that's why the card isn't rendering, and explain that you need to have filters that map to them.

#1 by itself should close this issue. I'll create separate issues for #2 and #3, and I believe there's already an existing issue for #4 that I'll dig up.

**Comment by tlrobinson** [comment]
I think in the original design we intended for the query creator to always mark required variables as required, and always give required variables a default value, so that queries were always runnable. In  that design technically the only bug here is not forcing the creator to set a default value. But that was always sub-par since we don't parse the query to know which variables are required thus it's easy to create a broken query.

If we're ok with queries not running in their default state then we can do what @mazameli suggested.

**Comment by dannyeuu** [comment]
Any update on this issue? I'm running v0.29.3 and the problem remains.

**Comment by glennpierce** [comment]
Would it not be best to allow one to add a default value for the variable when defining the question. This would allow the question to render with no input ?

**Comment by camsaul** [comment]
Fixed by #10794
