### ISSUE TITLE
Cannot read property 'lat' of null - Allow filter empty/not empty (like for dates)

### ISSUE THREAD

**Issue by Vadorequest** [metabase/metabase#7361]
### Feature requests and proposals

It would be nice to be able to filter latitude and longitude fields to only select those with an actual value. I'm currently trying to generate a map chart based on lat/long fields but some of the rows have empty data and it fails with `Cannot read property 'lat' of null`

I believe something similar was done for the Date fields.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by javiercr** [comment]
+1 to this. It's quite common to not have latitude and longitude for all records (eg. users), and without being able to exclude those with null latitudes and longitudes there is no way to map those records.

**Comment by paaacman** [comment]
+1

**Comment by morganhankins** [comment]
- Setup a table with some rows missing lat/lon data ('is null')
- Tried to map the table: get "Cannot read property 'lat' of null" [expected]
- Added  "Filter: Latitude is not 0"
- Tried to map the table: Map works!

Maybe this issue is resolved? (Or is the OP asking for a different kind of filtering?)

**Comment by flamber** [comment]
@morganhankins Great work-around, but I think for this to be solved, Metabase should automatically handle the `null` rows by skipping them.
