### ISSUE TITLE
Not Able to Access the Mongodb from SpringBootApplication image inside the docker 

### ISSUE THREAD

**Issue by sourabhlodha** [metabase/metabase#7441]
Hi Team,

I have tried many option to access the mongodb image from docker.It works fine outside the docker but If I run the application in docker container it shows me error.Mention below are screenshot of error.Also share you the code of connection and commands which I am running.
Exception while running spring boot application
![image](https://user-images.githubusercontent.com/11154338/39245935-b8006192-48b2-11e8-88f4-5365fd51ba72.png)

Mongo Db Container Running
![image](https://user-images.githubusercontent.com/11154338/39245951-c44df860-48b2-11e8-8ff4-96d684668f39.png)

Java Code used for connect to docker mongodb image
MongoClient mongo = new MongoClient(new ServerAddress("0.0.0.0", 27017));

Command Tried
docker run testingsprint
docker run testingsprint --link mongo

Kindly provide me the solution.

Thank you
Sourabh Lodha

**Comment by jornh** [comment]
Hey there,

Just another Metabase user chiming in here. I don’t think this is really a Metabase related problem so not anything that should be logged as an issue here. I have previously successfully connected to MongoDB from Metabase running from within a Docker. container. But I haven’t got 

I suggest you to start by reading up on Docker networking and the currently  recommended ways because just a quick google on “[Docker run link](https://docs.docker.com/network/links/)” told me that what you tried at least is a deprecated method. 

If reading up on Docker networking you still can not get it working I’m happy to continue the discussion over on https://discourse.metabase.com from what you tried next after reading this. That place is a more appropriate place to ask for (community)  help.

(The above might sound unhelpful- but I’m really just trying to teach you to find the solution than spoonfeeding you solutions, hope you’re Ok with that)
