### ISSUE TITLE
Unable to create custom query

### ISSUE THREAD

**Issue by sturgill** [metabase/metabase#7463]
I am getting some weird React errors when trying to use the interface to create custom queries (screenshot attached below). I am hosting Metabase 0.28.6 on Beanstalk and connecting to a Redshift database. I even tried to resolve by giving Metabase credentials to a super user, but that did not work. I am able to successfully run native SQL queries; I just can't create questions via the interface.

This happens on both Chrome and Safari on a Mac.

![screen shot 2018-04-26 at 9 44 36 am](https://user-images.githubusercontent.com/1447882/39313334-61fa5aa2-4937-11e8-90e7-87d7931c3337.png)

**Comment by mazameli** [comment]
Hmm, strange. This is what an instance with a single Redshift DB connected and no sample dataset looks like locally for me on macOS + Chrome, though this is on version 0.29.0 (soon to be released):

![screen shot 2018-05-01 at 2 02 36 pm](https://user-images.githubusercontent.com/2223916/39493626-67513d1c-4d48-11e8-8fcd-c59ff6cd3ef3.png)

**Comment by sturgill** [comment]
I see that same view, the error comes when I try to click on a schema name. The schema will not expand and I am unable to select a table.

**Comment by mazameli** [comment]
Got it. Sorry about that, @sturgill; I didn't read your description carefully enough.

I was in fact able to reproduce this on master on Chrome:
- Set up an instance such that you only have one connected DB which contains schemas.
- Go to the query builder and try to select a schema, and you'll notice nothing happens when you click any schema.

This actually doesn't have anything to do with the Sample Dataset: as long as you have more than one connected database, the schema+table selection works fine.

JS errors:

![screen shot 2018-05-01 at 3 08 06 pm](https://user-images.githubusercontent.com/2223916/39496024-a6408a10-4d51-11e8-91ce-abd2230b025e.png)

**Comment by sturgill** [comment]
Glad you were able to reproduce, @mazameli. Unfortunately I'm not a React guy or I'd dig into the code...

My workaround for now is to keep the sample dataset enabled. I don't love it, but it works for the moment.
