### ISSUE TITLE
Set MB_DB_PASS via Docker secret

### ISSUE THREAD

**Issue by mallchin** [metabase/metabase#7464]
Currently MB_DB_PASS is specified via an environment variable.  It would be preferable to support reading the value from a file on disk like-so:

MB_DB_PASS_FILE=/var/run/metabase-database-password

We could then store the password as a Docker secret.

It would also be useful to specify the default admin password and, if defined, skip the first-user registration step; I appreciate this is more complex but it would be handy to be able to orchestrate the whole setup.

**Comment by flamber** [comment]
Hi @mallchin 
This is related to or possibly a duplicate of #4349

**Comment by gilnei-ferraz** [comment]
@mallchin 

try to manually add the export in /app/run_metabase.sh

export MB_DB_DBNAME=$(cat /run/secrets/mb_db_dbname)	
export MB_DB_USER=$(cat /run/secrets/mb_db_user)
export MB_DB_PASS=$(cat /run/secrets/mb_db_pass)

**Comment by paoliniluis** [comment]
Closing since we merged https://github.com/metabase/metabase/pull/14839

**Comment by cgutierrezpa** [comment]
@paoliniluis 

Sorry to bother you all with this, but I'm trying to follow the guidelines to [use Docker Secrets](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#use-docker-secrets-to-hide-the-sensitive-parameters) inside the docker-compose file, and Metabase is not able to properly get the user and password to connect to the Postgres DB. I have the exact same docker-compose configuration, but I get the following error:

`Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "/run/secrets/db_user"`

I tried alternating passing the `MB_DB_USER` as docker-compose secret and the `MB_DB_USER` by value, and viceversa. Nothing works. My guess is that `/run/secrets/db_user` as specified in the docs is not being resolved to the value stored in the secret but to the path string instead, and the env variables `MB_DB_USER` and `MB_DB_PASS` expect the actual value of the user and password, not a path to the file containing its values

Is anyone having the same issue? Ended up doing some weird workaround by overriding the metabase entrypoint and initializing the variables as someone suggested above (`export MB_DB_USER=$(cat /run/secrets/db_user)`) before exec'ing the metabase process, but would love to have a cleaner solution.

**Comment by paoliniluis** [comment]
@cgutierrezpa did you create the txt files in the same directory as the docker-compose.yml? pay special attention to the part of the compose file where the postgres container is configured with environment variables:
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: /run/secrets/db_password

and then those secrets are passed on the bottom of the file as
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt

also, please post these issues in Discourse as the issue is closed, thanks!
