### ISSUE TITLE
More realistic estimates on cache size for MySQL

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7479]
Metabase currently stores query results for caching purposes using a blob column. We currently get a rough estimate for the size of the resultset before storing it and if it's too large, we don't store it in the query cache. The problem with the estimate is that it isn't connected to our realistic storage requirements. For MySQL this blob column has a max of 16 MB, for PostgreSQL, this is much higher.

We should change the query-cache estimation code to more closely reflect the reality of how that data is stored. Knowing data is too large would prevent issues like https://github.com/metabase/metabase/issues/7006.

**Comment by Roze** [comment]
The  maximum size for MySQL BLOB is only 64KB, for 16MB you need MEDIUMBLOB.

We hit the https://github.com/metabase/metabase/issues/7006 also but our workaround was rather than disabling the cache just alter the query_cache table to have LONGBLOB (a bit excessive but w/e).

Of course if you expect large resultsets you might need to tweak max_allowed_packet as with MySQL version <= 8.0.2 it's only 4MB so queries/fields larger than that will fail with "packet too large" error.

**Comment by joboyx** [comment]
This also happens to me with big queries resulting to multiple columns and thousands of rows.

Would be great to fix this. :)
Thumbs up for the main comment!

I'm running with:

- Metabase v0.29.1
- Oracle 12c

**Comment by MarkRx** [comment]
Can't use caching without this.

Even with better estimation unless it is 100% query caching can't really be used. I assume the serialization is streamed so the size cannot be known ahead of time. If this is the case, would it be sufficient to have a "cache N/A" state that gets set in the case that a cache save fails to save due to the size being too big? If set reads would always perform a cache miss. The N/A state could even become stale and retried over time (though in reality may not buy much unless the dataset shrinks due to deletions).

**Comment by fahernandez** [comment]
If anyone still has this problem, running this alter on metabase database fix the issue for us.

`ALTER TABLE query_cache MODIFY `results` MEDIUMBLOB NOT NULL COMMENT 'Cached, compressed results of running the query with the given hash.'; `

Thank you @Roze for the quick solution!

> The maximum size for MySQL BLOB is only 64KB, for 16MB you need MEDIUMBLOB.
> 
> We hit the #7006 also but our workaround was rather than disabling the cache just alter the query_cache table to have LONGBLOB (a bit excessive but w/e).
> 
> Also if you expect large resultsets you might need to tweak max_allowed_packet as with MySQL version <= 8.0.2 it's only 4MB so queries/fields larger than that will fail with "packet too large" error.

**Comment by MarkRx** [comment]
@fahernandez are you still seeing issues in 0.31?

**Comment by fahernandez** [comment]
> @fahernandez are you still seeing issues in 0.31?

I'm actually on v0.31.2 and I still seeing the issue.
