### ISSUE TITLE
can't work on low memory PC

### ISSUE THREAD

**Issue by imiskolee** [metabase/metabase#7539]
Hi,team:

i can't understand metabase why need more memory resource. the webpage can't work on low memory PC(2G ram).

render  a dashboard need 800M - 1.5G memory, its too big.

**Comment by salsakran** [comment]
Closing since we're working on overall memory consumption on an on-going basis, and this doesn't identify a specific problem.

Note that we're a fairly full featured analytics application vs a "web page" per se. While we're actively trying to reduce resource consumption, at some point all the things we offer need resources.
