### ISSUE TITLE
How do you create Docker release? 

### ISSUE THREAD

**Issue by collegeimprovements** [metabase/metabase#7550]
Hi Guys,
I cloned metabase repo and ran `docker build -t metabaser .` command.
The generate release is 1.59GB in size. How do you make 161MB release ?

**Comment by collegeimprovements** [comment]
I tried that, but it fails to build locally as it uses docker-hub references.

Side Question: How to restart metabase from docker? I need to change `metabase.jar` and need to restart it to apply changes. How can we do that ?

**Comment by ad-m** [comment]
@jornh , what do you think about use [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)?

**Comment by jornh** [comment]
@collegeimprovements I don’t see any references to Docker Hub in https://github.com/metabase/metabase/blob/master/bin/docker/Dockerfile. 

But you are right the `build_image.sh` helper script does, but: a) You don’t have to use that script in the first place. b) With the right combination of CLI options (as I remember, but you can verify) it performs a local source build instead of referencing released jars and the hub: https://github.com/metabase/metabase/blob/master/bin/docker/build_image.sh#L52-L56

- - - -

@ad-m I think multi-stage builds are cool. And the root folder `Dockerfile` could possibly be made into one. Then @collegeimprovements probably wouldn’t have had reason to raise this issue in the first place 😄. But I guess multi-stage builds weren’t around when the existing solution was built.

Potentially the two Dockerfiles could even be unified and avoid some duplication. I guess it’s not high on the agenda for the core developers, but they probably wouldn’t mind a PR. Specially not if it got rid of a bit of code duplication.

**Comment by collegeimprovements** [comment]
so we are not supposed to run `sh bin/docker/build_image.sh` ? 
should we build image via`cd bin/docker && docker build -t metabase:custom .`' ?

**Comment by jornh** [comment]
> should we build image via `cd bin/docker && docker build -t metabase:custom .` ?

I believe you can if you copy your custom `metabase.jar` to `bin/docker` first ... does that resolve the question for you?

What I tried to say above was that probably it's simply not documented because it's "just convenient tooling" the core developers built for themselves (But hey, I'm just another user like you - so your guess could be as good as mine)

**Comment by tlrobinson** [comment]
FYI I have a PR to replace the root `Dockerfile` with a multistage one here #7380 

Basically `./Dockerfile` is just for building locally (though I don't think we use it often), and `./bin/docker/Dockerfile` is just for deploying (it builds a minimal image from a previously built jar, without all the source code and build tools).

Multistage builds are precisely to avoid this situation. We should switch to using them.

There's still a bit of work to be done but you all could help by trying out that PR and letting me know how it works.

**Comment by salsakran** [comment]
./Dockerfile is what generates the `metabase-head` https://hub.docker.com/r/metabase/metabase-head/ 

`bin/docker/build_image.sh` is what we use to build releases.  Note however that this is all best considered an "internal API" and we can and will change this up.

**Comment by jornh** [comment]
@tlrobinson:
> FYI I have a PR to replace the root Dockerfile with a multistage one here #7380

Haha, I just *knew* you already had this lying around (no, seriously I didn't).

Agree with that `./Dockerfile` is probably not that much used, and important, for serious development (by the core team). I think it's still quite useful though for others who want to quickly have a *consistent* way to bring in dependencies for a build, even without "polluting" their existing environment.

Will take #7380 for a spin and report back whenever I get enough free cycles

@salsakran, fully agree! You guys being automated and agile and free to move quickly has more value that drive-by spectators has a super easy well documented on boarding.

**Comment by mbvictoria** [comment]
Closing - solved
