### ISSUE TITLE
No loading indicator on admin pages

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7572]
Just now I was using our internal instance and headed to `/admin/databases` and there was a one-or-two second delay where it was just a blank page with no DBs. Then all of the sudden the whole list popped up at once.

We should get a spinner or something going for the possible situations where the load isn't instantaneous

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
Ideally maybe we could just have a generic way to give any page a loading spinner? In my old mobile dev days I just [monkey-patched `UIView`](https://github.com/camsaul/bird-kit-x/blob/master/XPlatform/Categories/UIView%2BX.m#L255) to give it a `showsLoadingSpinner` property and all you had to do was set flip it like a switch
```objective-c
self.view.showsLoadingSpinner = YES; 
```

Not sure how to do this in React/Redux but something like this could definitely make our lives easy

**Comment by camsaul** [comment]
So I ran into this again on `/admin/people`. Not sure how many other places it applies to but we should get loading indicators on all of the admin pages if possible :D

**Comment by andrewluetgers** [comment]
Not exactly this issue but related is I don't see loading indicator when filtering data or initiating a download. Both of which end users then spam the ui causing more queries to take place.

In our apps we dim the content that is about to be replaced rather than popping up an annoying spinner so that the user gets an immediate ui response. When the new data comes in it goes back to full contrast.

For our downloads we use a trick where a random query parameter is passed in with the download request which is passed back int the response as a cookie value. This way we can indicate a download is working with a disabled download button, load the download in a hidden iframe, ping the frames window object for the cookie's presence and when it appears re-enable the button.

**Comment by flamber** [comment]
Not sure when this was added, but on 0.35.3 it shows a loading indicator on admin pages.
Related #10566 - download indicator
