### ISSUE TITLE
Proposal: Ability to restrict category filters to a single selection

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7605]
Multi-selection is awesome. However, there are some cases where a card / dashboard only makes sense when a single value is selected. In some cases selecting multiple values results in nonsense results that is confusing for the user.

This proposal is to add a checkbox when configuring filters along the lines of "allow multiple selections" that defaults to true. Users would be able to uncheck the box when configuring the filter to prevent multi-select thereby only allowing at most one selection.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
Can you give a concrete example of where multiple selections don't make sense?

In general, we not really going to be putting knobs like this all over the product, and we'd rather be able to mark something like this upstream via either metadata or just restricted filter widget selection.

**Comment by MarkRx** [comment]
The use case is with line graphs that have unrelated x-axis values.

![image](https://user-images.githubusercontent.com/17504314/39878107-8b3dabd0-5445-11e8-9086-35b1785bbe5b.png)
This graph charts a quality metric over a sequence (Jenkins job build number). It also has a little green / red pass fail marker at the bottom.

When attempting to use multiple jobs the graph will aggregate values that have the same x value. It does not make sense to view multiple items in this representation of the data because the x values of each series are unrelated. 

![image](https://user-images.githubusercontent.com/17504314/39878656-e33418dc-5446-11e8-9beb-c685a6b3c6a6.png)

As seen above y values are aggregated. Even if they were averaged so that the percentage did not go above 100% the graph itself would not make sense as there is no relation between the y values of two series that have the same x value.

**Comment by leorochael** [comment]
My usecase for single selection is when I write a raw query in SQL that does a (potentially limited) cartesian product with a generated series.

For instance, I might join a generated series of dates (say, the first day of every month) with the state of my data filtering out things that only happened after each date.

This would be a way of doing time travel on my data so that I can see what the state looked like in the past.

Such a result can only be filtered meaningfully by at most one item from the column containing the generated series of dates, as selecting more than one entry in the filter would produce nonsensical data. Unless the data was also grouped by the same column containing the generated date.

Similarly, if I write a query where I select only values below a certain (categorical but sorted) variable (think "stars" as in 5-star hotels), selecting more than one of these categories would produce overlapping values.

**Comment by leorochael** [comment]
I'd be ok if the single-selection case would only be possible in "raw-sql" queries (and in dashboards that included them).

**Comment by lindsay-stevens** [comment]
I'm interested in this because SQL questions are useful for when an analyst needs to write a query that is too complex for the QB and/or business users to write. 

As part of report delivery I want to try and ensure as far as possible that the filter/grouping options exposed via widgets are going to make it hard to break the report or give misleading results. 

An example of that is using a field filter to make sure an input is from a valid set of values, and the report requirements may call for only one input value for the report to make sense, such as:

- filtering on an "as-of" audit date - only makes sense to show a historical snapshot at a single time
- a set of statistics about a selected user - the request is specifically for a single-user stats per report
- a widget accepting 'day' / 'month' / 'year' for grouping - e.g. can't group by both day and month

The following is an example using the Sample Database, showing a pattern that can be used to work around this. It's not ideal because the error state is either "No results!", or using the table viz to show a message. 

If I could configure the widget as single-select only instead, then Metabase could clearly inform the user of the exact problem - or prevent it completely by only accepting one value.

```sql
/* Field-filter in CTE because these are only injected to a query once.
   Weird CTE syntax because this is an H2 sample database
   (otherwise don't need colname in WITH, or UNION...SELECT parts).
*/
WITH filter_cte(id) AS (
  SELECT
    id
  FROM people
  /* This variable is a field-filter connected to people.name */
  WHERE {{name}}
  UNION ALL
  SELECT NULL WHERE FALSE
)
SELECT
  name, 
  city
FROM people
/* Join to use filter for intended case (single-selection). */
INNER JOIN filter_cte
  ON filter_cte.id = people.id
/* Returns no rows if more than one person's name is selected. */
WHERE (
  SELECT 1 = count(*)
  FROM filter_cte
)
/* If possible, append a set of error message(s) of the same row type.
UNION ALL
SELECT
  'Please choose only one name!',
  NULL
*/
```

**Comment by vvaezian** [comment]
My use-case is: I want to give users the option to determine the level of granularity of data being shown on the graph (Yearly, Monthly, ...). For this I need to enforce only one selection of these values. Basically something similar to the radio button in HTML.

**Comment by winnephew** [comment]
There are many uses cases for this. It would also be useful to be able to define category filters not just for field filters but separately as well. (these could be used in native sql queries, for example for temporal aggregation as in vvaezian's example)

**Comment by cyarbro** [comment]
Any progress on this? Using v0.32.5 and still have a typeahead textbox rather than a dropdown for field filter, less than 300 results

**Comment by EBoisseauSierra** [comment]
My use-case is: I create a financial dashboards for a British holding that has subsidiaries across the globe (and, thus, using multiple currencies). I create one dashboard per subsidiary.

In my filter, I want to select the currency to use in the dashboards: either local currency, or GBP. But definitively not both.

**Comment by vanjavidenovic** [comment]
Would love to have this too, use case is for monitoring different metric between different buildings, makes it much simpler to select a single different filter rather than the resulting chart being cummulative results

**Comment by niparis** [comment]
Our use case : Show the marketshare of competing products in a country.

And have a filter to select in which country to show the marketshare.

A singe select dropdown prevents the user from mistakenly selecting 2 or more countries.

(it's like validation)

**Comment by emilythacher** [comment]
> 
> 
> My use-case is: I create a financial dashboards for a British holding that has subsidiaries across the globe (and, thus, using multiple currencies). I create one dashboard per subsidiary.
> 
> In my filter, I want to select the currency to use in the dashboards: either local currency, or GBP. But definitively not both.

Similar use case -- we make sales across multiple countries, and in various cases a single column in the data will have multiple currencies. We want to show the same information by country, but not allow users to "total" across countries that actually just adds different currencies directly. We have some dashboards in superset that meet this need, and I would like to migrate them to Metabase with our other visualizations.

**Comment by juliencohensolal** [comment]
Could this feature possibly get assigned a higher priority? I see 43 upvotes as of today, it seems like it would really help in a ton of use cases.

**Comment by rhartiunov** [comment]
My use case: I have a filter by date periods - last day, last week, last month, etc. It's obvious that multiselect here has almost no sense. I can hardly imagine a usefulness of filter like 'last year or last day'

**Comment by behnam-io** [comment]
My use case is to make users able to choose the currency for showing them amounts, Without single-select, it won't show users any logical number (i.e. will mix Euros and Dollars)

**Comment by devyetii** [comment]
Our use case : Admins should be able to specialize the dashboard to a just a single "Campaign" chosen from the dropdown menu, where choosing multiple campaigns - even if intentionally - doesn't make sense for the logic of the dashboard and would rune its UI.

**Comment by bruno-sa** [comment]
My current use case: We have a dashboard that can aggregate values in a daily/weekly/monthly basis. I've created a set of union selects that have the results by different granularity with a dummy column ("day", "week", "month"). We want to give the ability to the end user to navigate through those options using a filter by that dummy column.

**Comment by pmadlewski** [comment]
Our use case: dashboard with the ability to change data frequency between weekly and monthly. Currently requires some hacking to ensure we do not aggregate duplicate data together when both are selected. Toggle for this feature is a must have in drop down filter settings, available in every BI tool I ever worked with.

**Comment by paoliniluis** [comment]
This feature is coming in Dashboards in 45
