### ISSUE TITLE
Cannot connect to TiDB

### ISSUE THREAD

**Issue by on99** [metabase/metabase#7661]
### Bugs

**No matching clause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.**

- Your browser and the version: Firefox Quantum 60.0
- Your operating system: OS X 10.13.4
- Your databases: TiDB (MySQL Protocol compatible)
- Metabase version: v0.29.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

```sh
git clone https://github.com/pingcap/tidb-docker-compose.git
cd tidb-docker-compose && docker-compose up -d
docker run -p 9978:3000 -v ~/.metabase:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" -e "JAVA_TIMEZONE=Hongkong" --name metabase metabase/metabase:v0.29.3
```

Open metabase in browser to add a new database: http://localhost:9978/admin/databases/create

Select **MySQL** Database Type
Name: tidb
Host: 127.0.0.1
Port: 4000
Database Name: test
Database Username: root

Click *Save* you will see the error.

Thank you!

**Comment by tlrobinson** [comment]
I think this is a problem with your Docker configuration rather than Metabase. I was able to spin up a TiBD cluster using `tidb-docker-compose` and connect to it from Metabase running on my machine, both inside and outside a Docker.

You need to connect the Metabase container to the TiDB container's network. You can do that when creating the container with the `--network tidbdockercompose_default` flag, or afterwards by running `docker network connect tidbdockercompose_default metabase`. Then use `tidb` as the host and `4000` as the port when adding the database in Metabase.

**Comment by vDMG** [comment]
TiDB is actually not compatible with metabase as backend storage because TiDB does not support the operation of adding multi-schema change in one statement (follow this issue to track tidb support https://github.com/pingcap/tidb/issues/14766).
