### ISSUE TITLE
metabase drill through

### ISSUE THREAD

**Issue by SaraYassen** [metabase/metabase#7672]
I need drill through tutorial (all full steps)
when I click on bar, it goes to new question, I want data changing  in another card

**Comment by jornh** [comment]
Hi

Questions regarding usage are in general better asked on https://discourse.metabase.com. 

Anyway since you asked, see [this cross filter related enhancement request](http://discourse.metabase.com/t/cross-filtering/3466/3?u=jornh) on the forum, specifically:

> Metabase *does* have [filtering on dashboards](https://metabase.com/docs/latest/users-guide/08-dashboard-filters.html)  — but currently in a form where you’d have to pick your filter criteria in the drop downs — you can’t do it directly on the visualizations as you show above. 

Since this issue is now here I think it could as well just be kept as an enhancement request. I hope the above gives sufficient context about what's requested.

**Comment by salsakran** [comment]
As @jornh mentioned, requests for tutorials are outside the scope of what this issue tracker is used for.
