### ISSUE TITLE
Limit Access to Dashboard Creation

### ISSUE THREAD

**Issue by collegeimprovements** [metabase/metabase#7757]
Is it possible to provide Dashboard-Creation functionality just to Admins ? 
In our company, we have around 1000 users and many users create dashboards just out of curiosity.
What's a good way to tackle this issue ?

**Comment by lindsay-stevens** [comment]
If most users are just viewing questions and dashboards created by a smaller group of analysts, then embedding those questions and dashboards in another app is probably the way to go.

If it's important that everyone can still do other things like make own one-off questions, setup pulses or alerts for existing questions, etc., in the absence of a feature for disabling dashboard creation, you could initially train / advise users to avoid creating dashboards, and then enforce it with a small auto-delete cron job:

- fetch all dashboards `GET /api/dashboard/f=all`, each have `id` and `creator_id` props
- fetch all users `GET /api/user/`, each have `id` and `is_superuser` props
- filter retrieved user data to get `id` where `is_superuser` is `false`
- filter retrieved dashboard data to get `id` where the `creator_id` is one of the above non-admins
- delete these non-admin dashboards `DELETE /api/dashboard/:id`
  - optionally, use the users `email` prop to remind affected users to stop creating dashboards
  - optionally, use `PUT /api/dashboard/:id` to set `archived` to `true` instead of deleting

If you haven't worked with the Metabase API before, note that there is non-disable-able login throttling so you need to keep and re-use your auth token for between 15 mins and whatever `max_session_age` is set to (more of a dev issue really).

**Comment by mazameli** [comment]
@collegeimprovements We're making a bunch of changes to the way dashboards and collections work in version 0.30, and I think these changes will solve many of what I imagine are your underlying problems. Namely:

- Dashboards will no longer be listed on their own page. They'll be saved in collections, just like questions are. (The same goes for Pulses, too.)
- Users will only be allowed to save dashboards in collections for which they have Curate access.
- The top level of your collections "folder structure" will be able to have permissions set on it, allowing you to grant some user groups only View access to it, preventing them from saving random explorations in such an important place.
- Collections will be able to have sub-collections, giving you the ability to create better organizational hierarchy and structure.
- We're almost positive we'll also be including personal private collections, which would give your users a place to put the dashboards they're creating "just out of curiosity."

**Comment by mazameli** [comment]
Also, @collegeimprovements — I'd love to hear more about how you and your thousand users are using Metabase, and I'd be happy to show you a preview of the changes I mentioned that will be in version 0.30. If you'd be willing to have a call with me, can you [email me](mailto:maz@metabase.com)?
