### ISSUE TITLE
export API times out for csv of card results

### ISSUE THREAD

**Issue by RebekahHsieh** [metabase/metabase#7803]
Export of CSV for a complex query will time out resulting in the message 
"This Page isn't working. MB took too long to respond. HTTP ERROR 504"

The query does take a little bit of time to load in a card or dashboard. However, regardless of if the results show, export does not necessarily work (every once in a while, if i narrow the parameters of the query, it will successfully export).

What are the restrictions on time-out for view vs export?

- browser and the version: Chrome 66.0.3359.181
- operating system: macOS Sierra
- databases: redshift
- Metabase version: v. 0.29.0

**Comment by fredv** [comment]
Is the timeout configurable by any chance? I see the benefit for stability and availability but the difference in query editor / result interface and export is really hindering doing complex stuff (and using the results in other workflows and tools).

**Comment by flamber** [comment]
This is most likely already fixed by #11832, which was included in 0.35.0, so closing this.
There's a lot of variables to define some timeout, but it shouldn't be needed:
https://github.com/metabase/metabase/blob/db9f36ac2b4a7231a4bd81a2927a007fd3230c6e/docs/operations-guide/environment-variables.md
