### ISSUE TITLE
Problem pasting a password into the login page

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#788]
Just got a report that users are unable to paste their password on the login screen.  This is specifically happening on mobile and the password is being copied from a password manager app like 1Password into the login page, which is failing.

We should verify this against mobile and non-mobile browsers.

**Comment by tlrobinson** [comment]
For future reference, this was due to a bug in Chrome for iOS which breaks the ability to completely focus/paste into input elements while animating the margin property (possibly other properties) of an element on the page, but not necessarily the input element itself: https://jsfiddle.net/tlrobinson/vy9w59ok/
