### ISSUE TITLE
Connection To MySQL RDS: Timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by mobedi** [metabase/metabase#7932]
My Metabase app is up and running on Beanstalk and I was about to add my first Database. For this, I have created a MySQL database on RDS to which I have access to via MySQL Workbench and the database is publicly accessible with a username and password.

When I try to add this database to Metabase I get the following error:

> Timed out after 5000 milliseconds.

This could either be a Metabase timeout or a timeout on the database side. Has anyone faced a similar problem? If you know how to change the timeout value for the RDS please let me also know. I tried creating a parameter group that overwrites the timeout, but I don’t know how to tell Metabase which parameter group to use.

**Comment by salsakran** [comment]
Hello @mobedi  -

What you're describing is a problem in connecting to your data warehouse. We can't offer any help because it's dependent on your network/vpc/security group configuration. 
Please try the steps we recommend in our troubleshooting guide (https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html), and if you have issues  ask on our discussion forum. The issue tracker is not a place where we offer support.

**Comment by bogdanr** [comment]
I also have this issue even though I can connect just fine to the tunnel from the metabase machine.

**Comment by Siddarth434** [comment]
I have the same problem, any solution?

**Comment by karthiksasi** [comment]
I had the same problem, while adding remote Database server to Metabase.

I got it fixed by opening firewall between the DB servers & Metabase Server on the specific port number I am using.
