### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by gordon-matt** [metabase/metabase#7967]
I have just installed the Java SDK 10.1 and then started up the **metabase.jar** with the following

```
java -jar metabase.jar
```

I have tried to add an MSSQL database, but keep getting the following error:
**java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter**

What's the problem here? I don't know much about Java. Am I needing to install something or configure something? Or is this a bug?

**Comment by senior** [comment]
You need to include additional flags to launch Metabase with Java 9+ due to changes in the Java module system. If you are using JDK 8, you do not need the flags and a command like the one you have above will work fine.

 We don't have JDK 10 instructions and I have not tried running Metabase on JDK 10 but the JDK 9 instructions should help you get it working https://metabase.com/docs/latest/operations-guide/start.html#java-versions. If that doesn't work and there are JDK 10 specific issues, please reopen this with more info.

**Comment by camsaul** [comment]
@senior I'm using 10 and it works the same as 9

**Comment by gordon-matt** [comment]
@camsaul I already recently tried using the same commands as 9 in 10 and it had the same error. I eventually uninstalled 10 and replaced it with 8... now it's fine.

**Comment by camsaul** [comment]
@gordon-matt what version of Metabase are you using?
