### ISSUE TITLE
Emails not sending

### ISSUE THREAD

**Issue by ryantipple** [metabase/metabase#7972]
Have setup email correctly however getting an error message when sending the test email.

ERROR MESSAGE: "Sorry something went wrong, please try again"

Ive tried 3 different email servers, and get the same issue.

**Comment by joshualawson** [comment]
This issue was due to the HOSTNAME not being set correctly.

AWS sets the Hostname to the local ip which is not a FQDN which causes Gmail to automatically deny access to the SMTP servers.

Might be worth adding this to the e-mail documentation somewhere as I would presume it to be the same for most of the Email issues I found reported.

This issue can be closed

**Comment by salsakran** [comment]
thanks for the update! glad to hear it worked. updated our docs in #7984
