### ISSUE TITLE
Limited feedback on permissions graph not being consistent

### ISSUE THREAD

**Issue by whatnick** [metabase/metabase#7996]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Firefox 60.0.2
- Your operating system: Linux Ubuntu 16.04
- Your databases: SQL Server
- Metabase version: 0.29
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

Permissions changes are silently not being persisted possibly due to broken graph. Is metabase philosophy allow all by default and restrict by groups or the reverse i.e. deny all and gradually allow ?

Being able to understand how the permissions graph I am using is broken would be great.

![image](https://user-images.githubusercontent.com/491396/42407626-a0d489a4-81c8-11e8-8f37-7125d45857cc.png)

## Log 

```
:error [(named {:groups {5 {(not ("Integer greater than zero" -1337)) invalid-key}}} new-graph)],
 :message "Input to update-graph! does not match schema: \n\n\t   [(named {:groups {5 {(not (\"Integer greater than zero\" -1337)) invalid-key}}} new-graph)]  \n\n",
 :stacktrace
 ["models.permissions$fn__22003$update_graph_BANG___22012.invoke(permissions.clj:492)"
  "api.permissions$fn__48821$fn__48823.invoke(permissions.clj:74)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.permissions$fn__48821.invokeStatic(permissions.clj:62)"
  "api.permissions$fn__48821.invoke(permissions.clj:62)"
  "middleware$enforce_authentication$fn__38606.invoke(middleware.clj:118)"
  "api.routes$fn__49711.invokeStatic(routes.clj:80)"
  "api.routes$fn__49711.invoke(routes.clj:80)"
  "routes$fn__49772$fn__49773.doInvoke(routes.clj:108)"
  "routes$fn__49772.invokeStatic(routes.clj:103)"
  "routes$fn__49772.invoke(routes.clj:103)"
  "middleware$log_api_call$fn__38705$fn__38707.invoke(middleware.clj:349)"
  "middleware$log_api_call$fn__38705.invoke(middleware.clj:348)"
  "middleware$add_security_headers$fn__38655.invoke(middleware.clj:251)"
  "core$wrap_streamed_json_response$fn__55123.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__38610.invoke(middleware.clj:139)"
  "middleware$maybe_set_site_url$fn__38659.invoke(middleware.clj:275)"]}

```

**Comment by camsaul** [comment]
`-1337` represents the virtual "saved questions" and is not currently something you can set permissions for. (#5610 is open to consider allowing this.) The API endpoint for fetching the permissions graph in fact explictly checks that the virtual DB `-1337` isn't returned (via schema validation). 

It looks like when trying to update the graph, the virtual DB is getting specified somehow, which is similarly disallowed. I have no idea how it could be getting inserted into the graph but my guess is something weird must be happening with the selectors when the graph is fetched, adding the virtual ID into the graph because it's present in the store. @tlrobinson does that sound right?

We shouldn't be doing any transformations like adding DBs IDs into the response for the graph fetching endpoint

**Comment by flamber** [comment]
Closing, since I have never seen this reported after "Saved Questions" (-1337) was hidden in 0.33.1 by #10692
