### ISSUE TITLE
Even private schemas remain visible to all users

### ISSUE THREAD

**Issue by joaoferrao** [metabase/metabase#8045]
### Bugs
Database has 10 schemas. Both the DATABASE user (set up in the connection) as well as the Metabase User ONLY have access to one schema. Even so, when we "explore all data" (lowest positioned button right after the login page) and click on the name of the database connection, they see a collection (or folder like icons/menus) for each of the schemas. Clicking on each of them gives the user the list of each of the table names....

Example of one of the icons they see (they see 1 for each of the schemas, even if without access)
![image](https://user-images.githubusercontent.com/28150182/42649836-a476430c-8602-11e8-9e4e-cc9e68593939.png)

- Your browser and the version: 67.0.3396.99
- Your operating system: OS X 10
- Your databases: Postgres
- Metabase version: 0.30.0 snapshot
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres

Doesn't seem as intended behaviour, hence opening as a bug/issue.
The user should only see the schemas they have access to to protect information (even if it's only the title of the schema).

**Comment by mazameli** [comment]
I was able to reproduce this on master.

When going to the data browsing section for e.g. a Redshift DB, a user who has no access to any schemas except a handful will see *all* schemas and their contents listed:

<img width="1160" alt="screen shot 2018-07-22 at 11 32 12 am" src="https://user-images.githubusercontent.com/2223916/43047280-e94e20a6-8da2-11e8-83f2-fff7404cee5a.png">

However, clicking on a table for which they don't have access will not show the rows in the table; it'll give a permissions error:

<img width="1177" alt="screen shot 2018-07-22 at 11 33 15 am" src="https://user-images.githubusercontent.com/2223916/43047287-0a15c5dc-8da3-11e8-9ee9-c3b89e00e247.png">

Because the existence of the tables or schemas themselves can be sensitive, I'm going to mark this as a P2.

**Comment by lindsay-stevens** [comment]
@mazameli maybe a "Multi-schema" issue label would be helpful? Similar requirements for specifying which schemas/tables to sync are in: #2086, #2591, #5500, #6622, #6833, #8083. To try and help resolve this, I've summarised some relevant implementation details, a suggested approach, and my use case for this below.

## Implementation Details

- The JDBC driver for postgres doesn't have a [connection setting](https://jdbc.postgresql.org/documentation/head/connect.html) to ignore schemas or tables
- The generic-sql driver uses the `getTables` driver method to [fetch table metadata](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql.clj#L294)
- This returns all database metadata since the postgres metadata catalogs aren't permission controlled at all, so schema/table/column filtering needs to happen in the Metabase code base.
- The `getTables` method [accepts a schema name filter but doesn't report permissions](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html?is-external=true#getTables-java.lang.String-java.lang.String-java.lang.String-java.lang.String:A-)
- Driver method `getTablePrivileges` [provides privilege info for tables in a specified schema](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html?is-external=true#getTablePrivileges-java.lang.String-java.lang.String-java.lang.String-)
- Similarly, there is [`getColumns`](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html?is-external=true#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-) and [`getColumnPrivileges`](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html?is-external=true#getColumnPrivileges-java.lang.String-java.lang.String-java.lang.String-java.lang.String-)
- Each of these driver methods accepts a pattern of some sort to filter for schema/table/columns of interest, which [ends up in an SQL `LIKE` clause in the driver](https://github.com/pgjdbc/pgjdbc/blob/08631ccdabdb8ba6d52f398e2b0b46a9cf0cafbf/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L1295)
- [`LIKE`](https://www.postgresql.org/docs/current/static/functions-matching.html#FUNCTIONS-LIKE) is a simpler but less capable version of [regex](https://www.postgresql.org/docs/current/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP)
  - in particular `LIKE` can't do alternatives (such as `'abc' ~ '(b|d)'` which means if using these metadata methods to filter schemas/tables/columns, they'd all need to "look" the same e.g. start with the same string.
  - Also the driver doesn't have a `NOT LIKE` so perhaps it'd make more sense to fetch everything and filter in Metabase depending on what the user wanted
  - On a similar note the Metabase [query processor uses `LIKE`](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql/query_processor.clj#L231) for Question Builder / Native Widget filters but users could do a lot more if this substituted the regex operator instead

## Suggested Approach

- Users needing this sort of control grant/revoke permissions for the database user they connect as
- Metabase driver inspects the permissions it has in the database and limits introspection accordingly
- Admin users have an option to specify a filter passed through to the above metadata methods

In a [previous PR](https://github.com/metabase/metabase/pull/4466/files#diff-913dfe39cdb775e20c387845d1a4afa9R393) I proposed doing permission checks in a more generic way, by just trying to `count(*)` then catching the error, but on second thought that might be a problem for huge databases.

## My Use Case
In my use case it would be useful to have both permissions and filter strategies available (including a `NOT LIKE` for schema names). It's a bit complicated but what happens is each schema in the database is presented as a database in Metabase with the other schemas filtered out. So for QB users a "database" = "schema", but Native SQL users can still query across multiple schemas. For example:

- Metabase Database Connection "A"
  - Schema "A": user data which is visible in the QB for reporting
  - Schema "B": user data which is **not** visible in the QB for reporting, can be accessed via SQL, but does not require any metadata introspection, so should be ignored via filter
  - Schema "C": internal stuff not relevant to Metabase, ignored via permissions
- Metabase Database Connection "B"
  - Schema "A": user data which is **not** visible in the QB for reporting, can be accessed via SQL, but does not require any metadata introspection, so should be ignored via filter
  - Schema "B": user data which is visible in the QB for reporting
  - Schema "C": internal stuff not relevant to Metabase, ignored via permissions

**Comment by jlisyc** [comment]
Related
https://github.com/metabase/metabase/issues/8822

**Comment by TicklesTheBrain** [comment]
It seems to me that as @lindsay-stevens explained almost a year ago, this issue is NOT resolved and there is no viable workaround for it. Any clarification on from the dev team would be very helpful.

**Comment by edbizarro** [comment]
yeah, this bug is very annoying, especially if you have a datalake table (which is hidden in the admin) with more than 8B rows and some curious user click on the x-ray or feel the need to sql'd the goddamn thing

**Comment by camsaul** [comment]
@lindsay-stevens @TicklesTheBrain @edbizarro it sounds like the issue you're facing is actually this one:

https://github.com/metabase/metabase/issues/10139

**Comment by camsaul** [comment]
@lindsay-stevens @TicklesTheBrain @edbizarro when you say your user is configured to 

> do nothing for Schema B

What exactly do you mean by that? Does it still have [`USAGE` permissions](https://www.postgresql.org/docs/9.0/sql-grant.html) for the schema? If the user is not granted usage permissions for the schema, they can still see that the schema itself *exists* (see #10139), but they will not be able to see what's in that schema (e.g., tables).

If the user can't see tables in the schema, we can't sync them, and they won't show up as options in Metabase.

**Comment by TicklesTheBrain** [comment]
I have tried to clarify the problem in #10139 although my feeling is that it is the exact same issue as this one.
