### ISSUE TITLE
It should be possible to re-activate a deactivated user account

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#810]
Right now if someone leaves a company there are two options:
1. Delete their account. If they've previously created cards or dashboards this deletes them.
2. Manually lock their account by resetting their password (this assumes they used an email address under the companies control).

There should be a way to deactivate an account so that a persons content (and contribution to the company's institutional memory) persists. The field exists in the database schema (and I believe is respected), so we should add the ability to set this field in the admin UI.

**Comment by camsaul** [comment]
Is this still an issue?

**Comment by mazameli** [comment]
Yes, it's still an issue because this needs to be surfaced in the UI. I.e., there should be an option in the admin panel to "Deactivate" a user, where the behavior would be that the user would still be listed in the users table, but marked with a Deactivated status, and could subsequently be reactivated.
