### ISSUE TITLE
30.0rc dashboards only visible in admin mode

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#8168]
Hi, we just updated to 30.0-rc and encounter a couple of problems: 

**- Most importantly, Dashboards are not accessible for “all users” despite everyone having all permissions. Dashboards can only be viewed in Admin mode**

- “Edit permission” button when in “Our analytics” does not work
- “Edit permission” and “Edit this collection” buttons in collection do not work
- When coming from “https://mb.coffeecircle.com/” then ”Browse all items”, clicking from there on the collections does not lead anywhere
- Clicking on „Help“ from settings button in the upper left gets you to a kitten break

More general on usability:

- Finding Dashboards is not intuitive. Most of our users check their Dashboards on a regular or daily basis, hence these should be easy to find. There should be a visible button or basically a way to get to Dashboards wherever you are in Metabase - from my point of view. Right now you have to go through “Browse all items” unless dashboards are pinned to get there
- Seeing all data tables is not really useful or relevant for most users, but can be rather confusing. Most users need to easily find and see Dashboards and relevant questions (i.e. saved or favourite) 
- searching within collections would be useful 

Thanks!

Your browser and the version: Chrome Version 68.0.3440.75
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.3
Metabase hosting environment: Heroku

**Comment by mazameli** [comment]
Hi, Helen. Thanks for the feedback and for checking out the RC.

Thankfully, the bugs you mentioned have been fixed in master, like the behavior where the Edit Permissions button wasn't working. 

>  Most importantly, Dashboards are not accessible for “all users” despite everyone having all permissions. Dashboards can only be viewed in Admin mode.

Regarding the above, if you go to the "our analytics" collection and try clicking on "edit permissions," and then clicking refresh on your browser, that should be a workaround for the moment which should open up the modal to display the current permissions for that collection. If that works for you, can you verify that your user groups do in fact have View or Curate permission for this collection? Otherwise, if you move a dashboard to a different collection, can your users see it then? Can they see other items in the "our analytics" collection?

> Finding Dashboards is not intuitive.

Thanks for the feedback. Our hope is that by giving you the ability to create better organization with collections and sub-collections, and by pinning the most important dashboards in each collection, users would have a natural flow of going from the homepage, to clicking on a relevent top-level collection, to seeing the pinned dashboard (or questions) they're looking for. We've also found in our own use that the global search bar has been a fast way to jump to frequently-used items. Have you found search to be helpful in getting to your dashboards?

> Seeing all data tables is not really useful or relevant for most users, but can be rather confusing. Most users need to easily find and see Dashboards and relevant questions (i.e. saved or favourite)

Yeah, our vision for this is that as the homepage fills up with pinned company-wide dashboards, and with your collections, that those will be the things your users see and click on first, and that the data section will be there once they've gotten more familiar with your data or start getting curious to see what's there. Are you finding that this section is an active distraction or impediment for your users?

> searching within collections would be useful

How many items do your collections tend to have in them? Do you envision that you'll start to create sub-collections (i.e. subfolders) within some of your collections to make things a bit easier to find? Rather than having multiple ways to search, I would more likely see us doing something like adding a filter on the search results page to limit results to a specific collection(s).

**Comment by HelenMertes** [comment]
Thanks for the comprehensive answer!

The workaround you suggested worked, users can see dashboards again.

You are right, the search bar does help. Even though the page has to be refreshed if I want to run a second search and to get results (I guess it might be one of the bugs that you fix in 30.0 anyways).

I agree, pinning dashboads makes the homepage already more userfriendly.

We have quite a lot of questions in collections, but it actually still works with a normal search ("ctrl F").
I also like the idea of sub-collections though.

Thanks for the great work!

**Comment by mazameli** [comment]
Glad that worked for you. Because the bugs you're experiencing are fixed in master and in [the current release candidate](https://github.com/metabase/metabase/releases/tag/v0.30.0-rc), I'm going to go ahead and close this issue if that's alright with you. And thanks for the updated feedback!
