### ISSUE TITLE
org.postgresql.util.PSQLException:ERROR: column "tablename".gender (gender is column name in one of the tables) does not exist Position: 296

### ISSUE THREAD

**Issue by yashdave** [metabase/metabase#8179]
I have created a table view using custom sql in a .json configuration file and I see that view is created in db and when I use metabase option (From metabase UI) as "Custom", I see the table view name is populating from the list of drop down but when I select that table view it throws this error : 
- “org.postgresql.util.PSQLException: ERROR: column "tablename".gender (gender is column name in one of the tables) does not exist Position: 296
- When I open the same view by pasting the  sql in “Native query” option (select * from "tablename") then I see the desired output.
- If in the sql configuration, I keep the alias name for table.gender column as “gender” instead of “Gender” then it opens fine from Custom option.
Not able to figure out the issue.

**Bug Report Info
- Browser: Chrome
- Computer's OS is: OS X
- I'm running Metabase: On AWS (via Docker)
- Internally, Metabase is using this database: (This is the database
Metabase stores internal information like accounts and dashboards in,
not one you're running queries against. If you haven't done anything
special to configure this, Metabase defaults to using H2 when running
locally; if you're running Metabase on AWS or Heroku using the provided
scripts/instructions, you're most likely using Postgres.): Postgres
- My data is in a database of this type: MySQL (Data getting flattened from mysql to postgres using spting boot application and metabase is accessing this flattened postgres db)
- I'm using Metabase version: v0.29.3**

**Comment by jornh** [comment]
Hah, after reading through your description over and over I think I might have figured what the problem is. Postgres in particular is quite picky about upper/lowercase in naming tables, fields etc. In general the recommendation should be to go with lowercase for all of your schema or end up in trouble. Here a few StackOverflow/StackExhange posts on it:
- https://stackoverflow.com/questions/43111996/why-postgresql-does-not-like-uppercase-table-names
- https://dba.stackexchange.com/questions/191090/how-to-use-pgloader-to-transfer-sqlite-to-postgres-with-table-name-in-uppercase

Read through both answers and comments of these. Look at your Postgres schema and form your own opinion. As I don’t know the exact casing of your “gender” and if it was changed over time it *could* be that Metabase has cached a wrong/old value. So you can try clearing/re-sync under Admin > Databases.

Let us know how it goes 😊

**Comment by yashdave** [comment]
@jornh : Thanks you for your response. I cleared the metabase database and did the re-sync and it worked fine. It was probably because of the wrong cached value as you had assumed. Thanks much again.
