### ISSUE TITLE
filter widget cannot display in IE11

### ISSUE THREAD

**Issue by gnyuan** [metabase/metabase#8195]
### Bugs Report

- Your browser and the version: *IE11*
- Your operating system: *Win10*
- Your databases: *Sample dataset*
- Metabase version: *v0.30.0-rc*
- Metabase hosting environment: *Ubuntu 2014*
- Metabase internal database: *H2 (default)*

### Repeatable steps to reproduce the issue
1) make a query with filter widget to filter categories.
2) open this question in IE11
3) click the filter widget, and it cannot display, but when you zoom in or zoom out, the widget display.

### screenshot of abnormal widget:
![tmp](https://user-images.githubusercontent.com/6140657/43625877-dfb33fc6-9721-11e8-97ab-feee0ce0e77a.png)

Thanks
-------

**Comment by jlisyc** [comment]
Same to us.
Your browser and the version: IE11
Your operating system: Win10
Your databases: Sample dataset
Metabase version: v0.30.1 and 0.28.6 (tested)
Metabase hosting environment: Ubuntu 1604
Metabase internal database: postgres 9.5


That happends also with any filter widget (questions and dashboards) in IE11

**Comment by dervih** [comment]
Same to us.
Your browser and the version: IE11
Your operating system: Win7
Your databases: Sample dataset
Metabase version: v0.30.2
Metabase hosting environment: Win7
Metabase internal database: H2

Also noticed the problem when choosing columns for grouping in "New question" screen.
However sometimes it appears transparent and sometimes it doesn't appear at all
but in both cases zooming out (about 5 times) makes it appears normally and not-transparent.
Please find the screenshots attached below:

![metabase - transparent menu problem - not-transparent](https://user-images.githubusercontent.com/40885884/45308128-0a877d80-b521-11e8-9841-ef8f38b54b1c.jpg)
![metabase - transparent menu problem - transparent](https://user-images.githubusercontent.com/40885884/45308130-0b201400-b521-11e8-9361-0336019a0e0f.jpg)

**Comment by kdoh** [comment]
After a little bit of initial investigation I'm pretty positive we're running into some issues with CSSTransitionGroup for Popovers in IE 11. The popover does enter but doesn't seem to finish its enter transition (hence the ghosting we see in the screenshots)

I think the comments here about how zooming in / out gets stuff to show help reinforce this because I would imagine that the zoom causes a re-paint and that kicks the popovers into a fully entered state. Just to be sure I decided to remove CSSTransitionGroup entirely from the popover component to test the theory and things work just fine.

Currently looking into some possible solutions. So far to preview I think the options are either tweak some of the props to see if we can cause it to finish the transition or migrate off of CSSTransitionGroup in favor of something a little less finicky. Our popovers that use React Motion for transitions seem to behave nicely in IE 11 so part of me wonders if we should just standardize around that. Any opinions @tlrobinson?

**Comment by kdoh** [comment]
Ok so after a quick test, increasing the `POPOVER_TRANSITION_ENTER` and `POPOVER_TRANSITION_LEAVE` timeouts from `100` to `300` seems to get this to happen less often, although I did run into it again, but just far less frequently after clicking around a bunch. That leads me to believe the solution should either be a) just kill the transitions (they're kinda not that apparent in a lot of cases even in modern browsers where everything is "working" so they're of questionable value to me in their current state) b) replace the use of `CSSTransitionGroup` with `Motion`

**Comment by gnyuan** [comment]
It works.
Thank You!

**Comment by jornh** [comment]
@kdoh did you reopen this by accident again? Seems @gnyuan is a happy camper ...

**Comment by kdoh** [comment]
@jornh I think some github reference magic closed it and I had re-opened it since we hadn't merged the PR that fixes it, but now that it's in the `release-0.30.4` branch I feel comfortable closing it. Thanks for keeping such a good eye on things!

**Comment by jlisyc** [comment]
Related https://github.com/metabase/metabase/issues/9038
