### ISSUE TITLE
Feature request: Audit Logging

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#8234]
Would be nice to log the queries performed (and by which user) for security reviews.

**Comment by jornh** [comment]
First look on your activity feed (Homepage in 0.29.x or before and the 🔔 icon in 0.30 RC1 or later). The main feed are everyone's edit actions and it looks like the one on the side are *your* recent queries.

So let's look in your *backup* copy of Metabase. There it turns out that:

* For queries, the table `query_execution` is what you were after 
* and for edits The table `activity` looks like it's an added bonus.

I guess from there you can just join on user id and card id to other tables - and you basically have it. You can build it as some Metabase Questions and I think you're done (if you know how to setup **Friedlier Filds** with FK remapping) 🙂 

![](https://www.metabase.com/images/0.25-release/remapping.gif)
source: https://www.metabase.com/blog/Metabase-0.25/index.html

Not sure if you would just consider this a workaround or a good enough solution? That's basically up to you!

Oh, one final thought: This could all be packaged up in a separate local(?) Metabase instance just spun up running with H2 as it's own application base - and maybe pointing to your real environment as a Source DB?

**Comment by k2xl** [comment]
It doesn't seem like the query_execution table has the actual queries performed.

**Comment by jornh** [comment]
That’s why I mentioned you want to link to the `report_card` and I suppose there’s a dashboard relation as well.

 But you’re right, this still leaves out ad hoc queries. Not sure they are stored? If you need the full granular picture for security reviews I guess currently you’d either have to configure log4j to dump the full raw SQL on each query (Operations Guide briefly mentions custom log4j setups) or grab it from SQL server logs.

I think I saw someone posting either in another issue here or on the Discourse forum on what they ended doing related to monitoring Metabase. Try to search for the term “JMX”.

**Comment by k2xl** [comment]
thanks. having the adhoc queries log would be a helpful feature for compliance

**Comment by zachary95** [comment]
Seems to be part of the paid entreprise version already https://www.metabase.com/enterprise/

**Comment by salsakran** [comment]
@zachary95 

Yes it is. Closing this since it's been finished in the Enterprise edition.

**Comment by sethia** [comment]
But can we have a community edition feature for auditing? Do the developers have to build it from scratch here?  @salsakran @zachary95 
It's a useful feature for businesses who can't afford the enterprise license
