### ISSUE TITLE
Migrating from using the H2 database to MySQL 

### ISSUE THREAD

**Issue by zhangdoudou** [metabase/metabase#8246]
I want Migrating from using the H2 database to MySQL 
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase
export MB_DB_PORT=3306
export MB_DB_USER=...
export MB_DB_PASS=....
export MB_DB_HOST=47.10.****
java -jar metabase.jar load-from-h2 /path/to/metabase.db # do not include .mv.db or .h2.db suffix

When I perform these operations,will append the data in the default database is not migrated.
-------
 browser and the version: (Chrome 52.1)
operating system: (OS X 10)
databases: (MySQL)
Metabase version: ( 0.30)

-------
I don't know what caused this, please tell me how to operate

**Comment by MarcGJA** [comment]
Try again with just 
java -jar metabase.jar load-from-h2
at the end, get rid of everything from /path/to... onward

May want to post stuff like this to 
discourse.metabase.com 
because that forum is more likely to get a response to "get help" type issues.
They like to keep this forum for actionable proposals, bugs, etc.

**Comment by salsakran** [comment]
@zhangdoudou this is not the appropriate forum for questions like this. Please use the discussion forum.

**Comment by zhangdoudou** [comment]
Sorry,I see.I will correct it
