### ISSUE TITLE
Where are my dashboards?

### ISSUE THREAD

**Issue by sailxjx** [metabase/metabase#8306]
Hello I'v just upgraded metabase to 0.30 and this seemed to be an awesome version, but I couldn't find my dashboards on the navigation bar. Why did this happen?

New navigation bar
<img width="541" alt="screen shot 2018-08-14 at 09 25 22" src="https://user-images.githubusercontent.com/909853/44066712-621611c0-9fa4-11e8-91fe-2b685abd9e58.png">

Old navigation bar
<img width="787" alt="screen shot 2018-08-14 at 09 25 44" src="https://user-images.githubusercontent.com/909853/44066716-64419d16-9fa4-11e8-868a-60847d2e78e5.png">

**Comment by kdoh** [comment]
Hi there @sailxjx. In Metabase 0.30 dashboards, questions, and pulses now live inside of collections so you can organize items in Metabase how you'd like, rather than have to find things by what type of thing they are. Collections also allow you to set permissions so that only certain users can view certain items, which was previously only possible for questions. Since navigation is no longer centered around item types we've removed those links from the main nav in this version.

Because of this permissions system update, when upgrading from a previous version your existing dashboards are put in a "Migrated Dashboards" collection in your root collection (hit "Browse all items" from the home page and look for it on the left) so you can make sure no one will accidentally be able to see something that they shouldn’t and to give you a chance to decide where they should live and who should see what.

You can read more about these new features in our [release blog post](https://metabase.com/blog/0.30/) and learn more about the migration in our post about upgrading to 0.30 (https://metabase.com/blog/before-upgrading-to-0.30). Hope that helps!

**Comment by sailxjx** [comment]
I see, thanks @kdoh

**Comment by sailxjx** [comment]
@kdoh Yet another suggestion, collections are more useful than x-rays. I think put collections on the first screen, and put x-rays on the sidebar will be a better choice than current layout.

<img width="1632" alt="screen shot 2018-08-14 at 10 10 39" src="https://user-images.githubusercontent.com/909853/44068046-c84f9dca-9faa-11e8-937e-49f52a76499c.png">

**Comment by jornh** [comment]
@sailxjx that’s already covered in [this Discourse topic](http://discourse.metabase.com/t/disabling-hiding-x-ray-feature/3927?u=jornh) and 
https://github.com/metabase/metabase/issues/8255

**Comment by MarkRx** [comment]
I also find the menu bar harder to use - #7865

**Comment by jkowtko** [comment]
Where is the default post-login page that shows all of the Dashboards that are available?   Can any page do this anymore?

In our company we have developers preparing dashboards for managers ... so the manager is expecting to go to a default URL and seeing whatever dashboards we have made available for general consumption.   The manager can then view a dashboard and drill into Questions on that dashboard as they like.

By removing that initial post-login page showing all available dashboards, you have just eliminated the primary means of presenting data to the managers, and turned this into a "power-user only" tool.   

Was that the intent?

If not, then please do something like -- add a "public" collection that gets displayed as the default starting page for all users post-login ... where we can place all of our dashboards.   Then you can add a User personalization setting to choose their starting page.

Thanks.  John

**Comment by mazameli** [comment]
@jkowtko Because all dashboards are stored within collections now, when you upgraded to 0.30 they were moved into a "Migrated dashboards" collection (this is to make sure people aren't accidentally given access to dashboards they previously could not see upon upgrading). 

The intent was for you to then move them into collections based on the teams that should have permission to see them. If you want everyone in your company to be able to see a dashboard (or all of them), simply move those dashboards into the top-level "our analytics" collection; any dashboard that you **pin** in this collection will show up on the homepage for everyone. 

Additionally, if you organize your dashboards into collections and subcollections, you can pin important dashboards in them, so that e.g. when you go to the Marketing collection, the Marketing Stats dashboard will be front and center.
