### ISSUE TITLE
00:00 AM shown as 12:00 AM

### ISSUE THREAD

**Issue by cemsbr** [metabase/metabase#8318]
Using Firefox 61.0.1, Ubuntu 18.04, in "Ask a question", custom option:
1. Open a date filter (i.e.: Sample database, orders, created at);
1. Choose "After";
1. Click in "Add a time" at the bottom;
1. Click in "AM";
1. Type "00" in the hour input
1. Press "tab" or click in the minute input
1. Notice that "00" became "12"

Despite displaying "12", queries are done as intended: with "00".

**Comment by flamber** [comment]
Hi @cemsbr 
I'm unsure what you're reporting, because `00:00` on 24h equals `12:00 AM`, so it's correctly adjusted by the GUI to convert `00` hours to `12` hours.
And the parameter query filter, that is being sent, is in ISO 8601 format (`yyyy-MM-dd'T'HH:mm:ss`).
Metabase is still missing some i18n (internationalization), but it got better in version 0.31

**Comment by cemsbr** [comment]
Indeed, 00 in 24h is 12 AM.
