### ISSUE TITLE
JS and CSS not properly compressed/uglified

### ISSUE THREAD

**Issue by zhujunsan** [metabase/metabase#8327]
self hosting metabase using the docker image:
```
metabase/metabase      latest              3ea53572d627
```
which is also tagged as `v0.30.0`

The front-end assets are not compressed at all, all of them are in plain text together with all the comment.
For example the `vendor.bundle.js` alone is 7.18MB in size, 1.7MB after nginx's gzip. It's abnormally large for a web page asset.

I think it's a packing issue during the build but I'm unfamiliar with front-end building/packing staff, hope it can be fixed soon.

Thanks.

**Comment by lwqcz** [comment]
I've checked and my installation via *.jar file under Ubuntu environment is showing the same issue.

**Comment by cleydsonjr** [comment]
Hi guys, could you please share a possible fix date for this problem?

**Comment by dannyeuu** [comment]
We had to implement Cache and compression for CSS and JavaScript files at NGINX proxy level, cuz the download of this files cause the Metabase slow initial loading

**Comment by cleydsonjr** [comment]
@jornh I think there are tow different problems: 

1. The assets are not being transferred compressed by default (this can be easily fixed by a reverse proxy using nginx or apache http)
2. The CSS and JS files are not minified (there are spaces, line breaks, comments and long variable names). I think this can only be fixed during the build fase.

**Comment by jornh** [comment]
Yep! I think you’re right. At least it seems fixing either of the two problems would both work towards improving performance in the same area 😄 That’s probably what confused me. 

Anyway, agree they are technically different - not dupes - just related...

**Comment by tlrobinson** [comment]
The JavaScript bundles are being gzipped by Metabase's server, even without a reverse proxy such as nginx:

![screenshot 2018-10-30 11 41 00](https://user-images.githubusercontent.com/18193/47742027-f7e41780-dc38-11e8-9f67-20b0202f1403.png)

If you are seeing otherwise please give me more details about your deployment (Metabase version, Docker image vs JAR, hosting platform, browser, etc)

I'll take a look at why minification isn't being applied.

**Comment by tlrobinson** [comment]
Fixed minification here: #8834

We also accidentally disabled caching in a recent release, which I'll fix in #8834 as well.
