### ISSUE TITLE
binned longitude/latitude in editor

### ISSUE THREAD

**Issue by hsmith77** [metabase/metabase#8362]
I have a query in the SQL editor that uses several tables.
I return a sum of sales, grouped by lat and lon fields which I also return.
When I try to map it to grid I get 'Grid map requires binned longitude/latitude.'
I saw the post that indicated that to fix, go to the table and make sure the fields for lat and lon are marked as such.  
But because the table is in a different db than the other tables it isn't in the list in DataModel.
Their format in my SQL table is decimal(38,10)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by psrawke** [comment]
I am also facing a similar issue with the **Grid Map**.  `Grid map requires binned longitude/latitude.`

I am grouping the data by the integer values of latitude and longitude. I am able to plot the **Pin Map**, but **Grid Map** shows the `Grid map requires binned longitude/latitude.` error.

Can you share some **sample binned latitude-longitude (which is compatible with metabase)**, so that I can convert my latitude-longitude data into that format?

My query is something like this: 
```
SELECT  CAST(latitude AS INTEGER) latitude, CAST(longitude AS INTEGER) longitude, COUNT(*)
FROM location_table
GROUP BY CAST(latitude AS INTEGER), CAST(longitude AS INTEGER) 
LIMIT 20
```

The data returned by the Query is of the following form:

| latitude | longitude | count | 
| - | - | - |
| 22 | 69 | 1 |
| 13| 76| 6 |
| 21| 84| 3 |
| 20| 82| 1 |
| 17| 77| 1 |

**Comment by ohld** [comment]
I have a similar issue. I want to build a grid map but aggregating with step 0.002, not just 0.1. And right now I can choose aggregation bins only 0.1, 1, 10, 20 degrees. Can I do smaller?

**Comment by flamber** [comment]
@ohld Yes, https://github.com/metabase/metabase/issues/12257#issuecomment-663978078

**Comment by tcolinpa** [comment]
I'm facing this right now. Is there a way to bin lat/long on native queries?

**Comment by flamber** [comment]
@tcolinpa Not directly in SQL, but if you return all results and use that question as the base (Saved Question) of a new question:
https://www.metabase.com/docs/latest/users-guide/custom-questions.html#picking-your-starting-data
