### ISSUE TITLE
Option to change language

### ISSUE THREAD

**Issue by c990802** [metabase/metabase#8384]
With the new multilanguage version, the language is selected by metabase and not by the user. While this makes sense as a default option, I'd like to suggest to have the option for the user to change the language back to english.

The option to change the language might be there, but I have not found it.

In our case, we're based in Spain but inside the company we work in English as we have people from different nationalities. Right now, we're all seeing Metabase in Spanish.

My proposal is that the user can change on an individual basis his preferred language.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jornh** [comment]
You in fact already have that option available in your browser. You can specify your preference order for how it should pick languages among those offered from a server. So e.g. if you set your browser to en, en-UK, en-US, de-DE it would pick among a few English locales first, then fall back to German if the site offered that and finally, if none of these where offered from the server just show what the server offered as its top priority.

But, yes, I agree that may not be practical to either delegate that decision/having to manually configure it for each and every user each time they get a new computer. (Also because this is a global browser setting - and each persons preference might differ depending on the website). So I would even like to see this at a level where it’s not up to each user to set the language but a global admin setting: “We’re  part of an international company - we all do stuff in English” and Metabase then only offers that given language irrespective of each users browser settings.

Thoughts?

**Comment by c990802** [comment]
Thanks for your fast feedback.

In my opinion, this problem is widely solved in other websites, and following other sites patterns makes it easier to use by the user, making the product more usability friendly.

I think the best course of action is to use browser settings by default. That is, when the user has not changed the language preference. Then, if the user chooses to change the language, this can be stored somehow (i'd go for client side with localstorage/cookies).

Making it a global option for the admin is also an interesting choice, and might be the best choice for some companies. However, thinking about trying to satisfy the maximum amount of metabase users, the language selection at a user level is a better choice.

Hope my feedback helps.

**Comment by pawelkmpt** [comment]
Is there any progress in this topic?

**Comment by tlrobinson** [comment]
I like this idea but we haven't implemented it yet.

If you want to force the whole instance to a particular language you could hack it by overriding the `Accept-Language` header in your reverse proxy, if you use one.

**Comment by mustela** [comment]
Hey guys, any way we can force not to use the browser language (if Im not using a reverse proxy)? It's has been painful journey with translations so far. For instance, a few minutes ago, I had to delete a source and it didn't let me because the Spanish translation says you should type "ELIMINAR" when the code seems to be validating "DELETE". As you can see in the image.

![screenshot 2019-01-28 at 12 19 35](https://user-images.githubusercontent.com/325222/51833221-26849380-22f7-11e9-886e-566774e07a5f.jpg)


![screenshot 2019-01-28 at 12 20 39](https://user-images.githubusercontent.com/325222/51833222-26849380-22f7-11e9-9734-d27104a44d08.jpg)

Thanks

**Comment by gsouf** [comment]
Very unpracticale not to be able to change language in the ui, think of when you want to provide support in an other language then you have to change the language for the whole browser.  Most of webapps allow to choose a different of the browser's one

**Comment by mazameli** [comment]
Hey, folks. We're planning on doing this. Thanks for the feedback. Currently thinking it'll go into version 0.34.

@metabase/core-developers, here's the [current product doc](https://docs.google.com/document/d/1PdZFtq9DvUsjLv14x24HMiL2z05kam4DiRjvsU2J9p0/edit?usp=sharing).

**Comment by mazameli** [comment]
Hey, all. Here's what I'd like to propose to implement this feature. We'd love your feedback. The proposal is broken out into the different sections of the product that will need to change. 

## Overview

**At a very high level, this proposes that:**
- By default, only Admins can change the language for the whole instance.
- Admins can elect to allow individual users to pick a language that's different from the instance language from their account settings page.
- When a new installation of Metabase is created, the instance language should default to the installer's browser language, with an option to change it on the very first screen. This is the only situation where we should care about the browser's language setting anymore.

**Why this route?**
- For most organizations, it makes most sense for everyone to be working in the same language, but we understand this won't work for everyone, hence the ability to allow individual users to change their language settings.

## Specific changes

### Initial setup
1. The default language for the instance should be set to the initial admin user's browser's language setting. The rationale is that this is the strongest signal we have for what a smart default would be, and it's an opportunity to give a good first impression. The admin should also have the ability to change this setting on the very first screen of the setup flow in Metabase.

2. If their browser is set to a language not included in Metabase, the default should be English.

3. If the instance is upgraded to a version that no longer includes the selected instance language (i.e. if that language slips in its translations), the instance language should be set back to English.  

4. The `Change language` dropdown takes the place of the existing "Getting Started Guide" content in the footer of the first screen in the setup flow (and only on this screen). All subsequent steps in the setup flow should continue to have the Getting Started Guide link.

![welcome-screen](https://user-images.githubusercontent.com/2223916/66005010-0fd2a580-e45f-11e9-9d2a-e38cb62a4f39.png)

### Admin panel
1. Change the `Formatting` tab in /admin/settings to `Localization`, and move the `Language` setting from the `General` settings tab to the `Localization` tab, placed at the top. The page heading for the `Localization` tab should read `Localization Options`. 
2. Additionally, I think we should _remove_ the `Dates and Times`, `Number`, and `Currency` subheadings on the existing `Formatting` page, as they seem to be cluttering things up more than they help.
3. The Instance language setting should now change the language for the entire Metabase instance, i.e. including the UI. It should continue to affect the language for system emails, pulses, and alerts. The languages listed in the dropdown should ideally be presented as they would be in that language. E.g., `Español` instead of `Spanish`. 

![language_dropdown_user](https://user-images.githubusercontent.com/2223916/66009677-5977bc00-e470-11e9-8e55-809369dae3b6.png)

Here's how the microcopy for the setting should change:
	
`Instance language`
`The language that should be used for Metabase's UI, system emails, pulses, and alerts.`

4. There should be an additional new setting below that, allowing admins to optionally let users change their language settings. If users are allowed to change their language, their default language should be the instance's language.
	
`Users' language`
`You can set your users’ language to be the same as the instance, or configurable in their Account Settings. This will only affect what they see in the Metabase UI.`

This setting should be a dropdown with these options:
`Same as the instance language` (this is the default)
`Configurable`

![admin_panel_localization](https://user-images.githubusercontent.com/2223916/66004701-46f48700-e45e-11e9-8c8f-409c612e0767.png)

### User account settings
1. If the Admin Panel's `Users' language` setting is set to `Configurable`, then each user's Account Settings page should have a `Language` dropdown on the bottom of their `Profile` tab to select their preferred language.

2. If the instance is upgraded to a version that no longer includes the user's selected language, it should be set back to the instance's language setting.

![account_settings](https://user-images.githubusercontent.com/2223916/66009645-3d741a80-e470-11e9-910c-a35cb3cc7333.png)

**Comment by walterl** [comment]
How does a user's language (selected in _Account settings_) affect their experience? Will it only change the UI language, or will it also be used for pulses, alerts, embedding, etc.?

**Comment by c990802** [comment]
@mazameli The proposed implementation looks great. The only thing that seems a bit overfeatured is the fact that an organization can optionally enforce a language. U have strong signals of customers demanding this?

**Comment by salsakran** [comment]
I don't think we should have a language selection under the "let's get started". I think it should either be an explicit choice in the setup page or an interstitial.

Right now, there is a lot of simplicity and clarity to that first page, and I don't want to start adding knobs to it. We ask the user a bunch of questions in the following page, and this seems like a reasonable one to ask as a step.

I don't think showing that setup wizard in a native language is worth this muddying of the waters.

Conviction ~80%

**Comment by mazameli** [comment]
@salsakran yeah, I see where you're coming from. Here's how I think this could look as a discrete step in the setup flow:

![language_setting_in_setup_flow](https://user-images.githubusercontent.com/2223916/66349871-b3fc9680-e90e-11e9-8a78-6790ea0961b3.png)

Here's how that step could look once it's completed and collapsed, depending on the language that's chosen:

![language_set_to_english](https://user-images.githubusercontent.com/2223916/66349938-dbebfa00-e90e-11e9-928d-52f5c2123393.png)
![language_set_to_portuguese](https://user-images.githubusercontent.com/2223916/66349940-dbebfa00-e90e-11e9-9543-046d1c467c4e.png)

This change would mean we wouldn't need to look at the browser language settings at all.

In the future, we could also change this selection from just being "language," to being "locale," so that we could also set the global time, date, currency, and numeric formatting to match the locale.

(As a note, I changed the user language setting from a dropdown to a toggle. The dropdown was a holdover from an older exploration where I thought there might be more than two options. I think this simplifies it, so I've made that change up in the mock in the specs in my above comment.)

**Comment by salsakran** [comment]
@mazameli works for me

**Comment by kdoh** [comment]
A couple things I want to add to this as food for thought specific to the setup flow aspect of this.

- If we're properly detecting and setting a locale as I believe the original proposal intended, there won't really be much to do other than read the welcome text in your language and hit next on that screen. The change language CTA  would really just be there to provide an escape if things are reading (literally) wrong. 

- If we really do think we want it to be a discreet step, which I can see value in, I would want it to come before the user account creation step and only allow for language options, possibly presented as a list rather than a dropdown (think more like the OSX startup experience). One of our goals with setup is not necessarily to get every setting configured but to get the bare number of things going to help users decide if Metabase is for them. Things like the admin deciding whether to let other users pick their own language don't help serve that goal at this point and can be addressed later.

**Comment by mazameli** [comment]
> I would want it to come before the user account creation step and only allow for language options, possibly presented as a list rather than a dropdown (think more like the OSX startup experience).

I think this makes a lot of sense. That could look like this:

![setup_flow_first_step](https://user-images.githubusercontent.com/2223916/67344910-0a143100-f4ee-11e9-928f-86d78273ff9a.png)

![setup_flow_language_selected](https://user-images.githubusercontent.com/2223916/67344923-15675c80-f4ee-11e9-8aa8-cda2b3a59d68.png)

**Comment by sdspieg** [comment]
Any updates on this?

**Comment by mazameli** [comment]
@sdspieg We had marked this feature as a stretch goal for [version 0.34](https://github.com/metabase/metabase/releases/tag/v0.34.0) but weren't able to get to it. It will likely be on the short list of items we look at for version 0.35, but we haven't committed to a definite plan for that release quite yet.

**Comment by gutomarzagao** [comment]
I couldn't find it in version 0.35. You guys have an update on this? The translation is really misleading. Feels like Google Translator sometimes.

**Comment by flamber** [comment]
@gutomarzagao This has been given milestone 0.36 now - that's not always a guarantee it will make it for the targeted milestone, but we will try to.
You can help making the translations better: https://poeditor.com/join/project/ynjQmwSsGh

**Comment by mazameli** [comment]
Just a note for @metabase/core-developers — there was a bit of back and forth on the designs in the comments in this issue, so for the sake of clarity I'm going to open a separate issue with the final designs. Please disregard mockups in this issue.

**Comment by camsaul** [comment]
Notes from today's meeting:

- This issue seems like it's 90% frontend work and 10% backend work. 

- FE stuff:
  -  update the setup flow to add step to pick default language
    -  The default choice should be the browser language, falling back to English if it's not one we support.
  -  add an option in the "My Account" page to change User language.
  -  Add UI for the "default language" Setting (this should be pretty easy)
-  Backend stuff:
  -  Add a new "default language" Setting
      -  Setup API endpoint needs to set this value. Should validate it as well.
  -  Add a `language` column to User to record User's language Setting. Default = `NULL` which means use default language.
      -  Edit user API endpoint needs to be able to validate/set this value
  -  Need to rework how i18n works -- probably by removing the PuppetLabs i18n library entirely and using our new logic that relies on the "default language" Setting for `trs` and User `language` for `tru`
      -  Any log messages that happen *before* DB is initialized (i.e., before Settings are available) should probably just fall back to English

**Comment by camsaul** [comment]
Still need to make a few more changes

**Comment by mazameli** [comment]
Implemented by https://github.com/metabase/metabase/pull/12566. This will be included in the upcoming version 0.36!
