### ISSUE TITLE
webPackJsonP is not defined 0.29.3 

### ISSUE THREAD

**Issue by seventrust** [metabase/metabase#8388]
Hi Guys! 

I have a recent problem when lauching Metabase 0.29.3 as Docker App, the web console throws a error as Follows: 

![image](https://user-images.githubusercontent.com/1132539/44531560-76678a80-a6c7-11e8-8e8c-ed633b1876c3.png)

This occurs when open the website for metabase, is important to mention that Metabase is behind from a nginx reverse proxy hosting in Ubuntu Server AWS EC2

- Your browser and the version: 
Firefox  61.0.2 (64-bit) - Versión 68.0.3440.106 (Build oficial) (64 bits) - Microsoft Edge

- Your operating system: (
Windows 10 64bits

- Your databases: 
MySQL
- Metabase version:
 0.29.3

- Metabase hosting environment: 
Linux/Ubuntu Docker Image

**Comment by jornh** [comment]
Would be useful to know if you see the same behavior with version 0.30.1?

One thing is it's throwing this error, which of course ideally it shouldn't. Another is you don't mention how it affects the user experience. Does the page not load - or?

Also, just because you mention your environment involves running behind an Nginx reverse proxy - maybe http://discourse.metabase.com/t/metabase-0-30-rc-queries-timing-out-other-issues-aws-alb-http-2-related/4082 is relevant. Main point with that is people see problems when running with their reverse proxies in HTTP/2 mode. I realize your symptoms are different, it's just, it seems the details of the Nginx config could be important to know for diagnosing as well.

So, all in all 3 more questions to dig into...

**Comment by kdoh** [comment]
Hey there @seventrust. If its the issue I think it might be I believe this was fixed by #8140 (a dependency issue that was causing webpack transpile issues with that same error message in some browsers). If you're able to upgrade to 0.30.1 that fix is included and should hopefully get things going again.

**Comment by seventrust** [comment]
Hey Guys! sorry for the late response,  @jornh  you're right, it was a missing configuration for the nginx reverse proxy!!

**Comment by kdoh** [comment]
@seventrust I'm going to go ahead and close this since it sounds like things worked out. If I'm mistaken or if this comes back up I'll reopen it.

**Comment by ananth95** [comment]
> Hey Guys! sorry for the late response, @jornh you're right, it was a missing configuration for the nginx reverse proxy!!

What was the configuration made? I am facing the same issue! 
Thanks in Advance.

**Comment by flamber** [comment]
Hi @ananth95 
Which version of Metabase? Can you post your Nginx config?
I would recommend the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ananth95** [comment]
Hi, @flamber,

I am running Metabase and nginx in RHEL
Metabase Version: v0.32.4
nginx version: nginx/1.12.2 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
Nginx Conf
`
server {
    listen  2000 ssl;
    ssl_certificate "***";
    ssl_certificate_key "***";
    location / {
        proxy_pass http://servername:3000/;
    }
  }
}`

PS: this worked fine for sometime and all of a sudden started getting this json error. Metabase is working perfectly fine in http on port 3000.

**Comment by flamber** [comment]
@ananth95 
Latest release is 0.32.10
Seems strange that it all of a sudden stopped working - have you checked if any configurations were changed or any packages were updated?
Looks like you're missing several of Nginx directives, when reverse proxying https. The EBS image uses Nginx, so you might want to [look at it](https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/.ebextensions/metabase_config) as an example.
It's a fairly old Nginx you're using, which I don't even think supports http2, but try something like this:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ""      close;
}
server {
  listen 2000 ssl;
  server_name ***;
  ssl_certificate "***";
  ssl_certificate_key "***";
  location / {
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_pass http://upstream_metabase;
  }
}
upstream upstream_metabase {
  server 127.0.0.1:3000;
}
```
If you need more help, then head over to the [forum](https://discourse.metabase.com/).

**Comment by ananth95** [comment]
Hey @flamber,
proxy_http_version 1.1; fixed it. Thanks for your help. Much appreciated 👍
