### ISSUE TITLE
0.30 Missing X-Ray Setting

### ISSUE THREAD

**Issue by anthonylau** [metabase/metabase#8411]
Is the "X-Rays and Comparison" removed?

in v0.29
![screen shot 2018-08-28 at 11 02 24](https://user-images.githubusercontent.com/4386608/44698284-e607bc00-aab1-11e8-8b34-f0b7d3692da0.png)

in v0.30
![screen shot 2018-08-28 at 11 00 11](https://user-images.githubusercontent.com/4386608/44698312-033c8a80-aab2-11e8-8814-e82e529f779d.png)

**Comment by rjurado01** [comment]
Yes, I don't find the way of hide X-Ray from home page.

**Comment by tomdean** [comment]
Will this feature be optional in an upcoming release? If not, please advise so we can make appropriate plans to migrate off.

**Comment by mazameli** [comment]
The old, original x-ray and comparison features that required these admin settings was removed, and the new x-rays and comparisons were completely rebuilt. 

We're aware that a number of users have been experiencing performance problems when using x-rays in the most recent version of Metabase (0.30.0 and 0.30.1), and we just [merged a fix](https://github.com/metabase/metabase/pull/8428) that we think resolves the underlying problem. This fix will be available shortly in version 0.30.2.

Provided the current performance problem is fixed, I'd be interested to know if any of you who have commented or upvoted this issue would still want to toggle this feature off — and if so, why?

**Comment by anthonylau** [comment]
It's cause performance issue and not useful at the moment for our usage. It would be good if it can be included in permission control, so that we can rollout to limited users.

**Comment by MarkRx** [comment]
I want to turn the feature off. We don't plan to use it and it causes performance problems and crashes our system if used even with 0.30.2. It simply doesn't scale well with large data sets without full database tuning.

**Comment by MarkRx** [comment]
I suppose I should say the database becomes unresponsive. Neither Metabase nor the database crashes.

For example, after hitting "X-ray Compare to the rest" it started to create a dashboard. The dashboard eventually comes up but appears to have created well over 100 questions. While all of this was happening database calls were slow for users which could easily be mistaken as Metabase acting slow to the end user.

The catch is the underlying table is a history table with 5 million rows consisting of 33 columns (6 of which are FKs). It isn't designed for nor optimized for arbitrary column correlations - instead it is meant to be queried with specific filters on targeted indexed fields to obtain state or data on subsets of the whole table. Looking at the questions the automatic dashboard created I can a lot of questions that for a certainty would have been full table scans. Even if the table was fully optimized for any data correlation (which it isn't intentionally as that isn't our use case) the fact remains the dashboard still kicked off over 100 queries.

There are thus several things at play:

1. Automatic dashboards don't scale on tables with many columns (creates huge dashboards with too many questions). Chrome becomes unresponsive because of the amount of data it attempts to display. The database becomes bogged down in queries.
2. Automatic dashboards may not scale well with large tables (some of the questions it creates may have a lot of data to look through)
3. Automatic dashboards work on the assumption that it is okay to correlate any two data fields

I thus would like to be able to hide / turn off x-rays and the ability to automatically create a dashboard comparing everything.

The log fills up with this (tons of calls due to the 100+ questions):

```
09-17 16:42:05 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
--
  | 09-17 16:42:05 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
  | 09-17 16:42:05 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
  | 09-17 16:42:06 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
  | 09-17 16:42:06 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for aggregate fields has changed in MBQL '98. Instead of `[:aggregation 0]`, please use `[:aggregate-field 0]` instead.
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for aggregate fields has changed in MBQL '98. Instead of `[:aggregation 0]`, please use `[:aggregate-field 0]` instead.
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for aggregate fields has changed in MBQL '98. Instead of `[:aggregation 0]`, please use `[:aggregate-field 0]` instead.
  | 09-17 16:42:07 WARN middleware.expand :: The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
  | 09-17 16:42:08 DEBUG metabase.middleware :: POST /api/dataset 200 (1 s) (9 DB calls). Jetty threads: 8/50 (9 busy, 8 idle, 0 queued)
```

**Comment by sbelak** [comment]
Thank you for this in-depth answer!

**Comment by rjurado01** [comment]
We have collections with millions of documents and x-rays queries overburden the database as say @MarkRx and the information they offer it is not useful for us. Why not make this feature optional and configurable?

**Comment by kdoh** [comment]
We went ahead and added the ability to hide triggers in the UI for x-rays in #8706 . It'll be on by default but you'll be able to go in and turn it off once 0.31 ships shortly. When we have time (or if someone is feeling plucky) we should probably also have that setting turn off the actual api side of things too but the lack of ability to trigger them should hopefully alleviate things. Thanks for your feedback everyone!
