### ISSUE TITLE
Allow field filtering for users without access to the database

### ISSUE THREAD

**Issue by catabram** [metabase/metabase#8472]
Hi,
I use 0.30.1 version and I miss an ability for users without access to specific database filter questions based on this database.

E.g., I have a list of transactions: Id, Date, Product, Client, Sum. 
I want to show to the user only aggregated Sums by Products (excluding clients data). Also, I want to allow a user to apply a date filter, which is based on field "Date" from a table that user can not see. Currently, a user has no permission to see this question.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by zDogwatch** [comment]
Same issue here, just posting for visibility. Looking to be able to have field filter access within a saved query, but not grant access to the corresponding table the field filter is directing to.

**Comment by gerardhowell** [comment]
+1

This should really be tagged as a bug, because if you have created a field filter as part of the question, granting the user access to the saved question should be sufficient.

In our questions, we use native SQL queries almost exclusively, often involving field filters on many different tables. This has meant we have need to give all users access to all the underlying database tables, despite not wanting to do so.

**Comment by BenjaminGK** [comment]
Hi there,
Do we have any ETA on solving this issue or getting it prioritized? @salsakran 
We are facing the same issues as others and it is currently the biggest complaint we are getting from our users.
By not having this feature, it, unfortunately, renders permissions useless as we will have to grant full access to all our data in order to solve the issue, which is not really an option for us.

**Comment by flamber** [comment]
While doing other permission testing on Native questions, I stumbled over this.

Since 0.33.2, I can use Field Filters (both dates and category) with a user without data/SQL access in view-only collection (and dashboard), but I'm unsure which PR actually fixed it - perhaps https://github.com/metabase/metabase/commit/d32039aca96f4929ceb77b6ca8ca47ab05557d1e ?

It does give you a date-selector, but it does not show a dropdown list for category-types, just a text input. I'm almost certain I remember seeing an issue open on the dropdown, but I cannot find it.

**Comment by camsaul** [comment]
So I think there's a bit of confusion in this issue. If you don't have data perms for the database, it looks like you can now use field filters without any issue. My understanding of the original issue was that that feature specifically wasn't working, but it appears to have been fixed a while back.

A separate, but lesser issue (reproed in #12219) is you cannot *change* the Field targeted by a filter in a Dashboard without data permissions for that Table. I'm not entirely sure this is the wrong behavior -- if you don't have the permissions to view a Table, it seems like you shouldn't be able to view its Fields in order to select one to filter by. This is the current behavior.

A couple questions @flamber @dacort 
-  Am I understanding the remaining issue correctly?
- Since this seems like a separate, much less significant issue than the one originally described, is this really a P1?
- Does it even make sense that a user with no permissions to view a Table or its Fields should be able to view its Fields for the purpose of changing the field a filter applies to?

**Comment by camsaul** [comment]
Being able to see all the Fields in a Table in order to change a dashboard filter is fundamentally at odds with the way our data permissions work. Here's an example situation:

1. I have a database with a `user` Table and I want to give some of my employees restricted access to it. I create a few questions that filter out sensitive columns like `password` and `salary` and stick them in a Dashboard. I give my employees access to a Collection containing those questions, but no data access
2.  Because those employees don't have full permissions for the `user` Table, they cannot add a `password` or `salary` filter to the Dashboard.

@dacort it seems like what you're asking me to do in #12219 would be a huge security loophole. Here's the alternate version of the scenario:

1. I have a database with a `user` Table and I want to give some of my employees restricted access to it. I create a few questions that filter out sensitive columns like `password` and `salary` and stick them in a Dashboard. I give my employees access to a Collection containing those questions, but no data access
2.  Bad Actor Billy can add a `salary` filter to the Dashboard even though he doesn't have data access permissions
3.  Oops! `salary` only has a few distinct values making it a category. Billy can click the various salaries and determine which employees have which salary respectively. 

@flamber @dacort am I totally misunderstanding this issue? It seems to me like everything is working as it should.

**Comment by flamber** [comment]
Let's close this issue - it was likely fixed in 0.33.2
This issue was originally that you couldn't use Field Filters with no-data-user, it would give permission error.

As for Bad Actor, with read-user, I can add SQL question to dashboard and connect filters, but I cannot do the same for a QB question (`No valid fields`).
So that is by design, since SQL has specified the filters available, whereas QB would allow any column in the table (no matter if the column was part of the result) ?

I've noticed one strange thing that probably should get it's on issue:
With read-user, when going directly (new tab) to a SQL question with Field Filters, then none of the widgets work. If the same question is on a dashboard, then clicking the card title to access the question, will make them work. Maybe a frontend state issue. Bunch of JS errors.

**Comment by camsaul** [comment]
@flamber that does sound like some sort of FE client state issue, let's open it as a separate issue since it doesn't seem related to this original one

**Comment by camsaul** [comment]
@flamber you can filter by columns that aren't in results, for example 

```sql
SELECT id, name
FROM user
WHERE email = 'cam@example.com'
```

so only showing the fields that show up in the results isn't correct behavior. We would want to show all the fields in the table as well as fields from other tables that we can join against since you could in most cases filter against any of those fields. However for security reasons as mentioned above we don't want to do that for users that only have permissions to *view* a query. Adding a filter for a random field can completely change what they're viewing.

**Comment by camsaul** [comment]
@dacort I'm still interested in hearing your thoughts but I think @flamber and I are on the same page that the test you wrote in #12219 isn't testing the same thing originally described here in #8472. As detailed above, I don't think the behavior in that test is something we'd want to implement due to security implications.

It seems the original issue here has been fixed (probably in 0.33.2) so closing as already fixed. If we decide we do want to make changes so #12219 will pass I think we should open a separate issue for that since it's only tangentially related to this one

**Comment by dacort** [comment]
Yea @camsaul, definitely onboard with what you're saying here. The user should be able to use the field filter, but they shouldn't see all of the possible values for that field filter.

The one quirk is that the user gets an infinite spinner when they type in query. But I say we close this one and open another UX issue for that. I'll update #12219.

**Comment by willnaoosmith** [comment]
Any updates on this?
I'm on version 0.38.2 (Latest) and still suffer from this error!

**Comment by flamber** [comment]
@willnaoosmith This issue is closed. You are likely seeing some other issue.

**Comment by abroskin** [comment]
@flamber, I wonder why not allow to take field filtering values from a Metabase model? It shouldn't create any security risk

**Comment by flamber** [comment]
@abroskin Have a look here #23505. This issue is closed. Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
