### ISSUE TITLE
Filter by "Is not" or "Does not contain" excludes Null values in results

### ISSUE THREAD

**Issue by ryan-tangocard** [metabase/metabase#8486]
When using the filter "Is not* or "Does not contain" value it excludes null. 

- Your browser and the version: Version 68.0.3440.106 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases: Redshift
- Metabase version: 0.30.1
- Metabase hosting environment: Beanstalk
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*
1. A table contains a date, amount and department.  The department column can be null
2. Create a question that sums amount and group by department
3. All departments including the null show with the totals
4. Add the filter to exclude a single department using the "Is not" or "Does not contain"
5. The results no longer show the null totals

I understand that this how SQL works in terms of writing != or <> to filter out a value. It will also exclude null values, but in most cases, I would end up doing something like (field != 'value' or field IS NULL) so that I include null values. The other solution is to make sure I don't have any NULL values in any of my data models by adding something like nvl(department, 'not assigned').

**Comment by mvrabel** [comment]
@ryan-tangocard 
This is not a metabase problem.  Try to run this query directly in your prostgres DB.
The rows with NULL department will not show up. https://www.postgresql.org/docs/9.6/static/functions-comparison.html

To put it simply: 
1. You're asking if NULL == <filter department>
2. NULL != <filter department>
3. Rows with NULL in department column will not show up in the result set

**Comment by salsakran** [comment]
closing since as @mvrabel points out, this isn't an MB specific issue

**Comment by mvrabel** [comment]
@salsakran Please wait. Even tough this isn't a MB specific issue it is an user experience issue.
It happend in our company that some of our reports didn't add-up as expected because of this issue. (We fixed it by replacing all NULL values with "N/A" string)

**Why is this a problem**
Scenario: User filters rows by "is column A != xyz "
1. Expected results:  all rows that are non-NULL in column A AND their value is not xyz
2. Real results: all rows which value is not xyz INCLUDING rows that have NULL value
