### ISSUE TITLE
How to compile and run metabase faster?

### ISSUE THREAD

**Issue by edum18** [metabase/metabase#8564]
Hello, so I read the developers guide and noticed that are a lot of build and watch commands and running them takes a long time. do I need to run every command everytime I make a change? I know it watches for changes but the app isn't running itself and to run itself I need to run the .jar which doesnt have the changes. this is what I'm thinking it is, what am I missing?

**Comment by jornh** [comment]
It depends on the type of changes you do. FrontEnd and BackEnd development can be decoupled. So you can develop frontend stuff by using `yarn run build-hot` as described under  
https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#frontend-development if you spin up the backend in a separate console with `lein ring server`

Or for both FE and BE development better in many cases decouple even further and do TDD using the testing tools described in the developer guide. 

I hope that’s what you were asking for?

**Comment by edum18** [comment]
Yes it's what I'm asking for.
But should it start running on localhost:xxxx ? Right now it doesn't.
Outputs: 
```$ yarn run build-hot
yarn run v1.9.4
$ yarn && SET NODE_ENV=hot webpack-dev-server --progress
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
'\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.82s.
```

```$ lein ring server
09-21 09:21:25 INFO metabase.util :: Loading Metabase...
09-21 09:21:31 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance.
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
```
I just noticed that there's the error "Saved credentials encryption is DISABLED for this Metabase instance.". I searched for it and looks like there are some different solutions. Do you know the direct solution?
Thank you.

**Comment by edum18** [comment]
Yes it's what I'm asking for.
But should it start running on localhost:xxxx ? Right now it doesn't.
Outputs:
```
yarn run v1.9.4
$ yarn && SET NODE_ENV=hot webpack-dev-server --progress
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
'\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.82s.
```
```
09-21 09:21:25 INFO metabase.util :: Loading Metabase...
09-21 09:21:31 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance.
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
```
I just noticed that there's the warning "Saved credentials encryption is DISABLED for this Metabase instance.". So I followed the information link and tried `MB_ENCRYPTION_SECRET_KEY='my_key' lein ring server` and looks like it worked to enable the encryption. But it still doesn't run on localhost:3000. Should it be running after that?
Thank you.

**Comment by jornh** [comment]
Hmm, clearly as you were able to do a full build before this your prerequisite tool setup should be ok.

The encryption key setup is not needed. It’s a good practice for production _and_ dev environments with credentials for vital data sources etc. But just for local dev with a throwaway H2 with some sample data you don’t need it. It could _maybe_  be the reason for the error you’re getting, but probably more likely I notice that you have spaces in your path for the migration YAML file.

Another problem source BTW might be that something went wrong with the YAML e.g. a cross-platform line-ending problem or something. I’d suggest starting with a fresh Git clone on a path without spaces. Also if you are on a Win10 edition with WSL or can spin up a Linux VM I’d recommend that. Then you can also get access to running the `./bin/build` script etc. Though, Windows build _have_ improved over time - it used to be that I couldn’t build the frontend due to webpack wasn’t set up to cope with Windows backslash path conventions.

Finally, yes the long wait and occasional stack traces during builds confused me at first as well. For the Clojure build/run with `lein ring server` you should wait for the ready message you normally get when running a fully built jar. Similarly await the frontend `build gets to a state where when you edit frontend source it triggers the hot build. Then you should be able to connect on localhost port 3000 as usual.

**Comment by camsaul** [comment]
Closing this since it sounds like the question has been answered
