### ISSUE TITLE
Pivot table like Excel

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#8572]
### Feature requests: Pivot table like Excel
It will be good for business users if pivot table in custom metrics looks like Excel 
![Excel](https://www.microsoft.com/en-us/microsoft-365/blog/wp-content/uploads/2015/12/Learn-how-to-unpivot-static-tables-in-Excel-2016-3.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dannyeuu** [comment]
@tlrobinson I saw your PR #8552, but I can not see if this feature is planned. It is?

**Comment by mazameli** [comment]
This should be closed when #13662 is closed — i.e. when 0.38 ships.

**Comment by mazameli** [comment]
This is available in 0.38 now! https://github.com/metabase/metabase/releases/tag/v0.38.0

**Comment by dannyeuu** [comment]
Great to hear that, thanks!

**Comment by brunolnetto** [comment]
I can't access the URL content anymore

**Comment by flamber** [comment]
@brunolnetto Which URL? The "Excel" link in the first post? It was just a screenshot from Excel showing pivoting.

Pivot Table has been available since 0.38.0:
https://github.com/metabase/metabase/releases/tag/v0.38.0
https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html#pivot-table
https://www.metabase.com/learn/visualization/how-to-create-pivot-tables.html
