### ISSUE TITLE
Conditional Formatting - Gradient Format Not Working in Safari

### ISSUE THREAD

**Issue by sunny-t** [metabase/metabase#8578]
## Conditional Formatting - Gradient Format Not Working

This issue exists in:
Safari, OSX Yosemite, Postgres, 30.3, Ubuntu 12 - hosting.

The conditional formatting gradient does not work in Safari. Although it works perfectly fine in Firefox and Chrome. 

It also does not work at all for custom defined ranges in any browser.

<img width="209" alt="mb1" src="https://user-images.githubusercontent.com/31738497/45978463-b644c900-c009-11e8-9cc1-f1463a74aa34.png">
<img width="380" alt="mb2" src="https://user-images.githubusercontent.com/31738497/45978464-b644c900-c009-11e8-9dfb-bc1bba962bce.png">

**Comment by kdoh** [comment]
Was just able to reproduce this on our own instance. Seems like in Safari when you select a color range only the first cell in the range will get a style applied. When changing from `Single color` to `Color range` the single settings seem to persist because the range isn't properly replacing it.

Single color seems to behave as expected though.

**Comment by sunny-t** [comment]
+1 Single colour formatting works fine.

**Comment by MarkRx** [comment]
Single color formatting is also not working in some cases though for a different reason - #8478

**Comment by antoine-lizee** [comment]
I would like to make sure the non-browser-specific bug for gradient is also tackled:

**Gradient conditional formatting does not work at all for custom defined ranges in any browser.**

Happy to open a different issue if it's cleaner.
