### ISSUE TITLE
Fields marked as "detailed only" visibility should not show up in filters

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8600]
As an administrator I expected that marking fields with a visibility of "Only in Detailed Views" would prevent them from showing up as being filterable. I drew this conclusion from the wording on the setting as well as the fact that the field will not show up in tables or charts. Others drew this same conclusion. It turns out this is incorrect.

If a field is more or less hidden (except for the special detailed view) why should it show up in a filter?

![image](https://user-images.githubusercontent.com/17504314/46172887-b5fb3680-c272-11e8-863a-4bd205bfd24b.png)

**Comment by mazameli** [comment]
We've found people tend to use "only in detail views" for things like Descriptions. This is a hypothetical scenario, but I could imagine wanting to be able to filter on a Descriptions field with something like a "contains" filter, even though I wouldn't want to see the full description in the table rows.

**Comment by mazameli** [comment]
I don't see us doing this with my current mental model, so closing as won't-fix as it's been open for over a year and hasn't seemed to gain supporters.

**Comment by lindsay-stevens** [comment]
I think this should be a wont-fix because the only-in-detail-views setting is pretty much the only way to tidy up the default table visualisation, short of creating a question for every table (which goes against the "browse data" -> question workflow).

For example in big tables with 50 or so columns, often a subset of 20 or so are the most important / most used, but the rest are still occasionally relevant for filtering or grouping, and a user can easily choose show those extra column(s) by customising the table visualisation settings for that question.
