### ISSUE TITLE
Can't bin latitude/longitude anymore

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8719]
Both on master and on our stats instance, I'm no longer seeing binning options for latitude/longitude columns, and they're not getting binned automatically either. I double checked on both instances that the data model type was correctly set.

![screen shot 2018-10-17 at 4 28 18 pm](https://user-images.githubusercontent.com/2223916/47122001-d1ca7a80-d229-11e8-9a81-14d7c8500fe7.png)

**Comment by mazameli** [comment]
This appears to be resolved in master.

**Comment by mperacchi** [comment]
Using Metabase v0.34 and I can't bin Lat or Lon columns, it's working fine on other numeric columns, any idea why? I've already checked my column data type and they are Latitude and Longitude as expected.

**Comment by flamber** [comment]
@mperacchi Could you create a topic on the forum about this? That's the best place for questions and troubleshooting: https://discourse.metabase.com/
Please include "Diagnostic Info" from Admin > Troubleshooting. You might want to check Logs for errors, when you do a forced sync/scan, since it could be a problem during the process, which is causing it.
