### ISSUE TITLE
Line on area chart

### ISSUE THREAD

**Issue by listentojohan** [metabase/metabase#8721]
Running through Docker on Mac with a connection to a Redshift db.
I want to display a line chart over an area chart. This is not possible when doing and displaying the question - but when I click on the visualisation options (the cog), it displays correctly.

<img width="1711" alt="screen shot 2018-10-18 at 14 35 22" src="https://user-images.githubusercontent.com/3499770/47154960-0995f880-d2e4-11e8-8ab5-c3452f237d2b.png">

Correctly:
<img width="827" alt="screen shot 2018-10-18 at 14 35 30" src="https://user-images.githubusercontent.com/3499770/47154959-0995f880-d2e4-11e8-9bec-dfa462917abd.png">

**Comment by mazameli** [comment]
It looks like a situation where in the first screenshot the green line is stacked above the blue one, and in the second image it's not stacked. I think I recall seeing this issue (area charts defaulting to stacking, but displaying as unstacked in chart settings) before we made some changes in master, but I just checked and this appears to be fixed in master, so I'm going to close this issue. Please reopen if you believe I've misdiagnosed your problem. Thanks.
