### ISSUE TITLE
Slack channel selector in Pulses times out when there are hundreds of channels

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8733]
Reported by one of our larger users, if you have ~1,000+ public channels in Slack, when  you open this dropdown, Metabase reportedly hangs/times-out, with only the #general channel being shown:

![image](https://user-images.githubusercontent.com/2223916/47238256-7a95e880-d396-11e8-9456-458552e92537.png)

Maybe after a certain count of channels is reached, we could display a search box instead of a list, like how we do with category filters.

**Comment by Kelindar** [comment]
We have the same problem with around 10K channels, making it unusable.

**Comment by senior** [comment]
I'll look into fixing this. Looking at the [Slack API](https://api.slack.com/methods), it doesn't look like they support searching, so we would need to implement that ourselves.

One thing that would be pretty easy is we can exclude the members of each channel from the response according to the API docs [channels.list](https://api.slack.com/methods/channels.list). I would guess that makes a 10k channel response quite a bit bigger and we don't even use that data. Since we really only use the channel names we might be able to change how we're parsing the response as well so we don't consume so much memory.

**Comment by tlrobinson** [comment]
@senior We actually do show you user names in the picker.

**Comment by senior** [comment]
@mazameli @Kelindar I have a fix for this issue in https://github.com/metabase/metabase/pull/8786. None of the Slack communities I am a member of are large enough to trigger this issue. Would you be able to test this out?
