### ISSUE TITLE
Import geojson via file, http authenticated link or with cloud service account to bucket

### ISSUE THREAD

**Issue by mumblez** [metabase/metabase#8802]
Hi,

The maps feature allows us to set a http url to a geojson public link:
`URL for the GeoJSON file you want to use`

We have some sensitive geojson files we'd like to use but not make them publicly accessible. I'm not sure on what the process is, e.g. the file link gets sent to the mapping server or you send the file contents but is there a way, ideally, to set a service account and use that in conjunction with a bucket? e.g. on aws / google cloud storage

Another thing, can you describe how each geojson map get's stored / encrypted in the database?
If I wanted to build something that amended the links in the database, where would I look and how should I encrypt?

Thanks

**Comment by salsakran** [comment]
I believe that geojson files need to be reachable by the frontend client. The file is not downloaded and servered from the server. Is that correct @camsaul @tlrobinson ?

**Comment by mumblez** [comment]
some useful links:
https://github.com/metabase/metabase/blob/master/src/metabase/util/encryption.clj - code (encrypt / decrypt)
https://github.com/metabase/metabase/pull/4341 - how it works
possible python library to help - https://passlib.readthedocs.io/en/stable/narr/hash-tutorial.html#usage-example
possible shell commands (openssl / gpg) - https://www.integralist.co.uk/posts/hashing-and-encryption/

if someone alot smarter than me can help with manually decrypting and encrypting values in the db I'd be forever grateful, ideally with python or unix commands.

**Comment by flamber** [comment]
From what I can understand (0.31.2), your custom maps (the URL, field relation and formatting) are stored in the internal Metabase database in the table `settings` in the column `custom-geojson`.

When a user views a question/card/dashboard with a custom map, then the user browser get the data from Metabase via `/api/geojson/:UUID` and not directly via the Custom Map URL.
This is also the reason why #6593 (and probably #5338) is not working from public/shared links, because `/api/geojson` is currently authentication protected.

Note that it's possible to retrieve the Custom Map URL via `/api/session/properties`, so it's not private.
But you could run it through a reverse proxy, so your URL would be `http://localhost:3001/map1.geojson`, which you then do a proxy_pass to `https://example.com/path-to-secret-map.geojson`, and you could even pass auth link via `proxy_set_header Authorization ...` (Nginx example)

**Comment by flamber** [comment]
Closing in favor of #5339
