### ISSUE TITLE
Why don't we use the Presto JDBC driver?

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#8893]
Seems like it would make our lives 10x easier.

https://prestodb.io/docs/current/installation/jdbc.html

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
@raulcarlomagno we're just using the REST API

**Comment by camsaul** [comment]
Background: Presto is a community-contributed driver. AFAIK the JDBC driver didn't exist at the time we merged the Presto driver. I'm guessing they got around to writing one since that time however

**Comment by felipegmarques** [comment]
Hello,

I was thinking about tackling this issue.
I tried to run the test over the current Presto Driver implementation, but I failed.
Could someone give me an overview on how to run the tests or point to a place where I could understand better?

Sorry for the questions that may look simple, but this would be my first issue 😆 
Thanks!

**Comment by wccropper** [comment]
Not only am I interested in this change, but also the ability to provide the needed certs for ssl which might require changes to the connection setup page for Presto/Trino.

**Comment by willtrnr** [comment]
The reason why the API was used originally was because at the time Presto didn't support prepared statement (not only in the JDBC driver, but on the server end as well). There was no way to prevent Metabase form trying to invoke `prepareStatement`, so I went around everything and used the API.

Since contributing the initial version I've been on other projects, but now we're slowly trying to migrate to the yet again Trino rebranded version so I'll probably get back around to this.

**Comment by EBallou** [comment]
+1 on migrating, thanks @willtrnr. with the re-brand of prestosql, the trino current api can still be used with a legacy config value but would like to see the driver leveraged.  ( protocol.v1.alternate-header-name=Presto )  We have two trino deployments active as the config setting makes new trino instances with this value incompatible with the actual current driver.

**Comment by mosabua** [comment]
Just to start this and be simpler in terms of migration I started a PR with a new module for Trino .. https://github.com/metabase/metabase/pull/15160

Maybe we can get that improved and merged.. and then rejig it to use the JDBC driver and you can do whatever else with the legacy prestodb stuff.

**Comment by jeff303** [comment]
Support for Presto JDBC driver coming in #16194.  For now, at least, this will be a separate driver from the current Presto driver (which uses the HTTP interface).  Trino could be still another one, because they are [not client compatible](https://trino.io/blog/2021/01/04/migrating-from-prestosql-to-trino.html#:~:text=Client%20protocol%20compatiblity) with each other.
