### ISSUE TITLE
date formatting

### ISSUE THREAD

**Issue by orthagh** [metabase/metabase#8906]
- Your browser and the version: Chrome 70
- Your operating system: Ubuntu 17.04
- Your databases: Mysql
- Metabase version: 0.31
- Metabase hosting environment: Linux/debian stretch
- Metabase internal database: Mysql

I'm completely unable to change date formatting.

I tried:
- change language of my browser
- force the field to be set as 'date creation'
- resetting formatting to default

nothing worked

![image](https://user-images.githubusercontent.com/418844/48253237-18fdf280-e407-11e8-9a4f-52e410d1e29f.png)

**Comment by mazameli** [comment]
Reproduced this, but only for SQL/native queries. Can you confirm that @orthagh? Are you able to get it to work for queries created with the GUI builder? 

Interestingly, the one setting that _did_ work for me was abbreviating names of months/days.

![native-query-date-formatting](https://user-images.githubusercontent.com/2223916/48576463-7e4f5900-e8c9-11e8-8e16-ce4f37b77fed.gif)

**Comment by sofiarosati** [comment]
Same issue, date formatting is totally uneffective, I'm using Firefox 63 on Ubuntu 18.04.01 with a postgresql database, using native queries.
![schermata del 2018-11-21 17-16-42](https://user-images.githubusercontent.com/44224738/48854387-1eb5e980-edb2-11e8-97cf-6e299ab1967c.png)

**Comment by camsaul** [comment]
@tlrobinson off the top of your head do you know if there's anything missing from the backend response that would be causing this?

**Comment by luissancho** [comment]
This also happens in query builder if you modify the column settings. To reproduce it, create a table query, go to settings and delete a column (any column), then refresh the query. All the dates formatting go away.

**Comment by agoud1993** [comment]
Hi, I'm facing a similar problem of not able to fix the date format in a Bar Chart. 
Metabase version 0.30.1. i want the date in 'YYYY-MM-DD' format so I've written a query 

Select to_char(mondaydate, 'YYYY-MM-dd') as "monday date",

In order to get the format which I was able to get when I want to do the analysis in the table format(please view the 2nd image with the table"). But,
I'm unable to get the 'YYYY-MM-dd' format of date in Bar chart.
Suggestions will be greatly appreciated.
Thanks in advance.

![bar chart date](https://user-images.githubusercontent.com/45699622/49674171-faf3d400-fa3e-11e8-8713-49b392f342b5.PNG)
![table metabase date](https://user-images.githubusercontent.com/45699622/49674399-db10e000-fa3f-11e8-8d72-c9d654923c05.PNG)

**Comment by mazameli** [comment]
@tlrobinson Is this fixed by https://github.com/metabase/metabase/pull/9068?

**Comment by mazameli** [comment]
Confirmed this was fixed by #9068, which was included in [version 0.31.2](https://github.com/metabase/metabase/releases/tag/v0.31.2)

**Comment by maliayas** [comment]
I'm on 0.31.2. I can confirm it works if I modify a specific query's visualization for a date column. However it doesn't work via general Metabase settings. Anybody in the same situation?
