### ISSUE TITLE
Smart Number visualization wording

### ISSUE THREAD

**Issue by ValdarT** [metabase/metabase#8919]
Smart Number visualization displays the previous value as "was ... last day" (or "last week" etc). This is correct when the time filter used includes today / this week, but is incorrect if it doesn't. I think it would be clearer if the label instead stated "was ... day/week before". This way the label would be correct regardless of what the user did with the filters.
A related issue is that when using a native query then the label just says "was ... last". It would be nice if the user could select the label (day/week) in this case. A simpler fix is to just use some generic ending, e.g., "was ... last period".

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sbelak** [comment]
@nkconnor would you mind elaborating a bit on how you'd like to use smart numbers on non-numeric data

**Comment by nkconnor** [comment]
@sbelak - currently no use-case for non-numeric data, but I could see these being applicable to non-timeseries data - e.g. imagine you are Apple and have a dashboard showing sales stats for iPhone Y:

[Dashboard Filter: Q1,Q2,Q3,Q4]

$BB Total Revenue
up 30% vs iPhone X during same time period.

Our current use case is using native queries, and it would be nice to use custom text instead of 'vs last' . We would like to be able to enter 'vs prior month'

**Comment by shaunlebron** [comment]
Thank you!  We added a fix here: https://github.com/metabase/metabase/pull/34587

Before:
> ↑ 20%. was 50 last month

After:
> ↑ 20% vs. previous month: 50

**Comment by shaunlebron** [comment]
Oops, re-opening since the second issue related to the native query is not fixed.
