### ISSUE TITLE
Additional JDBC connection string options for Presto

### ISSUE THREAD

**Issue by raulcarlomagno** [metabase/metabase#8956]
if using presto jdbc, it should exist the option for setting additional jdbc string options like other providers like mysql or postgreSQL have. for example, right now i need to set SSL and SSLKeyStorePath options for jdbc
thanks

**Comment by camsaul** [comment]
Hi @raulcarlomagno (or anyone else interested) I'd gladly merge any PR to add this. Should be pretty straightforward

**Comment by camsaul** [comment]
I was working on implementing this, and I realized... we don't use the Presto JDBC driver!

We do everything via the Presto REST API. Not sure why we're not using the JDBC driver since it would make things a lot simpler -- it might not have existed when we wrote the Presto driver. 

Either way, we can't add additional JDBC connection string options for Presto because we're not using JDBC.

**Comment by camsaul** [comment]
Oh I guess I had in fact realized this in the past. See #8893. That will have to be implemented before we can do anything with this issue

**Comment by jeff303** [comment]
This will be added as part of #16194.
