### ISSUE TITLE
Rolling "group by" windows for time fields

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#8977]
Thanks so much for adding "Smart Number" to 0.31.0. This is a huge improvement for dashboards.

However, it doesn't seem to very usable for "sum of" aggregations by time.

We have a table called "Orders", which has a field called "Order Total", which is in USD. It also has a date, "Ordered At".

I'd like to be able to have a "smart number" showing "Total sales this week" with a meaningful growth percentage. However, with "Group by Ordered At -> Week", we instead start each week at $0 in sales, down 100% and slowly increase from there over the course of the week.

Our existing dashboard instead solves this problem by using a filter to "Past 7 Days (include today)", so it's a rolling 1-week window. But unfortunately this doesn't seem to work with Smart Numbers, which requires a "group by".

I'm able to construct the correct "group by" query in raw SQL, but Smart Number does not recognize the groups as it doesn't know how to interpret the results.

Is there any way to add a "group by" aggregation for date fields which is in rolling 1 day, 1 week, 1 month, 1 year intervals?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ValdarT** [comment]
Another way to approach this problem would be to have an option for Smart Number to calculate the difference "up to current time". So if I open the dashboard, for example, on Tuesday at 15:00 then the comparison would be made against last week up to Tuesday 15:00 (so-called "week-to-date").

**Comment by Go2ClassPoorYorick** [comment]
An additional piece that would be helpful with smart numbers would be "relative" dates- at the moment the smart-number formula just selects the latest "date-time" grouping and compares it to a previous date-time grouping in the dataset.

In order to view something like last week to the week previous to that, you (maybe not counter-intuitively) would filter "the previous two weeks"- this would make sense, as the datetime is looking at two pieces of data, one later to the other and comparing them.

Image showing explained situation, working with two week filter:
![image](https://user-images.githubusercontent.com/33301123/55502075-c1f8f400-5619-11e9-8617-92a7f8a0f74d.png)
Image showing why filtering by one week doesn't work, since there's only one piece in the data-set:
![image](https://user-images.githubusercontent.com/33301123/55502146-e8b72a80-5619-11e9-8f39-36703a59a74f.png)

But this actually works detrimentally for dashboards- If I want to view a smart number for last weeks data, I filter my smart number (say hours worked) by "previous two weeks", and I can repeat that for any time-dependent single numbers to display last week to the week before, which sounds well and good- but any charts/non single number cards break using two weeks- for example, a list of employees working last week grouped by employee for hour breakdown- has to use a different, "previous one week" filter, or I'm going to see two weeks of data. This may be minor, and mitigated by using two separate filters that are manually set on the dashboard, but it reduces the usefulness of a single filter- previous one week.
![image](https://user-images.githubusercontent.com/33301123/55504622-38e4bb80-561f-11e9-9f7b-e7139ae7228e.png)
![image](https://user-images.githubusercontent.com/33301123/55504650-4b5ef500-561f-11e9-9817-1e378087fd4c.png)

I'm not quite sure of the most practical way to fix this issue- the two filters is a workaround, but having the ability to adjust how filters are applied to custom questions/native query field filters would possibly be a start- Possibly a toggle for custom questions to apply an offset, maybe a impromptu "variable" field with a specific on custom questions, but with the ability to apply math/time functions against it.

This could show up as a "datetime", "number", "string" field in the dashboard when trying to apply filters, as it doesn't just apply to date and smart numbers.

- Say you wanted a dashboard that shows three sets of data, taken from a list of locations and their distance from a specific spot:

        1. Locations within 1/3 of your max traveling distance, i.e. "Preferred Locations"
        2. Locations within 3/4 of your max traveling distance but further than 1/3, i.e. "Inconvenient Locations"
        3. Locations that are at or below your max traveling distance, but above 3/4. i.e. "Unreasonable Locations"

Doing such a thing with a "custom query" does not appear possible in a dashboard, and it's not easy to calculate in a custom query itself- you could say you had a distance of "3", and then by hand filter by "Distances between 0 and 1", but you'd be recalculating this by hand for each question, and you'd have to enter it into each query as well. Instead, an option for a filter could look like the more traditional:

(for the preferred locations):
`Locations.Distance <= {{variablename}}/3 || Locations.Distance > 0` 
(the or is technically pointless, your dataset in this example shouldn't have negatives... but it could)

while "inconvenient locations" could look like the uglier:
`Locations.Distance <= ({{variablename}}*.75) && Locations.Distance > ({{variablename}}/3)`

After setting up your question, the field filter {{variablename}} would appear as a selection box on the filter screen of the dashboard for that question.
