### ISSUE TITLE
Ability to configure row limit of tables in pulses

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8984]
As mentioned in https://github.com/metabase/metabase/issues/3894, sometimes our users would like to have more than 20 rows included in a table in a pulse, possibly [configured at the Pulse-level](https://github.com/metabase/metabase/issues/3894#issuecomment-378512335).

**Comment by nileshtrivedi** [comment]
This is where the limits are currently hard-coded: https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render.clj#L42-L43

@mazameli How about having this fallback flow? Pulse parameters -> Environment vars -> Hard-coded values in source. This enables admins to override `rows-limit` and `cols-limit`using envvars and users still being able to customize it per pulse?

**Comment by nileshtrivedi** [comment]
@mazameli @camsaul @senior I'm trying to implement this in my fork (and hopefully merge in upstream). Does this sound like a good plan?

- Add `max_rows` and `max_columns` as non-nullable columns to `pulse_card` table with default values as 20 and 10 respectively. The migration will populate these for all existing rows.
- In `pulse/render.clj`, read from these columns instead of using the hard-coded values 20 & 10
- In `PulseEditCards.jsx`, provide number inputs to customize these. I will enforce limits of say 2000 and 50 for sanity.

**Comment by nileshtrivedi** [comment]
I started working on this here: https://github.com/nileshtrivedi/metabase/commit/bdc4ba2e76a034b080cb18d1fdea86cc07ab9548

But I could definitely use some suggestions / reviews from the Metabase core team. 😞

**Comment by sunitakawane** [comment]
I am working on this with @nileshtrivedi, proposing the following changes

- In 000_migrations.yaml, add rows_limit and cols_limit as non-nullable columns to pulse_card table with default values as 20 and 10 respectively. The migration will populate these for all existing rows.
- In pulse/render.clj, read from these columns instead of using the hard-coded values 20 & 10
- In PulseEditCards.jsx, provide number inputs to customize these. I will enforce limits of say 2000 and 50 for sanity.

Here is the PR with tests working https://github.com/PolyglotNetwork/metabase/pull/1
For frontend , here is the proposed design change. Does this sound like a good plan?

![image](https://user-images.githubusercontent.com/10069381/50803598-5ea84000-1310-11e9-8ca6-9d00b232d202.png)

**Comment by nileshtrivedi** [comment]
@mazameli @camsaul See if our approach makes sense and whether the PR can be merged.

**Comment by mazameli** [comment]
@nileshtrivedi Thanks for your enthusiasm in contributing to Metabase. One of our main principles with Metabase is that it needs to be simple, and "just work," so we try to avoid lots of additional options and knobs whenever we can.

For this particular problem, my current thinking is that we want to keep pulse emails from being enormous, and keep pulse creation simple. It's possible that we may simply slightly increase the limit of rows and columns (or expose those as admin environment variables?). 

A more robust solution we might explore in the future would be to have a separate _reporting_ feature or tool, with far more granular control over things like this, along with advanced scheduling controls, etc. But pulses for now should remain a quick, lightweight way to get regular, small updates and alerts. 

We're definitely interested in hearing more examples of how folks are using pulses, though, to inform what we do with them and a possible reporting feature in the future. But for now, I don't see us merging that PR. Thanks again.

**Comment by nileshtrivedi** [comment]
Hi @mazameli, I understand. We took this approach BECAUSE the issue description said "possibly configured at the Pulse-level".  And my comment here https://github.com/metabase/metabase/issues/8984#issuecomment-448125661 asking if this approach was acceptable, was posted a month ago. Tried to reach you folks (on Github, Gitter, Discourse etc) before starting work but didn't get a response.

What's the ideal way to discuss an issue with Metabase team so that our effort is not wasted? We're also looking at implementing https://github.com/metabase/metabase/issues/3846 but haven't started yet.

**Comment by nileshtrivedi** [comment]
@mazameli If we make it possible to override the default rows/column limits with admin environment variables, will that PR be merged?

**Comment by mazameli** [comment]
@nileshtrivedi Yep, apologies for our slow response. We're trying to make a concerted effort to be more responsive to external contributors, but we're still a relatively small team. I think commenting on a github issue with a proposal like you did is the best process.

Regarding configuring this via environment variables, let me bring this up with @metabase/core-developers to make sure we have a holistic opinion on exposing settings like these in general, rather than just pulse settings specifically.

**Comment by nileshtrivedi** [comment]
@mazameli Any decision on this?

**Comment by kdoh** [comment]
Hi there @nileshtrivedi.

Thanks for prodding us again to get to a decision. As you can probably tell from the issue count there are a lot of decisions for us to make :) As much as possible we try to avoid increasing the surface area of knobs and dials in Metabase, even if they aren't literal knobs and dials in the UI. Pulses aren't really meant to do more in depth custom report delivery, they're primarily meant to be quick hits of info for users of Metabase to explore further by logging in and exploring inside Metabase if things seem interesting.

While that's our vision for them, we absolutely understand that folks are doing all sorts of things to try and use them as a more robust reporting tool, including sending data to outside users, but I'm afraid if we keep adding bits and bobs to the Pulses tool we're going to end up with something that isn't particularly well suited for either case.

Our team's process for trying to solve the underlying reporting issues users are hitting would be to gather info and use cases and try to design and build a tool that works well for custom reporting, but I can't say when or even if we'll work on that at this time.

We won't be merging any PRs related to env var customization around pulses because of this, but we do sincerely thank you for offering to take the time to contribute to Metabase. Sorry again for the delay.

**Comment by lkraav** [comment]
Ain't nobody got time to look at half data in email, half in app, work through cognitive load of tracking the diff, every day.

App level configurable max rows value would be a fine 80/20 compromise. I literally would have to start adding an extra tool to the reporting stack.. would very much like to avoid and stay Meta.

Vote to re-open?

**Comment by mazameli** [comment]
@lkraav Hey, Leho. We're looking at addressing this via environment variables: https://github.com/metabase/metabase/issues/4564
