### ISSUE TITLE
New i18n support is great, but still need improvement

### ISSUE THREAD

**Issue by sailxjx** [metabase/metabase#8992]
For example, 「问候」sometime means `fxxk` in Chinese :), use 「你好」will be better. 
<img width="351" alt="screen shot 2018-11-21 at 10 39 14" src="https://user-images.githubusercontent.com/909853/48815699-4d17d280-ed7a-11e8-9bdc-11005d296cda.png">

I wonder who owns the workspace of `metabase.slack.com`, and how to join it.

**Comment by kdoh** [comment]
Oh wow :) Thanks for the heads up @sailxjx. i18n is still definitely a work in progress for us. As non native speakers of most of our languages this kind of feedback is helpful. All of our translation work happens over on [POEditor](https://poeditor.com/join/project/ynjQmwSsGh) so if you're willing your help on fixing that over there, that would be great.

For community discussion we recommend checking out http://discourse.metabase.com

I'm going to go ahead and close this issue since the main thing here can be handled via our translation framework outside of Github. Thanks for chiming in!
