### ISSUE TITLE
Metabase don't respect kubernetes limits

### ISSUE THREAD

**Issue by jalberto** [metabase/metabase#9009]
When using community metabase helm chart, I specify requests/limits for mem/cpu, but doesn't matter which limits I use, metabase always says: `Maximum memory available to JVM: 123.8 MB` crashing after a few minutes because of OOM

Suggestions:
- Add to helm chart optional JVM_OPTS 
- Detect memory limits in kubernetes

**Comment by camsaul** [comment]
What options are you setting?

Try setting them with the env var `JAVA_TOOL_OPTIONS`

**Comment by jalberto** [comment]
Yes, that works, thanks!

Still will be good idea to metabase be able to detect kubernetes limits

**Comment by camsaul** [comment]
Yeah, that's something that would need to be handled by the JVM rather than by Metabase. We don't have control over memory limits once Metabase launches.

With Java 8 they added an experimental option called `-XX:+UseCGroupMemoryLimitForHeap` which will attempt to infer max heap size based on the memory available for the container it's in. I've tried this with Docker and it seemed to work so I'd imagine it would work for Kubernetes as well.

In Java 9+ the option isn't experimental, I don't think it's enabled by default but it's something we might consider adding to our various deployment scripts

**Comment by jalberto** [comment]
Java 10 brings some improvement for container world.
@camsaul may I ask why metabase docker image still in Java8?

**Comment by jalberto** [comment]
That sounds great!

If I am not mistaken, Java10 introduced some improvements related to
containerization
