### ISSUE TITLE
High CPU usage on browser when dashboard auto-refresh is enabled

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#9019]
- Your browser and the version: latest Chrome and latest Firefox
- Your operating system: Windows 7
- Your databases: MySQL
- Metabase version: v0.31.1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*

1. Open a dashboard and enable auto-refresh (no matter which frequency you select).
2. Browser on the client side uses too much CPU forever. It only gets fixed when I disable auto-refresh.

**Comment by flamber** [comment]
I'm seeing the same - I think we're only seeing it because our computers are older than the developers :)
It's specially bogging down a RaspberryPi, which I'm currently playing with.

Having a look at app-main.bundle.js it looks like `this._timer` is being updated by an interval of 100ms, which seems a bit extreme. Even if it was set to 1000ms, then this tiny icon would still have 60 updates per minute.

**Comment by maliayas** [comment]
I was thinking if it was only me :)

P.S. I consider my PC a good one (4 core and 8 GB RAM).

**Comment by paulrosenzweig** [comment]
Resolved by #10505
