### ISSUE TITLE
Dashboard / Question Bug IE11. Not shows details in Bar Graph.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#9038]
## Environment
Your browser and the version: IE11
Your operating system: Windows10
Your databases: Postgres
Metabase version: 0.31.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

## Steps to reproduce
- Create a Question as a Bar graph

## Observed result
- It shows detail for the pie, but not for the bar graph
![graph view detail ko](https://user-images.githubusercontent.com/33416503/49149685-080c1700-f30b-11e8-96f5-2aadaa350a37.JPG)

![graph view detail ok](https://user-images.githubusercontent.com/33416503/49149702-12c6ac00-f30b-11e8-8d70-3b5b8db49c3d.JPG)

Problem 2:
Also, when a dashboard it is embedded, page is freeze and it shows next advice
![image](https://user-images.githubusercontent.com/33416503/50441345-8eac1800-08fa-11e9-8d40-ab23f11c64b7.png)

### Thanks a lot!
-------

**Comment by jlisyc** [comment]
related https://github.com/metabase/metabase/issues/5965

**Comment by jlisyc** [comment]
related https://github.com/metabase/metabase/issues/8195

**Comment by salsakran** [comment]
hello @jlisyc please break out the second problem into a second issue, and provide more context.

**Comment by salsakran** [comment]
@jlisyc is there anything in the javascript console when you try to hover over a bar chart?

**Comment by jlisyc** [comment]
Problem 2 break out on https://github.com/metabase/metabase/issues/9181

**Comment by jlisyc** [comment]
Yes, when hover over a bar it shows
![image](https://user-images.githubusercontent.com/33416503/50507880-9b0dad80-0a7f-11e9-9d14-19f0b548539f.png)

**Comment by flamber** [comment]
This looks to be because IE11 doesn't think `document` is a node, so `contains()` cannot be used on that, but only on sub-nodes, so the solution would be to use `document.body.contains()`.
Looks like that would also resolve #9181, when looking at the screenshot, but only showing 7/12 errors.
https://github.com/metabase/metabase/blob/9096d184e7f92844b7426e67f550622c5f599232/frontend/src/metabase/visualizations/components/ChartTooltip.jsx#L46
https://stackoverflow.com/questions/38582105/javascript-document-contains-not-working-on-ie11

**Comment by paulrosenzweig** [comment]
Fixed in #10993
