### ISSUE TITLE
CSV Downloads should not be limited to 2k rows.

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#905]
This was a regression. It should be possible to download the contents of even a modest sized table (eg, over 2k rows). Luke's been doing this for a while now.

**Comment by shri** [comment]
I'd say one sane measurement is to use Excel row limits before warning--these documents are almost always being opened in a program like Excel. Modern Excel accepts up to 1,048,576 rows.

Then you could warn: "This download contains more rows than the limit most spreadsheet processors can handle--are you sure you'd like to proceed?"

This still might be too high of a number but I know a lot of our use case is around building a report, bringing into Excel.

**Comment by mazameli** [comment]
I think @shri's suggestion is a good one, and I also like @salsakran's UX suggestion. Only tweak I'd add to it is in the confirmation modal for very, very large downloads, we could make them type a confirmation phrase into an input field, like "TERABYTE", in addition to clicking the Yes button.

**Comment by richardkwc** [comment]
As per twitter reply, in our use case we're trying to get an idea of how many times each user has created a particular entry in a database per month e.g. how many users created how many messages in each month, and then want to look at it in excel/Google Sheets. When you do two 'groupings', the resulting csv has multiple rows for each user e.g.

user_id | created_at | count
---|---|---
1 | Jan | 1
1 | Feb | 56
1 | Mar | 80
2 | Jan | 12
2 | Mar | 45
etc | etc | etc

You could reduce the number of rows if it displayed instead:

user_id | Jan | Feb | Mar
---|---|---|---
1|1|56|80
2|12| |45

Although since we have more than 10,000 users, it still wouldn't solve it completely but would work for a greater proportion of cases.

Another one would be, for a table of 'products' (maybe ~18000), we want to export a csv of all the products that have been used at least once and a count of how many times.

I like the two suggestions above to give a bit more room for people to make their decision.

**Comment by tegansnyder** [comment]
This is a request that would be very helpful to have. I agree with the UX approach.

**Comment by agilliland** [comment]
This is implemented by #1496

**Comment by fabioperrella** [comment]
Hi, I'm using the version 0..32.5 and when I try to export a CSV, it is being limited to 2000 rows. 

Is there any configuration to change it or maybe it is a regression?

**Comment by flamber** [comment]
@fabioperrella Yes, it's a regression in the latest 0.32.x releases - it will be fixed in 0.32.6 by #9872

**Comment by anastasiapapa** [comment]
Hey hey, the hard limit of 10K rows that you have had for aggregations in browser display, is still there right? There is no way for the user to adjust this limit somehow?

**Comment by flamber** [comment]
@anastasiapapa Correct, all the limits are hard coded until #4564 is implemented - upvote by clicking :+1:
