### ISSUE TITLE
Format Date to month always shows 1 January

### ISSUE THREAD

**Issue by ilvenini** [metabase/metabase#9057]
Hi all,
i'm using Metabase 0.31.1 on a Data Warehouse built on SQL Server 2017.

I have a table like this, in which i have on a row level (among other fields), day (DataCompleta), first day of month (PrimoGiornoMese) and first day of year (PrimoGiornoAnno):
![image](https://user-images.githubusercontent.com/36055023/49298489-d6877d00-f4bd-11e8-81ff-63973259bd84.png)

What happens is when i choose to aggregate by the first field (DataCompleta) by month, to leverage Metabase datetime formatting (I'm working on this table as a test), every row of that column gets formatted as January
![image](https://user-images.githubusercontent.com/36055023/49298654-40078b80-f4be-11e8-904e-79a481378702.png)

The SQL Code shows that the convert function is using `YYYY-MM-DD` instead of `YYYYMMDD` (my SQL Server is Italian, and it appears that if i convert to `YYYY-MM-DD` SQL Server is inverting days with months, while if i use `YYYYMMDD` is working correctly).

I tried to change the server language to US English using:
`EXEC sp_configure 'default language', 0 ;
RECONFIGURE;`
but still I can't make it work as I intend to.

Has anyone experienced this?

I forgot to mention that I modified the field metadata, to show YYYY/M/D in the admin page, but apparently it's not related.

Thanks a lot,
Andrea

**Comment by notrom** [comment]
I've got the same issue after upgrading to 0.31.1 and it's persisted to 0.31.2.

My data is in SQL Server 2014, it seems to be any question that groups by month gives me January for that year.

If I look at the SQL for the question gives the correct results, so it seems like the query in being built correctly but the UI is reformatting the date (see screenshot):
![image](https://user-images.githubusercontent.com/4504437/49842082-0ec47f00-fe1f-11e8-85ed-3519eae99671.png)

It's impacting anything grouped by month, tables, charts etc. This issue is stopping me from moving to v0.31 in production at the moment. Would love to see a resolution to it.

Thanks

**Comment by mattpera** [comment]
Hi there,

same bug here. Apparently CAST(<string_date> AS datetime) is expecting to get a <string_date> in the YYYYMMDD format or YYYY-MM-DDT00:00:00 in SQL Server (I'm using a 2012 French version). If not, it would convert a 'YYYY-MM-DD' string input to YYYY-DD-MM datetime object...

Hope someone has time to fix this some day!
Thank you for the great job on Metabase anyway!

Thanks,
Matt
