### ISSUE TITLE
Bug: Number showing wrong value when resizing the widget

### ISSUE THREAD

**Issue by steiml** [metabase/metabase#9072]
- Your browser and the version: Chrome 70.0.3538.110
- Your operating system: OX X 10.14
- Metabase version: 0.31.1

*Repeatable steps to reproduce the issue*
1. Create a number widget with the number 23.96553 and a size of 4 by 4
2. Set the number of decimal places to 0: The number will be correctly shown as 24
3. Resize the widget to a width of 3: The number will be incorrectly shown as 23.

Example of the behavior illustrated in the screen cast attached below.
Adding a suffix or choosing a different number of decimal places shows the same behavior.

[number_truncation_issue.mov.zip](https://github.com/metabase/metabase/files/2649206/number_truncation_issue.mov.zip)

**Comment by flamber** [comment]
I can confirm this - 0.31.1 on Firefox 63

**Comment by shaohua** [comment]
Trying to fix this, but the bug is inside the lib:
https://github.com/HubSpot/humanize/blob/master/src/humanize.js#L86

```
      const number = parseInt(input, 10);
```

As you might have realized, parseInt does NOT round, so the line above generates an output of 23 for an input of 23.96553.

To fix it, we should have changed it to 
```
      const number = Math.round(parseFloat(input));
```

However, the lib has NOT been updated in the last 3 years, so a PR might not be helpful.

Alternatively, since this codepath is only activated when the gridsize < 4, we could remove `compact: true` in Scalar.jsx. However,  that has the unintended effect of disabling many other compact formatting options.
```
    const compactScalarValue = isSmall
      ? formatValue(value, { ...formatOptions,  compact: true })
      : fullScalarValue;
```

Considering all the options, and given Humanize lib is only used in several places in the code, it might be worth considering cherry picking the code from the lib into the metabase repo.

That would be a decision up to the metabase team.
