### ISSUE TITLE
Can't set field filters for some particular columns.

### ISSUE THREAD

**Issue by agoud1993** [metabase/metabase#9085]
Are there any suggestions to fix this Bug?
Thanks in Advance!
![metabase error filter](https://user-images.githubusercontent.com/45699622/49673014-0c3ae180-fa3b-11e8-8a5a-a4288f20a88d.PNG)

_Originally posted by @agoud1993 in https://github.com/metabase/metabase/issue_comments#issuecomment-445367297_

**Comment by dyesseyumba** [comment]
Try to remove the equals symbols from your where clause. When you use `field filter` the `where` clause is applied differently as you can see in the documentation [https://metabase.com/docs/latest/users-guide/13-sql-parameters.html](https://metabase.com/docs/latest/users-guide/13-sql-parameters.html). Yous should also use apply your filter as optional parameter.

 Instead of 
```sql
where projectalias = {{projectalias}} and status = {{status}}
```
Use this
```sql
where true 
[[and projectalias {{projectalias}}]]
[[and status {{status}}]]
```

**Comment by agoud1993** [comment]
@dyesseyumba  even If I remove the equals symbol don't know why the table is not identifying the field as a field filter

**Comment by agoud1993** [comment]
I've solved the issue> I just went to the Data Model in the admin panel and to the related database table and set the field variable to category which worked to solve my issue. 

Thanks for your support
