### ISSUE TITLE
Date Filter Between does not contain the last day, (different behavior from previous versions)

### ISSUE THREAD

**Issue by rhnBen** [metabase/metabase#9089]
"Between" date filter is not casting timestamps to date anymore (where the time is not mentioned) and it's causing the users get confused and the reports getting wrong.

- Databases: Postgres
- Metabase version: 0.31.1 & 0.31.2
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: H2

-it happens when using custom queries

**Comment by Jyggafey** [comment]
A similar issue, most likely related, affecting the query builder:
If you use a date filter (e.g. "On") and nothing else on a table with a timestamp column, it works as expected:
`WHERE CAST("dwh"."orders"."date_placed" AS date) = CAST(? AS date)`

When i add any second filter:
No CAST is applied:
```
WHERE ("dwh"."orders"."date_placed" = ?
   AND "dwh"."orders"."status" = ?)
```
And no results returned since it is defaulting to 00:00 for the selected day to compare with the timestamp column.

**Comment by flamber** [comment]
@Jyggafey It sounds like you're experiencing #9288 - I'm not sure if they're related.

**Comment by flamber** [comment]
Closing in favor of #10824
