### ISSUE TITLE
Language setting doesn't show English when selected because it is the default

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#9098]
Hi,
With the latest release Metabase suddenly switched to German, but I am not able to change it back to English in the settings. For some reason, I can choose every single language that is listed in the dropdown, but not English...

Also, I have seen in other issues that the browser language should also be set, which it is, in English - still no change, Metabase shows up in German.

Thanks for looking into this and fixing it!

Your browser and the version: Chrome Version 71.0.3578.80 
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.31.2
Metabase hosting environment: Heroku

**Comment by nroi** [comment]
I assume you mean the dropdown menu in General Settings -> language? If so, it seems this is not a bug, but intended behavior, since it states:

> The default language for this Metabase instance.This only applies to emails, Pulses, etc. Users' browsers will specify the language used in the user interface.

Perhaps the dropdown doesn't show english after selecting it simply because that is the default.

But I agree that the change introduced with the most recent version is not ideal, there should be an option to set a default language for the interface and use this language regardles of the users' browser setting. Only rudimentary english skills are required to understand metabase, while translations introduce new problems:
- I have my browser set to english, my coworkers have it set to german. This makes it difficult for me to explain to them how to use metabase.
- Using the most widely used language (english) makes it easier to google error messages.
- Some translations are wrong ("Wie ist es gehen, John?"), and leave a bad first impression when I introduce metabase to coworkers.

**Comment by tlrobinson** [comment]
@HelenMertes I think this is just a UI bug. If the language setting is blank it defaults to English.

Separately, I do think we should have an option to toggle between using the user's browser settings vs forcing all users to use the instance language. That's covered by #8384.

**Comment by naviat** [comment]
I got this bug too. Only default language (Vietnamese - local) and then cannot change to English. There is any solution?

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
