### ISSUE TITLE
Customize the SQL created by Field Filters

### ISSUE THREAD

**Issue by NathanDalley** [metabase/metabase#9155]
I would like finer control of the SQL created by the field filters.

A Date Range field filter 
`WHERE {{ date_range }}`
Might create the line of SQL :
```
WHERE
  timestamp_trunc(CAST(`order_data.ordered_items`.`completed` AS timestamp), day) BETWEEN 
  timestamp('2018-12-01T00:00:00.000Z') AND timestamp('2018-12-04T00:00:00.000Z')
```
I would like to manipulate that start date and end date before the query is executed.
for example:
```
WHERE 
  timestamp_trunc({{date_range.field}}, day) BETWEEN {{date_range.start}} AND {{date_range.end}}
```

This is because I'm trying to query my UTC data from from the users timezone.

To make this work properly and query [only the correct partitions](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#pruning_limiting_partitions), I need to transform the date range.  
(time_offset = +10)
```
{{date_range.field}} BETWEEN 
    timestamp_SUB({{date_range.start}}, INTERVAL {{time_offset}} HOUR) 
    and 
    TIMESTAMP_SUB(TIMESTAMP_ADD({{date_range.end}}, INTERVAL 1 DAY), INTERVAL {{time_offset}} HOUR)
```

**Comment by orware** [comment]
I would add to this one as well...just being able to define custom SQL for a field filter would be nice (or tying it to a special question already created for the purpose).

Possibly using something that fits the typical dropdown <select> HTML tag pattern (returning a result that has two columns: one for the actual value you want used in the query and a second for the way you want it to be displayed) would be nice.

I just tried creating a Field Filter right now and it's making me navigate our list of schemas, pick a table, but doesn't quite seem to work the way I'd like it to and we have other dashboards created that used field filters and they aren't as friendly for users since you have to know what you want to search for ahead of time rather than being able to quickly pick from what is likely (in most cases) a short list of values you want to be selected from.

**Comment by flamber** [comment]
Closing in favor of #4509/#3156
Related #3324
