### ISSUE TITLE
Field Type - Deletion Timestamp

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#9202]
Similar to how there are the following field types listed under **Data Model**:

![image](https://user-images.githubusercontent.com/246103/50629452-8a07e500-0f34-11e9-84c9-4fd8dd91f527.png)

It'd be good to have the same applied for Deletion columns.

**Comment by MarkRx** [comment]
Personally I think the business use case should not be defined in a column type as there are too many possibilities to enumerate. Instead the column type should just be a type and nothing else. I have many columns that don't fit any of the predefined available use cases so am forced to not set a special type. I would prefer the business cases be removed from the types in favor of direct types.

**Comment by jbrooksuk** [comment]
@MarkRx I understand, but if Metabase is going to have field types for "Share" and stuff, then why not deletion data?

**Comment by flamber** [comment]
@jbrooksuk That's true, but it would be even greater if they were generic types. I have a huge custom dental system (with the worst data structure imagined) and many of the tables are without a column type, since none of the direct types apply.
I would very much appreciate what @MarkRx is proposing, but I'm not quite sure if it conflicts with how Metabase functions (I'm guessing the direct types has some relation to how x-rays works).

**Comment by salsakran** [comment]
@MarkRx one of the explicit goals of the project is to capture as much type info as possible and use it in smart places. X-Rays is our first big attempt in this, but there will be more. 

This is less "business types" and more semantic metadata, and deletion is definitely something we'd be interested in getting a grip on, and eg, automatically recognizing soft-deletes.
