### ISSUE TITLE
Line settings for changing thickness and/or pattern

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#9255]
In line chart visualization - option to change the thickness or pattern (dashed, dotted etc) of line for individual series, to make a certain series stand out.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by vi-vsn** [comment]
Also, it doesn't make sense how if you resize a "number" visualization to be smaller - it starts to round (removing decimals) or even abbreviate (turning 2,000 into 2K) the number without this being an option that the user can control. In many cases the font size used for the number should simply become smaller enough to fit.

**Comment by flamber** [comment]
Have a look at these related issues and vote :+1: on the ones that sounds similar to your request:
- Number font color and background color #5760
- Number font size and rounding #4369

**Comment by mchip22** [comment]
line styles would be great.  dashed/dotted lines for example

**Comment by Thossine** [comment]
I up voted this issue.
More than being cool, styling chart must be an option nowadays
Best regards

**Comment by EuanKirkhope** [comment]
Just to add, the option to have no line, just the dots. 

I was looking to make a visualisation to show events on a conveyor system, x=time, y=conveyor position.  with 1 series being a line series, and up to 'n' other series that were dot all series.  Each a different filled color or shape even.

Ideally with each series having its own time column, so that I don't have to truncate all the event times into buckets.  Bucketing would then mean tooltips showed the wrong time.  So an option to split multi series to have own x axis time column would be great also.  Currently if I could do dots I would need to do each event type as a separate graph then combine on the dashboard with add multi-series... :)

**Comment by kulyk** [comment]
Implemented in #42043, will be available in Metabase v50
