### ISSUE TITLE
bad links give status 200

### ISSUE THREAD

**Issue by Zhann** [metabase/metabase#9277]
### Bugs
Funny story. Our metabase server got accidentally added to our load balancer (don't ask), causing 503's all over the place. We have a health check url, but it always returned 200 on metabase. Apparently when you ask for a page that can't be found, it throws `200 OK`.

I'd argue that this should be a 404, right?

<img width="1075" alt="schermafbeelding 2019-01-16 om 22 55 03" src="https://user-images.githubusercontent.com/719108/51281346-689e0300-19e2-11e9-835a-d9b80e550b60.png">

**Comment by tlrobinson** [comment]
This is due to Metabase being a single-page application. Most URLs (except `/api/*` and `/app/*`) just return the initial HTML page which loads the frontend application, which *then* loads the required resources from `/api/*`. Only then do we find out if a resource doesn't exist.

Typically to solve this in a generic way you'd implement server-side rendering which serializes the initial DOM and Redux store, but our backend is Clojure so that may be difficult (though theoretically possible using the JavaScript engine included with Java)

I'm not sure it's worth fixing.

**Comment by flamber** [comment]
There's a separate health check URL, which should be used `/api/health`
Closing, as this would require a lot of code to apply everywhere and is not worth the effort.
