### ISSUE TITLE
Huge metadata size crashes browser 

### ISSUE THREAD

**Issue by smee** [metabase/metabase#9281]
Hi! I have a problem with a rather big relational database (MySQL) comprising about 170 tables with about 1500 columns each, 240.000 columns overall. The size of the metadata alone (86MB JSON) kills my browser. due to quickly running out of memory. Hiding tables doesn't reduce the metadata at all.

Is there a way to get metabase to completely ignore tables? I don't need those big tables, just a few smaller ones. Could I create the special `_metabase_metadata` table to make Metabase only see the tables I want to analyze?

**Comment by flamber** [comment]
@smee 
You could create a MySQL user that only has permissions to see the tables you want.
In Metabase database settings, you can configure "This is a large database..." and then manually sync things, but I don't think it will solve your issue because of the amount of columns in each table.

**Comment by smee** [comment]
@flamber Thank you! Creating a dedicated user that has only SELECT permissions to the relevant subset of tables works like a charm. Metabase only sees these tables, everything works as expected.

**Comment by lindsay-stevens** [comment]
@flamber at least for Postgres (and probably MySQL too) this won't work because Metabase sync looks at the database catalog to find tables, but doesn't check if the user it's connecting as has permissions. So you get all tables regardless of database permissions (summarised in #8045, [here](https://github.com/metabase/metabase/issues/8045#issuecomment-406932745)). And there is no way to tell sync to never look at certain tables / schemas - although you can mark tables as "hidden" afterwards, this "hidden" data is still returned by many metadata endpoints.

@smee I have the same crashing issue, in Chrome 71 using Metabase v0.28.6. The path to huge metadata is different but the outcome is the same. Actually I wasn't sure if I should report it since my use is beyond the SME analytics use case goals of Metabase, but here we both are. In my case I have 16 relatively large databases, where it's preferred to show schemas as databases, so I've actually got 256 (16*16) schemas worth of metadata hanging around, but 240 of which are marked "hidden".

The crash is reproducible in my case by visiting the data reference then using the same tab to run a few saved and ad-hoc QB questions. The tab's memory usage climbs to 500MB or so at the reference page, then in 100-200MB jumps as I click around, until it reaches Chome's (actually the V8 VM) default memory limit around 1.5GB and the tab crashes. Similar in Firefox 64 but it chugs a while longer before it croaks.

The main issues seem to be:

1. Too much database metadata is being requested where only a small subset is needed.
2. Too much irrelevant JSON / JS / DOM objects are being held without being garbage collected.

In both our cases I think the crashing could be avoided if Metabase queried only the metadata it needs to show at a given time. To walk through problem 1, as it relates to this ticket and how it could be solved:

- At the Data Reference guide page, we only see highlighted tables/segments/metrics
  - Visiting the guide page queries *all* metadata *twice*:
    - Calls `/api/database/metadata` for each database, with all table and field metadata.
    - Calls `/api/database?include_tables=true&include_cards=false` with all table metadata.
    - The vast majority of this data is very unlikely to be used in a given user session.
  - Both above calls exclude tables with `active=false` but includes `visibility=hidden` (a bug?).
    - The difference is, visibility is set by the user, and active is set only by the sync process.
  - At this point only the highlighted tables/segments/metrics should be queried.
- At the "See all tables" page, we see a list of database names and descriptions
  - No table / field info is used yet.
  - At this point the high-level info for all databases should be queried (no table or field info).
- If we explore Database A, the description / points_of_interest / caveats fields are shown.
  - If we only end up looking at Database A, all Database B / C / etc. table / field info is unused.
  - For Database A we've only used database info, no table / field info yet.
  - The same query as above could be used if it includes description / poi / caveats.
- If we look at "Tables in Database A" we see table name / descriptions, again not using any field info.
  - So far for 1 database we've used database / table info, but no field info yet.
  - At this point the table info for the database should be queried.
- If we look at "Table A", we see field name / type / data type, not using description / caveat / interest.
  - Now we're exploring 1 table's fields but might not look at any of the other 50 tables.
  - At this point the field info for the table should be queried.

A hacky workaround that you could try is to use `UPDATE metabase_table SET active = false WHERE visibility_type = 'hidden';`. This should make the tables you marked as hidden not be returned in the metadata calls. However, the next time the Metabase sync runs, it'll switch these back to `active=true` if it finds those tables in your source database. So if you have a cron job triggering your sync runs it'll need to be followed by the `UPDATE` to hide them again. This might not work out though because I'm seeing crashes with (only!) 8MB or so of JSON metadata, nowhere near 86MB.

Another option: try a fork with [this line](https://github.com/metabase/metabase/blob/14dd7d8b3ebf482e2fe2f004fdec038c29d13808/src/metabase/models/database.clj#L138) changed as per the comment to exclude hidden tables.
