### ISSUE TITLE
Run Update Queries in Metabase

### ISSUE THREAD

**Issue by SQLadmin** [metabase/metabase#9293]
Im using metabase for MySQL. Sometimes I want to run update queries via Metabase in questions tab.
But this throwing the below error.

```java.sql.SQLException: Can not issue data manipulation statements with executeQuery().```
Any possibilities to fix this?

**Comment by salsakran** [comment]
We intentionally do not allow any writes in queries in the native query editor. In general, we try to have Metabase work with a read-only connection to a data warehouse, and strongly suggest you set things up that way for security reasons. 

Leaving this open to collect feedback.

**Comment by kag0** [comment]
> strongly suggest you set things up that way for security reasons

I generally agree, but did just encounter a case where it would have been useful to allow anyone with metabase to be able to update data. I was trying to make this into a parameterized question to lower the risk of someone doing something catastrophic. I had granted column level update access to the otherwise read-only role in my database as the other way to contain potential damage.

**Comment by AmirrezaNasiri** [comment]
@nrktkt, Did you find any solution for your need? We faced a similar issue and wanted to have a Metabase-like solution for writing operations to keep things less manual.

**Comment by nrktkt** [comment]
@AmirrezaNasiri no, we never did. I still think that having metabase as read only is a good default (and usually the only way to go because it's hooked up to read replicas typically). But it would be nice to be able to configure a second connection for write access for some users and let the db auth on that control permissions.
