### ISSUE TITLE
Bug: wrong date label displayed on line chart

### ISSUE THREAD

**Issue by Maxhodges** [metabase/metabase#9366]
![image](https://user-images.githubusercontent.com/957271/52174284-ee88bf00-27d4-11e9-896d-afe6378bc56f.png)

The tooltip is correct: it's `2019 1Q`
but in the x-axis label, it shows `2018-Q1` shoud be 2019!

**Comment by azhestov** [comment]
0.32.0 same issue. switch axis to ordinal show correct labels, timeseries display wrong.
server timezone utc, database timezone utc, report timezone utc, browser - local time

**Comment by RomanAbashin** [comment]
possibly same as [#8413](https://github.com/metabase/metabase/issues/8413)

**Comment by mazameli** [comment]
This is fixed in master.

## 0.32.10
![Screen Shot 2019-11-27 at 4 00 19 PM](https://user-images.githubusercontent.com/2223916/69767226-1e240180-1130-11ea-94c0-438551d79de5.png)

## master
![Screen Shot 2019-11-27 at 4 07 21 PM](https://user-images.githubusercontent.com/2223916/69767231-254b0f80-1130-11ea-8e8f-6b76aca253e9.png)
