### ISSUE TITLE
Line + Bar changes do not reflect in renamed questions

### ISSUE THREAD

**Issue by cgopalan** [metabase/metabase#9377]
When an existing question is changed to a Line+Bar chart, the renamed questions do not get the changes.

Suppose we have a question (Test line and bar - original) and another question which is exactly the same but renamed to "Test line and bar - renamed" in a dashboard.

![1](https://user-images.githubusercontent.com/395294/52293707-84435c00-2945-11e9-84fc-7977ded06630.PNG)

If you change the original question visualization by adding a new aggregate column and changing it to a "Line+Bar" visualization, it should reflect on the renamed question. This does not happen.

![2](https://user-images.githubusercontent.com/395294/52293849-da180400-2945-11e9-9a25-6e215e947d25.PNG)

Also, if you click on the renamed question, it takes you to the original question (as it should). But there's no way to change the visualization.

![linebardefect1](https://user-images.githubusercontent.com/395294/52293940-092e7580-2946-11e9-94ed-4467238cf447.gif)
 

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 10
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by MarkRx** [comment]
I think this is because renaming a card changes it's visualization settings and once you do that then any visualization settings made to the original question will not and should not reflect in your card instance.

I'm guessing the query changes are still reflected in the card instance but the UI doesn't expose the ability to add the additional aggregation in the visualization settings. As a result you are unable to add the new count column even though it is there.

**Comment by flamber** [comment]
I've been trying to replicate, but to no success, when @MarkRx replied with the same answer as I would have given.
I've seen something similar, when I change colors on the question, then it didn't reflect those changes on the card, since I had edited the card previous, but when I edit the card and click `Reset to defaults`, `Done` and `Save`, then the card follows the changes done in the question.

**Comment by flamber** [comment]
Closing in favor of #13595
