### ISSUE TITLE
Funnel chart display problems

### ISSUE THREAD

**Issue by zyadsherif** [metabase/metabase#9486]
- Browser chrome 72.0.3626.109
- Your operating system: OS X Mojave
- Your databases: MySQL
- Metabase version: 0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

- Create & save a new chart of type Funnel
- The title is repeated twice
- The chart is overflowing the body of the dashboard it's presented at and most of the times it's cropped which leads to removing the percentages display

![screenshot 2019-02-25 at 12 01 31](https://user-images.githubusercontent.com/1159370/53333257-a5b8b780-38f5-11e9-9913-e6039994a4a0.jpg)

**Comment by flamber** [comment]
Confirmed on 0.31.2 as a card on the dashboard with this query:
```SQL
SELECT 'Registered' AS Step, 31159 AS Count UNION ALL 
SELECT 'Info_first' AS Step, 28372 AS Count UNION ALL 
SELECT 'Info_second' AS Step, 21494 AS Count UNION ALL 
SELECT 'DOI' AS Step, 19317 AS Count UNION ALL 
SELECT 'Verified' AS Step, 12284 AS Count UNION ALL 
SELECT 'Paid' AS Step, 1522 AS Count
```
And looks like it's because it's `LegendHeader` element is not skipped if `hasTitle` like LineBarChart.
https://github.com/metabase/metabase/blob/1aefe8f890d19112b2514bf0f0e1ca276f8034a9/frontend/src/metabase/visualizations/visualizations/Funnel.jsx#L159-L161
