### ISSUE TITLE
Time is showing 24:00 instead of 00:00

### ISSUE THREAD

**Issue by snblitz** [metabase/metabase#9538]
### Bugs

timedate shows 24:xx instead of 00:xx.

- Firefox 66.0b14 (64-bit)
- Debian 9
- Postgres
- Metabase v0.31.2
- hosted in Debian 9
- H2 database

#### Repeatable steps to reproduce the issue*

Set the date in a table  to display in yyyy-m-d h:m:s 24 hour format.
Look at a datetime with the time in 00:xx range.  See 24:xx instead of 00:xx

![SS](https://user-images.githubusercontent.com/4516175/54145907-1da1da00-43ec-11e9-9a58-3e583072945f.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by snblitz** [comment]
flamber wrote:
Hi @snblitz

I can reproduce this on H2 Sample Data on 0.31.2 - I’ve never noticed the “24” before now.
Can you create an issue on this: https://github.com/metabase/metabase/issues/new
This is both a bug and a feature request. I would say that the bug is more important.

**Comment by lenn4rd** [comment]
We're seeing the same bug running the same Metabase version against a Postgres database. The columns are timezone-aware and stored in UTC time in the database; the timestamps are shown as 2019-03-28 24:11 in Metabase.

Let me know if I can provide additional information and help triaging in any way.

**Comment by poorlymac** [comment]
Hi, I have debugged this to the use of "24 hour time from 1 to 24" in moment.js https://momentjs.com/docs/ of the format k:mm rather than using the format H:mm (or as I prefer HH:mm) to get 0 to 24. If you grep through the source k:mm occurs in date.js and column.js. The temporary hack I have done to fix this is to run this SQL on the metabase database UPDATE metabase_field SET settings = REPLACE(settings, '"k:mm', '"HH:mm') WHERE settings LIKE '%"k:mm%';

**Comment by spinus** [comment]
@snblitz did you verify if only 24 is displayed instead of 00 or actually all hours are shifted +1?

**Comment by flamber** [comment]
@spinus This is just a visual formatting issue, not a timezone issue, so nothing is shifted.

**Comment by szsuyuji** [comment]
any updating?
