### ISSUE TITLE
Failed to connect to database: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.

### ISSUE THREAD

**Issue by mapperr** [metabase/metabase#9572]
- Your browser and the version: Firefox 65
- Your operating system: ArchLinux
- Your databases: MySQL
- Metabase version: v0.31.2 Built on 2018-12-05
- Metabase hosting environment: Docker (latest)
- Metabase internal database: H2

*Repeatable steps to reproduce the issue*:
I'm trying to add a MySQL 8 database to my Metabase.
The mysql instance is on docker, hosted on another machine in google cloud

I've tried to connect with a normal user and the root user with no success.

From the metabase logs I get:
```
ERROR metabase.driver :: Failed to connect to database: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
DEBUG metabase.middleware :: POST /api/database/validate 200 (158 ms) (0 DB calls). Jetty threads: 8/50 (3 busy, 4 idle, 0 queued)
```

every time I hit the `Next` button.

I've red about mysql changed default password hashing since a version I don't remember (not sure I got it right), so that a number of clients have trouble connecting to newer instances.

**Comment by flamber** [comment]
Currently MySQL 8's new default authentication is not supported by a lot of clients, so until that time, you would need to use the old `mysql_native_password` method.

There are many ways to change authentication method:
https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

For reference, since Metabase from 0.32 uses MariaDB Connector/J:
https://mariadb.com/kb/en/library/authentication-plugin-sha-256/

**Comment by mapperr** [comment]
ok, got it.
I switched to native auth on the server and all worked fine as usual.

Thank you.
