### ISSUE TITLE
Return to signing jars?

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#9639]
We dropped signed jars in a recent release, mainly because of how long it takes to verify the jar and the fact that it seems like no one actually verifies them in production.

We should probably at least provide a checksum however.

Does anyone feel strongly about signed jars?

**Comment by camsaul** [comment]
Signed JARs don't really offer a lot since it's trivial to remove the signature from them. Switching to HTTPS for downloads was by far the most important thing we could have done since in a sense any file downloaded from https://downloads.metabase.com is signed by our SSL certificate. An additional checksum wouldn't hurt however, SHA1 I think should be sufficient. Of course if a bad actor gained push access to our s3 bucket and swapped our JAR with their own they would presumably be able to swap the checksum if it were listed in metabase.com. So perhaps tweeting the checksum as well when we announce new releases

**Comment by flamber** [comment]
Make http**s** everywhere - also all the links in `/start/` and `/docs/` (other places too?).
Post the checksums with the release notes on Github.

**Comment by camsaul** [comment]
@flamber I changed our servers to redirect all HTTP requests to HTTPS a few months ago so it is HTTPS everywhere now

**Comment by camsaul** [comment]
Here's a SHA1 of Metabase 0.32.1 `197c60d83a9cb9f22a90b14e0e89e5ffa65b0bd6` @salsakran @kdoh put that in the Release notes and tweet™? :interrobang:

**Comment by flamber** [comment]
@camsaul I saw that, which is great, but all links are still http, so they'll only become https after a round-trip, which means it can be mitm'ed.

**Comment by camsaul** [comment]
@flamber true. I'll have to see if there's a way to included [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) and maybe even [Public-Key-Pins](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning) headers on our downloads which live on CloudFront. If so that would help make MITM attacks harder.

I've been fixing HTTP links as I come across them, if you see any it would be a huge help if you want to submit a PR!

**Comment by flamber** [comment]
@camsaul Where is the Metabase website located on Github? Most `/start/` uses http as links.

**Comment by camsaul** [comment]
Oh, sorry @flamber I just realized our repository for our website is private. I can slap together a perl script and fix all the links at once I think

**Comment by camsaul** [comment]
Ok @flamber thanks to your excellent suggestion we are currently doing a find & replace on all links in the website, you should see them shortly when we finish releasing 0.32.1

**Comment by flamber** [comment]
@camsaul You're awesome! That will make everyone in in #3993 very happy.
By the way, you can skip HPKP, since it's a [dead fish](https://www.theregister.co.uk/2017/10/30/google_hpkp/)

**Comment by exabrial** [comment]
What build tool do you use? Maven has the gpg plugin which can sign during the build process. http://maven.apache.org/plugins/maven-gpg-plugin/

**Comment by flamber** [comment]
Closing, since all releases since 0.32.1 has included a SHA256 checksum on Github:
https://github.com/metabase/metabase/releases
