### ISSUE TITLE
No release-branch for 0.32.1 release 

### ISSUE THREAD

**Issue by truekoi** [metabase/metabase#9677]
Hi team, we would like to install new release 0.32.1 but we don't see valid release-branch for it. We wondering out is it something change ?

**Comment by flamber** [comment]
@truekoi I think the development team got a little swamped issues, so 0.32.1 was quickly pushed out to fix some issues. Expect a 0.32.2 very soon.

**Comment by truekoi** [comment]
Thanks for the reply!
 In this case we'll wait

**Comment by flamber** [comment]
@truekoi 
0.32.2 was just released, but it looks like all changes are added to branch `release-0.32.0`
This is what the log says, when starting Metabase 0.32.2:
```
Starting Metabase version v0.32.2 (4480b24 release-0.32.0) ...
```

**Comment by camsaul** [comment]
Our general process is to do all patch releases off of the same major release branch, in this case we’re releasing all 0.32.x releases off of `release-0.32.0` instead of making a new branch for each release. So you can go ahead and use that branch. We also push tags for each release so you can use one of those if you want a specific version.
