### ISSUE TITLE
Translate some messages on pulse notification

### ISSUE THREAD

**Issue by abmj1979** [metabase/metabase#9678]
Hi guys,

There is some way on we can translate this content in english sended in pulse notifications?

I don't locate this string on POEditor project.

![image](https://user-images.githubusercontent.com/22889283/55476771-d45d3880-55ed-11e9-8607-248851679891.png)

Regards

**Comment by flamber** [comment]
Just for reference - from my lack of Clojure knowledge, it seems like there's several strings in `render.clj`, which are not available for translation because they're not wrapped in `(trs "...")`
https://github.com/metabase/metabase/blob/8993c5548cc5c4fb6f4a0a72ece613e3776d6d5a/src/metabase/pulse/render.clj#L485

**Comment by abmj1979** [comment]
@flamber found that file too. I think that could be translate at POEditor project like the other strings.

**Comment by camsaul** [comment]
To mark stuff for i18n you just need to wrap it in a call to `trs` and due to some weirdness with the library we're using we haven't fixed yet in a call to `str` as well in certain cases like this one. So you would want to replace that with

```clj
(str (trs "More results have been included as a file attachment"))
```

and it will go into our PO files and then eventually into PO Editor

**Comment by abmj1979** [comment]
Tks for the tip @camsaul. I'll try this.
