### ISSUE TITLE
Adjust TaskHistory max rows limit based on instance size (e.g. 5k rows limit for Heroku)

### ISSUE THREAD

**Issue by yesthatguy** [metabase/metabase#9688]
I'm running Metabase v0.31.2 on Heroku (trying to upgrade right now but it's pending https://github.com/metabase/metabase-buildpack/pull/7)

We're running with a Professional 2X Dyno because we were getting errors with smaller dynos, but right now our Postgres instance is Hobby Dev.

We don't have a lot of data but recently (after upgrading to 0.31.2) we started getting row limit errors. It looks like the row limit on Hobby Dev is 10,000, and we're now filling this up and exceeding it just because of the `task_history` table.

It would be nice to be able to disable task_history or limit it to many fewer rows so it doesn't fill up the database. We may also pay to upgrade to a bigger database, but if the `task_history` table is the only thing keeping us from running on Hobby Dev, it would be great to be able to keep it trim and keep running on the lighter plan.

**Comment by camsaul** [comment]
@yesthatguy we do actually limit the number of rows in `task_history` to 100,000. We do record quite a lot of things in the Task History table. 

@metabase/core-developers on our stats instance for example we recorded 4,548 tasks yesterday, mostly because the sync process saves every single sync event as a separate row in the task history table. Luckily these all happen in a batched insert at the end, but it's still a lot of rows. This is done mostly for debugging purposes but even with our rather high number of databases we still have about 3 weeks of history and I don't know why we'd need to know that the sync process synced a Table almost 3 weeks ago

I think it would make sense to do a few things 

*  Make sure we handle errors correctly if saving TaskHistory fails -- done in #9723
*  Number of rows of TaskHistory to keep is something that should be configured automatically based on instance size -- Hobby dynos for instance might get a 5k limit so they don't run into errors once the 10k limit is reached
*  Consider consolidating TaskHistory for the sync process so there's not as much noise

**Comment by paoliniluis** [comment]
Closing as we don't officialy support heroku anymore
