### ISSUE TITLE
Update to 0.32.2 - Unable to Login when using reverse proxy

### ISSUE THREAD

**Issue by roemhildtg** [metabase/metabase#9718]
We're running into an issue with authenticating to metabase after upgrading to 0.32.2. 

We're running Metabase behind an IIS reverse proxy. This issue does not occur when hitting localhost:3000 on the local machine. We are running metabase via java -jar. Were there any modifications to the headers required for authentication with metabase in recent versions?

This issue occurs on Firefox 66.0.2 and chrome 73.0.3683

 I can send additional details, just let me know what would be helpful.

**Comment by tlrobinson** [comment]
@roemhildtg We changed the way we set the cookie in v0.32.0. Instead of getting the session ID from the a API call and using JavaScript to set the cookie we now just have the API call return a `Set-Cookie` header.

It's possible your reverse proxy is somehow modifying/removing that header, or it's also possible there's some other issue with how we're setting the cookie.

Can you provide more details about your reverse proxy configuration? Are you "mounting" Metabase at the root path (`/`) or a sub path (e.x. `/metabase`)?

**Comment by roemhildtg** [comment]
We're mounting metabase at `customdomain.com/reports/`. Would this require some sort of cookie configuration? IE set cookie /reports/api?

**Comment by camsaul** [comment]
I don't think including the `path` in the `Set-Cookie` header is really doing that much for us so I'll just remove it and that should fix the issue

**Comment by tlrobinson** [comment]
Confirmed this is a bug in Metabase (verified using https://github.com/tlrobinson/metabase-proxy-examples/tree/master/caddy-non-root-path)

**Comment by camsaul** [comment]
Fixed by #9719

**Comment by roemhildtg** [comment]
Wow! What a quick turnaround. You guys are awesome!

**Comment by jonathanperret** [comment]
The fix in #9719 unfortunately breaks Google authentication (see my comment there). A properly configured reverse proxy that wants to map requests to another path should actually rewrite the `path` attribute in `Set-Cookie` headers. See https://github.com/mholt/caddy/issues/2381 for the feature request in Caddy for example. For IIS, this might be relevant: https://stackoverflow.com/questions/5353861/rewrite-rules-for-response-headers-in-iis-7-replacing-the-cookie-path/5357223
