### ISSUE TITLE
Metabase Admin. Persons. Bug? Number groups shows [0]

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#9753]
### Metabase Admin. Persons. Bug? Number groups shows [0] instead of real number of groups selected

- Your browser and the version: (Firefox 60.0.1,)
- Your operating system: (ubuntu 18.04)
- Your databases: (postgres,...)
- Metabase version: (0.32.5), upgraded from 0.28.6
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (Postgres)

## Information
![image](https://user-images.githubusercontent.com/33416503/57360413-67076f00-717a-11e9-8279-6f60689416e3.png)

---

![image](https://user-images.githubusercontent.com/33416503/57364247-17797100-7183-11e9-981b-9cb4b7cf2381.png)

Only happend when browser is in spanish (ok in english)
When we updated from 0.28.6 to 0.29.3 it's showing correctly the number of groups of a user .
But when we upgrade to 0.30.4 or 0.32.5 it shows [0] instead of real number of groups selected for a person.

-------------------
Thanks for Metabase project!
-------

**Comment by flamber** [comment]
@jlisyc Please close this issue or update it with information.

**Comment by jlisyc** [comment]
Updated

**Comment by flamber** [comment]
I don't understand. Can you provide a screenshot of your issue?
Have you upgraded to 0.32.5? Do you see any errors in the log or browser console?

**Comment by jlisyc** [comment]
Updated. Only happend in browser in spanish

**Comment by flamber** [comment]
Okay, so that's a translation error. Specifically here:
https://github.com/metabase/metabase/blob/595fc00eb9ed9d769d44aed09211a7d75b3ed9a3/locales/es.po#L920-L925
Translations are imported from [POEditor](https://poeditor.com/join/project/ynjQmwSsGh) and I've already [fixed it](https://poeditor.com/projects/po_edit?order=&filter=&id=200535&id_language=152&search=grupo+m%C3%A1s), so it should be part of next release.
Not sure if translations gets pulled for minor releases like 0.32.6 or if you have to wait for 0.33.0.

Please close this issue.

**Comment by jlisyc** [comment]
Thanks a lot!
It's a minor bug, then no problem.

**Comment by flamber** [comment]
Please close this issue :+1:
