### ISSUE TITLE
Question: Does metabase limit # of connections to data source?

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#9803]
As stated. If I have 10 users open 10 different dashboards with 10 different questions on each - does this result in a simultaneous spike of 100 connections opened to the data-source?

In my mind an ideal behavior would be as follows: there's a connection limit configured per data source and questions are queued up until connection becomes available. 

There's an added benefit if it so happens, that while waiting in queue a question was answered by a different connection, then yay - that answer could be re-used to fulfill all relevant requests and remove them from the queue. But even if all queued requests are different, I think avoiding congestion in the data-source will be preferable.

What is the situation as it is currently?

**Comment by camsaul** [comment]
Yup, that’s how it works. There is a per-DB connection limit and questions are queued. In 0.32.x this was made async because in older versions queued queries could tie up and exhaust all web server threads locking up the whole instance. 

In 0.32.4 and older the queuing happens before the query is processed at all, even before cached queries get a chance to be returned. For 0.32.5 I’m working on a fix so cached results are returned right away and queuing happens after the cache gets a chance to return results.

**Comment by vi-vsn** [comment]
Thank you for the answer! Before asking - I made an effort to look for the information but came up empty. Where is that limit configured? Sorry if this is already answered somewhere.

**Comment by camsaul** [comment]
It’s currently only configurable by setting env vars, it’s set to 15 connections per DB. It’s something that we’ll probably make configurable in the future directly in the admin panel,
