### ISSUE TITLE
Personal collection name does not change when changing user name

### ISSUE THREAD

**Issue by gatalec** [metabase/metabase#9863]
Metabase version 0.32.5, default H2 database. Current versions of Chrome and IE. Windows 10 build 1809.

I changed a user's name while logged in as an administrator in the Admin settings | People | Edit User.

The changes did take effect: when I go to All Personal collections, I see that user’s collection with the new name. However if I click on it, below “Our Analytics” it displays "OLD USERNAME Personal Collection"

I logged out and logged in as the user and the same results (old name) appear.

**Comment by paulrosenzweig** [comment]
Thanks for reporting this!

This bug is due to how we copy the user's name directly into the collection's name. I see two potential solutions:

1. Continue copying the user's name into the collection, but give users the opportunity to edit it. 
2. Have personal collections directly pull the name from the user.

I think the second option makes more sense and will feel more consistent to the user. To avoid a brittle view-level solution, I think we'll want to either modify the collection API responses to conditionally overwrite name or issue a second API call in the client to list out users.

**Comment by paulrosenzweig** [comment]
I just dug into this a bit more. There are a lot more places in the API that pass collection names than I had thought. In addition to the index and object endpoint for collections, there are multiple search endpoints and places where a collection's `effective_ancestors` contain collection name for use in breadcrumbs.

Given that surface area, I don't think updating at the API level makes sense. It really complicates the API code on the client, and I think it would create too many unexpected joins if done on the server.

Instead, it seems better to overwrite the collection's name whenever the user's name is updated. That could happen right after [setting the user's permissions](https://github.com/metabase/metabase/blob/master/src/metabase/api/user.clj#L153) and reuse the [logic that originally sets](https://github.com/metabase/metabase/blob/master/src/metabase/models/collection.clj#L1015) the personal collection's name.

That had originally seemed the like wrong choice because it forces us to keep two strings in the database in sync. When possible just having the string in one place and dynamically populating the views is preferable, but here I think the complexity justifies the duplication.

**Comment by lins05** [comment]
Submitted a patch for this in #11379 
cc @paulrosenzweig
