### ISSUE TITLE
new metabase v0.32.6 shasum hashes do not appear to match the metabase.jar from the official download site.

### ISSUE THREAD

**Issue by hushfrog2** [metabase/metabase#9931]
new metabase v0.32.6 shasum hashes do not appear to match the metabase.jar from the official download site.

http://downloads.metabase.com/v0.32.6/metabase.jar

$ shasum -a 256 metabase.jar 
2fcf548076b1d770ebee5bd9d86b399be6ec20fb6a1d46c804e365a328f3cc92  metabase.jar

from the github.com site:
https://github.com/metabase/metabase/releases

SHA-256 checksum for the 0.32.6 JAR:
254a6d6f55cedee950a898907a14aaf257c2fbf97c4a9915abab54d5e67f9854

**Comment by flamber** [comment]
Pinging @camsaul

**Comment by camsaul** [comment]
Just a quick reminder please send security-related concerns to security@metabase.com instead of posting them in GitHub issues 👍 

I actually did two builds of 0.32.6 yesterday. In the first one I realized I built one of the drivers wrong so I did a new build shortly afterward. I didn’t realize that CloudFront was caching the initial build which is why you’re seeing the `2fc` hash instead of the `254` hash. `254` is the "correct" build of 0.32.6 so if you download it again you should see the correct hash.

That being said we will be releasing a 0.32.7 release in the next 10 or 20 minutes to clear up confusion around the two 0.32.6 releases so it's probably easiest to wait a minute and download that instead.

**Comment by camsaul** [comment]
0.32.7 is out
